<?php 
$bancos = isset($_data["todosOsBancos"]) ? $_data["todosOsBancos"] : Array();
 $idioma = new \Utils\PropertiesUtils("saque", IDIOMA);
?>
<div class="col-md-12">
    <div class="row panel-body" id="container-contas-bancarias" style="margin-top: -2px">
        

        <div class="row">
            <div class=" col-xs-12">
            <div class="alert alert-warning">
                <?php echo $idioma->getText("cadastreApenas") ?>
            </div>
            </div>
        </div> 
            <div class="row">
                <div class="col-md-3">

                    <div class="form-group">

                        <label><?php echo $idioma->getText("instituicaoBancariaC") ?></label>
                        <select class="form-control" id="cadastroContaIdBanco" style="width: 100%;">
                            <option value="0">
                                <?php echo $idioma->getText("seleInstiBancariaC") ?>
                            </option>
                            <?php
                            foreach ($bancos as $banco) {
                                ?>
                                <option value="<?php echo $banco->id ?>">
                                    <?php echo "{$banco->codigo}-{$banco->nome}"; ?>
                                </option>
                                <?php
                            }
                            ?>
                        </select> 
                       
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <label><?php echo $idioma->getText("tipoContaC") ?></label>
                        <select class="form-control" id="cadastroContaTipoConta">
                            <option value="<?php echo Utils\Constantes::CONTA_CORRENTE ?>"><?php echo $idioma->getText("contaCorrenteC") ?></option>
                        </select>
                    </div>
                </div>
                <div class="col-md-1">
                    <div class="form-group">
                        <label><?php echo $idioma->getText("agenciaC") ?></label>
                        <input type="text" class="form-control" id="cadastroContaAgencia" maxlength="10" />
                    </div>
                </div>
                
                <div class="col-md-1">
                    <div class="form-group">
                        <label><?php echo $idioma->getText("agenciaDigitoC") ?></label>
                        <input type="text" class="form-control" id="cadastroContaAgenciaDigito" maxlength="2" />
                    </div>
                </div>
                
                <div class="col-md-2">
                    <div class="form-group">
                        <label><?php echo $idioma->getText("contaC") ?></label>
                        <input type="text" class="form-control" id="cadastroContaConta" maxlength="10" />
                    </div>
                </div>
                
                <div class="col-md-1">
                    <div class="form-group">
                        <label><?php echo $idioma->getText("contaDigitoC") ?></label>
                        <input type="text" class="form-control" id="cadastroContaContaDigito" maxlength="2" />
                    </div>
                </div>
                <div class="col-xs-12 col-lg-2">
                    <label>&nbsp;</label>
                    <button type="button" class="btn btn-primary text-center full-width" onclick="salvarConta();" id="cadastroContaSalvar" ><?php echo $idioma->getText("salvarContaC") ?></button>
                </div>

            </div>


        
    </div>
</div>
<br>
<div class="row">
    <div class="col col-md-12">
        
            <div class="table-responsive">
        <table class="table table-stripped table-hover table-condensed table-bordered" style="background-color: #fff; font-size: 10px">
            <thead>
                <br>
                <tr>
                    <th class="text-center"><?php echo $idioma->getText("codBancoC") ?></th>
                    <th class="text-center"><?php echo $idioma->getText("bancoC") ?></th>
                    <th class="text-center"><?php echo $idioma->getText("agenciaDigC") ?></th>
                    <th class="text-center"><?php echo $idioma->getText("contaDigC") ?></th>
                    <th class="text-center"><?php echo $idioma->getText("tipoC") ?></th>
                    <th class="text-center"><?php echo $idioma->getText("statusA") ?></th>
                    <th class="text-center"><?php echo $idioma->getText("ativarC") ?></th>
                </tr>
            </thead>

            <tbody id="viewListaContasBancarias">

            </tbody>
        </table>
            </div>
        
    </div>
</div>

<script>

   

    function salvarConta() {
        $("#cadastroContaFechar, #cadastroContaSalvar").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_CADASTROSALVARCONTABANCARIA ?>',
            method: 'post',
            dataType: 'json',
            data: {
                id: $("#cadastroContaId").val(),
                agencia: $("#cadastroContaAgencia").val(),
                conta: $("#cadastroContaConta").val(),
                agenciaDigito: $("#cadastroContaAgenciaDigito").val(),
                contaDigito: $("#cadastroContaContaDigito").val(),
                idBanco: $("#cadastroContaIdBanco").val(),
                tipoConta: $("#cadastroContaTipoConta").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $(".select-lista-contas-bancarias").html(json.contas);
                        viewListarContasBancarias();
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }

                $("#cadastroContaFechar, #cadastroContaSalvar").prop("disabled", false);
            }
        });
    }

    function modalExcluirContaBancaria(idConta) {
        $("#modalExcluirContaId").val(idConta);
        $("#modalExcluirConta").modal();
    }

    function excluirContaBancaria() {
        $("#modalExcluirContaExcluir, #modalExcluirContaClose").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_CADASTROEXCLUIRCONTABANCARIA ?>',
            method: 'post',
            dataType: 'json',
            data: {id: $("#modalExcluirContaId").val()},
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#modalExcluirContaClose").prop("disabled", false).trigger("click");

                        viewListarContasBancarias();
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#modalExcluirContaExcluir, #modalExcluirContaClose").prop("disabled", false);
            }
        });
    }


    function viewListarContasBancarias() {
        $("#viewListaContasBancarias").html("<tr><td colspan='7' class='text-center' ><img src='<?php echo IMAGES ?>loading.gif' /></td></tr>");
        $.ajax({
            url: "<?php echo URLBASE_CLIENT . Utils\Rotas::R_CONTASBANCARIAS_LISTAR ?>",
            method: "post",
            dataType: "json",
            data: {

            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#viewListaContasBancarias").html(json.html);
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
            }
        });
    }


    function alterarStatusContaBancaria(codigo) {
        $.ajax({
            url: "<?php echo URLBASE_CLIENT . Utils\Rotas::R_CONTASBANCARIAS_STATUS_ALTERAR ?>",
            method: "post",
            dataType: "json",
            data: {
                codigo: codigo
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        viewListarContasBancarias();
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
            }
        });
    }
</script>

