<?php

use Utils\Layout;

Layout::append('metas');
$numero = $_data['numero'];
$mensagem = $_data['mensagem'];
$mensagemManual = (isset($_data['manual'])) ?
        ("Clique <a href='http://dduo.tecnologia.ws/manual/{$_data['manual']}')>aqui</a> para obter mais informações<br><br>") :
        ('');
$url = (isset($_data['url'])) ? ($_data['url']) : ("javascript:history.back();");
?>
<!-- Bootstrap Stylesheet -->
<link rel="stylesheet" href="<?php echo TEMA; ?>bootstrap/css/bootstrap.min.css" media="screen">
<!-- Main Layout Stylesheet -->
<link rel="stylesheet" href="<?php echo TEMA; ?>assets/css/error.css" media="screen">
<title>Estrutura</title>
<!-- Core Scripts -->
<script src="<?php echo TEMA; ?>assets/js/libs/jquery-1.8.2.min.js"></script>
<script src="<?php echo TEMA; ?>assets/js/libs/jquery.placeholder.min.js"></script>
<script>
    function support() {
        var vendorPrefixes = "O Ms Webkit Moz".split( ' ' ),    
        i = vendorPrefixes.length, support = true, 
        divStyle = document.createElement('div').style;

        while( i-- ) {
            for(var a = 0, support = true; a < arguments.length; a++) {
                support = (vendorPrefixes[ i ] + arguments[ a ] in divStyle);
            }

            if( support ) return true;
        }

        return false;
    }
    $(document).ready(function() {
        support( 'Animation' ) && $('#error-digits > span').each( function(i, span) {
            $(span).addClass('bounceInDown');
        });
    });
</script>
<style>
    #detalhes{
        text-align: center;
        width: 768px;
        margin: auto;
    }
</style>
</head>
<body>
    <div id="error-wrap">
        <div id="error-digits">
            <span class="animated"><?php echo $numero[0]; ?></span>
            <span class="animated delay300"><?php echo $numero[1]; ?></span>
            <span class="animated delay600"><?php echo $numero[2]; ?></span>
        </div>  
        <h3><?php echo $mensagem; ?></h3>
    </div>
    <div id="detalhes">
        <p>
            <?php echo($mensagemManual); ?>
            Para retornar ao sistema clique <a href="<?php echo($url); ?>">aqui</a>
        </p>
    </div>
</body>
</html>
