<?php
$dataInicial = new Utils\Data(date("d/m/Y"));
$dataFinal = new Utils\Data(date("d/m/Y"));
$dataInicial->subtrair(0, 0, 30);
$moeda = \Modules\principal\Controllers\Principal::getCurrency();
$deposito = isset($_data["deposito"]) ? $_data["deposito"] : new \Models\Modules\Cadastro\Deposito();
$bancos = isset($_data["bancos"]) ? $_data["bancos"] : Array();

$categorias = (isset($_data["categorias"]) ? $_data["categorias"] : Array());

$configuracao = \Models\Modules\Cadastro\ConfiguracaoRn::get();

$comissao = $configuracao->taxaBoleto;

$colspan = (Utils\Geral::isUsuario() ? "14" : "13");

$idioma = new \Utils\PropertiesUtils("boleto", 'IDIOMA');
$_data["idiomaMenu"] = $idioma;
?>
<style>
    .border-edit {
        border: 1px solid #1c84c6 !important;
    }
</style>
<?php Utils\Layout::append("inspina/metas", $_data) ?>
<?php Utils\Layout::append("inspina/scripts", $_data) ?>
<?php Utils\Layout::append("inspina/menu", $_data) ?>
<?php Utils\Layout::append("inspina/breadcrumb", $_data) ?>
<script src="<?php echo JS ?>highcharts/code/highcharts.js"></script>

<script src="<?php echo JS ?>highcharts/code/modules/exporting.js"></script>
<script src="<?php echo JS ?>highcharts/code/modules/export-data.js"></script>
<!--[if lt IE 9]>
<script src="<?php echo JS ?>highcharts/code/modules/oldie.js"></script>
<![endif]-->
<link href="<?php echo TEMA ?>css/plugins/fullcalendar/fullcalendar.print.css" rel='stylesheet' media='print'>

    
<div>
<br>

    <!-- Main content -->
    <section class="content">
        
        
        <div class="row">
            <div class="col col-lg-12 text-center">
                
                <br><br>
                <button class="btn btn-primary " onclick="listarCategoriasServicos();">
                    <?php echo $idioma->getText("cadastroCategoriaBtn") ?>
                </button>
                <br><br>
                
            </div>
        </div>
        
        <div class="tabs-container">
                <ul class="nav nav-tabs">
                    <?php if (Utils\Geral::isCliente()) { ?>
                    <li class="active"><a data-toggle="tab" href="#tab-1" data-target="#tab-1" aria-expanded="false"><?php echo $idioma->getText("abaBoleto") ?></a></li>
                    <li class=""><a data-toggle="tab" href="#tab-2" data-target="#tab-2" aria-expanded="true"><?php echo $idioma->getText("abaExtrato") ?></a></li>
                    <li class=""><a data-toggle="tab" href="#tab-6" data-target="#tab-6" aria-expanded="false" ><?php echo $idioma->getText("abaCalendario") ?></a></li>
                    <li class=""><a data-toggle="tab" href="#tab-3" data-target="#tab-3" aria-expanded="false"><?php echo $idioma->getText("abaBoletoCategoria") ?></a></li>
                    <li class=""><a data-toggle="tab" href="#tab-4" data-target="#tab-4" aria-expanded="false"><?php echo $idioma->getText("abaBoletoMes") ?></a></li>
                    <li class=""><a data-toggle="tab" href="#tab-5" data-target="#tab-5" aria-expanded="false"><?php echo $idioma->getText("abaBoletoMesCategoria") ?></a></li>
                    <?php } ?>
                </ul>
        
            <div class="tab-content">

                <div id="tab-2" class="tab-pane <?php echo (Utils\Geral::isUsuario() ? "active" : "") ?>"  >
                    
                    <div class="panel-body">

                    <form id="pesquisa">
                        <div class="row">
                            <div class="col col-lg-12">
                                
                                    <?php Utils\Layout::append("mensagem", $_data) ?>
                                    <!-- /.panel-heading -->
                                    


                                        <div class="row">
                                            <div class="col col-md-2">
                                                <div class="form-group">
                                                    <label class="control-label"><?php echo $idioma->getText("dtInicial") ?></label>
                                                    <input type="text" id="dataInicial" class="form-control" value="<?php echo $dataInicial->formatar(\Utils\Data::FORMATO_PT_BR) ?>"/>
                                                </div>
                                            </div>
                                            <div class="col col-md-2">
                                                <div class="form-group">
                                                    <label class="control-label"><?php echo $idioma->getText("dtFinal") ?></label>
                                                    <input type="text" id="dataFinal" class="form-control" value="<?php echo $dataFinal->formatar(\Utils\Data::FORMATO_PT_BR) ?>"/>
                                                </div>
                                            </div>
                                            <div class="col col-md-2">
                                                <div class="form-group">
                                                    <label class="control-label"><?php echo $idioma->getText("status") ?></label>
                                                    <select class="form-control" id="status">
                                                        <option value="T" ><?php echo $idioma->getText("todosOp") ?></option>
                                                        <option value="<?php echo \Utils\Constantes::STATUS_BOLETO_CLIENTE_AGUARDANDO ?>" ><?php echo $idioma->getText("aguardOp") ?></option>
                                                        <option value="<?php echo \Utils\Constantes::STATUS_BOLETO_CLIENTE_FINALIZADO ?>" ><?php echo $idioma->getText("finalizadoOp") ?></option>
                                                        <option value="<?php echo \Utils\Constantes::STATUS_BOLETO_CLIENTE_CANCELADO ?>" ><?php echo $idioma->getText("cancelOp") ?></option>
                                                    </select>
                                                </div>
                                            </div>

                                            <div class="col col-md-2">
                                                <div class="form-group">
                                                    <label class="control-label"><?php echo $idioma->getText("registros") ?></label>
                                                    <select class="form-control" id="nresultado">
                                                        <option value="10" >10</option>
                                                        <option value="20" >20</option>
                                                        <option value="50" >50</option>
                                                        <option value="100" >100</option>
                                                        <option value="T" ><?php echo $idioma->getText("todosOp") ?></option>
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="col col-lg-2">
                                                <div class="form-group">
                                                    <label class="control-label"><?php echo $idioma->getText("filtroGeral") ?></label>
                                                    <input type="text" id="filtro" name="barras" class="form-control"/>
                                                </div>
                                            </div>
                                            <div class="col col-lg-2">
                                                <div class="form-group">
                                                    <label class="control-label">&nbsp;</label>
                                                    <button type="button" class="btn btn-white pull-right full-width" onClick="listarBoletos();"><?php echo $idioma->getText("filtro") ?></button>
                                                </div>
                                            </div>
                                        </div>

                                        
                            </div>
                        </div>
                    </form>
                        </div>
                        <br>
                            <div class="row">
                                <div class="col col-lg-12">
                                    <div class="table-responsive">
                                    <table class="table table-hover table-condensed table-bordered" style="font-size: 10px">
                                        <thead>
                                            <tr>
                                                <?php if (\Utils\Geral::isUsuario()) { ?>
                                                    <th class="text-center">Cliente</th>
                                                <?php } ?>
                                                <th class="text-center"><strong><?php echo $idioma->getText("controle") ?></strong></th>
                                                <th class="text-center"><strong><?php echo $idioma->getText("codBarras") ?></strong></th>
                                                <th class="text-center"><strong><?php echo $idioma->getText("boleto") ?></strong></th>
                                                <th class="text-center"><strong><?php echo $idioma->getText("data") ?></strong></th>
                                                <th class="text-center"><strong><?php echo $idioma->getText("vencimento") ?></strong></th>
                                                <th class="text-center"><strong><?php echo $idioma->getText("dtPagamento") ?></strong></th>
                                                <th class="text-center"><strong><?php echo $idioma->getText("valor") ?></strong></th>
                                                <th class="text-center"><strong><?php echo $idioma->getText("taxa") ?></strong></th>
                                                <th class="text-center"><strong><?php echo $idioma->getText("comentarios") ?></strong></th>
                                                <th class="text-center"><strong><?php echo $idioma->getText("status") ?></strong></th>                                                
                                                <th class="text-center"><strong><?php echo $idioma->getText("comprovante") ?></strong></th>
                                                <th class="text-center"><strong><?php echo $idioma->getText("nf") ?></strong></th>
                                                <th class="text-center"><strong><?php echo $idioma->getText("acao") ?></strong></th>

                                            </tr>
                                        </thead>
                                        <tbody id="listaBoletos" style="background-color: #fff">

                                        </tbody>
                                    </table>
                                    </div>
                                    <br><br><br><br>
                                </div>
                            </div>
                       
                    
                </div> 
                
                <?php if (Utils\Geral::isCliente()) { ?>
                <div id="tab-1" class="tab-pane active">
                    <div class="panel-body">
                        
                        <div class="row">
                            <div class="col col-lg-12">
                                <div class="alert alert-info">
                                <label><?php echo $idioma->getText("infPagamentoBoleto") ?></label>
                                <ul>
                                    <li><?php echo $idioma->getText("txCobradaBoleto") ?> <?php echo number_format($comissao, 2, ",", "")?>%.</li>
                                    <li><?php echo $idioma->getText("pagamentoRealizadoDiaUtil") ?></li>
                                    <li><?php echo $idioma->getText("saldoSeraDebitado") ?></li>
                                </ul>
                                </div>
                            </div>
                        </div>

                        <form id="form-boleto" action="<?php echo URLBASE_CLIENT . Utils\Rotas::R_BOLETOS_SALVAR ?>" method="post" enctype="multipart/form-data">

                            <div class="row">
                                <div class="col col-lg-12">
                                    <div class="form-group">
                                        <label class="control-label"><?php echo $idioma->getText("codigoBarras") ?></label>
                                        <input type="text" id="barras" name="barras" class="form-control" value="" />
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col col-lg-12">
                                    <div class="form-group">
                                        <label><?php echo $idioma->getText("instituicaoBancaria") ?></label>

                                        <select class="form-control select2-selection__rendered" id="cadastroContaIdBanco" name="cadastroContaIdBanco">
                                            <option value="<?php echo \Utils\Criptografia::encriptyPostId(0) ?>"><?php echo $idioma->getText("selecioneBancoOp") ?></option>
                                            <?php
                                            foreach ($bancos as $banco) {
                                                ?>
                                            <option value="<?php echo \Utils\Criptografia::encriptyPostId($banco->id) ?>"><?php echo $banco->codigo . " - " . $banco->nome ?></option>
                                                <?php
                                            }
                                            ?>
                                        </select>   

                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col col-lg-3">
                                    <div class="form-group">
                                        <label class="control-label"><?php echo $idioma->getText("valorLb") ?></label>
                                        <input type="text" id="valor" name="valor" class="form-control" value="<?php echo number_format($deposito->valorDepositado, 2, ",", ".") ?>" />
                                    </div>
                                </div>
                                <div class="col col-lg-3">
                                    <div class="form-group">
                                        <label class="control-label"><?php echo $idioma->getText("vencimentoBoleto") ?></label>
                                        <input type="text" id="vencimento" name="vencimento" class="form-control"  value="" />
                                    </div>
                                </div>
                                <div class="col col-lg-6">
                                    <div class="form-group">
                                        <label class="control-label"><?php echo $idioma->getText("emailNotificacao") ?></label>
                                        <input type="text" id="email" name="email" class="form-control" maxlength="200"  value="<?php echo $email ?>" />
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col col-lg-12 col-xs-12">
                                    <label><?php echo $idioma->getText("anexeFotoBoleto") ?></label>
                                    <div class="form-group">
                                        <div class="fileinput fileinput-new input-group" data-provides="fileinput">
                                            <div class="form-control" data-trigger="fileinput">
                                                <i class="glyphicon glyphicon-file fileinput-exists"></i> <span class="fileinput-filename"></span>
                                            </div>
                                            <span class="input-group-addon btn btn-default btn-file">
                                                <span class="fileinput-new"><?php echo $idioma->getText("selecionar") ?></span>
                                                <span class="fileinput-exists"><?php echo $idioma->getText("alterar") ?></span>
                                                <input type="file" id="arquivo" name="arquivo" >
                                            </span>
                                            <a href="#" class="input-group-addon btn btn-default fileinput-exists" data-dismiss="fileinput"><?php echo $idioma->getText("remover") ?></a>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <div class="i-checks">
                                            <label class=""> 
                                                <div class="icheckbox_square-green" style="position: relative;">
                                                    <input type="checkbox" id="aceitaNota" name="aceitaNota" value="1" unchecked>
                                                </div> <?php echo $idioma->getText("cpfNf") ?>
                                            </label>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label><?php echo $idioma->getText("inserirComentarios") ?></label> <small>(<?php echo $idioma->getText("valorMaxCaracteres") ?><small class="caracteres"></small><small>500</small>)</small>
                                        <textarea type="text" class="form-control" id="comentario" name="comentario" rows="3" maxlength="500" style="resize: none;"></textarea>                                                    
                                    </div>

                                </div>

                            </div>
                                            
                            <div class="row">
                                <div class="col col-lg-11 col-xs-11">
                                    <div class="form-group">
                                        <label><?php echo $idioma->getText("categoriaServico") ?></label>
                                        <select id="idCategoriaServico" name="idCategoriaServico" data-categoria="0" class="form-control">
                                            <option value="<?php echo \Utils\Criptografia::encriptyPostId(0)?>"><?php echo $idioma->getText("selecioneCategoriaServico") ?></option>
                                            <?php
                                            if (sizeof($categorias) > 0) {
                                                foreach ($categorias as $categoria) {
                                                    $selected = ($categoria->id == $boleto->idCategoriaServico);
                                                    ?>
                                                    <option value="<?php echo \Utils\Criptografia::encriptyPostId($categoria->id)?>" <?php echo ($selected ? "selected='true'" : "")?>><?php echo $categoria->descricao ?></option>
                                                    <?php
                                                }
                                            }
                                            ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="col col-lg-1 col-xs-1">
                                    <br>
                                    <button onclick="cadastroCatagoriasServicos('<?php echo \Utils\Criptografia::encriptyPostId(0)?>')" class="btn btn-primary" type="button">
                                        <i class="fa fa-plus fa-1x"></i>
                                    </button>
                                </div>
                            </div>
                            
                            <div class="row">
                                <div class="col col-lg-12">
                                    <br>
                                    <label style="font-size: 15px;"><?php echo $idioma->getText("seraDebitadoSuaConta") ?>  </label> <strong id="valorCreditado2"> <?php echo $valorCreditado2 ?></strong>
                                    <br>
                                    <br>
                                </div>
                            </div>
                                            
                                                

                            <div class="row">
                                <div class="col-lg-4">
                                </div>
                                <div class="col col-lg-2 col-xs-12 text-center m-b-xs">
                                    <a class="btn btn-default full-width" href="<?php echo URLBASE_CLIENT . Utils\Rotas::R_BOLETOS ?>">
                                       <?php echo $idioma->getText("voltarBtn") ?>
                                    </a>
                                </div>
                                <div class="col col-lg-2 col-xs-12 text-center">
                                    <button class="btn btn-primary full-width" type="button" onclick="modalDialogPagar();" id="btn-cadastrar">
                                       <?php echo $idioma->getText("cadastrarBtn") ?>
                                    </button>
                                <div class="col-lg-4">
                                </div>

                                </div>
                            </div>

                        </form>
                    </div>
                </div>
                
                <div id="tab-3" class="tab-pane">
                    <div class="panel-body">
                        
                        <div class="row">
                            <div class="col col-lg-4">
                                <div class="form-group">
                                    <label><?php echo $idioma->getText("dtInicial") ?></label>
                                    <input type="text" id="filtroConsumoPorCategoriaDataInicial" class="form-control"  />
                                </div>
                            </div>
                            <div class="col col-lg-4">
                                <div class="form-group">
                                    <label><?php echo $idioma->getText("dtFinal") ?></label>
                                    <input type="text" id="filtroConsumoPorCategoriaDataFinal"  class="form-control"  />
                                </div>
                            </div>
                            <div class="col col-lg-4">
                                <div class="form-group">
                                    <label><?php echo $idioma->getText("tipoData") ?></label>
                                    <select id="filtroConsumoPorCategoriaTipoData"  class="form-control" >
                                        <option value="A"><?php echo $idioma->getText("dataVencimento") ?></option>
                                        <option value="B"><?php echo $idioma->getText("dataPagamento") ?></option>
                                        <option value="C"><?php echo $idioma->getText("dataCadastro") ?></option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col col-lg-12 text-center">
                                <br>
                                <button class="btn btn-primary" onclick="pieChartCategorias();">
                                    <?php echo $idioma->getText("atualizarGrafico") ?>
                                </button>
                                <br><br>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col col-lg-12" id="pieChartCategorias" style="height: 500px;">

                                

                            </div>
                        </div>
                    </div>
                </div>
                
                
                
                <div id="tab-4" class="tab-pane">
                    <div class="panel-body">
                        
                        <div class="row">
                            <div class="col col-lg-4">
                                <div class="form-group">
                                    <label><?php echo $idioma->getText("dtInicial") ?></label>
                                    <input type="text" id="filtroConsumoPorMesDataInicial" class="form-control"  />
                                </div>
                            </div>
                            <div class="col col-lg-4">
                                <div class="form-group">
                                    <label><?php echo $idioma->getText("dtFinal") ?></label>
                                    <input type="text" id="filtroConsumoPorMesDataFinal"  class="form-control"  />
                                </div>
                            </div>
                            <div class="col col-lg-4">
                                <div class="form-group">
                                    <label><?php echo $idioma->getText("tipoData") ?></label>
                                    <select id="filtroConsumoPorMesTipoData"  class="form-control" >
                                        <option value="A"><?php echo $idioma->getText("dataVencimento") ?></option>
                                        <option value="B"><?php echo $idioma->getText("dataPagamento") ?></option>
                                        <option value="C"><?php echo $idioma->getText("dataCadastro") ?></option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col col-lg-12 text-center">
                                <br>
                                <button class="btn btn-primary" onclick="barChartConsumoPorMes();">
                                    <?php echo $idioma->getText("atualizarGrafico") ?>
                                </button>
                                <br><br>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col col-lg-12" id="barChartConsumoPorMes" style="height: 500px;">
                                
                            </div>
                        </div>
                    </div>
                </div>
                
                <div id="tab-5" class="tab-pane">
                    <div class="panel-body">
                        
                        <div class="row">
                            <div class="col col-lg-4">
                                <div class="form-group">
                                    <label><?php echo $idioma->getText("dtInicial") ?></label>
                                    <input type="text" id="filtroConsumoPorMesPorCategoriaDataInicial" class="form-control"  />
                                </div>
                            </div>
                            <div class="col col-lg-4">
                                <div class="form-group">
                                    <label><?php echo $idioma->getText("dtFinal") ?></label>
                                    <input type="text" id="filtroConsumoPorMesPorCategoriaDataFinal"  class="form-control"  />
                                </div>
                            </div>
                            <div class="col col-lg-4">
                                <div class="form-group">
                                    <label><?php echo $idioma->getText("tipoData") ?></label>
                                    <select id="filtroConsumoPorMesPorCategoriaTipoData"  class="form-control" >
                                        <option value="A"><?php echo $idioma->getText("dataVencimento") ?></option>
                                        <option value="B"><?php echo $idioma->getText("dataPagamento") ?></option>
                                        <option value="C"><?php echo $idioma->getText("dataCadastro") ?></option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col col-lg-12 text-center">
                                <br>
                                <button class="btn btn-primary" onclick="barChartConsumoPorMesPorCategoria();">
                                    <?php echo $idioma->getText("atualizarGrafico") ?>
                                </button>
                                <br><br>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col col-lg-12" id="barChartConsumoPorMesPorCategoria" style="height: 500px;">
                                
                            </div>
                        </div>
                    </div>
                </div>
                
                <div id="tab-6" class="tab-pane">
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="ibox float-e-margins">
                                    <div class="ibox-title">
                                        <h5><?php echo $idioma->getText("lancamentosRegistrados") ?></h5>
                                    </div>
                                    <div class="ibox-content">
                                        <div id="calendar"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                    </div>
                </div>
                
                <?php } ?>
            </div>
        </div>
            
        
        <br><br>
        
        <?php \Utils\Layout::view("categorias_servicos", $_data) ?>
        
</section>
    
    <div class="clearfix"></div>
</div>

<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>
<!-- Full Calendar -->
<script src="<?php echo TEMA ?>js/plugins/fullcalendar/moment.min.js"></script>
<script src="<?php echo TEMA ?>js/plugins/fullcalendar/fullcalendar.min.js"></script>

<script>
$(document).ready(function () {
    
    <?php if (Utils\Geral::isCliente()) { ?>
    pieChartCategorias();
    barChartConsumoPorMes();
    barChartConsumoPorMesPorCategoria();
    initializeCalendar();
    
    
    $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
        if ($(this).attr("href") === "#tab-6") {
            $('#calendar').fullCalendar('render');
        }
    });
    
    $("#filtroConsumoPorCategoriaDataInicial, #filtroConsumoPorCategoriaDataFinal").mask("99/99/9999").datepicker({format: "dd/mm/yyyy"});
    $("#filtroConsumoPorMesDataInicial, #filtroConsumoPorMesDataFinal").mask("99/99/9999").datepicker({format: "dd/mm/yyyy"});
    $("#filtroConsumoPorMesPorCategoriaDataInicial, #filtroConsumoPorMesPorCategoriaDataFinal").mask("99/99/9999").datepicker({format: "dd/mm/yyyy"});
    <?php } ?>    
        
        
    $("#dataInicial,#dataFinal,#vencimento").datepicker({
        format: "dd/mm/yyyy",
        todayBtn: "linked",
        language: "pt-BR",
        orientation: "top left",
        autoclose: true,
        todayHighlight: true,
        toggleActive: true,
    });
    
    $('.i-checks').iCheck({
        checkboxClass: 'icheckbox_square-green',
        radioClass: 'iradio_square-green'
    });

        
    $("#valor").keydown(function (event) {
        $(this).val(currency($(this).val(), 2, 8, event.keyCode));
        calcularValorCreditado();
        event.preventDefault();
    });
    
    $(document).on("input", "#comentario", function() {
        var limite = 500;
        var informativo = " de ";
        var caracteresDigitados = $(this).val().length;
        var caracteresRestantes = limite - caracteresDigitados;

        if (caracteresRestantes <= 0) {
            var comentario = $("textarea[name=comentario]").val();
            $("textarea[name=comentario]").val(comentario.substr(0, limite));
            $(".caracteres").text("0 " + informativo);
        } else {
            $(".caracteres").text(caracteresRestantes + " " + informativo);
        }
    });
        
    $("#cadastroContaIdBanco").select2();
        
    listarBoletos();
        
    $("#form-finalizar").ajaxForm({
        dataType: "json",
        beforeSubmit: function () {
            $("#dialogFinalizarBoletoFechar, #dialogFinalizarBoletoConfirmar").prop("disabled", true);
        },
        uploadProgress: function(event, position, total, percentComplete) {
                $("#progressDocumentsContainer").show();
                var percentVal = percentComplete + '%';
                $("#progressDocuments").width(percentVal);
                $("#progressDocumentsLegend").html("Carregando: "+percentVal + "%");
                },
        success: function (json) {
            try {
                if (json.sucesso) {
                    $("#dialogFinalizarBoletoFechar").prop("disabled", false).trigger("click");
                    
                    listarBoletos();
                    showNotyAlert(json.mensagem, "s");
                } else {
                    showNotyAlert(json.mensagem, "e");
                }
            } catch (e) {
                showNotyAlert(e, "e");
            }
            $("#dialogFinalizarBoletoFechar, #dialogFinalizarBoletoConfirmar").prop("disabled", false);
            $("#comprovante").val("");
            $("#progressDocumentsContainer").hide();
            $("#progressDocuments").width("0%");
            $("#progressDocumentsLegend").html("");
            
        }
    });
    
    $("#form-cancelar").ajaxForm({
        dataType: "json",
        beforeSubmit: function () {
            $("#dialogCancelarBoletoFechar, #dialogCancelarBoletoConfirmar").prop("disabled", true);
        },
        success: function (json) {
            try {
                if (json.sucesso) {
                    $("#dialogCancelarBoletoFechar").prop("disabled", false).trigger("click");
                    
                    listarBoletos();
                    showNotyAlert(json.mensagem, "s");
                } else {
                    showNotyAlert(json.mensagem, "e");
                }
            } catch (e) {
                showNotyAlert(e, "e");
            }
            $("#dialogCancelarBoletoFechar, #dialogCancelarBoletoConfirmar").prop("disabled", false);
            $("#motivoCancelamento").val();
            listarBoletos();
        }
        
    });
        
    $("#form-boleto").ajaxForm({
        dataType: "json",
        beforeSubmit: function () {
            $("#dialogPagarSalvar, #dialogPagarClose").prop("disabled", true);
        },
        uploadProgress: function(event, position, total, percentComplete) {
            $("#progressBoletoContainer").show();
            var percentVal = percentComplete + '%';
            $("#progressBoleto").width(percentVal);
            $("#progressBoletoLegend").html("Carregando: "+percentVal);
        },
        success: function (json) {
            try {
                if (json.sucesso) {
                    $("#dialogPagarClose").prop("disabled", false).trigger("click");
                    
                    showNotyAlert(json.mensagem, "s");
                    $("#dialogConfirmacaoPagamento").modal();
                    limpar();
                    listarBoletos();
                } else {
                    showNotyAlert(json.mensagem, "e");
                }
            } catch (e) {
                showNotyAlert(e, "e");
            }
            $("#dialogPagarSalvar, #dialogPagarClose").prop("disabled", false);
            $("#progressBoletoContainer").hide();
            $("#progressBoleto").width("0%");
            $("#progressBoletoLegend").html("");
            //location.reload();
            
        }
    }, false);
        
    $("#barras").numeric();
    $("#barras").keyup(function () {
        if ($(this).val().length >= 33) {
            //getDadosByBarras();
        }
    });
        
});
    
function listarBoletos() {
    $("#listaBoletos").html("<tr class='text-center'><td  class='text-center' colspan='13'><img src='<?php echo IMAGES ?>loading.gif' /></td></tr>");
    $.ajax({
        url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_BOLETOS_FILTRAR ?>',
        method: 'post',
        dataType: 'json',
        data: {
            dataInicial:$("#dataInicial").val(),
            dataFinal:$("#dataFinal").val(),
            status:$("#status").val(),
            tipoData:$("#tipoData").val(),
            idBanco:$("#idBanco").val(),
            email:$("#email").val(),
            nresultado: $("#nresultado").val(),
            barras: $("#barras").val()
        },
        success: function (json) {
            try {
                if (json.sucesso) {
                    $("#listaBoletos").html(json.html);
                    $("#aguardando").html(json.dados.aguardando);
                    $("#pago").html(json.dados.pago);
                    $("#finalizados").html(json.dados.finalizado);
                    $("#cancelados").html(json.dados.cancelado);
                    
                    $(".btn-popover-comentario").each(function () {
                            let comentario = $(this).attr("data-controle");
                            $(this).popover({
                                html: true,
                                trigger: "focus",
                                container: "body",
                                placement: "top",
                                title: comentario,
                                content: json.popover[comentario]
                            });
                        });
                        
                        
                    $(".boleto-comentarios").each(function () {
                            let motivo = $(this).attr("data-motivo");
                            let comentario = $(this).attr("data-controle");
                            $(this).popover({
                                html: true,
                                trigger: "focus",
                                container: "body",
                                placement: "top",
                                title: comentario,
                                content: motivo
                            });
                        });
                        
                        $(".btn-popover-cancelamento").each(function () {
                            let cancelamento = $(this).attr("data-controle");
                            $(this).popover({
                                html: true,
                                trigger: "focus",
                                container: "body",
                                placement: "top",
                                title: cancelamento,
                                content: json.popover[cancelamento]
                            });
                        });
                        
                        
                    $(".boleto-cancelamento").each(function () {
                            let motivo = $(this).attr("data-motivo");
                            let cancelamento = $(this).attr("data-controle");
                            $(this).popover({
                                html: true,
                                trigger: "focus",
                                container: "body",
                                placement: "top",
                                title: cancelamento,
                                content: motivo
                            });
                        });
                        
                        $(".btn-popover-barras").each(function () {
                            let barras = $(this).attr("data-controle");
                            $(this).popover({
                                html: true,
                                trigger: "focus",
                                container: "body",
                                placement: "top",
                                title: barras,
                                content: json.popover[barras]
                            });
                        });
                        
                        
                    $(".boleto-barras").each(function () {
                            let motivo = $(this).attr("data-motivo");
                            let barras = $(this).attr("data-controle");
                            $(this).popover({
                                html: true,
                                trigger: "focus",
                                container: "body",
                                placement: "top",
                                title: barras,
                                content: motivo
                            });
                        });
                    
                    
                } else {
                    $("#listaBoletos").html("<tr class='text-center'><td  class='text-center' colspan='13'><img src='<?php echo IMAGES ?>loading.gif' /></td></tr>");

                    $("#aguardando").html("0");
                    $("#pago").html("0");
                    $("#finalizados").html("0");
                    $("#cancelados").html("0");
                }
            } catch (e) {
                $("#listaBoletos").html("<tr ><td colspan='13' class='text-center'>"+e+"</td></tr>");
                $("#aguardando").html("0");
                $("#pago").html("0");
                $("#finalizados").html("0");

            }
        }
    });
}

function modalFinalizarBoleto(idBoleto) {
    
    $.ajax({
        url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_BOLETOS_DADOS ?>',
        method: 'post',
        dataType: 'json',
        data: {
            idBoleto:idBoleto
        },
        success: function (json) {
            try {
                if (json.sucesso) {
                    $("#dadosPagamento").html(json.dados);
                    $("#dialogFinalizarBoletoIdBoleto").val(idBoleto);
                    $("#dialogFinalizarBoleto").modal();
                } else {
                    
                }
            } catch (e) {

            }
        }
    });
}

function confirmarFinalizacaoBoleto() {
    $("#form-finalizar").submit();
}

function confirmarCancelarBoleto() {
    $("#form-cancelar").submit();
    
}

function modalCancelarBoleto(idBoleto){
    $("#dialogCancelarBoletoIdBoleto").val(idBoleto);
    $("#dialogCancelarBoleto").modal();
    
}  

    
    
function modalDialogPagar() {    
    $("#dialogPagar").modal();
    
}


function confirmarPagamento() {
    $("#form-boleto").submit();  
    
}
/*
function modalFinalizarBoleto(codigo) {
    $("#dialogFinalizarBoleto").modal();
    $("#form-finalizar").val(null);
    $("#dialogFinalizarBoletoIdBoleto").val(codigo);
}*/

function getDadosByBarras() {
    $.ajax({
        url : "<?php echo URLBASE_CLIENT . Utils\Rotas::R_BOLETOS_BARRAS_DADOS ?>",
        method: "post",
        dataType: "json",
        data: {
            barras: $("#barras").val()
        },
        success: function (json) {
            try {
                if (json.sucesso) {
                    
                    $("#cadastroContaIdBanco").val(json.banco).trigger("change");
                    $("#vencimento").val(json.validade);
                    $("#valor").val(json.valor);
                    calcularValorCreditado();
                } else {
                    showNotyAlert(json.mensagem, "e");
                }
            } catch (e) {
                showNotyAlert(e, "e");
            }
        }
    });
    
}

    function limpar(){
        $("#valor, #email, #barras, #vencimento, #comentario").val("");
        $("#valorCreditado2").html("R$ 0,00");
        $("#cadastroContaIdBanco").select2("val", "");
        $('.fileinput').fileinput("clear");
        $("#comprovante").val("");
    
    }


    function calcularValorCreditado() {
         var valor = ($("#valor").val().length > 0 ? parseFloat(toFloat($("#valor").val())) : 0);

         var comissao = <?php echo number_format($comissao, 2, ".", "")?>; //Precisa trazer a comissao correta


         var resultado = ((valor * comissao / 100));
         var valorDebitado = valor + resultado;
         //$("#valorCreditado2").html("R$ " + resultado.toFixed(2).replace(".", ","));

         $("#valorCreditado2").html("R$ " + mascaraValor(valorDebitado.toFixed(2)));
         //$("#valorDebitado").html("R$ " + mascaraValor(resultado.toFixed(2)));
     }
     
     
     
     
     
 <?php if (Utils\Geral::isCliente()) { ?>    
     function pieChartCategorias() {
         
         $.ajax({
             url: '<?php echo URLBASE_CLIENT  . Utils\Rotas::R_BOLETOS_RELATORIOS_CONSUMOPORCATEGORIA  ?>',
             method: 'post',
             dataType: 'json',
             data: {
                 dataInicial: $("#filtroConsumoPorCategoriaDataInicial").val(),
                 dataFinal: $("#filtroConsumoPorCategoriaDataFinal").val(),
                 tipoData: $("#filtroConsumoPorCategoriaTipoData").val()
             },
             success: function (json) {
                 try {
                     if (json.sucesso) {
                         var data = [];
                         var i = 0;
                         var maior = 0;
                         var iMaior = 0;
                        for (i = 0; i < json.dados.length; i++) {
                            if (json.dados[i].total > maior) {
                                maior = json.dados[i].total;
                                iMaior = i;
                            }
                            
                            var d = [json.dados[i].categoria, parseFloat(json.dados[i].total), false, false];
                            data.push(d);
                        }
                        
                        if (data.length > 0) {
                            data[iMaior][2] = true;
                            data[iMaior][3] = true;
                        }
                         
                        Highcharts.chart('pieChartCategorias', {
                            title: {
                                text: <?php echo $idioma->getText("graficoBoletoCategoria")?>
                            },
                            credits: {
                                enabled: true,
                                href: "<?php echo URLBASE_CLIENT ?>",
                                text: "<?php echo URLBASE_CLIENT ?>"
                            },
                            xAxis: {
                                categories: json.categorias
                            },
                            series: [{
                                type: 'pie',
                                name: 'Valor total R$:',
                                allowPointSelect: true,
                                keys: ['name', 'y', 'selected', 'sliced'],
                                data: data,
                                showInLegend: true
                            }]
                        });
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                
                    showNotyAlert(e, "e");
                }
            }
        });
    }
    
    
    
    function barChartConsumoPorMes() {
         
         $.ajax({
             url: '<?php echo URLBASE_CLIENT  . Utils\Rotas::R_BOLETOS_RELATORIOS_CONSUMOPORMES  ?>',
             method: 'post',
             dataType: 'json',
             data: {
                 dataInicial: $("#filtroConsumoPorMesDataInicial").val(),
                 dataFinal: $("#filtroConsumoPorMesDataFinal").val(),
                 tipoData: $("#filtroConsumoPorMesTipoData").val()
             },
             success: function (json) {
                 try {
                     if (json.sucesso) {
                         var data = [];
                         var i = 0;
                         
                        for (i = 0; i < json.meses.length; i++) {
                            var d = [json.meses[i].mes, parseFloat(json.meses[i].total), false, false];
                            data.push(d);
                        }
                        
                        Highcharts.chart('barChartConsumoPorMes', {
                            chart: {
                                type: 'column'
                            },
                            title: {
                                text: <?php echo $idioma->getText("enviosPorMes")?>
                            },
                            credits: {
                                enabled: true,
                                href: "<?php echo URLBASE_CLIENT ?>",
                                text: "<?php echo URLBASE_CLIENT ?>"
                            },
                            xAxis: {
                                type: 'category',
                                labels: {
                                    rotation: -45,
                                    style: {
                                        fontSize: '13px',
                                        fontFamily: 'Verdana, sans-serif'
                                    }
                                }
                            },
                            yAxis: {
                                min: 0,
                                title: {
                                    text: 'Valor total: R$ '
                                }
                            },
                            legend: {
                                enabled: false
                            },
                            tooltip: {
                                pointFormat: 'Valor total: <b>R$ {point.y:.2f}</b>'
                            },
                            series: [{
                                name: 'Mês/Ano',
                                data: data,
                                dataLabels: {
                                    enabled: true,
                                    rotation: -90,
                                    color: '#FFFFFF',
                                    align: 'right',
                                    format: 'R$ {point.y:.2f}', // one decimal
                                    y: 10, // 10 pixels down from the top
                                    style: {
                                        fontSize: '13px',
                                        fontFamily: 'Verdana, sans-serif'
                                    }
                                }
                            }]
                        });
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                
                    showNotyAlert(e, "e");
                }
            }
        });
    }
    
    
    function barChartConsumoPorMesPorCategoria() {
         
         $.ajax({
             url: '<?php echo URLBASE_CLIENT  . Utils\Rotas::R_BOLETOS_RELATORIOS_CONSUMOPORMESPORCATEGORIA  ?>',
             method: 'post',
             dataType: 'json',
             data: {
                 dataInicial: $("#filtroConsumoPorMesPorCategoriaDataInicial").val(),
                 dataFinal: $("#filtroConsumoPorMesPorCategoriaDataFinal").val(),
                 tipoData: $("#filtroConsumoPorMesPorCategoriaTipoData").val()
             },
             success: function (json) {
                 try {
                     if (json.sucesso) {
                         var data = [];
                         var i = 0;
                        for (i = 0; i < json.grafico.length; i++) {
                            var val = [];
                            var valores = json.grafico[i].totais;
                            var z = 0;
                            for(z=0; z < valores.length; z++) {
                                val.push(parseFloat(valores[z]));
                            }
                            
                            var series = {
                                name: json.grafico[i].categoria,
                                data: val
                            };
                            
                            data.push(series);
                        }
                        
                        Highcharts.chart('barChartConsumoPorMesPorCategoria', {
                            chart: {
                                type: 'column'
                            },
                            title: {
                                text: <?php echo $idioma->getText("graficoEnviosMesCategorias")?>
                            },
                            credits: {
                                enabled: true,
                                href: "<?php echo URLBASE_CLIENT ?>",
                                text: "<?php echo URLBASE_CLIENT ?>"
                            },
                            xAxis: {
                                categories: json.meses
                            },
                            yAxis: {
                                min: 0,
                                title: {
                                    text: 'Boletos por categoria'
                                },
                                stackLabels: {
                                    enabled: true,
                                    style: {
                                        fontWeight: 'bold',
                                        color: (Highcharts.theme && Highcharts.theme.textColor) || 'gray'
                                    }
                                }
                            },
                            legend: {
                                align: 'right',
                                x: -30,
                                verticalAlign: 'top',
                                y: 25,
                                floating: true,
                                backgroundColor: (Highcharts.theme && Highcharts.theme.background2) || 'white',
                                borderColor: '#CCC',
                                borderWidth: 1,
                                shadow: false
                            },
                            tooltip: {
                                headerFormat: '<b>{point.x}</b><br/>',
                                pointFormat: '{series.name}: R$ {point.y:.2f}<br/>Total: R$ {point.stackTotal:.2f}'
                            },
                            plotOptions: {
                                column: {
                                    stacking: 'normal',
                                    dataLabels: {
                                        enabled: true,
                                        color: (Highcharts.theme && Highcharts.theme.dataLabelsColor) || 'white'
                                    }
                                }
                            },
                            series: data
                        });
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                
                    showNotyAlert(e, "e");
                }
            }
        });
    }
    
    
    function initializeCalendar() {
        $.ajax({
             url: '<?php echo URLBASE_CLIENT  . Utils\Rotas::R_BOLETOS_RELATORIOS_CARREGAREVENTOS  ?>',
             method: 'post',
             dataType: 'json',
             success: function (json) {
                 try {
                     if (json.sucesso) {
                        $('#calendar').fullCalendar({
                            header: {
                                left: 'prev,next today',
                                center: 'title',
                                right: 'month,agendaWeek,agendaDay'
                            },
                            editable: false,
                            droppable: false,
                            events: json.eventos
                        });
                        $(".fc-month-button").trigger("click");
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
            }
        });
    }
    
 <?php } ?>
</script>


<div class="modal fade" id="dialogFinalizarBoleto" tabindex="-1" role="dialog" aria-labelledby="dialogFinalizarBoleto" aria-hidden="true" >
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title" id="dialogFinalizarBoletoLabel"><?php echo $idioma->getText("marcarBoletoFinalizado") ?></h2>
            </div>
            <div class="modal-body">
                <div class="col col-lg-12" >
                <form id="form-finalizar" action="<?php echo URLBASE_CLIENT . Utils\Rotas::R_BOLETOS_FINALIZAR ?>" method="post">
                    <input type="hidden" id="dialogFinalizarBoletoIdBoleto" name="idBoleto" />
                    
                        <div class="row">                            
                        <h5><?php echo $idioma->getText("marcarBoletoDesejaContinuar") ?><br><br>
                            <strong><?php echo $idioma->getText("desejaContinuar") ?></strong></h5>
                        </div>
                    <div class="row" id="dadosPagamento">
                    </div>
                    <br>
                    <div class="row">
                        <div class="col col-lg-12">
                            <div class="form-group">
                                <label><?php echo $idioma->getText("anexarComprovante") ?></label>
                                <input type="file" id="comprovante" name="comprovante" class="form-control" />
                                <div class="row" id="progressDocumentsContainer">
                                    <div class="col col-lg-12">
                                        <div class="progress">
                                            <div style="width: 0%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="0" role="progressbar" id="progressDocuments" class="progress-bar progress-bar-success">
                                                <span class="sr-only" id="progressDocumentsLegend"></span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="dialogFinalizarBoletoFechar" data-dismiss="modal"><?php echo $idioma->getText("fecharBtn") ?></button>
                <button type="button" class="btn btn-success" id="dialogFinalizarBoletoConfirmar" onclick="confirmarFinalizacaoBoleto();" ><?php echo $idioma->getText("confirmarFinalizacao") ?></button>
            </div>
        </div>
        <!-- /.modal-content -->
        </div>
    </div>
    <!-- /.modal-dialog -->
</div>

<div class="modal fade" id="dialogCancelarBoleto" tabindex="-1" role="dialog" aria-labelledby="dialogCancelarBoleto" aria-hidden="true" >
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title" id="dialogCancelarBoletoLabel"><?php echo $idioma->getText("cancelarBoleto") ?></h3>
            </div>
            <div class="modal-body">
                <div class="col col-lg-12" >
                <form id="form-cancelar" action="<?php echo URLBASE_CLIENT . Utils\Rotas::R_BOLETOS_CANCELAR ?>" method="post">
                    <input type="hidden" id="dialogCancelarBoletoIdBoleto" name="idBoleto" />
                    <br>
                    <br>
                        <div class="row">                            
                            <h3><?php echo $idioma->getText("desejaRealmenteCancelar") ?></h3>
                        </div>
                    <?php if(Utils\Geral::isUsuario()){ ?>
                    <label><?php echo $idioma->getText("motivoCancelamento") ?></label>
                    <textarea type="text" class="form-control" id="motivoCancelamento" name="motivoCancelamento" rows="3" maxlength="1500" style="resize: none;"></textarea>  
                    <?php } ?>
                     <br>
                    <br>
                      <br>
                    <br>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="dialogCancelarBoletoFechar" data-dismiss="modal"><?php echo $idioma->getText("fecharBtn") ?></button>
                <button type="button" class="btn btn-success" id="dialogCancelarBoletoConfirmar" onclick="confirmarCancelarBoleto();" ><?php echo $idioma->getText("cancelarPagamento") ?></button>
            </div>
        </div>
        <!-- /.modal-content -->
        </div>
    </div>
    <!-- /.modal-dialog -->
</div>

    


<div class="modal fade" id="dialogPagar" tabindex="-1" role="dialog" aria-labelledby="dialogPagar" aria-hidden="true" >
    <div class="modal-dialog modal-lg modal-dialog-centered" >
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" ><?php echo $idioma->getText("pagarBoleto") ?></h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    
                    <div class="col col-lg-12">
                        <?php echo $idioma->getText("valorDoBoletoSeraDebitado") ?>
                    </div>
                    
                </div>
                
                <br>


                <div class="row" >
                    <div class="col col-lg-12">
                        <div class="progress">
                            <div style="width: 0%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="0" role="progressbar" id="progressBoleto" class="progress-bar progress-bar-success">
                                <span class="sr-only" id="progressBoletoLegend"></span>
                            </div>
                        </div>
                    </div>
                </div>

                <br>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="dialogPagarClose" data-dismiss="modal"><?php echo $idioma->getText("fecharBtn") ?></button>
                <button type="button" class="btn btn-primary" onclick="confirmarPagamento();" id="dialogPagarSalvar" ><?php echo $idioma->getText("pagarBoletoBtn") ?></button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>


<div class="modal fade" id="dialogConfirmacaoPagamento" tabindex="-1" role="dialog" aria-labelledby="dialogConfirmacaoPagamento" aria-hidden="true" >
    <div class="modal-dialog modal-dialog-centered modal-lg" >
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" ><?php echo $idioma->getText("pagamentoEfetuado") ?></h4>
            </div>
            <div class="modal-body">
                <br><br>
                <div class="row">
                    
                    <div class="col col-lg-12">
                        <strong> <?php echo $idioma->getText("recebemosSeuPagamento") ?></strong>
                    </div>
                    
                </div>
                <br><br>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="dialogConfirmacaoPagamentoClose" data-dismiss="modal"><?php echo $idioma->getText("fecharBtn") ?></button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>


