<?php
$dataInicial = new Utils\Data(date("d/m/Y"));
$dataFinal = new Utils\Data(date("d/m/Y"));
$dataInicial->subtrair(0, 0, 30);
$moeda = \Modules\principal\Controllers\Principal::getCurrency();
$usuarios = isset($_data["usuarios"]) ? $_data["usuarios"] : Array();
?>


<?php Utils\Layout::append("inspina/metas", $_data) ?>

<?php Utils\Layout::append("inspina/scripts", $_data) ?>


<?php Utils\Layout::append("inspina/menu", $_data) ?>

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
            <div class="row wrapper border-bottom page-heading" style="background: linear-gradient(to right, #fff, <?php echo $moeda->mainColor ?>) !important;">
                <div class="col-lg-10">
                    <h2>P2P Venda</h2>
                    <ol class="breadcrumb" style="background-color: transparent !important;">
                        <li>
                            Serviços
                        </li>
                        <li class="active">
                            <strong>P2P Venda</strong>
                        </li>
                    </ol>
                </div>
            </div>

    <br><br>
    <!-- Main content -->
    <section class="content">

        <div class="row">
            <div class="col col-lg-12 text-center">
                
                <a class="btn btn-primary" href="<?php echo URLBASE_CLIENT . Utils\Rotas::R_P2P_CADASTRO ?>">
                    Cadastrar Novo
                </a>
                <br><br><br>
            </div>
        </div>
        
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <?php Utils\Layout::append("mensagem", $_data)?>
                    
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        
                        
                        <div class="row">
                            <div class="col col-md-3">
                                <div class="form-group">
                                    <label class="control-label">Data Inicial</label>
                                    <input type="text" id="dataInicial" class="form-control" value="<?php echo $dataInicial->formatar(\Utils\Data::FORMATO_PT_BR)?>" />
                                </div>
                            </div>
                            <div class="col col-md-3">
                                <div class="form-group">
                                    <label class="control-label">Data Final</label>
                                    <input type="text" id="dataFinal" class="form-control" value="<?php echo $dataFinal->formatar(\Utils\Data::FORMATO_PT_BR)?>" />
                                </div>
                            </div>
                            <div class="col col-md-3">
                                <div class="form-group">
                                    <label class="control-label">Tipo de Data</label>
                                    <select class="form-control" id="tipoData" >
                                        <option value="compra" >Data de Compra</option>
                                        <option value="finalizacao" >Data de Finalização</option>
                                        <option value="lancamento" >Data de Lançamento</option>
                                        <option value="alteracao" >Data de Alteração</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col col-md-3">
                                <div class="form-group">
                                    <label class="control-label">Status</label>
                                    <select class="form-control" id="status" >
                                        <option value="T" >Todos</option>
                                        <option value="<?php echo \Utils\Constantes::P2P_STATUS_CONCLUIDO ?>" >Concluído</option>
                                        <option value="<?php echo \Utils\Constantes::P2P_STATUS_CONFIRMADO ?>" >Confirmado</option>
                                        <option value="<?php echo \Utils\Constantes::P2P_STATUS_NAO_CONFIRMADO ?>" >Não confirmado</option>
                                        <option value="<?php echo \Utils\Constantes::P2P_STATUS_PROCESSANDO ?>" >Processando</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col col-lg-3">
                                <div class="form-group">
                                    <label class="control-label">Tipo Depósito</label>
                                    <select class="form-control" id="tipoDeposito" >
                                        <option value="T" >Todos</option>
                                        <option value="<?php echo \Utils\Constantes::TIPO_DEPOSITO_DINHEIRO ?>" >Dinheiro</option>
                                        <option value="<?php echo \Utils\Constantes::TIPO_DEPOSITO_DOC ?>" >DOC</option>
                                        <option value="<?php echo \Utils\Constantes::TIPO_DEPOSITO_TED ?>" >TED</option>
                                        <option value="<?php echo \Utils\Constantes::TIPO_DEPOSITO_TEF ?>" >TEF</option>
                                    </select>
                                </div>
                            </div>
                            
                            <div class="col col-md-3">
                                <div class="form-group">
                                    <label class="control-label">Usuário</label>
                                    <select class="form-control" id="idUsuario" >
                                        <option value="0" >Todos</option>
                                        <?php foreach($usuarios as $usuario) { ?>
                                        <option value="<?php echo $usuario->id ?>" ><?php echo $usuario->nome ?></option
                                        <?php } ?>
                                    </select>
                                </div>
                            </div>
                            
                            <div class="col col-md-6">
                                <div class="form-group">
                                    <label class="control-label">Filtro</label>
                                    <input type="text" id="texto" class="form-control" />
                                </div>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col col-lg-12 text-center">
                                <br>
                                <button class="btn btn-primary" onclick="listar();">
                                    <i class="fa fa-refresh"></i> Filtrar
                                </button>
                                <br><br>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col col-lg-12">
                                <ul class="list-group">
                                    <li class="list-group-item">
                                        <div class="row">
                                            <div class="col col-xs-4 ">
                                                Total Compra: R$ <span id="totalCompra"></span>
                                            </div>
                                            <div class="col col-xs-4 ">
                                                Total Depósito: R$ <span id="totalDeposito"></span>
                                            </div>
                                            <div class="col col-xs-4 ">
                                                Volume BTC: $ <span id="totalBtc"></span>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col col-lg-12" >
                                <ul class="list-group" id="lista">
                                    
                                </ul>
                            </div>
                        </div>
                    </div>
                    <!-- /.panel-body -->

                </div>
            </div>

        </div>

        <a  id="openOrder" target="_BLANK"></a>
    </section>
    
    <div class="clearfix"></div>
</div>

<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>

<script>
    $(document).ready(function () {
        
        $("#dataInicial, #dataFinal").datepicker({format: "dd/mm/yyyy"}).mask("99/99/9999");
        listar();
        
    });
    
    function listar() {
        $("#lista").html("<div class='col-lg-12 text-center'><img src='<?php echo IMAGES ?>loading.gif' /></div>");
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_P2P_LISTAR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                dataInicial:$("#dataInicial").val(),
                dataFinal:$("#dataFinal").val(),
                status:$("#status").val(),
                tipoData:$("#tipoData").val(),
                idUsuario:$("#idBanco").val(),
                texto:$("#email").val(),
                tipoDeposito:$("#tipoDeposito").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#lista").html(json.html);
                        $("#totalCompra").html(json.totalCompra);
                        $("#totalDeposito").html(json.totalDeposito);
                        $("#totalBtc").html(json.totalBtc);
                    } else {
                        $("#lista").html("<div class='col-lg-12 text-center'>"+json.mensagem+"</div>");
                        
                        $("#totalCompra").html("0");
                        $("#totalDeposito").html("0");
                        $("#totalBtc").html("0");
                    }
                } catch (e) {
                    $("#lista").html("<div class='col-lg-12 text-center'>"+e+"</div>");
                    $("#totalCompra").html("0");
                    $("#totalDeposito").html("0");
                    $("#totalBtc").html("0");
                }
            }
        });
    }
    
    
    function excluir(id) {
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_P2P_EXCLUIR ?>',
            dataType: 'json',
            method: 'post',
            data: {id: id},
            success: function (json) {
                try {
                    if (json.sucesso) {
                        showNotyAlert(json.mensagem, "s");
                        $("#p2p-"+id).remove();
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
            }
        });
    }
    
</script>

