<?php

$bancos = (isset($_data['bancos']) ? ($_data['bancos']) : false);

$cliente = \Utils\Geral::getCliente();
$moeda = \Modules\principal\Controllers\Principal::getCurrency();
$email = ($cliente != null ? $cliente->email : "");
?>


<?php Utils\Layout::append("inspina/metas", $_data) ?>

<?php Utils\Layout::append("inspina/scripts", $_data) ?>


<?php Utils\Layout::append("inspina/menu", $_data) ?>

<div class="content-wrapper">
  <div class="row wrapper border-bottom page-heading" style="background: linear-gradient(to right, #fff, <?php echo $moeda->mainColor ?>) !important;">
    <div class="col-lg-9">
      <ol class="breadcrumb m-t-md" style="background-color: transparent !important;">
          <li>
            <?php echo $idioma->getText("subTitulo") ?>
          </li>
          <li class="active">
              <strong><?php echo $idioma->getText("titulo") ?>
          </li>
      </ol>
    </div>
    <div class="col-lg-3">
    <?php Utils\Layout::append("inspina/flags", $_data) ?>
    </div>
  </div>
</div>
    
<div>
<br>

    <section class="content">

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="row">
                            <div class="col col-lg-12">
                                <h5 class="page-header">O crédito na conta informada será realizado em até 1 dia útil </h5>
                            </div>
                        </div>
                        
                        <form id="form-remessa" action="<?php echo URLBASE_CLIENT . Utils\Rotas::R_REMESSAS_SALVAR ?>" method="post" enctype="multipart/form-data">

                            <div class="row">
                                <div class="col col-lg-6">
                                    <div class="form-group">
                                        <label class="control-label">Titular</label>
                                        <input type="text" id="titular" name="titular" class="form-control" maxlength="200" value="" />
                                    </div>
                                </div>
                                <div class="col col-lg-6">
                                    <div class="form-group">
                                        <label class="control-label">CNPJ / CPF (somente números)</label>
                                        <input type="text" id="documento" name="documento" class="form-control" maxlength="14" value="" />
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col col-lg-8">
                                    <div class="form-group">
                                        <label class="control-label">Banco</label>
                                        <select class="form-control" id="idBanco" name="idBanco">
                                            <option value="0">Selecione um banco</option>
                                            <?php 
                                            foreach ($bancos as $banco) {
                                            ?>
                                            <option value="<?php echo $banco->id ?>"><?php echo $banco->codigo . " - " . $banco->nome ?></option>
                                            <?php 
                                            }
                                            ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="col col-lg-4">
                                    <div class="form-group">
                                        <label class="control-label">Tipo de Conta</label>
                                        <select class="form-control" id="tipoConta" name="tipoConta">
                                            <option value="0">Selecione um tipo de conta</option>
                                            <option value="<?php echo Utils\Constantes::CONTA_CORRENTE ?>">Conta Corrente</option>
                                            <option value="<?php echo Utils\Constantes::CONTA_POUPANCA ?>">Conta Poupança</option>
                                        </select>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col col-lg-3">
                                    <div class="form-group">
                                        <label class="control-label">Agência</label>
                                        <input type="text" id="agencia" name="agencia" class="form-control" maxlength="10"  value="" />
                                    </div>
                                </div>
                                <div class="col col-lg-3">
                                    <div class="form-group">
                                        <label class="control-label">Conta</label>
                                        <input type="text" id="conta" name="conta" class="form-control" maxlength="15"  value="" />
                                    </div>
                                </div>
                                <div class="col col-lg-2">
                                    <div class="form-group">
                                        <label class="control-label">Operação</label>
                                        <input type="text" id="operacao" name="operacao" class="form-control" maxlength="5"  value="" />
                                    </div>
                                </div>
                                <div class="col col-lg-4">
                                    <div class="form-group">
                                        <label class="control-label">Valor</label>
                                        <input type="text" id="valor" name="valor" class="form-control"  value="" />
                                    </div>
                                </div>
                            </div>

                            <br><br><br>

                            <div class="row">
                                <div class="col col-lg-6 text-center">
                                    <a class="btn btn-default" href="<?php echo URLBASE_CLIENT . Utils\Rotas::R_REMESSAS ?>">
                                        Voltar
                                    </a>
                                </div>
                                <div class="col col-lg-6 text-center">
                                    <button class="btn btn-primary" type="button" onclick="dialogConfirmar();" id="btn-cadastrar">
                                        Cadastrar
                                    </button>
                                </div>
                            </div>
                        
                        </form>
                        
                    </div>
                    <!-- /.panel-body -->

                </div>
            </div>

        </div>

        <a  id="openOrder" target="_BLANK"></a>
    </section>
    
    <div class="clearfix"></div>
</div>

<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>

<script>
    

$(document).ready(function () {
    $("#idBanco").select2();
    $("#documento").numeric();
    $("#valor").keydown(function (event) {
        $(this).val(currency($(this).val(), 2, 8, event.keyCode));
        event.preventDefault();
    });
    
    $("#form-remessa").ajaxForm({
        dataType: 'json',
        beforeSubmit: function () {
            $("#btn-cadastrar").prop("disabled", true);
        },
        success: function (json) {
            try {
                if (json.sucesso) {
                    location = "<?php echo URLBASE_CLIENT . Utils\Rotas::R_REMESSAS?>";
                } else {
                    showNotyAlert(json.mensagem, "e");
                }
            } catch (e) {
                showNotyAlert(e, "e");
            }
            $("#btn-cadastrar").prop("disabled", false);
        }
    });
    
});


function dialogConfirmar() {
    $("#dialogConfirmacaoPagamento").modal();
}

function confirmar() {
    $("#form-remessa").submit();
}

</script>



<div class="modal fade" id="dialogConfirmacaoPagamento" tabindex="-1" role="dialog" aria-labelledby="dialogConfirmacaoPagamento" aria-hidden="true" >
    <div class="modal-dialog modal-lg" >
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" >Pagamento Efetuado</h4>
            </div>
            <div class="modal-body">
                <br><br>
                <div class="row">
                    
                    <div class="col col-lg-12">
                        Ao clicar em confirmar o saldo será automaticamente debitado da sua conta corrente. Não havendo saldo suficiente a remessa ficará como pendente de pagamento.<strong></strong>.
                    </div>
                    
                </div>
                <br><br>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="dialogConfirmacaoPagamentoClose" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-primary" id="dialogConfirmacaoPagamentoSalvar" onclick="confirmar();" >Confirmar</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

