<?php
$bancos = (isset($_data['bancos']) ? ($_data['bancos']) : false);

$cliente = \Utils\Geral::getCliente();
$moeda = \Modules\principal\Controllers\Principal::getCurrency();
$email = ($cliente != null ? $cliente->email : "");

$salvar = false;

?>


<?php Utils\Layout::append("inspina/metas", $_data) ?>

<?php Utils\Layout::append("inspina/scripts", $_data) ?>


<?php Utils\Layout::append("inspina/menu", $_data) ?>


<div class="content-wrapper">
  <div class="row wrapper border-bottom page-heading" style="background: linear-gradient(to right, #fff, <?php echo $moeda->mainColor ?>) !important;">
    <div class="col-lg-9">
      <ol class="breadcrumb m-t-md" style="background-color: transparent !important;">
          <li>
            <?php echo $idioma->getText("subTitulo") ?>
          </li>
          <li class="active">
              <strong><?php echo $idioma->getText("titulo") ?>
          </li>
      </ol>
    </div>
    <div class="col-lg-3">
    <?php Utils\Layout::append("inspina/flags", $_data) ?>
    </div>
  </div>
</div>
    
<div>
<br>

    <!-- Main content -->
    <section class="content">

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <?php Utils\Layout::append("mensagem", $_data)?>
                    <div class="panel-heading">
                        Dados do Boleto
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        
                        <div class="row">
                            <div class="col col-lg-12">
                                <h5 class="page-header">O pagamento será realizado em até 1 dia útil após a confirmação de pagamento da invoice</h5>
                            </div>
                        </div>
                        
                        <form id="form-boleto" action="<?php echo URLBASE_CLIENT . Utils\Rotas::R_BOLETOS_SALVAR ?>" method="post" enctype="multipart/form-data">

                            <div class="row">
                                <div class="col col-lg-12">
                                    <div class="form-group">
                                        <label class="control-label">Linha Digitável</label>
                                        <input type="text" id="barras" name="barras" class="form-control" maxlength="50" value="" />
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Instituição Bancaria:</label>
                                        <select class="form-control select2" id="cadastroContaIdBanco" name="cadastroContaIdBanco">
                                            <option value="0">Selecione um banco</option>
                                            <?php 
                                            foreach ($bancos as $banco) {
                                            ?>
                                            <option value="<?php echo $banco->id ?>"><?php echo $banco->codigo . " - " . $banco->nome ?></option>
                                            <?php 
                                            }
                                            ?>
                                        </select>   
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col col-lg-6">
                                    <div class="form-group">
                                        <label class="control-label">Valor</label>
                                        <input type="text" id="valor" name="valor" class="form-control"  value="" />
                                    </div>
                                </div>
                                <div class="col col-lg-6">
                                    <div class="form-group">
                                        <label class="control-label">Vencimento</label>
                                        <input type="text" id="vencimento" name="vencimento" class="form-control"  value="" />
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col col-lg-6">
                                    <br>
                                    <div class="form-group">
                                        <label class="control-label">Email</label>
                                        <input type="text" id="email" name="email" class="form-control" maxlength="200"  value="<?php echo $email ?>" />
                                    </div>
                                </div>
                                <div class="col col-lg-6">
                                    <div class="form-group">
                                        <div class="ibox-content">
                                            <label>Anexe uma foto ou PDF do boleto</label> <br>
                                            <div class="fileinput fileinput-new input-group" data-provides="fileinput">
                                                <div class="form-control" data-trigger="fileinput">
                                                    <i class="glyphicon glyphicon-file fileinput-exists"></i> <span class="fileinput-filename"></span>
                                                </div>
                                                <span class="input-group-addon btn btn-default btn-file">
                                                    <span class="fileinput-new">Selecionar</span>
                                                    <span class="fileinput-exists">Mudar</span>
                                                    <input type="file" id="arquivo" name="arquivo" >
                                                </span>
                                                <a href="#" class="input-group-addon btn btn-default fileinput-exists" data-dismiss="fileinput">Remover</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <br><br><br>

                            <div class="row">
                                <div class="col col-lg-6 text-center">
                                    <a class="btn btn-default" href="<?php echo URLBASE_CLIENT . Utils\Rotas::R_BOLETOS ?>">
                                        Voltar
                                    </a>
                                </div>
                                <div class="col col-lg-6 text-center">
                                    
                                    
                                    <button class="btn btn-primary" type="button" onclick="dialogConfirmar();" id="btn-cadastrar">
                                        Cadastrar
                                    </button>
                                    
                                    
                                </div>
                            </div>
                        
                        </form>
                        
                    </div>
                    <!-- /.panel-body -->

                </div>
            </div>

        </div>

        <a  id="openOrder" target="_BLANK"></a>
    </section>
    
    <div class="clearfix"></div>
</div>

<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>

<script>
    
$(document).ready(function () {
    $("#cadastroContaIdBanco").select2();
    $("#barras").numeric();
    $("#vencimento").datepicker({format: 'dd/mm/yyyy'}).mask("99/99/9999");
    $("#valor").keydown(function (event) {
        $(this).val(currency($(this).val(), 2, 8, event.keyCode));
        event.preventDefault();
    });
    
    
    $("#form-boleto").ajaxForm({
        dataType: 'json',
        beforeSubmit: function () {
            $("#btn-cadastrar").prop("disabled", true);
        },
        success: function (json) {
            try {
                if (json.sucesso) {
                    location = "<?php echo URLBASE_CLIENT . Utils\Rotas::R_BOLETOS ?>";
                } else {
                    showNotyAlert(json.mensagem, "e");
                }
            } catch (e) {
                showNotyAlert(e, "e");
            }
            $("#btn-cadastrar").prop("disabled", false);
        }
    });
    
});


function dialogConfirmar() {
    $("#dialogConfirmacaoPagamento").modal();
}

function confirmar() {
    $("#form-boleto").submit();
}


</script>


<?php Utils\Layout::append("mensage_text", $_data) ?>






<div class="modal fade" id="dialogConfirmacaoPagamento" tabindex="-1" role="dialog" aria-labelledby="dialogConfirmacaoPagamento" aria-hidden="true" >
    <div class="modal-dialog modal-lg" >
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" >Pagamento Efetuado</h4>
            </div>
            <div class="modal-body">
                <br><br>
                <div class="row">
                    
                    <div class="col col-lg-12">
                        Ao clicar em confirmar o saldo será automaticamente debitado da sua conta corrente. Não havendo saldo suficiente o boleto ficará como pendente de pagamento.
                    </div>
                    
                </div>
                <br><br>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="dialogConfirmacaoPagamentoClose" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-primary" id="dialogConfirmacaoPagamentoSalvar" onclick="confirmar();" >Confirmar</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

