<?php
?>


<?php Utils\Layout::append("inspina/metas", $_data) ?>

<?php Utils\Layout::append("inspina/scripts", $_data) ?>


<?php Utils\Layout::append("inspina/menu", $_data) ?>

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
            <div class="row wrapper border-bottom page-heading" style="background: linear-gradient(to right, #fff, <?php echo $moeda->mainColor ?>) !important;">
                <div class="col-lg-10">
                    <h2>Identificação de Pagamentos (API de Pagamentos)</h2>
                    <ol class="breadcrumb" style="background-color: transparent !important;">
                        <li>
                            Serviços
                        </li>
                        <li class="active">
                            <strong>Pagamentos</strong>
                        </li>
                    </ol>
                </div>
            </div>

    <!-- Main content -->
    <section class="content">

        <br><br>
        
        <div class="row">
            
            <div class="col col-lg-4 col-lg-offset-4 col-md-4 col-md-offset-4 col-xs-6 col-xs-offset-6">
                <div class="form-group">
                    <label>Informe o código</label>
                    <div class="input-group">
                        <input type="text" class="form-control" id="codigo"> 
                        <span class="input-group-btn"> 
                            <button type="button" class="btn btn-primary" onclick="buscar();">Pesquisar</button> 
                        </span>
                    </div>
                </div>
            </div>
            
            
        </div>
        
        
        <div class="row">
            
            <div class="col col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-xs-12 col-xs-offset-0">
                <div class="col-xs-12" id="widget-loading">
                    <img src="<?php echo IMAGES ?>loader.gif" style="margin: 10px auto; display: none;"  />
                </div>
                
                <div class="widget  p-xl" id="widget-pagamento" style="display: none;">

                    <h2 id="pagamento-status">
                        
                    </h2>
                    <ul class="list-unstyled m-t-md">
                        
                        <li>
                            <label>Cliente:</label> <span id="pagamento-cliente"></span>
                        </li>
                        <li>
                            <label>Origem:</label> <span id="pagamento-origem"></span>
                        </li>
                        <li>
                            <label>Destino:</label> <span id="pagamento-destino"></span>
                        </li>
                        <li>
                            <label>Volume:</label> <span id="pagamento-volume"></span>
                        </li>
                        <li>
                            <label>Data de cadastro:</label> <span id="pagamento-cadastro"></span>
                        </li>
                        <li>
                            <label>Data de pagamento:</label> <span id="pagamento-dataPagamento"></span>
                        </li>
                        <li>
                            <label>Pago:</label> <span id="pagamento-pago"></span>
                        </li>
                        <li>
                            <label>Hash:</label> <span id="pagamento-hash"></span>
                        </li>
                        <li>
                            <div class="row">
                                <div class="col col-xs-12 text-center" id="pagamento-btn-callback">
                                    
                                </div>
                            </div>
                        </li>
                    </ul>

                </div>
                
            </div>
            
        </div>
        
        

        <a  id="openOrder" target="_BLANK"></a>
    </section>
    
    <div class="clearfix"></div>
</div>

<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>

<script>
    $(document).ready(function () {
        
        
        
    });
    
    function buscar() {
        $("#widget-loading").show();
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_APIPAGAMENTOS_BUSCAR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                codigo:$("#codigo").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#widget-pagamento").removeClass("yellow-bg").removeClass("navy-bg").removeClass("red-bg");
                        $("#pagamento-status").html("Status: "+ json.pagamento.status);
                        
                        $("#pagamento-origem").html(json.pagamento.origem);
                        $("#pagamento-destino").html(json.pagamento.destino);
                        $("#pagamento-volume").html(json.pagamento.volume);
                        $("#pagamento-cadastro").html(json.pagamento.cadastro);
                        $("#pagamento-dataPagamento").html(json.pagamento.dataPagamento);
                        $("#pagamento-pago").html(json.pagamento.pago);
                        $("#pagamento-hash").html(json.pagamento.hash);
                        $("#pagamento-cliente").html(json.pagamento.cliente);
                        $("#widget-pagamento").addClass(json.pagamento.class);
                        $("#pagamento-btn-callback").html(json.pagamento.callback);
                        $("#widget-pagamento").show();
                        
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                        showNotyAlert(e, "e");
                }
                $("#widget-loading").hide();
            }
        });
    }
    
    
    function enviarCallback(codigo) {
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_APIPAGAMENTOS_CALLBACK ?>',
            method: 'post',
            dataType: 'json',
            data: {
                codigo: codigo
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#modalRetornoCallback").modal();
                        $("#modalRetornoCallbackConteudo").html(json.resultado);
                        $("#modalRetornoCallbackURL").html(json.url);
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                
            }
        });
    }
    
</script>

<div class="modal fade" id="modalRetornoCallback" tabindex="-1" role="dialog" aria-labelledby="modalRetornoCallback" aria-hidden="true" >
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="modalRetornoCallbackLabel">Retorno do Callback</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col col-lg-12">
                        <h4 id="modalRetornoCallbackURL" ></h4>
                        <div id="modalRetornoCallbackConteudo" style="white-space: pre-wrap; height: 400px; overflow-y: scroll;">
                            
                        </div>
                    </div>
                </div>
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="modalRetornoCallbackClose" data-dismiss="modal">Fechar</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>