<?php
$dataInicial = new Utils\Data(date("d/m/Y"));
$dataFinal = new Utils\Data(date("d/m/Y"));
$dataInicial->subtrair(0, 0, 30);
$moeda = \Modules\principal\Controllers\Principal::getCurrency();
$bancos = isset($_data["bancos"]) ? $_data["bancos"] : Array();
?>


<?php Utils\Layout::append("inspina/metas", $_data) ?>

<?php Utils\Layout::append("inspina/scripts", $_data) ?>


<?php Utils\Layout::append("inspina/menu", $_data) ?>


    <!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
            <div class="row wrapper border-bottom page-heading" style="background: linear-gradient(to right, #fff, <?php echo $moeda->mainColor ?>) !important;">
                <div class="col-lg-10">
                    <h2>Pagamento de Boletos</h2>
                    <ol class="breadcrumb" style="background-color: transparent !important;">
                        <li>
                            Serviços
                        </li>
                        <li class="active">
                            <strong>Pagamento de Boletos</strong>
                        </li>
                    </ol>
                </div>
            </div>
</div>
</br>

    <!-- Main content -->
    <section class="content">
<form id="pesquisa">
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <?php Utils\Layout::append("mensagem", $_data)?>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        
                        
                        <div class="row">
                            <div class="col col-md-2">
                                <div class="form-group">
                                    <label class="control-label">Data Inicial</label>
                                    <input type="text" id="dataInicial" class="form-control" value="<?php echo $dataInicial->formatar(\Utils\Data::FORMATO_PT_BR)?>" onchange="listarBoletos();" />
                                </div>
                            </div>
                            <div class="col col-md-2">
                                <div class="form-group">
                                    <label class="control-label">Data Final</label>
                                    <input type="text" id="dataFinal" class="form-control" value="<?php echo $dataFinal->formatar(\Utils\Data::FORMATO_PT_BR)?>" onchange="listarBoletos();"/>
                                </div>
                            </div>
                            <div class="col col-md-2">
                                <div class="form-group">
                                    <label class="control-label">Status</label>
                                    <select class="form-control" id="status" onchange="listarBoletos();">
                                        <option value="T" >Todos</option>
                                        <option value="<?php echo \Utils\Constantes::STATUS_BOLETO_CLIENTE_AGUARDANDO ?>" >Aguardando</option>
                                        <option value="<?php echo \Utils\Constantes::STATUS_BOLETO_CLIENTE_CANCELADO ?>" >Boleto Pago</option>
                                        <option value="<?php echo \Utils\Constantes::STATUS_BOLETO_CLIENTE_FINALIZADO ?>" >Solicitação Cancelada</option>
                                    </select>
                                </div>
                            </div>
                            
                            <div class="col col-md-2">
                                <div class="form-group">
                                    <label class="control-label">Registros</label>
                                    <select class="form-control" id="nresultado" onchange="listarBoletos();" >
                                        <option value="10" >10</option>
                                        <option value="20" >20</option>
                                        <option value="50" >50</option>
                                        <option value="100" >100</option>
                                        <option value="T" >Todos</option>

                                    </select>
                                </div>
                            </div>
                            <div class="col col-lg-4">
                                    <div class="form-group">
                                        <label class="control-label">Filtro</label>
                                        <input type="text" id="filtro" name="barras" class="form-control" onkeyup="listarBoletos();"  />
                                    </div>
                                </div>
                        </div>
                        
                        <div class="row">
                            <div class="col col-lg-12 text-center">
                                <br>
                                <?php if (\Models\Modules\Acesso\RotinaRn::validar(\Utils\Rotas::R_BOLETOS, \Utils\Constantes::CADASTRAR)) { ?>
                                <a class="btn btn-primary" href="<?php echo URLBASE_CLIENT . Utils\Rotas::R_BOLETOS_CADASTRO ?>">
                                    Cadastrar novo Boleto
                                </a>
                                <?php } ?>
                                <button class="btn btn-default pull-right" onClick="limpar();">
                                    Limpar
                                </button>


                                <br><br>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</form>
<div class="row">
            <div class="col-lg-12">
                        <div class="row">
                            <div class="col col-lg-12 table-responsive">
                                <table class="table table-hover table-condensed table-bordered" style="font-size: 10px">
                                    <thead>
                                        <tr>
                                            <?php if (\Utils\Geral::isUsuario()) { ?>
                                            <th class="text-center">Cliente</th>
                                            <?php } ?>
                                            <th class="text-center"><strong>Controle</strong></th>
                                            <th class="text-center"><strong>Cod. Barras</strong></th>
                                            <th class="text-center"><strong>Boleto</strong></th>
                                            <th class="text-center"><strong>Data Cadastro</strong></th>
                                            <th class="text-center"><strong>Vencimento</strong></th>
                                            <th class="text-center"><strong>Data Pagamento</strong></th>
                                            <th class="text-center"><strong>Valor R$</strong></th>
                                            <th class="text-center"><strong>Taxa R$</strong></th>
                                            <th class="text-center"><strong>Status</strong></th>
                                            <th class="text-center"><strong>Detalhes</strong></th>
                                            <th class="text-center"><strong>Comp.</strong></th>
                                            <th class="text-center"><strong>NF</strong></th>
                                        </tr>
                                    </thead>
                                    <tbody id="listaBoletos" style="background-color: #fff">

                                    </tbody>
                                </table>
                            </div>
                        </div>
            </div>
</div>
</section>
    
    <div class="clearfix"></div>
</div>

<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>

<script>
    $(document).ready(function () {

        
         $("#dataInicial,#dataFinal").datepicker({
            format: "dd/mm/yyyy",
            todayBtn: "linked",
            language: "pt-BR",
            orientation: "top left",
            autoclose: true,
            todayHighlight: true,
            toggleActive: true,
            });

        function limpar(){
        $('#pesquisa').each (function(){
          this.reset();
          filtrar();
        });
        }
        
        listarBoletos();
        
        $("#form-finalizar").ajaxForm({
            dataType: "json",
            beforeSubmit: function () {
                $("#dialogFinalizarBoletoFechar, #dialogFinalizarBoletoConfirmar").prop("disabled", true);
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#dialogFinalizarBoletoFechar").prop("disabled", false).trigger("click");
                        listarBoletos();
                        showNotyAlert(json.mensagem, "s");
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#dialogFinalizarBoletoFechar, #dialogFinalizarBoletoConfirmar").prop("disabled", false);
            }
        });
        
    });
    
    function listarBoletos() {
        $("#listaBoletos").html("<div class='col-lg-12 text-center'><img src='<?php echo IMAGES ?>loading.gif' /></div>");
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_BOLETOS_FILTRAR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                dataInicial:$("#dataInicial").val(),
                dataFinal:$("#dataFinal").val(),
                status:$("#status").val(),
                tipoData:$("#tipoData").val(),
                idBanco:$("#idBanco").val(),
                email:$("#email").val(),
                nresultado: $("#nresultado").val(),
                barras: $("#barras").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#listaBoletos").html(json.html);
                        $("#aguardando").html(json.dados.aguardando);
                        $("#pago").html(json.dados.pago);
                        $("#finalizados").html(json.dados.finalizado);
                        $("#cancelados").html(json.dados.cancelado);
                    } else {
                        $("#listaBoletos").html("<div class='col-lg-12 text-center'>"+json.mensagem+"</div>");
                        
                        $("#aguardando").html("0");
                        $("#pago").html("0");
                        $("#finalizados").html("0");
                        $("#cancelados").html("0");
                    }
                } catch (e) {
                    $("#listaBoletos").html("<div class='col-lg-12 text-center'>"+e+"</div>");
                    $("#aguardando").html("0");
                    $("#pago").html("0");
                    $("#finalizados").html("0");
                    $("#finalizados").html("0");
                }
            }
        });
    }
    
    function dialogFinalizarBoleto(idBoleto) {
        $("#dialogFinalizarBoletoIdBoleto").val(idBoleto);
        $("#dialogFinalizarBoleto").modal();
    }
    
    function confirmarFinalizacaoBoleto() {
        $("#form-finalizar").submit();
    }
    
    
function modalDialogPagar(id) {
    
    $("#dialogPagar").modal();
    $("#dialogPagarIdBoleto").val(id);
}

function pagarBoleto() {
    $("#dialogPagarClose, #dialogPagarSalvar").prop("disabled", true);
    $.ajax({
        url : "<?php echo URLBASE_CLIENT . Utils\Rotas::R_BOLETOS_PAGAR ?>",
        method: "post",
        dataType: "json",
        data: {
            id: $("#dialogPagarIdBoleto").val()
        },
        success: function (json) {
            try {
                if (json.sucesso) {
                    $("#dialogPagarClose").prop("disabled", false).trigger("click");
                    modalDialogConfirmacaoPagamento();
                    listarBoletos();
                } else {
                    showNotyAlert(json.mensagem, "e");
                }
            } catch (e) {
                showNotyAlert(e, "e");
            }
            $("#dialogPagarClose, #dialogPagarSalvar").prop("disabled", false);
        }
    });
    
}

function modalDialogConfirmacaoPagamento() {
    
    $("#dialogConfirmacaoPagamento").modal();
    
}
</script>


<div class="modal fade" id="dialogFinalizarBoleto" tabindex="-1" role="dialog" aria-labelledby="dialogFinalizarBoleto" aria-hidden="true" >
    <div class="modal-dialog" style="width: 800px;">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="dialogFinalizarBoletoLabel">Marcar Boleto como Finalizado</h4>
            </div>
            <div class="modal-body">
                <form id="form-finalizar" action="<?php echo URLBASE_CLIENT . Utils\Rotas::R_BOLETOS_FINALIZAR ?>" method="post">
                    <input type="hidden" id="dialogFinalizarBoletoIdBoleto" name="idBoleto" />
                    <div class="row">
                        <div class="col col-lg-12" >
                            Marcar o boleto como finalizado significa ter efetuado o pagamento do mesmo perante uma instituição financeira. Deseja continuar?
                        </div>
                    </div>
                    <br><br>
                    <div class="row">
                        <div class="col col-lg-12">
                            <div class="form-group">
                                <label>Anexar comprovante</label>
                                <input type="file" id="comprovante" name="comprovante" class="form-control" />
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="dialogFinalizarBoletoFechar" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-success" id="dialogFinalizarBoletoConfirmar" onclick="confirmarFinalizacaoBoleto();">Confirmar Finalização</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>


<div class="modal fade" id="dialogPagar" tabindex="-1" role="dialog" aria-labelledby="dialogPagar" aria-hidden="true" >
    <div class="modal-dialog modal-lg" >
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" >Pagar Boleto</h4>
            </div>
            <div class="modal-body">
                <input type="hidden" value="" id="dialogPagarIdBoleto" />
                <div class="row">
                    
                    <div class="col col-lg-12">
                        O valor do boleto será debitado do seu saldo. Deseja continuar?
                    </div>
                    
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="dialogPagarClose" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-primary" onclick="pagarBoleto();" id="dialogPagarSalvar" >Pagar Boleto</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>


<div class="modal fade" id="dialogConfirmacaoPagamento" tabindex="-1" role="dialog" aria-labelledby="dialogConfirmacaoPagamento" aria-hidden="true" >
    <div class="modal-dialog modal-lg" >
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" >Pagamento Efetuado</h4>
            </div>
            <div class="modal-body">
                <br><br>
                <div class="row">
                    
                    <div class="col col-lg-12">
                        Recebemos o seu pagamento. O boleto será quitado no prazo máximo de 1 dia útil.<strong></strong>.
                    </div>
                    
                </div>
                <br><br>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="dialogConfirmacaoPagamentoClose" data-dismiss="modal">Fechar</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>


