<?php Utils\Layout::append("inspina/metas", $_data) ?>

<?php Utils\Layout::append("inspina/scripts", $_data) ?>
<?php
$moeda = \Modules\principal\Controllers\Principal::getCurrency();
?>
<style>
    code {
        white-space: pre-wrap;
        color: #047cc1;
    }
    code i {
        color: #545454;
    }
</style>

<?php Utils\Layout::append("inspina/menu", $_data) ?>

    
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
            <div class="row wrapper border-bottom page-heading" style="background: linear-gradient(to right, #fff, <?php echo $moeda->mainColor ?>) !important;">
                <div class="col-lg-10">
                    <h2>Calculadora</h2>
                    <ol class="breadcrumb" style="background-color: transparent !important;">
                        <li>
                            Documentação - API
                        </li>
                        <li class="active">
                            <strong>PDV</strong>
                        </li>
                    </ol>
                </div>
            </div>
</div>
<br>       
<div class="wrapper wrapper-content">
    <div class="col-lg-12">
                    <div class="wrapper wrapper-content animated fadeInRight">

                        <div class="ibox-content m-b-sm border-bottom">
                            <div class="text-center p-lg">
                                <h2>Documentação - API de Calculadora</h2>
                                
                            </div>
                        </div>

                        <div class="faq-item">
                            <div class="row">
                                <div class="col-md-7">
                                    <a data-toggle="collapse" href="#faq1" class="faq-question collapsed" aria-expanded="false">Conversão de moedas</a>
                                    
                                </div>
                                <div class="col-md-4">
                                    <i class="fa fa-clock-o"></i> Segunda-feira 11:57 - 19/02/2018</small>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-12">
                                    <div id="faq1" class="panel-collapse collapse" aria-expanded="false" style="height: 0px;">
                                        <div class="faq-answer">
                                            
<p>Retorna o valor em reais ou o volume em btc de acordo com os dados passados.</p>

Endpoint: <b>/api/calc/buy</b></br>
Verbo: <b>POST</b></p>
                                        
                                        
<b>Parâmetros:</b> </br>
<b>@param String amount</b>   =   Volume da moeda (obrigatório)</br>
<b>@param String from</b>   =  Moeda de origem ao qual o valor passado se refere (Ex: BRL, BTC, LTC).</br>
<b>@param String to</b>   =  Moeda para o qual o valor será convertido (Ex: BTC, BRL, LTC)</p>  
                                        <br><br>
<strong>Exemplo 1 para calcular o volume de BTC que um valor em Reais consegue comprar: (amount = 200.00, from = BRL, to = BTC)</strong>
                   
<b>Retorno:</b></p>

<code>
    {
        "BTC": "0.00426146",<i> Volume em na moeda configurada em TO que pode ser comprado com o montante em reais enviado</i>
        "fontenome": "",<i> Nome do site onde os valores de referencia são capturados</i>
        "fonteurl": "",<i> URL do site de onde os valores referência para conversão foram retirados</i>
        "sucesso": true
    }
</code>
                                        <br><br>
<strong>Exemplo 2 para calcular o volume de LTC que um valor em Reais consegue comprar: (amount = 200.00, from = BRL, to = LTC)</strong>
                   
<b>Retorno:</b></p>

<code>
    {
        "LTC": "0.00426146",<i> Volume em na moeda configurada em TO que pode ser comprado com o montante em reais enviado</i>
        "fontenome": "",<i> Nome do site onde os valores de referencia são capturados</i>
        "fonteurl": "",<i> URL do site de onde os valores referência para conversão foram retirados</i>
        "sucesso": true
    }
</code>
                                        
                                                                               <br><br>
<strong>Exemplo 3 para calcular o preço em reais do volume de BTC informado: (amount = 0.00426146, from = BTC, to = BRL)</strong>
                   
<b>Retorno:</b></p>

<code>
    {
        "BRL": "198,00",<i> Valor em reais do volume de BTC informado</i>
        "fontenome": "",<i> Nome do site onde os valores de referencia são capturados</i>
        "fonteurl": "",<i> URL do site de onde os valores referência para conversão foram retirados</i>
        "sucesso": true
    }
</code>


                                            
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        
                        
                    </div>
</div>
</div>

    
    <div class="clearfix"></div>
</div>

<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>

