<?php Utils\Layout::append("inspina/metas", $_data) ?>

<?php Utils\Layout::append("inspina/scripts", $_data) ?>
<?php
$moeda = \Modules\principal\Controllers\Principal::getCurrency();
?>

<style>
    code {
        white-space: pre-wrap;
        color: #047cc1;
    }
    code i {
        color: #545454;
    }
</style>

<?php Utils\Layout::append("inspina/menu", $_data) ?>

    
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
            <div class="row wrapper border-bottom page-heading" style="background: linear-gradient(to right, #fff, <?php echo $moeda->mainColor ?>) !important;">
                <div class="col-lg-10">
                    <h2>PDV</h2>
                    <ol class="breadcrumb" style="background-color: transparent !important;">
                        <li>
                            Documentação - API
                        </li>
                        <li class="active">
                            <strong>PDV</strong>
                        </li>
                    </ol>
                </div>
            </div>
</div>
<br>       
<div class="wrapper wrapper-content">
    <div class="col-lg-12">
                    <div class="wrapper wrapper-content animated fadeInRight">

                        <div class="ibox-content m-b-sm border-bottom">
                            <div class="text-center p-lg">
                                <h2>Documentação - API de Ponto de Venda</h2>
                                
                            </div>
                        </div>

                        <div class="faq-item">
                            <div class="row">
                                <div class="col-md-7">
                                    <a data-toggle="collapse" href="#faq1" class="faq-question collapsed" aria-expanded="false">Autenticação</a>
                                    
                                </div>
                                <div class="col-md-4">
                                    <i class="fa fa-clock-o"></i> Terça-feira 18:55 - 5/12/2017</small>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-12">
                                    <div id="faq1" class="panel-collapse collapse" aria-expanded="false" style="height: 0px;">
                                        <div class="faq-answer">
                                            
Para utilizar os métodos da API é necessário para cada requisição efetuar o login utilizando o seguinte endpoint:</p>

Endpoint: <b>/api/auth</b></br>
Verbo: <b>POST</b></p>

<b>Parâmetros:</b> </br>
<b>@param String email</b>   =   Email de login (obrigatório)</br>
<b>@param String senha</b>   =  Senha de login (obrigatório)</p>

<b>Retorno:</b></p>


<code>
    {
        "sucesso" => true, <i>true or false</i>
        "mensagem" => '' <i>se sucesso for false indica o motivo do erro</i>
        "token" => '' <i>se sucesso for true retorna o token de acesso</i>
    }
</code>


                                            
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="faq-item">
                            <div class="row">
                                <div class="col-md-7">
                                    <a data-toggle="collapse" href="#faq2" class="faq-question collapsed" aria-expanded="false">Gerar nova Invoice</a>
                                    
                                </div>
                                <div class="col-md-4">
                                    <i class="fa fa-clock-o"></i> Terça-feira 18:55 - 5/12/2017</small>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-12">
                                    <div id="faq2" class="panel-collapse collapse" aria-expanded="false" style="height: 0px;">
                                        <div class="faq-answer">
                                            <p>
Descrição: Este método irá criar uma nova invoice no sistema. Note que o parâmetro de identificação da invoice não deve ser informado. Se informado os dados da invoice existente serão retornados.</br>

Endpoint: <b>/api/pdv</b></br>
Verbo: <b>POST</b>
                                            </p>
    
<b>Parâmetros:</b> </br> 
<b>@param String token</b>   =    Token de validação do login</br>
<b>@param String chave</b>   =    API KEY do Ponto de PDV cadastrado no sistema</br>
<b>@param String email</b>   =    Email de identificação do cliente (Opcional).</br>
<b>@param String celular</b>   =   Celular do cliente (Opcional).</br>
<b>@param String moeda</b>   =    A moeda que será adicionada a conta corrente. Se informada BRL além da taxa da transação será cobrada a taxa de conversão em reais.</br>
<b>@param String callback</b>   =    Url de callback (Opcional).</br>
<b>@param Numeric valor</b>   =    Valor a ser cobrado. <br>
<b>@param Numeric cotacao</b>   =   Valor da cotação do BTC em BRL(Opcional). Se não for informado o valor será considerada a cotação do Order Book <br>

<br><br>
<b>Exemplo de retorno com sucesso:</b></p> 
<code>
    {
        "sucesso": true,
        "mensagem": "",
        "invoice": {
            "invoice": "1234",  <i>Identificação da invoice</i>
            "endereco": "1E9J1r8pAMAe7qD778uE7gktkT9m7c84CE", <i>Endereço de pagamento</i>
            "callback": "http://minhaurl.com.br", <i>Endereço de callback cadastrado</i>
            "valorbrl": "100.000", <i>Valor em reais cobrado na invoice</i>
            "valorbtc": "0.00002000", <i>Valor em BTC cobrado na invoice</i>
            "status": "Pendente", <i>Status da invoice (A = Aguardando, P = Pago, S = Pago com valor superior ao cobrado, I = Pago com valor inferior ao da invoice, C = Cancelada)</i>
            "datacriacao": "05/12/2017", <i>Data em que a invoice foi criada (Formato dd/mm/yyyy hh:mm:ss)</i>
            "datadeposito": "05/12/2017", <i>Data em que o cliente fez o último depósito (Formato dd/mm/yyyy hh:mm:ss)</i>
            "email": "fulano@fulano.com.br", <i>Email cadastrado na invoice</i>
            "celular": "1199999999", <i>celular cadastrado na invoice </i>
            "pdv": "Nome do PDV", <i>Identificação do PDV </i>
            "moeda": "BTC", <i>Moeda que será creditada na conta do estabelecimento</i>
            "estabelecimento": <i>"Nome do estabelecimento", identificação do estabelecimento</i>
            "cotacao": "42320.00", <i>Preço do BTC no momento da criação da invoice</i>
            "saldoRecebido": "0.004", <i>Valor total em BTC depositado no endereço de recebimento da invoice</i>
        }
    }
</code>

<b>Exemplo de retorno com erro:</b></p> 

<code>
{
    "sucesso": false,
    "mensagem": "Mensagem descritiva de erro"
}
</code>
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="faq-item">
                            <div class="row">
                                <div class="col-md-7">
                                    <a data-toggle="collapse" href="#faq3" class="faq-question collapsed" aria-expanded="false">Consultar Invoice</a>
                                    
                                </div>
                                <div class="col-md-4">
                                    <i class="fa fa-clock-o"></i> Terça-feira 18:55 - 5/12/2017</small>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-12">
                                    <div id="faq3" class="panel-collapse collapse" aria-expanded="false" style="height: 0px;">
                                        <div class="faq-answer">
                                            <p>
Descrição: Este método irá retornar os dados da invoice solicitada. Note que somente o parâmetro de identificação da invoice é informado. Se informados os demais dados eles serão ignorados.</br>

Endpoint: <b>/api/pdv</b></br>
Verbo: <b>POST</b></p>
    
<b>Parâmetros:</b> </br>
<b>@param String token</b> Token de validação do login</br>
<b>@param String chave</b> API KEY do Ponto de PDV cadastrado no sistema</br>
<b>@param String invoice</b> Identificação da invoice.</p>

    
<b>Exemplo de retorno com sucesso:</b></p> 
<code>
    {
        "sucesso": true,
        "mensagem": "",
        "invoice": {
            "invoice": "1234",  <i>Identificação da invoice</i>
            "endereco": "1E9J1r8pAMAe7qD778uE7gktkT9m7c84CE", <i>Endereço de pagamento</i>
            "valorbrl": "100.000", <i>Valor em reais cobrado na invoice</i>
            "valorbtc": "0.00002000", <i>Valor em BTC cobrado na invoice</i>
            "status": "Pendente", <i>Status da invoice (A = Aguardando, P = Pago, S = Pago com valor superior ao cobrado, I = Pago com valor inferior ao da invoice, C = Cancelada)</i>
            "datacriacao": "05/12/2017", <i>Data em que a invoice foi criada (Formato dd/mm/yyyy hh:mm:ss)</i>
            "datadeposito": "05/12/2017", <i>Data em que o cliente fez o último depósito (Formato dd/mm/yyyy hh:mm:ss)</i>
            "email": "fulano@fulano.com.br", <i>Email cadastrado na invoice</i>
            "celular": "1199999999", <i>celular cadastrado na invoice </i>
            "pdv": "Nome do PDV", <i>Identificação do PDV </i>
            "moeda": "BTC", <i>Moeda que será creditada na conta do estabelecimento</i>
            "estabelecimento": "Nome do estabelecimento", <i>identificação do estabelecimento</i>
            "cotacao": "42320.00", <i>Preço do BTC no momento da criação da invoice</i>
            "saldoRecebido": "0.004", <i>Valor total em BTC depositado no endereço de recebimento da invoice</i>
        }
    }
</code>

<b>Exemplo de retorno com erro:</b></p> 

<code>
{
    "sucesso": false,
    "mensagem": "Mensagem descritiva de erro"
}
</code>
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="faq-item">
                            <div class="row">
                                <div class="col-md-7">
                                    <a data-toggle="collapse" href="#faq4" class="faq-question collapsed" aria-expanded="false">Listar Invoices</a>
                                    
                                </div>
                                <div class="col-md-4">
                                    <i class="fa fa-clock-o"></i> Terça-feira 18:55 - 5/12/2017</small>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-12">
                                    <div id="faq4" class="panel-collapse collapse" aria-expanded="false" style="height: 0px;">
                                        <div class="faq-answer">
                                            <p>
Método reponsável por listar as invoices utilizando como filtro os parâmetros informados.</br>

Endpoint: <b>/api/pdv/listar</b></br>
Verbo: <b>POST</b></p>
    
<b>Parâmetros:</b> </br>
<b>@param String token</b> = Token de validação do login </br>
<b>@param String chave</b> = API KEY do Ponto de PDV cadastrado no sistema</br>
<b>@param String email</b> = Se informado irá retornar todas as invoices relacionadas a este email (Opcional).</br>
<b>@param String status</b> = Se informado irá retornar somente as invoices com este status (Opcional).</br>
<b>@param String dtinicial</b> = Se informado será retornado as invoices criadas de dtinicial a dtfinal (formato dd/mm/yyyy).</br>
<b>@param String dtfinal</b> = Se informado será retornado as invoices criadas de dtinicial a dtfinal (formato dd/mm/yyyy)</br>

    
<b>Exemplo de retorno com sucesso:</b></p> 
<code>
    {
        "sucesso": true,
        "mensagem": "",
        "invoices": [
            {
                "invoice": "1234",  <i>Identificação da invoice</i>
                "endereco": "1E9J1r8pAMAe7qD778uE7gktkT9m7c84CE", <i>Endereço de pagamento</i>
                "callback": "http://minhaurl.com.br", <i>Endereço de callback cadastrado</i>
                "valorbrl": "100.000", <i>Valor em reais cobrado na invoice</i>
                "valorbtc": "0.00002000", <i>Valor em BTC cobrado na invoice</i>
                "status": "Pendente", <i>Status da invoice (A = Aguardando, P = Pago, S = Pago com valor superior ao cobrado, I = Pago com valor inferior ao da invoice, C = Cancelada)</i>
                "datacriacao": "05/12/2017", <i>Data em que a invoice foi criada (Formato dd/mm/yyyy hh:mm:ss)</i>
                "datadeposito": "05/12/2017", <i>Data em que o cliente fez o último depósito (Formato dd/mm/yyyy hh:mm:ss)</i>
                "email": "fulano@fulano.com.br", <i>Email cadastrado na invoice</i>
                "celular": "1199999999", <i>celular cadastrado na invoice </i>
                "pdv": "Nome do PDV", <i>Identificação do PDV </i>
                "moeda": "BTC", <i>Moeda que será creditada na conta do estabelecimento</i>
                "estabelecimento": "Nome do estabelecimento", <i>identificação do estabelecimento</i>
                "cotacao": "42320.00", <i>Preço do BTC no momento da criação da invoice</i>
                "saldoRecebido": "0.004", <i>Valor total em BTC depositado no endereço de recebimento da invoice</i>
            }
        ]
    }
</code>

<b>Exemplo de retorno com erro:</b></p> 

<code>
{
    "sucesso": false,
    "mensagem": "Mensagem descritiva de erro"
}
</code>
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        
                        
                        <div class="faq-item">
                            <div class="row">
                                <div class="col-md-7">
                                    <a data-toggle="collapse" href="#faq8" class="faq-question collapsed" aria-expanded="false">Pagar Invoice (Somente SANDBOX) </a>
                                    
                                </div>
                                <div class="col-md-4">
                                    <i class="fa fa-clock-o"></i> <small>Terça-feira 15:37 - 6/03/2018</small>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-12">
                                    <div id="faq8" class="panel-collapse collapse" aria-expanded="false" style="height: 0px;">
                                        <div class="faq-answer">
                                            <p>
Método reponsável por pagar a invoice com os dados fornecidos e chamar a URL de callback se configurada.</br>

Endpoint: <b>/api/pdv/pay</b></br>
Verbo: <b>POST</b></p>
    
<b>Parâmetros:</b> </br>
<b>@param String token</b>          =   Obrigatório. Token de Login </br>
<b>@param String chave</b>          =   Obrigatório. A chave de SANDBOX do PDV que deve ser informada. </br>
<b>@param String carteira</b>     =   Obrigatório. Endereço bitcoin da invoice SANDBOX que terá o saldo incrementado. </br>
<b>@param Numeric volume</b>         =   Obrigatório. Volume BTC que será pago pela invoice.</br>
     

<b>Exemplo de retorno com sucesso:</b></p> 

<code>
    {
        "sucesso": true
    }
</code>

<b>Exemplo de retorno com erro:</b></p> 

<code>
{
    "sucesso": false,
    "mensagem": "Mensagem descritiva de erro"
}
</code>
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        
                    </div>
</div>
</div>

    
    <div class="clearfix"></div>
</div>

<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>

