<?php

$moedas = isset($_data["moedas"]) ? $_data["moedas"] : Array();
$moeda = \Modules\principal\Controllers\Principal::getCurrency();
?>

<?php Utils\Layout::append("inspina/metas", $_data) ?>

<?php Utils\Layout::append("inspina/scripts", $_data) ?>

<style>
    code {
        white-space: pre-wrap;
        color: #047cc1;
    }
    code i {
        color: #545454;
    }
</style>

<?php Utils\Layout::append("inspina/menu", $_data) ?>

    
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
            <div class="row wrapper border-bottom page-heading" style="background: linear-gradient(to right, #fff, <?php echo $moeda->mainColor ?>) !important;">
                <div class="col-lg-10">
                    <h2>Tabelas</h2>
                    <ol class="breadcrumb" style="background-color: transparent !important;">
                        <li>
                            Documentação - API
                        </li>
                        <li class="active">
                            <strong>Tabelas</strong>
                        </li>
                    </ol>
                </div>
            </div>
</div>
<br>     
<div class="wrapper wrapper-content">
    <div class="col-lg-12">
                    <div class="wrapper wrapper-content animated fadeInRight">

                        <div class="ibox-content m-b-sm border-bottom">
                            <div class="text-center p-lg">
                                <h2>Documentação - Tabelas utilizadas nas APIs</h2>
                                
                            </div>
                        </div>

                        <div class="faq-item">
                            <div class="row">
                                <div class="col-md-7">
                                    <a data-toggle="collapse" href="#faq1" class="faq-question collapsed" aria-expanded="false">Código das Moedas</a>
                                    
                                </div>
                                <div class="col-md-4">
                                    <i class="fa fa-clock-o"></i> Terça-feira 18:55 - 5/12/2017</small>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-12">
                                    <div id="faq1" class="panel-collapse collapse" aria-expanded="false" style="height: 0px;">
                                        <div class="faq-answer">
                                            
                                            <div class="ibox float-e-margins">
                                                <div class="ibox-title">
                                                    <h5>Tabela de Código das Moedas</h5>
                                                </div>
                                                <div class="ibox-content">

                                                    <table class="table">
                                                        <thead>
                                                            <tr>
                                                                <th>Código</th>
                                                                <th>Moeda</th>
                                                                <th>Nome</th>
                                                                <th>Logo</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>

                                                        <?php 
                                                        foreach ($moedas as $moeda) {
                                                        ?>
                                                        <tr>
                                                            <td><?php echo $moeda->id ?></td>
                                                            <td><?php echo $moeda->simbolo ?></td>
                                                            <td><?php echo $moeda->nome ?></td>
                                                            <td><img src="<?php echo IMAGES ?>currencies/<?php echo $moeda->icone ?>"  style="width: 40px;" /></td>
                                                        </tr>
                                                        <?php 
                                                        }
                                                        ?>
                                                        
                                                        </tbody>
                                                    </table>

                                                </div>
                                            </div>
                                            
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        
                    </div>
</div>
</div>
    
    <div class="clearfix"></div>
</div>

<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>

