<?php Utils\Layout::append("inspina/metas", $_data) ?>

<?php Utils\Layout::append("inspina/scripts", $_data) ?>
<?php
$moeda = \Modules\principal\Controllers\Principal::getCurrency();
?>
<style>
    code {
        white-space: pre-wrap;
        color: #047cc1;
    }
    code i {
        color: #545454;
    }
</style>

<?php Utils\Layout::append("inspina/menu", $_data) ?>

    
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
            <div class="row wrapper border-bottom page-heading" style="background: linear-gradient(to right, #fff, <?php echo $moeda->mainColor ?>) !important;">
                <div class="col-lg-10">
                    <h2>Carteira</h2>
                    <ol class="breadcrumb" style="background-color: transparent !important;">
                        <li>
                            Documentação - API
                        </li>
                        <li class="active">
                            <strong>Carteiras</strong>
                        </li>
                    </ol>
                </div>
            </div>
</div>
<br>     
<div class="wrapper wrapper-content">
    <div class="col-lg-12">
                    <div class="wrapper wrapper-content animated fadeInRight">

                        <div class="ibox-content m-b-sm border-bottom">
                            <div class="text-center p-lg">
                                <h2>Documentação - API de Carteiras</h2>
                                
                            </div>
                        </div>

                        <div class="faq-item">
                            <div class="row">
                                <div class="col-md-7">
                                    <a data-toggle="collapse" href="#faq1" class="faq-question collapsed" aria-expanded="false">Autenticação</a>
                                    
                                </div>
                                <div class="col-md-4">
                                    <i class="fa fa-clock-o"></i> Terça-feira 18:55 - 5/12/2017</small>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-12">
                                    <div id="faq1" class="panel-collapse collapse" aria-expanded="false" style="height: 0px;">
                                        <div class="faq-answer">
                                            
Para utilizar os métodos da API é necessário para cada requisição efetuar o login utilizando o seguinte endpoint:</p>

Endpoint: <b>/api/auth</b></br>
Verbo: <b>POST</b></p>

<b>Parâmetros:</b> </br>
<b>@param String email</b>   =   Email de login (obrigatório)</br>
<b>@param String senha</b>   =  Senha de login (obrigatório)</p>

<b>Retorno:</b></p>

<code>
    {
        "sucesso" => true, <i>true or false</i>
        "mensagem" => '' <i>se sucesso for false indica o motivo do erro</i>
        "token" => '' <i>se sucesso for true retorna o token de acesso</i>
    }
</code>


                                            
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="faq-item">
                            <div class="row">
                                <div class="col-md-7">
                                    <a data-toggle="collapse" href="#faq2" class="faq-question collapsed" aria-expanded="false">Cadastrar Nova Carteira</a>
                                    
                                </div>
                                <div class="col-md-4">
                                    <i class="fa fa-clock-o"></i> Terça-feira 18:55 - 5/12/2017</small>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-12">
                                    <div id="faq2" class="panel-collapse collapse" aria-expanded="false" style="height: 0px;">
                                        <div class="faq-answer">
Método responsável por criar uma nova carteira para o cliente ou retornar os dados de uma carteira existente. Incluindo o saldo.</p>

Endpoint: <b>/api/wallet</b></br>
Verbo: <b>POST</b></p>
    
<b>Parâmetros:</b> </br>
<b>@param String token</b>          =   Token de validação do login</br>
<b>@param String chave</b>          =   Chave de identificação do estabelecimento</br>
<b>@param String referencia</b>     =   Referência que identificará o cliente no estabelecimento</br>
<b>@param Integer codigo</b>        =   Código da carteira. Se informado um valor maior que zero a carteira será procurada e os dados da mesma serão retornados. Caso nenhum valor seja passado será criada uma nova carteira e o os dados da nova carteira serão retornados.</p>

<b>@param String parametroUm</b>     =   Informações adicionais</br>
<b>@param String parametroDois</b>     =   Informações adicionais</br>
<b>@param String parametroTres</b>     =   Informações adicionais</br>

<b>Exemplo de retorno com sucesso:</b></p> 

<code>
    {
        "sucesso": true,
        "mensagem": "",
        "codigo": "1234",  <i>Código da carteira</i>
        "endereco": "1E9J1r8pAMAe7qD778uE7gktkT9m7c84CE",  <i>Endereço da carteira</i>
        "referencia": "cliente020",  <i>Identificação do cliente utilizada pelo estabelecimento</i>
        "saldo": "0.00002000",  <i>Saldo da carteira em BTC</i>
        "confirmado": "1",  <i>Indica se a carteira recebeu algum valor depositado pelo cliente</i>
        "parametroUm": "",  <i>Informações adicionais cadastradas anteriormente</i>
        "parametroDois": "",  <i>Informações adicionais cadastradas anteriormente</i>
        "parametroTres": ""  <i>Informações adicionais cadastradas anteriormente</i>
    }
</code>

<b>Exemplo de retorno com erro:</b></p> 
<code>
{
    "sucesso": false,
    "mensagem": "Mensagem descritiva de erro"
}
</code>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="faq-item">
                            <div class="row">
                                <div class="col-md-7">
                                    <a data-toggle="collapse" href="#faq3" class="faq-question collapsed" aria-expanded="false">Listar Carteiras</a>
                                    
                                </div>
                                <div class="col-md-4">
                                    <i class="fa fa-clock-o"></i> Terça-feira 18:55 - 5/12/2017</small>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-12">
                                    <div id="faq3" class="panel-collapse collapse" aria-expanded="false" style="height: 0px;">
                                        <div class="faq-answer">
Método responsável por listar as carteiras do estabelecimento ou  de um cliente específico.</p>

Endpoint: <b>/api/wallet/listar</b></br>
Verbo: <b>POST</b></p>

<b>Parâmetros:</b> </br>
<b>@param String token</b>          =   Obrigatório. Token de Login </br>
<b>@param String chave</b>          =   Obrigatório. A chave do estabelecimento que deve ser informada. Se for informado somente a chave do estabelecimento, todas as carteiras de todos os clientes do estabelecimento serão retornadas.</br>
<b>@param String referencia</b>     =   Opcional. Referência que identifica o cliente. Se informado Todas as carteiras do cliente serão retornadas</p>


<b>Exemplo de retorno com sucesso:</b></p> 
<code>
    {
        "sucesso": true,
        "mensagem": "",
        "wallets": [
            {
                "codigo": "1234",  <i>Código da carteira</i>
                "endereco": "1E9J1r8pAMAe7qD778uE7gktkT9m7c84CE", <i>Endereço da carteira</i>
                "referencia": "cliente020", <i>Identificação do cliente utilizada pelo estabelecimento</i>
                "saldo": "0.00002000", <i>Saldo da carteira em BTC</i>
                "confirmado": "1", <i>Indica se a carteira recebeu algum valor depositado pelo cliente</i>
                "parametroUm": "",  <i>Informações adicionais cadastradas anteriormente</i>
                "parametroDois": "",  <i>Informações adicionais cadastradas anteriormente</i>
                "parametroTres": ""  <i>Informações adicionais cadastradas anteriormente</i>
            }
        ]
    }
</code>

<b>Exemplo de retorno com erro:</b></p> 

<code>
{
    "sucesso": false,
    "mensagem": "Mensagem descritiva de erro"
}
</code>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="faq-item">
                            <div class="row">
                                <div class="col-md-7">
                                    <a data-toggle="collapse" href="#faq4" class="faq-question collapsed" aria-expanded="false">Consulta de Saldo</a>
                                    
                                </div>
                                <div class="col-md-4">
                                    <i class="fa fa-clock-o"></i> Terça-feira 18:55 - 5/12/2017</small>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-12">
                                    <div id="faq4" class="panel-collapse collapse" aria-expanded="false" style="height: 0px;">
                                        <div class="faq-answer">

Retorna o saldo total do estabelecimento assim como retorna o saldo total de cada cliente.</p>

Endpoint: <b>/api/wallet/balance</b></br>
Verbo: <b>POST</b></p>

<b>Parâmetros:</b> </br>
<b>@param String token</b>   =   Obrigatório. Token de Login</br> 
<b>@param String chave</b>   =   Obrigatório. A chave do estabelecimento que deve ser informada.</br> 
<b>@param Integer tipo</b>   =   Obrigatório. 1 = Retorna apenas o saldo do estabelecimento. 2 = Retorna o saldo do estabelecimento e o saldo de cada cliente.</br> 
</p>

<b>Exemplo de retorno com sucesso:</b></p> 
<code>
    {
        "sucesso": true,
        "saldo": 35.87564490, <i>Saldo total do estabelecimento em BTC</i>
        "registros": 1, <i>Quantidade de registros retornados no extrato</i>
        "extrato" : [
            {
                "referencia": "cli020", <i>Referência do cliente</i>
                "saldo": "1.89", <i>Saldo total da referência em BTC</i>
            }
        ]
    }
</code>

<b>Exemplo de retorno com erro:</b></p> 

<code>
{
    "sucesso": false,
    "mensagem": "Mensagem descritiva de erro"
}
</code>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="faq-item">
                            <div class="row">
                                <div class="col-md-7">
                                    <a data-toggle="collapse" href="#faq5" class="faq-question collapsed" aria-expanded="false">Histórico das Carteiras</a>
                                    
                                </div>
                                <div class="col-md-4">
                                    <i class="fa fa-clock-o"></i> Terça-feira 18:55 - 5/12/2017</small>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-12">
                                    <div id="faq5" class="panel-collapse collapse" aria-expanded="false" style="height: 0px;">
                                        <div class="faq-answer">

Retorna todas as transações ocorridas envolvendo as carteiras de clientes do estabelecimento.</p>

Endpoint: <b>/api/wallet/historico</b></br>
Verbo: <b>POST</b></p>

<b>Parâmetros:</b> </br>
<b>@param String token</b>          =   Obrigatório. Token de Login</br> 
<b>@param String chave</b>          =   Obrigatório. A chave do estabelecimento que deve ser informada. Se for informado somente a chave do estabelecimento, todo o histórico de transações do estabelecimento será retornada.</br>
<b>@param String referencia</b>     =   Opcional. Referência que identifica o cliente. Se informado será retornado o histórico de transações de carteiras somente do cliente.</br>
<b>@param Integer codigo</b>        =    Opcional. Identificação da carteira. Se informado serão retornadas somente as transações relacionadas a carteira.</br>

</p>
<b>Exemplo de retorno com sucesso:</b></p> 
<code>
    {
        "sucesso": true,
        "mensagem": "",
        "registros": 1, <i>Quantidade de transações encontradas</i>
        "transacoes": [
            {
                "controle": "1", <i>Identificação do registro histórico</i>
                "referencia": "cliente020", <i>Identificação do cliente utilizada pelo estabelecimento</i>
                "endereco": "1E9J1r8pAMAe7qD778uE7gktkT9m7c84CE", <i>Endereço da carteira</i>
                "valor": "1.9", <i>Valor da transação em BTC</i>
                "tipo": "Saque", <i>Tipo da transação (Deposito, Saque, Atualizacao)</i>
                "data": "2017-11-09 10:25:35" <i>Data e hora da transação </i>
            }
        ]
    }
</code>


<b>Exemplo de retorno com erro:</b></p> 

<code>
{
    "sucesso": false,
    "mensagem": "Mensagem descritiva de erro"
}
</code>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        
                        <div class="faq-item">
                            <div class="row">
                                <div class="col-md-7">
                                    <a data-toggle="collapse" href="#faq6" class="faq-question collapsed" aria-expanded="false">Resgate do Saldo</a>
                                    
                                </div>
                                <div class="col-md-4">
                                    <i class="fa fa-clock-o"></i> Terça-feira 18:55 - 5/12/2017</small>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-12">
                                    <div id="faq6" class="panel-collapse collapse" aria-expanded="false" style="height: 0px;">
                                        <div class="faq-answer">
Efetua o saque do valor informado e credita o valor na conta corrente BTC do dono do estabelecimento. O valor sacado será debitado das carteiras do cliente informado. Se o valor sacado for maior que o saldo de uma carteira o saldo da mesma será consumido por completo e o valor restante será debitado da carteira seguinte e assim sucessivamente. Caso o valor sacado ou restante seja inferior ao valor disponível na carteira será efetuado um consumo parcial do saldo disponível da mesma e o restante do saldo ficará disponível para saque futuro.</br>

Endpoint: <b>/api/wallet/sacar</b></br>
Verbo: <b>POST</b></p>


<b>Parâmetros:</b> </br>
<b>@param String token</b>          =   Obrigatório. Token de Login </br>
<b>@param String chave</b>          =   Obrigatório. A chave do estabelecimento que deve ser informada. </br>
<b>@param String referencia</b>     =   Obrigatório. Referência que identifica o cliente. </br>
<b>@param Numeric valor</b>         =   Obrigatório. Valor em BTC que será sacado</br>
     

<b>Exemplo de retorno com sucesso:</b></p> 

<code>
    {
        "sucesso": true,
        "mensagem": "",
        "transacao" : [
            {
                "protocolo": "1234567", <i>Número de controle da transação</i>
                "data": "2017-11-09 10:25:35", <i>data da transação</i>
                "valor": "1.89", <i>valor da transação em BTC</i>
            }
        ]
    }
</code>

<b>Exemplo de retorno com erro:</b></p> 

<code>
{
    "sucesso": false,
    "mensagem": "Mensagem descritiva de erro"
}
</code>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        
                        
                        
                        
                        
                        
                        <div class="faq-item">
                            <div class="row">
                                <div class="col-md-7">
                                    <a data-toggle="collapse" href="#faq7" class="faq-question collapsed" aria-expanded="false">Adicionar Crédito (Somente carteiras SANDBOX)</a>
                                    
                                </div>
                                <div class="col-md-4">
                                    <i class="fa fa-clock-o"></i> Terça-feira 18:55 - 5/12/2017</small>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-12">
                                    <div id="faq7" class="panel-collapse collapse" aria-expanded="false" style="height: 0px;">
                                        <div class="faq-answer">
Acrescenta o saldo informado a carteira para fins de teste da API. Deve ser usando somente com chave de SANDBOX e informando carteiras de SANDBOX.</br>

Endpoint: <b>/api/wallet/addfounds</b></br>
Verbo: <b>POST</b></p>


<b>Parâmetros:</b> </br>
<b>@param String token</b>          =   Obrigatório. Token de Login </br>
<b>@param String chave</b>          =   Obrigatório. A chave de SANDBOX do estabelecimento que deve ser informada. </br>
<b>@param String carteira</b>     =   Obrigatório. Carteira SANDBOX que terá o saldo incrementado. </br>
<b>@param Numeric volume</b>         =   Obrigatório. Volume BTC a ser acrescentado a carteira</br>
     

<b>Exemplo de retorno com sucesso:</b></p> 

<code>
    {
        "sucesso": true
    }
</code>

<b>Exemplo de retorno com erro:</b></p> 

<code>
{
    "sucesso": false,
    "mensagem": "Mensagem descritiva de erro"
}
</code>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        
                    </div>
</div>
</div>


    
    <div class="clearfix"></div>
</div>

<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>

<script>
         $(document).ready(function(){

             var editor_one = CodeMirror.fromTextArea(document.getElementById("code1"), {
                 lineNumbers: true,
                 matchBrackets: true,
                 styleActiveLine: true,
                 theme:"ambiance"
             });
        });
    </script>


