<?php Utils\Layout::append("inspina/metas", $_data) ?>

<?php Utils\Layout::append("inspina/scripts", $_data) ?>
<?php
$moeda = \Modules\principal\Controllers\Principal::getCurrency();
?>
<style>
    code {
        white-space: pre-wrap;
        color: #047cc1;
    }
    code i {
        color: #545454;
    }
</style>

<?php Utils\Layout::append("inspina/menu", $_data) ?>

    
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
            <div class="row wrapper border-bottom page-heading" style="background: linear-gradient(to right, #fff, <?php echo $moeda->mainColor ?>) !important;">
                <div class="col-lg-10">
                    <h2>Pagamentos</h2>
                    <ol class="breadcrumb" style="background-color: transparent !important;">
                        <li>
                            Documentação - API
                        </li>
                        <li class="active">
                            <strong>Pagamentos</strong>
                        </li>
                    </ol>
                </div>
            </div>
</div>
<br>     
<div class="wrapper wrapper-content">
    <div class="col-lg-12">
                    <div class="wrapper wrapper-content animated fadeInRight">

                        <div class="ibox-content m-b-sm border-bottom">
                            <div class="text-center p-lg">
                                <h2>Documentação - API de Pagamentos Externos (Wallet to Wallet)</h2>
                                
                            </div>
                        </div>

                        
                        <div class="faq-item">
                            <div class="row">
                                <div class="col-md-7">
                                    <a data-toggle="collapse" href="#faq1" class="faq-question collapsed" aria-expanded="false">Cadastrar Nova Pagamento</a>
                                    
                                </div>
                                <div class="col-md-4">
                                    <i class="fa fa-clock-o"></i> <small>Sexta-feira 17:50 - 9/03/2018</small>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-12">
                                    <div id="faq1" class="panel-collapse collapse" aria-expanded="false" style="height: 0px;">
                                        <div class="faq-answer">
Método responsável por criar um novo pagamento no sistema. </p>

Endpoint: <b>/api/payment</b></br>
Verbo: <b>POST</b></p>
    
<b>Parâmetros:</b> </br>
<b>@param String key</b>          =   (Obrigatório) Chave da API de pagamento cadastrada na tela de perfil do cliente</br>
<b>@param String origem</b>          =   (Obrigatório) Endereço bitcoin de origem</br>
<b>@param String destino</b>     =   (Obrigatório) Endereço bitcoin de destino</br>
<b>@param Integer volume</b>        =   (Obrigatório)  Volume bitcoin a ser enviado do endereço de origem para o endereço de destino<br>
<b>@param Integer callback</b>        =   URL de callback que será chamada quando identificada transação da carteira de origem para a carteira de destino<br>
<b>@param Integer parametroUm</b>        =   Parametro adicional para uso do sistema do cliente<br>
<b>@param Integer parametroDois</b>        =   Parametro adicional para uso do sistema do cliente<br>
<b>@param Integer parametroTres</b>        =   Parametro adicional para uso do sistema do cliente<br>

<br><br>
<b>Exemplo de retorno com sucesso:</b><br><br>


<code>
    {
        "sucesso": true,
        "mensagem": "",
        "codigo": "1234",  <i>Código do pagamento cadastrado no sistema. Este código deverá ser usado para consulta posterior</i>
        "destino": "1E9J1r8pAMAe7qD778uE7gktkT9m7c84CE",  <i>Endereço da carteira de destino</i>
        "origem": "1E9J1r8pAMAe7qD778uE7gktkT9m7c84CE",  <i>Endereço da carteira de origem</i>
        "volume": "0.00002000",  <i>Volume a ser pago da carteira de origem para a carteira de destino</i>
        "callback": "URL",  <i>URL de callback que será chamada quando uma transação da carteira de origem for identificada para a carteira de destino</i>
        "status": "A",  <i>Status do pagamento: A = Aberto, P = Pago, C = Cancelado</i>
        "hash": "",  <i>Hash da transação encontrada</i>
        "volumePago": "0.00002000",  <i>Volume que foi enviado da carteira de origem para a carteira de destino</i>
        "dataPagamento": "09/03/2017 17:15:24",  <i>Data em que o pagamento foi identificado no formato DD/MM/YYYY HH:MM:SS</i>
        "parametroUm": "",  <i>Informações adicionais cadastradas anteriormente</i>
        "parametroDois": "",  <i>Informações adicionais cadastradas anteriormente</i>
        "parametroTres": ""  <i>Informações adicionais cadastradas anteriormente</i>
    }
</code>

<b>Exemplo de retorno com erro:</b></p> 
<code>
{
    "sucesso": false,
    "mensagem": "Mensagem descritiva de erro"
}
</code>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="faq-item">
                            <div class="row">
                                <div class="col-md-7">
                                    <a data-toggle="collapse" href="#faq2" class="faq-question collapsed" aria-expanded="false">Consultar Pagamento</a>
                                    
                                </div>
                                <div class="col-md-4">
                                    <i class="fa fa-clock-o"></i> Sexta-feira 17:50 - 9/03/2018</small>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-12">
                                    <div id="faq2" class="panel-collapse collapse" aria-expanded="false" style="height: 0px;">
                                        <div class="faq-answer">
Endpoint para consulta das informações de um pagamento </p>

Endpoint: <b>/api/payment</b></br>
Verbo: <b>POST</b></p>
    
<b>Parâmetros:</b> </br>
<b>@param String key</b>          =   (Obrigatório) Chave da API de pagamento cadastrada na tela de perfil do cliente</br>
<b>@param String codigo</b>          =   (Obrigatório) Código do pagamento obtido no momento do cadastro</br>

<br><br>
<b>Exemplo de retorno com sucesso:</b><br><br>


<code>
    {
        "sucesso": true,
        "mensagem": "",
        "codigo": "1234",  <i>Código do pagamento cadastrado no sistema. Este código deverá ser usado para consulta posterior</i>
        "destino": "1E9J1r8pAMAe7qD778uE7gktkT9m7c84CE",  <i>Endereço da carteira de destino</i>
        "origem": "1E9J1r8pAMAe7qD778uE7gktkT9m7c84CE",  <i>Endereço da carteira de origem</i>
        "volume": "0.00002000",  <i>Volume a ser pago da carteira de origem para a carteira de destino</i>
        "callback": "URL",  <i>URL de callback que será chamada quando uma transação da carteira de origem for identificada para a carteira de destino</i>
        "status": "A",  <i>Status do pagamento: A = Aberto, P = Pago, C = Cancelado</i>
        "hash": "",  <i>Hash da transação encontrada</i>
        "volumePago": "0.00002000",  <i>Volume que foi enviado da carteira de origem para a carteira de destino</i>
        "dataPagamento": "09/03/2017 17:15:24",  <i>Data em que o pagamento foi identificado no formato DD/MM/YYYY HH:MM:SS</i>
        "parametroUm": "",  <i>Informações adicionais cadastradas anteriormente</i>
        "parametroDois": "",  <i>Informações adicionais cadastradas anteriormente</i>
        "parametroTres": ""  <i>Informações adicionais cadastradas anteriormente</i>
    }
</code>

<b>Exemplo de retorno com erro:</b></p> 
<code>
{
    "sucesso": false,
    "mensagem": "Mensagem descritiva de erro"
}
</code>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="faq-item">
                            <div class="row">
                                <div class="col-md-7">
                                    <a data-toggle="collapse" href="#faq3" class="faq-question collapsed" aria-expanded="false">Atualizar dados do pagamento</a>
                                    
                                </div>
                                <div class="col-md-4">
                                    <i class="fa fa-clock-o"></i> <small>Quinta-feira 15-55 - 15/03/2018</small>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-12">
                                    <div id="faq3" class="panel-collapse collapse" aria-expanded="false" style="height: 0px;">
                                        <div class="faq-answer">
                                            <p>
                                                Método responsável por atualizar os dados fornecidos de um pagamento. <br>
                                                <strong>Só é possível alterar os dados de um pagamento pendente. Pagamentos realizados ou cancelados não podem ser editados.</strong>
                                            </p>

Endpoint: <b>/api/payment/change</b></br>
Verbo: <b>POST</b></p>
    
<b>Parâmetros:</b> </br>
<b>@param String key</b>          =   (Obrigatório) Chave da API de pagamento cadastrada na tela de perfil do cliente</br>
<b>@param String origem</b>          =   (Opcional) Informe para atualizar a origem</br>
<b>@param String destino</b>     =   (Opcional) Informe para atualizar o destino</br>
<b>@param Integer volume</b>        =   (Opcional)  Informe para atualizar o volume<br>
<b>@param Integer callback</b>        =   (Opcional) informe para atualizar a URL de callback<br>
<b>@param Integer parametroUm</b>        =   (Opcional) Informe para atualizar o campo parametro um<br>
<b>@param Integer parametroDois</b>        =  (Opcional) Informe para atualizar o campo parametro dois<br>
<b>@param Integer parametroTres</b>        =    (Opcional) Informe para atualizar o campo parametro três<br>

<br><br>
<b>Exemplo de retorno com sucesso:</b><br><br>


<code>
    {
        "sucesso": true,
        "mensagem": "",
        "codigo": "1234",  <i>Código do pagamento cadastrado no sistema. Este código deverá ser usado para consulta posterior</i>
        "destino": "1E9J1r8pAMAe7qD778uE7gktkT9m7c84CE",  <i>Endereço da carteira de destino</i>
        "origem": "1E9J1r8pAMAe7qD778uE7gktkT9m7c84CE",  <i>Endereço da carteira de origem</i>
        "volume": "0.00002000",  <i>Volume a ser pago da carteira de origem para a carteira de destino</i>
        "callback": "URL",  <i>URL de callback que será chamada quando uma transação da carteira de origem for identificada para a carteira de destino</i>
        "status": "A",  <i>Status do pagamento: A = Aberto, P = Pago, C = Cancelado</i>
        "hash": "",  <i>Hash da transação encontrada</i>
        "volumePago": "0.00002000",  <i>Volume que foi enviado da carteira de origem para a carteira de destino</i>
        "dataPagamento": "09/03/2017 17:15:24",  <i>Data em que o pagamento foi identificado no formato DD/MM/YYYY HH:MM:SS</i>
        "parametroUm": "",  <i>Informações adicionais cadastradas anteriormente</i>
        "parametroDois": "",  <i>Informações adicionais cadastradas anteriormente</i>
        "parametroTres": ""  <i>Informações adicionais cadastradas anteriormente</i>
    }
</code>

<b>Exemplo de retorno com erro:</b></p> 
<code>
{
    "sucesso": false,
    "mensagem": "Mensagem descritiva de erro"
}
</code>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                    </div>
</div>
</div>


    
    <div class="clearfix"></div>
</div>

<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>

<script>
         $(document).ready(function(){

             var editor_one = CodeMirror.fromTextArea(document.getElementById("code1"), {
                 lineNumbers: true,
                 matchBrackets: true,
                 styleActiveLine: true,
                 theme:"ambiance"
             });
        });
    </script>


