<?php Utils\Layout::append("inspina/metas", $_data) ?>

<?php Utils\Layout::append("inspina/scripts", $_data) ?>
<?php
$moeda = \Modules\principal\Controllers\Principal::getCurrency();
?>
<style>
    code {
        white-space: pre-wrap;
        color: #047cc1;
    }
    code i {
        color: #545454;
    }
</style>

<?php Utils\Layout::append("inspina/menu", $_data) ?>

    
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
            <div class="row wrapper border-bottom page-heading" style="background: linear-gradient(to right, #fff, <?php echo $moeda->mainColor ?>) !important;">
                <div class="col-lg-10">
                    <h2>Transferência</h2>
                    <ol class="breadcrumb" style="background-color: transparent !important;">
                        <li>
                            Documentação - API
                        </li>
                        <li class="active">
                            <strong>Transferência</strong>
                        </li>
                    </ol>
                </div>
            </div>
</div>
<br>     
<div class="wrapper wrapper-content">
    <div class="col-lg-12">
                    <div class="wrapper wrapper-content animated fadeInRight">

                        <div class="ibox-content m-b-sm border-bottom">
                            <div class="text-center p-lg">
                                <h2>Documentação - API de Transferência</h2>
                                
                            </div>
                        </div>

                        <div class="faq-item">
                            <div class="row">
                                <div class="col-md-7">
                                    <a data-toggle="collapse" href="#faq1" class="faq-question collapsed" aria-expanded="false">Autenticação</a>
                                    
                                </div>
                                <div class="col-md-4">
                                    <i class="fa fa-clock-o"></i> Terça-feira 18:55 - 5/12/2017</small>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-12">
                                    <div id="faq1" class="panel-collapse collapse" aria-expanded="false" style="height: 0px;">
                                        <div class="faq-answer">

                                            Para utilizar os métodos da API é necessário para cada requisição efetuar o login utilizando o seguinte endpoint:</p>
                                            <br>
                                            Endpoint: <b>/api/auth</b>
                                            <br>
                                            Verbo: <b>POST</b></p>
                                            <br>
                                            <b>Parâmetros:</b>
                                            <br>
                                            <b>@param String email</b>   =   Email de login (obrigatório)<br>
                                            <b>@param String senha</b>   =  Senha de login (obrigatório)</p>
                                            <br>
                                            <b>Retorno:</b></p>

                                            <br>
<code>
    {
        "sucesso" => true, <i>true or false</i>
        "mensagem" => '' <i>se sucesso for false indica o motivo do erro</i>
        "token" => '' <i>se sucesso for true retorna o token de acesso</i>
    }
</code>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="faq-item">
                            <div class="row">
                                <div class="col-md-7">
                                    <a data-toggle="collapse" href="#faq2" class="faq-question collapsed" aria-expanded="false">Realizar Transferência</a>
                                    
                                </div>
                                <div class="col-md-4">
                                    <i class="fa fa-clock-o"></i> Terça-feira 18:55 - 5/12/2017</small>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-12">
                                    <div id="faq2" class="panel-collapse collapse" aria-expanded="false" style="height: 0px;">
                                        <div class="faq-answer">
Este método realiza transferência de volume BTC da sua conta para a conta informada como parâmetro.</br>

Endpoint: <b>/api/btc/transferir</b></br>
Verbo: <b>POST</b></p></br>
    
<b>Parâmetros:</b> </br> 
<b>@param Integer moeda</b>     =    Código da moeda (vide <a href="<?php echo URLBASE_CLIENT . \Utils\Rotas::DOC_API_TABELAS ?>" target="_BLANK_TABELAS">tabela</a>). <br>
<b>@param String token</b>     =    Token de validação do login </br>
<b>@param String endereco</b>     =    Endereço de carteira Bitcoin para a qual o valor será transferido</br>
<b>@param String descricao</b>     =    Texto descritivo da transferência.</br>
<b>@param Numeric valor</b>     =    Valor a ser transferido. A comissão sobre transferência será acrescida ao valor informado.</p> <br>

    
<b>Exemplo de retorno com sucesso:</b></p> 
<code>
{
    "sucesso": true,
    "mensagem": "",
    "transacao": {
            "controle": "1234",  <i>Identificação da transação</i>
            "endereco": "1E9J1r8pAMAe7qD778uE7gktkT9m7c84CE", <i>Endereço da carteira de destino</i>
            "descricao": "Transferencia para fulano", <i>Texto descritivo da transação</i>
            "valor": "0.00002000", <i>Montante transferido</i>
            "status": "Pendente", <i>Status da transação (Pendente ou Executada)</i>
            "data": "05/12/2017", <i>Data da transação (Formato dd/mm/yyyy)</i>
            "hash": "Pendente", <i>Hash da transação na blockchain (Somente se a transferência for para uma carteira de fora da Exchange)</i>
            "comissao": "0.00000100", <i>Comissão de transferência cobrada</i>
            "moeda": "BTC" <i>Código da moeda</i>
        }
    }
</code>

<b>Exemplo de retorno com erro:</b></p> 

<code>
{
    "sucesso": false,
    "mensagem": "Mensagem descritiva de erro"
}
</code>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="faq-item">
                            <div class="row">
                                <div class="col-md-7">
                                    <a data-toggle="collapse" href="#faq3" class="faq-question collapsed" aria-expanded="false">Consultar Transferência</a>
                                    
                                </div>
                                <div class="col-md-4">
                                    <i class="fa fa-clock-o"></i> Terça-feira 18:55 - 5/12/2017</small>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-12">
                                    <div id="faq3" class="panel-collapse collapse" aria-expanded="false" style="height: 0px;">
                                        <div class="faq-answer">
Retorna os dados de uma transferência.</br>

Endpoint: <b>/api/btc/transferencia</b></br>
Verbo: <b>POST</b></p>
    
<b>Parâmetros:</b> </br> 
<b>@param String token</b>     =    Token de validação do login </br>
<b>@param String controle</b>     =    Identificação da transação</br>

    
<b>Exemplo de retorno com sucesso:</b></p> 
<code>
{
    "sucesso": true,
    "mensagem": "",
    "transacao": {
        "controle": "1234",  <i>Identificação da transação</i>
        "endereco": "1E9J1r8pAMAe7qD778uE7gktkT9m7c84CE", <i>Endereço da carteira de destino</i>
        "descricao": "Transferencia para fulano", <i>Texto descritivo da transação</i>
        "valor": "0.00002000", <i>Montante transferido</i>
        "status": "Pendente", <i>Status da transação (Pendente ou Executada)</i>
        "data": "05/12/2017", <i>Data da transação (Formato dd/mm/yyyy)</i>
        "hash": "Pendente", <i>Hash da transação na blockchain (Somente se a transferência for para uma carteira de fora da Exchange)</i>
        "moeda": "BTC", <i>Código da moeda</i>
        "comissao": "0.00000100" <i>Comissão de transferência cobrada</i>
    }
}


</code>

<b>Exemplo de retorno com erro:</b></p> 

<code>
{
    "sucesso": false,
    "mensagem": "Mensagem descritiva de erro"
}
</code>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="faq-item">
                            <div class="row">
                                <div class="col-md-7">
                                    <a data-toggle="collapse" href="#faq4" class="faq-question collapsed" aria-expanded="false">Listar Transferências</a>
                                    
                                </div>
                                <div class="col-md-4">
                                    <i class="fa fa-clock-o"></i> Terça-feira 18:55 - 5/12/2017</small>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-12">
                                    <div id="faq4" class="panel-collapse collapse" aria-expanded="false" style="height: 0px;">
                                        <div class="faq-answer">
Lista as transferências realizadas no período solicitado</br>

Endpoint: <b>/api/btc/listartransferencias</b></br>
Verbo: <b>POST</b></p>
    
<b>Parâmetros:</b> </br> 
<b>@param String token</b>     =    Token de validação do login </br>
<b>@param String dtinicio</b>     =    Data inicial do filtro</br>
<b>@param String dtfim</b>     =    Data final do filtro.</br>
<b>@param Integer moeda</b>     =    Código da moeda (vide <a href="<?php echo URLBASE_CLIENT . \Utils\Rotas::DOC_API_TABELAS ?>" target="_BLANK_TABELAS">tabela</a>).</br>

    
<b>Exemplo de retorno com sucesso:</b></p> 
<code>
    {
        "sucesso": true,
        "mensagem": "",
        "transacoes": [
            {
                "controle": "1234",  <i>Identificação da transação</i>
                "endereco": "1E9J1r8pAMAe7qD778uE7gktkT9m7c84CE", <i>Endereço da carteira de destino</i>
                "descricao": "Transferencia para fulano", <i>Texto descritivo da transação</i>
                "valor": "0.00002000", <i>Montante transferido</i>
                "status": "Pendente", <i>Status da transação (Pendente ou Executada)</i>
                "data": "05/12/2017", <i>Data da transação (Formato dd/mm/yyyy)</i>
                "hash": "Pendente", <i>Hash da transação na blockchain (Somente se a transferência for para uma carteira de fora da Exchange)</i>
                "moeda": "BTC", <i>Código da moeda</i>
                "comissao": "0.00000100", <i>Comissão de transferência cobrada</i>
            }
        ]
    }
</code>

<b>Exemplo de retorno com erro:</b></p> 

<code>
{
    "sucesso": false,
    "mensagem": "Mensagem descritiva de erro"
}
</code>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>     
                    </div>
</div>
</div>
    
    <div class="clearfix"></div>
</div>

<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>

