
<?php
$clienteHasComissao = Models\Modules\Cadastro\ClienteHasComissaoRn::get();
?>
<?php Utils\Layout::append("inspina/metas", $_data) ?>

<?php Utils\Layout::append("inspina/scripts", $_data) ?>


<?php Utils\Layout::append("inspina/menu", $_data) ?>




    
    <!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
            <div class="row wrapper border-bottom white-bg page-heading">
                <div class="col-lg-10">
                    <h2>Comissões de Clientes</h2>
                    <ol class="breadcrumb">
                        <li>
                            Configurações
                        </li>
                        <li class="active">
                            <strong>Comissões</strong>
                        </li>
                    </ol>
                </div>
            </div>
</div>
<br>
    <!-- Main content -->
    <section class="content">

        <div class="row">
            <div class="col-lg-12">
                
                <div class="panel-body">
                    <div class="row">
                        <div class="col col-lg-6">
                            <div class="form-group">
                                <label>Comissão em depósitos (%)</label>
                                <input type="text" id="dialogClientesHasComissaoDeposito" class="form-control dialog-comissao-real" name="dialogClientesHasComissaoDeposito" value="<?php echo number_format($clienteHasComissao->deposito, 2, ",", "")?>" />
                            </div>
                        </div>
                        <div class="col col-lg-6">
                            <div class="form-group">
                                <label>Comissão em Saques (%)</label>
                                <input type="text" id="dialogClientesHasComissaoSaque" class="form-control dialog-comissao-real" name="dialogClientesHasComissaoSaque" value="<?php echo number_format($clienteHasComissao->saque, 2, ",", "")?>" />
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col col-lg-6">
                            <div class="form-group">
                                <label>Comissão em Boletos (%)</label>
                                <input type="text" id="dialogClientesHasComissaoBoleto" class="form-control dialog-comissao-real" name="dialogClientesHasComissaoBoleto"  value="<?php echo number_format($clienteHasComissao->boleto, 2, ",", "")?>"  />
                            </div>
                        </div>
                        <div class="col col-lg-6">
                            <div class="form-group">
                                <label>Comissão em Remessas (%)</label>
                                <input type="text" id="dialogClientesHasComissaoRemessa" class="form-control dialog-comissao-real" name="dialogClientesHasComissaoRemessa"  value="<?php echo number_format($clienteHasComissao->remessa, 2, ",", "")?>"  />
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col col-lg-6">
                            <div class="form-group">
                                <label>Comissão em Compra (%)</label>
                                <input type="text" id="dialogClientesHasComissaoCompra" class="form-control dialog-comissao-real" name="dialogClientesHasComissaoCompra"  value="<?php echo number_format($clienteHasComissao->compra, 2, ",", "")?>"  />
                            </div>
                        </div>
                        <div class="col col-lg-6">
                            <div class="form-group">
                                <label>Comissão em Venda (%)</label>
                                <input type="text" id="dialogClientesHasComissaoVenda" class="form-control dialog-comissao-real" name="dialogClientesHasComissaoVenda"  value="<?php echo number_format($clienteHasComissao->venda, 2, ",", "")?>" />
                            </div>
                        </div>
                    </div>

                    <br><br>

                    <div class="row">
                        <div class="col col-lg-12 text-center">

                            <?php if (\Models\Modules\Acesso\RotinaRn::validar(\Utils\Rotas::R_CRIPTOCURRENCIES_FEES, \Utils\Constantes::EDITAR)) { ?>
                            <button type="button" class="btn btn-primary" onclick="salvarClienteHasComissao()" id="btn-update">
                                Atualizar Comissões
                            </button>
                            <?php } ?>

                        </div>
                    </div>
                </div>
            </div>

        </div>

    </section>
    
    <div class="clearfix"></div>
</div>

<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>



<script>
    
    $(document).ready(function () {
        $(".dialog-comissao-real").keydown(function (event) {
            if (event.keyCode !== 9) {
                $(this).val(currency($(this).val(), 2, 8, event.keyCode));
                event.preventDefault();
            }
        });
    });
    
    
    function salvarClienteHasComissao() {
    
        $("#dialogClientesHasComissao, #dialogClientesHasComissaoConfirmar").prop("disabled", true);
        $.ajax({
            url: "<?php echo URLBASE_CLIENT . Utils\Rotas::R_CONFIGURACOES_COMISSOES_SALVAR ?>",
            method: "post",
            dataType: "json",
            data: {
                deposito:  $("#dialogClientesHasComissaoDeposito").val(),
                saque:     $("#dialogClientesHasComissaoSaque").val(),
                boleto:    $("#dialogClientesHasComissaoBoleto").val(),
                remessa:   $("#dialogClientesHasComissaoRemessa").val(),
                compra:    $("#dialogClientesHasComissaoCompra").val(),
                venda:     $("#dialogClientesHasComissaoVenda").val(),
                utilizar: ($("#dialogClientesHasComissaoUtilizar").is(":checked") ? 1 : 0)
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#dialogClientesHasComissaoClose").prop("disabled", false).trigger("click");
                        showNotyAlert(json.mensagem, "s");
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#dialogClientesHasComissaoClose, #dialogClientesHasComissaoConfirmar").prop("disabled", false);
            }
        });
        
    }
    
</script>