<?php

$configuracao = isset($_data["configuracao"]) ? $_data["configuracao"] : new Models\Modules\Cadastro\ConfiguracaoSite();
//$configuracao = new Models\Modules\Cadastro\ConfiguracaoSite();
?>


<?php Utils\Layout::append("inspina/metas", $_data) ?>

<?php Utils\Layout::append("inspina/scripts", $_data) ?>


<?php Utils\Layout::append("inspina/menu", $_data) ?>



    
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
            <div class="row wrapper border-bottom white-bg page-heading">
                <div class="col-lg-10">
                    <h2>Painel de Controle</h2>
                    <ol class="breadcrumb">
                        <li>
                            Configurações
                        </li>
                        <li class="active">
                            <strong>Painel de Controle</strong>
                        </li>
                    </ol>
                </div>
            </div>
</div>  
<br>
    <!-- Main content -->
    <section class="content">

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <?php Utils\Layout::append("mensagem", $_data)?>
                    <div class="panel-heading">
                        Configurações do Sistema
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <form id="form-configuracao" action="<?php echo URLBASE_CLIENT . Utils\Rotas::R_PAINELSITE_SALVAR ?>" method="post" enctype="multipart/form-data">
                            
                            <div class="row">
                                <div class="col col-lg-12">
                                    
                                    <div class="tabs-container">
                                        <ul class="nav nav-tabs">
                                            <li class="active"><a data-toggle="tab" href="#tab-1" aria-expanded="true">Site</a></li>
                                        </ul>
                                        <div class="tab-content">
                                            
                                            
                                            
                                            <div id="tab-1" class="tab-pane active">
                                                <div class="panel-body">
                                                    
                                                    <h2 class="page-header">Centro</h2>
                                                    <br>
                                                    
                                                    <div class="row">
                                                        <div class="col col-lg-5">
                                                            <div class="form-group">
                                                                <label>Título</label>
                                                                <input class="form-control" id="tituloCacentro" name="tituloCacentro" value="<?php echo $configuracao->tituloCacentro?>" />
                                                            </div>
                                                        </div>
                                                        
                                                        <div class="col col-lg-4">
                                                            <div class="form-group">
                                                                <label>URL Botão</label>
                                                                <input class="form-control" id="urlBotaoCacentro" name="urlBotaoCacentro" value="<?php echo $configuracao->urlBotaoCacentro ?>" />
                                                            </div>
                                                        </div>
                                                        
                                                        <div class="col col-lg-3">
                                                            <div class="form-group">
                                                                <label>Label Botão</label>
                                                                <input class="form-control" id="labelBotaoCacentro" name="labelBotaoCacentro" value="<?php echo $configuracao->labelBotaoCacentro ?>" />
                                                            </div>
                                                        </div>
                                                    </div>
                                                    
                                                    
                                                    <div class="row">
                                                        <div class="col col-lg-12">
                                                            <div class="form-group">
                                                                <label>Texto</label>
                                                                <textarea class="form-control" id="textoCacentro" name="textoCacentro"  ><?php echo $configuracao->textoCacentro ?></textarea>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    
                                                    <div class="row">
                                                        <div class="col col-lg-2">
                                                            <div class="form-group">
                                                                <label>Mostrar celular: </label>
                                                                <div class="switch">
                                                                    <div class="onoffswitch">
                                                                        <input type="checkbox" class="onoffswitch-checkbox" name="showCelularCacentro" id="showCelularCacentro" value="1" <?php echo ($configuracao->showCelularCacentro > 0 ? "checked" : "") ?>>
                                                                        <label class="onoffswitch-label" for="showCelularCacentro">
                                                                            <span class="onoffswitch-inner"></span>
                                                                            <span class="onoffswitch-switch"></span>
                                                                        </label>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="col col-lg-2">
                                                            <div class="form-group">
                                                                <label>Mostrar botão: </label>
                                                                <div class="switch">
                                                                    <div class="onoffswitch">
                                                                        <input type="checkbox" class="onoffswitch-checkbox" name="showBotaoCacentro" id="showBotaoCacentro" value="1" <?php echo ($configuracao->showBotaoCacentro > 0 ? "checked" : "") ?>>
                                                                        <label class="onoffswitch-label" for="showBotaoCacentro">
                                                                            <span class="onoffswitch-inner"></span>
                                                                            <span class="onoffswitch-switch"></span>
                                                                        </label>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="col col-lg-2">
                                                            <div class="form-group">
                                                                <label>Mostrar Centro: </label>
                                                                <div class="switch">
                                                                    <div class="onoffswitch">
                                                                        <input type="checkbox" class="onoffswitch-checkbox" name="showCacentro" id="showCacentro" value="1" <?php echo ($configuracao->showCacentro > 0 ? "checked" : "") ?>>
                                                                        <label class="onoffswitch-label" for="showCacentro">
                                                                            <span class="onoffswitch-inner"></span>
                                                                            <span class="onoffswitch-switch"></span>
                                                                        </label>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        
                                                        <div class="col col-lg-6">
                                                            <div class="fileinput fileinput-new input-group" data-provides="fileinput">
                                                                <div class="form-control" data-trigger="fileinput">
                                                                    <i class="glyphicon glyphicon-file fileinput-exists"></i> <span class="fileinput-filename"></span>
                                                                </div>
                                                                <span class="input-group-addon btn btn-default btn-file">
                                                                    <span class="fileinput-new">Selecionar</span>
                                                                    <span class="fileinput-exists">Alterar</span>
                                                                    <input type="file" id="imagemCacentro" name="imagemCacentro" >
                                                                </span>
                                                                <a href="#" class="input-group-addon btn btn-default fileinput-exists" data-dismiss="fileinput">Remover</a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    
                                                    <br>
                                                    <h2 class="page-header">Base</h2>
                                                    <br>
                                                    
                                                    <div class="row">
                                                        <div class="col col-lg-5">
                                                            <div class="form-group">
                                                                <label>Título</label>
                                                                <input class="form-control" id="tituloCabase" name="tituloCabase" value="<?php echo $configuracao->tituloCabase?>" />
                                                            </div>
                                                        </div>
                                                        
                                                        <div class="col col-lg-4">
                                                            <div class="form-group">
                                                                <label>URL Botão</label>
                                                                <input class="form-control" id="urlBotaoCabase" name="urlBotaoCabase" value="<?php echo $configuracao->urlBotaoCabase ?>" />
                                                            </div>
                                                        </div>
                                                        
                                                        
                                                        <div class="col col-lg-3">
                                                            <div class="form-group">
                                                                <label>Label Botão</label>
                                                                <input class="form-control" id="labelBotaoCabase" name="labelBotaoCabase" value="<?php echo $configuracao->labelBotaoCabase ?>" />
                                                            </div>
                                                        </div>
                                                    </div>
                                                    
                                                    
                                                    <div class="row">
                                                        <div class="col col-lg-12">
                                                            <div class="form-group">
                                                                <label>Texto</label>
                                                                <textarea class="form-control" id="textoCabase" name="textoCabase"  ><?php echo $configuracao->textoCabase ?></textarea>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    
                                                    <div class="row">
                                                        <div class="col col-lg-2">
                                                            <div class="form-group">
                                                                <label>Mostrar celular: </label>
                                                                <div class="switch">
                                                                    <div class="onoffswitch">
                                                                        <input type="checkbox" class="onoffswitch-checkbox" name="showCelularCabase" id="showCelularCabase" value="1" <?php echo ($configuracao->showCelularCabase > 0 ? "checked" : "") ?>>
                                                                        <label class="onoffswitch-label" for="showCelularCabase">
                                                                            <span class="onoffswitch-inner"></span>
                                                                            <span class="onoffswitch-switch"></span>
                                                                        </label>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="col col-lg-2">
                                                            <div class="form-group">
                                                                <label>Mostrar botão: </label>
                                                                <div class="switch">
                                                                    <div class="onoffswitch">
                                                                        <input type="checkbox" class="onoffswitch-checkbox" name="showBotaoCabase" id="showBotaoCabase" value="1" <?php echo ($configuracao->showBotaoCabase > 0 ? "checked" : "") ?>>
                                                                        <label class="onoffswitch-label" for="showBotaoCabase">
                                                                            <span class="onoffswitch-inner"></span>
                                                                            <span class="onoffswitch-switch"></span>
                                                                        </label>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="col col-lg-2">
                                                            <div class="form-group">
                                                                <label>Mostrar Centro: </label>
                                                                <div class="switch">
                                                                    <div class="onoffswitch">
                                                                        <input type="checkbox" class="onoffswitch-checkbox" name="showCabase" id="showCabase" value="1" <?php echo ($configuracao->showCabase > 0 ? "checked" : "") ?>>
                                                                        <label class="onoffswitch-label" for="showCabase">
                                                                            <span class="onoffswitch-inner"></span>
                                                                            <span class="onoffswitch-switch"></span>
                                                                        </label>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        
                                                        <div class="col col-lg-6">
                                                            <div class="fileinput fileinput-new input-group" data-provides="fileinput">
                                                                <div class="form-control" data-trigger="fileinput">
                                                                    <i class="glyphicon glyphicon-file fileinput-exists"></i> <span class="fileinput-filename"></span>
                                                                </div>
                                                                <span class="input-group-addon btn btn-default btn-file">
                                                                    <span class="fileinput-new">Selecionar</span>
                                                                    <span class="fileinput-exists">Alterar</span>
                                                                    <input type="file" id="imagemCabase" name="imagemCabase" >
                                                                </span>
                                                                <a href="#" class="input-group-addon btn btn-default fileinput-exists" data-dismiss="fileinput">Remover</a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    
                                                </div>
                                            </div>
                                            
                                        </div>


                                    </div>
                                    
                                </div>
                            </div>
                            
                            
                            
                            <div class="row">
                                <div class="col col-lg-12 text-center">
                                    <br><br><br>
                                    
                                    <?php if (\Models\Modules\Acesso\RotinaRn::validar(\Utils\Rotas::R_PAINELSITE, \Utils\Constantes::EDITAR)) {  ?>
                                    <button class="btn btn-primary btn-lg" type="submit" id="btn-salvar">
                                        Salvar Alterações
                                    </button>
                                    <?php } ?>
                                </div>
                            </div>
                            
                        </form>
                    </div>
                    <!-- /.panel-body -->

                </div>
            </div>

        </div>

        <a  id="openOrder" target="_BLANK"></a>
    </section>
    
    <div class="clearfix"></div>
</div>

<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>

<script>
    $(document).ready(function () {

        
        
        $("#form-configuracao").ajaxForm({
            dataType: "json",
            beforeSubmit: function () {
                $("#btn-salvar").prop("disabled", true);
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        location = "<?php echo URLBASE_CLIENT . Utils\Rotas::R_PAINELSITE ?>";
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#btn-salvar").prop("disabled", false);
            }
        });
        
    });
    
    
    
    
</script>

