<?php
$idioma = new \Utils\PropertiesUtils("docs_aceitacao", IDIOMA);
$id = \Utils\Get::getEncrypted($_data, 0, NULL);

$brand = \Models\Modules\Cadastro\BrandRn::getBrand();
?>



<!DOCTYPE html>
<html class="wide wow-animation smoothscroll scrollTo" lang="pt-br">
<head>
<title><?php echo TITULO ?></title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta http-equiv="cache-control" content="max-age=0" />
<meta http-equiv="cache-control" content="no-cache" />
<meta http-equiv="expires" content="Tue, 01 Jan 2030 1:00:00 GMT" />
<meta http-equiv="pragma" content="no-cache" />
<meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<link href="<?php echo TEMA; ?>css/bootstrap.min.css" rel="stylesheet">
<link href="<?php echo TEMA; ?>font-awesome/css/font-awesome.css" rel="stylesheet">
<link href="<?php echo TEMA; ?>css/animate.css" rel="stylesheet">
<link href="<?php echo TEMA; ?>css/style.css" rel="stylesheet">
<link href="<?php echo TEMA; ?>css/plugins/iCheck/custom.css" rel="stylesheet">
</head>

<body class="" style="background-color: <?php echo $brand->colorBackground ?>">
    <div class="middle-box text-center loginscreen animated fadeInDown">
        <div>
            <h1 class="logo-name" style="font-size: 10px"><a href="/"><img style='margin-top: -5px;margin-left: -15px;' width='200' height='47' src='<?php echo IMAGES . $brand->logo; ?>' alt=''/></a></h1>
        </div>
    </div>
    </br></br>
    <div class="row">
        <div class="col-lg-offset-2 col-lg-8 text-center">
            <h3 class="m-b-md"><?php echo $idioma->getText("mensagemImportante") ?></h3></br>
            <h2 id="nomeMoeda" style="display: inline"></h2>&nbsp;&nbsp;&nbsp;<img class="m-b-xs" src="" id="imagemMoeda" width="30px" height="30px"/>
            <div class="panel panel-default text-center">
                <div class="panel-heading text-center" ><h2 id="tituloIng" style="display: inline;"></h2></div>
                <div class="panel-body text-center" id="descIng" style="white-space: pre-wrap;"></div>
            </div>
            <div class="panel panel-default text-center">
                <div class="panel-heading text-center" ><h2 id="tituloPort" style="display: inline"></h2></div>                
                <div class="panel-body text-center" id="descPort" style="white-space: pre-wrap;"></div>
                <div class="panel-footer pull-right" style="background-color: <?php echo $brand->colorBackground ?>"><button class="btn btn-primary" id="marcarComoLido" onclick="">Continue&nbsp;&nbsp;<i class="fa fa-arrow-circle-o-right"></i></button></div>
            </div>
        </div>            
    </div>
</body>
<script src="<?php echo TEMA; ?>js/jquery-3.1.1.min.js"></script>
<script src="<?php echo TEMA; ?>bootstrap/js/bootstrap.min.js"></script>
<script src="<?php echo TEMA; ?>js/plugins/iCheck/icheck.min.js"></script>
<script>
     $(document).ready(function () {
         listarMensagensMoeda();
    });
    
    function listarMensagensMoeda() {    
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . \Utils\Rotas::R_NOTIFICACAO_MOEDA_ONLY_VIEW_LISTAR ?>',
            method: 'post',
            dataType:'json',
            data: {
                codigo: '<?php echo $id ?>'
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                            $("#nomeMoeda").html(json.nomeMoeda);
                            $("#imagemMoeda").attr("src", json.imagemMoeda);
                            $("#tituloIng").html(json.tituloIng);
                            $("#descIng").html(json.descIng);
                            $("#tituloPort").html(json.tituloPort);
                            $("#descPort").html(json.descPort);                   
                    } else {
                    }
                } catch (e) {
                }
            }
        });
    }    
    
</script>
</body>
</html>