<?php

$dataInicial = new \Utils\Data(date("d/m/Y H:i:s"));
$dataInicial->subtrair(0, 0, 30);
$dataFinal = new \Utils\Data(date("d/m/Y H:i:s"));

?>


<?php Utils\Layout::append("inspina/metas", $_data) ?>

<?php Utils\Layout::append("inspina/scripts", $_data) ?>


<?php Utils\Layout::append("inspina/menu", $_data) ?>



    
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Notas Fiscais</h2>
            <ol class="breadcrumb">
                <li>
                    Configurações
                </li>
                <li class="active">
                    <strong>Painel de Notas Fiscais</strong>
                </li>
            </ol>
        </div>
    </div>
</div>  
<br>
    <!-- Main content -->
    <section class="content">

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    
                    <div class="panel-body">
                        
                        <div class="row">
                            <div class="col col-lg-12">
                                
                                <h4 class="page-header">Emissão manual de nota fiscal</h4>
                                
                                <div class="row">
                                    <div class="col col-sm-5">
                                        <div class="form-group">
                                            <label>Número do depósito ou saque</label>
                                            <input type="text" id="cadastroControle" class="form-control field-emitir" />
                                        </div>
                                    </div>
                                    <div class="col col-sm-5">
                                        <div class="form-group">
                                            <label>Tipo</label>
                                            <select id="cadastroTipo" class="form-control field-emitir">
                                                <option value="d">Depósito</option>
                                                <option value="s">Saque</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col col-sm-2 text-center">
                                        <br>
                                        
                                        <button class="btn btn-primary field-emitir" type="button" onclick="emitirNota();" id="cadastroBtnEmitir">
                                            Emitir NF
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="row">
                        
                            <div class="col col-lg-12">
                                
                                <h4 class="page-header">Filtro de notas fiscais</h4>
                                
                                <div class="row">
                                    <div class="col col-lg-3">
                                        <div class="form-group">
                                            <label>Data inicial</label>
                                            <input type="text" class="form-control" id="filtroDataInicial" value="<?php echo $dataInicial->formatar(\Utils\Data::FORMATO_PT_BR) ?>" onchange="filtrar();" />
                                        </div>
                                    </div>

                                    <div class="col col-lg-3">
                                        <div class="form-group">
                                            <label>Data Final</label>
                                            <input type="text" class="form-control" id="filtroDataFinal" value="<?php echo $dataFinal->formatar(\Utils\Data::FORMATO_PT_BR) ?>" onchange="filtrar();" />
                                        </div>
                                    </div>

                                    <div class="col col-lg-3">
                                        <div class="form-group">
                                            <label>Status da nota</label>
                                            <select class="form-control" id="filtroStatusNota" onchange="filtrar();">
                                                <option value="T">Todas</option>
                                                <option value="<?php echo Utils\Constantes::STATUS_NF_SOLICITANDO_AUTORIZACAO ?>">Solicitando autorização</option>
                                                <option value="<?php echo Utils\Constantes::STATUS_NF_AGUARDANDO_AUTORIZACAO ?>">Aguardando autorização</option>
                                                <option value="<?php echo Utils\Constantes::STATUS_NF_PROCESSANDO_AUTORIZACAO ?>">Em processo de autorização</option>
                                                <option value="<?php echo Utils\Constantes::STATUS_NF_AUTORIZACAO_SOLICITADA ?>">Autorização solicitada</option>
                                                <option value="<?php echo Utils\Constantes::STATUS_NF_AUTORIZADA ?>">Autorizada</option>
                                                <option value="<?php echo Utils\Constantes::STATUS_NF_AGUARDANDO_PDF ?>">Autorizada e aguardadndo geração do PDF</option>
                                                <option value="<?php echo Utils\Constantes::STATUS_NF_NEGADA ?>">Negada</option>
                                                <option value="<?php echo Utils\Constantes::STATUS_NF_SOLICITANDO_CANCELAMENTO ?>">Solicitando cancelamento</option>
                                                <option value="<?php echo Utils\Constantes::STATUS_NF_PROCESSANDO_CANCELAMENTO ?>">Processando cancelamento</option>
                                                <option value="<?php echo Utils\Constantes::STATUS_NF_CANCELAMENTO_SOLICITADO ?>">Cancelamento solicitado</option>
                                                <option value="<?php echo Utils\Constantes::STATUS_NF_CANCELADA ?>">Cancelada</option>
                                                <option value="<?php echo Utils\Constantes::STATUS_NF_CANCELADA_AGUARDANDO_PDF ?>">Cancelada e aguardando atualização do PDF</option>
                                                <option value="<?php echo Utils\Constantes::STATUS_NF_CANCELAMENTO_NEGADO ?>">Cancelamento Negado</option>
                                            </select>
                                        </div>
                                    </div>

                                    <div class="col col-lg-3">
                                        <div class="form-group">
                                            <label>Filtro</label>
                                            <input type="text" class="form-control" id="filtroTexto" onkeyup="filtrar();" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                  
                        <div class="row">
                            <div class="col col-lg-4" >
                                Qtd Notas: <strong id="notas"></strong>
                            </div>
                            <div class="col col-lg-4">
                                Depósitos: <strong  id="depositos"></strong>
                            </div>
                            <div class="col col-lg-4">
                                Saques: <strong id="saques"></strong>
                            </div>
                            <div class="col col-lg-4">
                                Autorizadas: <strong id="autorizadas"> </strong>
                            </div>
                            <div class="col col-lg-4" >
                                Aguardadando Autorização: <strong id="autorizacaoSolicitada"> </strong>
                            </div>
                            <div class="col col-lg-4" >
                                Canceladas: <strong id="canceladas"></strong>
                            </div>
                            <div class="col col-lg-4" >
                                Cancelamento Negado: <strong id="cancelamentoNegado"> </strong>
                            </div>
                            <div class="col col-lg-4">
                                Cancelamento Solicitado: <strong id="cancelamentoSolicitado"></strong>
                            </div>
                            <div class="col col-lg-4" >
                                Negadas: <strong id="negada"></strong>
                            </div>
                        </div>
                        
                    </div>
                    <!-- /.panel-body -->

                </div>
                    <div class="row">
                            <div class="col-lg-12 table-responsive">
                                <table class="table table-striped table-hover table-condensed table-bordered" style="font-size: 10px; background-color: #fff">
                                    <thead>
                                        <tr>
                                            <th class="text-center"><strong>Controle</strong></th>
                                            <th class="text-center"><strong>Data</strong></th>
                                            <th class="text-center"><strong>Cliente</strong></th>
                                            <th class="text-center"><strong>NF-ID</strong></th>
                                            <th class="text-center"><strong>Tipo</strong></th>
                                            <th class="text-center"><strong>Total</strong></th>
                                            <th class="text-center"><strong>Valor NF</strong></th>
                                            <th class="text-center"><strong>NF</strong></th>
                                            <th class="text-center"><strong>Status</strong></th>
                                            <th class="text-center"><strong>PDF</strong></th>
                                            <th class="text-center"><strong>XML</strong></th>
                                            <th class="text-center"><strong>Atualizar</strong></th>
                                            <th class="text-center"><strong>Cancelar</strong></th>
                                        </tr>
                                    </thead>
                                    <tbody id="listanfs">

                                    </tbody>
                                </table>
                            </div>
            </div>

        </div>

        <a  id="openOrder" target="_BLANK"></a>
    </section>
    
    <div class="clearfix"></div>
</div>

<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>

<script>
    $(document).ready(function () {
        $("#filtroDataInicial, #filtroDataFinal").datepicker({format: "dd/mm/yyyy"}).mask("99/99/9999");
        
        filtrar();
    });
    
    function filtrar() {
        
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_NOTASFISCAIS_FILTRAR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                dataInicial: $("#filtroDataInicial").val(),
                dataFinal: $("#filtroDataFinal").val(),
                status: $("#filtroStatusNota").val(),
                filtro: $("#filtroTexto").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#listanfs").html(json.html);
                        
                        $("#notas").html(json.notas);
                        $("#depositos").html(json.depositos);
                        $("#saques").html(json.saques);
                        $("#autorizadas").html(json.autorizadas);
                        $("#autorizacaoSolicitada").html(json.autorizacaoSolicitada);
                        $("#canceladas").html(json.canceladas);
                        $("#cancelamentoNegado").html(json.cancelamentoNegado);
                        $("#cancelamentoSolicitado").html(json.cancelamentoSolicitado);
                        $("#negada").html(json.negada);
                        
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
            }
        });
        
    }
    
    
    function emitirNota() {
        $(".field-emitir").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_NOTASFISCAIS_EMITIR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                controle: $("#cadastroControle").val(),
                tipo: $("#cadastroTipo").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        filtrar();
                        $("#cadastroControle").val("");
                        $("#cadastroTipo").val("d");
                        showNotyAlert(json.mensagem, "s");
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $(".field-emitir").prop("disabled", false);
            }
        });
    }
    
    
    function atualizarStatusNota(identificacao) {
        $("#loading-"+identificacao).show();
        $("#btn-update-"+identificacao).prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_NOTASFISCAIS_ATUALIZAR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                identificacao: identificacao
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#"+json.ref).replaceWith(json.html);
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#loading-"+identificacao).hide();
                $("#btn-update-"+identificacao).prop("disabled", false);
            }
        });
    }
    
    function cancelarNota(identificacao) {
        $("#loading-cancel-"+identificacao).show();
        $("#btn-cancel-"+identificacao).prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_NOTASFISCAIS_CANCELAR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                identificacao: identificacao
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#"+json.ref).replaceWith(json.html);
                        showNotyAlert(json.mensagem, "s");
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#loading-cancel-"+identificacao).hide();
                $("#btn-cancel-"+identificacao).prop("disabled", false);
            }
        });
    }
</script>