<?php
$cliente = Utils\Geral::getCliente();
$moeda = \Modules\principal\Controllers\Principal::getCurrency();
?>

<?php Utils\Layout::append("inspina/metas", $_data) ?>

<?php Utils\Layout::append("inspina/scripts", $_data) ?>

<style>
        
    
</style>

<?php Utils\Layout::append("inspina/menu", $_data) ?>
<div class="content-wrapper">
  <div class="row wrapper border-bottom page-heading" style="background: linear-gradient(to right, #fff, <?php echo $moeda->mainColor ?>) !important;">
    <div class="col-lg-9">
      <ol class="breadcrumb m-t-md" style="background-color: transparent !important;">
          <li>
            <?php echo $idioma->getText("subTitulo") ?>
          </li>
          <li class="active">
              <strong><?php echo $idioma->getText("titulo") ?>
          </li>
      </ol>
    </div>
    <div class="col-lg-3">
    <?php Utils\Layout::append("inspina/flags", $_data) ?>
    </div>
  </div>
</div>


<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            
            <div class="tabs-container">
                <ul class="nav nav-tabs">
                    <li class="active"><a data-toggle="tab" href="#tab-1" aria-expanded="true">Blacklist</a></li>
                    <li class=""><a data-toggle="tab" href="#tab-2" aria-expanded="true">Analisar</a></li>
                    
                </ul>
                <div class="tab-content"> 
           
                    <div id="tab-1" class="tab-pane active">
                <div class="ibox">
                <div class="ibox-content" >
                    
                   <div class="row">
                       
                       <div class="col-xs-12 col-sm-4 m-b-xs">
                            <label>Nome</label>
                            <input id="nome" name="nome" placeholder="Nome do cliente a ser bloqueado" type="text" class="form-control" > 
                        
                       </div>
                        
                       <div class="col-xs-12 col-sm-4 m-b-xs">
                            <label>E-mail</label>
                            <input id="email" name="email" placeholder="E-mail" type="text" class="form-control" > 
                        </div>
                      
                        
                       <div class="col-xs-12 col-sm-2 m-b-xs">
                            <label>CPF</label>
                            <input id="cpf" name="cpf" placeholder="CPF" type="text" class="form-control" > 
                        </div>
                       
                        <div class="col-xs-12 col-sm-2 text-center m-b-xs">
                            <label>&nbsp;</label>
                            <button type="button" class="btn btn-primary full-width" onclick="convidar();" id="btn-convidar">
                                Adicionar
                            </button>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-xs-12 col-sm-10 m-t-xs">
                            <input type="text" class="form-control" id="pesquisa" onkeyup="setTipoFiltro('t');" placeholder="Pesquise pelo nome / e-mail / CPF">
                        </div>
                        
                        <div class="col-xs-12 col-sm-2 text-center m-t-xs">
                            <button class="btn btn-white full-width" type="button" onclick="limpar();">
                                Limpar
                            </button>
                        </div>
                    </div>
                </div>
                </div>
            </div> <!-- Fim da tab 1 -->
        
            <div id="tab-2" class="tab-pane">
                <div class="ibox">
                <div class="ibox-content" >
                    
                   <div class="row">
                       
                       <div class="col-xs-12 col-sm-4 m-b-xs">
                            <label>Nome</label>
                            <input id="nome" name="nome" placeholder="Nome do cliente a ser bloqueado" type="text" class="form-control" > 
                        
                       </div>
                        
                       <div class="col-xs-12 col-sm-4 m-b-xs">
                            <label>E-mail</label>
                            <input id="email" name="email" placeholder="E-mail" type="text" class="form-control" > 
                        </div>
                       
                        </div>
                    </div>
                </div>
                </div>
            </div>
                
                </div>
            </div>

                        <div class="row">
                            <div class="col-lg-12 col-xs-12">
                                <div class="table-responsive">
                                <table class="table table-striped table-hover table-condensed table-bordered" style="font-size: 10px; background-color: #fff">
                                    <thead>
                                        <tr>
                                            <th class="text-center"><strong>Nome</strong></th>
                                            <th class="text-center"><strong>E-mail</strong></th>
                                            <th class="text-center"><strong>CPF</strong></th>
                                            <th class="text-center"><strong>Ação</strong></th>
                                            
                                        </tr>
                                    </thead>

                                    <tbody id="lista-clientes">
                                    </tbody>
                                </table>
                                </div>
                            </div>
                        </div>
        </div>
    </div>
</div>


<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>

<?php Utils\Layout::append("mensage_text", $_data) ?>



<script>
    
    $(document).ready(function () {
        listarClientes();
        
        $("#cpf").mask("999.999.999-99");
    
    });
    
    new Clipboard("#btn-link-ref");
    
    
    var tipoFiltro = "a";

    
    function listarClientes() {
        //$("#lista-clientes").html("<tr><td class='text-center' colspan='4'><img src='<?php echo IMAGES ?>loading.gif' /></td></tr>");
        $.ajax({
            //url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_FRANQUIADO_CLIENTES_LISTAR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                tipoFiltro: tipoFiltro,
                pesquisa: $("#pesquisa").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#lista-clientes").html(json.html);
                        
                    } else {
                        $("#lista-clientes").html("<tr><td class='text-center' colspan='4'>"+json.mensagem+"</td></tr>");
                    }
                } catch (e) {
                    $("#lista-clientes").html("<tr><td class='text-center' colspan='4'>"+e+"</td></tr>");
                }
            }
        });
    }
    
    function setTipoFiltro(tipo) {
        tipoFiltro = tipo;
        listarClientes();
    }
    
    function limpar() {
        tipoFiltro = "a";
        $("#pesquisa").val("");
        listarClientes();
    }
    
    

</script>



