<?php

$cliente = Utils\Geral::getCliente();
$mostrarBotoes = ($paridade->ativo > 0 && $paridade->statusMercado > 0 && $cliente->statusMercado > 0 && $paridade->moedaBook->statusMercado > 0 && $paridade->moedaBook->ativo > 0);
$mostrarAlerta = false;
$mensagemAlerta = "";

$idioma = new \Utils\PropertiesUtils("compra_venda_direta", IDIOMA);

if ($paridade->ativo < 1 || $paridade->moedaBook->ativo < 1) {
  $mostrarAlerta = true;
  $mensagemAlerta = $idioma->getText("mercadoEncerrado");
} else if ($paridade->statusMercado < 1 || $paridade->moedaBook->statusMercado < 1) {
  $mostrarAlerta = true;
  $mensagemAlerta = $idioma->getText("mercadoSupenso");
} else if ($cliente->statusMercado < 1) {
  $mensagemAlerta = $idioma->getText("compraVendaSuspensaConta");
  $mostrarAlerta = true;
}

$configuracao = \Models\Modules\Cadastro\ConfiguracaoRn::get();

$_data["idiomaMenu"] = $idioma;
?>


<?php Utils\Layout::append("inspina/metas", $_data) ?>
<?php Utils\Layout::append("inspina/scripts", $_data) ?>
<?php Utils\Layout::append("inspina/menu", $_data) ?>

<link href="<?php echo TEMA; ?>css.old/plugins/ladda/ladda-themeless.min.css" rel="stylesheet">
<link rel="stylesheet" href="assets/css/dashboard.css">


<!-- <?php echo $configuracao->valorMinSaqueReais ?> -->


<div class="container-fluid mt-3">
  <div class="row">
    <div class="col-12 col-md-11 mx-auto">
      <div class="row justify-content-between">
        <div class="dashboard col-12 mb-5">
          <div class="row">
            <div class="col-12 d-flex">
              <div class="nav nav-pills dashboard-nav" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                <a class="nav-link active" id="dashboard-tab" data-toggle="pill" href="#dashboard" role="tab"
                  aria-controls="dashboard" aria-selected="true"><i class="icon ion-ios-home mr-1"></i>Dashboard</a>
                <a class="nav-link" id="dashboard-portfolio-tab" data-toggle="pill" href="#dashboard-portfolio"
                  role="tab" aria-controls="dashboard-portfolio" aria-selected="false"><i
                    class="icon ion-ios-pie mr-1"></i>Portfólio</a>
                <a class="nav-link" id="dashboard-wallet-tab" data-toggle="pill" href="#dashboard-wallet" role="tab"
                  aria-controls="dashboard-wallet" aria-selected="false"><i class="icon ion-ios-wallet mr-1"></i>Minha
                  Carteira</a>
                <button class="btn btn-sm btn-light ml-2" id="visibility-button"><i class="icon ion-ios-eye"
                    id="eye"></i></button>
              </div>
            </div>
          </div>

          <div class="shadow mt-3">
            <div class="p-3">
              <div class="row">
                <div class="col-lg-8">
                  <h5 class="" id="market-card-title">Sua posição padrão está a mercado</h5>
                  <h5 class="text-hidden" id="curve-card-title">Sua posição padrão está na taxa de compra</h5>
                  <p class="" id="market-radio-text">Posição a mercado é uma estimativa de quanto os ativos valeriam
                    caso fossem resgatados
                    antes
                    do
                    vencimento. Válido para Criptomoedas, Renda Digital, Utility Tokens, Startups e Staking. Os outros ativos são
                    precificados na taxa de compra. Caso queira alterar o seu padrão de visualização para
                    <b>Posição
                      na taxa de compra ("na curva")</b> acesse: <a class="text-dark font-weight-bold btn btn-light"
                      href="#" id="market-radio-toggler">Mudar posição padrão <i
                        class="icon ion-ios-arrow-forward text-warning"></i></a>
                  </p>
                  <p class="text-hidden" id="curve-radio-text">Posição
                    na taxa de compra ("na curva") é um método de atualização dos ganhos em investimentos de renda
                    fixa. Com ela, é possível identificar a rentabilidade, a longo prazo, de uma aplicação.
                    Caso queira alterar o seu padrão de visualização para
                    <b>Posição a mercado (D-1)</b> acesse: <a class="text-dark font-weight-bold btn btn-light" href="#"
                      id="curve-radio-toggler">Mudar posição padrão <i
                        class="icon ion-ios-arrow-forward text-warning"></i></a>
                  </p>
                </div>
                <div class="col-lg-4">
                  <h5 class="theme-color">Recomendados para você</h5>
                  <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner bg-primary rounded">
                      <div class="carousel-item active">
                        <div class="row align-items-center">
                          <div class="col-3">
                            <img src="assets/img/icon/convert.svg" class="d-block w-100 carousel_icon" alt="...">
                          </div>
                          <div class="col-9">
                            <div class="text-white fs-10 mr-4 mt-3 ml-1">
                              <p class="h6">Slide 1</p>
                              <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="carousel-item">
                        <div class="row align-items-center">
                          <div class="col-3">
                            <img src="assets/img/icon/earn.svg" class="d-block w-100 carousel_icon" alt="...">
                          </div>
                          <div class="col-9">
                            <div class="text-white fs-10 mr-4 mt-3 ml-1">
                              <p class="h6">Slide 2</p>
                              <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="carousel-item">
                        <div class="row align-items-center">
                          <div class="col-3">
                            <img src="assets/img/icon/futures.svg" class="d-block w-100 carousel_icon" alt="...">
                          </div>
                          <div class="col-9">
                            <div class="text-white fs-10 mr-4 mt-3 ml-1">
                              <p class="h6">Slide 3</p>
                              <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="carousel-item">
                        <div class="row align-items-center">
                          <div class="col-3">
                            <img src="assets/img/icon/spot.svg" class="d-block w-100 carousel_icon" alt="...">
                          </div>
                          <div class="col-9">
                            <div class="text-white fs-10 mr-4 mt-3 ml-1">
                              <p class="h6">Slide 4</p>
                              <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>

                    <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
                      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                      <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
                      <span class="carousel-control-next-icon" aria-hidden="true"></span>
                      <span class="sr-only">Next</span>
                    </a>

                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="d-flex mt-3">
            <div class="d-flex">
              <a href="#" type="button" id="market-radio-trigger"><i class="icon ion-ios-radio-button-on icon-badge"
                  id="market-radio"></i></a>
              <span class="h5 radio-title ml-1">Posição a mercado (D-1)</span>
            </div>
            <div class="d-flex ml-2">
              <a href="#" type="button" id="curve-radio-trigger"><i class="icon ion-ios-radio-button-off icon-badge"
                  id="curve-radio"></i></a>
              <span class="h5 radio-title ml-1">Posição na taxa de compra ("na curva")</span>
            </div>
          </div>
          <div class="row justify-content-around align-items-center">
            <div class="col-12 col-lg-2 d-flex justify-content-center">
              <div class="" id="dashboard-chart"></div>
              <div class="text-center innerPieText" id="">
                <span class="d-block fs-16 font-weight-bold" id="total-percent"></span>
                <span class="">Total Investido</span>
              </div>
            </div>
            <div class="col-12 col-sm-9 col-lg-10">
              <div class="row mt-3">
                <div class="col-xl-12 mb-3">
                  <div class="row">
                    <div class="col-md-5 text-center mb-3-md">
                      <span class="d-block">
                        <?php echo $cliente->nome ?>, este é o seu patrimônio 
                      </span>
                      <span class="fs-20 d-block font-weight-bold"><span class="balance-hidden">****</span><span
                          class="balance-visible" id="total-balance"></span></span>
                      <span id="current-date"></span>
                    </div>
                    <div class="col-md-7 d-flex vl-60 justify-content-between">
                      <div class="row text-center">
                        <div class="col-12 col-lg-4 mt-2">
                          <span class="d-block">Saldo disponível</span>
                          <span class="fw-bold fs-16"><span class="balance-hidden">****</span><span
                              class="balance-visible" id="available-balance"></span></span>
                        </div>
                        <div class="col-12 col-lg-4 mt-2">
                          <span class="d-block">Total investido</span>
                          <span class="fw-bold fs-16"><span class="balance-hidden">****</span><span
                              class="balance-visible" id="invested-balance"></span></span>
                        </div>
                        <div class="col-12 col-lg-4 mt-2">
                          <span class="d-block">Saldo projetado</span>
                          <span class="fw-bold fs-16"><span class="balance-hidden">****</span><span
                              class="balance-visible" id="projected-balance"></span></span>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div id="div-line"></div>
                  <div class="row">
                    <div class="border-top mt-3">
                      <a href="/extract">
                        <p class="text-dark h6 mt-3 text-center">Consulte o extrato completo da sua conta <i
                            class="icon ion-ios-arrow-forward text-warning"></i></p>
                      </a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="tab-content" id="v-pills-tabContent">
            <div class="tab-pane fade show active" id="dashboard" role="tabpanel" aria-labelledby="dashboard-tab">
              <div class="dashboard shadow">
                <div class="row justify-content-around align-items-center px-3">
                  <div class="col-12 mt-3">
                    <p class="h5">
                      Performance da sua carteira e recomendado para você
                    </p>
                    <p>
                      Acompanhe a performance da sua carteira e também as nossas recomendações. Para visualizar mais
                      detalhes, acessa a aba <b>Minha Carteira</b>.
                    </p>
                  </div>
                  <div class="col-12 ">
                    <p class="mt-3">
                      Performance da sua carteira
                    </p>
                    <div class="row">
                      <div class="col-md-9">
                        <span class="balance-hidden">****ATIVE A VISIBILIDADE DO SALDO PARA VER O GRÁFICO DE
                          PERFORMANCE****</span><span class="balance-visible">
                          <div id="performance-chart"></div>
                        </span>
                      </div>
                      <div class="col-md-3">
                        <div id="rentabilidade-values">
                          <div class="mt-2">
                            <span class="font-weight-bold d-block">
                              Rendimento
                            </span>
                            <span class="text-success">
                              <span class="balance-hidden">****</span><span class="balance-visible">R$ 0,00</span>
                            </span>
                          </div>
                          <div class="mt-2">
                            <span class="font-weight-bold d-block">
                              Rentabilidade
                            </span>
                            <span class="text-success">
                              <span class="balance-hidden">****</span><span class="balance-visible">0,00%</span>
                            </span>
                          </div>
                          <div class="mt-2">
                            <span class="font-weight-bold d-block">
                              Rentabilidade CDI
                            </span>
                            <span class="text-success">
                            <span class="balance-hidden">****</span><span class="balance-visible" id="rentabilidade-cdi">0,00%</span>
                            </span>
                          </div>
                        </div>
                        <div class="mt-5">
                        <a id="visualizar-portfolio" data-toggle="pill" href="#dashboard-portfolio"
                          role="tab" aria-controls="dashboard-portfolio" aria-selected="false">
                          <p class="h6">
                            Visualizar Evolução Completa <i class="icon ion-ios-arrow-forward text-warning"></i>
                          </p></a>
                          
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div class="tab-pane fade" id="dashboard-portfolio" role="tabpanel"
              aria-labelledby="dashboard-portfolio-tab">
              <div class="dashboard-portfolio shadow">
                <div class="row">
                  <div class="col-12">
                    <div class="accordion" id="portfolio-accordion">
                      <div class="card">
                        <div class="card-header collapsed cursor" data-toggle="collapse" data-target="#collapseOne"
                          aria-expanded="true" aria-controls="collapseOne" id="headingOne">
                          <div class="d-flex justify-content-between align-items-center">
                            <div class="w-75">
                              <div class="pie animate no-round" id="pie-crypto-chart">0%</div>
                              <span class="font-weight-bold font-card fs-r">Criptomoedas</span>
                            </div>
                            <div class="vl font-weight-bold w-50">
                              <span class="d-block ml-4 fs-r">Saldo</span>
                              <span class="balance-hidden ml-4 fs-r">****</span>
                              <span class="balance-visible">
                                <span class="ml-4 fs-r" id="crypto-balance"></span>
                              </span>
                            </div>
                            <span class="vl d-flex align-items-center justify-content-center w-10"><i
                                class="icon ion-ios-arrow-down ml-3"></i></span>
                          </div>
                        </div>
                        <div id="collapseOne" class="collapse" aria-labelledby="headingOne"
                          data-parent="#portfolio-accordion">
                          <div class="card">
                            <div class="card-header">
                              <div class="row justify-content-between text-center">
                                <div class="col-1">
                                  #
                                </div>
                                <div class="col-2">
                                  Ativo
                                </div>
                                <div class="col-3">
                                  Quantidade
                                </div>
                                <div class="col-3">
                                  Valor em CBRL
                                </div>
                                <div class="col-2">
                                  24h
                                </div>
                              </div>
                            </div>
                          </div>
                          <div class="accordion" id="crypto-accordion"></div>
                        </div>
                      </div>
                      <div class="card">
                        <div class="card-header collapsed cursor" data-toggle="collapse" data-target="#collapseTwo"
                          aria-expanded="true" aria-controls="collapseTwo" id="headingTwo">
                          <div class="d-flex justify-content-between align-items-center">
                            <div class="w-75">
                              <div class="pie animate no-round" id="pie-renda-chart">0%</div>
                              <span class="font-weight-bold font-card fs-r">Renda Digital</span>
                            </div>
                            <div class="vl font-weight-bold w-50">
                              <span class="d-block ml-4 fs-r">Saldo</span>
                              <span class="balance-hidden ml-4 fs-r">****</span>
                              <span class="balance-visible">
                                <span class="ml-4 fs-r" id="renda-balance"></span>
                              </span>
                            </div>
                            <span class="vl d-flex align-items-center justify-content-center w-10"><i
                                class="icon ion-ios-arrow-down ml-3"></i></span>
                          </div>
                        </div>
                        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo"
                          data-parent="#portfolio-accordion">
                          <div class="card">
                            <div class="card-header">
                              <div class="row justify-content-between text-center">
                                <div class="col-1">
                                  #
                                </div>
                                <div class="col-2">
                                  Ativo
                                </div>
                                <div class="col-3">
                                  Quantidade
                                </div>
                                <div class="col-3">
                                  Valor em CBRL
                                </div>
                                <div class="col-3">
                                  24h
                                </div>
                              </div>
                            </div>
                          </div>
                          <div class="accordion" id="renda-accordion"></div>
                        </div>
                      </div>
                      <div class="card">
                        <div class="card-header collapsed cursor" data-toggle="collapse" data-target="#collapseThree"
                          aria-expanded="true" aria-controls="collapseThree" id="headingThree">
                          <div class="d-flex justify-content-between align-items-center">
                            <div class="w-75">
                              <div class="pie animate no-round" id="pie-utility-chart">0%</div>
                              <span class="font-weight-bold font-card fs-r">Utility Tokens</span>
                            </div>
                            <div class="vl font-weight-bold w-50">
                              <span class="d-block ml-4 fs-r">Saldo</span>
                              <span class="balance-hidden ml-4 fs-r">****</span>
                              <span class="balance-visible">
                                <span class="ml-4 fs-r" id="utility-balance"></span>
                              </span>
                            </div>
                            <span class="vl d-flex align-items-center justify-content-center w-10"><i
                                class="icon ion-ios-arrow-down ml-3"></i></span>
                          </div>
                        </div>
                        <div id="collapseThree" class="collapse" aria-labelledby="headingThree"
                          data-parent="#portfolio-accordion">
                          <div class="card">
                            <div class="card-header">
                              <div class="row justify-content-between text-center">
                                <div class="col-1">
                                  #
                                </div>
                                <div class="col-2">
                                  Ativo
                                </div>
                                <div class="col-3">
                                  Quantidade
                                </div>
                                <div class="col-3">
                                  Valor em CBRL
                                </div>
                                <div class="col-3">
                                  24h
                                </div>
                              </div>
                            </div>
                          </div>
                          <div class="accordion" id="utility-accordion"></div>
                        </div>
                      </div>
                      <div class="card">
                        <div class="card-header collapsed cursor" data-toggle="collapse" data-target="#collapseFour"
                          aria-expanded="true" aria-controls="collapseFour" id="headingFour">
                          <div class="d-flex justify-content-between align-items-center">
                            <div class="w-75">
                              <div class="pie animate no-round" id="pie-startups-chart">0%</div>
                              <span class="font-weight-bold font-card fs-r">Startups</span>
                            </div>
                            <div class="vl font-weight-bold w-50">
                              <span class="d-block ml-4 fs-r">Saldo</span>
                              <span class="balance-hidden ml-4 fs-r">****</span>
                              <span class="balance-visible">
                                <span class="ml-4 fs-r" id="startups-balance"></span>
                              </span>
                            </div>
                            <span class="vl d-flex align-items-center justify-content-center w-10"><i
                                class="icon ion-ios-arrow-down ml-3"></i></span>
                          </div>
                        </div>
                        <div id="collapseFour" class="collapse" aria-labelledby="headingFour"
                          data-parent="#portfolio-accordion">
                          <div class="card">
                            <div class="card-header">
                              <div class="row justify-content-between text-center">
                                <div class="col-1">
                                  #
                                </div>
                                <div class="col-2">
                                  Ativo
                                </div>
                                <div class="col-3">
                                  Quantidade
                                </div>
                                <div class="col-3">
                                  Valor em CBRL
                                </div>
                                <div class="col-3">
                                  24h
                                </div>
                              </div>
                            </div>
                          </div>
                          <div class="accordion" id="startups-accordion"></div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="shadow mt-3">
                <div class="row">
                  <div class="col-12 py-3">
                    <div class="ml-3">
                      <span class="rounded-badge bg-primary"><i
                          class="icon ion-ios-checkmark-circle-outline icon-badge"></i></span>
                      <span class="h5">Proventos</span>
                      <span class="d-block ml-33">Acompanhe as distribuições dos proventos gerados pelos seus
                        investimentos</span>
                    </div>
                  </div>
                  <div class="col-12">
                    <div class="accordion" id="proventos-accordion">
                      <div class="card">
                        <div class="card-header collapsed cursor" data-toggle="collapse"
                          data-target="#collapseProventos" aria-expanded="true" aria-controls="collapseProventos"
                          id="headingProventos">
                          <div class="d-flex justify-content-between align-items-center">
                            <div class="w-50">
                              <span class="font-weight-bold font-card fs-r ml-63">Proventos</span>
                            </div>
                            <div class="vl font-weight-bold w-50">
                              <span class="d-block ml-4 fs-r">Ganhos Acumulados</span>
                              <span class="balance-hidden ml-4 fs-r">****</span>
                              <span class="balance-visible">
                                <span class="ml-4 fs-r text-success" id="proventos-balance"></span>
                              </span>
                            </div>
                            <span class="vl d-flex align-items-center justify-content-center w-10"><i
                                class="icon ion-ios-arrow-down ml-3"></i></span>
                          </div>
                        </div>

                        <div id="collapseProventos" class="collapse" aria-labelledby="headingProventos"
                          data-parent="#proventos-accordion">
                          <div class="card-body">
                            <table class="table mt-2" id="portfolio">
                              <thead class="text-center">
                                <tr>
                                  <th>#</th>
                                  <th>Token</th>
                                  <th>Ganho</th>
                                  <th>Valor em CBRL</th>
                                  <th>Data</th>
                                </tr>
                              </thead>
                              <tbody class="text-center" id="proventos-items">

                              </tbody>
                            </table>
                            <!-- <div class="d-flex mt-3 justify-content-center">
                            <nav aria-label="Page navigation example">
                              <ul class="pagination" id="proventos_pagination"></ul>
                            </nav>
                            </div> -->
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div class="tab-pane fade" id="dashboard-wallet" role="tabpanel" aria-labelledby="dashboard-wallet-tab">
              <div class="dashboard-wallet mt-3">
                <div class="row">
                  <div class="col-12">
                    <div class="card">
                      <div class="card-header">
                        <div class="row justify-content-between text-center">
                          <div class="col-1">
                            #
                          </div>
                          <div class="col-2">
                            Ativo
                          </div>
                          <div class="col-3">
                            Quantidade
                          </div>
                          <div class="col-3">
                            Valor em CBRL
                          </div>
                          <div class="col-2">
                            24h
                          </div>
                        </div>
                      </div>
                    </div>

                    <div class="accordion" id="wallet-accordion"></div>

                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-12 mt-3 py-3 shadow">
            <div class="">
              <span class="rounded-badge bg-primary"><i class="icon ion-ios-stats mt-1"></i></span>
              <span class="h5">Rentabilidade comparada</span>
              <span class="d-block ml-33">Confira a performance da sua carteira quando comparada a outros
                indicadores</span>
            </div>



            <table class="table table-hover mt-3" id="rentabilidade-table">
              <thead>
                <tr>
                  <th scope="col"></th>
                  <th scope="col">No mês</th>
                  <th scope="col">Semestre</th>
                  <th scope="col">No ano</th>
                  <th scope="col">12 meses</th>
                  <th scope="col">Desde o início</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th scope="row">Sua carteira</th>
                  <td>0,00%</td>
                  <td>0,00%</td>
                  <td>0,00%</td>
                  <td>0,00%</td>
                  <td>0,00%</td>
                </tr>
                <tr>
                  <th scope="row">CDI</th>
                  <td id="cdi-mes">0,00%</td>
                  <td id="cdi-sem">0,00%</td>
                  <td id="cdi-ano">0,00%</td>
                  <td id="cdi-12m">0,00%</td>
                  <td id="cdi-ini">0,00%</td>
                </tr>
                <tr>
                  <th scope="row">IPCA</th>
                  <td id="ipca-mes">0,00%</td>
                  <td id="ipca-sem">0,00%</td>
                  <td id="ipca-ano">0,00%</td>
                  <td id="ipca-12m">0,00%</td>
                  <td id="ipca-ini">0,00%</td>
                </tr>
                <tr>
                  <th scope="row">Selic</th>
                  <td id="selic-mes">0,00%</td>
                  <td id="selic-sem">0,00%</td>
                  <td id="selic-ano">0,00%</td>
                  <td id="selic-12m">0,00%</td>
                  <td id="selic-ini">0,00%</td>
                </tr>
                <tr>
                  <th scope="row" class="">Rentabilidade real <i class="icon ion-ios-information-circle-outline" d
                      data-toggle="tooltip" data-html="true" title="Rentabilidade já considerando a inflação"></i>
                  </th>
                  <td>0,00%</td>
                  <td>0,00%</td>
                  <td>0,00%</td>
                  <td>0,00%</td>
                  <td>0,00%</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>
<link href="<?php echo TEMA; ?>css.old/plugins/toastr/toastr.min.css" rel="stylesheet">
<script src="https://cdn.amcharts.com/lib/4/core.js"></script>
<script src="https://cdn.amcharts.com/lib/4/charts.js"></script>
<script src="https://cdn.amcharts.com/lib/4/themes/animated.js"></script>
<script src="https://www.amcharts.com/lib/4/lang/pt_BR.js"></script>
<script src="assets/js/dashboard.js"></script>
<script>
    var walletData = "";
    var projectedBalance = 0;

    $.getJSON("<?php echo $_ENV['SITE_URL'] ?>" + "/api/priv/jsonPortfolio?user=<?php echo $cliente->id ?>", function (parsed_data) {

        walletData = parsed_data;

    }).then(function(){
      var walletHtml = '';
      var portfolio_cryptoHtml = '';
      var portfolio_rendaHtml = '';
      var portfolio_utilityHtml = '';
      var portfolio_startupsHtml = '';
      var portfolio_cryptoBalance = 0;
      var portfolio_rendaBalance = 0;
      var portfolio_utilityBalance = 0;
      var portfolio_startupsBalance = 0;

      // Configurações do gráfico redondo
      const handleRadialChart = (id, percent, color, width, fontSize) => {
            const radChart = document.getElementById(id);
            radChart.style = "--p: " + percent + "; --c:" + color + "; --w:" + width + "px" + "; font-size:" + fontSize + "px";
            if (id === "dashboard-chart" || id === "portfolio-chart") {
                radChart.innerHTML = `<span class="d-block mt-2 text-center">${percent}%</span><p class="fs-12 text-center">Total Investido</p>`
            } else {
                radChart.innerText = percent + "%";
            }
        }
  
      const headerHtml = (j) => {
          return `<div class="card">
                          <div class="card-header collapsed cursor" data-toggle="collapse" data-target="#collapse${walletData['labels'][j + 1]}"
                            aria-expanded="false" aria-controls="collapse${walletData['labels'][j + 1]}" id="heading${walletData['labels'][j + 1]}">
                            <div class="row justify-content-between text-center">
                              <div class="col-1">
                                <img class="symbol" src="assets/img/icon/${walletData['labels'][j + 1]}.png" alt="symbol">
                              </div>
                              <div class="col-2">
                                <span class="theme-color">${walletData['labels'][j + 1]}</span>
                              </div>
                              <div class="col-3">
                                <span class="balance-hidden">****</span><span class="balance-visible">${walletData['position'][j].amount}</span>
                              </div>
                              <div class="col-3">
                                <span class="balance-hidden">****</span><span class="balance-visible">${walletData['series'][j + 1].toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' })}</span>
                              </div>
                              <div class="col-2">
                                <span class="text-success">${walletData['position'][j]._24h}%</span>
                              </div>
                            </div>
                          </div>`
      }
  
      const headerWalletHtml = (j) => {
          return `<div class="card">
                          <div class="card-header collapsed cursor" data-toggle="collapse" data-target="#collapse-${walletData['labels'][j + 1]}"
                            aria-expanded="false" aria-controls="collapse-${walletData['labels'][j + 1]}" id="heading-${walletData['labels'][j + 1]}">
                            <div class="row justify-content-between text-center">
                              <div class="col-1">
                                <img class="symbol" src="assets/img/icon/${walletData['labels'][j + 1]}.png" alt="symbol">
                              </div>
                              <div class="col-2">
                                <span class="theme-color">${walletData['labels'][j + 1]}</span>
                              </div>
                              <div class="col-3">
                                <span class="balance-hidden">****</span><span class="balance-visible">${walletData['position'][j].amount}</span>
                              </div>
                              <div class="col-3">
                                <span class="balance-hidden">****</span><span class="balance-visible">${walletData['series'][j + 1].toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' })}</span>
                              </div>
                              <div class="col-2">
                                <span class="text-success">${walletData['position'][j]._24h}%</span>
                              </div>
                            </div>
                          </div>`
      }
  
      const bodyHtml = (t, j) => {
          return `<div id="collapse${walletData['labels'][j + 1]}" class="collapse" aria-labelledby="heading${walletData['labels'][j + 1]}"
                            data-parent="#${t}-accordion">
                            <div class="card-body">
                            <div class="row justify-content-center mb-4">
                                  <div class="col-12 col-lg-6 mt-4 mx-0">
                                    <div class="my-3 border-bottom d-flex justify-content-between font-weight-bold">
                                      <span class="ml-2 mb-2"><i class="icon ion-ios-trending-up mr-1"></i>Minha
                                        Posição</span>
                                      <span class="ml-2 mb-2">Ver mais detalhes</span>
                                    </div>
                                    <table class="table table-responsive mt-2">
                                      <thead class="text-center">
                                        <tr>
                                          <th>Rendimento</th>
                                          <th>Projetado</th>
                                          <th>Negociado do dia</th>
                                          <th>Em garantia</th>
                                          <th>Liquidação de termo</th>
                                        </tr>
                                      </thead>
                                      <tbody class="text-center">
                                        <tr>
                                          <td><span class="balance-hidden">****</span><span class="balance-visible">R$
                                              160,00</span></td>
                                          <td><span class="balance-hidden">****</span><span
                                              class="balance-visible">0</span>
                                          </td>
                                          <td><span class="balance-hidden">****</span><span
                                              class="balance-visible">0</span>
                                          </td>
                                          <td><span class="balance-hidden">****</span><span
                                              class="balance-visible">0</span>
                                          </td>
                                          <td><span class="balance-hidden">****</span><span
                                              class="balance-visible">0</span>
                                          </td>
                                          
                                        </tr>
                                      </tbody>
                                    </table>
                                    <div class="row justify-content-center my-5">
                                      <div class="col-6 col-md-3 mb-2">
                                        <a class="btn btn-light btn-square d-flex align-items-center mx-auto justify-content-center" href="/exchange">
                                          <i class="text-primary fs-30"><img src="assets/img/icon/ico-wallet-in.svg" alt="deposit"></i>
                                        </a>
                                        <p class="fw-bold text-center">Investir</p>
                                      </div>
                                      <div class="col-6 col-md-3 mb-2">
                                        <a class="btn btn-light btn-square d-flex align-items-center mx-auto justify-content-center" href="/exchange">
                                          <i class="text-primary fs-30"><img src="assets/img/icon/ico-wallet-out.svg" alt="deposit"></i>
                                        </a>
                                        <p class="fw-bold text-center">Resgatar</p>
                                      </div>
                                      </div>
                                  </div>
                                  <div class="col-12 col-lg-6 mt-4 mx-0">
                                    <div class="my-3 border-bottom d-flex font-weight-bold">
                                      <span class="ml-2 mb-2"><i class="icon ion-ios-trending-up mr-1"></i>Evolução do
                                        Ativo</span>
                                    </div>
                                    <div class="divergentChartDiv" id="${walletData['labels'][j + 1]}-divergentChart" style="height:300px"></div>
                                  </div>
                                </div>
                            </div>
                          </div>
                        </div>`
      }
      if (walletData.position.length > 0) {
          for (var j = 0; j < walletData['position'].length; j++) {
              walletHtml += headerWalletHtml(j) + `
                          <div id="collapse-${walletData['labels'][j + 1]}" class="collapse" aria-labelledby="heading-${walletData['labels'][j + 1]}"
                            data-parent="#wallet-accordion">
                            <div class="card-body">
                              <div class="row">
                                <div class="col-12 col-lg-6">
                                    <div class="row">
                                      <div class="col-6 col-md-4 mb-2">
                                        <a class="btn btn-light btn-square d-flex align-items-center mx-auto justify-content-center" href="/deposit">
                                          <i class="text-primary fs-30"><img src="assets/img/icon/ico-depositar.svg" alt="deposit"></i>
                                        </a>
                                        <p class="fw-bold text-center">Depositar</p>
                                      </div>
                                      <div class="col-6 col-md-4 mb-2">
                                        <a class="btn btn-light btn-square d-flex align-items-center mx-auto justify-content-center" href="/withdraw">
                                          <i class="text-primary fs-30"><img src="assets/img/icon/ico-sacar.svg" alt="withdraw"></i>
                                        </a>
                                        <p class="fw-bold text-center">Transferir</p>
                                      </div>
                                      <div class="col-6 col-md-4 mb-2">
                                        <a class="btn btn-light btn-square d-flex align-items-center mx-auto justify-content-center" href="/exchange">
                                          <i class="text-primary fs-30"><img src="assets/img/icon/ico-comprar.svg" alt="exchange"></i>
                                        </a>
                                        <p class="fw-bold text-center">Comprar</p>
                                      </div>
                                      <div class="col-6 col-md-4 mb-2">
                                        <a class="btn btn-light btn-square d-flex align-items-center mx-auto justify-content-center" href="/book">
                                          <i class="text-primary fs-30"><img src="assets/img/icon/ico-ordens.svg" alt="book"></i>
                                        </a>
                                        <p class="fw-bold text-center">Ordens</p>
                                      </div>
                                      <div class="col-6 col-md-4 mb-2">
                                        <a class="btn btn-light btn-square d-flex align-items-center mx-auto justify-content-center" href="/staking">
                                          <i class="text-primary fs-30"><img src="assets/img/icon/ico-staking.svg" alt="staking"></i>
                                        </a>
                                        <p class="fw-bold text-center">Staking</p>
                                      </div>
                                
                                    </div>
                                </div>
                                <div class="col-12 col-lg-6 shadow">
                                  <div class="pt-4 pl-2 pr-2 mr-2">
                                    <p class="font-weight-lighter fs-12">ORIENTAÇÕES</p>
                                    <div class="row">
                                      <div class="col-1">
                                      <span class="rounded-icon bg-primary">
                                        <i class="icon ion-ios-information icon-badge"></i>
                                      </span>
                                      </div>
                                      <div class="col-11">
                                      O valor mínimo para depósitos em <b>${walletData['position'][j].name}</b> é de <b>0,00001000 ${walletData['labels'][j + 1]}</b>.
                                      </div>
                                    </div>
  
                                    <p class="font-weight-lighter fs-12 mt-3">INFORMAÇÕES ADICIONAIS</p>
                                    <div class="row">
                                      <div class="col-1">
                                      <span class="rounded-icon bg-primary">
                                        <i class="icon ion-ios-information icon-badge"></i>
                                      </span>
                                      </div>
                                      <div class="col-11">
                                      Depósitos em <b>${walletData['position'][j].name}</b> levam <b>3 confirmações</b> para serem aprovados.</p>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>`;
          }
          for (var j = 0; j < walletData['position'].length - 1; j++) {
              portfolio_cryptoBalance += walletData['series'][j + 1];
              portfolio_cryptoHtml += headerHtml(j) + bodyHtml("crypto", j);
          }
          for (var j = 4; j < walletData['position'].length; j++) {
              portfolio_rendaBalance += walletData['series'][j + 1];
              portfolio_rendaHtml += headerHtml(j) + bodyHtml("renda", j);
          }
          for (var j = 5; j < walletData['position'].length; j++) {
              portfolio_utilityBalance += walletData['series'][j + 1];
              portfolio_utilityHtml += headerHtml(j) + bodyHtml("utility", j);
          }
          for (var j = 5; j < walletData['position'].length; j++) {
              portfolio_startupsBalance += walletData['series'][j + 1];
              portfolio_startupsHtml += headerHtml(j) + bodyHtml("startups", j);
          }
      } else {
          walletHtml = '<p>Nenhuma posição encontrada</p>';
          portfolio_cryptoHtml = '<p>Nenhuma posição encontrada</p>';
          portfolio_rendaHtml = '<p>Nenhuma posição encontrada</p>';
          portfolio_utilityHtml = '<p>Nenhuma posição encontrada</p>';
          portfolio_startupsHtml = '<p>Nenhuma posição encontrada</p>';
      }
  
      const totalBalance = () => {
          total = 0;
          if (walletData['series']) {
              walletData['series'].forEach(element => {
                  total = element + total;
              });
          }
          return total;
      }
  
      projectedBalance = totalBalance();
  
      const investedBalance = () => {
          total = 0;
          if (walletData['series']) {
              walletData['series'].forEach((e, i) => {
                  if (i > 0) {
                      total = e + total;
                  }
              });
          }
          return total;
      }
  
      const currentDate = () => {
          let now = new Date();
          return "Atualizado em " + now.toLocaleString("pt-BR");
      }
  
      const pieChartPercent = (amount) => {
          const total = totalBalance();
          const percent100 = total == 0 ? 1: total;
          return (amount * 100 / percent100);
      }
  
      const dadosPie = [
          {
              "products": "Criptomoedas",
              "share": pieChartPercent(portfolio_cryptoBalance).toFixed(2),
              "color": am4core.color("orange")
          }, {
              "products": "Renda Digital",
              "share": pieChartPercent(portfolio_rendaBalance).toFixed(2),
              "color": am4core.color("yellow")
          }, {
              "products": "Utility Tokens",
              "share": pieChartPercent(portfolio_utilityBalance).toFixed(2),
              "color": am4core.color("blue")
          }, {
              "products": "Startups",
              "share": pieChartPercent(portfolio_startupsBalance).toFixed(2),
              "color": am4core.color("green")
          }, {
              "products": "Não Investido",
              "share": pieChartPercent(walletData["series"][0]).toFixed(2),
              "color": am4core.color("#ccc")
          }
      ];
  
      const handlePieChart = (id, data) => {
          am4core.ready(function () {
  
              // License begin
              am4core.addLicense("ch-custom-attribution");
  
              // Themes begin
              am4core.useTheme(am4themes_animated);
              // Themes end
  
              // Create chart instance
              var chart = am4core.create(id, am4charts.PieChart);
  
              // Add data
              chart.data = data;
  
              // Set inner radius
              chart.innerRadius = am4core.percent(70);
  
              // Add and configure Series
              var pieSeries = chart.series.push(new am4charts.PieSeries());
              pieSeries.ticks.template.disabled = true;
              pieSeries.labels.template.disabled = true;
              pieSeries.dataFields.value = "share";
              pieSeries.dataFields.category = "products";
              pieSeries.slices.template.propertyFields.fill = "color";
              pieSeries.slices.template.stroke = am4core.color("#fff");
              pieSeries.slices.template.strokeWidth = 2;
              pieSeries.slices.template.strokeOpacity = 1;
  
              // This creates initial animation
              pieSeries.hiddenState.properties.opacity = 1;
              pieSeries.hiddenState.properties.endAngle = -90;
              pieSeries.hiddenState.properties.startAngle = -90;
  
          }); // end am4core.ready()
      }
  
      async function fetchData(user_id) {
          try {
              const response = await fetch("https://sandbox.coinage.trade/api/priv/performance/monthly?user=" + user_id);
              const fData = await response.json();
              const data = Object.keys(fData.scope).map(key => fData.scope[key]);
              return data;
          } catch (error) {
              console.error(`Data error: ${error.message}`);
          }
      }
  
      // Mudar seleção entre radios
      const handleRadioIcon = ({ target }) => {
          const mktRadio = document.getElementById("market-radio");
          const crvRadio = document.getElementById("curve-radio");
          const mktTxt = document.getElementById("market-radio-text");
          const crvTxt = document.getElementById("curve-radio-text");
          const mktTitle = document.getElementById("market-card-title");
          const crvTitle = document.getElementById("curve-card-title");
  
          if (target.parentNode.id == "market-radio-trigger") {
              if (mktRadio.classList.contains("ion-ios-radio-button-off")) {
                  handleChangePosition()
              }
          } else {
              if (crvRadio.classList.contains("ion-ios-radio-button-off")) {
                  handleChangePosition()
              }
          }
      }
  
      // Mudar posição padrão
      const handleChangePosition = () => {
  
          const mktTxt = document.getElementById("market-radio-text");
          const crvTxt = document.getElementById("curve-radio-text");
          const mktTitle = document.getElementById("market-card-title");
          const crvTitle = document.getElementById("curve-card-title");
          const mktRadio = document.getElementById("market-radio");
          const crvRadio = document.getElementById("curve-radio");
          const projectedBalanceValue = document.getElementById('projected-balance');
  
          if (crvTitle.classList.contains("text-hidden")) {
              mktRadio.classList.replace("ion-ios-radio-button-on", "ion-ios-radio-button-off")
              crvRadio.classList.replace("ion-ios-radio-button-off", "ion-ios-radio-button-on")
              mktTxt.classList.toggle("text-hidden")
              crvTxt.classList.toggle("text-hidden")
              mktTitle.classList.toggle("text-hidden")
              crvTitle.classList.toggle("text-hidden")
              projectedBalanceValue.innerHTML = (projectedBalance + (portfolio_rendaBalance * 1.24)).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
  
          } else {
              mktRadio.classList.replace("ion-ios-radio-button-off", "ion-ios-radio-button-on")
              crvRadio.classList.replace("ion-ios-radio-button-on", "ion-ios-radio-button-off")
              mktTxt.classList.toggle("text-hidden")
              crvTxt.classList.toggle("text-hidden")
              mktTitle.classList.toggle("text-hidden")
              crvTitle.classList.toggle("text-hidden")
              projectedBalanceValue.innerHTML = projectedBalance.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
          }
      }
  
      function formatPercent(num) {
          return num / 100;
      }
  
      var performanceGraphData = [];
  
      const callData = async () => {
          const data = await fetchData("<?php echo $cliente->id ?>")
          data.forEach(e => {
              performanceGraphData.push({
                  "date": new Date(e.label),
                  "ativo": formatPercent(e.wallet),
                  "cdi": formatPercent(e.cdi),
                  "ipca": formatPercent(e.ipca),
                  "selic": formatPercent(e.selic)
              })
          });
      }
  
      callData()
  
      const ativoData = [{
          "date": new Date(2023, 0, 1),
          "ativo": 2.30 / 100,
          "cdi": 0 / 100,
          "ipca": 0 / 100,
          "selic": 0 / 100,
      }, {
          "date": new Date(2023, 1, 1),
          "ativo": 4.60 / 100,
      }, {
          "date": new Date(2023, 2, 1),
          "ativo": 6.91 / 100,
      }, {
          "date": new Date(2023, 3, 1),
          "ativo": 9.21 / 100,
      }, {
          "date": new Date(2023, 4, 1),
          "ativo": 11.52 / 100,
      }, {
          "date": new Date(2023, 5, 1),
          "ativo": 13.82 / 100,
      }, {
          "date": new Date(2023, 6, 1),
          "ativo": 16.12 / 100,
      }, {
          "date": new Date(2023, 7, 1),
          "ativo": 18.43 / 100,
      }, {
          "date": new Date(2023, 8, 1),
          "ativo": 20.73 / 100,
      }, {
          "date": new Date(2023, 9, 1),
          "ativo": 23.04 / 100,
      }, {
          "date": new Date(2023, 10, 1),
          "ativo": 25.34 / 100,
      }, {
          "date": new Date(2023, 11, 1),
          "ativo": 27.64 / 100,
          "cdi": 12.65 / 100,
          "ipca": 5.19 / 100,
          "selic": 12.25 / 100,
      }];
  
      const token_data = (symbol) => [
          {
              "field": "ativo",
              "name": symbol,
              "color": "blue",
              "dashed": true
          },
          {
              "field": "cdi",
              "name": "CDI",
              "color": "orange",
              "dashed": false
          },
          {
              "field": "ipca",
              "name": "IPCA",
              "color": "green",
              "dashed": false
          },
          {
              "field": "selic",
              "name": "Selic",
              "color": "black",
              "dashed": false
          }
      ];
  
      const handleDivergentLinesChart = (id, data, series) => {
          am4core.ready(function () {
  
              // License begin
              am4core.addLicense("ch-custom-attribution");
              // License end
  
              // Themes begin
              am4core.useTheme(am4themes_animated);
              // Themes end
  
              // Create chart instance(2023
              var chart = am4core.create(id, am4charts.XYChart);
  
              chart.numberFormatter.language.locale = am4lang_pt_BR;
              chart.dateFormatter.dateFormat = "MMM YYYY";
              chart.numberFormatter.numberFormat = "#.##%";
  
              // Chart title
              var title = chart.titles.create();
              // title.text = "Projected infection dynamics";
              title.fontSize = 20;
              title.paddingBottom = 10;
  
              // Add data
              chart.data = data;
  
              // Create axes
              var dateAxis = chart.xAxes.push(new am4charts.DateAxis());
              dateAxis.renderer.grid.template.location = 0;
              dateAxis.renderer.minGridDistance = 30;
  
              var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
              valueAxis.renderer.inside = true;
              valueAxis.renderer.labels.template.verticalCenter = "bottom";
              valueAxis.renderer.labels.template.dx = -5;
              valueAxis.renderer.labels.template.dy = 10;
              valueAxis.renderer.maxLabelPosition = 0.95;
              // valueAxis.title.text = "Number of infections";
              valueAxis.title.marginRight = 5;
  
              // Create series
              function createSeries(field, name, color, dashed) {
                  var series = chart.series.push(new am4charts.LineSeries());
                  series.dataFields.valueY = field;
                  series.dataFields.dateX = "date";
                  series.name = name;
                  series.tooltipText = "[bold]{name}[/]\n{dateX}: [b]{valueY}[/]";
                  series.strokeWidth = 2;
                  series.smoothing = "monotoneX";
                  series.stroke = color;
  
                  if (dashed) {
                      series.strokeDasharray = "5 3";
                  }
  
                  return series;
              }
  
              series.forEach((e, i) => {
                  createSeries(series[i].field, series[i].name, am4core.color(series[i].color), series[i].dashed);
              });
  
              chart.legend = new am4charts.Legend();
              chart.cursor = new am4charts.XYCursor();
  
          }); // end am4core.ready()
      }
  
      setTimeout(() => {
          handleDivergentLinesChart("performance-chart", performanceGraphData, token_data("Carteira"));
          handleDivergentLinesChart("BTC-divergentChart", ativoData, token_data("BTC"));
          handleDivergentLinesChart("ETH-divergentChart", ativoData, token_data("ETH"));
          handleDivergentLinesChart("USDT-divergentChart", ativoData, token_data("USDT"));
          handleDivergentLinesChart("BNB-divergentChart", ativoData, token_data("BNB"));
          handleDivergentLinesChart("FTR-divergentChart", ativoData, token_data("FTR"));
      }, "1000");
  
      handlePieChart("dashboard-chart", dadosPie);
      // handleAxisChart("performance-chart", "<?php echo $cliente->id ?>" )
      handleRadialChart("pie-crypto-chart", pieChartPercent(portfolio_cryptoBalance).toFixed(1), "orange", 50, 14);
      handleRadialChart("pie-renda-chart", pieChartPercent(portfolio_rendaBalance).toFixed(1), "yellow", 50, 14);
      handleRadialChart("pie-utility-chart", pieChartPercent(portfolio_utilityBalance).toFixed(1), "blue", 50, 14);
      handleRadialChart("pie-startups-chart", pieChartPercent(portfolio_startupsBalance).toFixed(1), "green", 50, 14);
      document.getElementById('total-percent').innerHTML = pieChartPercent(investedBalance()).toFixed(2) + "%";
      document.getElementById('wallet-accordion').innerHTML = walletHtml;
      document.getElementById('crypto-accordion').innerHTML = portfolio_cryptoHtml;
      document.getElementById('renda-accordion').innerHTML = portfolio_rendaHtml;
      document.getElementById('utility-accordion').innerHTML = portfolio_utilityHtml;
      document.getElementById('startups-accordion').innerHTML = portfolio_startupsHtml;
      document.getElementById('crypto-balance').innerHTML = portfolio_cryptoBalance.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
      document.getElementById('renda-balance').innerHTML = portfolio_rendaBalance.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
      document.getElementById('utility-balance').innerHTML = portfolio_utilityBalance.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
      document.getElementById('startups-balance').innerHTML = portfolio_startupsBalance.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
      document.getElementById('current-date').innerHTML = currentDate();
      document.getElementById('total-balance').innerHTML = totalBalance().toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
      document.getElementById('available-balance').innerHTML = walletData['series'][0] ? walletData['series'][0].toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' }) : "R$ 0,00";
      document.getElementById('invested-balance').innerHTML = investedBalance().toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
      document.getElementById("market-radio-toggler").addEventListener("click", handleChangePosition);
      document.getElementById("curve-radio-toggler").addEventListener("click", handleChangePosition);
      document.getElementById("market-radio").addEventListener("click", handleRadioIcon);
      document.getElementById("curve-radio").addEventListener("click", handleRadioIcon);
      document.getElementById('projected-balance').innerHTML = projectedBalance.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
      const vPortfolio = document.getElementById('visualizar-portfolio');
      vPortfolio.addEventListener("click", () => {
          document.getElementById('dashboard-tab').classList.remove("active");
          document.getElementById('dashboard-portfolio-tab').classList.add("active");
          setTimeout(() => {
              vPortfolio.setAttribute("aria-selected", "false");
              vPortfolio.classList.remove("active");
          }, 1000);
      })
    })
    // });

    // $.getJSON("<?php echo $_ENV['SITE_URL'] ?>"+"/api/priv/listOurTokens", function (data) {
</script>
<!-- <script src="assets/js/divergentLinesChart.js"></script> -->
<!-- <script src="assets/js/valueAxisChart.js"></script> -->
<?php Utils\Layout::append("mensage_text", $_data) ?>
<?php Utils\Layout::append("mensage_text", $_data) ?>

<div class="row mt-3">
