<?php 

$moedas = isset($_data["moedas"]) ? $_data["moedas"] : Array();
$moeda = \Modules\principal\Controllers\Principal::getCurrency();
?>

<?php Utils\Layout::append("inspina/metas", $_data) ?>

<?php Utils\Layout::append("inspina/scripts", $_data) ?>


<?php Utils\Layout::append("inspina/menu", $_data) ?>



    
    
    <div class="content-wrapper">
    <!-- Content Header (Page header) -->
             <div class="row wrapper border-bottom page-heading" style="background: linear-gradient(to right, #fff, <?php echo $moeda->mainColor ?>) !important;">
                <div class="col-lg-10">
                    <h2>Conta Corrente (BTC)</h2>
                    <ol class="breadcrumb" style="background-color: transparent !important;">
                        <li>
                            Bitcoin
                        </li>
                        <li class="active">
                            <strong>Conta Corrente (BTC)</strong>
                        </li>
                    </ol>
                </div>
            </div>
</div>
    <br>
    <!-- Main content -->
    <section class="content">

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <?php Utils\Layout::append("mensagem", $_data)?>
                    <div class="panel-heading">
                        Listagem de Contas 
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <div class="row">
                            <div class="col col-lg-3">
                                <div class="form-group" >
                                    <label>Moeda</label>
                                    <select class="select2" id="filtroMoeda" style="width: 100%;">
                                        <option value="<?php echo \Utils\Criptografia::encriptyPostId(0)?>" style="">Todas</option>
                                        <?php  
                                        foreach ($moedas as $moeda) {
                                            ?>
                                        <option value="<?php echo \Utils\Criptografia::encriptyPostId($moeda->id)?>" style=""><?php echo $moeda->simbolo ?></option>
                                            <?php
                                        }
                                        ?>
                                    </select>
                                </div>
                            </div>
                            <div class="col col-lg-9">
                                <div class="form-group">
                                    <label>Filtro Geral</label>
                                    <input type="text" id="filtro" class="form-control" />
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col col-lg-4">
                                <div class="form-group">
                                    <div class="checkbox">
                                        <input type="checkbox"  name="contasZeradas" id="contasZeradas" />
                                        <label for="contasZeradas" >
                                             Mostrar contas zeradas
                                        </label>
                                    </div>
                                    
                                </div>
                            </div>
                            <div class="col col-lg-4">
                                <div class="form-group">
                                    <div class="checkbox">
                                        <input type="checkbox" name="contasPositivas" checked id="contasPositivas" />
                                        <label for="contasPositivas">
                                             Mostrar contas positivas
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <div class="col col-lg-4">
                                <div class="form-group">
                                    <div class="checkbox">
                                        <input type="checkbox" checked name="contasNegativas" id="contasNegativas" />
                                        <label for="contasNegativas">
                                             Mostrar contas negativas
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col col-lg-12 text-center">
                                <br>
                                <button class="btn btn-primary" onclick="filtrar();">
                                    <i class="fa fa-refresh"></i> Atualizar
                                </button>
                                <br><br>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col col-lg-12" >
                                <ul class="list-group" id="lista">
                                    
                                </ul>
                            </div>
                        </div>
                    </div>
                    <!-- /.panel-body -->

                </div>
            </div>

        </div>

    </section>
    
    <div class="clearfix"></div>
</div>

<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>

<script>
    $(document).ready(function () {
        $("#filtroMoeda").select2();
        filtrar();
    });
    
    function filtrar() {
        $("#lista").html("<div class='col-lg-12 text-center'><img src='<?php echo IMAGES ?>loading.gif' /></div>");
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_BTC_CONTAS_RESUMO ?>',
            method: 'post',
            dataType: 'json',
            data: {
                moeda: $("#filtroMoeda").val(),
                filtro: $("#filtro").val(),
                contasZeradas: ($("#contasZeradas").is(":checked") ? 1 : 0),
                contasPositivas: ($("#contasPositivas").is(":checked") ? 1 : 0),
                contasNegativas: ($("#contasNegativas").is(":checked") ? 1 : 0)
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#lista").html(json.html);
                    } else {
                        $("#lista").html("<div class='col-lg-12 text-center'>"+json.mensagem+"</div>");
                    }
                } catch (e) {
                    $("#lista").html("<div class='col-lg-12 text-center'>"+e+"</div>");
                }
            }
        });
    }
    
    
    
</script>