<?php
$dataInicial = new Utils\Data(date("d/m/Y"));
$dataFinal = new Utils\Data(date("d/m/Y"));
$dataInicial->subtrair(0, 0, 30);
$cliente = isset($_data["cliente"]) ? $_data["cliente"] : new Models\Modules\Cadastro\Cliente();
$adm = (\Utils\Geral::isUsuario() && \Utils\Geral::getLogado()->tipo == Utils\Constantes::ADMINISTRADOR);
$moeda = \Modules\principal\Controllers\Principal::getCurrency();
?>
<?php Utils\Layout::append("inspina/metas", $_data) ?>
<?php Utils\Layout::append("inspina/scripts", $_data) ?>
<?php Utils\Layout::append("inspina/menu", $_data) ?>

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
             <div class="row wrapper border-bottom page-heading" style="background: linear-gradient(to right, #fff, <?php echo $moeda->mainColor ?>) !important;">
                <div class="col-lg-10">
                    <h2>Histórico</h2>
                    <ol class="breadcrumb" style="background-color: transparent !important;">
                        <li>
                            Reais
                        </li>
                        <li class="active">
                            <strong>Histórico</strong>
                        </li>
                    </ol>
                </div>
            </div>
</div>


<br>
<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-content">
                <div class="row">
                    <div class="col-md-12">

                        <div class="col col-md-2">
                            <div class="form-group">
                                <label class="control-label">Data Inicial</label>
                                <input type="text" id="dataInicial" class="form-control" onchange="filtrar();" value="<?php echo $dataInicial->formatar(\Utils\Data::FORMATO_PT_BR)?>" />
                            </div>
                        </div>
                        <div class="col col-md-2">
                            <div class="form-group">
                                <label class="control-label">Data Final</label>
                                <input type="text" id="dataFinal" class="form-control" onchange="filtrar();" value="<?php echo $dataFinal->formatar(\Utils\Data::FORMATO_PT_BR)?>" />
                            </div>
                        </div>

                        <div class="col col-md-4">
                            <div class="form-group">
                                <label class="control-label">Tipo</label>
                                <select class="form-control" id="tipo" onchange="filtrar();">
                                    <option value="T" >Todos</option>
                                    <option value="<?php echo \Utils\Constantes::ENTRADA ?>" >Somente Entradas</option>
                                    <option value="<?php echo \Utils\Constantes::SAIDA ?>" >Somente Saídas</option>
                                </select>
                            </div>
                        </div>

                        <div class="col col-lg-4">
                            <div class="form-group">
                                <label>Filtro Geral</label>
                                <input type="text" id="filtro" class="form-control" onkeyup="filtrar();" />
                            </div>
                        </div>
                    </div>
                </div>



                <div class="row">
                    <div class="col col-lg-12" >
                        <div id="lista" class="vertical-container light-timeline">

                        </div>
                    </div>
                </div>        
                
                

            </div>
        </div>
    </div>
</div>
    
<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>


<?php Utils\Layout::append("mensage_text", $_data) ?>

<script>
    $(document).ready(function () {
        
        filtrar();
        
        $("#dataInicial, #dataFinal").datepicker({format: 'dd/mm/yyyy'}).mask("99/99/9999");
        
        $("#dialogCadastroContaValor, #dialogTransferenciaContaValor").keydown(function(event) {
            $(this).val(currency($(this).val(), 2, 8, event.keyCode));
            event.preventDefault();
        });
        
        $("#dialogCadastroContaData").datepicker({format: 'dd/mm/yyyy'}).mask("99/99/9999");
    });
    
    function filtrar() {
        $("#lista").html("<div class='col-lg-12 text-center'><img src='<?php echo IMAGES ?>loading.gif' /></div>");
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_REAIS_CONTA_LANCAMENTOS ?>',
            method: 'post',
            dataType: 'json',
            data: {
                dataInicial:$("#dataInicial").val(),
                dataFinal:$("#dataFinal").val(),
                tipo:$("#tipo").val(),
                idCliente:<?php echo $cliente->id ?>,
                filtro: $("#filtro").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#lista").html(json.html);
                    } else {
                        $("#lista").html("<div class='col-lg-12 text-center'>"+json.mensagem+"</div>");
                    }
                } catch (e) {
                    $("#lista").html("<div class='col-lg-12 text-center'>"+e+"</div>");
                }
            }
        });
    }
    
    
    
    function cadastro(idContaCorrente) {
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_REAIS_LANCAMENTO_CADASTRO ?>',
            method: 'post',
            dataType: 'json',
            data: {
                id: idContaCorrente
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#dialogCadastroContaId").val(json.conta.id);
                        $("#dialogCadastroContaValor").val(json.conta.valor);
                        $("#dialogCadastroContaDescricao").val(json.conta.descricao);
                        $("#dialogCadastroContaData").val(json.conta.data);
                        if (json.conta.tipo !== null) {
                            $("#dialogCadastroContaTipo").val(json.conta.tipo);
                        } else {
                            $("#dialogCadastroContaTipo").val('<?php echo \Utils\Constantes::ENTRADA ?>');
                        }
                        $("#dialogCadastroConta").modal();
                        
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
            }
        });
    }
    
    function salvar() {
        $("#dialogCadastroContaFechar, #dialogCadastroContaSalvar").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_REAIS_LANCAMENTO_SALVAR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                id: $("#dialogCadastroContaId").val(),
                data: $("#dialogCadastroContaData").val(),
                valor: $("#dialogCadastroContaValor").val(),
                descricao: $("#dialogCadastroContaDescricao").val(),
                tipo: $("#dialogCadastroContaTipo").val(),
                idCliente: <?php echo $cliente->id ?>
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        filtrar();
                        $("#dialogCadastroContaFechar").prop("disabled", false).trigger("click");
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#dialogCadastroContaFechar, #dialogCadastroContaSalvar").prop("disabled", false);
            }
        });
    }
    
    function modalExcluir(id) {
        $("#modalExcluirContaId").val(id);
        $("#modalExcluirConta").modal();
    }
    
    function excluir() {
        $("#modalExcluirContaFechar, #modalExcluirContaExcluir").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_REAIS_LANCAMENTO_EXCLUIR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                id: $("#modalExcluirContaId").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        filtrar();
                        $("#modalExcluirContaFechar").prop("disabled", false).trigger("click");
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#modalExcluirContaFechar, #modalExcluirContaExcluir").prop("disabled", false);
            }
        });
    }
    
    function print() {
        var dataInicial = $("#dataInicial").val();
        var dataFinal = $("#dataFinal").val();
        var tipo = $("#tipo").val();
        var idCliente = <?php echo $cliente->id ?>;
        var filtro = $("#filtro").val();
        var s = dataInicial + "|"+ dataFinal + "|"+tipo+"|"+filtro+"|"+idCliente;
        var params = btoa(s);
        
        window.open("<?php echo URLBASE_CLIENT . Utils\Rotas::R_REAIS_LANCAMENTOS_IMPRIMIR ?>/"+params);
        
    }
    
</script>


<div class="modal fade" id="modalExcluirConta" tabindex="-1" role="dialog" aria-labelledby="modalExcluirConta" aria-hidden="true" >
    <div class="modal-dialog" style="width: 800px;">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="dialogFinalizarRecargaLabel">Excluir Lançamento</h4>
            </div>
            <div class="modal-body">
                <input type="hidden" id="modalExcluirContaId" />
                <div class="row">
                    <div class="col col-lg-12" >
                        Tem certeza que deseja excluir o lançamento selecionado?
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="modalExcluirContaFechar" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-danger" id="modalExcluirContaExcluir" onclick="excluir();">Excluir</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>



<div class="modal fade" id="dialogCadastroConta" tabindex="-1" role="dialog" aria-labelledby="dialogCadastroConta" aria-hidden="true" >
    <div class="modal-dialog" style="width: 800px;">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="dialogCadastroContaLabel">Cadastro de Lançamento</h4>
            </div>
            <div class="modal-body">
                <input type="hidden" id="dialogCadastroContaId" />
                <div class="row">
                    <div class="col col-lg-12">
                        <div class="form-group">
                            <label>Descrição</label>
                            <input type="text" class="form-control"  id="dialogCadastroContaDescricao"/>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col col-lg-4" >
                        <div class="form-group">
                            <label class="control-label">Movimento</label>
                            <select class="form-control" id="dialogCadastroContaTipo" >
                                <option value="<?php echo \Utils\Constantes::ENTRADA ?>" >Entrada</option>
                                <option value="<?php echo \Utils\Constantes::SAIDA ?>" >Saída</option>
                            </select>
                        </div>
                    </div>
                    <div class="col col-lg-4" >
                        <div class="form-group">
                            <label>Data</label>
                            <input type="text" class="form-control" id="dialogCadastroContaData"  />
                        </div>
                    </div>
                    <div class="col col-sm-4">
                        <div class="form-group">
                            <label>Valor</label>
                            <input type="text" class="form-control" id="dialogCadastroContaValor"  />
                        </div>
                    </div>
                </div>
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="dialogCadastroContaFechar" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-primary" id="dialogCadastroContaSalvar"  onclick="salvar();">Salvar</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>