<?php
$deposito = isset($_data["deposito"]) ? $_data["deposito"] : new \Models\Modules\Cadastro\Deposito();
$comissao = isset($_data["comissao"]) ? $_data["comissao"] : 0;
$carteira = isset($_data["carteira"]) ? $_data["carteira"] : null;
$configuracao = isset($_data["configuracao"]) ? $_data["configuracao"] : new \Models\Modules\Cadastro\Configuracao();
$dataInicial = new \Utils\Data(date("d/m/Y H:i:s"));
$dataInicial->subtrair(0,1,0);
$dataFinal = new \Utils\Data(date("d/m/Y H:i:s"));
$processoDeposito = isset($_data["processoDeposito"]) ? $_data["processoDeposito"] : null;

$contasBancarias = isset($_data["contas"]) ? $_data["contas"] : Array();
$moeda = \Modules\principal\Controllers\Principal::getCurrency();
$cliente = Utils\Geral::getCliente();
$mostrarBotaoDeposito = (Models\Modules\Acesso\ModuloRn::validar(Utils\Rotas::M_DEPOSITOS, \Utils\Constantes::CADASTRAR)  ? (Utils\Geral::isCliente() && ($cliente->statusDepositoBrl > 0)) : false);

 $idioma = new \Utils\PropertiesUtils("deposito", IDIOMA);
 
$mostrarAbaDepositoReais = ($cliente->fotoClienteVerificada > 0 && $cliente->fotoDocumentoVerificada > 0 && $cliente->fotoResidenciaVerificada > 0 && $cliente->utilizaSaqueDepositoBrl > 0);
$_data["idiomaMenu"] = $idioma;
?>
<style>
    .border-edit {
        border: 1px solid #1c84c6 !important;
    }
</style>
<?php Utils\Layout::append("inspina/metas", $_data) ?>
<?php Utils\Layout::append("inspina/scripts", $_data) ?>
<?php Utils\Layout::append("inspina/menu", $_data) ?>
<?php Utils\Layout::append("inspina/breadcrumb", $_data) ?>
<br>


<!-- Main content -->
<section class="content">

    <?php if (\Utils\Geral::isCliente()) { ?>
    <div class="row">
        <div class="col col-xs-12">
            
            <div class="tabs-container">
                <ul class="nav nav-tabs">
                      
                    <?php if ($configuracao->statusDepositoBrl > 0 && $mostrarAbaDepositoReais) { ?>
                    <li class="active"><a data-toggle="tab" href="#tab-2" data-target="#tab-2, #tab-3" aria-expanded="false">
                            <img src="<?php echo IMAGES?>currencies/BRL.png" style="max-width: 20px; height: 20px;" />
                            <?php echo $idioma->getText("abaReais") ?> 
                        </a>
                    </li>
                    <?php } ?>
                    
                    <?php if ($configuracao->statusDepositoCurrency > 0 && $moeda->statusDeposito > 0) { ?>
                    <li class=""><a data-toggle="tab" href="#tab-1" data-target="#tab-1, #tab-4" aria-expanded="true">
                            <img src="<?php echo IMAGES?>currencies/<?php echo $moeda->icone ?>" style="max-width: 20px; height: 20px;" />
                            <?php echo $idioma->getText("abaMoeda") ?> <?php echo $moeda->nome?> 
                        </a>
                    </li>
                    <?php } ?>
                </ul>
                    
              
                <div class="tab-content">
                    
                    
                    <?php if ($configuracao->statusDepositoCurrency > 0 && $moeda->statusDeposito > 0) { ?>
                    <div id="tab-1" class="tab-pane <?php echo ($mostrarAbaDepositoReais ? "" : "active") ?>">
                        <div class="panel-body">
                            <div class="col col-lg-6 text-center">
                                
                                <?php if ($configuracao->statusCarteiras > 0) { ?>
                                <h2 class="page-header" style="margin-top: 10px"><?php echo str_replace("{var}", $moeda->nome, $idioma->getText("carteira")) ?></h2>
                                <?php if ($carteira != null) { ?>
                                <img src="https://qrcode.kaywa.com/img.php?s=7&d=<?php echo $carteira->endereco ?>" alt="" id="imgCarteiraDestino" style="width: 100%; max-height: 150px; max-width: 150px; margin-top: -20px;">
                                <br>
                                <span class="label label-default" style="cursor: pointer; font-size: 12px" id="btncopy" alt="<?php echo $idioma->getText("copiarEndereco") ?>">
                                    <?php echo $carteira->endereco ?>
                                </span>
                                <br>
                                <button class="btn-link m-t-xs" id="btn-link-ref" data-clipboard-target="#btncopy">
                                       <?php echo $idioma->getText("copiarEndereco1") ?>
                                </button>
                                <?php } else { ?>
                                <div class="alert alert-info">
                                    <?php echo str_replace("{var}", $moeda->nome, $idioma->getText("possuiCarteira")) ?>. <a href="<?php echo URLBASE_CLIENT . Utils\Rotas::R_CARTEIRAS ?>"><?php echo $idioma->getText("cliqueAquiCarteira")?></a> 
                                </div>
                                <?php } ?>
                                
                                <?php } else { ?>
                                <br><br>
                                <div class="alert alert-info text-center" >
                                    <?php echo $idioma->getText("funcionaNaoDispo") ?>
                                </div>
                                <?php } ?>
                            </div><br>

                            <div class="col col-lg-6">
                                <br><br>
                                <div class="alert alert-info" style="font-size: 14px">
                                    <h4><?php echo $idioma->getText("informacoes")?></h4>
                                    <ul>
                                        <li> <?php echo str_replace("{var}", $moeda->nome, $idioma->getText("aNewCashNao")) ?>.</li>
                                        <br>
                                        <li> <b><?php echo $idioma->getText("atencao") ?></b> <?php echo $idioma->getText("envieSomente") ?> <b><?php echo $moeda->nome ?></b> <?php echo $idioma->getText("paraOEnderecoAbaixo") ?></li>
                                        
                                    </ul>
                                    

                                </div>
                                
                            </div>
                        </div>
                    </div>
                    <?php } ?>
                    
                    <?php if ($configuracao->statusDepositoBrl > 0 && $mostrarAbaDepositoReais) { ?>
                    <div id="tab-2" class="tab-pane active">
                        <div class="panel-body">
                                        
                            <div class="row">
                                        <div class="col-lg-12">
                                            <div class="ibox float-e-margins">
                                                <div class="ibox-title">
                                                    <strong style="font-size: 14px"><?php echo $idioma->getText("fiqueAtento")?></strong>
                                                    <div class="ibox-tools">
                                                        <a class="collapse-link">
                                                            <i class="fa fa-chevron-up"></i>
                                                        </a>
                                                    </div>
                                                </div>
                                                <div class="ibox-content">
                                                        <div class="alert alert-danger">
                                                             <ul>
                                                                 <li><?php echo $idioma->getText("desanconselhamos")?></li>
                                                                 <li><?php echo $idioma->getText("naoRealizamos")?></li>
                                                                 <li><?php echo $idioma->getText("naoAceitamosTED")?></li>
                                                             </ul>
                                                        </div>
                                                    </div>
                                            </div>
                                        </div>
                                    </div>

                                   
                            <div class="row">
                                <div class="col col-lg-6">
                                    <form action="<?php echo URLBASE_CLIENT  . Utils\Rotas::R_REAIS_DEPOSITOS_SALVAR ?>" method="post" enctype="multipart/form-data" id="form-deposito" >
                                        <input type="hidden" value="<?php echo $deposito->id ?>" name="id" />

                                        <div class="row">
                                            <div class="col col-lg-12">
                                                <div class="form-group">
                                                    <label><?php echo $idioma->getText("tipoDeposito") ?></label>
                                                    <select class="form-control" id="tipoDeposito" name="tipoDeposito" >
                                                        <option value="<?php echo Utils\Constantes::TED ?>" <?php echo ($deposito->tipoDeposito == Utils\Constantes::TED ? "selected='true'" : "")?>><?php echo $idioma->getText("ted")?></option>
                                                        <option value="<?php echo Utils\Constantes::DOC ?>" <?php echo ($deposito->tipoDeposito == Utils\Constantes::DOC ? "selected='true'" : "")?>><?php echo $idioma->getText("doc")?></option>
                                                        <option value="<?php echo Utils\Constantes::DINHEIRO ?>" <?php echo ($deposito->tipoDeposito == Utils\Constantes::DINHEIRO ? "selected='true'" : "")?>><?php echo $idioma->getText("dinheiro")?></option>
                                                        <option value="<?php echo Utils\Constantes::TED ?>" <?php echo ($deposito->tipoDeposito == Utils\Constantes::TED ? "selected='true'" : "")?>><?php echo $idioma->getText("transEntreContas") ?></option>
                                                        <?php if ($cliente->idPaisNaturalidade == Utils\Constantes::BRASIL) { ?>
                                                        <option value="<?php echo Utils\Constantes::GERENCIA_NET ?>" <?php echo ($deposito->tipoDeposito == Utils\Constantes::GERENCIA_NET ? "selected='true'" : "")?>><?php echo $idioma->getText("boletoGerenciaNet") ?></option>
                                                        <?php } ?>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>
                                        
                                        <div class="row">
                                            <div class="col col-lg-12">
                                                <div class="form-group">
                                                    <label><?php echo $idioma->getText("selecioneOBanco") ?></label>
                                                    <select class="form-control" id="idContaBancariaEmpresa" name="idContaBancariaEmpresa">
                                                        <option value="0"><?php echo $idioma->getText("selecioneUmaConta") ?></option>
                                                        <?php 
                                                        foreach ($contasBancarias as $contaBancaria) {
                                                            ?>
                                                            <option value="<?php echo $contaBancaria->id?>" <?php echo ($deposito->idContaBancariaEmpresa == $contaBancaria->id ? "selected='true'" : "")?>>
                                                                <?php echo "{$contaBancaria->banco->codigo}-{$contaBancaria->banco->nome}";?>
                                                            </option>
                                                            <?php
                                                        }
                                                        ?>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col col-lg-12">
                                                <div class="form-group">
                                                    <label><?php echo $idioma->getText("valorDepositado")?></label>
                                                    <input type="text"  class="form-control" id="valor" name="valor" value="<?php echo number_format($deposito->valorDepositado, 2, ",", ".") ?>" />
                                                </div>
                                            </div>
                                        </div>

                                        <div class="row text-left">
                                                <div class="col col-lg-12">
                                                    <div class="form-group">
                                                        <label><?php echo $idioma->getText("comprovanDeposito")?></label>
                                                            <div class="alert alert-info" style="margin-bottom: 0px !important;">
                                                                <p>
                                                                    <?php echo $idioma->getText("informacoesEnvioArq")?>
                                                                    <br>  
                                                                <ul>
                                                                    <li><?php echo $idioma->getText("informacoesEnvioArqLi1")?></li>
                                                                    <li><?php echo $idioma->getText("informacoesEnvioArqLi2")?></li>
                                                                    <li><?php echo $idioma->getText("informacoesEnvioArqLi3")?></li>
                                                                    <li><?php echo $idioma->getText("informacoesEnvioArqLi4")?></li> 
                                                                    <li><?php echo $idioma->getText("informacoesEnvioArqLi5")?></li>
                                                                    <li><?php echo $idioma->getText("informacoesEnvioArqLi6")?></li>
                                                                </ul>
                                                                </p>
                                                            </div>
                                                             <div class="ibox-content" style="position: relative">
                                                                    <div class="fileinput fileinput-new input-group text-left" data-provides="fileinput">
                                                                        <div class="form-control" data-trigger="fileinput">
                                                                            <i class="glyphicon glyphicon-file fileinput-exists"></i> <span class="fileinput-filename"></span>
                                                                        </div>
                                                                        <span class="input-group-addon btn btn-default btn-file">
                                                                            <span class="fileinput-new"><?php echo $idioma->getText("selecionar")?></span>
                                                                            <span class="fileinput-exists"><?php echo $idioma->getText("alterar")?></span>
                                                                            <input class="full-width" type="file" id="comprovante" name="comprovante" accept=".pdf,.jpg,.jpeg,.png,.xps,.doc,.docx,.bmp">
                                                                        </span>
                                                                        <a href="#" class="input-group-addon btn btn-default fileinput-exists" data-dismiss="fileinput"><?php echo $idioma->getText("remover")?></a>
                                                                    </div>
                                                                    <div class="row" id="progressDocumentsContainer">
                                                                        <div class="col col-lg-12">
                                                                            <div class="progress">
                                                                                <div style="width: 0%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="0" role="progressbar" id="progressDocuments" class="progress-bar progress-bar-success">
                                                                                    <span class="sr-only" id="progressDocumentsLegend"></span>
                                                                                </div>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                        <?php if (!empty($deposito->comprovante)) { ?>
                                                        <a href="<?php echo URLBASE_CLIENT . UPLOADS . $deposito->comprovante ?>" target="_BLANK"><?php echo $idioma->getText("verComprovante")?></a>
                                                        <?php } ?>
                                                    </div>
                                                </div>
                                            </div>
                                        
                                        <div class="row">
                                            <div class="col col-lg-12">
                                                <h4 ><?php echo $idioma->getText("comissaoDeposito") ?> (<span id="comissaoCobradaDeposito"><?php echo number_format($comissao, 2, ",", "")?></span>%)</h4>
                                                <h4><?php echo $idioma->getText("seraCreditado") ?> <strong id="valorCreditado2"> </strong></h4>
                                                <h4><?php echo $idioma->getText("prazoMedioAprovacao")?> <?php echo $processoDeposito["media"] ?> <?php echo $idioma->getText("horas")?></strong></h4>
                                            </div>
                                        </div>

                                        <br>

                                        <div class="row">

                                            <div class="col-xs-12 col-lg-6 text-center">

                                                <?php if (\Models\Modules\Acesso\ModuloRn::validar(\Utils\Rotas::M_DEPOSITOS, \Utils\Constantes::CADASTRAR)) { ?>

                                                <?php if ($mostrarBotaoDeposito) { ?>
                                                <button class="btn btn-primary pull-right full-width" type="submit" id="btnSalvar">
                                                    <?php echo $idioma->getText("cadastrarDeposito") ?>
                                                </button>
                                                <?php } ?>

                                                <?php } ?>

                                            </div>
                                        </div>
                                    </form>
                                </div>
                                <br>
                                <div class="col col-lg-6">
                                    <div class="panel panel-primary">
                                        <div class="panel-heading">
                                            <?php echo $idioma->getText("informacoesBancoSelec") ?>
                                        </div>
                                        <div class="panel-body">
                                            <ul class="list-group">
                                                <li class="list-group-item text-center" style="display: none;" id="item-list-logo-banco">
                                                    <img src="" id="logo-banco" class="img-fluid" style="max-width: 75%; max-height: auto;"/>
                                                </li>
                                                <li class="list-group-item"><b><?php echo $idioma->getText("titular") ?> </b><span id="contaTitular"></span></li>
                                                <li class="list-group-item"><b><?php echo $idioma->getText("cnpj") ?> </b><span id="contaCnpj"></span></li>
                                                <li class="list-group-item"><b><?php echo $idioma->getText("banco") ?> </b><span id="contaNomeBanco"></span></li>
                                                <li class="list-group-item"><b><?php echo $idioma->getText("tipo") ?> </b><span id="contaTipo"></span></li>
                                                <li class="list-group-item"><b><?php echo $idioma->getText("agencia") ?> </b><span id="contaAgencia"></span></li>
                                                <li class="list-group-item"><b><?php echo $idioma->getText("conta") ?> </b><span id="contaNumero"></span></li>
                                                <br>
                                                <div id="alerta-banco" class="alert alert-danger" style="margin-bottom: 0px !important; display: none;">
                                                    <span id="alerta-banco-observacoes"></span>
                                                </div>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php } ?>
                </div>
                
            </div>
        </div>
    </div>
    <?php } // final if cliente?>    
    <br>
    

    
</section>
    
<section class="content">
    <div class="row">
        <div class="col col-lg-12">
            <div class="tabs-container">
                                 
                <?php if (\Utils\Geral::isUsuario()) { ?>
                <ul class="nav nav-tabs">
                    <li class="active"><a data-toggle="tab" href="#tab-3" data-target="#tab-3" aria-expanded="false">
                            <img src="<?php echo IMAGES?>currencies/BRL.png" style="max-width: 20px; height: 20px;" />
                            <?php echo $idioma->getText("abaReais") ?> 
                        </a>
                    </li>
                    <li class=""><a data-toggle="tab" href="#tab-4" data-target="#tab-4" aria-expanded="true">
                            <img src="<?php echo IMAGES?>currencies/<?php echo $moeda->icone ?>" style="max-width: 20px; height: 20px;" />
                            <?php echo $moeda->nome?> 
                        </a>
                    </li>
                </ul>
                <?php } ?>
                
                
                <div class="tab-content">
                    <div id="tab-4" class="tab-pane">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="panel panel-default">
                                    <?php Utils\Layout::append("mensagem", $_data) ?>
                                    <!-- /.panel-heading -->
                                    <div class="panel-body">

                                        <form id="pesquisa">                        
                                            <div class="row">
                                                <div class="col col-lg-3">
                                                    <div class="form-group">
                                                        <label><?php echo $idioma->getText("dtInicial") ?></label>
                                                        <input type="text" class="form-control" id="filtroDataInicial" value="<?php echo $dataInicial->formatar(\Utils\Data::FORMATO_PT_BR) ?>" />
                                                    </div>
                                                </div>
                                                <div class="col col-lg-3">
                                                    <div class="form-group">
                                                        <label><?php echo $idioma->getText("dtFinal") ?></label>
                                                        <input type="text" class="form-control" id="filtroDataFinal" value="<?php echo $dataFinal->formatar(\Utils\Data::FORMATO_PT_BR) ?>"/>
                                                    </div>
                                                </div>
                                                <div class="col col-lg-3">
                                                    <div class="form-group">
                                                        <label><?php echo $idioma->getText("statusDeposito") ?></label>
                                                        <select class="form-control" id="filtroStatus">
                                                            <option value="T"><?php echo $idioma->getText("todos") ?></option>
                                                            <option value="<?php echo Utils\Constantes::STATUS_DEPOSITO_PENDENTE ?>">Pendente</option>
                                                            <option value="<?php echo Utils\Constantes::STATUS_DEPOSITO_CONFIRMADO ?>">Confirmado</option>
                                                            <option value="<?php echo Utils\Constantes::STATUS_DEPOSITO_CANCELADO ?>">Cancelado</option>
                                                        </select>
                                                    </div>
                                                </div>
                                                
                                                <div class="col col-lg-3">
                                                    <div class="form-group">
                                                        <label class="control-label"><?php echo $idioma->getText("registros") ?></label>
                                                        <select class="form-control" id="nresultado">
                                                            <option value="10" >10</option>
                                                            <option value="20" >20</option>
                                                            <option value="50" >50</option>
                                                            <option value="100" >100</option>
                                                            <option value="T" ><?php echo $idioma->getText("todos") ?></option>

                                                        </select>
                                                    </div>
                                                </div>
                                            </div>
                                            
                                            <div class="row">
                                                <div class="col col-lg-6">
                                                    <div class="form-group">
                                                        <label><?php echo $idioma->getText("filtroGeral") ?></label>
                                                        <input type="text" id="filtroTextoBtc" class="form-control"/>
                                                    </div>
                                                </div>
                                                <div class="col-lg-4"></div>
                                                <div class="col-xs-12 col-lg-2">
                                                    <label>&nbsp;</label>
                                                    <div class="form-group">

                                                        <button type="button" class="btn btn-default pull-right full-width" onClick="filtrarReais();"><?php echo $idioma->getText("filtro") ?></button>
                                                    </div>
                                                </div>

                                            </div>
                                        </form>                   
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="table-responsive">
                        <table class="table table-hover table-bordered table-stripped table-condensed" style="background-color: #fff; font-size: 11px">
                            <thead>
                                <tr>
                                    <th class="text-center"><?php echo $idioma->getText("controle") ?></th>
                                    <th class="text-center"><?php echo $idioma->getText("tipoTabela") ?></th>
                                    <th class="text-center"><?php echo $idioma->getText("volume") ?></th>
                                    <th class="text-center"><?php echo $idioma->getText("comp") ?></th>
                                    <th class="text-center"><?php echo $idioma->getText("data") ?></th>
                                    <th class="text-center"><?php echo $idioma->getText("endereco") ?></th>
                                    <?php if (\Utils\Geral::isUsuario()) { ?>
                                    <th class="text-center"><?php echo $idioma->getText("acoes") ?></th>
                                    <?php } ?>
                                </tr>
                            </thead>

                            <tbody id="listaBtc" class="text-center">

                            </tbody>
                        </table>
                        </div>
                    </div>
                    <div id="tab-3" class="tab-pane active">
                        
                        <div class="row">
                            <div class="col-lg-12 col-xs-12">
                                <div class="panel panel-default">
                                    <?php Utils\Layout::append("mensagem", $_data) ?>
                                    <!-- /.panel-heading -->
                                    <div class="panel-body">

                                        <form id="pesquisa">                        
                                            <div class="row">
                                                <div class="col col-lg-3">
                                                    <div class="form-group">
                                                        <label><?php echo $idioma->getText("dtInicial") ?></label>
                                                        <input type="text" class="form-control" id="filtroDataInicialReal" value="<?php echo $dataInicial->formatar(\Utils\Data::FORMATO_PT_BR) ?>" />
                                                    </div>
                                                </div>
                                                <div class="col col-lg-3">
                                                    <div class="form-group">
                                                        <label><?php echo $idioma->getText("dtFinal") ?></label>
                                                        <input type="text" class="form-control" id="filtroDataFinalReal" value="<?php echo $dataFinal->formatar(\Utils\Data::FORMATO_PT_BR) ?>"/>
                                                    </div>
                                                </div>
                                                <div class="col col-lg-4">
                                                    <div class="form-group">
                                                        <label><?php echo $idioma->getText("realizadoConta") ?></label>
                                                        <select class="form-control" id="filtroIdContaBancariaEmpresa">
                                                            <option value="0"><?php echo $idioma->getText("todasContas") ?></option>
                                                            <?php
                                                            foreach ($contasBancarias as $contaBancaria) {
                                                                ?>
                                                                <option value="<?php echo $contaBancaria->id ?>">
                                                                    <?php echo "{$contaBancaria->banco->codigo}-{$contaBancaria->banco->nome}  {$contaBancaria->agencia}/{$contaBancaria->conta}"; ?>
                                                                </option>
                                                                <?php
                                                            }
                                                            ?>
                                                        </select>
                                                    </div>
                                                </div>
                                                <div class="col col-lg-2">
                                                    <div class="form-group">
                                                        <label><?php echo $idioma->getText("tipoDeposito") ?></label>
                                                        <select class="form-control" id="filtroTipoDeposito">
                                                            <option value="Q"><?php echo $idioma->getText("todos") ?></option>
                                                            <option value="<?php echo Utils\Constantes::TED ?>"><?php echo $idioma->getText("ted") ?></option>
                                                            <option value="<?php echo Utils\Constantes::DOC ?>"><?php echo $idioma->getText("doc") ?></option>
                                                            <option value="<?php echo Utils\Constantes::DINHEIRO ?>"><?php echo $idioma->getText("dinheiro") ?></option>
                                                            <option value="<?php echo Utils\Constantes::GERENCIA_NET ?>"><?php echo $idioma->getText("boletoGerenciaNet") ?></option>
                                                        </select>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="row">

                                                <div class="col col-lg-2">
                                                    <div class="form-group">
                                                        <label><?php echo $idioma->getText("statusDeposito") ?></label>
                                                        <select class="form-control" id="filtroStatus">
                                                            <option value="T"><?php echo $idioma->getText("todos") ?></option>
                                                            <option value="<?php echo Utils\Constantes::STATUS_DEPOSITO_PENDENTE ?>"><?php echo $idioma->getText("pendente") ?></option>
                                                            <option value="<?php echo Utils\Constantes::STATUS_DEPOSITO_CONFIRMADO ?>"><?php echo $idioma->getText("confirmado") ?></option>
                                                            <option value="<?php echo Utils\Constantes::STATUS_DEPOSITO_CANCELADO ?>"><?php echo $idioma->getText("cancelado") ?></option>
                                                        </select>
                                                    </div>
                                                </div>

                                                <div class="col col-lg-2">
                                                    <div class="form-group">
                                                        <label class="control-label"><?php echo $idioma->getText("registros") ?></label>
                                                        <select class="form-control" id="nresultadoReal">
                                                            <option value="10" >10</option>
                                                            <option value="20" >20</option>
                                                            <option value="50" >50</option>
                                                            <option value="100" >100</option>
                                                            <option value="T" ><?php echo $idioma->getText("todos") ?></option>

                                                        </select>
                                                    </div>
                                                </div>

                                                <div class="col col-lg-6">
                                                    <div class="form-group">
                                                        <label><?php echo $idioma->getText("filtroGeral") ?></label>
                                                        <input type="text" id="filtroTextoReal" class="form-control"/>
                                                    </div>
                                                </div>

                                                <div class="col-xs-12 col-lg-2">
                                                    <label>&nbsp;</label>
                                                    <div class="form-group">

                                                        <button type="button" class="btn btn-default pull-right full-width" onClick="filtrarReais();"><?php echo $idioma->getText("filtro") ?></button>
                                                    </div>
                                                </div>

                                            </div>
                                        </form>                        
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="table-responsive">
                        <table class="table table-hover table-bordered table-stripped table-condensed" style="background-color: #fff; font-size: 11px">
                            <thead>
                                <tr>
                                    <?php if (\Utils\Geral::isUsuario()) { ?>
                                    <th class="text-center">
                                        <?php echo $idioma->getText("cliente") ?>
                                    </th>
                                    <?php } ?>
                                    <th class="text-center">
                                        <?php echo $idioma->getText("controle") ?>
                                    </th>

                                    <th class="text-center">
                                        <?php echo $idioma->getText("data") ?>
                                    </th>

                                    <th class="text-center">
                                        <?php echo $idioma->getText("contaBancaria") ?>
                                    </th>
                                    <th class="text-center">
                                        <?php echo $idioma->getText("deposito") ?> 
                                    </th>
                                    <th class="text-center">
                                        <?php echo $idioma->getText("comissaoR") ?>
                                    </th>
                                    <th class="text-center">
                                        <?php echo $idioma->getText("comissaoP") ?>
                                    </th>
                                    <th class="text-center">
                                        <?php echo $idioma->getText("creditado") ?>
                                    </th>
                                    <th class="text-center">
                                        <?php echo $idioma->getText("comp") ?>
                                    </th>
                                    <th class="text-center">
                                        <?php echo $idioma->getText("nf") ?>
                                    </th>
                                    <th class="text-center">
                                        <?php echo $idioma->getText("status") ?>
                                    </th>
                                    <?php if (\Utils\Geral::isUsuario()) { ?>
                                    <th class="text-center">
                                        <?php echo $idioma->getText("analisar") ?>
                                    </th>
                                    <?php } ?>
                                </tr>
                            </thead>

                            <tbody id="listaReais">

                            </tbody>
                        </table>
                        </div>

                    </div><br>
                </div>
            </div>
        </div>
    </div>
</section>
<br><br>
<div class="clearfix"></div>


<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>

<script>
    var comissao = <?php echo number_format($comissao, 2, ".", "")?>;
    var comissaoBoleto = <?php echo number_format($comissaoBoleto, 2, ".", "")?>;
    var tarifaBoleto = <?php echo number_format($tarifaBoleto, 2, ".", "")?>;

    var comissaoDinheiroAte2 = <?php echo number_format($configuracao->percentualDepositos, 2, ".", "")?>;
    var comissaoDinheiro2a5 = <?php echo number_format($configuracao->depositoDoisCinco, 2, ".", "")?>;
    var comissaoDinheiro5a10 = <?php echo number_format($configuracao->depositoCincoDez, 2, ".", "")?>;
    var comissaoDinheiro10a50 = <?php echo number_format($configuracao->depositoDezCinquenta, 2, ".", "")?>;
    var comissaoDinheiro50acima = <?php echo number_format($configuracao->depositoCinquentaAcima, 2, ".", "")?>;

    $(document).ready(function () {
        $("#filtroIdCliente").select2();
        filtrar();
        
        new Clipboard('#spancopy');
        
        $('.i-checks').iCheck({
            checkboxClass: 'icheckbox_square-green',
            radioClass: 'iradio_square-green'
        });
        
        $("#tipoDeposito").change(function () {
            if ($(this).val() === '<?php echo \Utils\Constantes::GERENCIA_NET?>') {
                $("#idContaBancariaEmpresa").val(0);
                $("#idContaBancariaEmpresa").prop("disabled", true);
                $("#comprovante").prop("disabled", true).trigger("change");
                $("#item-list-logo-banco").show();
                $("#logo-banco").attr("src", "<?php echo IMAGES ?>logo.png");
                $("#contaTitular, #contaCnpj, #contaNomeBanco, #contaTipo, #contaAgencia, #contaNumero").val("");
            } else {
                $("#idContaBancariaEmpresa").prop("disabled", false);
                $("#item-list-logo-banco").hide();
                $("#logo-banco").attr("src", "");
                $("#comprovante").prop("disabled", false).trigger("change");
            }
            calcularValorCreditado();
        });
        
        $("#filtroDataInicial,#filtroDataFinal, #filtroDataInicialReal ,#filtroDataFinalReal").datepicker({
            format: "dd/mm/yyyy",
            todayBtn: "linked",
            language: "pt-BR",
            orientation: "top left",
            autoclose: true,
            todayHighlight: true,
            toggleActive: true,
            });
        $("#filtroDataInicial,#filtroDataFinal, #filtroDataInicialReal ,#filtroDataFinalReal").datepicker({format: 'dd/mm/yyyy'}).mask("99/99/9999");


        
        $("#idContaBancariaEmpresa").change(function () {
            getDadosContaBancaria();
        });
        
        $(function() {
            $('#tipoDeposito').change(function(){
                if($('#tipoDeposito').val() === 'R') {
                    $('#nota').hide(); 
                } else {
                    $('#nota').show(); 
                } 
            });
        });
        
        $("#valor").keydown(function (event) {
            $(this).val(currency($(this).val(), 2, 8, event.keyCode));
        event.preventDefault();
        calcularValorCreditado();
        });
        
        $("#form-deposito").ajaxForm({
            dataType: 'json',
            beforeSubmit: function () {
                //msgCarregarArquivo();
                $("#btnVoltar, #btnSalvar").prop("disabled", true);
            },
            uploadProgress: function(event, position, total, percentComplete) {
                $("#progressDocumentsContainer").show();
                var percentVal = percentComplete + '%';
                $("#progressDocuments").width(percentVal);
                $("#progressDocumentsLegend").html("<?php echo $idioma->getText("carregando")?> "+percentVal + "%");
                },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("a[data-dismiss='fileinput']").trigger("click");
                        $("#idContaBancariaEmpresa").children("option").first().prop("selected", true);
                        $("#tipoDeposito").children("option").first().prop("selected", true);
                        $("#valor").val("0,00").trigger("keydown");
                        $("#aceitaNota").prop("checked", false).trigger("change");
                        showNotyAlert("<?php echo $idioma->getText("solicitacaoDepositoSucesso")?>", "s");
                        filtrar();
                        
                        if (json.boleto) {
                            modalGerarBoleto(json.deposito);
                        }
                        
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e){
                    showNotyAlert(e, "e");
                }
                $("#btnVoltar, #btnSalvar").prop("disabled", false);
                $("#progressDocumentsContainer").hide();
                $("#progressDocuments").width("0%");
                $("#progressDocumentsLegend").html("");
            }
        });
        
        $("#tipoDeposito").change(function () {
            if ($(this).val() === '<?php echo Utils\Constantes::DINHEIRO ?>' && $("#alerta-banco-observacoes").html().length > 0) {
                $("#alerta-banco").show();
            } else {
                $("#alerta-banco").hide();
            }
        });
        
        getDadosContaBancaria();
        filtrar();
    });
    
    new Clipboard("#btn-link-ref");
    
    function filtrar() {
        filtrarReais();
        filtrarBtc();
    }
    
    function filtrarReais() {
        $("#listaReais").html("<tr><td colspan='12' class='text-center'><img src='<?php echo IMAGES ?>loading.gif' /></td></tr>");
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_REAIS_DEPOSITOS_LISTAR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                dataInicialReal: $("#filtroDataInicialReal").val(),
                dataFinalReal: $("#filtroDataFinalReal").val(),
                idCliente: $("#filtroIdCliente").val(),
                idContaBancariaEmpresa: $("#filtroIdContaBancariaEmpresa").val(),
                status: $("#filtroStatus").val(),
                tipoDeposito: $("#filtroTipoDeposito").val(),
                filtro: $("#filtroTextoReal").val(),
                nresultadoReal: $("#nresultadoReal").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#listaReais").html(json.html);
                        
                        $(".btn-popover-deposito").each(function () {
                            let controle = $(this).attr("data-controle");
                            $(this).popover({
                                html: true,
                                trigger: "focus",
                                container: "body",
                                placement: "top",
                                title: "<?php echo $idioma->getText("depositoJs")?>" + controle,
                                content: json.popover[controle]
                            });
                        });
                        
                        
                        $(".deposito-motivo").each(function () {
                            let motivo = $(this).attr("data-motivo");
                            let controle = $(this).attr("data-controle");
                            $(this).popover({
                                html: true,
                                trigger: "focus",
                                container: "body",
                                placement: "top",
                                title: "<?php echo $idioma->getText("depositoJs")?>" + controle,
                                content: motivo
                            });
                        });
                        
                    } else {
                        $("#listaReais").html("<tr><td colspan='12' class='text-center'>"+json.mensagem+"</td></tr>");
                    }
                } catch (e) {
                    $("#listaReais").html("<tr><td colspan='12' class='text-center'>"+e+"</td></tr>");
                }
            }
        });
    }
    
    
    function limpar(){
        $('#pesquisa').each (function(){
          this.reset();
          filtrar();
        });
    }

    function filtrarBtc() {
        $("#listaBtc").html("<tr><td colspan='7' class='text-center'><img src='<?php echo IMAGES ?>loading.gif' /></td></tr>");
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_BTC_CONTA_LANCAMENTOS ?>',
            method: 'post',
            dataType: 'json',
            data: {
                dataInicial: $("#filtroDataInicial").val(),
                dataFinal: $("#filtroDataFinal").val(),
                idCliente: $("#filtroIdCliente").val(),
                tipo: 'E',
                filtro: $("#filtroTextoBtc").val(),
                nresultado: $("#nresultado").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#listaBtc").html(json.html);
                    } else {
                        $("#listaBtc").html("<tr><td colspan='7'>"+json.mensagem+"</td></tr>");
                    }
                } catch (e) {
                    $("#listaBtc").html("<tr><td colspan='7'>"+e+"</td></tr>");
                }
            }
        });
    }
    
    function getDadosContaBancaria() {
        if ($("#idContaBancariaEmpresa").val() > 0) {
            $.ajax({
                url: '<?php echo URLBASE_CLIENT  . Utils\Rotas::R_REAIS_DEPOSITOS_DADOSCONTA ?>',
                method: 'post',
                dataType: 'json',
                data: {
                    idContaBancariaEmpresa: $("#idContaBancariaEmpresa").val()
                },
                success: function (json) {
                    try {
                        if (json.sucesso) {
                            
                            if (json.conta.banco.logo !== null) {
                                $("#item-list-logo-banco").show();
                                $("#logo-banco").attr("src", "<?php echo IMAGES ?>bancos/" + json.conta.banco.logo);
                            } else {
                                $("#item-list-logo-banco").hide();
                            }
                            
                            $("#contaNomeBanco").html(json.conta.banco.nome);
                            $("#contaTipo").html(json.conta.tipoConta);
                            $("#contaAgencia").html(json.conta.agencia);
                            $("#contaNumero").html(json.conta.conta);
                            $("#contaTitular").html(json.conta.titular);
                            $("#contaCnpj").html(json.conta.cnpj);
                            $("#alerta-banco-observacoes").html(json.conta.observacoes);
                            
                            if ($("#tipoDeposito").val() === '<?php echo Utils\Constantes::DINHEIRO ?>' && json.conta.observacoes.length > 0) {
                                $("#alerta-banco").show();
                            } else {
                                $("#alerta-banco").hide();
                            }
                            
                        } else {
                            showNotyAlert(json.mensagem, "e");
                        }
                    } catch (e) {
                        showNotyAlert(e, "e");
                    }
                }
            });
        }
    }
    
    function calcularValorCreditado() {
        var valor = ($("#valor").val().length > 0 ? parseFloat(toFloat($("#valor").val())) : 0);
        
        var tarifaExtra = ($("#tipoDeposito").val() === "<?php echo \Utils\Constantes::GERENCIA_NET ?>" ? tarifaBoleto : 0);
        
        var comissao = <?php echo number_format($comissao, 2, ".", "")?>;
        if ($("#tipoDeposito").val() === "<?php echo \Utils\Constantes::GERENCIA_NET ?>") {
            var comissao = <?php echo number_format($comissaoBoleto, 2, ".", "")?>;
        } else if ($("#tipoDeposito").val() === "<?php echo \Utils\Constantes::DINHEIRO ?>") {
            
            if (valor >= 50000) {
                var comissao = comissaoDinheiro50acima;
            } else if (valor >= 10000) {
                var comissao = comissaoDinheiro10a50;
            } else if (valor >= 5000) {
                var comissao = comissaoDinheiro5a10;
            } else if (valor >= 2000) {
                var comissao = comissaoDinheiro2a5;
            } else {
                var comissao = comissaoDinheiroAte2;
            }
            
        }
        
        var resultado = (valor - tarifaExtra - ((valor - tarifaExtra) * comissao / 100));
        if ($("#tipoDeposito").val() === "<?php echo \Utils\Constantes::GERENCIA_NET ?>") {
            $("#comissaoCobradaDeposito").html("R$ "+ tarifaBoleto.toFixed(2).replace(".", ",") + " + "+comissao.toFixed(2).replace(".", ","));
        } else {
            $("#comissaoCobradaDeposito").html(comissao.toFixed(2).replace(".", ","));
        }
        
        if (resultado <= 0) {
            resultado = 0;
        }
        
        $("#valorCreditado2").html("R$ " + mascaraValor(resultado.toFixed(2)));
    }
      

    function modalGerarBoleto(deposito) {
        $("#modalGerarBoletoDeposito").val(deposito);
        $("#modalGerarBoleto").modal();
    }

    function gerarBoleto() {
        $("#modalGerarBoletoBtnCancelar, #mmodalGerarBoletoBtnSalvar").prop("disabled", true);
        $.ajax({
            url: "<?php echo URLBASE_CLIENT  . Utils\Rotas::R_DEPOSITO_BOLETO_GERAR ?>",
            method: "post",
            dataType: "json",
            data: {
                deposito: $("#modalGerarBoletoDeposito").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#modalGerarBoletoBtnCancelar").prop("disabled", false).trigger("click");
                        $("#modalBoletoGeradoBarcode").html(json.barras);
                        $("#modalBoletoGeradoVencimento").html(json.vencimento);
                        $("#modalBoletoGeradoLink").attr("href",  json.link);
                        $("#modalBoletoGeradoLink").html(json.link);
                        $("#modalBoletoGeradoImgBarcode").html(json.img);
                        $("#modalBoletoGerado").modal();
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#modalGerarBoletoBtnCancelar, #mmodalGerarBoletoBtnSalvar").prop("disabled", false);
            }
        });
    }
</script>


<div class="modal inmodal" id="modalGerarBoleto" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content animated bounceInRight">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                <i class="fa fa-barcode modal-icon"></i>
                <h4 class="modal-title"><?php echo $idioma->getText("modalGerarBoletoTitulo") ?></h4>
            </div>
            <div class="modal-body">
                <input type="hidden" id="modalGerarBoletoDeposito" value="" />
                <p>
                    <strong ><?php echo $idioma->getText("modalGerarBoletoMensagem") ?></strong>
                </p>
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-white" data-dismiss="modal" id="modalGerarBoletoBtnCancelar"><?php echo $idioma->getText("modalGerarBoletoCancelar") ?></button>
                <button type="button" class="btn btn-success" onclick="gerarBoleto();"  id="mmodalGerarBoletoBtnSalvar"><?php echo $idioma->getText("modalGerarBoletoSalvar") ?></button>
            </div>
        </div>
    </div>
</div>



<div class="modal inmodal" id="modalBoletoGerado" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content animated bounceInRight">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                
                <h4 class="modal-title"><?php echo $idioma->getText("modalBoletoGeradoTitulo") ?></h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col col-lg-12 text-center" id="modalBoletoGeradoImgBarcode">
                        
                    </div>
                </div>
                <div class="row">
                    <div class="col col-lg-12 text-center" >
                        <p>
                            <strong ><?php echo $idioma->getText("modalBoletoGeradoBarras") ?> <span id="modalBoletoGeradoBarcode"></span></strong> <br>
                            <strong ><?php echo $idioma->getText("modalBoletoGeradoVencimento") ?> <span id="modalBoletoGeradoVencimento"></span></strong> <br>
                            <strong ><?php echo $idioma->getText("modalBoletoGeradoLink") ?> <a href="" target="_BLANK" id="modalBoletoGeradoLink"></a></strong> <br>
                        </p>
                    </div>
                </div>
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-white" data-dismiss="modal" ><?php echo $idioma->getText("modalBoletoGeradoFechar") ?></button>
            </div>
        </div>
    </div>
</div>