<?php
$selectMoeda = (isset($_POST['moeda'])) ? $_POST['moeda'] : '';
$selectCategoria = (isset($_POST['categoria'])) ? $_POST['categoria'] : '';
$contasBancarias = isset($_data["contas"]) ? $_data["contas"] : Array();
$configuracao = isset($_data["configuracao"]) ? $_data["configuracao"] : new \Models\Modules\Cadastro\Configuracao();
$valorMinReais = number_format($configuracao->valorMinSaqueReais, 2, ",", ".");
$idioma = new \Utils\PropertiesUtils("saque", IDIOMA);
$_data["idiomaMenu"] = $idioma;
$cliente = Utils\Geral::getCliente();
$mostrarAbaDepositoReais = isset($_data["verificado"]) ? $_data["verificado"] : false;
$comissao = isset($_data["comissao"]) ? $_data["comissao"] : 0;
$saque = isset($_data["saque"]) ? $_data["saque"] : new Models\Modules\Cadastro\Saque();
$saldo = isset($_data["saldo"]) ? $_data["saldo"] : 0;
$tarifaTed = isset($_data["tarifaTed"]) ? $_data["tarifaTed"] : 0;
$contasSemTaxaSaque = isset($_data["contasSemTaxa"]) ? $_data["contasSemTaxa"] : Array();
$valorSacado = ($saque->valorSaque - ($saque->valorSaque * $comissao / 100));

$moeda = \Modules\principal\Controllers\Principal::getCurrency();

$paridade = Modules\principal\Controllers\Principal::getParity();

$paridades = (isset($_data["paridades"]) ? $_data["paridades"]: Array() );
$casasDecimais = (isset($_data["casasDecimais"]) ? $_data["casasDecimais"]  : 2);
$dataInicial = new \Utils\Data(date("d/m/Y H:i:s"));
$dataInicial->subtrair(0, 1, 0);
$dataFinal = new \Utils\Data(date("d/m/Y H:i:s"));

$processo1 = \Utils\Criptografia::encriptyPostId(Utils\Constantes::PROCESSO_SAQUE_1);
$processo2 = \Utils\Criptografia::encriptyPostId(Utils\Constantes::PROCESSO_SAQUE_2);


?>
<style>
    .border-edit {
        border: 1px solid #1c84c6 !important;
    }
   .carregando {
   background: url("<?php echo IMAGES ?>loading.gif") center no-repeat;
    width: 200px;
    height: 200px;
    position: absolute;
    top: 30%;
    left: 45%;
    color: blue;
   }
   
   tr.strikeout td:before {
  content: " ";
  position: absolute;
  top: 50%;
  left: 0;
  border-bottom: 1px solid #111;
  width: 100%;
}

/* Caique 29/07/2019 */
    .table-new {
    width: 100%;
    max-width: 110%;
    margin-bottom: 20px;
    }
    
    

   
    /* end */
</style>
<?php Utils\Layout::append("inspina/metas", $_data) ?>
<?php Utils\Layout::append("inspina/scripts", $_data) ?>
<?php Utils\Layout::append("inspina/menu", $_data) ?>
            <div class="carregando">
            </div>
<div class="wrapper wrapper-content mostrar">
     
        <div class="row">
            <div class="col-lg-2">
                <div class="ibox float-e-margins">
                    <div class="mailbox-content">
                        <div class="file-manager mostrar" id="lista">
                            
                            <div class="clearfix"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-10 animated fadeInLeft m-t-sm">
               
                <div class="" id="saqueReais" hidden="true">                   
                    <div class="row">
                        <div class="col-lg-7">                            
                            <h2 style="display: inline;"><?php echo $idioma->getText("saqueReais") ?></h2>&nbsp;&nbsp;<img src="<?php echo IMAGES ?>currencies/BRL.png" id="imagemBanco" height="30" width="30" style="margin-bottom: 10px;"/>
                            <div id="saqueBrl">
                                <div class="row">
                                    <div class="col-lg-12">     
                                        <table class="table table-striped text-center" style="font-size: 16px; border: 1px solid #e7eaec !important; border-radius: 10px !important;">
                                            <thead>
                                                <tr class="text-center">
                                                    <th class="text-center"><?php echo $idioma->getText("saldoTotal") ?></th>
                                                    <th class="text-center"><?php echo $idioma->getText("saldoDisponivel") ?></th>
                                                    <th class="text-center"><?php echo $idioma->getText("saldoBloqueado") ?></th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr id="saldoAtual">
                                                    <td id=""></td>
                                                    <td id=""></td>
                                                    <td id=""></td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <div id="infReais">
                                    <div class="row">
                                        <div class="col-sm-12">
                                            <div class="form-group">
                                                <label><?php echo $idioma->getText("seleUmaConta") ?></label>
                                                <select class="form-control input-sm form-control input-s-sm inline" id="idContaBancaria" name="idContaBancaria">
                                                    <option value="0"><?php echo $idioma->getText("seleUmaConta") ?></option>
                                                    <?php if($configuracao->atarAtivo == 1 ){ ?>
                                                        <option value="2"><?php echo "Atar Pay" ?></option>
                                                    <?php } ?>
                                                    <option value="1"><?php echo $idioma->getText("transfInterna") ?></option>
                                                    <?php foreach ($contasBancarias as $contaBancaria) { ?>
                                                        <option value="<?php echo $contaBancaria->id ?>">                                                                
                                                            <?php
                                                            $tipoConta = strlen(\Utils\Validacao::limparString($contaBancaria->documentoCliente)) == 14 ? "Empresa" : "";
                                                            $digito = empty($contaBancaria->agenciaDigito) ? "" : "-{$contaBancaria->agenciaDigito}";
                                                            echo "{$contaBancaria->banco->nome}    |    {$contaBancaria->agencia}{$digito} / {$contaBancaria->conta}-{$contaBancaria->contaDigito} / {$tipoConta}";
                                                            ?>
                                                        </option>
                                                <?php } ?>
                                                </select>
                                            </div>
                                        </div>
                                    </div> 
                                    <div class="row" id="emailCliente" hidden="true">
                                        <div class="col col-lg-12 border-right">
                                            <div class="form-group">
                                                <label><?php echo $idioma->getText("email") ?></label>
                                                <div class="input-group">
                                                    <input type="text"  class="form-control" id="email" name="email" value="" />
                                                    <span class="input-group-btn">
                                                        <button type="button" class="btn btn-primary" onclick="findCliente();">&nbsp;<i class="fa fa-search"></i></button>
                                                    </span>
                                                </div>
                                                <strong><span id="nomeCliente"></span></strong>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row" id="atar" hidden="true">
                                        <div class="col col-lg-12 border-right">
                                            <div class="form-group">
                                                <label><?php echo "Informe o CPF ou CNPJ do destinatário Atar" ?></label>
                                                <input type="text"  class="form-control" id="atarDoc" name="atarDoc" value="" />
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col col-lg-6 border-right">
                                            <div class="form-group">
                                                <label><?php echo $idioma->getText("valor") ?></label>
                                                <div class="input-group">
                                                    <input type="text"  class="form-control" id="valorReais" name="valorReais" value="0,00" />
                                                    <span class="input-group-btn">
                                                        <button type="button" class="btn btn-primary" onclick="getSaldoDisponivel();"><?php echo $idioma->getText("meuSaldoTotal") ?></button>
                                                    </span>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-6 m-t-xs">
                                            <small><?php echo $idioma->getText("comiSaque") ?> <span id="comissaoCobradaSaque"><?php echo number_format($comissao, 2, ",", "") ?></span>%</small></br>
                                            <small><?php echo $idioma->getText("tarifaTansfer") ?> <span id="tarifaTransferencia"></span></small></br>
                                            <small><?php echo $idioma->getText("seraCreditadaNaConta") ?> <strong id="valorSacado2"></strong></small></br>
                                        </div>
                                    </div>
                                    <div class="row">                                            
                                        <div class="col-lg-4">
                                            <div class="form-group">  
                                                <button class="btn btn-primary full-width" type="button" onclick="saqueTransferir('<?php echo $processo1 ?>');" id="btnSalvar">
                                                    <?php echo $idioma->getText("confirmaSaque") ?>
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div id="carregaTokenBrl" class="text-center" hidden="true"></div>
                                <div class="row" id="token2faBrl" hidden="true">                                
                                <div class="col-lg-12">                                     
                                    <label><?php echo $idioma->getText("insiraSeuToken") ?></label>                                    
                                    <ul class="list-group">
                                        <li class="list-group-item" style="height: 30px !important; padding-bottom: 5px !important; padding-top: 5px !important;"><b>Nome Titular:</b> <span id="nomeTitular"></span></li>
                                        <li class="list-group-item" style="height: 30px !important; padding-bottom: 5px !important; padding-top: 5px !important;"><b>Documento:</b> <span id="documentoCPF"></span></li>
                                        <li class="list-group-item" style="height: 30px !important; padding-bottom: 5px !important; padding-top: 5px !important;"><b>Banco:</b> <span id="bancoInf"></span></li>
                                        <li class="list-group-item" style="height: 30px !important; padding-bottom: 5px !important; padding-top: 5px !important;"><b>Agência:</b> <span id="agencia"></span>&nbsp;&nbsp;&nbsp;<b>Conta: </b><span id="conta"></span></li>
                                        <li class="list-group-item" style="height: 30px !important; padding-bottom: 5px !important; padding-top: 5px !important;"><b>Valor Solicitado:</b> <span id="valorSolicitado"></span>&nbsp;&nbsp;&nbsp;<b>Valor do Saque:</b> <strong><span id="valorSaque"></span></strong></li>
                                        <li class="list-group-item">
                                            <div class="row">
                                                <div class="col-lg-6">
                                                    <div class="form-group">
                                                        <label><?php echo $idioma->getText("pin") ?></label>
                                                        <input type="password" inputmode="numeric" pattern="[0-9]*" class="form-control" id="pinBrl"/>
                                                    </div>
                                                </div>
                                                <div class="col-lg-6">
                                                    <div class="form-group m-b-none">
                                                        <label><?php echo $idioma->getText("token2fa") ?></label>
                                                        <input type="text" inputmode="numeric" pattern="[0-9]*" class="form-control" id="tokenBrl"/>
                                                        <?php if($cliente->tipoAutenticacao === \Utils\Constantes::TIPO_AUTH_EMAIL){ ?>
                                                            <a href="javascript:saqueTransferir('<?php echo $processo1 ?>');" id="reenviarLink"><?php echo $idioma->getText("reenviar2fa") ?></a>
                                                        <?php }?>
                                                    </div>
                                                </div> 
                                            </div>
                                        </li>
                                        <li class="list-group-item text-center">
                                            <div class="row">
                                                <div class="col-lg-6">
                                                    <button class="btn btn-white" style="width: 180px;" onclick="cancelarTransferencia();"><?php echo $idioma->getText("cancelar") ?></button>
                                                </div>
                                                <div class="col-lg-6">
                                                    <button class="btn btn-success" style="width: 180px;" onclick="saqueTransferir('<?php echo $processo2 ?>');"><?php echo $idioma->getText("confirmar") ?></button>
                                                </div>
                                            </div>
                                        </li>
                                    </ul>
                                </div>                            
                            </div>
                                <?php if($configuracao->atarAtivo == 1) { ?>
                                <div class="row" id="token2faAtar" hidden="true">                                
                                        <div class="col-lg-12">                                     
                                            <label><?php echo $idioma->getText("insiraSeuToken") ?></label>                                    
                                            <ul class="list-group">
                                                <li class="list-group-item" style="height: 30px !important; padding-bottom: 5px !important; padding-top: 5px !important;"><b>Documento:</b> <span id="documentoAtar"></span></li>
                                                <li class="list-group-item" style="height: 30px !important; padding-bottom: 5px !important; padding-top: 5px !important;"><b>Valor Solicitado:</b> <span id="valorSolicitadoAtar"></span>&nbsp;&nbsp;&nbsp;<b>Valor do Saque:</b> <strong><span id="valorSaqueAtar"></span></strong></li>
                                                <li class="list-group-item">
                                                    <div class="row">
                                                        <div class="col-lg-6">
                                                            <div class="form-group">
                                                                <label><?php echo $idioma->getText("pin") ?></label>
                                                                <input type="password" inputmode="numeric" pattern="[0-9]*" class="form-control" id="pinAtar"/>
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-6">
                                                            <div class="form-group m-b-none">
                                                                <label><?php echo $idioma->getText("token2fa") ?></label>
                                                                <input type="text" inputmode="numeric" pattern="[0-9]*" class="form-control" id="tokenAtar"/>
                                                                <?php if ($cliente->tipoAutenticacao === \Utils\Constantes::TIPO_AUTH_EMAIL) { ?>
                                                                    <a href="javascript:atar();" id="reenviarLinkAtar"><?php echo $idioma->getText("reenviar2fa") ?></a>
                                                                <?php } ?>
                                                            </div>
                                                        </div> 
                                                    </div>
                                                </li>
                                                <li class="list-group-item text-center">
                                                    <div class="row">
                                                        <div class="col-lg-6">
                                                            <button class="btn btn-white" style="width: 180px;" onclick="cancelarTransferencia();"><?php echo $idioma->getText("cancelar") ?></button>
                                                        </div>
                                                        <div class="col-lg-6">
                                                            <button class="btn btn-success" style="width: 180px;" onclick="saqueAtar();"><?php echo $idioma->getText("confirmar") ?></button>
                                                        </div>
                                                    </div>
                                                </li>
                                            </ul>
                                        </div>                            
                                    </div>
                                <?php } ?>
                                <div class="row" id="progressDocumentsContainer">
                                    <div class="col col-lg-12">
                                        <div class="progress">
                                            <div style="width: 0%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="0" role="progressbar" id="progressDocuments" class="progress-bar progress-bar-success">
                                                <span class="sr-only" id="progressDocumentsLegend"></span>
                                            </div>
                                        </div>
                                    </div>
                                </div>                                
                            </div>
                        </div>
                            <div class="col-lg-5">
                                <div id="vertical-timeline" class="vertical-container light-timeline no-margins">
                                    <?php if($configuracao->atarAtivo == 1 ) { ?>
                                    <div class="vertical-timeline-block">
                                        <div class="vertical-timeline-icon blue-bg">
                                            <i class="fa fa-info fa-1x"></i>
                                        </div>
                                        <div class="vertical-timeline-content">
                                            <strong class="text-center"><h5><?php echo "ATAR PAY" ?> </h5></strong><!--informacoes-->
                                            <small><ul>
                                                    <li class="m-t-xs"><?php echo "Saques via Atar Pay são instantâneos e 24/7." ?></li>
                                                    <li class="m-t-xs"><?php echo "Baixe o app Atar Pay e crie sua conta grátis em apenas 2 minutos." ?></li>
                                                    <li class="m-t-xs"><a href="https://apps.apple.com/br/app/atar-pay/id1144625341" target="atar_pay"><?php echo "Link iOS" ?></a></li>
                                                    <li class="m-t-xs"><a href="https://play.google.com/store/apps/details?id=com.wearatar.atarpay&hl=en" target="atar_pay"><?php echo "Link Android" ?></a></li>
                                                    <li class="m-t-xs">Valor disponível para saque: <span id="atarSaldo">R$ 0,00</span></li> 
                                                </ul></small> 
                                        </div>
                                    </div>
                                    <?php } ?>
                                    <div class="vertical-timeline-block">
                                        <div class="vertical-timeline-icon blue-bg">
                                            <i class="fa fa-info fa-1x"></i>
                                        </div>
                                        <div class="vertical-timeline-content">
                                            <strong class="text-center"><h5><?php echo $idioma->getText("informacoes") ?> </h5></strong>
                                            <small><ul>
                                                    <li class="m-t-xs"><?php echo $idioma->getText("saque5"); ?></li>
                                                    <li class="m-t-xs"><?php echo $idioma->getText("saque6"); ?></li>
                                                    <li class="m-t-xs"><?php echo str_replace("{var}", $valorMinReais, $idioma->getText("saque1")) ?></li>                                                    
                                                    <li class="m-t-xs"><?php echo $idioma->getText("saque2") ?></li>
                                                    <li class="m-t-xs"><?php echo $idioma->getText("saque3") ?></li>
                                                    <li class="m-t-xs"><?php echo $idioma->getText("paraBrasileiro") ?></li>                                                    
                                                </ul></small> 
                                        </div>
                                    </div>                                    
                                </div>
                                </br>
                            </div>

                            <!--Tabela Reais-->
                            <div id="tabelaReais">
                                <div class="ibox-content">
                                    <div class="row">
                                        <div class="col-sm-2 ">
                                            <select class="form-control input-sm form-control input-s-sm inline" id="filtroStatus">
                                                <option value="T"><?php echo $idioma->getText("todos") ?></option>
                                                <option value="<?php echo Utils\Constantes::STATUS_SAQUE_PENDENTE ?>"><?php echo $idioma->getText("pendente") ?></option>
                                                <option value="<?php echo Utils\Constantes::STATUS_SAQUE_CONFIRMADO ?>"><?php echo $idioma->getText("confirmado") ?></option>
                                                <option value="<?php echo Utils\Constantes::STATUS_SAQUE_CANCELADO ?>"><?php echo $idioma->getText("cancelado") ?></option>
                                            </select>
                                        </div>
                                        <div class="col-sm-3 ">
                                            <select class="form-control input-sm form-control input-s-sm inline" id="filtroIdContaBancaria">
                                                <option value="0"><?php echo $idioma->getText("todasContas") ?></option>
                                                <?php foreach ($contasBancarias as $contaBancaria) { ?>
                                                    <option value="<?php echo $contaBancaria->id ?>">
                                                        <?php echo "{$contaBancaria->banco->nome}  {$contaBancaria->agencia}/{$contaBancaria->conta}"; ?>
                                                    </option>
                                                <?php } ?>
                                            </select>
                                        </div>                                        
                                        <div class="col-sm-3 ">
                                            <div data-toggle="buttons" class="btn-group" id="radioDatas">
                                                <label class="btn btn-sm btn-white" id="diaReal"> <input type="radio"  name="options" value="dia"><?php echo $idioma->getText("dia") ?></label>
                                                <label class="btn btn-sm btn-white active" id="semanaReal"> <input type="radio"  name="options" value="semana"><?php echo $idioma->getText("semana") ?></label>
                                                <label class="btn btn-sm btn-white" id="mesReal"> <input type="radio"  name="options" value="mes"><?php echo $idioma->getText("mes") ?></label>
                                                <label class="btn btn-sm btn-white" id="todosReal"> <input type="radio"  name="options" value="todos"><?php echo $idioma->getText("todos") ?></label>
                                            </div>
                                        </div>
                                        <div class="col-sm-offset-1 col-sm-3 ">
                                            <div class="input-group">
                                                <input type="text" id="filtroTextoReal" placeholder="<?php echo $idioma->getText("pesquisar") ?>" class="input-sm form-control"><span class="input-group-btn">
                                                    <button type="button" class="btn btn-sm btn-primary" onclick="filtrarReaisAux();">&nbsp;<i class="fa fa-search"></i></button>
                                                    <button type="button" class="btn btn-sm btn-default" onclick="limpaSearchReal();">&nbsp;<i class="fa fa-eraser"></i></button></span>
                                            </div>
                                        </div>
                                    </div>                            
                                    <div class="table-responsive ">
                                        <table id="tbllistareais" class="table table-striped text-center" data-page-size="8"  style="font-size: 16px;">
                                            <thead>
                                                <tr>
                                                    <th class="text-center">
                                                        <?php echo $idioma->getText("controle") ?>
                                                    </th>
                                                    <th class="text-center">
                                                        <?php echo $idioma->getText("data") ?>
                                                    </th>
                                                    <th class="text-center">
                                                        <?php echo $idioma->getText("conta") ?>
                                                    </th>
                                                    <th class="text-center">
                                                        <?php echo $idioma->getText("valor") ?> 
                                                    </th>
                                                    <th class="text-center">
                                                        <?php echo $idioma->getText("comissaoR") ?>
                                                    </th>
                                                    <th class="text-center">
                                                        <?php echo $idioma->getText("comissaoP") ?>
                                                    </th>
                                                    <th class="text-center">
                                                        <?php echo $idioma->getText("taxaTed") ?>
                                                    </th>
                                                    <th class="text-center">
                                                        <?php echo $idioma->getText("creditado") ?>
                                                    </th>
                                                    <th class="text-center">
                                                        <?php echo $idioma->getText("comp") ?>
                                                    </th>
                                                    <th class="text-center">
                                                        <?php echo $idioma->getText("nf") ?>
                                                    </th>
                                                    <th class="text-center">
                                                        <?php echo $idioma->getText("status") ?>
                                                    </th>
                                                </tr>
                                            </thead>
                                            <tbody id="listaReais">

                                            </tbody>
                                            <tfoot>
                                                <tr>
                                                    <td colspan="11">
                                                        <ul class="pagination pull-right"></ul>
                                                    </td>
                                                </tr>
                                            </tfoot>
                                        </table>
                                    </div>                        
                                </div>
                            </div>
                            
                            <div id="tabelaAtar" hidden="true">
                                <div class="ibox-content">
                                    <div class="row">                                                                                
                                        <div class="col-sm-3 ">
                                            <div data-toggle="buttons" class="btn-group" id="radioDatasAtar">
                                                <label class="btn btn-sm btn-white" id="diaAtar"> <input type="radio"  name="optionsAtar" value="dia"><?php echo $idioma->getText("dia") ?></label>
                                                <label class="btn btn-sm btn-white active" id="semanaAtar"> <input type="radio"  name="optionsAtar" value="semana"><?php echo $idioma->getText("semana") ?></label>
                                                <label class="btn btn-sm btn-white" id="mesAtar"> <input type="radio"  name="optionsAtar" value="mes"><?php echo $idioma->getText("mes") ?></label>
                                                <label class="btn btn-sm btn-white" id="todosAtar"> <input type="radio"  name="optionsAtar" value="todos"><?php echo $idioma->getText("todos") ?></label>
                                            </div>
                                        </div>
                                        <div class="col-sm-offset-6 col-sm-3 ">
                                            <div class="input-group">
                                                <input type="text" id="filtroTextoAtar" placeholder="<?php echo $idioma->getText("pesquisar") ?>" class="input-sm form-control"><span class="input-group-btn">
                                                    <button type="button" class="btn btn-sm btn-primary" onclick="filtrarAtarAux();">&nbsp;<i class="fa fa-search"></i></button>
                                                    <button type="button" class="btn btn-sm btn-default" onclick="filtrarAtar();">&nbsp;<i class="fa fa-eraser"></i></button></span>
                                            </div>
                                        </div>
                                    </div>                            
                                    <div class="table-responsive ">
                                        <table id="tbllistaAtar" class="table table-striped text-center" data-page-size="8"  style="font-size: 16px;">
                                            <thead>
                                                <tr>                                                    
                                                    <th class="text-center">
                                                        <?php echo $idioma->getText("data") ?>
                                                    </th>                                                    
                                                    <th class="text-center">
                                                        <?php echo $idioma->getText("valor") ?> 
                                                    </th>
                                                    <th class="text-center">
                                                        <?php echo $idioma->getText("comissaoP") ?>
                                                    </th>
                                                    <th class="text-center">
                                                        <?php echo $idioma->getText("taxaTed") ?>
                                                    </th>
                                                    <th class="text-center">
                                                        <?php echo $idioma->getText("creditado") ?>
                                                    </th>
                                                    <th class="text-center">
                                                        <?php echo "Destino" ?>
                                                    </th>                                                    
                                                    <th class="text-center">
                                                        <?php echo $idioma->getText("status") ?>
                                                    </th>
                                                </tr>
                                            </thead>
                                            <tbody id="listaAtar">

                                            </tbody>
                                            <tfoot>
                                                <tr>
                                                    <td colspan="11">
                                                        <ul class="pagination pull-right"></ul>
                                                    </td>
                                                </tr>
                                            </tfoot>
                                        </table>
                                    </div>                        
                                </div>
                            </div>
                        </div>
                </div>
                
                <div id="saqueMoedas" hidden="true">
                    <div class="row">
                        <div class="col-lg-7">
                            <h2 id="tituloMoeda" style="display: inline;"></h2>&nbsp;&nbsp;<img id="icone" src="" height="25" width="25" style="margin-bottom: 10px;"/>
                            <div class="row">
                                <div class="col-lg-12">
                                    <table class="table table-striped text-center" style="font-size: 16px; border: 1px solid #e7eaec !important; border-radius: 10px !important;">
                                        <thead>
                                            <tr class="text-center">
                                                <th class="text-center"><?php echo $idioma->getText("saldoTotal") ?></th>
                                                <th class="text-center"><?php echo $idioma->getText("saldoDisponivel") ?></th>
                                                <th class="text-center"><?php echo $idioma->getText("saldoBloqueado") ?></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr id="saldoAtualBtc">
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div id="infMoeda">
                            <div class="row">
                                <div class="col-lg-12">      
                                    <div class="form-group">
                                        <label><?php echo $idioma->getText("carteiraDestino") ?></label>
                                        <input type="text" class="form-control" id="endereco"/>
                                    </div>
                                </div>
                            </div>                            
                            <div class="row">
                                <div class="col col-lg-7 border-right">
                                    <div class="form-group">
                                        <label><?php echo $idioma->getText("volume") ?></label>
                                        <div class="input-group">
                                            <input type="text"  class="form-control" inputmode="numeric" pattern="[0-9]*" id="valor" name="valor" value="0.00000000" />
                                            <span class="input-group-btn">
                                                <button type="button" class="btn btn-primary" onclick="getSaldoDisponivel();"><?php echo $idioma->getText("meuSaldoTotal") ?></button>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-5 m-t-sm" style="font-size: 16px !important;">
                                    <span><?php echo $idioma->getText("taxa") ?>:</span> <span id="comissaoCobradaBtc"></span></br>                                    
                                    <strong><span><?php echo $idioma->getText("seraDebitado") ?>:</span> <span id="debitadoBtc"></span></strong></br>                                      
                                </div>
                            </div>                            
                            <div class="row">
                                <div class="col-lg-4">      
                                    <button class="btn btn-primary full-width" onclick="confirmarTransferencia();"><?php echo $idioma->getText("transferir") ?></button>
                                </div>
                            </div> 
                            </div>
                            <div id="carregaToken" class="text-center" hidden="true"></div>
                            <div class="row" id="token2fa" hidden="true">                                
                                <div class="col-lg-12">                                     
                                    <label><?php echo $idioma->getText("insiraSeuToken") ?></label>                                    
                                    <ul class="list-group">
                                        <li class="list-group-item"><b><?php echo $idioma->getText("volume") ?>: </b><span id="volumeConfirmar"></span></li>
                                        <li class="list-group-item"><b><?php echo $idioma->getText("carteira") ?>: </b><span id="enderecoConfirmar"></span></li>                                            
                                        <li class="list-group-item">
                                            <div class="row">
                                                <div class="col-lg-6">
                                                    <div class="form-group">
                                                        <label><?php echo $idioma->getText("pin") ?></label>
                                                        <input type="password" inputmode="numeric" pattern="[0-9]*" class="form-control" id="pin"/>
                                                    </div>
                                                </div>
                                                <div class="col-lg-6">
                                                    <div class="form-group m-b-none">
                                                        <label><?php echo $idioma->getText("token2fa") ?></label>
                                                        <input type="text" inputmode="numeric" pattern="[0-9]*" class="form-control" id="token"/>
                                                        <?php if($cliente->tipoAutenticacao === \Utils\Constantes::TIPO_AUTH_EMAIL){ ?>
                                                            <a href="javascript:confirmarTransferencia();" id="reenviarLink"><?php echo $idioma->getText("reenviar2fa") ?></a>
                                                        <?php }?>
                                                    </div>
                                                </div> 
                                            </div>
                                        </li>
                                        <li class="list-group-item text-center">
                                            <div class="row">
                                                <div class="col-lg-6">
                                                    <button class="btn btn-white" style="width: 180px;" onclick="cancelarTransferencia();"><?php echo $idioma->getText("cancelar") ?></button>
                                                </div>
                                                <div class="col-lg-6">
                                                    <button class="btn btn-success" style="width: 180px;" onclick="transferirCurrency();"><?php echo $idioma->getText("confirmar") ?></button>
                                                </div>
                                            </div>
                                        </li>
                                    </ul>
                                </div>                            
                            </div>
                        </div>
                        <div class="col-lg-5">
                            <div id="vertical-timeline" class="vertical-container light-timeline no-margins">
                                <div class="vertical-timeline-block">
                                    <div class="vertical-timeline-icon blue-bg">
                                        <i class="fa fa-info fa-1x"></i>
                                    </div>
                                    <div class="vertical-timeline-content">
                                        <strong class="text-center"><h5><?php echo $idioma->getText("informacoes") ?></h5></strong>
                                        <small><ul>
                                                <li class="m-t-xs" id="useCarteira"></li>
                                            </ul></small>                    
                                    </div>
                                </div>                                
                            </div>
                            </br>
                            <div id="vertical-timeline" class="vertical-container light-timeline no-margins">
                                <div class="vertical-timeline-block">
                                    <div class="vertical-timeline-icon yellow-bg">
                                        <i class="fa fa-exclamation-triangle fa-1x"></i>
                                    </div>
                                    <div class="vertical-timeline-content">
                                        <strong class="text-center"><h5><?php echo $idioma->getText("atencao") ?></h5></strong>
                                        <small>
                                            <ul>  
                                                <li class="m-t-xs"><?php echo $idioma->getText("irreversiveis") ?></li>
                                            </ul>
                                        </small> 
                                    </div>
                                </div>                                    
                            </div>
                        </div>                        
                    </div>
                    </br></br>
                    <!--Tabela Moeda-->
                    <div id="tabelaMoeda">
                        <div class="ibox-content">
                            <div class="row">
                                <div class="col-sm-4 ">
                                    <div data-toggle="buttons" class="btn-group" id="radioDatasBtc">
                                        <label class="btn btn-sm btn-white" id="diaBtc"> <input type="radio" id="" name="optionsBtc" value="dia"><?php echo $idioma->getText("dia") ?></label>
                                        <label class="btn btn-sm btn-white active" id="semanaBtc"> <input type="radio" id="" name="optionsBtc" value="semana"><?php echo $idioma->getText("semana") ?></label>
                                        <label class="btn btn-sm btn-white" id="mesBtc"> <input type="radio" id="" name="optionsBtc" value="mes"><?php echo $idioma->getText("mes") ?></label>
                                        <label class="btn btn-sm btn-white" id="todosBtc"> <input type="radio" id="" name="optionsBtc" value="todos"><?php echo $idioma->getText("todos") ?></label>
                                    </div>
                                </div>
                                <div class="col-sm-offset-5 col-sm-3 pull-left">
                                    <div class="input-group">
                                        <input type="text" id="filtroTextoBtc" placeholder="<?php echo $idioma->getText("pesquisar") ?>" class="input-sm form-control"><span class="input-group-btn">
                                        <button type="button" class="btn btn-sm btn-primary" onclick="filtrarBtcAux();">&nbsp;<i class="fa fa-search"></i></button>
                                        <button type="button" class="btn btn-sm btn-default" onclick="limpaSearchBtc();">&nbsp;<i class="fa fa-eraser"></i></button></span>
                                    </div>
                                </div>
                            </div>   
                            
                        <div class="table-responsive ">
                                <table id="tbllistabtc" class="table table-striped text-center" data-page-size="6"  style="font-size: 16px;">
                                    <thead>
                                    <tr>
                                        <tr>                                            
                                            <th class="text-center"><?php echo $idioma->getText("controle") ?></th>
                                            <th class="text-center"><?php echo $idioma->getText("data") ?></th>
                                            <th class="text-center"><?php echo $idioma->getText("volume") ?></th>
                                            <th class="text-center"><?php echo $idioma->getText("taxa") ?></th>
                                            <th class="text-center"><?php echo $idioma->getText("carteira") ?></th>
                                            <th class="text-center"><?php echo $idioma->getText("status") ?></th>
                                            <th class="text-center"><?php echo $idioma->getText("hash") ?></th>
                                        </tr>
                                    </tr>
                                    </thead>
                                    <tbody id="listaCripto">                                    
                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <td colspan="5">
                                                <ul class="pagination pull-right"></ul>
                                            </td>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>
                    </div>
                    </div>
                </div>
                <div id="ultimosSaques" class="mostrar" hidden="true">
                    <div class="row">
                        <div class="col-lg-12">
                            <h2 style="display: inline;"><?php echo $idioma->getText("meusUltimosSaques") ?></h2>
                            <div class="table-responsive" style="margin-top: 33px;">
                                <input type="text" class="form-control input-sm m-b-xs col-offset-4 col-lg-2" id="filter"
                                   placeholder="<?php echo $idioma->getText("pesquisar") ?>" style="margin-bottom: 10px !important;">

                                        <table id="tblultimosdepositos" class="table table-stripped text-center" data-page-size="15" data-filter=#filter style="font-size: 16px;">
                                    <thead>
                                    <tr>
                                        <th class="text-center"><?php echo $idioma->getText("data") ?></th>
                                        <th class="text-center"><?php echo $idioma->getText("hora") ?></th>
                                        <th class="text-center"><?php echo $idioma->getText("moeda") ?></th>
                                        <th class="text-center"><?php echo $idioma->getText("volume") ?></th>
                                        <th class="text-center"><?php echo $idioma->getText("comprovante") ?></th>
                                        <th class="text-center"><?php echo $idioma->getText("status") ?></th>
                                    </tr>
                                    </thead>
                                    <tbody id="listaDepositos">                                    
                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <td colspan="6">
                                                <ul class="pagination pull-right"></ul>
                                            </td>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            
            </div>                
            <div class="clearfix"></div>
        </div>
    </div>

    <?php Utils\Layout::append("inspina/footer_esp", $_data) ?>
    <script>
    var comissao = <?php echo number_format($comissao, 2, ".", "")?>;
    var dataReal = "";
    var dataAtar = "";
    var dataCoin = "";
    var moeda = "";
    var banco = "";
    var boleto = false;
    var taxaMoeda = 0.00000000;
    var contasSemTaxa = <?php echo json_encode($contasSemTaxaSaque) ?>;
    var saldoDisponivel = "";
    var interval = null;
    var simbolo = "";
    var tarifaAtar = 0;
    
    
    $(document).ready(function () {  
        atarSaldo();
        setInterval(atarSaldo, 10000);
         
        $("#btnSalvar").prop("disabled", true);          
        new Clipboard("#barCode");
        
        $('#tblultimosdepositos').footable();
        $('#tbllistabtc').footable();
        $('#tbllistareais').footable();
        $('#tblListaBoleto').footable();
        $('#tbllistaAtar').footable();
        
        $("#filtroStatus").change(function () {
           filtrarReais();  
        }); 
        
        $("#filtroStatusBtc").change(function () {
           filtrarBtc();  
        });

        $("#filtroIdContaBancaria").change(function () {
           filtrarReais();  
        });
        
        $("#radioDatas input").on('change', function(){
            dataReal = $('input[name="options"]:checked', '#radioDatas').val();
            filtrarReais();  
       });
        $("#radioDatasBtc input").on('change', function(){
            dataCoin = $('input[name="optionsBtc"]:checked', '#radioDatasBtc').val();
            filtrarBtc();  
       });
        
               
       <?php if($configuracao->atarAtivo == 1){ ?>
           $("#radioDatasAtar input").on('change', function(){
                dataAtar = $('input[name="optionsAtar"]:checked', '#radioDatasAtar').val();
                filtrarAtar();  
           });
       <?php }?>
        
        new Clipboard("#btn-link-ref");
             
        $("#saqueReais").hide();
        $("#saqueMoedas").hide();
        $("#moeda, #filtroMoeda").select2();
        $(".mostrar").show();
        listar();
        listaUltimosSaques();

       $("#valorReais").keydown(function (event) {
            $(this).val(currency($(this).val(), 2, 8, event.keyCode));
            event.preventDefault();
            calcularValorSacado();
        });
        
        $("#valor").keydown(function (event) {
            $(this).val(currency($(this).val(), 8, 8, event.keyCode));
            event.preventDefault();
            calcularValorTotal();
        });

        $("#idContaBancaria").change(function () {
            calcularValorSacado();
        });

        $("#idContaBancaria").change(function () {
        if ($(this).val() == 1) {
            $("#valorReais").html('0,00');
            $("#comissaoCobradaSaque").html('0,00');
            $("#tarifaTransferencia").html('R$ <?php echo number_format($configuracao->taxaTransferenciaInternaReais, 2, ",", ".")?>');
            $("#atar").attr("hidden", true);
            $("#emailCliente").attr("hidden", false);
            filtrarReais();
        } else {
            $("#valorReais").html('0,00');
            $("#comissaoCobradaSaque").html('<?php echo number_format($comissao, 2, ",", ".") ?>');
            $("#tarifaTransferencia").html('R$ <?php echo number_format($tarifaTed, 2, ",", ".")?>');
            $("#emailCliente").attr("hidden", true);
        }
        });
        
        $("#idContaBancaria").change(function () {
        if ($(this).val() == 2) {
            $("#valorReais").html('0,00');
            $("#atarDoc").val('');
            $("#comissaoCobradaSaque").html('<?php echo number_format($configuracao->atarTaxaSaque, 2, ",", ".") ?>');
            $("#tarifaTransferencia").html('R$ <?php echo number_format($configuracao->atarTarifaSaque, 2, ",", ".")?>');
            tarifaAtar = <?php echo number_format($configuracao->atarTarifaSaque, 2, ".", "")?>;
            $("#emailCliente").attr("hidden", true);
            $("#atar").attr("hidden", false);
            $("#tabelaReais").attr("hidden", true);
            $("#tabelaAtar").attr("hidden", false);
            filtrarAtar();
           
        } else {
            $("#valorReais").html('0,00');
            $("#comissaoCobradaSaque").html('<?php echo number_format($comissao, 2, ",", ".") ?>');
            $("#tarifaTransferencia").html('R$ <?php echo number_format($tarifaTed, 2, ",", ".")?>');
            $("#tabelaReais").attr("hidden", false);
            $("#tabelaAtar").attr("hidden", true);            
        }
        });
        
        $("#idContaBancaria").change(function () {
        if ($(this).val() != 2 && $(this).val() != 1) {
            $("#valorReais").html('0,00');           
            $("#comissaoCobradaSaque").html('<?php echo number_format($comissao, 2, ",", ".") ?>');
            $("#tarifaTransferencia").html('R$ <?php echo number_format($tarifaTed, 2, ",", ".")?>');
            $("#emailCliente").attr("hidden", true);
            $("#tabelaAtar").attr("hidden", true);
            $("#atar").attr("hidden", true);
            $("#tabelaReais").attr("hidden", false);
            filtrarReais();
        } 
        });

        });
        
    function updateSaldo(ativa){
        if(ativa){
            saldos();
            interval = setInterval(saldos,10000);
        }else{
            clearInterval(interval);
        }
    
    }
    
    function confirmarTransferencia(){
        $("#infMoeda").hide();
        $("#token2fa").hide();
        $("#carregaToken").show();
        $("#carregaToken").html("<img src='<?php echo IMAGES ?>loading.gif' />");
        
        $.ajax({
                url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_BTC_AUTORIZACAO_TOKEN  ?>',
                method: 'post',
                dataType: 'json',
                data: {
                    enderecoBitcoin:  $("#endereco").val(),
                    valor: $("#valor").val(),
                    moeda: moeda
                },
                success: function (json) {
                    try {
                        if (json.sucesso) {
                            $("#enderecoConfirmar").html($("#endereco").val());
                            $("#volumeConfirmar").html($("#debitadoBtc").html());
                            $("#carregaToken").hide();
                            $("#infMoeda").hide();
                            $("#token2fa").show();
                            showNotyAlert(json.mensagem, "s");
                        } else {
                            $("#carregaToken").hide();
                            $("#token2fa").hide();
                            $("#infMoeda").show();
                            showNotyAlert(json.mensagem, "e");
                        }
                    } catch (e) {
                        showNotyAlert(e, "e");
                        $("#carregaToken").hide();
                        $("#token2fa").hide();
                        $("#infMoeda").show();
                    }
                    
                }
            });
    }
            
    function transferirCurrency() {
        $("#infMoeda").hide();
        $("#token2fa").hide();
        $("#carregaToken").show();
        $("#carregaToken").html("<img src='<?php echo IMAGES ?>loading.gif' />");
        
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_BTC_TRANSFERIR ?>',
            method: 'post',
            dataType: 'json',
            data: {                
                enderecoBitcoin: $("#endereco").val(),
                valor: $("#valor").val(),                
                token: $("#token").val(),
                pin: $("#pin").val(),
                moeda: moeda
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#carregaToken").hide();
                        $("#token2fa").hide();
                        $("#infMoeda").show();  
                        
                        showNotyAlert(json.mensagem, "s");
                        
                    } else {
                        showNotyAlert(json.mensagem, "e");
                        $("#carregaToken").hide();
                        $("#token2fa").hide();
                        $("#infMoeda").show();
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                    $("#carregaToken").hide();
                    $("#token2fa").hide();
                    $("#infMoeda").show();
                }
                limpaSearchBtc();
            }
        });
    }
    
    
    function cancelarTransferencia(){
        $("#infMoeda").show();
        $("#token2fa").hide();     
        $("#token2faAtar").hide(); 
        $("#token2faBrl").hide();  
        $("#infReais").show();
    }
        
    function findCliente() {
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_REAIS_CLIENTES_FINDBYEMAIL ?>',
            dataType: 'json',
            method: 'post',
            data: {
                email: $("#email").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        if(json.found){
                            $("#nomeCliente").html(json.nome);
                        } else {
                            $("#nomeCliente").html("Não encontrado.");
                        }
                    } else {
                       $("#nomeCliente").html("Não encontrado.");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
            }
        });
    }
     
    function listaUltimosSaques(categoria) {
    $.ajax({
        url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_REAIS_SAQUES_ULTIMOS_SAQUES ?>',
        method: 'post',
        dataType: 'json',
        data: {
          categoria: categoria  
        },        
        success: function (json) {
            try {
                if (json.sucesso) {
                    $("#listaDepositos").html(json.html);
                    $('#tblultimosdepositos').trigger('footable_initialize');
                    $(".carregando").hide();
                } else {
                    $("#listaDepositos").html("<tr><td colspan='5'>"+json.mensagem+"</td></tr>");
                }
            } catch (e) {
                $("#listaDepositos").html("<tr><td colspan='5'>"+e+"</td></tr>");
            }
            }
        });
    }
    
    function getSaldoDisponivel(){
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_REAIS_SAQUES_SALDOS ?>',
            method: 'post',
            dataType: 'json',
            data:{
                id: moeda
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        saldoDisponivel = json.saldoDisp;

                        
                        var taxa = parseFloat(taxaMoeda);
                        var saldoSacado = parseFloat(saldoDisponivel) - taxa;

                        //$("#valorReais").val(saldoSacado.toFixed().replace(".", ","));
                        $("#valorReais").val(saldoDisponivel); 
                        //console.log($("#valorReais").val(),saldoSacado,saldoDisponivel);return;
                        var total = parseFloat(saldoDisponivel);


                        if(saldoSacado > 0){
                            $("#valor").val(saldoSacado.toFixed(8).replace(".", ",")); 
                            $("#debitadoBtc").html(total.toFixed(8) + " " + simbolo);
                        } else if (saldoSacado < 0){            
                            $("#valor").val("0.00000000"); 
                            $("#debitadoBtc").html("0.00000000 " + simbolo);                
                        }

                        calcularValorSacado();
                        
                    }
                } catch (e) {
                }
            }
        });
        
    }    
    
    function saldos() {
    $.ajax({
        url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_REAIS_SAQUES_SALDOS ?>',
        method: 'post',
        dataType: 'json',
        data:{
            id: moeda
        },
        success: function (json) {
            try {
                if (json.sucesso) {
                    if(json.cripto){
                        $("#saldoAtualBtc").html(json.html);
                        saldoDisponivel = json.saldoDisp;
                    } else {
                        $("#saldoAtual").html(json.html);
                        saldoDisponivel = json.saldoDisp;
                    }
                } else {
                     $("#saldoAtual").html("<td colspan='3' class='text-center'><img src='<?php echo IMAGES ?>loading.gif' /></td>");
                }
            } catch (e) {
                 $("#saldoAtual").html("<td colspan='3' class='text-center'><img src='<?php echo IMAGES ?>loading.gif' /></td>");
            }
            }
        });
    }
        
    function filtrarBtcAux(){
        dataCoin = "todos";
        filtrarBtc();
    }
        
    function filtrarBtc() {
    $("#listaCripto").html("<tr><td colspan='7' class='text-center'><img src='<?php echo IMAGES ?>loading.gif' /></td></tr>");
    $.ajax({
        url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_BTC_TRANSFERENCIAS_FILTRAR  ?>',
        method: 'post',
        dataType: 'json',
        data: {
            data: dataCoin,
            filtro: $("#filtroTextoBtc").val(),
            moeda: moeda                
        },
        success: function (json) {
            try {
                if (json.sucesso) {
                    $("#listaCripto").html(json.html);
                    $('#tbllistabtc').trigger('footable_initialize');
                } else {
                    $("#listaCripto").html("<tr><td colspan='7'>"+json.mensagem+"</td></tr>");
                }
            } catch (e) {
                $("#listaCripto").html("<tr><td colspan='7'>"+e+"</td></tr>");
            }

        }
        });
    }  
    
    function calcularValorSacado() {
        var tarifaTed = <?php echo number_format($tarifaTed, 2, ".", "") ?>;
        var tarifaTransf = <?php echo number_format($configuracao->taxaTransferenciaInternaReais, 2, ".", "") ?>;
        var valorMinimo = <?php echo number_format($valorMinReais, 2, ".", "") ?>;
        
        if($("#idContaBancaria").val() == 1){
            var valor = ($("#valorReais").val().length > 0 ? parseFloat(toFloat($("#valorReais").val())) : 0);
            var comissao = 0;
            var resultado = (valor - tarifaTransf);
            
        } else if($("#idContaBancaria").val() == 2){
             var valor = ($("#valorReais").val().length > 0 ? parseFloat(toFloat($("#valorReais").val())) : 0);
             var comissao = <?php echo number_format($configuracao->atarTaxaSaque, 2, ".", "") ?>;
             var resultado = (valor - tarifaAtar - (valor * comissao / 100)) ;
            
        } else {
            var valor = ($("#valorReais").val().length > 0 ? parseFloat(toFloat($("#valorReais").val())) : 0);
            var comissao = <?php echo number_format($comissao, 2, ".", "") ?>;
            var resultado = (valor - tarifaTed - (valor * comissao / 100)) ;
        }

        if (resultado < 0) {
            resultado = 0;   
             $("#btnSalvar").prop("disabled", true);
        } else {
            if(valor >= valorMinimo){
                $("#btnSalvar").prop("disabled", false);
            }
        }

        $("#valorSacado2").html("R$ " + mascaraValor(resultado.toFixed(2)));
    }   
    
    function calcularValorTotal() {

        var valor = ($("#valor").val().length > 0 ? parseFloat(toFloat($("#valor").val())) : 0.00);
        var taxa = parseFloat(taxaMoeda);
        var total = (taxa + valor);
        
        $("#debitadoBtc").html(total.toFixed(8) + " " + simbolo);
    }
 
    function listar() {            
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_REAIS_SAQUES_LISTAR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                f: $("#filtro").val(), 
                moeda: $("#filtroMoeda").val(),
                idCliente: $("#filtroIdCliente").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $(".carregando").hide();
                        $("#lista").html(json.html);
                    } else {
                        $("#lista").html("<tr ><td class='text-center' colspan='9'>"+json.mensagem+"</td></tr>");
                    }
                } catch (e) {
                    $("#lista").html("<tr ><td class='text-center' colspan='9'>"+e+"</td></tr>");
                }
            }
            });
        }
        
    function ativaUltimosSaques(categoria){
        listaUltimosSaques(categoria)
        $("#saqueMoedas").hide();                                           
        $("#saqueReais").hide(); 
        $("#ultimosSaques").show(); 
    }
        
    function showCoin(codigo, tipo) {
        moeda = codigo;
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_REAIS_SAQUES_SHOW_DADOS ?>',
            method: 'post',
            dataType: 'json',
            data: {
                codigo: codigo, 
                tipo: tipo
            },
            success: function (json) {
                try {
                    if (json.sucesso) {                            
                        if (tipo === "b") {  
                            moeda = "";
                            saldoDisponivel = "";
                            $("#debositoBoleto").hide();
                            $("#saqueMoedas").hide();
                            $("#ultimosSaques").hide(); 
                            $("#depositoBoleto").hide(); 
                            $("#saqueBrl").show(); 
                            $("#saqueReais").show();
                            $("#token2faBrl").hide(); 
                            $("#carregaTokenBrl").hide();
                            $("#infReais").show();
                            updateSaldo(true);
                            limpaSearchReal();
                            limparTransferir();                            
                        } else {                            
                            moeda = codigo; 
                            saldoDisponivel = "";
                            $("#ultimosSaques").hide();   
                            $("#saqueReais").hide();
                            $("#saqueMoedas").show(); 
                            $("#tituloMoeda").html(json.nomeMoeda);                           
                            $("#icone").attr("src", json.icone); 
                            $("#comissaoCobradaBtc").html(json.taxa + " " + json.simbolo);
                            taxaMoeda = "" + json.taxa;
                            simbolo = json.simbolo;
                            $("#useCarteira").html(json.useCarteira);
                            $("#carregaToken").hide();
                            $("#token2fa").hide();
                            $("#infMoeda").show();
                            updateSaldo(true);
                            limpaSearchBtc();
                            filtrarBtc();
                        }
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                        showNotyAlert(json.mensagem, "e");
                }
            }
        });
    }       

        
    function limpaSearchBtc(){    
        $("#valor").val("");
        $("#endereco").val("");
        $("#pin").val("");
        $("#token").val("");
        $("#debitadoBtc").html("0.00000000");
        $("#filtroTextoBtc").val("");
        $("#diaBtc").removeClass("active");
        $("#mesBtc").removeClass("active");
        $("#todosBtc").removeClass("active");
        $("#semanaBtc").addClass("active");
        $("#semanaBtc").click();
        dataCoin = "semana";
        filtrarBtc();
    }
        
    
    function limpaSearchReal(){         
        $("#semanaReal").addClass("active");
        $("#filtroIdContaBancariaEmpresa").prop('selectedIndex',0);
        $("#filtroStatus").prop('selectedIndex',0);
        $("#filtroTipoDeposito").prop('selectedIndex',0);
        $("#filtroTextoReal").val("");
        $("#filtroTextoAtar").val("");
        $("#valorReais").val("0,00").trigger("keyup");
        $("#diaReal").removeClass("active");
        $("#mesReal").removeClass("active");
        $("#todosReal").removeClass("active");
        $("#semanaReal").click();        
        dataReal = "semana";
        filtrarReais();
    }
    
    
    function filtrarReaisAux(){
        dataReal = "todos";
        filtrarReais();
    }
    
    function filtrarAtarAux(){
        dataAtar = "todos";
        filtrarAtar();
    }
    
    function boletoAux(){
       boleto = true;
       filtrarReais();       
    }
    
    function filtrarReais() {    
        $("#listaReais").html("<tr><td colspan='11' class='text-center'><img src='<?php echo IMAGES ?>loading.gif' /></td></tr>");
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_REAIS_SAQUES_FILTRAR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                data: dataReal,
                idContaBancaria: $("#filtroIdContaBancaria").val(),
                status: $("#filtroStatus").val(),
                filtro: $("#filtroTextoReal").val()
            },
            success: function (json) {                 
                try {
                    if (json.sucesso) { 
                            $("#listaReais").html(json.html);   
                            $(".saque-motivo").each(function () {
                                let motivo = $(this).attr("data-motivo");
                                let controle = $(this).attr("data-controle");
                                $(this).popover({
                                    html: true,
                                    trigger: "focus",
                                    container: "body",
                                    placement: "top",
                                    title: "<?php echo $idioma->getText("controle")?> " + controle,
                                    content: motivo
                                });
                            });
                            $('#tbllistareais').trigger('footable_initialize');
                    } else {
                        $("#listaReais").html("<tr><td colspan='11' class='text-center'>"+json.mensagem+"</td></tr>");                      
                    }
                } catch (e) {
                    $("#listaBoleto").html("<tr><td colspan='11' class='text-center'>"+e+"</td></tr>");
                }
            }
        });
    }
    
    function limparTransferir() {
       $("#idContaBancaria").val(0);
       $("#nomeCliente").html(""); 
       $("#email").val("");
       $("#emailCliente").attr("hidden", true);
       

    }
        
    function limparCampos(){
        $("#idContaBancariaEmpresa").val("");
        $("#comprovante").val("");
        $("#tipoDeposito").val("<?php echo Utils\Constantes::TED ?>");
        $("#valor").val("0,00");
        $("#valorBoleto").val("0,00");
    }
    
    function saqueTransferir(processo){
        if($("#idContaBancaria").val() == 1){
            transferir();
        } else if($("#idContaBancaria").val() == 2){
            atar();
        } else {  
            saque(processo);
        }
    }
    
    <?php if($configuracao->atarAtivo == 1 ) { ?>
    
    function atarSaldo() {        
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_ATAR_SALDO ?>',
            method: 'post',
            dataType: 'json',  
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#atarSaldo").html(json.atarSaldo);    
                    } else {
                        $("#atarSaldo").html("R$ 0,00");    
                    }
                } catch (e) {
                   
                }    
            }
        });
    }
    
    
    function atar() {
        $("#tokenAtar").val("");
        $("#pinAtar").val("");
        $("#token2faBrl").hide(); 
        $("#infReais").hide();
        $("#carregaTokenBrl").show();
        $("#carregaTokenBrl").html("<img src='<?php echo IMAGES ?>loading.gif' />");        
        
        $("#btnSalvar").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_ATAR_TOKEN ?>',
            method: 'post',
            dataType: 'json',            
            data: {       
                valorReais: $("#valorReais").val(),
                documento: $("#atarDoc").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                            $("#tokenBrl").val("");
                            $("#pinBrl").val("");                            
                            $("#carregaTokenBrl").hide();
                            $("#token2faAtar").show();                             
                            $("#documentoAtar").html(json.documentoCPF);                            
                            $("#valorSolicitadoAtar").html("R$ " + json.valorSolicitado);
                            $("#valorSaqueAtar").html("R$ " + json.valorSaque);
                            showNotyAlert(json.mensagem, "s");

                    } else {
                        $("#token2faAtar").hide(); 
                        $("#carregaTokenBrl").hide();
                        $("#infReais").show();
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    $("#token2faAtar").hide(); 
                    $("#carregaTokenBrl").hide();
                    $("#infReais").show();
                    showNotyAlert(e, "e");
                }    
                
                $("#btnSalvar").prop("disabled", false);
            }
        });
    }
    
    function saqueAtar() {
        $("#token2faAtar").hide(); 
        $("#carregaTokenBrl").show();
        $("#carregaTokenBrl").html("<img src='<?php echo IMAGES ?>loading.gif' />"); 
        
        $("#btnSalvar").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_ATAR_SALVAR ?>',
            method: 'post',
            dataType: 'json',            
            data: {       
                valorReais: $("#valorReais").val(),
                documento: $("#atarDoc").val(),
                token: $("#tokenAtar").val(),
                pin: $("#pinAtar").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#carregaTokenBrl").hide();
                        $("#infReais").show();
                        filtrarAtar();
                        showNotyAlert(json.mensagem, "s");
                        
                    } else {
                        $("#carregaTokenBrl").hide();
                        $("#infReais").show();
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    $("#token2faAtar").hide(); 
                    $("#carregaTokenBrl").hide();
                    $("#infReais").show();
                    showNotyAlert(e, "e");
                }    
                
                $("#btnSalvar").prop("disabled", false);
            }
        });
    }
    
    function filtrarAtar() {   
        $("#listaReais").html("<tr><td colspan='7' class='text-center'><img src='<?php echo IMAGES ?>loading.gif' /></td></tr>");
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_ATAR_LISTAR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                data: dataAtar,
                filtro: $("#filtroTextoAtar").val()
            },
            success: function (json) {                 
                try {
                    if (json.sucesso) { 
                            $("#listaAtar").html(json.html);   
                            $('#tbllistaAtar').trigger('footable_initialize');
                    } else {
                        
                        $("#listaAtar").html("<tr><td colspan='7' class='text-center'>"+json.mensagem+"</td></tr>");                      
                    }
                } catch (e) {                
                    $("#listaAtar").html("<tr><td colspan='7' class='text-center'>"+e+"</td></tr>");
                }
            }
        });
    }
    <?php } ?>

    function saque(processo) {
        $("#token2faBrl").hide(); 
        $("#infReais").hide();
        $("#carregaTokenBrl").show();
        $("#carregaTokenBrl").html("<img src='<?php echo IMAGES ?>loading.gif' />");        
        
        $("#btnSalvar").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_REAIS_SAQUES_SALVAR ?>',
            method: 'post',
            dataType: 'json',            
            data: {                
                idContaBancaria: $("#idContaBancaria").val(),
                valorReais: $("#valorReais").val(),
                processo: processo,
                token: $("#tokenBrl").val(),
                pin: $("#pinBrl").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        if(processo === '<?php echo $processo1 ?>'){
                            
                            $("#tokenBrl").val("");
                            $("#pinBrl").val("");                            
                            $("#carregaTokenBrl").hide();
                            $("#token2faBrl").show();                             
                            $("#nomeTitular").html(json.nomeTitular);
                            $("#documentoCPF").html(json.documentoCPF);                            
                            $("#bancoInf").html(json.bancoInf);
                            $("#agencia").html(json.agencia);
                            $("#conta").html(json.conta);
                            $("#valorSolicitado").html(json.valorSolicitado);
                            $("#valorSaque").html(json.valorSaque);
                            showNotyAlert(json.mensagem, "s");
                            
                        } else if (processo === '<?php echo $processo2 ?>') { 
                            
                            $("#tokenBrl").val("");
                            $("#pinBrl").val("");                            
                            $("#carregaTokenBrl").hide();                            
                            $("#infReais").show();      
                            $("#idContaBancaria").children("option").first().prop("selected", true);
                            $("#valorReais").val("0,00").trigger("keyup");
                            limpaSearchReal();
                            showNotyAlert(json.mensagem, "s");
                        }

                    } else {
                        $("#token2faBrl").hide(); 
                        $("#carregaTokenBrl").hide();
                        $("#infReais").show();
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    $("#token2faBrl").hide(); 
                    $("#carregaTokenBrl").hide();
                    $("#infReais").show();
                    showNotyAlert(e, "e");
                }    
                
                
                saldos();
                calcularValorSacado();
                $("#btnSalvar").prop("disabled", false);
            }
        });
    }
      
    function transferir() {
        $("#btnSalvar").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_REAIS_TRANSFERIR ?>',
            method: 'post',
            dataType: 'json',
            data: {                
                email: $("#email").val(),
                valor: $("#valorReais").val() 
            },
            success: function (json) {
                try {
                    if (json.sucesso) {                        
                        showNotyAlert("<?php echo $idioma->getText("transSucesso") ?>", "s");
                        limparTransferir();
                        $("#valorReais").val("0,00");
                        
                        limpaSearchReal();
                        showNotyAlert(json.mensagem, "s");//created André 20/08/2019 
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#btnSalvar").prop("disabled", false);
                saldos();
                calcularValorSacado();
            }
        }); 
    }
    
    </script>    
    <?php Utils\Layout::append("inspina/footer_esp", $_data) ?>
    </body>
</html>

