<?php
$contasBancarias = isset($_data["contas"]) ? $_data["contas"] : Array();
$configuracao = isset($_data["configuracao"]) ? $_data["configuracao"] : new \Models\Modules\Cadastro\Configuracao();
$valorMinReais = number_format($configuracao->valorMinSaqueReais, 2, ".", ",");
$idioma = new \Utils\PropertiesUtils("saque", IDIOMA);
$_data["idiomaMenu"] = $idioma;
$cliente = Utils\Geral::getCliente();
$comissao = isset($_data["comissao"]) ? $_data["comissao"] : 0;
$atar = isset($_data["atar"]) ? $_data["atar"] : null;

$processo1 = \Utils\Criptografia::encriptyPostId(Utils\Constantes::PROCESSO_SAQUE_1);
$processo2 = \Utils\Criptografia::encriptyPostId(Utils\Constantes::PROCESSO_SAQUE_2);

$jsonMoedas = isset($_data["moedas"]) ? $_data["moedas"] : Array();
$jsonOperacao = isset($_data["operacao"]) ? $_data["operacao"] : Array();

$tarifaTed = $configuracao->tarifaTed;

$cliente->moedaFavorita = Utils\Criptografia::decriptyPostId(isset($_data["moedaFavorita"]) ? $_data["moedaFavorita"] : null);

$moedaCategoria = "c";
$moedaSelecionado = \Utils\Criptografia::encriptyPostId(2); //Bitcoin

$moedaRn = new Models\Modules\Cadastro\MoedaRn();

if(!empty($cliente->moedaFavorita)){
    if($cliente->moedaFavorita > 1){
        $moedaCategoria = "c";
        $moedaSelecionado = \Utils\Criptografia::encriptyPostId($cliente->moedaFavorita);
        $moeda = $moedaRn->get($cliente->moedaFavorita);
    } else {
        $moedaCategoria = "b";
        $moedaSelecionado = \Utils\Criptografia::encriptyPostId(1);//Reasl
    }
}
?>
<style>
    .border-edit {
        border: 1px solid #1c84c6 !important;
    }
   .carregando {
   background: url("<?php echo IMAGES ?>loading.gif") center no-repeat;
    width: 200px;
    height: 200px;
    position: absolute;
    top: 30%;
    left: 45%;
    color: blue;
   }

   .box {
       border-radius: 10px !important;
   }

    .row {
        margin-right: 0 !important;
        margin-left: 0 !important;
    }


    * {
        font-family: "Segoe UI", Roboto, sans-serif;
    }

    .choose-position .select2-container {
        width: 100% !important;
    }

    .choose-position .select2-container--default .select2-selection--single {
        width: 100% !important;
        display: flex;
        align-items: center;
        padding: 0 30px;
        height: 50px;
        line-height: 50px;
        font-weight: 500;
        font-size: 16px;
        background-color: #fafafa;
        border: 1px solid #eeeeee;
        border-radius: 25px;
        transition: 0.1s;
    }

    .select2-dropdown {
        border: 1px solid #eeeeee !important;
    }

    .choose-position .select2-search {
        display: none;
    }

    .choose-position .select2-results__option {
        display: flex;
        align-items: center;
    }

    .choose-position .select2-results__option .img-flag {
        width: 40px;
        height: 40px;
        border-radius: 50%;
        object-fit: cover;
        margin-right: 10px;
    }

    .choose-position .select2-container--default.select2-container--focus .select2-selection--single {
        border: 1px solid #c9c9c9 !important;
        outline: 0;
    }

    .choose-position span.select2-selection.select2-selection--single {
        outline: none;
    }

    .choose-position .select2-container--default .select2-selection--single .select2-selection__arrow {
        height: 35px;
        top: 50%;
        transform: translateY(-50%);
        right: 10px;
        width: 35px;
        background-color: #fff;
        border-radius: 50%;
        display: flex;
        align-items: center;
        justify-content: center;
        box-shadow: 0 5px 20px rgba(35, 49, 45, 0.14);
    }
</style>
<?php Utils\Layout::append("inspina/metas", $_data) ?>
<?php Utils\Layout::append("inspina/scripts", $_data) ?>
<?php Utils\Layout::append("inspina/menu", $_data) ?>
<div class="carregando">
</div>
<!-- <div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-12">
        <h5><?php echo $idioma->getText("titulo") ?></h2>
    </div>
</div> -->
<body>
    <div class="">
        <div class="col-md-12 col-lg-9">
            <div class="card mostrar mtb15">
                <div class="row">
                    <div class="card-body">
                        <h5 class="card-title"><?php echo $idioma->getText("titulo") ?></h2>
                        <div class="">
                            <div class="">
                                <div class="row p-md">
                                    <div class="col-sm-12 select-box choose-position">
                                        <select class="form-control-lg select2 chosen-select input-lg full-width" id="selectCoins">
                                        </select>
                                    </div>
                                </div>
                                <div class="" id="saqueReais">
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <div class="row p-md text-center">
                                                <h2 class="m-l-sm p-md" style="display: inline;"><?php echo $idioma->getText("saqueReais") ?></h2>
                                            </div>
                                            <div id="saqueBrl p-md">
                                                <div class="row p-md">
                                                    <div class="col-sm-4">
                                                        <div class="ibox float-e-margins">
                                                            <h4><?php echo $idioma->getText("saldoTotal") ?></h4>
                                                            <div class="ibox-content">
                                                                <h3 class="" id="saldoTotalBrl">-</h3>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-sm-4">
                                                        <div class="ibox float-e-margins">
                                                            <h4><?php echo $idioma->getText("saldoDisponivel") ?></h4>
                                                            <div class="ibox-content">
                                                                <h3 class="" id="saldoBrl">-</h3>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-sm-4">
                                                        <div class="ibox float-e-margins">
                                                            <h4><?php echo $idioma->getText("saldoBloqueado") ?></h4>
                                                            <div class="ibox-content">
                                                                <h3 class="" id="saldoBloqueadoBrl">-</h3>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div id="infReais">

                                                    <div class="row p-md" id="emailCliente">
                                                        <div class="col col-lg-12 ">
                                                            <div class="form-group">
                                                                <label><?php echo $idioma->getText("email") ?></label>
                                                                <div class="input-group">
                                                                    <input type="text"  class="form-control" id="email" name="email" value="" />
                                                                    <span class="input-group-btn">
                                                                        <button type="button" class="btn btn-primary" onclick="findCliente();">&nbsp;<i class="fa fa-search"></i></button>
                                                                    </span>
                                                                </div>
                                                                <strong><span id="nomeCliente"></span></strong>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <?php if(!empty($atar) && $atar->ativo == true) {?>
                                                    <div class="row p-md" id="atar">
                                                        <div class="col-lg-12 ">
                                                            <h3>O saque através da Atar é somente para o titular da conta.</h3>
                                                            <div class="form-group">
                                                                <label>Nome:</label>
                                                                <input type="text"  class="form-control"  value="<?php echo $cliente->nome ?>" disabled="true"/>
                                                            </div>
                                                            <div class="form-group">
                                                                <label>Documento</label>
                                                                <input type="text"  class="form-control"  value="<?php echo $cliente->documento ?>" disabled="true"/>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <?php } else { ?>
                                                    <div class="row p-md" id="atar">
                                                        <div class="col col-lg-12">
                                                            <div class="form-group">
                                                                <label><?php echo "Faça o cadastro de seu Atar ID ou CPF no menu Depósito." ?></label>
                                                            </div>
                                                        </div>
                                                    </div>

                                                    <?php } ?>

                                                    <div class="row">
                                                        <div class="col-sm-12 m-b-lg">
                                                            <div class="form-group">
                                                                <label><?php echo $idioma->getText("valor") ?></label>
                                                                <div class="input-group">
                                                                    <input type="text"  class="form-control" id="valorReais" name="valorReais" value="0,00" />
                                                                    <span class="input-group-btn">
                                                                        <button type="button" class="btn btn-primary full-width" onclick="getSaldoDisponivel();"><?php echo $idioma->getText("meuSaldoTotal") ?></button>
                                                                    </span>
                                                                </div>
                                                                <label style="margin-top: 5px !important;">
                                                                    <small><?php echo $idioma->getText("comiSaque") ?> <span id="comissaoCobradaSaque"><?php echo number_format($comissao, 2, ",", "") ?></span>%</small></br>
                                                                    <small><?php echo $idioma->getText("tarifaTansfer") ?> <span id="tarifaTransferencia"></span></small></br>
                                                                    <small><?php echo $idioma->getText("seraCreditadaNaConta") ?> <strong id="valorSacado2"></strong></small></br>
                                                                </label>
                                                            </div>
                                                        </div>
                                                    </div>

                                                    <div class="row p-md">
                                                        <h3 class="m-l-md text-center" id="limiteDisponivelReal"></h3>
                                                        <div class="col-lg-12 col-xs-12 col-sm-12">

                                                            <div class="form-group">
                                                                <button class="btn btn-primary full-width" type="button" onclick="saqueTransferir('<?php echo $processo1 ?>');" id="btnSalvar" disabled>
                                                                    <?php echo $idioma->getText("confirmaSaque") ?>
                                                                </button>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div id="carregaTokenBrl" class="text-center"></div>
                                                <div class="row p-w-md" id="token2faBrl">
                                                    <div class="col-lg-12">
                                                        <label><?php echo $idioma->getText("insiraSeuToken") ?></label>
                                                        <dl class="dl-horizontal m-t-sm">
                                                            <dt class="border-bottom">Nome Titular:</dt> <dd id="nomeTitular">-</dd>
                                                            <dt class="border-bottom">Chave PIX:</dt> <dd id="documentoCPF">-</dd>
                                                            <!-- <dt class="border-bottom">Banco:</dt> <dd id="bancoInf">-</dd>
                                                            <dt class="border-bottom">Agência:</dt> <dd id="agencia">-</dd>
                                                            <dt class="border-bottom">Conta:</dt> <dd id="conta">-</dd> -->
                                                            <dt class="border-bottom">Valor Solicitado:</dt> <dd id="valorSolicitado">-</dd>
                                                            <dt class="border-bottom">Valor do Saque:</dt> <dd id="valorSaque">-</dd>
                                                        </dl>

                                                        <div class="row">
                                                            <div class="col-md-6 col-xs-12">
                                                                <div class="form-group">
                                                                    <label><?php echo $idioma->getText("pin") ?></label>
                                                                    <input type="password" inputmode="numeric" pattern="[0-9]*" class="form-control" id="pinBrl"/>
                                                                </div>
                                                            </div>
                                                            <div class="col-md-6 col-xs-12">
                                                                <div class="form-group m-b-none">
                                                                    <label><?php echo $idioma->getText("token2fa") ?></label>
                                                                    <input type="text" inputmode="numeric" pattern="[0-9]*" class="form-control" id="tokenBrl"/>
                                                                    <?php if ($cliente->tipoAutenticacao === \Utils\Constantes::TIPO_AUTH_EMAIL) { ?>
                                                                        <a href="javascript:saqueTransferir('<?php echo $processo1 ?>');" id="reenviarLink"><?php echo $idioma->getText("reenviar2fa") ?></a>
                                                                    <?php } ?>
                                                                </div>
                                                            </div>
                                                        </div>

                                                        <div class="row p-h-sm">
                                                            <div class="col-lg-12 col-xs-12 m-t-xs">
                                                                <button class="btn btn-white full-width" onclick="cancelarTransferencia();"><?php echo $idioma->getText("cancelar") ?></button>
                                                            </div>
                                                            <div class="col-lg-12 col-xs-12 m-t-xs">
                                                                <button class="btn btn-success full-width"  onclick="saqueTransferir('<?php echo $processo2 ?>');"><?php echo $idioma->getText("confirmar") ?></button>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <?php if ($configuracao->atarAtivo == 1) { ?>
                                                    <div class="row p-w-md" id="token2faAtar">
                                                        <div class="col-lg-12">
                                                            <label><?php echo $idioma->getText("insiraSeuToken") ?></label>
                                                            <dl class="dl-horizontal m-t-sm">
                                                                <dt class="border-bottom">Documento:</dt> <dd id="documentoAtar">-</dd>
                                                                <dt class="border-bottom">Valor Solicitado:</dt> <dd id="valorSolicitadoAtar">-</dd>
                                                                <dt class="border-bottom">Valor do Saque:</dt> <dd id="valorSaqueAtar">-</dd>
                                                            </dl>
                                                            <div class="row">
                                                                <div class="col-lg-12 col-xs-12">
                                                                    <div class="form-group">
                                                                        <label><?php echo $idioma->getText("pin") ?></label>
                                                                        <input type="password" inputmode="numeric" pattern="[0-9]*" class="form-control full-width" id="pinAtar"/>
                                                                    </div>
                                                                </div>
                                                                <div class="col-lg-12 col-xs-12">
                                                                    <div class="form-group m-b-none">
                                                                        <label><?php echo $idioma->getText("token2fa") ?></label>
                                                                        <input type="text" inputmode="numeric" pattern="[0-9]*" class="form-control full-width" id="tokenAtar"/>
                                                                        <?php if ($cliente->tipoAutenticacao === \Utils\Constantes::TIPO_AUTH_EMAIL) { ?>
                                                                            <a href="javascript:atar();" id="reenviarLinkAtar"><?php echo $idioma->getText("reenviar2fa") ?></a>
                                                                        <?php } ?>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                            <div class="row p-h-sm">
                                                                <div class="col-lg-12 col-xs-12 m-t-xs">
                                                                    <button class="btn btn-white full-width"  onclick="cancelarTransferencia();"><?php echo $idioma->getText("cancelar") ?></button>
                                                                </div>
                                                                <div class="col-lg-12 col-xs-12 m-t-xs">
                                                                    <button class="btn btn-success full-width"  onclick="saqueAtar();"><?php echo $idioma->getText("confirmar") ?></button>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                <?php } ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div id="saqueMoedas">
                                    <div class="row">
                                        <div class="col-sm-12 col-xs-12">
                                            <div class="row text-left">
                                                <h4 id="tituloMoeda" class="m-l-sm p-md text-center" style="display: inline;"><?php echo $idioma->getText("saqueCripto") ?></h4>
                                            </div>
                                            <div class="row">
                                                <div class="col-sm-4">
                                                    <div class="card">
                                                        <div class="card-body">
                                                            <h5 class="card-title"><?php echo $idioma->getText("saldoTotal") ?></h5>
                                                            <h3 class="" id="saldoTotalCripto">-</h3>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-sm-4">
                                                    <div class="card">
                                                        <div class="card-body">
                                                            <h5 class="card-title"><?php echo $idioma->getText("saldoDisponivel") ?></h5>
                                                            <h3 class="" id="saldoCripto">-</h3>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-sm-4">
                                                    <div class="card">
                                                        <div class="card-body">
                                                            <h5 class="card-title"><?php echo $idioma->getText("saldoBloqueado") ?></h5>
                                                            <h3 class="" id="saldoBloqueadoCripto">-</h3>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            
                                            <br>
                                            <div class="row">
                                                <div id="infMoeda">
                                                    <div class="row">
                                                        <div class="col-sm-12 m-b-lg">
                                                            <div class="form-group">
                                                                <label><?php echo $idioma->getText("carteiraDestino") ?></label>
                                                                <input type="text" class="form-control" id="endereco"/>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="row" id="redeMoeda">
                                                        <div class="">
                                                            <label>Escolha a rede de saque: </label>
                                                        </div>
                                                        <div class="">
                                                            <div data-toggle="buttons" class="btn-group" id="optionsRede">
                                                                <label class="btn btn-white" id="erc20"> <input type="radio" name="optionRede" value="<?php echo \Utils\Constantes::REDE_ERC20 ?>">ERC20</label>
                                                                <label class="btn btn-white" id="bep20"> <input type="radio" name="optionRede" value="<?php echo \Utils\Constantes::REDE_BEP20 ?>">BEP20</label>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="row">
                                                        <div class="col-sm-12 m-b-lg">
                                                            <div class="form-group">
                                                                <label><?php echo $idioma->getText("volume") ?></label>
                                                                <div class="input-group">
                                                                    <input type="text"  class="form-control" inputmode="numeric" pattern="[0-9]*" id="valor" name="valor" value="0.00000000" />
                                                                    <span class="input-group-btn">
                                                                        <button type="button" class="btn btn-primary" onclick="getSaldoDisponivel();"><?php echo $idioma->getText("meuSaldoTotal") ?></button>
                                                                    </span>
                                                                </div>
                                                                <div>
                                                                <label style="margin-top: 5px !important;">
                                                                <span><?php echo $idioma->getText("taxa") ?>:</span> <span id="comissaoCobradaBtc"></span></br>
                                                                <strong><span><?php echo $idioma->getText("seraDebitado") ?>:</span> <span id="debitadoBtc"></span></strong></br>
                                                                </label>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <h3 class="m-l-md text-center" id="limiteDisponivelCripto"></h3>
                                            <div class="col-lg-12 col-xs-12 col-sm-12">
                                                <button class="btn btn-primary full-width" id="btnTransferir" onclick="confirmarTransferencia();" disabled><?php echo $idioma->getText("transferir") ?></button>
                                            </div>
                                        </div>
                                    </div>
                                    <div id="carregaToken" class="text-center"></div>
                                    <div class="row  p-md" id="token2fa">
                                        <div class="col-lg-12">
                                            <label><?php echo $idioma->getText("insiraSeuToken") ?></label>
                                            <dl class="dl-horizontal m-t-sm">
                                                <dt class="border-bottom"><?php echo $idioma->getText("volume") ?>: </dt> <dd id="volumeConfirmar">-</dd>
                                                <dt class="border-bottom"><?php echo $idioma->getText("carteira") ?>:</dt> <dd id="enderecoConfirmar">-</dd>
                                                <dt class="border-bottom" id="redeConfirmar"><?php echo "Rede" ?>:</dt> <dd id="rede">-</dd>
                                            </dl>

                                            <div class="row">
                                                <div class="col-lg-6 col-xs-12">
                                                    <div class="form-group">
                                                        <label><?php echo $idioma->getText("pin") ?></label>
                                                        <input type="password" inputmode="numeric" pattern="[0-9]*" class="form-control full-width" id="pin"/>
                                                    </div>
                                                </div>
                                                <div class="col-lg-6 col-xs-12">
                                                    <div class="form-group m-b-none">
                                                        <label><?php echo $idioma->getText("token2fa") ?></label>
                                                        <input type="text" inputmode="numeric" pattern="[0-9]*" class="form-control full-width" id="token"/>
                                                        <?php if ($cliente->tipoAutenticacao === \Utils\Constantes::TIPO_AUTH_EMAIL) { ?>
                                                            <a href="javascript:confirmarTransferencia();" id="reenviarLink"><?php echo $idioma->getText("reenviar2fa") ?></a>
                                                        <?php } ?>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="row p-h-sm">
                                                <div class="col-lg-12 col-xs-12 m-t-xs">
                                                    <button class="btn btn-white full-width"  onclick="cancelarTransferencia();"><?php echo $idioma->getText("cancelar") ?></button>
                                                </div>
                                                <div class="col-lg-12 col-xs-12 m-t-xs">
                                                    <button class="btn btn-success full-width" onclick="transferirCurrency();"><?php echo $idioma->getText("confirmar") ?></button>
                                                </div>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="card mtb15">
                <div class="row">
                    <div class="card-body">

                                                            ///aquiii
                        <div id="tabelaReais">
                                <div class="">
                                    <div class="col-sm-3 ">
                                        <div class=" p-xs">
                                            <select class="form-control input-sm" id="filtroStatus">
                                                <option value="T"><?php echo $idioma->getText("todos") ?></option>
                                                <option value="<?php echo Utils\Constantes::STATUS_DEPOSITO_PENDENTE ?>"><?php echo $idioma->getText("pendente") ?></option>
                                                <option value="<?php echo Utils\Constantes::STATUS_DEPOSITO_CONFIRMADO ?>"><?php echo $idioma->getText("confirmado") ?></option>
                                                <option value="<?php echo Utils\Constantes::STATUS_DEPOSITO_CANCELADO ?>"><?php echo $idioma->getText("cancelado") ?></option>
                                            </select>
                                        </div>

                                    </div>
                                    <div class="col-sm-5 ">
                                        <div data-toggle="buttons" class="btn-group p-xs" id="radioDatas">
                                            <!-- <label class="btn btn-sm btn-white" id="diaReal"> <input type="radio"  name="options" value="dia"><?php echo $idioma->getText("dia") ?></label>
                                            <label class="btn btn-sm btn-white active" id="semanaReal"> <input type="radio"  name="options" value="semana"><?php echo $idioma->getText("semana") ?></label>
                                            <label class="btn btn-sm btn-white" id="mesReal"> <input type="radio"  name="options" value="mes"><?php echo $idioma->getText("mes") ?></label>
                                            <label class="btn btn-sm btn-white" id="todosReal"> <input type="radio"  name="options" value="todos"><?php echo $idioma->getText("todos") ?></label> -->
                                            <button type="button" class="btn-white" onclick="filterBtnReal('dia');" id="diaReal"><?php echo $idioma->getText("dia") ?></button>
                                            <button type="button" class="btn-white" onclick="filterBtnReal('semana');" id="semanaReal"><?php echo $idioma->getText("semana") ?></button>
                                            <button type="button" class="btn-white" onclick="filterBtnReal('mes');" id="mesReal"><?php echo $idioma->getText("mes") ?></button>
                                            <button type="button" class="btn-white" onclick="filterBtnReal('todos');" id="todosReal"><?php echo $idioma->getText("todos") ?></button>
                                        </div>
                                    </div>
                                    <div class="col-sm-4 ">
                                        <div class="input-group p-xs">
                                            <input type="text" id="filtroTextoReal" placeholder="<?php echo $idioma->getText("pesquisar") ?>" class="input-sm form-control"><span class="input-group-btn">
                                                        <button type="button" class="btn btn-sm btn-primary" onclick="filtrarReaisAux();">&nbsp;<i class="fa fa-search"></i></button>
                                                        <button type="button" class="btn btn-sm btn-default" onclick="limpaSearchReal();">&nbsp;<i class="fa fa-eraser"></i></button></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class="table-responsive m-t-sm">
                                            <table id="tbllistareais" class="table table-striped text-center" data-paging="true" data-limit-navigation="3" data-paging-size="3" data-paging-limit="10" style="font-size: 12px;">
                                                <thead>
                                                <tr>
                                                    <th class="text-center">
                                                        <?php echo $idioma->getText("data") ?>
                                                    </th>
                                                    <!-- <th class="text-center">
                                                        <?php  //echo $idioma->getText("conta") ?>
                                                    </th> -->
                                                    <th class="text-center">
                                                        <?php echo $idioma->getText("valor") ?>
                                                    </th>
                                                    <th class="text-center">
                                                        <?php echo $idioma->getText("comissaoP") ?>
                                                    </th>
                                                    <th class="text-center">
                                                        <?php echo $idioma->getText("taxaTed") ?>
                                                    </th>
                                                    <th class="text-center">
                                                        <?php echo $idioma->getText("creditado") ?>
                                                    </th>
                                                    <!-- <th class="text-center">
                                                        <?php //echo $idioma->getText("comp") ?>
                                                    </th> -->
                                                    <th class="text-center">
                                                        <?php echo $idioma->getText("status") ?>
                                                    </th>
                                                </tr>
                                                </thead>
                                                <tbody id="listaReais">

                                                </tbody>
                                                <tfoot>
                                                <tr>
                                                <tr>
                                                    <td colspan="12">
                                                        <ul class="pagination pull-right"></ul>
                                                    </td>
                                                </tr>
                                                </tr>
                                                </tfoot>
                                            </table>
                                        </div>
                                    </div>
                                </div>

                        </div>



                        <div id="tabelaMoeda">
                                <div class="row">
                                    <div class="col-sm-6 pull-left">
                                        <div data-toggle="buttons" class="btn-group p-xs" id="radioDatasBtc">
                                            <!-- <label class="btn btn-sm btn-white" id="diaBtc"> <input type="radio" id="" name="optionsBtc" value="dia"><?php echo $idioma->getText("dia") ?></label>
                                            <label class="btn btn-sm btn-white active" id="semanaBtc"> <input type="radio" id="" name="optionsBtc" value="semana"><?php echo $idioma->getText("semana") ?></label>
                                            <label class="btn btn-sm btn-white" id="mesBtc"> <input type="radio" id="" name="optionsBtc" value="mes"><?php echo $idioma->getText("mes") ?></label>
                                            <label class="btn btn-sm btn-white" id="todosBtc"> <input type="radio" id="" name="optionsBtc" value="todos"><?php echo $idioma->getText("todos") ?></label>
                                            -->
                                            <button type="button" class="btn-white" onclick="filterBtn('dia');" id="diaBtc"><?php echo $idioma->getText("dia") ?></button>
                                            <button type="button" class="btn-white" onclick="filterBtn('semana');" id="semanaBtc"><?php echo $idioma->getText("semana") ?></button>
                                            <button type="button" class="btn-white" onclick="filterBtn('mes');" id="mesBtc"><?php echo $idioma->getText("mes") ?></button>
                                            <button type="button" class="btn-white" onclick="filterBtn('todos');" id="todosBtc"><?php echo $idioma->getText("todos") ?></button>
                                        </div>
                                    </div>

                                    <div class="col-sm-6 pull-left">
                                        <div class="input-group p-xs">
                                            <input type="text" id="filtroTextoBtc" placeholder="<?php echo $idioma->getText("pesquisar") ?>" class="input-sm form-control"><span class="input-group-btn">
                                            <div class="input-group-prepend">
                                                <button type="button" class="btn btn-sm btn-primary" onclick="filtrarBtcAux();">&nbsp;<i class="fa fa-search"></i></button>
                                                <button type="button" class="btn btn-sm btn-default" onclick="limpaSearchBtc();">&nbsp;<i class="fa fa-eraser"></i></button></span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="table-responsive ">
                                    <table id="tbllistabtc" class="table table-striped text-center" data-paging="true" data-limit-navigation="3" data-paging-size="3" data-paging-limit="10" style="font-size: 12px;">
                                        <thead>
                                        <tr>
                                            <th class="text-center"><?php echo $idioma->getText("data") ?></th>
                                            <th class="text-center"><?php echo $idioma->getText("volume") ?></th>
                                            <th class="text-center"><?php echo $idioma->getText("taxa") ?></th>
                                            <th class="text-center"><?php echo $idioma->getText("carteira") ?></th>
                                            <th class="text-center"><?php echo $idioma->getText("hash") ?></th>
                                            <th class="text-center"><?php echo $idioma->getText("status") ?></th>
                                        </tr>
                                        </thead>
                                        <tbody id="listaCripto">
                                        </tbody>
                                        <tfoot>
                                        <tr>
                                            <td colspan="5">
                                                <ul class="pagination pull-right"></ul>
                                            </td>
                                        </tr>
                                        </tfoot>
                                    </table>
                                </div>

                        </div>


                        <div id="tabelaAtar">
                                <div class="row">
                                    <div class="col-sm-5">
                                        <div data-toggle="buttons" class="btn-group p-xs" id="radioDatasAtar" >
                                            <label class="btn btn-sm btn-white" id="diaAtar"> <input type="radio"  name="optionsAtar" value="dia"><?php echo $idioma->getText("dia") ?></label>
                                            <label class="btn btn-sm btn-white active" id="semanaAtar"> <input type="radio"  name="optionsAtar" value="semana"><?php echo $idioma->getText("semana") ?></label>
                                            <label class="btn btn-sm btn-white" id="mesAtar"> <input type="radio"  name="optionsAtar" value="mes"><?php echo $idioma->getText("mes") ?></label>
                                            <label class="btn btn-sm btn-white" id="todosAtar"> <input type="radio"  name="optionsAtar" value="todos"><?php echo $idioma->getText("todos") ?></label>
                                        </div>
                                    </div>
                                    <div class="col-sm-offset-2 col-sm-5">
                                        <div class="input-group p-xs">
                                            <input type="text" id="filtroTextoAtar" placeholder="<?php echo $idioma->getText("pesquisar") ?>" class="input-sm form-control"><span class="input-group-btn">
                                                        <button type="button" class="btn btn-sm btn-primary" onclick="filtrarAtarAux();">&nbsp;<i class="fa fa-search"></i></button>
                                                        <button type="button" class="btn btn-sm btn-default" onclick="filtrarAtar();">&nbsp;<i class="fa fa-eraser"></i></button></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="table-responsive ">
                                    <table id="tbllistaAtar" class="table table-striped text-center" data-paging="true" data-limit-navigation="3" data-paging-size="3" data-paging-limit="10" style="font-size: 12px;">
                                        <thead>
                                        <tr>
                                            <th class="text-center">
                                                <?php echo $idioma->getText("data") ?>
                                            </th>
                                            <th class="text-center">
                                                <?php echo $idioma->getText("valor") ?>
                                            </th>
                                            <th class="text-center">
                                                <?php echo $idioma->getText("comissaoP") ?>
                                            </th>
                                            <th class="text-center">
                                                <?php echo $idioma->getText("taxaTed") ?>
                                            </th>
                                            <th class="text-center">
                                                <?php echo $idioma->getText("creditado") ?>
                                            </th>
                                            <th class="text-center">
                                                <?php echo "Destino" ?>
                                            </th>
                                            <th class="text-center">
                                                <?php echo $idioma->getText("status") ?>
                                            </th>
                                        </tr>
                                        </thead>
                                        <tbody id="listaAtar">

                                        </tbody>
                                        <tfoot>
                                        <tr>
                                            <td colspan="7">
                                                <ul class="pagination pull-right"></ul>
                                            </td>
                                        </tr>
                                        </tfoot>
                                    </table>
                                </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-12 col-lg-3">
            <div class="card mtb15">
                <div class="card-body">
                    <div class="row m-t-md m-l-sm" id="infGerais">
                        <div class="col-sm-12 m-b-lg">
                            <div class="">
                                <div class="list-indicados">
                                    <div class="">
                                        <div class="col-sm-12">
                                            <div id="avisoFiat">
                                            </div>
                                            <div id="avisoCurrency">
                                                <div id="vertical-timeline" class="vertical-container light-timeline no-margins">
                                                    <div class="vertical-timeline-block">
                                                        <div class="vertical-timeline-icon yellow-bg">
                                                            <i class="fa fa-exclamation-triangle fa-1x"></i>
                                                        </div>
                                                        <div class="vertical-timeline-content">
                                                            <strong class="text-left"><h5><?php echo $idioma->getText("atencao") ?></h5></strong>
                                                            <small>
                                                                <ul>
                                                                    <li class="m-t-xs"><?php echo $idioma->getText("irreversiveis") ?></li>
                                                                    <li class="m-t-xs" id="aceitaRede"></li>
                                                                </ul>
                                                            </small>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>

                                            <div id="infFiat">
                                                <div id="vertical-timeline" class="vertical-container light-timeline no-margins">
                                                    <?php if ($configuracao->atarAtivo == 1) { ?>
                                                        <div class="vertical-timeline-block">
                                                            <div class="vertical-timeline-icon blue-bg">
                                                                <i class="fa fa-info fa-1x"></i>
                                                            </div>
                                                            <div class="vertical-timeline-content">
                                                                <strong class="text-left"><h5><?php echo "ATAR PAY" ?> </h5></strong><!--informacoes-->
                                                                <small><ul>
                                                                        <li class="m-t-xs"><?php echo "Saques via Atar Pay são instantâneos e 24/7." ?></li>
                                                                        <li class="m-t-xs"><?php echo "Baixe o app Atar Pay e crie sua conta grátis em apenas 2 minutos." ?></li>
                                                                        <li class="m-t-xs"><a href="https://apps.apple.com/br/app/atar-pay/id1144625341" target="atar_pay"><?php echo "Link iOS" ?></a></li>
                                                                        <li class="m-t-xs"><a href="https://play.google.com/store/apps/details?id=com.wearatar.atarpay&hl=en" target="atar_pay"><?php echo "Link Android" ?></a></li>
                                                                        <li class="m-t-xs">Valor disponível para saque: <span id="atarSaldo">R$ 0,00</span></li>
                                                                    </ul></small>
                                                            </div>
                                                        </div>
                                                    <?php } ?>
                                                    <div class="vertical-timeline-block">
                                                        <div class="vertical-timeline-icon blue-bg">
                                                            <i class="fa fa-info fa-1x"></i>
                                                        </div>
                                                        <div class="vertical-timeline-content">
                                                            <strong class="text-left"><h5><?php echo $idioma->getText("informacoes") ?> </h5></strong>
                                                            <small><ul>
                                                                    <li class="m-t-xs" id="limiteInformacaoReal"></li>
                                                                    <li class="m-t-xs"><?php echo $idioma->getText("saque5"); ?></li>
                                                                    <li class="m-t-xs"><?php echo $idioma->getText("saque6"); ?></li>
                                                                    <li class="m-t-xs"><?php echo str_replace("{var}", $valorMinReais, $idioma->getText("saque1")) ?></li>
                                                                    <li class="m-t-xs"><?php echo $idioma->getText("saque2") ?></li>
                                                                    <li class="m-t-xs"><?php echo $idioma->getText("saque3") ?></li>
                                                                    <li class="m-t-xs"><?php echo $idioma->getText("paraBrasileiro") ?></li>
                                                                </ul></small>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div id="infCurrency">
                                                <div id="vertical-timeline" class="vertical-container light-timeline no-margins">
                                                    <div class="vertical-timeline-block">
                                                        <div class="vertical-timeline-icon blue-bg">
                                                            <i class="fa fa-info fa-1x"></i>
                                                        </div>
                                                        <div class="vertical-timeline-content">
                                                            <strong class="text-left"><h5><?php echo $idioma->getText("informacoes") ?></h5></strong>
                                                            <small><ul>
                                                                    <li class="m-t-xs" id="limiteInformacaoCripto"></li>
                                                                    <li class="m-t-xs" id="useCarteira"></li>
                                                                    <li class="m-t-xs" id="taxasMoeda"></li>
                                                                </ul></small>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

    <?php Utils\Layout::append("inspina/footer_esp", $_data) ?>
<script>
    var comissao = <?php echo number_format($comissao, 2, ".", "")?>;
    var dataReal = "";
    var dataAtar = "";
    var dataCoin = "";
    var rede = "";
    var moeda = "";
    var banco = "";
    var boleto = false;
    var taxaMoeda = 0.00000000;
    var saldoDisponivel = "";
    var interval = null;
    var simbolo = "";
    var simboloTaxa = "";
    var codeContaBancaria = null;
    var tarifaAtar = 0;

    $(document).ready(function () {



    $("#selectCoins").select2({
        data: <?php echo $jsonMoedas ?>,
        templateSelection: formatState,
        templateResult: formatState,
        closeOnSelect: true
    });

    $("#selectCoins").on('select2:select', function (e) {
        var data = e.params.data;
        moeda = data.id;
        rede = "";
        $("#btnTransferir").prop("disabled", true);

        if(data.tag == "real"){
            showCoin(data.op, data.tipo);
            calcularValorSacado();
            codeContaBancaria = data.id;
            contaBancaria(data.id);
        } else {
            showCoin(data.id, data.tipo, data.rede);
        }
    });

    function formatState (state) {
        if (!state.id) {
            return state.text;
        }
        var $state = $(
            '<span><img src="' + state.icone + '" height="25" width="25" />&nbsp;&nbsp;<span></span></span>'
        );

        $state.find("span").text(state.text);
        $state.find("img").attr("src", state.icone);


        return $state;
    }


    if (('<?php echo $moedaSelecionado ?>' != '') && ('<?php echo $moedaCategoria ?>' != '')){

        showCoin('<?php echo $moedaSelecionado ?>', '<?php echo $moedaCategoria ?>');

        if('<?php echo $moedaCategoria ?>' == 'b'){
            calcularValorSacado();
            contaBancaria();
        }
        }

        $("#btnSalvar").prop("disabled", true);
        new Clipboard("#barCode");

        $('#tblultimosdepositos').footable();
        $('#tbllistabtc').footable();
        $('#tbllistareais').footable();
        $('#tblListaBoleto').footable();
        $('#tbllistaAtar').footable();

        $("#filtroStatus").change(function () {
        filtrarReais();
        });

        $("#filtroStatusBtc").change(function () {
        filtrarBtc();
        });

        $("#filtroIdContaBancaria").change(function () {
        filtrarReais();
        });

        $("#radioDatas input").on('change', function(){
            dataReal = $('input[name="options"]:checked', '#radioDatas').val();
            filtrarReais();
    });
        $("#radioDatasBtc input").on('change', function(){
            dataCoin = $('input[name="optionsBtc"]:checked', '#radioDatasBtc').val();
            filtrarBtc();
    });
    
    $("#optionsRede input").on('change', function(){
            rede = $('input[name="optionRede"]:checked', '#optionsRede').val();

            $("#redeConfirmar").show();
            switch(rede){
            case '<?php echo \Utils\Constantes::REDE_ERC20; ?>':
                $("#rede").html('<?php echo \Utils\Constantes::REDE_ERC20; ?>');
                break;
            case '<?php echo \Utils\Constantes::REDE_BEP20; ?>':
                $("#rede").html('<?php echo \Utils\Constantes::REDE_BEP20; ?>');
                break;
            }

            taxas();
    });


    <?php if($configuracao->atarAtivo == 1){ ?>

        atarSaldo();
        setInterval(atarSaldo, 10000);

        $("#radioDatasAtar input").on('change', function(){
            dataAtar = $('input[name="optionsAtar"]:checked', '#radioDatasAtar').val();
            filtrarAtar();
        });
    <?php }?>

        new Clipboard("#btn-link-ref");

        $("#saqueReais").hide();
        $("#saqueMoedas").hide();
        $("#moeda, #filtroMoeda").select2();
        $(".mostrar").show();

    $("#valorReais").keydown(function (event) {
            $(this).val(currency($(this).val(), 2, 8, event.keyCode));
            event.preventDefault();
            calcularValorSacado();
        });

        $("#valor").keydown(function (event) {
            $(this).val(currency($(this).val(), 8, 8, event.keyCode));
            event.preventDefault();
            calcularValorTotal();
        });
    });


    function contaBancaria(code) {

        switch (code) {
            case 1:
            limparTransferir();
            $("#valorReais").html('0,00');
            $("#comissaoCobradaSaque").html('0,00');
            $("#tarifaTransferencia").html('R$ <?php echo number_format($configuracao->taxaTransferenciaInternaReais, 2, ",", ".") ?>');
            $("#atar").attr("hidden", true);
            $("#emailCliente").attr("hidden", false);
            tabelas("reais");
            filtrarReais();
                break;

            case 2:
            $("#valorReais").html('0,00');
            $("#atarDoc").val('');
            $("#comissaoCobradaSaque").html('<?php echo number_format($configuracao->atarTaxaSaque, 2, ",", ".") ?>');
            $("#tarifaTransferencia").html('R$ <?php echo number_format($configuracao->atarTarifaSaque, 2, ",", ".") ?>');
            tarifaAtar = <?php echo number_format($configuracao->atarTarifaSaque, 2, ".", "") ?>;
            $("#emailCliente").attr("hidden", true);
            $("#atar").attr("hidden", false);
            tabelas("atar");
            filtrarAtar();
                break;

            default:
            $("#valorReais").html('0,00');
            $("#comissaoCobradaSaque").html('<?php echo number_format($comissao, 2, ",", ".") ?>');
            $("#tarifaTransferencia").html('R$ <?php echo number_format($tarifaTed, 2, ",", ".") ?>');
            $("#emailCliente").attr("hidden", true);
            $("#tabelaAtar").attr("hidden", true);
            $("#atar").attr("hidden", true);
            $("#tabelaReais").attr("hidden", false);
            tabelas("reais");
            filtrarReais();
                break;
        }
    }

    function filterBtn(data) {
        console.log(data);
        dataCoin = data;
        filtrarBtc();
    }

    function filterBtnReal(data) {
        console.log(data);
        dataCoin = data;
        filtrarReais();
    }

    function updateSaldo(ativa){
        if(ativa){
            saldos();
            interval = setInterval(saldos,10000);
        }else{
            clearInterval(interval);
        }

    }

    function tabelas(tabela){
        $("#tabelaReais").hide();
        $("#tabelaMoeda").hide();
        $("#tabelaAtar").hide();

        $("#infCurrency").hide();
        $("#infFiat").hide();
        $("#avisoFiat").hide();
        $("#avisoCurrency").hide();

        switch (tabela) {
            case "reais":
                $("#tabelaReais").show();
                $("#avisoFiat").show();
                $("#infFiat").show();
                break;
            case "atar":
                $("#tabelaAtar").show();
                $("#avisoFiat").show();
                $("#infFiat").show();
                break;
            case "moeda":
                $("#tabelaMoeda").show();
                $("#infCurrency").show();
                $("#avisoCurrency").show();
                break;
            default:
                $("#tabelaReais").show();
                $("#avisoFiat").show();
                $("#infFiat").show();
                break;
        }
    }

    function confirmarTransferencia(){
        $("#infMoeda").hide();
        $("#token2fa").hide();
        $("#carregaToken").show();
        $("#carregaToken").html("<img src='<?php echo IMAGES ?>loading.gif' />");

        $.ajax({
                url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_BTC_AUTORIZACAO_TOKEN  ?>',
                method: 'post',
                dataType: 'json',
                data: {
                    enderecoBitcoin:  $("#endereco").val(),
                    valor: $("#valor").val(),
                    moeda: moeda,
                    rede: rede
                },
                success: function (json) {
                    try {
                        if (json.sucesso) {
                            $("#enderecoConfirmar").html($("#endereco").val());
                            $("#volumeConfirmar").html($("#debitadoBtc").html());
                            $("#carregaToken").hide();
                            $("#infMoeda").hide();
                            $("#token2fa").show();
                            showNotyAlert(json.mensagem, "s");
                        } else {
                            $("#carregaToken").hide();
                            $("#token2fa").hide();
                            $("#infMoeda").show();
                            showNotyAlert(json.mensagem, "e");
                        }
                    } catch (e) {
                        showNotyAlert(e, "e");
                        $("#carregaToken").hide();
                        $("#token2fa").hide();
                        $("#infMoeda").show();
                    }

                }
            });
    }

    function transferirCurrency() {
        $("#infMoeda").hide();
        $("#token2fa").hide();
        $("#carregaToken").show();
        $("#carregaToken").html("<img src='<?php echo IMAGES ?>loading.gif' />");

        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_BTC_TRANSFERIR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                enderecoBitcoin: $("#endereco").val(),
                valor: $("#valor").val(),
                token: $("#token").val(),
                pin: $("#pin").val(),
                rede: rede,
                moeda: moeda
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#carregaToken").hide();
                        $("#token2fa").hide();
                        $("#infMoeda").show();

                        showNotyAlert(json.mensagem, "s");

                    } else {
                        showNotyAlert(json.mensagem, "e");
                        $("#carregaToken").hide();
                        $("#token2fa").hide();
                        $("#infMoeda").show();
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                    $("#carregaToken").hide();
                    $("#token2fa").hide();
                    $("#infMoeda").show();
                }
                limpaSearchBtc();
            }
        });
    }

    function cancelarTransferencia(){
        $("#infMoeda").show();
        $("#token2fa").hide();
        $("#token2faAtar").hide();
        $("#token2faBrl").hide();
        $("#infReais").show();
    }

    function findCliente() {
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_REAIS_CLIENTES_FINDBYEMAIL ?>',
            dataType: 'json',
            method: 'post',
            data: {
                email: $("#email").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        if(json.found){
                            $("#nomeCliente").html(json.nome);
                        } else {
                            $("#nomeCliente").html("Não encontrado.");
                        }
                    } else {
                    $("#nomeCliente").html("Não encontrado.");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
            }
        });
    }

    function getSaldoDisponivel(){
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_REAIS_SAQUES_SALDOS ?>',
            method: 'post',
            dataType: 'json',
            data:{
                id: moeda
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        saldoDisponivel = json.saldoDisp;


                        var taxa = parseFloat(taxaMoeda);
                        var saldoSacado = parseFloat(saldoDisponivel) - taxa;

                        $("#valorReais").val(saldoDisponivel);
                        var total = parseFloat(saldoDisponivel);


                        if(saldoSacado > 0){
                            $("#valor").val(saldoSacado.toFixed(8).replace(".", ","));
                            $("#debitadoBtc").html(total.toFixed(8) + " " + simbolo);
                            $("#btnTransferir").prop("disabled", false);
                        } else if (saldoSacado < 0){
                            $("#valor").val("0.00000000");
                            $("#debitadoBtc").html("0.00000000 " + simbolo);
                        }

                        calcularValorSacado();

                    }
                } catch (e) {
                }
            }
        });

    }

    function saldos() {
    $.ajax({
        url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_REAIS_SAQUES_SALDOS ?>',
        method: 'post',
        dataType: 'json',
        data:{
            id: moeda
        },
        success: function (json) {
            try {
                if (json.sucesso) {
                    if(json.cripto){
                        $("#saldoTotalCripto").html(json.saldoTotal);
                        $("#saldoCripto").html(json.saldo);
                        $("#saldoBloqueadoCripto").html(json.saldoBloqueado);
                        saldoDisponivel = json.saldoDisp;
                        
                        if(saldoDisponivel > 0){
                            $("#btnTransferir").prop("disabled", false);
                        }
                    } else {
                        $("#saldoTotalBrl").html(json.saldoTotal);
                        $("#saldoBrl").html(json.saldo);
                        $("#saldoBloqueadoBrl").html(json.saldoBloqueado);
                        saldoDisponivel = json.saldoDisp;
                    }
                } else {
                    showNotyAlert(json.mensagem, "e");
                }
            } catch (e) {
                showNotyAlert(json.mensagem, "e");
            }
            }
        });
    }

    function filtrarBtcAux(){
        dataCoin = "todos";
        filtrarBtc();
    }

    function filtrarBtc() {
        $("#listaCripto").html("<tr><td colspan='6' class='text-center'><img src='<?php echo IMAGES ?>loading.gif' /></td></tr>");
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_BTC_TRANSFERENCIAS_FILTRAR  ?>',
            method: 'post',
            dataType: 'json',
            data: {
                data: dataCoin,
                filtro: $("#filtroTextoBtc").val(),
                moeda: moeda
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#listaCripto").html(json.html);
                        $('#tbllistabtc').trigger('footable_initialize');
                    } else {
                        $("#listaCripto").html("<tr><td colspan='6'>"+json.mensagem+"</td></tr>");
                    }
                } catch (e) {
                    $("#listaCripto").html("<tr><td colspan='6'>"+e+"</td></tr>");
                }

            }
        });
    }

    function calcularValorSacado() {
        var tarifaTed = <?php echo number_format($tarifaTed, 2, ".", "") ?>;
        var tarifaTransf = <?php echo number_format($configuracao->taxaTransferenciaInternaReais, 2, ".", "") ?>;
        var valorMinimo = <?php echo number_format($valorMinReais, 2, ".", "") ?>;

        if(codeContaBancaria == 1){
            var valor = ($("#valorReais").val().length > 0 ? parseFloat(toFloat($("#valorReais").val())) : 0);
            var comissao = 0;
            var resultado = (valor - tarifaTransf);

        } else if(codeContaBancaria == 2){
            var valor = ($("#valorReais").val().length > 0 ? parseFloat(toFloat($("#valorReais").val())) : 0);
            var comissao = <?php echo number_format($configuracao->atarTaxaSaque, 2, ".", "") ?>;
            var resultado = (valor - tarifaAtar - (valor * comissao / 100)) ;

        } else {
            var valor = ($("#valorReais").val().length > 0 ? parseFloat(toFloat($("#valorReais").val())) : 0);
            var comissao = <?php echo number_format($comissao, 2, ".", "") ?>;
            var resultado = (valor - tarifaTed - (valor * comissao / 100)) ;
        }

        if (resultado < 0) {
            resultado = 0;
            $("#btnSalvar").prop("disabled", true);
        } else {
            if(valor >= valorMinimo){
                $("#btnSalvar").prop("disabled", false);
            }
        }

        $("#valorSacado2").html("R$ " + mascaraValor(resultado.toFixed(2)));
    }

    function calcularValorTotal() {
        if(simboloTaxa !== null){
            var valor = ($("#valor").val().length > 0 ? parseFloat(toFloat($("#valor").val())) : 0.00);
            $("#debitadoBtc").html(valor.toFixed(8) + " " + simbolo);

        } else {
            var valor = ($("#valor").val().length > 0 ? parseFloat(toFloat($("#valor").val())) : 0.00);
            var taxa = parseFloat(taxaMoeda);
            var total = (taxa + valor);

            $("#debitadoBtc").html(total.toFixed(8) + " " + simbolo);
        }
    }


    function ativaUltimosSaques(categoria){
        $("#saqueMoedas").hide();
        $("#saqueReais").hide();
        $("#ultimosSaques").show();
    }

    function showCoin(codigo, tipo, rede) {

        moeda = codigo;
        $("#infGerais").hide();

        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_REAIS_SAQUES_SHOW_DADOS ?>',
            method: 'post',
            dataType: 'json',
            data: {
                codigo: codigo,
                tipo: tipo
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $(".carregando").hide();
                        if (tipo === "b") {
                            moeda = "";
                            saldoDisponivel = "";
                            $("#debositoBoleto").hide();
                            $("#saqueMoedas").hide();
                            $("#ultimosSaques").hide();
                            $("#depositoBoleto").hide();
                            $("#saqueBrl").show();
                            $("#saqueReais").show();
                            $("#token2faBrl").hide();
                            $("#token2faAtar").hide();
                            $("#carregaTokenBrl").hide();

                            if(json.limiteDisponivel != ""){
                                $("#limiteDisponivelReal").html(json.limiteDisponivel);
                            } else {
                                $("#limiteDisponivelReal").html("");
                            }

                            $("#infReais").show();
                            updateSaldo(true);
                            limpaSearchReal();
                        } else {
                            moeda = codigo;
                            saldoDisponivel = "";
                            $("#ultimosSaques").hide();
                            $("#saqueReais").hide();
                            $("#saqueMoedas").show();
                            $("#tituloMoeda").html(json.nomeMoeda);
                            $("#icone").attr("src", json.icone);
                            $("#comissaoCobradaBtc").html(json.taxa + " " + (json.simboloTaxa === null ? json.simbolo : json.simboloTaxa));
                            taxaMoeda = "" + json.taxa;
                            simbolo = json.simbolo;
                            simboloTaxa = json.simboloTaxa;
                            $("#useCarteira").html(json.useCarteira);
                            $("#taxasMoeda").html(json.taxasMoeda);
                            $("#carregaToken").hide();
                            $("#token2fa").hide();

                            if(json.limiteDisponivel != ""){
                                $("#limiteDisponivelCripto").html(json.limiteDisponivel);
                            } else {
                                $("#limiteDisponivelCripto").html("");
                            }
                            
                            $("#erc20").removeClass("active");
                            $("#bep20").removeClass("active");
                            
                            if(json.erc20){
                                $("#erc20").show();
                            } else {
                                $("#erc20").hide();
                            }
                            
                            if(json.bep20){
                                $("#bep20").show();
                            } else {
                                $("#bep20").hide();
                            }
                            
                            if(json.aceitaRede != ""){
                                $("#aceitaRede").html(json.aceitaRede);
                                $("#aceitaRede").show();
                            } else {
                                $("#aceitaRede").html("");
                                $("#aceitaRede").hide();
                            }
                            
                            $('input[name="optionRede"]').prop('checked', false);

                            $("#infMoeda").show();
                            redeMoeda(rede);
                            tabelas("moeda");
                            updateSaldo(true);
                            limpaSearchBtc();
                            filtrarBtc();

                        }
                        
                        if(json.limiteInformacao != ""){
                            $("#limiteInformacaoReal").html(json.limiteInformacao);
                            $("#limiteInformacaoCripto").html(json.limiteInformacao);
                            $("#limiteInformacaoReal").show();
                            $("#limiteInformacaoCripto").show();
                        } else {
                            
                            $("#limiteInformacaoReal").html("");
                            $("#limiteInformacaoCripto").html("");
                            $("#limiteInformacaoReal").hide();
                            $("#limiteInformacaoCripto").hide();
                        }

                        $("#infGerais").show();
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                        showNotyAlert(json.mensagem, "e");
                }
            }
        });
    }

    function redeMoeda(rede){
        if(rede){
            $("#redeMoeda").show();
        } else {
            $("#redeMoeda").hide();
            $("#redeConfirmar").hide();
            $("#rede").html('');
        }
    }

    function limpaSearchBtc(){
        $("#valor").val("");
        $("#endereco").val("");
        $("#pin").val("");
        $("#token").val("");
        $("#debitadoBtc").html("0.00000000");
        $("#filtroTextoBtc").val("");
        $("#diaBtc").removeClass("active");
        $("#mesBtc").removeClass("active");
        $("#todosBtc").removeClass("active");
        $("#semanaBtc").addClass("active");
        $("#semanaBtc").click();
        dataCoin = "semana";
        filtrarBtc();
    }

    function limpaSearchReal(){
        $("#semanaReal").addClass("active");
        $("#filtroIdContaBancariaEmpresa").prop('selectedIndex',0);
        $("#filtroStatus").prop('selectedIndex',0);
        $("#filtroTipoDeposito").prop('selectedIndex',0);
        $("#filtroTextoReal").val("");
        $("#filtroTextoAtar").val("");
        $("#valorReais").val("0,00").trigger("keyup");
        $("#diaReal").removeClass("active");
        $("#mesReal").removeClass("active");
        $("#todosReal").removeClass("active");
        $("#semanaReal").click();
        dataReal = "semana";
        filtrarReais();
    }


    function filtrarReaisAux(){
        dataReal = "todos";
        filtrarReais();
    }

    function filtrarAtarAux(){
        dataAtar = "todos";
        filtrarAtar();
    }

    function boletoAux(){
    boleto = true;
    filtrarReais();
    }

    function filtrarReais() {
        $("#listaReais").html("<tr><td colspan='11' class='text-center'><img src='<?php echo IMAGES ?>loading.gif' /></td></tr>");
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_REAIS_SAQUES_FILTRAR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                data: dataReal,
                idContaBancaria: $("#filtroIdContaBancaria").val(),
                status: $("#filtroStatus").val(),
                filtro: $("#filtroTextoReal").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                            $("#listaReais").html(json.html);
                            $(".saque-motivo").each(function () {
                                let motivo = $(this).attr("data-motivo");
                                let controle = $(this).attr("data-controle");
                                $(this).popover({
                                    html: true,
                                    trigger: "focus",
                                    container: "body",
                                    placement: "top",
                                    title: "<?php echo $idioma->getText("controle")?> " + controle,
                                    content: motivo
                                });
                            });

                            $('#tbllistareais').trigger('footable_initialize');


                    } else {
                        $("#listaReais").html("<tr><td colspan='11' class='text-center'>"+json.mensagem+"</td></tr>");
                    }
                } catch (e) {
                    $("#listaBoleto").html("<tr><td colspan='11' class='text-center'>"+e+"</td></tr>");
                }
            }
        });
    }

    function limparTransferir() {
    $("#nomeCliente").html("");
    $("#email").val("");
    }

    function limparCampos(){
        $("#idContaBancariaEmpresa").val("");
        $("#comprovante").val("");
        $("#tipoDeposito").val("<?php echo Utils\Constantes::TED ?>");
        $("#valor").val("0,00");
        $("#valorBoleto").val("0,00");
    }

    function saqueTransferir(processo){
        if(codeContaBancaria == 1){
            transferir();
        } else if(codeContaBancaria == 2){
            atar();
        } else {
            saque(processo);
        }
    }

    <?php if($configuracao->atarAtivo == 1 ) { ?>

    function atarSaldo() {
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_ATAR_SALDO ?>',
            method: 'post',
            dataType: 'json',
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#atarSaldo").html(json.atarSaldo);
                    } else {
                        $("#atarSaldo").html("R$ 0,00");
                    }
                } catch (e) {

                }
            }
        });
    }


    function atar() {
        $("#tokenAtar").val("");
        $("#pinAtar").val("");
        $("#token2faBrl").hide();
        $("#infReais").hide();
        $("#carregaTokenBrl").show();
        $("#carregaTokenBrl").html("<img src='<?php echo IMAGES ?>loading.gif' />");

        $("#btnSalvar").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_ATAR_TOKEN ?>',
            method: 'post',
            dataType: 'json',
            data: {
                valorReais: $("#valorReais").val(),
                documento: $("#atarDoc").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                            $("#tokenBrl").val("");
                            $("#pinBrl").val("");
                            $("#carregaTokenBrl").hide();
                            $("#token2faAtar").show();
                            $("#documentoAtar").html(json.documentoCPF);
                            $("#valorSolicitadoAtar").html("R$ " + json.valorSolicitado);
                            $("#valorSaqueAtar").html("R$ " + json.valorSaque);
                            showNotyAlert(json.mensagem, "s");

                    } else {
                        $("#token2faAtar").hide();
                        $("#carregaTokenBrl").hide();
                        $("#infReais").show();
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    $("#token2faAtar").hide();
                    $("#carregaTokenBrl").hide();
                    $("#infReais").show();
                    showNotyAlert(e, "e");
                }

                $("#btnSalvar").prop("disabled", false);
            }
        });
    }

    function saqueAtar() {
        $("#token2faAtar").hide();
        $("#carregaTokenBrl").show();
        $("#carregaTokenBrl").html("<img src='<?php echo IMAGES ?>loading.gif' />");

        $("#btnSalvar").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_ATAR_SALVAR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                valorReais: $("#valorReais").val(),
                documento: $("#atarDoc").val(),
                token: $("#tokenAtar").val(),
                pin: $("#pinAtar").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#carregaTokenBrl").hide();
                        $("#infReais").show();
                        filtrarAtar();
                        showNotyAlert(json.mensagem, "s");

                    } else {
                        $("#carregaTokenBrl").hide();
                        $("#infReais").show();
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    $("#token2faAtar").hide();
                    $("#carregaTokenBrl").hide();
                    $("#infReais").show();
                    showNotyAlert(e, "e");
                }

                $("#btnSalvar").prop("disabled", false);
            }
        });
    }

    function filtrarAtar() {
        $("#listaAtar").html("<tr><td colspan='7' class='text-center'><img src='<?php echo IMAGES ?>loading.gif' /></td></tr>");
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_ATAR_LISTAR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                data: dataAtar,
                filtro: $("#filtroTextoAtar").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                            $("#listaAtar").html(json.html);
                            $('#tbllistaAtar').trigger('footable_initialize');
                    } else {

                        $("#listaAtar").html("<tr><td colspan='7' class='text-center'>"+json.mensagem+"</td></tr>");
                    }
                } catch (e) {
                    $("#listaAtar").html("<tr><td colspan='7' class='text-center'>"+e+"</td></tr>");
                }
            }
        });
    }
    <?php } ?>

    function saque(processo) {
        $("#token2faBrl").hide();
        $("#infReais").hide();
        $("#carregaTokenBrl").show();
        $("#carregaTokenBrl").html("<img src='<?php echo IMAGES ?>loading.gif' />");

        $("#btnSalvar").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_REAIS_SAQUES_SALVAR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                idContaBancaria: codeContaBancaria,
                valorReais: $("#valorReais").val(),
                processo: processo,
                token: $("#tokenBrl").val(),
                pin: $("#pinBrl").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        if(processo === '<?php echo $processo1 ?>'){

                            $("#tokenBrl").val("");
                            $("#pinBrl").val("");
                            $("#carregaTokenBrl").hide();
                            $("#token2faBrl").show();
                            $("#nomeTitular").html(json.nomeTitular);
                            $("#documentoCPF").html(json.documentoCPF);
                            $("#bancoInf").html(json.bancoInf);
                            $("#agencia").html(json.agencia);
                            $("#conta").html(json.conta);
                            $("#valorSolicitado").html(json.valorSolicitado);
                            $("#valorSaque").html(json.valorSaque);
                            showNotyAlert(json.mensagem, "s");

                        } else if (processo === '<?php echo $processo2 ?>') {

                            $("#tokenBrl").val("");
                            $("#pinBrl").val("");
                            $("#carregaTokenBrl").hide();
                            $("#infReais").show();
                        // $("#idContaBancaria").children("option").first().prop("selected", true);
                            $("#valorReais").val("0,00").trigger("keyup");
                            limpaSearchReal();
                            showNotyAlert(json.mensagem, "s");
                        }

                    } else {
                        $("#token2faBrl").hide();
                        $("#carregaTokenBrl").hide();
                        $("#infReais").show();
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    $("#token2faBrl").hide();
                    $("#carregaTokenBrl").hide();
                    $("#infReais").show();
                    showNotyAlert(e, "e");
                }


                saldos();
                calcularValorSacado();
                $("#btnSalvar").prop("disabled", false);
            }
        });
    }

    function transferir() {
        $("#btnSalvar").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_REAIS_TRANSFERIR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                email: $("#email").val(),
                valor: $("#valorReais").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        showNotyAlert("<?php echo $idioma->getText("transSucesso") ?>", "s");
                        limparTransferir();
                        $("#valorReais").val("0,00");

                        limpaSearchReal();
                        showNotyAlert(json.mensagem, "s");//created André 20/08/2019
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#btnSalvar").prop("disabled", false);
                saldos();
                calcularValorSacado();
            }
        });
    }

    function taxas() {
        $("#optionsRede").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_REAIS_SAQUES_GET_TAXAS_ERC20 ?>',
            method: 'post',
            dataType: 'json',
            data: {
                rede: rede,
                codigo: moeda
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                    $("#comissaoCobradaBtc").html(json.taxa + " " + json.simboloTaxa);
                    $("#debitadoBtc").html("0.00000000");
                    $("#valor").val("");
                    
                    if(json.somar){
                        simboloTaxa = null;
                        taxaMoeda = json.taxa;
                    } else {
                        taxaMoeda = 0;
                    }
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#optionsRede").prop("disabled", false);
            }
        });
    }



</script>
    <?php Utils\Layout::append("inspina/footer_esp", $_data) ?>
    </body>
</html>

