<?php
$dataInicial = new Utils\Data(date("d/m/Y"));
$dataFinal = new Utils\Data(date("d/m/Y"));
$dataInicial->subtrair(0, 0, 30);

$moeda = \Modules\principal\Controllers\Principal::getCurrency();
$cliente = isset($_data["cliente"]) ? $_data["cliente"] : new Models\Modules\Cadastro\Cliente();
?>


<?php Utils\Layout::append("inspina/metas", $_data) ?>
<?php Utils\Layout::append("inspina/scripts", $_data) ?>
<?php Utils\Layout::append("inspina/menu", $_data) ?>
<div class="content-wrapper">
  <div class="row wrapper border-bottom page-heading" style="background: linear-gradient(to right, #fff, <?php echo $moeda->mainColor ?>) !important;">
    <div class="col-lg-9">
      <ol class="breadcrumb m-t-md" style="background-color: transparent !important;">
          <li>
            <?php echo $idioma->getText("subTitulo") ?>
          </li>
          <li class="active">
              <strong><?php echo $idioma->getText("titulo") ?>
          </li>
      </ol>
    </div>
    <div class="col-lg-3">
    <?php Utils\Layout::append("inspina/flags", $_data) ?>
    </div>
  </div>
</div>
<br>
    <!-- Main content -->
    <section class="content">

        <div class="row">
            <div class="col col-lg-12">
                <ul class="list-group">
                    <li class="list-group-item">
                        Cliente: <?php echo $cliente->nome ?>
                    </li>
                    <li class="list-group-item">
                        Email: <?php echo $cliente->email ?>
                    </li>
                </ul>
            </div>
        </div>
        
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <?php Utils\Layout::append("mensagem", $_data)?>
                    <div class="panel-heading">
                        Listagem de Logs 
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <div class="row">
                            <div class="col col-lg-3 text-center">
                                <a class="btn btn-default btn-lg" href="<?php echo URLBASE_CLIENT . Utils\Rotas::R_CONTACORRENTEREAIS ?>/<?php echo Utils\Criptografia::encriptyPostId($cliente->id) ?>">
                                    Voltar
                                </a>
                                <br><br>
                            </div>
                        </div>
                        <div class="row">

                            <div class="col col-md-3">
                                <div class="form-group">
                                    <label class="control-label">Data Inicial</label>
                                    <input type="text" id="dataInicial" class="form-control" value="<?php echo $dataInicial->formatar(\Utils\Data::FORMATO_PT_BR)?>" />
                                </div>
                            </div>
                            <div class="col col-md-3">
                                <div class="form-group">
                                    <label class="control-label">Data Final</label>
                                    <input type="text" id="dataFinal" class="form-control" value="<?php echo $dataFinal->formatar(\Utils\Data::FORMATO_PT_BR)?>" />
                                </div>
                            </div>

                            <div class="col col-lg-6">
                                <div class="form-group">
                                    <label>Filtro Geral</label>
                                    <input type="text" id="filtro" class="form-control" />
                                </div>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col col-lg-12 text-center">
                                <br>
                                <button class="btn btn-primary" onclick="filtrar();">
                                    <i class="fa fa-refresh"></i> Atualizar
                                </button>
                                <button class="btn btn-default pull-right" onclick="print();">
                                    <i class="fa fa-print"></i> Imprimir
                                </button>
                                <br><br>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col col-lg-12" >
                                <ul class="list-group" id="lista">
                                    
                                </ul>
                            </div>
                        </div>
                        
                        <br><br>
                        <div class="row">
                            
                            <div class="col col-lg-3 col-lg-offset-9 text-center">
                                <a class="btn btn-default btn-lg" href="<?php echo URLBASE_CLIENT . Utils\Rotas::R_CONTACORRENTEREAIS  ?>/<?php echo Utils\Criptografia::encriptyPostId($cliente->id) ?>">
                                    Voltar
                                </a>
                                <br><br>
                            </div>
                        </div>
                    </div>
                    <!-- /.panel-body -->

                </div>
            </div>

        </div>

    </section>
    
    <div class="clearfix"></div>
</div>

<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>

<script>
    $(document).ready(function () {
        
        filtrar();
        
        $("#dataInicial, #dataFinal").datepicker({format: 'dd/mm/yyyy'}).mask("99/99/9999");
    });
    
    function filtrar() {
        $("#lista").html("<div class='col-lg-12 text-center'><img src='<?php echo IMAGES ?>loading.gif' /></div>");
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_REAIS_LOG_FILTRAR  ?>',
            method: 'post',
            dataType: 'json',
            data: {
                dataInicial:$("#dataInicial").val(),
                dataFinal:$("#dataFinal").val(),
                idUsuario:$("#idUsuario").val(),
                idCliente:<?php echo $cliente->id ?>,
                filtro: $("#filtro").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#lista").html(json.html);
                    } else {
                        $("#lista").html("<div class='col-lg-12 text-center'>"+json.mensagem+"</div>");
                    }
                } catch (e) {
                    $("#lista").html("<div class='col-lg-12 text-center'>"+e+"</div>");
                }
            }
        });
    }
    
    
    function print() {
        var dataInicial = $("#dataInicial").val();
        var dataFinal = $("#dataFinal").val();
        var idUsuario = $("#idUsuario").val();
        var idCliente = <?php echo $cliente->id ?>;
        var filtro = $("#filtro").val();
        var s = dataInicial + "|"+ dataFinal + "|"+idUsuario+"|"+filtro+"|"+idCliente;
        var params = btoa(s);
        
        window.open("<?php echo URLBASE_CLIENT . Utils\Rotas::R_REAIS_LOG_IMPRIMIR ?>/"+params);
        
    }
    
</script>