<?php
$sucesso = isset($_data["sucesso"]) ? $_data["sucesso"] : true;
$mensagem = isset($_data["mensagem"]) ? $_data["mensagem"] : "";

$dataInicial = new Utils\Data(date("d/m/Y"));
$dataInicial->subtrair(0,1,0);
$dataFinal = new Utils\Data(date("d/m/Y"));

$moedas = isset($_data["moedas"]) ? $_data["moedas"] : Array();
$moeda = \Modules\principal\Controllers\Principal::getCurrency();
?>

<?php Utils\Layout::append("inspina/metas", $_data) ?>

<?php Utils\Layout::append("inspina/scripts", $_data) ?>


<?php Utils\Layout::append("inspina/menu", $_data) ?>


                
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
     <div class="row wrapper border-bottom page-heading" style="background: linear-gradient(to right, #fff, <?php echo $moeda->mainColor ?>) !important;">
        <div class="col-lg-10">
            <h2>Painel de controle de transações</h2>
            <ol class="breadcrumb" style="background-color: transparent !important;">
                <li>
                    Moedas
                </li>
                <li class="active">
                    <strong>Painel de controle de transações</strong>
                </li>
            </ol>
        </div>
    </div>
</div>         
</br> 
<?php Utils\Layout::append("mensagem", $_data)?>
    <div class="panel-body">
        <div class="row">
            <div class="col col-lg-12">
                <div class="tabs-container">
                    <ul class="nav nav-tabs">
                    <li class="active"><a data-toggle="tab" href="#tab-1" aria-expanded="true" data-target="#transacoes-tab-1, #lista-tab1">Pendentes</a></li>
                    <li class=""><a data-toggle="tab" href="#tab-2" aria-expanded="false" data-target="#transacoes-tab-2, #lista-tab2">Não Autorizadas</a></li>
                    <li class=""><a data-toggle="tab" href="#tab-3" aria-expanded="false" data-target="#transacoes-tab-3, #lista-tab3">Saques ICO</a></li>
                    </ul>
                    <div class="tab-content">
                        <div id="transacoes-tab-1" class="tab-pane active">
                            <div class="panel-body">
                                <div class="row">
                                    <div class="col col-lg-2">
                                        <div class="form-group" >
                                            <label>Moeda</label>
                                            <select class="select2" id="filtroMoeda" style="width: 100%;" >
                                                option value="<?php echo \Utils\Criptografia::encriptyPostId(0)?>" style="">Todas</option><
                                                <?php  
                                                foreach ($moedas as $moeda) {
                                                    ?>
                                                <option value="<?php echo \Utils\Criptografia::encriptyPostId($moeda->id)?>" style=""><?php echo $moeda->simbolo ?></option>
                                                    <?php
                                                }
                                                ?>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col col-lg-3">
                                        <div class="form-group">
                                            <label>Data inicial</label>
                                            <input type="text" class="form-control" id="filtroDataInicial" value="<?php echo $dataInicial->formatar(Utils\Data::FORMATO_PT_BR)?>"/>
                                        </div>
                                    </div>
                                    <div class="col col-lg-3">
                                        <div class="form-group">
                                            <label>Data final</label>
                                            <input type="text" class="form-control" id="filtroDataFinal"  value="<?php echo $dataFinal->formatar(Utils\Data::FORMATO_PT_BR)?>" />
                                        </div>
                                    </div>

                                    <div class="col col-lg-4">
                                        <div class="form-group">
                                            <label>Status</label>
                                            <select class="form-control" id="filtroStatus"> 
                                                <option value="0">Pendentes</option>
                                                <option value="1">Confirmadas</option>
                                                <option value="-1">Todas</option>
                                            </select>
                                        </div>
                                    </div>

                                </div>


                                <div class="row">
                                    <div class="col col-lg-12">
                                        <label >Filtro geral</label>
                                        <input type="text" id="filtro" class="form-control" />
                                    </div>
                                </div>

                                <br><br>

                                <div class="row">
                                    <div class="col col-lg-12 text-center">
                                        <button class="btn btn-info" onclick="filtrar();">
                                            Filtrar
                                        </button>
                                    </div>
                                </div>

                                <br><br>

                                <ul class="list-group" id="listaTransacoes">

                                </ul>
                                
                                
                            </div>
                        </div>
                        <div id="transacoes-tab-2" class="tab-pane">
                            <div class="panel-body">
                                <div class="row">
                                    <div class="col col-lg-2 col-lg-offset-5">
                                        <div class="form-group" style="text-align: center;">
                                            <label>Moeda</label>
                                            <select class="select2" id="filtroMoedaTransacoesNaoAutorizadas" style="width: 100%;" >
                                                <option value="<?php echo \Utils\Criptografia::encriptyPostId(0)?>" style="">Todas</option>
                                                <?php  
                                                foreach ($moedas as $moeda) {
                                                    ?>
                                                <option value="<?php echo \Utils\Criptografia::encriptyPostId($moeda->id)?>" style=""><?php echo $moeda->simbolo ?></option>
                                                    <?php
                                                }
                                                ?>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <br>
                                <div class="row">
                                    <div class="col col-lg-12 text-center">
                                        <button class="btn btn-info" onclick="filtrarTransacoesNaoAutorizadas();">
                                            Atualizar
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div id="transacoes-tab-3" class="tab-pane">
                            <div class="panel-body">
                                <div class="row">
                                    <div class="col col-lg-2">
                                        <div class="form-group">
                                            <label>Data inicial</label>
                                            <input type="text" class="form-control" id="filtroSaqueIcoDataInicial" value="<?php echo $dataInicial->formatar(Utils\Data::FORMATO_PT_BR)?>"/>
                                        </div>
                                    </div>
                                    <div class="col col-lg-2">
                                        <div class="form-group">
                                            <label>Data final</label>
                                            <input type="text" class="form-control" id="filtroSaqueIcoDataFinal"  value="<?php echo $dataFinal->formatar(Utils\Data::FORMATO_PT_BR)?>" />
                                        </div>
                                    </div>

                                    <div class="col col-lg-3">
                                        <div class="form-group">
                                            <label>Status</label>
                                            <select class="form-control" id="filtroSaqueIcoStatus"> 
                                                <option value="0">Pendentes</option>
                                                <option value="1">Autorizadas</option>
                                                <option value="2">Finalizadas</option>
                                                <option value="3">Negadas</option>
                                                <option value="100">Todos</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col col-lg-5">
                                        <label >Filtro geral</label>
                                        <input type="text" id="saqueIcoFiltro" class="form-control" />
                                    </div>
                                </div>
                                <br><br>

                                <div class="row">
                                    <div class="col col-lg-12 text-center">
                                        <button class="btn btn-info" onclick="filtrarSaquesIco();">
                                            Filtrar
                                        </button>
                                    </div>
                                </div>

                                <br><br>

                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>                 
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col col-lg-12">
                <div class="tab-content">
                    <div id="lista-tab1" class="tab-pane active">
                        
                    </div>
                    <div id="lista-tab2" class="tab-pane">
                        <div class="row">
                            <div class="col-lg-12 table-responsive">
                                <table class="table table-striped table-hover table-condensed table-bordered" style="font-size: 10px; background-color: #fff">
                                    <thead>
                                        <tr>
                                            <th class="text-center"><strong>Controle</strong></th>
                                            <th class="text-center"><strong>Moeda</strong></th>
                                            <th class="text-center"><strong>Solicitado</strong></th>
                                            <th class="text-center"><strong>Cliente</strong></th>
                                            <th class="text-center"><strong>Destino</strong></th>
                                            <th class="text-center"><strong>Taxa</strong></th>
                                            
                                            <th class="text-center"><strong>Volume</strong></th>
                                            <th class="text-center"><strong>Int/Ext</strong></th>
                                            <th class="text-center"><strong>Comp.</strong></th>
                                            <th class="text-center"><strong>Status</strong></th>
                                            <th class="text-center"><strong>Ação</strong></th>
                                        </tr>
                                    </thead>

                                    <tbody id="listaTransacoesNaoAutorizadas">

                                    </tbody>

                                </table>
                            </div>
                        </div>
                    </div>
                    <div id="lista-tab3" class="tab-pane">
                        <div class="row">
                            <div class="col-lg-12 table-responsive">
                                <table class="table table-striped table-hover table-condensed table-bordered" style="font-size: 10px; background-color: #fff">
                                    <thead>
                                        <tr>
                                            <th class="text-center"><strong>Controle</strong></th>
                                            <th class="text-center"><strong>Cliente</strong></th>
                                            <th class="text-center"><strong>Volume Dólar</strong></th>
                                            <th class="text-center"><strong>Cotação</strong></th>
                                            <th class="text-center"><strong>Volume Bitcoin</strong></th>
                                            <th class="text-center"><strong>Data</strong></th>
                                            <th class="text-center"><strong>Status</strong></th>
                                            <th class="text-center"><strong>Aprovar</strong></th>
                                            <th class="text-center"><strong>Negar</strong></th>
                                        </tr>
                                    </thead>

                                    <tbody id="listaSaquesIcoAutorizadas">

                                    </tbody>

                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>



<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>

<script>
    $(document).ready(function () {
        $("#filtroMoeda, #filtroMoedaTransacoesNaoAutorizadas").select2();
        $("#filtroDataInicial, #filtroDataFinal").datepicker({format: "dd/mm/yyyy"}).mask("99/99/9999");
        
        $("#modalConfirmarSaqueIcoCotacao").keydown(function (event) {
            $(this).val(currency($(this).val(), 8, 8, event.keyCode));
            event.preventDefault();
            
            var cotacao = parseFloat(($("#modalConfirmarSaqueIcoCotacao").val().length > 0 ? $("#modalConfirmarSaqueIcoCotacao").val().replace(",", ".") : 0));
            
            var volumeBtc = ((volumeConversao / cotacao) - taxaTransacao);
            if (volumeBtc < 0) {
                volumeBtc = 0;
            }
            
            $("#modalConfirmarSaqueIcoTotalBtc").html(volumeBtc.toFixed(8));
        });
        
        filtrar();
        filtrarTransacoesNaoAutorizadas();
        filtrarSaquesIco();
    });
    
    
    function filtrar() {
        $("#listaTransacoes").html("<li class='list-group-item'><div class='row'><div class='col col-lg-12 text-center'><img src='<?php echo IMAGES ?>loader.gif' /></div></div></li>");
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_BTC_PAINEL_FILTRAR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                dataInicial: $("#filtroDataInicial").val(),
                dataFinal: $("#filtroDataFinal").val(),
                status: $("#filtroStatus").val(),
                filtro: $("#filtro").val(),
                moeda: $("#filtroMoeda").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#listaTransacoes").html(json.html);
                    } else {
                        $("#listaTransacoes").html("<li class='list-group-item'><div class='row'><div class='col col-lg-12 text-center'>"+json.mensagem+"</div></div></li>");
                    }
                } catch (e) {
                    $("#listaTransacoes").html("<li class='list-group-item'><div class='row'><div class='col col-lg-12 text-center'>"+e+"</div></div></li>");
                }
            }
        });
        
    }
    
    function filtrarTransacoesNaoAutorizadas() {
        $("#listaTransacoesNaoAutorizadas").html("<tr ><td class='text-center' colspan='11' ><img src='<?php echo IMAGES ?>loader.gif' /></td><\tr>");
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_BTC_PAINEL_FILTRARNAOAUTORIZADAS ?>',
            method: 'post',
            dataType: 'json',
            data: {
                moeda: $("#filtroMoedaTransacoesNaoAutorizadas").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#listaTransacoesNaoAutorizadas").html(json.html);
                    } else {
                        $("#listaTransacoesNaoAutorizadas").html("<tr ><td class='text-center' colspan='11' >"+json.mensagem+"</td><\tr>");
                    }
                } catch (e) {
                    $("#listaTransacoesNaoAutorizadas").html("<tr ><td class='text-center' colspan='11' >"+e+"</td><\tr>");
                }
            }
        });
        
    }
    
    function filtrarSaquesIco() {
        $("#listaSaquesIcoAutorizadas").html("<tr ><td class='text-center' colspan='10' ><img src='<?php echo IMAGES ?>loader.gif' /></td><\tr>");
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_PAINEL_ICO_SAQUES ?>',
            method: 'post',
            dataType: 'json',
            data: {
                dataInicial: $("#filtroSaqueIcoDataInicial").val(),
                dataFinal: $("#filtroSaqueIcoDataFinal").val(),
                status: $("#filtroSaqueIcoStatus").val(),
                filtro: $("#saqueIcoFiltro").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#listaSaquesIcoAutorizadas").html(json.html);
                    } else {
                        $("#listaSaquesIcoAutorizadas").html("<tr ><td class='text-center' colspan='10' >"+json.mensagem+"</td><\tr>");
                    }
                } catch (e) {
                    $("#listaSaquesIcoAutorizadas").html("<tr ><td class='text-center' colspan='10' >"+e+"</td><\tr>");
                }
            }
        });
        
    }
    
    function modalExcluir(codigo) {
        $("#modalExclusaoCodigo").val(codigo);
        $("#modalExclusao").modal();
    }
    
    function excluir() {
        $("#modalExclusaoClose, #modalExclusaoExcluir").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_BTC_PAINEL_EXCLUIR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                hash: $("#modalExclusaoCodigo").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        location = "<?php echo URLBASE_CLIENT . Utils\Rotas::R_PAINELBTC ?>";
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#modalExclusaoClose, #modalExclusaoExcluir").prop("disabled", false);
            }
        });
        
    }
    
    function modalAutorizarTransacao(codigo) {
        $("#modalConfirmarAutorizarTransacaoIdTransacao").val(codigo);
        $("#modalConfirmarAutorizarTransacao").modal();
    }
    
    function modalNegarTransacao(codigo) {
        $("#modalConfirmarNegarTransacaoIdTransacao").val(codigo);
        $("#modalConfirmarNegarTransacao").modal();
    }
    
    
    function autorizarTransacao() {
        $("#modalConfirmarAutorizarTransacaoClose, #modalConfirmarAutorizarTransacaoConfirmar").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_BTC_PAINEL_AUTORIZARTRANSACAO ?>',
            method: 'post',
            dataType: 'json',
            data: {
                id: $("#modalConfirmarAutorizarTransacaoIdTransacao").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#modalConfirmarAutorizarTransacaoClose").prop("disabled", false).trigger("click");
                        filtrarTransacoesNaoAutorizadas();
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#modalConfirmarAutorizarTransacaoClose, #modalConfirmarAutorizarTransacaoConfirmar").prop("disabled", false);
            }
        });
        
    }
    
    
    function negarTransacao() {
        $("#modalConfirmarNegarTransacaoClose, #modalConfirmarNegarTransacaoConfirmar").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_BTC_PAINEL_NEGARTRANSACAO ?>',
            method: 'post',
            dataType: 'json',
            data: {
                id: $("#modalConfirmarNegarTransacaoIdTransacao").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#modalConfirmarNegarTransacaoClose").prop("disabled", false).trigger("click");
                        filtrarTransacoesNaoAutorizadas();
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#modalConfirmarNegarTransacaoClose, #modalConfirmarNegarTransacaoConfirmar").prop("disabled", false);
            }
        });
        
    }
    
    
    var volumeConversao = 0;
    var taxaTransacao = 0;
    
    function modalAutorizarSaqueIco(codigo) {
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_PAINEL_ICO_CARREGARSAQUE ?>',
            method: 'post',
            dataType: 'json',
            data: {
                codigo: codigo
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        volumeConversao = json.saqueIco.volumeMoedaConversao;
                        taxaTransacao = parseFloat(json.taxa);
                        $("#modalConfirmarSaqueIcoIdSaqueIco").val(codigo);

                        $("#modalConfirmarSaqueIcoCotacao").val(json.saqueIco.cotacao.replace(".", ",")).trigger("keydown");
                        $("#modalConfirmarSaqueIcoExchange").val(json.saqueIco.exchangeCotacao);

                        $("#modalConfirmarSaqueIco").modal();
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
            }
        });
    }
    
    
    function modalNegarSaqueIco(codigo) {
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_PAINEL_ICO_CARREGARSAQUE ?>',
            method: 'post',
            dataType: 'json',
            data: {
                codigo: codigo
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        
                        $("#modalNegarSaqueIcoIdSaqueIco").val(codigo);

                        $("#modalNegarSaqueIcoMotivo").val();

                        $("#modalNegarSaqueIco").modal();
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
            }
        });
    }
    
    
    function autorizarSaqueIco() {
        $("#modalConfirmarSaqueIcoClose, #modalConfirmarSaqueIcoConfirmar").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_PAINEL_ICO_AUTORIZARSAQUE ?>',
            method: 'post',
            dataType: 'json',
            data: {
                codigo: $("#modalConfirmarSaqueIcoIdSaqueIco").val(),
                cotacao: $("#modalConfirmarSaqueIcoCotacao").val(),
                exchange: $("#modalConfirmarSaqueIcoExchange").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        showNotyAlert(json.mensagem, "s");
                        $("#modalConfirmarSaqueIcoClose").prop("disabled", false).trigger("click");
                        filtrarSaquesIco();
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#modalConfirmarSaqueIcoClose, #modalConfirmarSaqueIcoConfirmar").prop("disabled", false);
            }
        });
    }
    
    function negarSaqueIco() {
        $("#modalNegarSaqueIcoClose, #modalNegarSaqueIcoConfirmar").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_PAINEL_ICO_AUTORIZARSAQUE ?>',
            method: 'post',
            dataType: 'json',
            data: {
                codigo: $("#modalConfirmarSaqueIcoIdSaqueIco").val(),
                motivo: $("#modalNegarSaqueIcoMotivo").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        showNotyAlert(json.mensagem, "s");
                        $("#modalNegarSaqueIcoClose").prop("disabled", false).trigger("click");
                        filtrarSaquesIco();
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#modalNegarSaqueIcoClose, #modalNegarSaqueIcoConfirmar").prop("disabled", false);
            }
        });
    }
</script>


<div class="modal fade" id="modalExclusao" tabindex="-1" role="dialog" aria-labelledby="modalExclusao" aria-hidden="true" >
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="modalExclusaoLabel">Excluir transação</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col col-lg-12">
                        <input type="hidden" id="modalExclusaoCodigo" />
                        Deseja realmente excluir a transação?
                    </div>
                </div>
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="modalExclusaoClose" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-danger" onclick="excluir();" id="modalExclusaoExcluir" >Excluir</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

<div class="modal fade" id="modalConfirmarAutorizarTransacao" tabindex="-1" role="dialog" aria-labelledby="modalConfirmarAutorizarTransacao" aria-hidden="true" >
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="modalConfirmarAutorizarTransacaoLabel">Autorizar Transação</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col col-lg-12">
                        <input type="hidden" id="modalConfirmarAutorizarTransacaoIdTransacao" />
                        Deseja realmente autorizar a transação?
                    </div>
                </div>
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="modalConfirmarAutorizarTransacaoClose" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-primary" onclick="autorizarTransacao();" id="modalConfirmarAutorizarTransacaoConfirmar" >Autorizar</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>


<div class="modal fade" id="modalConfirmarNegarTransacao" tabindex="-1" role="dialog" aria-labelledby="modalConfirmarNegarTransacao" aria-hidden="true" >
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="modalConfirmarNegarTransacaoLabel">Autorizar Transação</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col col-lg-12">
                        <input type="hidden" id="modalConfirmarNegarTransacaoIdTransacao" />
                        Deseja realmente negar a transação?
                    </div>
                </div>
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="modalConfirmarNegarTransacaoClose" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-danger" onclick="negarTransacao();" id="modalConfirmarNegarTransacaoConfirmar" >Negar</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>




<div class="modal fade" id="modalConfirmarSaqueIco" tabindex="-1" role="dialog" aria-labelledby="modalConfirmarSaqueIco" aria-hidden="true" >
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="modalConfirmarSaqueIcoLabel">Autorizar Resgate</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col col-lg-12">
                        <input type="hidden" id="modalConfirmarSaqueIcoIdSaqueIco" />
                        
                        <div class="form-group">
                            <label>Informe a cotação utilizada</label>
                            <input type="text" id="modalConfirmarSaqueIcoCotacao" class="form-control" />
                            <p>O cliente receberá: <span id="modalConfirmarSaqueIcoTotalBtc"></span> BTC.</p>
                        </div>
                        
                        
                        <div class="form-group">
                            <label>Informe a exchange utilizada para cotação</label>
                            <input type="text" id="modalConfirmarSaqueIcoExchange" maxlength="200" class="form-control" />
                        </div>
                    </div>
                </div>
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="modalConfirmarSaqueIcoClose" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-primary" onclick="autorizarSaqueIco();" id="modalConfirmarSaqueIcoConfirmar" >Autorizar</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>


<div class="modal fade" id="modalNegarSaqueIco" tabindex="-1" role="dialog" aria-labelledby="modalNegarSaqueIco" aria-hidden="true" >
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="modalNegarSaqueIcoLabel">Autorizar Transação</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col col-lg-12">
                        <input type="hidden" id="modalNegarSaqueIcoIdSaqueIco" />
                        <div class="form-group">
                            <label>Informe o motivo para negação do saque:</label>
                            <input type="text" id="modalNegarSaqueIcoMotivo" maxlength="200" class="form-control" />
                        </div>
                    </div>
                </div>
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="modalNegarSaqueIcoClose" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-danger" onclick="negarSaqueIco();" id="modalNegarSaqueIcoConfirmar" >Negar</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>