<?php
$comissao = isset($_data["comissao"]) ? $_data["comissao"] : 0;
$deposito = isset($_data["deposito"]) ? $_data["deposito"] : new Models\Modules\Cadastro\Deposito();
$contasBancarias = isset($_data["contas"]) ? $_data["contas"] : Array();
$valorCreditado = ($deposito->valorDepositado - ($deposito->valorDepositado * $comissao / 100));

$cliente = Utils\Geral::getCliente();
$mostrarBotaoDeposito = (Utils\Geral::isCliente() && ($cliente->statusDepositoBrl > 0));
?>

<?php Utils\Layout::append("inspina/metas", $_data) ?>
<?php Utils\Layout::append("inspina/scripts", $_data) ?>
<?php Utils\Layout::append("inspina/menu", $_data) ?>
<div class="content-wrapper">
  <div class="row wrapper border-bottom page-heading" style="background: linear-gradient(to right, #fff, <?php echo $moeda->mainColor ?>) !important;">
    <div class="col-lg-9">
      <ol class="breadcrumb m-t-md" style="background-color: transparent !important;">
          <li>
            <?php echo $idioma->getText("subTitulo") ?>
          </li>
          <li class="active">
              <strong><?php echo $idioma->getText("titulo") ?>
          </li>
      </ol>
    </div>
    <div class="col-lg-3">
    <?php Utils\Layout::append("inspina/flags", $_data) ?>
    </div>
  </div>
</div>
<br>

<div class="row">
            <div class="col col-lg-12">
                <div class="alert alert-danger" style="margin-bottom: 0px !important;">

                    <p>
                        Fique atento as nossas regras sobre <b>DEPÓSITOS</b>:
                        <br>
                    <ul>
                        <li>Desaconselhamos que os depósitos sejam realizados em dinheiro, caso tenha realizado um depósito em dinheiro, selecione o banco/conta onde o depósito foi realizado, no tipo de depósito escolha a opção Dinheiro e leia a política do banco sobre este tipo de depósito. 
                        A política de depósito do banco estará disponível no quadro "Informações sobre o banco selecionado", destacada em vermelho.</li>
                        <li>Não realizamos o estorno de depósitos em dinheiro.</li>
                        <li>Não aceitamos <b>TED</b> ou <b>DOC</b> realizados por contas de terceiros, o estorno será executado para a conta de origem e será descontado 3% do valor depositado.</li>
                    </ul>
                    </p>

                </div>
            </div>
</div>

<br>
    <!-- Main content -->
    <section class="content">

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <?php Utils\Layout::append("mensagem", $_data)?>
                    
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        
                        <div class="row">
                            
                            
                            <div class="col col-lg-6">
                                <form action="<?php echo URLBASE_CLIENT  . Utils\Rotas::R_REAIS_DEPOSITOS_SALVAR ?>" method="post" enctype="multipart/form-data" id="form-deposito">
                                    <input type="hidden" value="<?php echo $deposito->id ?>" name="id" />
                                    
                                    <div class="row">
                                        <div class="col col-lg-12">
                                            <div class="form-group">
                                                <label>Selecione o banco para depósito:</label>
                                                <select class="form-control" id="idContaBancariaEmpresa" name="idContaBancariaEmpresa">
                                                    <option value="0">Selecione uma conta</option>
                                                    <?php 
                                                    foreach ($contasBancarias as $contaBancaria) {
                                                        ?>
                                                        <option value="<?php echo $contaBancaria->id?>" <?php echo ($deposito->idContaBancariaEmpresa == $contaBancaria->id ? "selected='true'" : "")?>>
                                                            <?php echo "{$contaBancaria->banco->codigo}-{$contaBancaria->banco->nome}";?>
                                                        </option>
                                                        <?php
                                                    }
                                                    ?>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <div class="row">
                                        <div class="col col-lg-12">
                                            <div class="form-group">
                                                <label>Tipo de depósito:</label>
                                                <select class="form-control" id="tipoDeposito" name="tipoDeposito" >
                                                    <option value="<?php echo Utils\Constantes::TED ?>" <?php echo ($deposito->tipoDeposito == Utils\Constantes::TED ? "selected='true'" : "")?>>TED</option>
                                                    <option value="<?php echo Utils\Constantes::DOC ?>" <?php echo ($deposito->tipoDeposito == Utils\Constantes::DOC ? "selected='true'" : "")?>>DOC</option>
                                                    <option value="<?php echo Utils\Constantes::DINHEIRO ?>" <?php echo ($deposito->tipoDeposito == Utils\Constantes::DINHEIRO ? "selected='true'" : "")?>>Dinheiro</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>

                                    
                                    <div class="row">
                                        <div class="col col-lg-12">
                                            <div class="form-group">
                                                <label>Valor a ser depositado:</label>
                                                <input type="text"  class="form-control" id="valor" name="valor" value="<?php echo number_format($deposito->valorDepositado, 2, ",", ".") ?>" />
                                            </div>
                                        </div>
                                    </div>
                                    

                                    <div class="form-group">
                                        <label>Comprovante de depóstito (Formatos: PDF ou JPEG / Tamanho máximo: 3Mb):</label>
                                        <div class="ibox-content">
                                             <div class="fileinput fileinput-new input-group" data-provides="fileinput">
                                                <div class="form-control" data-trigger="fileinput">
                                                    <i class="glyphicon glyphicon-file fileinput-exists"></i> <span class="fileinput-filename"></span>
                                                </div>
                                                <span class="input-group-addon btn btn-default btn-file">
                                                    <span class="fileinput-new">Selecionar</span>
                                                    <span class="fileinput-exists">Mudar</span>
                                                    <input type="file" id="comprovante" name="comprovante" >
                                                </span>
                                                <a href="#" class="input-group-addon btn btn-default fileinput-exists" data-dismiss="fileinput">Remover</a>
                                            </div>
                                        </div>
                                        <?php if (!empty($deposito->comprovante)) { ?>
                                        <a href="<?php echo URLBASE_CLIENT . UPLOADS . $deposito->comprovante ?>" target="_BLANK">Ver comprovante anexado.</a>
                                        <?php } ?>
                                    </div>
                                    
                                    
                                    <div class="form-group">
                                        <div class="i-checks">
                                            <label class=""> 
                                                <div class="icheckbox_square-green" style="position: relative;">
                                                    <input type="checkbox"  id="aceitaNota" name="aceitaNota" value="1">
                                                </div> CPF na nota?
                                            </label>
                                        </div>
                                    </div>
                                    
                                    <div class="row">
                                        <div class="col col-lg-12">
                                            <h4>Comissão de depósito: (<?php echo number_format($comissao, 2, ",", "")?>%)</h4>
                                            <h4>Será creditado em sua conta: <strong id="valorCreditado">R$ <?php echo number_format($valorCreditado, 2, ",", ".")?></strong></h4>
                                        </div>
                                    </div>
                                    
                                    <br><br>
                                    
                                    <div class="row">
                                        <div class="col col-lg-6 text-center">
                                            <a class="btn btn-default pull-left" href="<?php echo URLBASE_CLIENT . Utils\Rotas::R_DEPOSITOS  ?>" id="btnVoltar">
                                                Ver depósitos efetuados.
                                            </a>
                                        </div>
                                        <div class="col col-lg-6 text-center">
                                            
                                            <?php if (\Models\Modules\Acesso\RotinaRn::validar(\Utils\Rotas::R_DEPOSITOS, \Utils\Constantes::CADASTRAR)) { ?>
                                            
                                            <?php if ($mostrarBotaoDeposito) { ?>
                                            <button class="btn btn-success pull-right" type="submit" id="btnSalvar">
                                                Cadastrar depósito.
                                            </button>
                                            <?php } ?>
                                            
                                            <?php } ?>
                                            
                                        </div>
                                    </div>
                                </form>
                            </div>
                            <br>
                            <div class="col col-lg-6">
                                <div class="panel panel-primary">
                                    <div class="panel-heading">
                                        Informaçoes sobre o banco selecionado!
                                    </div>
                                    <div class="panel-body">
                                        <ul class="list-group">
                                            <li class="list-group-item text-center" style="display: none;" id="item-list-logo-banco">
                                                <img src="" id="logo-banco" style="max-width: 250px; max-height: 80px;"/>
                                            </li>
                                            <li class="list-group-item"><b>Titular: </b><span id="contaTitular"></span></li>
                                            <li class="list-group-item"><b>CNPJ: </b><span id="contaCnpj"></span></li>
                                            <li class="list-group-item"><b>Banco: </b><span id="contaNomeBanco"></span></li>
                                            <li class="list-group-item"><b>Tipo: </b><span id="contaTipo"></span></li>
                                            <li class="list-group-item"><b>Agência: </b><span id="contaAgencia"></span></li>
                                            <li class="list-group-item"><b>Conta: </b><span id="contaNumero"></span></li>
                                            <br>
                                            <div class="alert alert-danger" style="margin-bottom: 0px !important;">
                                                <span id="observacoes">Alertas!</span>
                                            </div>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.panel-body -->
                    <br><br>
                </div>
            </div>

        </div>

    </section>
    

</div>

<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>

<script>
    $(document).ready(function () {
        $("#idContaBancariaEmpresa").change(function () {
            getDadosContaBancaria();
        });
        
        
        $("#valor").keydown(function (event) {
            $(this).val(currency($(this).val(), 2, 8, event.keyCode));
            event.preventDefault();
            calcularValorCreditado();
        });
        
        $("#form-deposito").ajaxForm({
            dataType: 'json',
            beforeSubmit: function () {
                $("#btnVoltar, #btnSalvar").prop("disabled", true);
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        location = "<?php echo URLBASE_CLIENT  . Utils\Rotas::R_DEPOSITOS ?>";
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e){
                    showNotyAlert(e, "e");
                }
                $("#btnVoltar, #btnSalvar").prop("disabled", false);
            }
        });
        
        
        $('.i-checks').iCheck({
            checkboxClass: 'icheckbox_square-green',
            radioClass: 'iradio_square-green',
        });
        
        getDadosContaBancaria();
    });
    
    function getDadosContaBancaria() {
        if ($("#idContaBancariaEmpresa").val() > 0) {
            $.ajax({
                url: '<?php echo URLBASE_CLIENT  . Utils\Rotas::R_REAIS_DEPOSITOS_DADOSCONTA ?>',
                method: 'post',
                dataType: 'json',
                data: {
                    idContaBancariaEmpresa: $("#idContaBancariaEmpresa").val()
                },
                success: function (json) {
                    try {
                        if (json.sucesso) {
                            
                            if (json.conta.banco.logo !== null) {
                                $("#item-list-logo-banco").show();
                                $("#logo-banco").attr("src", "<?php echo IMAGES ?>bancos/" + json.conta.banco.logo);
                            } else {
                                $("#item-list-logo-banco").hide();
                            }
                            
                            $("#contaNomeBanco").html(json.conta.banco.nome);
                            $("#contaTipo").html(json.conta.tipoConta);
                            $("#contaAgencia").html(json.conta.agencia);
                            $("#contaNumero").html(json.conta.conta);
                            $("#contaTitular").html(json.conta.titular);
                            $("#contaCnpj").html(json.conta.cnpj);
                            $("#observacoes").html(json.conta.observacoes);
                        } else {
                            showNotyAlert(json.mensagem, "e");
                        }
                    } catch (e) {
                        showNotyAlert(e, "e");
                    }
                }
            });
        }
    }
    
    function calcularValorCreditado() {
        var valor = ($("#valor").val().length > 0 ? parseFloat($("#valor").val().replace(",", ".")) : 0);
        var comissao = <?php echo number_format($comissao, 2, ".", "")?>;
        
        var resultado = (valor - (valor * comissao / 100));
        $("#valorCreditado").html("R$ " + resultado.toFixed(2).replace(".", ","));
    }
    
</script>
