<?php
$comissao = isset($_data["comissao"]) ? $_data["comissao"] : 0;
$saque = isset($_data["saque"]) ? $_data["saque"] : new Models\Modules\Cadastro\Saque();
$saldo = isset($_data["saldo"]) ? $_data["saldo"] : 0;
$tarifaTed = isset($_data["tarifaTed"]) ? $_data["tarifaTed"] : 0;
$contasBancarias = isset($_data["contas"]) ? $_data["contas"] : Array();

$valorSacado = ($saque->valorSaque - ($saque->valorSaque * $comissao / 100));

$cliente = Utils\Geral::getCliente();
$mostrarBotaoSaque = (Utils\Geral::isCliente() && ($cliente->statusSaqueBrl > 0));

?>

<?php Utils\Layout::append("inspina/metas", $_data) ?>
<?php Utils\Layout::append("inspina/scripts", $_data) ?>
<?php Utils\Layout::append("inspina/menu", $_data) ?>
<div class="content-wrapper">
  <div class="row wrapper border-bottom page-heading" style="background: linear-gradient(to right, #fff, <?php echo $moeda->mainColor ?>) !important;">
    <div class="col-lg-9">
      <ol class="breadcrumb m-t-md" style="background-color: transparent !important;">
          <li>
            <?php echo $idioma->getText("subTitulo") ?>
          </li>
          <li class="active">
              <strong><?php echo $idioma->getText("titulo") ?>
          </li>
      </ol>
    </div>
    <div class="col-lg-3">
    <?php Utils\Layout::append("inspina/flags", $_data) ?>
    </div>
  </div>
</div>
    <!-- Main content -->
    <section class="content">

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <?php Utils\Layout::append("mensagem", $_data)?>
                    
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        
                        <form action="<?php echo URLBASE_CLIENT  . Utils\Rotas::R_REAIS_SAQUES_SALVAR ?>" method="post" enctype="multipart/form-data" id="form-saque">
                            <input type="hidden" value="<?php echo $saque->id ?>" name="id" id="id" />
                            <div class="row">
                                <div class="col col-lg-12">
                                    
                                    <div class="alert alert-success">
                                        Seu Saldo: R$ <?php echo number_format($saldo, 2, ",", ".")?>
                                    </div>
                                </div>
                            </div>    
                            <div class="row">
                                <div class="col col-md-9">
                                    <label>Selecione o banco para depósito</label>
                                    <select class="form-control select-lista-contas-bancarias" id="idContaBancaria" name="idContaBancaria">
                                        <option value="0">Selecione uma conta</option>
                                        <?php 
                                        foreach ($contasBancarias as $contaBancaria) {
                                            ?>
                                            <option value="<?php echo $contaBancaria->id?>" <?php echo ($saque->idContaBancaria == $contaBancaria->id ? "selected='true'" : "")?>>
                                                <?php echo "{$contaBancaria->banco->codigo}-{$contaBancaria->banco->nome} | {$contaBancaria->agencia} | {$contaBancaria->conta}";?>
                                            </option>
                                            <?php
                                        }
                                        ?>
                                    </select>
                                </div>
                                
                                
                                <div class="col col-md-3 text-center">
                                    <br>
                                    <button type="button" class="btn btn-primary" onclick="cadastrarNovaContaBancaria();">
                                        Cadastrar Conta
                                    </button>
                                </div>
                                
                            </div>
                                    
                            <?php Utils\Layout::view("includes/contas_bancarias", $_data)?>


                            <br><br>
                            
                            <div class="row">
                                <div class="col col-md-12">
                                    <div class="form-group">
                                        <label>Valor do saque</label>
                                        
                                        <div class="input-group">
                                            <input type="text"  class="form-control" id="valor" name="valor" value="<?php echo number_format($saque->valorSaque, 2, ",", ".") ?>" />
                                            <span class="input-group-btn">
                                                <button type="button" class="btn btn-primary" onclick="utilizarSaldo();">Meu Saldo Total</button>
                                            </span>
                                        </div>
                                        
                                        
                                    </div>
                                </div>
                            </div>
                            
                            
                            <div class="form-group">
                                <div class="i-checks">
                                    <label class=""> 
                                        <div class="icheckbox_square-green" style="position: relative;">
                                            <input type="checkbox"  id="aceitaNota" name="aceitaNota" value="1" checked>
                                        </div> CPF na nota?
                                    </label>
                                </div>
                            </div>
                            
                            
                            <div class="row">
                                <div class="col col-md-12">
                                    <div class="form-group">
                                        <label>Comissão de saque: (<?php echo number_format($comissao, 2, ",", "")?>%)</label> <br>
                                        <label>Tarifa de transferência: (R$ <?php echo number_format($tarifaTed, 2, ",", "")?>)</label> <br>
                                        <label>Será creditado em sua conta: <strong id="valorSacado">R$ <?php echo number_format($valorSacado, 2, ",", ".")?></strong></label>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col col-md-12">
                                    <div class="form-buttons text-center">
                                        <?php if (Models\Modules\Acesso\ModuloRn::validar(Utils\Rotas::M_SAQUES, \Utils\Constantes::CADASTRAR)) { ?>
                                        
                                        <?php if ($saque->id > 0) { ?>
                                        <button class="btn btn-danger" type="button" id="btnCancelar" onclick="dialogCancelar();">
                                            Cancelar
                                        </button>
                                        <?php } ?>

                                        <?php if ($mostrarBotaoSaque && (!$saque->id > 0)) { ?>
                                        <button class="btn btn-primary pull-right" type="submit" id="btnSalvar">
                                            Confirmar Saque
                                        </button>
                                        <?php } ?>
                                        
                                        <?php } ?>
                                        
                                    </div>
                                </div>
                            </div>
                                    
                        </form>
                    </div>
                    <!-- /.panel-body -->
                    
                </div>
            </div>

        </div>

    </section>
    <br>
    <br>
    <div class="clearfix"></div>
</div>

<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>
<script src="<?php echo TEMA ?>js/plugins/chosen/chosen.jquery.js"></script>
<script src="<?php echo TEMA ?>js/plugins/select2/select2.full.min.js"></script>
<script>
    $(document).ready(function () {
        
        $("#valor").keydown(function (event) {
            $(this).val(currency($(this).val(), 2, 8, event.keyCode));
            event.preventDefault();
            calcularValorSacado();
        });
        
        $("#form-saque").ajaxForm({
            dataType: 'json',
            beforeSubmit: function () {
                $("#btnVoltar, #btnSalvar").prop("disabled", true);
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        location = "<?php echo URLBASE_CLIENT . Utils\Rotas::R_SAQUES  ?>";
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e){
                    alert(e);showNotyAlert(json.mensagem, "e");
                }
                $("#btnVoltar, #btnSalvar").prop("disabled", false);
            }
        });
        
        
        $('.i-checks').iCheck({
            checkboxClass: 'icheckbox_square-green',
            radioClass: 'iradio_square-green'
        });
        
    });
    
    function calcularValorSacado() {
        var valor = ($("#valor").val().length > 0 ? parseFloat($("#valor").val().replace(",", ".")) : 0);
        var comissao = <?php echo number_format($comissao, 2, ".", "")?>;
        var tarifaTed = <?php echo number_format($tarifaTed, 2, ".", "")?>;
        
        var resultado = (valor - (valor * comissao / 100) - tarifaTed);
        $("#valorSacado").html("R$ " + resultado.toFixed(2).replace(".", ","));
    }
    
    
    
    function dialogCancelar() {
        $("#modalCancelar").modal();
    }
    
    function cancelar() {
        $("#btnVoltar, #btnSalvar, #btnCancelar, #modalCancelarClose, #modalCancelarConfirmar").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_REAIS_SAQUES_CANCELAR  ?>',
            method: 'post',
            dataType: 'json',
            data: {
                id: $("#id").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        showNotyAlert("Saque cancelado com sucesso!", "e");
                        location = "<?php echo URLBASE_CLIENT  . Utils\Rotas::R_SAQUES ?>";
                    } else {
                        $("#btnVoltar, #btnSalvar, #btnCancelar").prop("disabled", false);
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    $("#btnVoltar, #btnSalvar, #btnCancelar, #modalCancelarClose, #modalCancelarConfirmar").prop("disabled", false);
                    showNotyAlert(e, "e");
                }
            }
        });
    }
    $('#cadastroContaIdBanco').css('width', '100%');
    $("#cadastroContaIdBanco").select2();
    
    function utilizarSaldo() {
        
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_INIT ?>',
            method: 'post',
            dataType: 'json',
            data: {
                
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#valor").val(json.saldobrl.replace(".", ""));
                        calcularValorSacado();
                    }
                } catch (e) {
                }
                
            }
        });
    }
    
</script>


<div class="modal fade" id="modalCancelar" tabindex="-1" role="dialog"  aria-labelledby="modalCancelar" aria-hidden="true" >
    <div class="modal-dialog" style="width: 800px;">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="modalCancelarLabel">Cancelar Depósito</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col col-lg-12">
                        Deseja realmente cancelar o saque?
                    </div>
                </div>
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="modalCancelarClose" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-danger" onclick="cancelar();" id="modalCancelarConfirmar" >Cancelar</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>