<?php
$dataInicial = new Utils\Data(date("d/m/Y"));
$dataFinal = new Utils\Data(date("d/m/Y"));
$dataInicial->subtrair(0, 0, 30);

$moeda = Modules\principal\Controllers\Principal::getCurrency();

$saldoBtc = (isset($_data["saldobtc"]) ? $_data["saldobtc"] : 0);
$saldoReais = (isset($_data["saldoreais"]) ? $_data["saldoreais"] : 0);

?>
<?php Utils\Layout::append("inspina/metas", $_data) ?>
<?php Utils\Layout::append("inspina/scripts", $_data) ?>
<?php Utils\Layout::append("inspina/menu", $_data) ?>
<div class="content-wrapper">
  <div class="row wrapper border-bottom page-heading" style="background: linear-gradient(to right, #fff, <?php echo $moeda->mainColor ?>) !important;">
    <div class="col-lg-9">
      <ol class="breadcrumb m-t-md" style="background-color: transparent !important;">
          <li>
            <?php echo $idioma->getText("subTitulo") ?>
          </li>
          <li class="active">
              <strong><?php echo $idioma->getText("titulo") ?>
          </li>
      </ol>
    </div>
    <div class="col-lg-3">
    <?php Utils\Layout::append("inspina/flags", $_data) ?>
    </div>
  </div>
</div>
<br>
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-content">


                    <div class="tabs-container">


                        <ul class="nav nav-tabs">
                            <li class="nav-item active" style="width: 33%; text-align: center;">
                                <a data-toggle="tab" href="#tab-1">
                                    <img src="<?php echo IMAGES?>currencies/<?php echo $moeda->icone ?>" style="max-width: 20px; height: 20px;" />
                                    Transferir <?php echo $moeda->nome ?>
                                </a>
                            </li>
                            <li class="nav-item"  style="width: 33%; text-align: center;">
                                <a data-toggle="tab" href="#tab-2">
                                    <img src="<?php echo IMAGES?>currencies/BRL.png" style="max-width: 20px; height: 20px;" />
                                     Transferir Reais
                                </a>
                            </li>
                            <li class="nav-item"  style="width: 33%; text-align: center;">
                                <a data-toggle="tab" href="#tab-3">
                                    Extrato
                                </a>
                            </li>
                            
                            
                        </ul>
                        <div class="tab-content">

                            <div id="tab-1" class="tab-pane active">
                                <div class="panel-body">

                                    <div class="row">
                                        <div class="col-sm-6">
                                            
                                            <div class="form-group">
                                                <label>Endereço <?php echo $moeda->nome ?> de destino.</label> 
                                                <input type="text" class="form-control"  id="enderecoBitcoinCurrency" maxlength="40"/>
                                            </div>
                                            
                                            <div class="form-group">
                                                <label>Descrição para essa transferência.</label> 
                                                <input type="text" class="form-control"  id="descricaoCurrency"  maxlength="60"/>
                                            </div>
                                            
                                            <label>Volume (em <?php echo $moeda->simbolo ?>).</label>
                                            <div class="input-group">
                                                <input type="text" class="form-control" id="transferenciaContaValorCurrency">
                                                <span class="input-group-btn">
                                                    <button type="button" class="btn btn-primary" onclick="utilizarSaldo('c');">Meu Volume Total</button>
                                                </span>
                                            </div>
                                            <p class="help-block">
                                                <strong>
                                                    Saldo disponível para transferência: <span id="saldo-btc-disponivel-transferencia"><?php echo number_format($saldoBtc, 8, ".", "")?></span> <?php echo $moeda->simbolo ?>.
                                                </strong>
                                            </p>
                                        </div>
                                        
                                        <div class="col-sm-6">
                                            <div class="widget style1 " style="background-color: <?php echo $moeda->mainColor ?> !important;">
                                                <div class="row">
                                                    <div class="col-xs-4 text-center">
                                                        <img src="<?php echo IMAGES ?>currencies/<?php echo $moeda->icone ?>"  style="max-height: 60px; max-width: 60px;"/>
                                                    </div>
                                                    <div class="col-xs-8 text-right">
                                                        <span> <?php echo $moeda->nome ?> </span>
                                                        <h1 class="font-bold"> <label id="transferenciaContaTotalCurrency">0.00000000</label></h1>
                                                    </div>
                                                </div>
                                            </div>
                                            
                                            <div class="row">
                                                <div class="col col-lg-12 text-center">
                                                    <br><br>
                                                    <?php if (Models\Modules\Acesso\RotinaRn::validar(Utils\Rotas::R_CONTAS_EMPRESA_TRANSFERENCIA, \Utils\Constantes::CADASTRAR)) { ?>
                                                    <button type="button" class="btn btn-lg  btn-success  m-t-n-xs" id="transferenciaContaBtnTransferirCurrency" onclick="modalTransferirCurrency();">
                                                        <strong>Transferir Agora</strong>
                                                    </button>
                                                   <?php } ?>
                                                </div>
                                            </div>

                                            
                                            
                                            
                                        </div>
                                    </div>

                                </div>
                            </div>



                            <div id="tab-2" class="tab-pane">
                                <div class="panel-body">


                                    <div class="row">
                                        <div class="col-sm-6 b-r">
                                            <div class="form-group">
                                                <label>Carteira de destino.</label>
                                                <div class="form-group">
                                                    <input type="text" class="form-control"  id="transferenciaContaCarteiraReais"/>
                                                    <input type="hidden" id="idClienteDestiantarioReais"/>

                                                </div>
                                                <p>
                                                    Atenção: utilize o endereço de Bitcoin da pessoa para a qual deseja enviar o valor. O valor será debitado em reais da sua 
                                                    conta corrente e será creditado em reais na conta corrente do destinatário.
                                                </p>
                                            </div>
                                            <div class="form-group"><label>Descrição para essa transferência.</label> <input type="text" class="form-control"  id="descricaoReais"  maxlength="60"/></div>
                                            <label>Valor (em reais).</label>
                                            <div class="input-group">
                                                <input type="text" class="form-control" id="transferenciaContaValorReais"  />
                                                <span class="input-group-btn">
                                                    <button type="button" class="btn btn-primary" onclick="utilizarSaldo('r');">Meu Saldo Total</button>
                                                </span>
                                            </div>
                                            <p class="help-block">
                                                <strong>
                                                    Saldo disponível para transferência: R$ <span id="saldo-reais-disponivel-transferencia"><?php echo number_format($saldoReais, 2, ",", "")?></span>.
                                                </strong>
                                            </p>
                                        </div>
                                        <div class="col-sm-6">

                                            <span id="transferenciaContaNomeClienteDestinatarioReais" class="label label-warning" style="font-size: 16px;"></span>
                                            <span id="transferenciaContaNaoEncontradoContainerReais" class="label label-danger" style="font-size: 16px; display: none;">Carteira Inválida</span>
                                            <span style="font-size: 16px;">&nbsp;</span>

                                            <div class="widget style1 navy-bg">
                                                <div class="row">
                                                    <div class="col-xs-4 text-center">
                                                        <span style="font-size: 70px">R</span><i class="fa fa-usd fa-5x"></i>
                                                    </div>
                                                    <div class="col-xs-8 text-right">
                                                        <span> Reais </span>
                                                        <h1 class="font-bold"> <label id="transferenciaContaTotalReais">0,00</label></h1>
                                                    </div>
                                                </div>
                                            </div>
                                            
                                            <div class="row">
                                                <div class="col col-lg-12 text-center">
                                                    <br><br>
                                                    <?php if (Models\Modules\Acesso\RotinaRn::validar(Utils\Rotas::R_CONTAS_EMPRESA_TRANSFERENCIA, \Utils\Constantes::CADASTRAR)) { ?>
                                                    <button type="button" class="btn btn-lg  btn-success m-t-n-xs" id="transferenciaContaBtnTransferirReais" onclick="modalTransferirReais();">
                                                        <strong>Transferir Agora</strong>
                                                    </button>
                                                    <?php } ?>
                                                </div>
                                            </div>
                                            
                                            
                                        </div>

                                    </div>
                                </div>
                            </div>
                            
                            
                            <div id="tab-3" class="tab-pane">
                                <div class="panel-body">
                                    
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <div class="row">

                                                <div class="col col-md-2">
                                                    <div class="form-group">
                                                        <label class="control-label">Data Inicial</label>
                                                        <input type="text" id="dataInicial" class="form-control" value="<?php echo $dataInicial->formatar(\Utils\Data::FORMATO_PT_BR)?>" />
                                                    </div>
                                                </div>
                                                <div class="col col-md-2">
                                                    <div class="form-group">
                                                        <label class="control-label">Data Final</label>
                                                        <input type="text" id="dataFinal" class="form-control" value="<?php echo $dataFinal->formatar(\Utils\Data::FORMATO_PT_BR)?>" />
                                                    </div>
                                                </div>
                                                <div class="col col-md-3">
                                                    <div class="form-group">
                                                        <label>Registros</label>
                                                        <select class="form-control" id="nregistros">
                                                            <option value="10">10 registros</option>
                                                            <option value="20">20 registros</option>
                                                            <option value="50">50 registros</option>
                                                            <option value="100">100 registros</option>
                                                            <option value="T">Todos</option>
                                                        </select>
                                                    </div>
                                                </div>
                                                <div class="col col-lg-5">
                                                    <div class="form-group">
                                                        <label>Filtro Geral</label>
                                                        <input type="text" id="filtro" class="form-control" />
                                                    </div>
                                                </div>
                                            </div>
                                            
                                            <div class="row">
                                                <div class="col col-lg-12 text-center">
                                                    <br>

                                                    <button class="btn btn-primary" onclick="filtrar();">
                                                        <i class="fa fa-refresh"></i> Atualizar
                                                    </button>
                                                    <br><br>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    
                                    <div class="row">
                                        <div class="col-lg-12">        

                                            <div class="tabs-container">

                                                <ul class="nav nav-tabs ">
                                                    <li class="nav-item active" style="width: 50%; text-align: center;">
                                                        <a data-toggle="tab" href="#tab-2-1">
                                                            <img src="<?php echo IMAGES?>currencies/<?php echo $moeda->icone ?>" style="max-width: 20px; height: 20px;" />
                                                            Transferências de <?php echo $moeda->simbolo ?>
                                                        </a>
                                                    </li>
                                                    <li class="nav-item" style="width: 50%; text-align: center;">
                                                        <a data-toggle="tab" href="#tab-2-2">
                                                            <img src="<?php echo IMAGES?>currencies/BRL.png" style="max-width: 20px; height: 20px;" />
                                                            Transferências de reais
                                                        </a>
                                                    </li>
                                                </ul>
                                                <div class="tab-content">

                                                    <div id="tab-2-1" class="tab-pane active">

                                                        <div class="row">
                                                            <div class="col col-lg-12 table-responsive" style="font-size: 10px" >

                                                                <table class="table table-condensed table-stripped table-hover table-bordered">
                                                                    <thead>
                                                                        <tr>
                                                                            <th>Controle</th>
                                                                            <th>Data</th>
                                                                            <th>Descrição</th>
                                                                            <th>Valor</th>
                                                                            <th>Log</th>
                                                                        </tr>
                                                                    </thead>

                                                                    <tbody id="lista-currency" style="background-color: #fff">

                                                                    </tbody>

                                                                </table>
                                                            </div>
                                                        </div>

                                                    </div>

                                                    <div id="tab-2-2" class="tab-pane">
                                                        <div class="row">
                                                            <div class="col col-lg-12 table-responsive" style="font-size: 10px" >

                                                                <table class="table table-condensed table-stripped table-hover table-bordered">
                                                                    <thead>
                                                                        <tr>
                                                                            <th>Controle</th>
                                                                            <th>Data</th>
                                                                            <th>Descrição</th>
                                                                            <th>Valor</th>
                                                                            <th>Log</th>
                                                                        </tr>
                                                                    </thead>

                                                                    <tbody id="lista-reais" style="background-color: #fff">

                                                                    </tbody>

                                                                </table>

                                                            </div>
                                                        </div>
                                                    </div>

                                                </div>

                                            </div>

                                            <div class="clearfix"></div>
                                        </div>
                                    </div><br><br>
                                    
                                </div>
                            </div>
                            
                        </div>

                    </div>

                </div>
            </div>
        </div>
    </div>
   
    <?php if ($adm) { ?>
    <div class="row">

        <div class="col col-lg-3 col-lg-offset-9 text-center">
            <br><br>
            <a class="btn btn-default btn-lg" href="<?php echo URLBASE_CLIENT . Utils\Rotas::R_CONTACORRENTEBTC ?>/<?php echo Utils\Criptografia::encriptyPostId($cliente->id) ?>">
                Voltar
            </a>
            <br><br>
        </div>
    </div>
    <?php } ?>
    
    
    

<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>


<?php Utils\Layout::append("mensage_text", $_data) ?>

<script>
    $(document).ready(function () {
        
        filtrar();
        
        $("#dataInicial, #dataFinal").datepicker({format: 'dd/mm/yyyy'}).mask("99/99/9999");
        
        
        $("#transferenciaContaValorCurrency").keydown(function(event) {
            $(this).val(currency($(this).val(), 8, 8, event.keyCode));
            calcularValorTotal("c");
            event.preventDefault();
        });
        $("#transferenciaContaValorReais").keydown(function(event) {
            $(this).val(currency($(this).val(), 2, 8, event.keyCode));
            calcularValorTotal("r");
            event.preventDefault();
        });
        $("#tokenBtc, #tokenReais, #pinBtc, #pinReais").numeric();
        
        $('#transferenciaContaCarteiraReais').on('keyup', function() {
            let myLength = $("#transferenciaContaCarteiraReais").val().length;
            
            if (myLength > 26) {
                findClienteWallet();
            } else  {
                $("#transferenciaContaNaoEncontradoContainerReais").hide();
                $("#transferenciaContaDestinatarioContainerReais").hide();
                $("#transferenciaContaNomeClienteDestinatarioReais").html("");
                $("#transferenciaContaBtnTransferirReais").prop("disabled", true);
            }
        });
    });
    
    
    
    function utilizarSaldo(tipo) {
        
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_CONTAS_EMPRESA_SALDO ?>',
            method: 'post',
            dataType: 'json',
            data: {
                
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#saldo-btc-disponivel-transferencia").html(json.saldobtc);
                        $("#saldo-reais-disponivel-transferencia").html(json.saldoreais.replace(".",","));
                        if (tipo === "c") {
                            $("#transferenciaContaValorCurrency").val(json.saldobtc);
                            
                        } else {
                            $("#transferenciaContaValorReais").val(json.saldoreais.replace(".",","));
                        }
                        calcularValorTotal(tipo);
                    }
                } catch (e) {
                }
                
            }
        });
    }
    
    function calcularValorTotal(tipo) {
        if (tipo === "c") {
            var taxa = <?php echo number_format($taxa, 8, ".", "")?>;
            var valor = ($("#transferenciaContaValorCurrency").val().length > 0 ? parseFloat($("#transferenciaContaValorCurrency").val().replace(",", ".")) : 0.00);
            var total = taxa + valor;
            $("#transferenciaContaTotalCurrency").text(total.toFixed(8).replace(".",","));
        } else {
            var taxa = <?php echo number_format($configuracao->taxaTransferenciaInternaReais, 2, ".", "")?>;
            var valor = ($("#transferenciaContaValorReais").val().length > 0 ? parseFloat($("#transferenciaContaValorReais").val().replace(",", ".")) : 0.00);
            var total = taxa + valor;
            $("#transferenciaContaTotalReais").text(total.toFixed(2).replace(".",","));
        }
    }
    
    function filtrar() {
        filtrarCurrency();
        filtrarReais();
    }
    
    function filtrarCurrency() {
        $("#lista-currency").html("<tr><td colspan='5' class='text-center'><img src='<?php echo IMAGES ?>loading.gif' /></td></tr>");
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_CONTAS_EMPRESA_FILTRARCURRENCY  ?>',
            method: 'post',
            dataType: 'json',
            data: {
                dataInicial:$("#dataInicial").val(),
                dataFinal:$("#dataFinal").val(),
                filtro: $("#filtro").val(),
                nregistros: $("#nregistros").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#lista-currency").html(json.html);
                        
                        $(".btn-popover-currency").each(function () {
                            let controle = $(this).attr("data-controle");
                            $(this).popover({
                                html: true,
                                trigger: "focus",
                                container: "body",
                                placement: "top",
                                title: "Transferência " + controle,
                                content: json.popover[controle]
                            });
                        });
                        
                    } else {
                        $("#lista-currency").html("<tr><td colspan='5' class='text-center'>"+json.mensagem+"</td></tr>");
                    }
                } catch (e) {
                    $("#lista-currency").html("<tr><td colspan='5' class='text-center'>"+e+"</td></tr>");
                }
            }
        });
    }
    
    function filtrarReais() {
        $("#lista-reais").html("<tr><td colspan='5' class='text-center'><img src='<?php echo IMAGES ?>loading.gif' /></td></tr>");
        $.ajax({
            url: '<?php echo URLBASE_CLIENT  . Utils\Rotas::R_CONTAS_EMPRESA_FILTRARBRL ?>',
            method: 'post',
            dataType: 'json',
            data: {
                dataInicial:$("#dataInicial").val(),
                dataFinal:$("#dataFinal").val(),
                filtro: $("#filtro").val(),
                nregistros: $("#nregistros").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#lista-reais").html(json.html);
                        
                        $(".btn-popover-brl").each(function () {
                            let controle = $(this).attr("data-controle");
                            $(this).popover({
                                html: true,
                                trigger: "focus",
                                container: "body",
                                placement: "top",
                                title: "Transferência " + controle,
                                content: json.popover[controle]
                            });
                        });
                    } else {
                        $("#lista-reais").html("<tr><td colspan='5' class='text-center'>"+json.mensagem+"</td></tr>");
                    }
                } catch (e) {
                    $("#lista-reais").html("<tr><td colspan='5' class='text-center'>"+e+"</td></tr>");
                }
            }
        });
    }
    
    function transferirCurrency() {
        $("#transferenciaContaBtnTransferirCurrency, #modalTransacaoConfirmarCurrency, #modalTransacaoCancelarCurrency").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_CONTAS_EMPRESA_TRANSFERIRCURRENCY ?>',
            method: 'post',
            dataType: 'json',
            data: {
                enderecoBitcoin: $("#enderecoBitcoinCurrency").val(),
                valor: $("#transferenciaContaValorCurrency").val(),
                descricao: $("#descricaoCurrency").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#modalTransacaoCancelarCurrency").prop("disabled", false).trigger("click");
                        showNotyAlert(json.mensagem, "s");
                        
                        $("#transferenciaContaNomeClienteDestinatarioCurrency").html("");
                        $("#transferenciaContaDestinatarioContainerCurrency").hide();
                        $("#transferenciaContaNaoEncontradoContainerCurrency").hide();
                        $("#saldobtcCurrency").text(json.saldo);
                        $("#transferenciaContaValorCurrency").text("0,00000000");
                        $("#transferenciaContaTotalCurrency").text("0,00000000");
                        $("#transferenciaContaEmailCurrency").val("");
                        $("#idClienteDestiantarioCurrency").val("0");
                        filtrar();
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#transferenciaContaBtnTransferirCurrency, #modalTransacaoConfirmarCurrency, #modalTransacaoCancelarCurrency").prop("disabled", false);
            }
        });
    }
    
    
    function transferirReais() {
        $("#transferenciaContaBtnTransferirReais, #modalTransacaoConfirmarReais, #modalTransacaoCancelarReais").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_CONTAS_EMPRESA_TRANSFERIRBRL ?>',
            method: 'post',
            dataType: 'json',
            data: {
                idClienteTo: $("#idClienteDestiantarioReais").val(),
                valor: $("#transferenciaContaValorReais").val(),
                descricao: $("#descricaoReais").val()
            },

            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#modalTransacaoCancelarReais").prop("disabled", false).trigger("click");
                        showNotyAlert(json.mensagem, "s");
                        
                        $("#transferenciaContaNomeClienteDestinatarioReais").html("");
                        $("#transferenciaContaDestinatarioContainerReais").hide();
                        $("#transferenciaContaNaoEncontradoContaineReaisr").hide();
                        $("#saldobrlReais").text(json.saldo);
                        $("#transferenciaContaValorReais").val("0,00");
                        $("#transferenciaContaTotalReais").text("0,00");
                        $("#transferenciaContaCarteiraReais").text("");
                        $("#idClienteDestiantarioReais").val("0");
                        filtrar();
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#transferenciaContaBtnTransferirReais, #modalTransacaoConfirmarReais, #modalTransacaoCancelarReais").prop("disabled", false);
            }
        });
    }
    
    
    function findClienteWallet() {
        $("#transferenciaContaBtnFindReais").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_REAIS_CLIENTES_FINDBYWALLET ?>',
            dataType: 'json',
            method: 'post',
            data: {
                carteira: $("#transferenciaContaCarteiraReais").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        if (json.cliente.id > 0) {
                            $("#idClienteDestiantarioReais").val(json.id);
                            $("#transferenciaContaDestinatarioContainerReais").show();
                            $("#transferenciaContaNaoEncontradoContainerReais").hide();
                            $("#transferenciaContaNomeClienteDestinatarioReais").html(json.cliente.nome);
                            $("#transferenciaContaBtnTransferirReais").prop("disabled", false);
                        } else {
                            
                        }
                    } else {
                        //alert(json.mensagem);
                            $("#idClienteDestiantarioReais").val(0);
                            $("#transferenciaContaNaoEncontradoContainerReais").show();
                            $("#transferenciaContaDestinatarioContainerReais").hide();
                            $("#transferenciaContaNomeClienteDestinatarioReais").html("");
                            $("#transferenciaContaBtnTransferirReais").prop("disabled", true);
                    }
                } catch (e) {
                    alert(e);
                }
                //$("#transferenciaContaBtnFind").prop("disabled", false);
            }
        });
    }
    
    function modalTransferirCurrency() {
        $("#transferenciaContaBtnTransferirCurrency").prop("disabled", true);
        $("#modalTransacaoCancelarCurrency").trigger("click");
        
        var endereco = $("#enderecoBitcoinCurrency").val();
        var descricao = $("#descricaoCurrency").val();
        var valor = parseFloat(($("#transferenciaContaValorCurrency").val().length > 0 ? $("#transferenciaContaValorCurrency").val().replace(",", ".") : 0));
        
        if (endereco.length <= 0 || descricao.length <= 0 || valor <= 0) {
            $("#transferenciaContaBtnTransferirCurrency").prop("disabled", false);
            
            showNotyAlert("Você precisa informar todos os parâmetros", "e");
        } else {
            $("#modalTransacaoCurrencyVolume").html($("#transferenciaContaValorCurrency").val().replace(",", "."));
            $("#modalTransacaoCurrencyAddress").html(endereco);
            $("#modalTransacaoCurrency").modal();
        }
    }
    
    
    function modalTransferirReais() {
        $("#transferenciaContaBtnTransferirReais").prop("disabled", true);
        $("#modalTransacaoCancelarReais").trigger("click");
        
        var idClienteTo = $("#idClienteDestiantarioReais").val();
        var descricao = $("#descricaoReais").val();
        var valor = parseFloat(($("#transferenciaContaValorReais").val().length > 0 ? $("#transferenciaContaValorReais").val().replace(",", ".") : 0));
        
        if (!idClienteTo > 0 || descricao.length <= 0 || valor <= 0) {
            $("#transferenciaContaBtnTransferirReais").prop("disabled", false);
            showNotyAlert("Você precisa informar todos os parâmetros", "e");
        } else {
            $("#modalTransacaoReaisValor").html($("#transferenciaContaValorReais").val().replace(",", "."));
            $("#modalTransacaoReaisCliente").html($("#transferenciaContaNomeClienteDestinatarioReais").html());
            $("#modalTransacaoReais").modal();
        }
    }
</script>


<div class="modal inmodal" id="modalTransacaoCurrency" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content animated bounceInRight">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                <i class="fa fa-bitcoin modal-icon"></i>
                <h4 class="modal-title">Confirmar transação</h4>
            </div>
            <div class="modal-body">
                <p>
                    Deseja realmente enviar o volume de <span id="modalTransacaoCurrencyVolume"></span> para <span id="modalTransacaoCurrencyAddress"></span>.
                </p>
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-white" data-dismiss="modal" id="modalTransacaoCancelarCurrency">Cancelar</button>
                <button type="button" class="btn btn-success" onclick="transferirCurrency();"  id="modalTransacaoConfirmarCurrency">Confirmar transação</button>
            </div>
        </div>
    </div>
</div>



<div class="modal inmodal" id="modalTransacaoReais" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content animated bounceInRight">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                <i class="fa fa-bitcoin modal-icon"></i>
                <h4 class="modal-title">Confirmar transação</h4>
            </div>
            <div class="modal-body">
                <p>
                    Deseja realmente enviar o valor de R$ <span id="modalTransacaoReaisValor"></span> para <span id="modalTransacaoReaisCliente"></span>.
                </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-white" data-dismiss="modal" id="modalTransacaoCancelarReais">Cancelar</button>
                <button type="button" class="btn btn-success" onclick="transferirReais();"  id="modalTransacaoConfirmarReais">Confirmar transação</button>
            </div>
        </div>
    </div>
</div>
