<?php

$idioma = new \Utils\PropertiesUtils("book", IDIOMA);
$moedas = (isset($_data["moedas"]) ? $_data["moedas"]  : null);

$dataInicial = new Utils\Data(date("d/m/Y"));
$dataFinal = new Utils\Data(date("d/m/Y"));
$dataInicial->subtrair(0,1);

$cliente = \Utils\Geral::getCliente();

if(!empty($cliente->moedaFavorita)){
    $moedaFavorita = $cliente->moedaFavorita;
} else {
    $moedaFavorita = 2;
}

$linkCliente = URLBASE_CLIENT . \Utils\Rotas::R_REGISTER . "/" . Utils\Criptografia::encriptyPostId($cliente->id);


$_data["idiomaMenu"] = $idioma;
?>

<?php Utils\Layout::append("inspina/metas", $_data) ?>
<?php Utils\Layout::append("inspina/scripts", $_data) ?>
<?php Utils\Layout::append("inspina/menu", $_data) ?>
<style>
    button.btn-success.dim.whatsapp{
        box-shadow: inset 0 0 0 #25d366, 0 5px 0 0 #25d366, 0 10px 5px #999999;
    }
    .btn-success.btn-outline.whatsapp {
        color: #25d366;
        border-color: #25d366;
    }
    .btn-success.whatsapp:hover {
        background-color: #128c7e;
    }

    button.btn-primary.dim.telegram{
        box-shadow: inset 0 0 0 #0088cc, 0 5px 0 0 #0088cc, 0 10px 5px #999999;
    }
    .btn-primary.btn-outline.telegram {
        color: #0088cc;
        border-color: #0088cc;
    }
    .btn-primary.telegram:hover {
        background-color: #97dcff;
    }

</style>

<div id="container">
    <!-- <div class="col-md-12 col-lg-2">
    </div> -->
    <!-- <div class="col-md-12 col-lg-8"> -->
        <div class="page_content">
            <div class="settings mtb15">
                <div class="container-fluid">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Link Para Compartilhamento</h5>
                            <div class="container">
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="row">
                                            <div class="alert alert-success m-t-md m-r-md">
                                                <span id="linkReferencia" style="word-wrap: break-word;"><?php echo $linkCliente ?></span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="row d-flex justify-content-center">
                                            <div class="col">
                                                <button class="btn btn-lg btn-outline dim btn-primary telegram  m-t-md " onclick="telegram();" ><i class="fa fa-telegram"></i></button>
                                            </div>
                                            <div class="col">
                                                <button class="btn btn-lg btn-outline dim btn-success whatsapp m-t-md " onclick="whatsapp();" ><i class="fa fa-whatsapp"></i></button>

                                            </div>
                                            <div class="col">
                                                <button class="btn btn-lg btn-outline dim btn-success m-t-md " onclick="facebook();" ><i class="fa fa-facebook-f"></i></button> 

                                            </div>
                                            <div class="col">
                                                <button class="btn btn-lg btn-outline dim btn-warning m-t-md " onclick="email();" ><i class="fa fa-envelope-o"></i></button> 

                                            </div>
                                            <div class="col">
                                                <button id="copyRef" class="btn btn-lg btn-outline dim btn-info m-t-md " data-clipboard-target="#linkReferencia"><i class="fa fa-copy"></i></button> 
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>

            <div class="settings mtb15">
                <div class="container-fluid">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Filtrar por Período</h5>
                                <div class="row">
                                    <div class="col-sm-4">
                                        <div class="form-group" id="datas">
                                            <label class="control-label">Período</label>
                                            <div class="input-daterange input-group full-width" id="datepicker">
                                                <input type="text" id="dataInicial" class=" form-control" name="dataInicial" value="<?php echo $dataInicial->formatar(\Utils\Data::FORMATO_PT_BR) ?>">
                                                <span class="input-group-addon">Até</span>
                                                <input type="text" id="dataFinal" class=" form-control" name="dataFinal" value="<?php echo $dataFinal->formatar(\Utils\Data::FORMATO_PT_BR) ?>">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-4">
                                        <div class="form-group">
                                            <label>Moedas</label>
                                            <select class="form-control custom-select" id="idMoeda">
                                                <?php foreach ($moedas as $m) { ?>
                                                    <option value="<?php echo \Utils\Criptografia::encriptyPostId($m->id) ?>" <?php echo $m->id == $moedaFavorita ? "selected" : ""; ?>><?php echo $m->simbolo . " - " . $m->nome ?></option>
                                                <?php } ?>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-sm-4">
                                        <div class="form-group">
                                            <label><?php echo "Registro" ?></label>
                                            <select class="form-control custom-select" id="registros">
                                                <option value="30">30</option>
                                                <option value="50">50</option>
                                                <option value="100">100</option>
                                                <option value="T"><?php echo "Todos" ?></option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-sm-12">
                                        <label>&nbsp;</label>
                                        <div class="form-group">
                                            <button type="button" class="btn btn-light full-width" onclick="filtrar()"><?php echo "Filtrar" ?>&nbsp;&nbsp;<i class="fa fa-filter"></i></button>
                                        </div>
                                    </div>
                                </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="settings mtb15">
                <div class="container-fluid">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Informações Gerais</h5>
                            <div class="row m-l-xs">
                                <div class="col-sm-1">
                                    <small class="stats-label">Moeda</small></br>
                                    <div id="moedaImg">-</div>
                                </div>
                                <div class="col-sm-12 col-md-2">
                                    <small class="stats-label">Qtd. Total Indicados</small>
                                    <h6 id="qtdReferencias">-</h4>
                                </div>
                                <div class="col-sm-12 col-md-2">
                                    <small class="stats-label">Total Depósitos</small>
                                    <h6 id="totalDepositos">-</h4>
                                </div>
                                <div class="col-sm-12 col-md-2">
                                    <small class="stats-label">Total Compra/Venda</small>
                                    <h6 id="totalCompraVenda">-</h4>
                                </div>
                                <div class="col-sm-12 col-md-2">
                                    <small class="stats-label">Total Saques</small>
                                    <h6 id="totalSaques">-</h4>
                                </div>
                                <div class="col-sm-12 col-md-2">
                                    <small class="stats-label">Total no Período</small>
                                    <h6><strong id="total">-</strong></h4>
                                </div>
                                <div class="col-sm-1">
                                    <div class="ibox-tools">
                                        <a class="collapse-link">
                                            <i class="fa fa-chevron-down"></i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>

            <div class="settings mtb15">
                <div class="container-fluid">
                    <div class="card">
                        <div class="card-body">
                        <h5 class="card-title">Saldos</h5>
                            <div class="row m-t-xs">            
                                <div class="col-lg-12">                 
                                    <div class="ibox float-e-margins ">                    
                                        <div class="list-items" id="detalhesReferencias">
                                            
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <!-- </div> -->
    <!-- <div class="col-md-12 col-lg-2">
    </div> -->
    
</div>

<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>
<script src="<?php echo TEMA; ?>js/plugins/datapicker/bootstrap-datepicker.js"></script>
<script src="<?php echo TEMA; ?>js/plugins/daterangepicker/daterangepicker.js"></script>
<script type="text/template" data-template="listindicados">
    <div class="ibox-content">
        <div class="row m-l-xs">
            <div class="col-sm-9">
                <small class="stats-label">Nome</small></br>
                <h4>${nomeIndicado}</h4>
            </div>
            <div class="col-sm-3">
                <small class="stats-label">Data Cadastro</small>
                <h4>${dataIndicado}</h4>
            </div>
        </div>
    </div>  
</script>
<script type="text/template" data-template="listitem">
    <div class="ibox-content">
        <div class="row m-l-xs">
            <div class="col-sm-2">
                <small class="stats-label">Indicação</small></br>
                <h4>${nome}</h4>
            </div>
            <div class="col-sm-2">
                <small class="stats-label">Data Cadastro</small>
                <h4>${data}</h4>
            </div>
            <div class="col-sm-2">
                <small class="stats-label">Depósito</small>
                <h4>${deposito}</h4>
            </div>
            <div class="col-sm-2">
                <small class="stats-label">Compra/Venda</small>
                <h4>${compraVenda}</h4>
            </div>
            <div class="col-sm-2">
                <small class="stats-label">Saque</small>
                <h4>${saque}</h4>
            </div>
            <div class="col-sm-2">
                <small class="stats-label">Total</small>
                <h4><strong>${totalTodos}</strong></h4>
            </div>
        </div>
    </div>  
</script>
<script>
      
    $(document).ready(function () {
        new Clipboard('#copyRef');
        $("#dataInicial, #dataFinal").datepicker({forceParse: false,format: 'dd/mm/yyyy'}).mask("99/99/9999");
        filtrar();
        
        $('#copyRef').click(function () {
            swal({
                title: "Compartilhe seu link!",
                text: "Seu link foi copiado!",
                icon: "success",
                type: "success",
                showCancelButton: false,
                closeOnConfirm: true,
                showLoaderOnConfirm: true,
                confirmButtonColor: "#18a689",
                buttons: true
            });
        });
    });
    
    
    function render(props) {
        return function(tok, i) {
          return (i % 2) ? props[tok] : tok;
        };
      }
    
    function filtrar() {    
        $("#detalhesReferencias").html("<div class='text-center'><img src='<?php echo IMAGES ?>loading.gif' /></div>");
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_REFERENCIA_LISTAR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                dataInicial : $("#dataInicial").val(),
                dataFinal : $("#dataFinal").val(),
                registros : $("#registros").val(),
                moeda: $("#idMoeda").val()
            },
            success: function (json) {                 
                try {
                    if (json.sucesso) { 
                         $("#detalhesReferencias").html("");
                         $(".list-indicados").html("");
                       
                         $("#moedaImg").html(' <img src="' + json.moedaImg +'" style="width: 25px; height: 25px;">');
                         $("#qtdReferencias").html(json.qtdReferencias);
                         $("#totalDepositos").html(json.totalDepositos);
                         $("#totalCompraVenda").html(json.totalCompraVenda);
                         $("#totalSaques").html(json.totalSaques);
                         $("#total").html(json.total);
                         
                        for (var i = 0; i < json.dados.length; i++) {
                           var items = [{
                                  nome: json.dados[i].nomeReferencia,
                                  data: json.dados[i].dataCadastro,
                                  deposito:  json.dados[i].valorDeposito,
                                  compraVenda: json.dados[i].valorCompraVenda,
                                  saque: json.dados[i].valorSaque,
                                  totalTodos: json.dados[i].total                                  
                                }];
                           
                           var itemTpl = $('script[data-template="listitem"]').text().split(/\$\{(.+?)\}/g);
                           
                           $('.list-items').append(items.map(function(item) {
                                return itemTpl.map(render(item    )).join('');
                            }));
                        }
                        
                        for (var i = 0; i < json.indicados.length; i++) {
                           var items = [{
                                  nomeIndicado: json.indicados[i].nomeReferencia,
                                  dataIndicado: json.indicados[i].dataCadastro
                                }];
                           
                           var itemTpl = $('script[data-template="listindicados"]').text().split(/\$\{(.+?)\}/g);
                           
                           $('.list-indicados').append(items.map(function(item) {
                                return itemTpl.map(render(item    )).join('');
                            }));
                        }
                     
                    } else {
                        $("#detalhesReferencias").html("<div class='text-center'><img src='<?php echo IMAGES ?>loading.gif' /></div>");   
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                   $("#detalhesReferencias").html("<div class='text-center'><img src='<?php echo IMAGES ?>loading.gif' /></div>");
                   showNotyAlert(json.mensagem, "e");
                }
            }
        });
    }
    

    function whatsapp() {
        window.open('https://wa.me/?text=<?= "Acesse e cadastre" . ' ' . $linkCliente; ?>', '_blank'); 
    }
    
    function facebook() {
        window.open('https://www.facebook.com/sharer.php?u=<?= $linkCliente; ?>', '_blank'); 
    }
    
    function telegram() {
        window.open('https://telegram.me/share/url?url=<?= $linkCliente; ?>&text=ExchangeCX - Compartilhe seu link referência.', '_blank');
    }
    
    function email() {
        window.open('mailto:<?= $cliente->email ?>?&subject=ExchangeCX&body=Compartilhe%20seu%20link%20de%20referência. - <?= $linkCliente ?>', '_blank');
    }
    
</script>


<?php Utils\Layout::append("mensage_text", $_data) ?>

