<?php
$estabelecimentos = isset($_data["estabelecimentos"]) ? $_data["estabelecimentos"] : Array();
$pontoPdv = isset($_data["ponto"]) ? $_data["ponto"] : new \Models\Modules\Cadastro\PontoPdv();
$moeda = \Modules\principal\Controllers\Principal::getCurrency();
$chavePdv = isset($_data["chave"]) ? $_data["chave"] : new \Models\Modules\Cadastro\ChavePdv();


$salvar = false;

if ($pontoPdv->id > 0) {
    if (\Models\Modules\Acesso\RotinaRn::validar(\Utils\Rotas::R_PONTOSPDVS, \Utils\Constantes::EDITAR)) {
        $salvar = true;
    }
} else {
    if (\Models\Modules\Acesso\RotinaRn::validar(\Utils\Rotas::R_PONTOSPDVS, \Utils\Constantes::CADASTRAR)) {
        $salvar = true;
    }
}

?>
<?php Utils\Layout::append("inspina/metas", $_data) ?>

<?php Utils\Layout::append("inspina/scripts", $_data) ?>


<?php Utils\Layout::append("inspina/menu", $_data) ?>

<div class="content-wrapper">
  <div class="row wrapper border-bottom page-heading" style="background: linear-gradient(to right, #fff, <?php echo $moeda->mainColor ?>) !important;">
    <div class="col-lg-9">
      <ol class="breadcrumb m-t-md" style="background-color: transparent !important;">
          <li>
            Pontos PDV
          </li>
          <li class="active">
              <strong>Estabelecimentos</strong>
          </li>
      </ol>
    </div>
    <div class="col-lg-3">
    <?php Utils\Layout::append("inspina/flags", $_data) ?>
    </div>
  </div>
</div>
    
<div>
<br>

    <!-- Main content -->
    <section class="content">

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <?php Utils\Layout::append("mensagem", $_data)?>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <input type="hidden" id="id" value="<?php echo Utils\Criptografia::encriptyPostId($pontoPdv->id)?>" />
                        <div class="row">
                            <div class="col col-lg-12">
                                <div class="form-group">
                                    <label>Descrição do Ponto<strong>*</strong></label>
                                    <input type="text" class="form-control" id="descricao" value="<?php echo $pontoPdv->descricao ?>" maxlength="200" />
                                </div>
                            </div>
                            
                        </div>
                        
                        
                        <div class="row">
                            <div class="col col-lg-4">
                                <div class="form-group">
                                    <label>Url de Callback (Produção)</label>
                                    <input type="text" class="form-control" id="callbackProducao" value="<?php echo $pontoPdv->callbackProducao ?>" maxlength="200" />
                                </div>
                            </div>
                            <div class="col col-lg-4">
                                <div class="form-group">
                                    <label>Url de Callback (Homologação)</label>
                                    <input type="text" class="form-control" id="callbackHomologacao" value="<?php echo $pontoPdv->callbackHomologacao ?>" maxlength="200" />
                                </div>
                            </div>
                            <div class="col col-lg-4">
                                <div class="form-group">
                                    <label>Comissão cobrada pelo PDV por cada invoice</label>
                                    <div class="input-group">
                                        <input type="text" class="form-control" id="comissaoPdv" value="<?php echo number_format($pontoPdv->comissaoPdv, 8, ",", "") ?>" />
                                        <div class="input-group-addon">
                                            <select name="tipoComissaoPdv" id="tipoComissaoPdv">
                                                <option value="p" <?php echo ($pontoPdv->tipoComissaoPdv == "p" ? "selected" : "") ?> >%</option>
                                                <option value="v" <?php echo ($pontoPdv->tipoComissaoPdv == "v" ? "selected" : "") ?> >BTC</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col col-lg-12">
                                <div class="input-group m-b">
                                    <span class="input-group-addon bg-primary"> 
                                        <input type="checkbox" id="habilitarSaqueAutomatico" <?php echo ($pontoPdv->habilitarSaqueAutomatico? "checked" : "") ?>> <label for="habilitarSaqueAutomatico">Habilitar saque automático </label>
                                    </span> 
                                    <input type="text" class="form-control" id="walletSaqueAutomatico" placeholder="Wallet para saque automático" value="<?php echo $pontoPdv->walletSaqueAutomatico ?>" maxlength="200" />
                                </div>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col col-lg-12">
                                <div class="form-group">
                                    <label>
                                        Estabelecimento<strong>*</strong>
                                    </label>
                                    <select class="form-control" id="idEstabelecimento">
                                        <option value="<?php echo Utils\Criptografia::encriptyPostId(0)?>">Selecione um estabelecimento</option>
                                        <?php 
                                        foreach ($estabelecimentos as $estabelecimento) {
                                            ?>
                                            <option value="<?php echo Utils\Criptografia::encriptyPostId($estabelecimento->id)?>" <?php echo ($pontoPdv->idEstabelecimento == $estabelecimento->id ? "selected='true'" : "")?> >
                                                <?php echo $estabelecimento->nome ?>
                                            </option>
                                            <?php
                                        }
                                        ?>
                                    </select>
                                </div>
                            </div>
                        </div>
                        
                        
                        <br><br>
                        <div class="row rowChave" >
                            <div class="col col-lg-12">
                                <h4>Configure uma API Key para visualizar os relatórios e informações dos PDVs.</h4>
                            </div>
                        </div>
                        <div class="row rowChave" >
                            <div class="col col-lg-6">
                                API Key: <strong id="apikey"><?php echo ($chave != null && $chave->id > 0 ? "*********" : "Você ainda não criou uma API Key")?></strong> <br>
                                API Key Homologacao: <strong id="apikeyh"><?php echo ($chave != null && $chave->id > 0 ? "*********" : "Você ainda não criou uma API Key")?></strong>
                            </div>
                            <div class="col col-lg-4">
                                <button class="btn btn-primary" onclick="modalGerarApiKey();" id="btnGerarApiKey">
                                    Gerar uma nova API Key
                                </button>
                            </div>
                            
                            <div class="col col-lg-2 text-center">
                                <button class="btn btn-success"  onclick="modalMostrarApiKey();">
                                    Mostrar Key
                                </button>
                            </div>
                        </div>
                        
                        <br><br>
                        <div class="row">
                            <div class="col col-lg-3 text-center" >
                                <button class="btn btn-danger rowChave" onclick="modalDesativarKey();" >
                                    Desativar Chave
                                </button>
                            </div>
                            <div class="col col-lg-6">
                                <div class="form-actions text-center">
                                    <button class="btn btn-default" onclick="cancelar();" id="btnCancelar">
                                        Cancelar
                                    </button>
                                    
                                    <?php if ($salvar) { ?>
                                    <button class="btn btn-primary" onclick="salvar();" id="btnSalvar">
                                        Salvar
                                    </button>
                                    <?php } ?>
                                </div>
                            </div>
                        </div>
                        
                        
                    </div>
                    <!-- /.panel-body -->

                </div>
            </div>

        </div>

    </section>
    
    <div class="clearfix"></div>
</div>

<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>

<script>
    $(document).ready(function () {
        
        <?php
        if ($pontoPdv->id > 0) {
            ?>
            $(".rowChave").show();        
            <?php
        } else {
            ?>
            $(".rowChave").hide();        
            <?php
        }
        ?>
                
                
        $("#comissaoPdv").keydown(function (event) {
            $(this).val(currency($(this).val(), 8, 8, event.keyCode));
            
            event.preventDefault();
        });
        
    });
    
    function cancelar() {
        location = "<?php echo URLBASE_CLIENT . Utils\Rotas::R_PONTOSPDVS ?>";
    }
    
    function salvar() {
        $("#btnCancelar, #btnSalvar").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT  . Utils\Rotas::R_PONTOSPDVS_SALVAR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                id: $("#id").val(),
                descricao: $("#descricao").val(),
                callbackHomologacao: $("#callbackHomologacao").val(),
                callbackProducao: $("#callbackProducao").val(),
                idEstabelecimento: $("#idEstabelecimento").val(),
                walletSaqueAutomatico: $("#walletSaqueAutomatico").val(),
                habilitarSaqueAutomatico: ($("#habilitarSaqueAutomatico").is(":checked") ? 1 : 0),
                comissaoPdv :$("#comissaoPdv").val(),
                tipoComissaoPdv: $("#tipoComissaoPdv").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        showNotyAlert(json.mensagem, "s");
                        $("#id").val(json.id);
                        $(".rowChave").show();
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#btnCancelar, #btnSalvar").prop("disabled", false);
            }
        });
    }
    
    
    function modalGerarApiKey() {
        $.ajax({
            url: '<?php echo URLBASE_CLIENT  . Utils\Rotas::R_PONTOSPDVS_CHAVES_PREPARAR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#modalGerarApiKeyPin").val("");
                        $("#modalGerarApiKey").modal();
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
            }
        });
    }
    
    function gerarApiKey() {
        $("#modalGerarApiKeyCancelar, #modalGerarApiKeyConfirmar").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT  . Utils\Rotas::R_PONTOSPDVS_CHAVES_GERAR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                codigo: $("#id").val(),
                pin: $("#modalGerarApiKeyPin").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        showNotyAlert(json.mensagem, "s");
                        $("#modalGerarApiKeyCancelar").prop("disabled", false).trigger("click");
                        $("#apikey").html(json.chave);
                        $("#apikeyh").html(json.chaveh);
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch(e) {
                    showNotyAlert(e, "e");
                }
                $("#modalGerarApiKeyCancelar, #modalGerarApiKeyConfirmar").prop("disabled", false);
            }
        });
    }
    
    
    function modalMostrarApiKey() {
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_PONTOSPDVS_CHAVES_PREPARAR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#modalVerApiKeyPin").val("");
                        $("#modalVerApiKey").modal();
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
            }
        });
    }
    
    function mostrarApiKey() {
        $("#modalVerApiKeyCancelar, #modalVerApiKeyConfirmar").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_PONTOSPDVS_CHAVES_MOSTRAR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                codigo: $("#id").val(),
                pin: $("#modalVerApiKeyPin").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#modalVerApiKeyCancelar").prop("disabled", false).trigger("click");
                        $("#apikey").html(json.chave);
                        $("#apikeyh").html(json.chaveh);
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch(e) {
                    showNotyAlert(e, "e");
                }
                $("#modalVerApiKeyCancelar, #modalVerApiKeyConfirmar").prop("disabled", false);
            }
        });
    }
    
    function modalDesativarKey() {
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_PONTOSPDVS_CHAVES_PREPARAR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#modalDesativarApiKeyPin").val("");
                        $("#modalDesativarApiKey").modal();
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
            }
        });
    }
    
    function desativarApiKey() {
        $("#modalDesativarApiKeyCancelar, #modalDesativarApiKeyConfirmar").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_PONTOSPDVS_CHAVES_DESATIVAR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                codigo: $("#id").val(),
                pin: $("#modalDesativarApiKeyPin").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#modalDesativarApiKeyCancelar").prop("disabled", false).trigger("click");
                        $("#apikey").html("Você ainda não criou uma API Key");
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch(e) {
                    showNotyAlert(e, "e");
                }
                $("#modalDesativarApiKeyCancelar, #modalDesativarApiKeyConfirmar").prop("disabled", false);
            }
        });
    }
</script>




<div class="modal inmodal" id="modalGerarApiKey" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content animated bounceInRight">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                <i class="fa fa-bitcoin modal-icon"></i>
                <h4 class="modal-title">Gerar API Key</h4>
            </div>
            <div class="modal-body">
                <p>
                    Para gerar uma nova chave de acesso é necessário informar o seu PIN cadastrado.
                </p>
                
                <div class="form-group">
                    <label>Informe o seu PIN: </label> 
                    <input type="text"  class="form-control" id="modalGerarApiKeyPin">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-white" data-dismiss="modal" id="modalGerarApiKeyCancelar">Cancelar</button>
                <button type="button" class="btn btn-success" onclick="gerarApiKey()();"  id="modalGerarApiKeyConfirmar">Gerar Chave</button>
            </div>
        </div>
    </div>
</div>



<div class="modal inmodal" id="modalVerApiKey" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content animated bounceInRight">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                <i class="fa fa-bitcoin modal-icon"></i>
                <h4 class="modal-title">Visualizar API Key</h4>
            </div>
            <div class="modal-body">
                <p>
                    Para visualizar a API Key é necessário informar o seu PIN cadastrado.
                </p>
                
                <div class="form-group">
                    <label>Informe o seu PIN: </label> 
                    <input type="text"  class="form-control" id="modalVerApiKeyPin">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-white" data-dismiss="modal" id="modalVerApiKeyCancelar">Cancelar</button>
                <button type="button" class="btn btn-success" onclick="mostrarApiKey();"  id="modalVerApiKeyConfirmar">Validar</button>
            </div>
        </div>
    </div>
</div>


<div class="modal inmodal" id="modalDesativarApiKey" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content animated bounceInRight">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                <i class="fa fa-bitcoin modal-icon"></i>
                <h4 class="modal-title">Visualizar API Key</h4>
            </div>
            <div class="modal-body">
                <p>
                    Para cancelar a API Key é necessário informar o seu PIN cadastrado.
                </p>
                
                <div class="form-group">
                    <label>Informe o seu PIN: </label> 
                    <input type="text"  class="form-control" id="modalDesativarApiKeyPin">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-white" data-dismiss="modal" id="modalDesativarApiKeyCancelar">Cancelar</button>
                <button type="button" class="btn btn-success" onclick="desativarApiKey();"  id="modalDesativarApiKeyConfirmar">Desativar Key</button>
            </div>
        </div>
    </div>
</div>