<?php
$clientes = isset($_data["clientes"]) ? $_data["clientes"] : Array();
$adm = (\Utils\Geral::isUsuario() || \Utils\Geral::getLogado()->tipo == Utils\Constantes::ADMINISTRADOR);
$moeda = \Modules\principal\Controllers\Principal::getCurrency();

$estabelecimentos = (isset($_data["estabelecimentos"]) ? $_data["estabelecimentos"] : Array());


$cliente = Utils\Geral::getCliente();
$mostrarBotaoResgatar = (Utils\Geral::isCliente() && ($cliente->statusResgatePdv > 0));
?>
<?php Utils\Layout::append("inspina/metas", $_data) ?>

<?php Utils\Layout::append("inspina/scripts", $_data) ?>


<?php Utils\Layout::append("inspina/menu", $_data) ?>

<div class="content-wrapper">
  <div class="row wrapper border-bottom page-heading" style="background: linear-gradient(to right, #fff, <?php echo $moeda->mainColor ?>) !important;">
    <div class="col-lg-9">
      <ol class="breadcrumb m-t-md" style="background-color: transparent !important;">
          <li class="active">
              <strong>Estabelecimentos</strong>
          </li>
      </ol>
    </div>
    <div class="col-lg-3">
    <?php Utils\Layout::append("inspina/flags", $_data) ?>
    </div>
  </div>
</div>
    
<div>

      
    <!-- Main content -->
    <section class="content">
<?php Utils\Layout::append("mensagem", $_data) ?>
        <div class="row">
                            

<div class="col-lg-12">
                <div class="wrapper wrapper-content animated fadeInUp">

                    <div class="ibox">
                        <div class="ibox-title">
                            <h5>Lista de estabelecimentos </h5>
                            <div class="ibox-tools">
                                
                                <?php if (\Models\Modules\Acesso\RotinaRn::validar(\Utils\Rotas::R_ESTABELECIMENTOS, \Utils\Constantes::CADASTRAR)) { ?>
                                <a class="btn btn-primary btn-xs" href="<?php echo URLBASE_CLIENT . Utils\Rotas::R_ESTABELECIMENTOS_CADASTRO ?>">
                                    <i class="fa fa-plus"></i> Cadastrar
                                </a>
                                <?php } ?>
                            </div>
                        </div>
                        
                        <div class="ibox-content">
                            
                            <?php if (Utils\Geral::isCliente()) { ?>
                            <br><br>
                            
                            <?php if ($mostrarBotaoResgatar) { ?>
                            <div class="row">
                                <div class="col col-lg-12 text-center">
                                    <button class="btn btn-primary" onclick="dialogResgatarSaldo();">
                                        Resgatar Saldo
                                    </button>
                                </div>
                            </div>
                            <?php } ?>
                         
                            <br><br>
                            <?php } ?>
                            
                            <div class="row">
                                <?php if ($adm) { ?>
                                <div class="col col-lg-6">
                                    <div class="form-group">
                                        <label>Cliente</label>
                                        <select class="form-control" id="idCliente" onchange="filtrar();">
                                            <option value="0">Todos os clientes</option>
                                            <?php 
                                                foreach ($clientes as $cliente) {
                                                    ?>
                                                    <option value="<?php echo Utils\Criptografia::encriptyPostId($cliente->id) ?>"><?php echo $cliente->nome ?></option>
                                                    <?php
                                                }
                                            ?>
                                        </select>
                                    </div>
                                </div>
                                <?php } ?>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <div class="input-group">
                                        <input type="text" class="input-sm form-control" id="filtro"> 
                                        <span class="input-group-btn">
                                            <button type="button" class="btn btn-sm btn-primary" onclick="filtrar();"> Filtrar</button> 
                                        </span>
                                    </div>
                                </div>
                            </div>


                            

                            <div class="project-list">

                                <div class="dd" >
                                    <ol class="dd-list" id="lista">
                                        
                                    </ol>
                                </div>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>






        </div>

    </section>
    
    <div class="clearfix"></div>
</div>

<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>

<script>
    $(document).ready(function () {
        
        $("#modalResgateSaldoValor").keydown(function (event) {
            if (event.keyCode !== 9) {
                $(this).val(currency($(this).val(), 8, 8, event.keyCode));
                event.preventDefault();
            }
        });
        
        $("#modalResgateSaldoEstabelecimento").change(function () {
            getResumoEstabelecimento();
        });
        
        $("#modalResgateSaldoValor").keyup(function () {
            calcularTaxa();
        });
        
        filtrar();
    });
    
    function filtrar() {
        $("#lista").html("<li class='dd-item'><div class=dd-handle' ><div class='row'><div class='col-lg-12 text-center'><img src='<?php echo IMAGES ?>loading.gif' /></div></div></div></li>");
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_ESTABELECIMENTOS_LISTAR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                <?php if ($adm) { ?>
                idCliente: $("#idCliente").val(),
                <?php } ?>
                filtro: $("#filtro").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#lista").html(json.html);
                    } else {
                        $("#lista").html("<li class='dd-item'><div class=dd-handle' ><div class='row'><div class='col-lg-12 text-center'>"+json.mensagem+"</div></div></div></li>");
                    }
                } catch (e) {
                    $("#lista").html("<li class='dd-item'><div class=dd-handle' ><div class='row'><div class='col-lg-12 text-center'>"+e+"</div></div></div></li>");
                }
            }
        });
    }
    
    function alterarStatusAtivo(codigo) {
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_ESTABELECIMENTOS_ALTERARSTATUS ?>',
            method: 'post',
            dataType: 'json',
            data: {
                id: codigo
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        filtrar();
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
            }
        });
    }
    
    function dialogExcluir(codigo) {
        $("#modalExclusaoCodigo").val(codigo);
        $("#modalExclusao").modal();
    }
    
    function excluir() {
        $("#modalExclusaoClose, #modalExclusaoExcluir").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_ESTABELECIMENTOS_EXCLUIR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                id: $("#modalExclusaoCodigo").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        showNotyAlert(json.mensagem, "s");
                        $("#modalExclusaoClose").prop("disabled", false).trigger("click");
                        filtrar();
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#modalExclusaoClose, #modalExclusaoExcluir").prop("disabled", false);
            }
        });
    }
    
    function mostrarCarteiras(estabelecimento) {
        console.log($("#input-pesquisa-"+estabelecimento).val());
        $("#btn-show-"+estabelecimento).hide();
        $("#btn-hide-"+estabelecimento).show();
        $("#wallets-loader-"+estabelecimento).show();
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_ESTABELECIMENTOS_WALLETS_LISTAR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                estabelecimento: estabelecimento,
                filtro: $("#input-pesquisa-"+estabelecimento).val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#estabelecimento-"+estabelecimento + " ol ").remove();
                        $("#estabelecimento-"+estabelecimento).append(json.html);
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#wallets-loader-"+estabelecimento).hide();
            }
        });
    }
    
    function enviarCallback(wallet) {
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_ESTABELECIMENTOS_WALLETS_CALLBACK ?>',
            method: 'post',
            dataType: 'json',
            data: {
                wallet: wallet
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#modalRetornoCallback").modal();
                        $("#modalRetornoCallbackConteudo").html(json.resultado);
                        $("#modalRetornoCallbackURL").html(json.url);
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                
            }
        });
    }
    
    function esconderCarteiras(estabelecimento) {
        $("#btn-show-"+estabelecimento).show();
        $("#btn-hide-"+estabelecimento).hide();
        $("#wallets-"+estabelecimento).remove();
    }
    
    
    function calcularTaxa() {
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_ESTABELECIMENTOS_RESGATE_CALCULARTAXA ?>',
            method: 'post',
            dataType: 'json',
            data: {
                estabelecimento: $("#modalResgateSaldoEstabelecimento").val(),
                valor: $("#modalResgateSaldoValor").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#modalResgateSaldoTaxa").val(json.taxa.replace(".", ","));
                    } else {
                        //showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
            }
        });
    }
    
    <?php if (Utils\Geral::isCliente()) { ?>

    function dialogResgatarSaldo() {
        $("#modalResgateSaldo").modal();
        $("#modalResgateSaldoEstabelecimento").children("option").first().prop("selected", true).trigger("change");
    }

    function getResumoEstabelecimento() {
        $("#modalResgateSaldoResgatar, #modalResgateSaldoClose").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_ESTABELECIMENTO_DADOS_RESUMO ?>',
            method: 'post',
            dataType: 'json',
            data: {
                estabelecimento: $("#modalResgateSaldoEstabelecimento").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#modalResgateSaldoQtdClientes").html(json.clientes);
                        $("#modalResgateSaldoQtdWallets").html(json.wallets);
                        $("#modalResgateSaldoAmount").html(json.saldo);
                        $("#modalResgateSaldoValor").val(json.saldo.replace(".", ","));
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#modalResgateSaldoResgatar, #modalResgateSaldoClose").prop("disabled", false);
            }
        });
        
    }

    function resgatarSaldo() {
        $("#modalResgateSaldoResgatar, #modalResgateSaldoClose").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_ESTABELECIMENTO_SALDO_RESGATAR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                estabelecimento: $("#modalResgateSaldoEstabelecimento").val(),
                valor: $("#modalResgateSaldoValor").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        filtrar();
                        $("#modalResgateSaldoClose").prop("disabled", false).trigger("click");
                        showNotyAlert(json.mensagem, "s");
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#modalResgateSaldoResgatar, #modalResgateSaldoClose").prop("disabled", false);
            }
        });
        
    }

    <?php } ?>
</script>


<div class="modal fade" id="modalExclusao" tabindex="-1" role="dialog" aria-labelledby="modalExclusao" aria-hidden="true" >
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="modalExclusaoLabel">Excluir Estabelecimento</h4>
            </div>
            <div class="modal-body">
                <input type="hidden" id="modalExclusaoCodigo" />
                <div class="row">
                    <div class="col col-lg-12">
                        Deseja realmente excluir o estabelecimento?
                    </div>
                </div>
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="modalExclusaoClose" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-danger" onclick="excluir();" id="modalExclusaoExcluir" >Excluir</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>


<div class="modal fade" id="modalRetornoCallback" tabindex="-1" role="dialog" aria-labelledby="modalRetornoCallback" aria-hidden="true" >
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="modalRetornoCallbackLabel">Retorno do Callback</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col col-lg-12">
                        <h4 id="modalRetornoCallbackURL" ></h4>
                        <div id="modalRetornoCallbackConteudo" style="white-space: pre-wrap; height: 400px; overflow-y: scroll;">
                            
                        </div>
                    </div>
                </div>
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="modalRetornoCallbackClose" data-dismiss="modal">Fechar</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>



<div class="modal fade" id="modalResgateSaldo" tabindex="-1" role="dialog" aria-labelledby="modalResgateSaldo" aria-hidden="true" >
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="modalResgateSaldoLabel">Resgatar saldo</h4>
            </div>
            <div class="modal-body">
                
                <div class="row">
                    <div class="col col-lg-12">
                        <div class="form-group">
                            <label>Estabelecimento</label>
                            <select class="form-control" id="modalResgateSaldoEstabelecimento">
                                <?php foreach ($estabelecimentos as $estabelecimento) {
                                    ?>
                                    <option value="<?php echo Utils\Criptografia::encriptyPostId($estabelecimento->id) ?>"><?php echo $estabelecimento->nome ?></option>
                                    <?php
                                }?>
                            </select>
                        </div>
                    </div>
                </div>
                
                <div class="row">
                    <div class="col col-lg-4">
                        <div class="widget style1 blue-bg">
                            <div class="row">
                                <div class="col col-lg-12 text-center">
                                    <strong>Clientes</strong>
                                </div>
                            </div>
                            <div class="row vertical-align">
                                <div class="col-xs-3">
                                    <i class="fa fa-address-card-o fa-3x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <h2 class="font-bold" id="modalResgateSaldoQtdClientes"></h2>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col col-lg-4">
                        <div class="widget style1 navy-bg">
                            <div class="row">
                                <div class="col col-lg-12 text-center">
                                    <strong>Wallets</strong>
                                </div>
                            </div>
                            <div class="row vertical-align">
                                <div class="col-xs-3">
                                    <i class="fa fa-briefcase fa-3x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <h2 class="font-bold" id="modalResgateSaldoQtdWallets"></h2>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col col-lg-4">
                        <div class="widget style1 yellow-bg">
                            <div class="row">
                                <div class="col col-lg-12 text-center">
                                    <strong>Saldo disponível</strong>
                                </div>
                            </div>
                            <div class="row vertical-align">
                                <div class="col-xs-3">
                                    <i class="fa fa-bitcoin fa-3x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <h2 class="font-bold" id="modalResgateSaldoAmount"></h2>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
                
                <div class="row">
                    <div class="col col-md-6">
                        <div class="form-group">
                            <label>Valor a resgatar para a conta corrente: </label>
                            <input type="text"  class="form-control" id="modalResgateSaldoValor" />
                        </div>
                    </div>
                    <div class="col col-md-6">
                        <div class="form-group">
                            <label>Taxa cobrada pelo resgate: </label>
                            <input type="text"  class="form-control" id="modalResgateSaldoTaxa" readonly="true" />
                        </div>
                    </div>
                </div>
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="modalResgateSaldoClose" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-success" onclick="resgatarSaldo();" id="modalResgateSaldoResgatar" >Resgatar o Saldo</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>