<?php
$dataInicial = new Utils\Data(date("d/m/Y"));
$dataFinal = new Utils\Data(date("d/m/Y"));
$dataInicial->subtrair(0, 0, 30);

$moeda = Modules\principal\Controllers\Principal::getCurrency();


?>
<?php Utils\Layout::append("inspina/metas", $_data) ?>
<?php Utils\Layout::append("inspina/scripts", $_data) ?>
<?php Utils\Layout::append("inspina/menu", $_data) ?>
<div class="content-wrapper">
     <div class="row wrapper border-bottom page-heading" style="background: linear-gradient(to right, #fff, <?php echo $moeda->mainColor ?>) !important;">
        <div class="col-lg-10">
            <h2>Transferir <?php echo $moeda->nome ?></h2>
            <ol class="breadcrumb" style="background-color: transparent !important;">
                <li>
                    <a href="<?php echo Utils\Rotas::R_DASHBOARD ?>">Conta Corrente Empresa</a>
                </li>
                <li class="active">
                    <strong>Transferir <?php echo $moeda->nome ?></strong>
                </li>
            </ol>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-lg-12">
            
            


            <div class="tabs-container">

                <ul class="nav nav-tabs">
                    <li class="nav-item active" style="width: 33%; text-align: center;">
                        <a data-toggle="tab" href="#tab-1">
                            <img src="<?php echo IMAGES?>currencies/<?php echo $moeda->icone ?>" style="max-width: 20px; height: 20px;" />
                            Lançamento <?php echo $moeda->simbolo ?>
                        </a>
                    </li>
                    <li class="nav-item" style="width: 33%; text-align: center;">
                        <a data-toggle="tab" href="#tab-2">
                            <img src="<?php echo IMAGES?>currencies/BRL.png" style="max-width: 20px; height: 20px;" />
                            Lançamento Reais
                        </a>
                    </li>
                </ul>
                        
                <div class="tab-content">
                    <!--
                    <div class="ibox-content">
                    -->
                        <div id="tab-1" class="tab-pane active">
                            <div class="panel-body">
                                <input type="hidden" id="contaCurrencyId" />

                                <div class="row">
                                    <div class="col col-lg-12">
                                        <div class="form-group">
                                            <label>Descrição</label>
                                            <input type="text" class="form-control disabled-currency"  id="contaCurrencyDescricao" maxlength="2000"/>
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="row">
                                    <div class="col col-md-4">
                                        <div class="form-group">
                                            <label class="control-label">Movimento</label>
                                            <select class="form-control disabled-currency" id="contaCurrencyTipo" >
                                                <option value="<?php echo \Utils\Constantes::ENTRADA ?>" >Entrada</option>
                                                <option value="<?php echo \Utils\Constantes::SAIDA ?>" >Saída</option>
                                            </select>
                                        </div>
                                    </div>
                                    
                                    
                                    <div class="col col-md-4" >
                                        <div class="form-group">
                                            <label>Data</label>
                                            <input type="text" class="form-control disabled-currency" id="contaCurrencyData"  />
                                        </div>
                                    </div>
                                    <div class="col col-md-4">
                                        <div class="form-group">
                                            <label>Valor</label>
                                            <input type="text" class="form-control disabled-currency" id="contaCurrencyValor"  />
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="row">
                                    <div class="col col-xs-6 text-center">
                                        
                                        <?php if(\Models\Modules\Acesso\RotinaRn::validar(\Utils\Rotas::R_CONTAS_EMPRESA, \Utils\Constantes::CADASTRAR)) {  ?>
                                        <button type="button" class="btn btn-default" onclick="cadastroCurrency('<?php echo \Utils\Criptografia::encriptyPostId(0)?>');" id="btnCadastroCurrency">
                                            Iniciar novo cadastro
                                        </button>
                                        <?php }  ?>
                                    </div>
                                    <div class="col col-xs-6 text-center">
                                        <button type="button" class="btn btn-primary disabled-currency" onclick="salvarCurrency();" id="btnSalvarCurrency">
                                            Salvar
                                        </button>
                                    </div>
                                </div>
                                
                            </div>
                        </div>



                        <div id="tab-2" class="tab-pane">
                            <div class="panel-body">

                                <input type="hidden" id="contaBrlId" />
                                <div class="row">
                                    <div class="col col-lg-12">
                                        <div class="form-group">
                                            <label>Descrição</label>
                                            <input type="text" class="form-control disabled-brl"  id="contaBrlDescricao"/>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col col-lg-4" >
                                        <div class="form-group">
                                            <label class="control-label">Movimento</label>
                                            <select class="form-control disabled-brl" id="contaBrlTipo" >
                                                <option value="<?php echo \Utils\Constantes::ENTRADA ?>" >Entrada</option>
                                                <option value="<?php echo \Utils\Constantes::SAIDA ?>" >Saída</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col col-lg-4" >
                                        <div class="form-group">
                                            <label>Data</label>
                                            <input type="text" class="form-control disabled-brl" id="contaBrlData"  />
                                        </div>
                                    </div>
                                    <div class="col col-sm-4">
                                        <div class="form-group">
                                            <label>Valor</label>
                                            <input type="text" class="form-control disabled-brl" id="contaBrlValor"  />
                                        </div>
                                    </div>
                                </div>
                                
                                
                                <div class="row">
                                    <div class="col col-xs-6 text-center">
                                        <?php if(\Models\Modules\Acesso\RotinaRn::validar(\Utils\Rotas::R_CONTAS_EMPRESA, \Utils\Constantes::CADASTRAR)) {  ?>
                                        <button type="button" class="btn btn-default" onclick="cadastroBrl('<?php echo \Utils\Criptografia::encriptyPostId(0)?>');" id="btnCadastroBrl">
                                            Iniciar novo cadastro
                                        </button>
                                        <?php }  ?>
                                        
                                    </div>
                                    <div class="col col-xs-6 text-center">
                                        <button type="button" class="btn btn-primary disabled-brl" onclick="salvarBrl();" id="btnSalvarBrl">
                                            Salvar
                                        </button>
                                    </div>
                                </div>

                            </div>
                        </div>

                    <!--
                    </div>
                    -->
                </div>

            </div>
            
            
            
            <br><br><br>
            
            
            <div class="ibox float-e-margins">
                <div class="ibox-content">
                                    
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="row">

                                <div class="col col-md-2">
                                    <div class="form-group">
                                        <label class="control-label">Data Inicial</label>
                                        <input type="text" id="dataInicial" class="form-control" onchange="filtrar();"  value="<?php echo $dataInicial->formatar(\Utils\Data::FORMATO_PT_BR)?>" />
                                    </div>
                                </div>
                                <div class="col col-md-2">
                                    <div class="form-group">
                                        <label class="control-label">Data Final</label>
                                        <input type="text" id="dataFinal" class="form-control" onchange="filtrar();" value="<?php echo $dataFinal->formatar(\Utils\Data::FORMATO_PT_BR)?>" />
                                    </div>
                                </div>
                                <div class="col col-md-3">
                                    <div class="form-group">
                                        <label>Registros</label>
                                        <select class="form-control" id="nregistros" onchange="filtrar();">
                                            <option value="10">10 registros</option>
                                            <option value="20">20 registros</option>
                                            <option value="50">50 registros</option>
                                            <option value="100">100 registros</option>
                                            <option value="T">Todos</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col col-lg-5">
                                    <div class="form-group">
                                        <label>Filtro Geral</label>
                                        <input type="text" id="filtro" onkeyup="filtrar();" class="form-control" />
                                    </div>
                                </div>
                            </div>

                            <br><br>
                        </div>
                    </div>


                    <div class="row">
                        <div class="col-lg-12">        

                            <div class="tabs-container">

                                <ul class="nav nav-tabs ">
                                    <li class="nav-item active" style="width: 50%; text-align: center;">
                                        <a data-toggle="tab" href="#tab-2-1">
                                            <img src="<?php echo IMAGES?>currencies/<?php echo $moeda->icone ?>" style="max-width: 20px; height: 20px;" />
                                            Conta corrente <?php echo $moeda->simbolo ?>
                                        </a>
                                    </li>
                                    <li class="nav-item" style="width: 50%; text-align: center;">
                                        <a data-toggle="tab" href="#tab-2-2">
                                            <img src="<?php echo IMAGES?>currencies/BRL.png" style="max-width: 20px; height: 20px;" />
                                            Conta corrente reais
                                        </a>
                                    </li>
                                </ul>
                                <div class="tab-content">

                                    <div id="tab-2-1" class="tab-pane active">

                                        <div class="row">
                                            <div class="col col-lg-12 table-responsive" >

                                                <table class="table table-condensed table-stripped table-hover table-bordered">
                                                    <thead>
                                                        <tr>
                                                            <th class="col col-lg-1 text-center">
                                                                <strong>Controle</strong>
                                                            </th>
                                                            <th class="col col-lg-1 text-center">
                                                                <strong>Data</strong>
                                                            </th>
                                                            <th class="col col-lg-4">
                                                                <strong>Descrição</strong>
                                                            </th>
                                                            <th class="col col-lg-2 text-center">
                                                                <strong>Valor</strong>
                                                            </th>
                                                            <th class="col col-lg-2 text-center">
                                                                <strong>Log</strong>
                                                            </th>

                                                            <th class="col col-lg-1 text-center">
                                                                <strong>Editar</strong>
                                                            </th>
                                                            <th class="col col-lg-1 text-center">
                                                                <strong>Excluir</strong>
                                                            </th>
                                                        </tr>
                                                    </thead>

                                                    <tbody id="lista-currency">

                                                    </tbody>

                                                </table>
                                            </div>
                                        </div>

                                    </div>

                                    <div id="tab-2-2" class="tab-pane">
                                        <div class="row">
                                            <div class="col col-lg-12 table-responsive" >

                                                <table class="table table-condensed table-stripped table-hover table-bordered">
                                                    <thead>
                                                        <tr>
                                                            <th class="col col-lg-1 text-center">
                                                                <strong>Controle</strong>
                                                            </th>
                                                            <th class="col col-lg-1 text-center">
                                                                <strong>Data</strong>
                                                            </th>
                                                            <th class="col col-lg-4">
                                                                <strong>Descrição</strong>
                                                            </th>
                                                            <th class="col col-lg-2 text-center">
                                                                <strong>Valor</strong>
                                                            </th>
                                                            <th class="col col-lg-2 text-center">
                                                                <strong>Log</strong>
                                                            </th>

                                                            <th class="col col-lg-1 text-center">
                                                                <strong>Editar</strong>
                                                            </th>
                                                            <th class="col col-lg-1 text-center">
                                                                <strong>Excluir</strong>
                                                            </th>
                                                        </tr>
                                                    </thead>

                                                    <tbody id="lista-reais">

                                                    </tbody>

                                                </table>

                                            </div>
                                        </div>
                                    </div>

                                </div>

                            </div>

                            <div class="clearfix"></div>
                        </div>
                    </div><br><br>

                </div>
            </div>
            
            
        </div>
    </div>
   
    <?php if ($adm) { ?>
    <div class="row">

        <div class="col col-lg-3 col-lg-offset-9 text-center">
            <br><br>
            <a class="btn btn-default btn-lg" href="<?php echo URLBASE_CLIENT . Utils\Rotas::R_CONTACORRENTEBTC ?>/<?php echo Utils\Criptografia::encriptyPostId($cliente->id) ?>">
                Voltar
            </a>
            <br><br>
        </div>
    </div>
    <?php } ?>
    
    
    

<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>


<?php Utils\Layout::append("mensage_text", $_data) ?>

<script>
    $(document).ready(function () {
        
        filtrar();
        
        $("#dataInicial, #dataFinal").datepicker({format: 'dd/mm/yyyy'}).mask("99/99/9999");
        
        $("#contaCurrencyValor").keydown(function(event) {
            $(this).val(currency($(this).val(), 8, 8, event.keyCode));
            event.preventDefault();
        });
        
        $("#contaBrlValor").keydown(function(event) {
            $(this).val(currency($(this).val(), 2, 8, event.keyCode));
            event.preventDefault();
        });
        
        $("#contaCurrencyData, #contaBrlData").datepicker({format: 'dd/mm/yyyy'}).mask("99/99/9999");
        
        
        $(".disabled-currency, .disabled-brl").prop("disabled", true);
    });
    
    
    function filtrar() {
        filtrarCurrency();
        filtrarReais();
    }
    
    function filtrarCurrency() {
        $("#lista-currency").html("<tr><td colspan='7' class='text-center'><img src='<?php echo IMAGES ?>loading.gif' /></td></tr>");
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_CONTAS_EMPRESA_FILTRARCCCURRENCY ?>',
            method: 'post',
            dataType: 'json',
            data: {
                dataInicial:$("#dataInicial").val(),
                dataFinal:$("#dataFinal").val(),
                tipo:$("#tipo").val(),
                filtro: $("#filtro").val(),
                nregistros: $("#nregistros").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#lista-currency").html(json.html);
                        
                        $(".btn-popover-currency").each(function () {
                            let controle = $(this).attr("data-controle");
                            $(this).popover({
                                html: true,
                                trigger: "focus",
                                container: "body",
                                placement: "top",
                                title: "Controle " + controle,
                                content: json.popover[controle]
                            });
                        });
                        
                    } else {
                        $("#lista-currency").html("<tr><td colspan='7' class='text-center'>"+json.mensagem+"</td></tr>");
                    }
                } catch (e) {
                    $("#lista-currency").html("<tr><td colspan='7' class='text-center'>"+e+"</td></tr>");
                }
            }
        });
    }
    
    function filtrarReais() {
        $("#lista-reais").html("<tr><td colspan='7' class='text-center'><img src='<?php echo IMAGES ?>loading.gif' /></td></tr>");
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_CONTAS_EMPRESA_FILTRARCCBRL ?>',
            method: 'post',
            dataType: 'json',
            data: {
                dataInicial:$("#dataInicial").val(),
                dataFinal:$("#dataFinal").val(),
                tipo:$("#tipo").val(),
                filtro: $("#filtro").val(),
                nregistros: $("#nregistros").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#lista-reais").html(json.html);
                        
                        $(".btn-popover-brl").each(function () {
                            let controle = $(this).attr("data-controle");
                            $(this).popover({
                                html: true,
                                trigger: "focus",
                                container: "body",
                                placement: "top",
                                title: "Controle " + controle,
                                content: json.popover[controle]
                            });
                        });
                    } else {
                        $("#lista-reais").html("<tr><td colspan='7' class='text-center'>"+json.mensagem+"</td></tr>");
                    }
                } catch (e) {
                    $("#lista-reais").html("<tr><td colspan='7' class='text-center'>"+e+"</td></tr>");
                }
            }
        });
    }
    
    
    
    function cadastroCurrency(idContaCorrente) {
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_CONTAS_EMPRESA_CADASTROCURRENCY ?>',
            method: 'post',
            dataType: 'json',
            data: {
                id: idContaCorrente
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#contaCurrencyId").val(json.conta.id);
                        $("#contaCurrencyValor").val(json.conta.valor);
                        $("#contaCurrencyDescricao").val(json.conta.descricao);
                        $("#contaCurrencyData").val(json.conta.data);
                        if (json.conta.tipo !== null) {
                            $("#contaCurrencyTipo").val(json.conta.tipo);
                        } else {
                            $("#contaCurrencyTipo").val('<?php echo \Utils\Constantes::ENTRADA ?>');
                        }
                        $("a[href='#tab-1']").trigger("click");
                        $(".disabled-currency, #btnCadastroCurrency").prop("disabled", false);
                        
                        if (json.salvar) {
                            $("#btnSalvarCurrency").show();
                        } else {
                            $("#btnSalvarCurrency").hide();
                        }
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
            }
        });
    }
    
    function salvarCurrency() {
        $(".disabled-currency, #btnCadastroCurrency").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT  . Utils\Rotas::R_CONTAS_EMPRESA_SALVARCURRENCY ?>',
            method: 'post',
            dataType: 'json',
            data: {
                id: $("#contaCurrencyId").val(),
                data: $("#contaCurrencyData").val(),
                valor: $("#contaCurrencyValor").val(),
                descricao: $("#contaCurrencyDescricao").val(),
                tipo: $("#contaCurrencyTipo").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        filtrar();
                        
                        $("#contaCurrencyId").val("");
                        $("#contaCurrencyValor").val("");
                        $("#contaCurrencyDescricao").val("");
                        $("#contaCurrencyData").val("");
                        $("#contaCurrencyTipo").val('<?php echo \Utils\Constantes::ENTRADA ?>');
                        
                        showNotyAlert(json.mensagem, "s");
                        $(".disabled-currency").prop("disabled", true);
                        $("#btnCadastroCurrency").prop("disabled", false);
                    } else {
                        showNotyAlert(json.mensagem, "e");
                        $(".disabled-currency, #btnCadastroCurrency").prop("disabled", false);
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                    $(".disabled-currency, #btnCadastroCurrency").prop("disabled", false);
                }
                
            }
        });
    }
    
    
    
    
    function cadastroBrl(idContaCorrente) {
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_CONTAS_EMPRESA_CADASTROBRL ?>',
            method: 'post',
            dataType: 'json',
            data: {
                id: idContaCorrente
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#contaBrlId").val(json.conta.id);
                        $("#contaBrlValor").val(json.conta.valor);
                        $("#contaBrlDescricao").val(json.conta.descricao);
                        $("#contaBrlData").val(json.conta.data);
                        if (json.conta.tipo !== null) {
                            $("#contaBrlTipo").val(json.conta.tipo);
                        } else {
                            $("#contaBrlTipo").val('<?php echo \Utils\Constantes::ENTRADA ?>');
                        }
                        $("a[href='#tab-2']").trigger("click");
                        $(".disabled-brl, #btnCadastroBrl").prop("disabled", false);
                        
                        
                        
                        if (json.salvar) {
                            $("#btnSalvarBrl").show();
                        } else {
                            $("#btnSalvarBrl").hide();
                        }
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
            }
        });
    }
    
    function salvarBrl() {
        $(".disabled-brl, #btnCadastroBrl").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_CONTAS_EMPRESA_SALVARBRL ?>',
            method: 'post',
            dataType: 'json',
            data: {
                id: $("#contaBrlId").val(),
                data: $("#contaBrlData").val(),
                valor: $("#contaBrlValor").val(),
                descricao: $("#contaBrlDescricao").val(),
                tipo: $("#contaBrlTipo").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        filtrar();
                        
                        $("#contaBrlId").val("");
                        $("#contaBrlValor").val("");
                        $("#contaBrlDescricao").val("");
                        $("#contaBrlData").val("");
                        $("#contaBrlTipo").val('<?php echo \Utils\Constantes::ENTRADA ?>');
                        
                        showNotyAlert(json.mensagem, "s");
                        
                        $(".disabled-brl").prop("disabled", true);
                        $("#btnCadastroBrl").prop("disabled", false);
                    } else {
                        showNotyAlert(json.mensagem, "e");
                        $(".disabled-brl, #btnCadastroBrl").prop("disabled", false);
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                    $(".disabled-brl, #btnCadastroBrl").prop("disabled", false);
                }
                
            }
        });
    }
    
    
    function modalExcluirBrl(id) {
        $("#modalExcluirContaBrlId").val(id);
        $("#modalExcluirContaBrl").modal();
    }
    
    function excluirBrl() {
        $("#modalExcluirContaBrlFechar, #modalExcluirContaBrlExcluir").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_CONTAS_EMPRESA_EXCLUIRBRL ?>',
            method: 'post',
            dataType: 'json',
            data: {
                id: $("#modalExcluirContaBrlId").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        filtrar();
                        $("#modalExcluirContaBrlFechar").prop("disabled", false).trigger("click");
                        showNotyAlert(json.mensagem, "s");
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#modalExcluirContaBrlFechar, #modalExcluirContaBrlExcluir").prop("disabled", false);
            }
        });
    }
    
    
    
    
    function modalExcluirCurrency(id) {
        $("#modalExcluirContaCurrencyId").val(id);
        $("#modalExcluirContaCurrency").modal();
    }
    
    function excluirCurrency() {
        $("#modalExcluirContaCurrencyFechar, #modalExcluirContaCurrencyExcluir").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_CONTAS_EMPRESA_EXCLUIRCURRENCY ?>',
            method: 'post',
            dataType: 'json',
            data: {
                id: $("#modalExcluirContaCurrencyId").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        filtrar();
                        $("#modalExcluirContaCurrencyFechar").prop("disabled", false).trigger("click");
                        showNotyAlert(json.mensagem, "s");
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#modalExcluirContaCurrencyFechar, #modalExcluirContaCurrencyExcluir").prop("disabled", false);
            }
        });
    }
    
</script>


<div class="modal fade" id="modalExcluirContaCurrency" tabindex="-1" role="dialog" aria-labelledby="modalExcluirContaCurrency" aria-hidden="true" >
    <div class="modal-dialog" style="width: 800px;">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" >Excluir Lançamento</h4>
            </div>
            <div class="modal-body">
                <input type="hidden" id="modalExcluirContaCurrencyId" />
                <div class="row">
                    <div class="col col-lg-12" >
                        Tem certeza que deseja excluir o lançamento selecionado?
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="modalExcluirContaCurrencyFechar" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-danger" id="modalExcluirContaCurrencyExcluir" onclick="excluirCurrency();">Excluir</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>



<div class="modal fade" id="modalExcluirContaBrl" tabindex="-1" role="dialog" aria-labelledby="modalExcluirContaBrl" aria-hidden="true" >
    <div class="modal-dialog" style="width: 800px;">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" >Excluir Lançamento</h4>
            </div>
            <div class="modal-body">
                <input type="hidden" id="modalExcluirContaBrlId" />
                <div class="row">
                    <div class="col col-lg-12" >
                        Tem certeza que deseja excluir o lançamento selecionado?
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="modalExcluirContaBrlFechar" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-danger" id="modalExcluirContaBrlExcluir" onclick="excluirBrl();">Excluir</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

