

<script> 
    var idInterval = setInterval(layoutLara, 2000);
    
    function layoutLara(){
        var exec = $('.widget').css('padding', '0');
        
        if(exec !== null){
           clearInterval(idInterval); 
        }
    }

    var script = document.createElement("script");

    var dadosConfig = {
    codUser: "",
    codeLoja: "",
    idProduto: "",
    codCliente: 'Dy10CJ3qAwIL9IIiA0Bk', 

    bot_color: "#003759",
    bot_logo: "<?php echo IMAGES . "logo_cmc.png"?>",
    bot_name: "Suporte",
    bot_display: "block", //block ou none
    bot_load:false,
    timeParam: (new Date).getTime()
    };

    (function() 
    { 
        console.log('[Lara] - Iniciando V4 ...'); 
        script.setAttribute('id','lara-script');
        script.setAttribute('key', dadosConfig.codCliente);
        script.setAttribute('idProduto', dadosConfig.idProduto);
        script.setAttribute('jquery',"false");
        script.setAttribute('src', `https://bot.assistentelara.com.br/bot.js?key=${dadosConfig.codCliente}&version=${dadosConfig.timeParam}`); 

        document.head.appendChild(script);
    })();
</script>