<?php
use Utils\Rotas;
$moeda = \Modules\principal\Controllers\Principal::getCurrency();
$moedas = (isset($_data["moedas"]) ? $_data["moedas"] : 0);

$idioma = new \Utils\PropertiesUtils("cofre", 'IDIOMA');
$configuracao = \Models\Modules\Cadastro\ConfiguracaoRn::get();

$_data["idiomaMenu"] = $idioma;
?>
<style>
    .border-edit {
        border: 1px solid #1c84c6 !important;
    }
</style>
<?php Utils\Layout::append("inspina/metas", $_data) ?>
<?php Utils\Layout::append("inspina/scripts", $_data) ?>
<?php Utils\Layout::append("inspina/menu", $_data) ?>
<?php Utils\Layout::append("inspina/breadcrumb", $_data) ?>
<div class="wrapper wrapper-content  animated fadeInRight">
    
       
        <div class="row">
                 <div class="col-lg-12 col-xs-12">
                    <div class="alert alert-info">
                        <strong><strong><?php echo $idioma->getText("info1") ?></strong>
                        <ul>
                            <br>
                            <?php $cofre = new Modules\cofre\Controllers\Cofre(); ?>
                            <li><?php echo str_replace("{var1}", $configuracao->comissaoUsoCofre,$idioma->getText("info2")); ?></li>
                            <li><?php echo $idioma->getText("rendimentosPagoDiariamente") ?></li>
                            <li><?php echo str_replace("{var1}",$configuracao->prazoDiasSaqueCofre, $idioma->getText("info3")) ?></li>
                            <li><?php echo $idioma->getText("info4") ?></li>
                            <li><?php echo str_replace("{var1}",$configuracao->prazoDiasContratoCofre, $idioma->getText("info5")) ?></li>
                            <li><?php echo $idioma->getText("resgatePode") ?></li>
                            <li><?php echo $idioma->getText("rendimentoMoeda") ?></li>
                        </ul>
                    </div>
                 </div>
            </div>
 
            
            
    <div class="tabs-container">
        <ul class="nav nav-tabs">
            <?php
            foreach ($moedas as $dados) {
                $m = $dados["moeda"];
                ?>
                <li class="<?php echo ($m->id == 2 ? "active" : "") ?>">
                    <a data-toggle="tab" href="#tab-<?php echo $m->id ?>" >
                        <img src='<?php echo IMAGES ?>currencies/<?php echo $m->icone ?>' style="width: 25px; height: 25px; " />
                        <?php echo $idioma->getText("info6") ?> <?php echo $m->nome ?>
                    </a>
                </li>
                <?php
            }
            ?>
        </ul>


        <div class="tab-content">
            <?php
            foreach ($moedas as $dados) {
                $m = $dados["moeda"];
                $depositado = $dados["depositado"];
                $rendimento = $dados["rendimento"];
                $recebido = $dados["recebido"];
                $saldo = $dados["saldo"];
                ?>
                <div id="tab-<?php echo $m->id ?>" class="tab-pane <?php echo ($m->id == 2 ? "active" : "") ?>">
                    <div class="panel-body">
                        <div class="row" style="">
                            <div class="col-lg-6">
                                <div class="tumb text-center">
                                    </br>
                                    <img src="<?php echo IMAGES ?>profits.png" style="max-width: 100%; max-height: 200px;" />
                                </div>
                            </div>

                            <div class="col-lg-6 text-center">

                                <div class="row">
                                    <div class="col col-lg-12">
                                        <h4><?php echo $idioma->getText("cofreTextoSaldoCCMoeda") ?> <strong id="saldo-cc-<?php echo $m->id ?>"><?php echo number_format($saldo, 8, ".", "") ?></strong> <?php echo $m->simbolo ?></h4>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col col-md-4 m-b-xs">
                                        <h3><?php echo $idioma->getText("saldoAtual") ?> </h3>

                                        <div class="alert alert-warning">
                                            <h4>
                                                <img src="<?php echo IMAGES ?>currencies/<?php echo $m->icone ?>" style="max-width: 20px; max-height: 20px;"></br></br>
                                                <strong id="depositado-cofre-<?php echo $m->id ?>">
                                                    <?php echo number_format($depositado, 8, ".", "") ?>
                                                </strong>
                                            </h4>
                                        </div> 
                                    </div>
                                    <div class="col col-md-4 m-b-xs">
                                        <h3><?php echo $idioma->getText("info7") ?></h3>

                                        <div class="alert alert-success">
                                            <h4>
                                                <img src="<?php echo IMAGES ?>currencies/<?php echo $m->icone ?>" style="max-width: 20px; max-height: 20px;"> </br></br>
                                                <strong id="rendimento-cofre-<?php echo $m->id ?>">
                                                    <?php echo number_format($rendimento, 8, ".", "") ?>
                                                </strong>
                                            </h4>
                                        </div> 
                                    </div>
                                    <div class="col col-md-4 m-b-xs">
                                        <h3><?php echo $idioma->getText("info8") ?></h3>

                                        <div class="alert alert-success">
                                            <h4>
                                                <img src="<?php echo IMAGES ?>currencies/<?php echo $m->icone ?>" style="max-width: 20px; max-height: 20px;"> </br></br>
                                                <strong id="recebido-cofre-<?php echo $m->id ?>">
                                                    <?php echo number_format($recebido, 8, ".", "") ?>
                                                </strong>
                                            </h4>
                                        </div>

                                    </div>


                                </div>


                                <?php if (in_array($m->id, \Models\Modules\Cadastro\CofreRn::$MOEDAS_ACEITAS)) { ?>
                                    <div class="row">
                                        <div class="col col-md-6 m-b-xs">
                                            <button type="button" class="btn btn-warning full-width" id="btn-depositar" onclick="modalDepositar('<?php echo Utils\Criptografia::encriptyPostId($m->id) ?>');">
                                                <i class="fa fa-cloud-download"></i>&nbsp;&nbsp;<?php echo $idioma->getText("guardar") ?> <?php echo $m->nome ?>
                                            </button>

                                        </div>
                                        <div class="col col-md-6 m-b-xs">
                                            <button type="button" class="btn btn-success full-width" id="btn-sacar" onclick="modalSacar('<?php echo Utils\Criptografia::encriptyPostId($m->id) ?>');">
                                                <i class="fa fa-cloud-upload"></i>&nbsp;&nbsp;<?php echo $idioma->getText("sacar") ?> <?php echo $m->nome ?>
                                            </button>
                                        </div>

                                    </div>
                                <?php } ?>
                            </div>
                        </div>
                    </div>
                    <div class="row ">
                        <div class="col col-lg-12 ">
                            <br>
                            <h3><?php echo $idioma->getText("meusInvestimentos") ?></h3>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col col-lg-12 ">
                            
                            <div class="table-responsive">
                                <table class="table table-striped table-hover table-condensed table-bordered" style="font-size: 11px; background-color: #fff">
                                    <thead>
                                        <tr> 
                                            <th class="text-center"><?php echo $idioma->getText("moeda") ?></th>
                                            <th class="text-center"><?php echo $idioma->getText("cofreTabelaMeusInvestimentosControle") ?></th>
                                            <th class="text-center"><?php echo $idioma->getText("descricao") ?></th>
                                            <th class="text-center"><?php echo $idioma->getText("dataDeposito") ?></th>
                                            <th class="text-center"><?php echo $idioma->getText("saldoDepositado") ?></th>
                                            <th class="text-center"><?php echo $idioma->getText("saldoRendimentos") ?></th>
                                            <th class="text-center"><?php echo $idioma->getText("saldoTotal") ?></th>
                                            <th class="text-center"><?php echo $idioma->getText("vencimentoContrato") ?></th>
                                            <th class="text-center">Status</th>
                                            <th class="text-center"><?php echo $idioma->getText("sacar") ?></th>
                                        </tr>
                                    </thead>

                                    <tbody id="lista-meus-investimentos-<?php echo \Utils\Criptografia::encriptyPostId($m->id) ?>">

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <?php
            }
            ?>
        </div>
    </div>
    <hr style="border: #ADB5BD">  
    <div class="row ">
        <div class="col col-lg-12 ">
            <br>
            <h3><?php echo $idioma->getText("meuHistoricoRendimentos") ?></h3>
        </div>
    </div>    
    <div class="row">
        <div class="col-lg-12 col-xs-12">
            <div class="panel panel-default">
                <div class="panel-body">                    
                        <div class="row">
                            <div class="col col-lg-3">
                                <div class="form-group">
                                    <label><?php echo $idioma->getText("ultimosDias") ?></label>
                                    <select class="form-control" id="filtroDias">    
                                        <option value="7">7 <?php echo $idioma->getText("dias") ?></option>
                                        <option value="15">15 <?php echo $idioma->getText("dias") ?></option>
                                        <option value="30">30 <?php echo $idioma->getText("dias") ?></option>
                                        <option value="T" ><?php echo $idioma->getText("todas") ?></option>
                                    </select>
                                </div>
                            </div>
                            <div class="col col-lg-3">
                                <div class="form-group">
                                    <label class="control-label"><?php echo $idioma->getText("moeda") ?></label>
                                    <select class="form-control" id="filtroMoeda">
                                        <option value="<?php echo \Utils\Criptografia::encriptyPostId("T")?>"><?php echo $idioma->getText("todas") ?></option>
                                    <?php foreach ($moedas as $dados) {
                                        $m = $dados["moeda"]; ?>                                        
                                        <option value="<?php echo \Utils\Criptografia::encriptyPostId($m->id)?>"><?php echo $m->nome ?></option>
                                    <?php } ?>
                                    </select>
                                </div>
                            </div>
                            <div class="col col-lg-3">
                                <br>
                                <div class="checkbox i-checks">
                                    <div class="icheckbox_square-green" style="position: relative;">
                                        <input type="checkbox"  id="consolidado" name="consolidado" value="1" checked>                                        
                                    </div>&nbsp;<?php echo $idioma->getText("saldoConsolidado") ?>
                                </div>
                            </div>
                            <div class="col-xs-12 col-lg-3">
                                <label>&nbsp;</label>
                                <div class="form-group">
                                    <button type="button" class="btn btn-default pull-right full-width" onClick="listarHistoricoRendimentos();"><?php echo $idioma->getText("filtrar") ?></button>
                                </div>
                            </div>
                        </div>                                      
                </div>
            </div>
        </div>
    </div>
        <div class="row">
            <div class="col col-lg-12 ">
                <div class="table-responsive">
                <table class="table table-striped table-hover table-condensed table-bordered" style="font-size: 11px; background-color: #fff">
                    <thead>
                        <tr> 
                            <th class="text-center"><?php echo $idioma->getText("rendimentosData") ?></th>
                            <th class="text-center"><?php echo $idioma->getText("rendimentosMoeda") ?></th>
                            <th class="text-center"><?php echo $idioma->getText("rendimentosDescricao") ?></th>
                            <th class="text-center"><?php echo $idioma->getText("rendimentosValor") ?></th>
                        </tr>
                    </thead>
                    
                    <tbody id="lista-meus-rendimentos">
                            
                    </tbody>
                </table>
                </div>
            </div>
        </div>
        
</div>



<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>


<?php Utils\Layout::append("mensage_text", $_data) ?>



<script>
    
    $(document).ready(function () {
        
        $("#modalDepositarVolume").keydown(function (event) {
            $(this).val(currency($(this).val(), 8, 8, event.keyCode));
            event.preventDefault();
        });
        
        $("#ck-habilitar-descricao-deposito").change(function () {
            $("#modalDepositarSaldoDescricao").prop("disabled", (!$(this).is(":checked")));
        });
        
        $('.i-checks').iCheck({
        checkboxClass: 'icheckbox_square-green',
        radioClass: 'iradio_square-green'
        });
        
        <?php foreach ($moedas as $dados) {
            $m = $dados["moeda"]; ?>                                        
            listarInvestimentos("<?php echo \Utils\Criptografia::encriptyPostId($m->id) ?>");
        <?php } ?>
        
        listarHistoricoRendimentos();
    });
    
    
    var saldoDisponivelDeposito = 0;
    function modalDepositar(moeda) {
        $("#btn-depositar").prop("disabled", true);
        $.ajax({
            url: "<?php echo URLBASE_CLIENT . Rotas::R_COFRE_TOKEN ?>",
            method: "post",
            dataType: "json",
            data: {
                moeda: moeda
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        saldoDisponivelDeposito = parseFloat(json.saldo);
                        $("#modalDepositarSaldoDisponivel").html(saldoDisponivelDeposito.toFixed(8) +" "+ json.simbolo);
                        $("#modalDepositarMoeda").val(moeda);
                        $("#modalDepositarVolume").val("");
                        $("#modalDepositarToken").val("");
                        $("#modalDepositarPin").val("");
                        $("#modalDepositarMeio").html(json.meio);
                        
                        if (json.google) { 
                            $("#modalDepositarReenviar").show();
                        } else {
                            $("#modalDepositarReenviar").hide();
                        }
                        $("#ck-habilitar-descricao-deposito").prop("checked", false).trigger("change");
                        $("#modalDepositar").modal();
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch(e) {
                    showNotyAlert(e, "e");
                }
                $("#btn-depositar").prop("disabled", false);
            }
        });
        
    }
    
    function depositarMeuSaldo() {
        $("#modalDepositarVolume").val(saldoDisponivelDeposito.toFixed(8).replace(".", ","));
    }
    
    function depositar() {
        $("#modalDepositarCancelar, #modalDepositarReenviar, #modalDepositarConfirmar").prop("disabled", true);
        $.ajax({
            url: "<?php echo URLBASE_CLIENT . Rotas::R_COFRE_DEPOSITAR ?>",
            method: "post",
            dataType: "json",
            data: {
                volume: $("#modalDepositarVolume").val(),
                token: $("#modalDepositarToken").val(),
                pin: $("#modalDepositarPin").val(),
                moeda: $("#modalDepositarMoeda").val(),
                descricao: $("#modalDepositarSaldoDescricao").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        showNotyAlert(json.mensagem, "s");
                        $("#modalDepositarCancelar").prop("disabled", false).trigger("click");
                        getSaldoCofre($("#modalDepositarMoeda").val());
                        //listarInvestimentos();
                        location.reload();
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch(e) {
                    showNotyAlert(e, "e");
                }
                $("#modalDepositarCancelar, #modalDepositarReenviar, #modalDepositarConfirmar").prop("disabled", false);
            }
        });
        
    }
    
    function modalSacar(moeda) {
        $("#btn-sacar").prop("disabled", true);
        $.ajax({
            url: "<?php echo URLBASE_CLIENT . Rotas::R_COFRE_TOKEN ?>",
            method: "post",
            dataType: "json",
            data: {
                moeda: moeda
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#modalSacarMoeda").val(moeda);
                        $("#modalSacarToken").val("");
                        $("#modalSacarPin").val("");
                        $("#modalSacarMeio").html(json.meio);
                        
                        if (json.google) { 
                            $("#modalSacarReenviar").show();
                        } else {
                            $("#modalSacarReenviar").hide();
                        }
                        
                        $("#modalSacar").modal();
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch(e) {
                    showNotyAlert(e, "e");
                }
                $("#btn-sacar").prop("disabled", false);
            }
        });
        
    }
    
    function sacar() {
        $("#modalSacarCancelar, #modalSacarReenviar, #modalSacarConfirmar").prop("disabled", true);
        $.ajax({
            url: "<?php echo URLBASE_CLIENT . Rotas::R_COFRE_RETIRADA_SOLICITAR ?>",
            method: "post",
            dataType: "json",
            data: {
                token: $("#modalSacarToken").val(),
                pin: $("#modalSacarPin").val(),
                moeda: $("#modalSacarMoeda").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        showNotyAlert(json.mensagem, "s");
                        $("#modalSacarCancelar").prop("disabled", false).trigger("click");
                        getSaldoCofre($("#modalSacarMoeda").val());
                        $("#modalSacar").modal("hide");
                        location.reload();
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch(e) {
                    showNotyAlert(e, "e");
                }
                $("#modalSacarCancelar, #modalSacarReenviar, #modalSacarConfirmar").prop("disabled", false);
                
            }
        });
        
    }
    
    function reenviarToken() {
        $.ajax({
            url: "<?php echo URLBASE_CLIENT . Rotas::R_COFRE_TOKEN ?>",
            method: "post",
            dataType: "json",
            success: function (json) {
                try {
                    if (json.sucesso) {
                        showNotyAlert(<?php echo $idioma->getText("foiEnviadoTokenEmailCel")?>, "s");
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch(e) {
                    showNotyAlert(e, "e");
                }
            }
        });
    }
    
    
    function getSaldoCofre(moeda) {
        $.ajax({
            url: "<?php echo URLBASE_CLIENT . Rotas::R_COFRE_SALDO ?>",
            method: "post",
            dataType: "json",
            data: {
                moeda: moeda
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#depositado-cofre-"+json.codigo).html(json.depositado.replace(".", ","));
                        $("#rendimento-cofre-"+json.codigo).html(json.rendimento.replace(".", ","));
                        $("#recebido-cofre-"+json.codigo).html(json.recebido.replace(".", ","));
                        $("#saldo-cc-"+json.codigo).html(json.saldo.replace(".", ","));
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch(e) {
                    showNotyAlert(e, "e");
                }
            }
        });
    }
    
    
    function listarInvestimentos(moeda) {
    
       //console.log(moeda + "Teste moeda");
      
        $("#lista-meus-investimentos-" + moeda).html("<tr><td class='text-center' colspan='10' ><img src='<?php echo IMAGES ?>loading.gif' /></td><tr>");
        $.ajax({
            url: "<?php echo URLBASE_CLIENT . Rotas::R_COFRE_LISTAR ?>",
            method: "post",
            dataType: "json",
            data: {
                moeda: moeda
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#lista-meus-investimentos-" + moeda).html(json.html);
                    } else {
                        $("#lista-meus-investimentos-" + moeda).html("<tr><td class='text-center' colspan='10' >"+json.mensagem+"</td><tr>");
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch(e) {
                    $("#lista-meus-investimentos-" + moeda).html("<tr><td class='text-center' colspan='10' >"+e+"</td><tr>");
                    showNotyAlert(e, "e");
                }
            }
        });

    }
    
    
    function listarHistoricoRendimentos() {
    
        $("#lista-meus-rendimentos").html("<tr><td class='text-center' colspan='4' ><img src='<?php echo IMAGES ?>loading.gif' /></td><tr>");
        $.ajax({
            url: "<?php echo URLBASE_CLIENT . Rotas::R_COFRE_RENDIMENTOS_FILTRAR ?>",
            method: "post",
            dataType: "json",
            data: {
                moeda: $("#filtroMoeda").val(),
                dias: $("#filtroDias").val(),
                consolidado: $("#consolidado").is(":checked")
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#lista-meus-rendimentos").html(json.html);
                    } else {
                        $("#lista-meus-rendimentos").html("<tr><td class='text-center' colspan='4' >"+json.mensagem+"</td><tr>");
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch(e) {
                    $("#lista-meus-rendimentos").html("<tr><td class='text-center' colspan='4' >"+e+"</td><tr>");
                    showNotyAlert(e, "e");
                }
            }
        });
    }
    
    
    
    function modalSacarInvestimento(investimento) {
        $("#btn-sacar").prop("disabled", true);
        $.ajax({
            url: "<?php echo URLBASE_CLIENT . Rotas::R_COFRE_TOKEN ?>",
            method: "post",
            dataType: "json",
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#modalSacarInvestimentoCodigo").val(investimento);
                        $("#modalSacarInvestimentoToken").val("");
                        $("#modalSacarInvestimentoPin").val("");
                        $("#modalSacarInvestimentoMeio").html(json.meio);
                        
                        if (json.google) { 
                            $("#modalSacarInvestimentoReenviar").show();
                        } else {
                            $("#modalSacarInvestimentoReenviar").hide();
                        }
                        
                        $("#modalSacarInvestimento").modal();
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch(e) {
                    showNotyAlert(e, "e");
                }
                $("#btn-sacar").prop("disabled", false);
            }
        });
        
    }
    
    function sacarInvestimento() {
        $("#modalSacarInvestimentoCancelar, #modalSacarInvestimentoReenviar, #modalSacarInvestimentoConfirmar").prop("disabled", true);
        $.ajax({
            url: "<?php echo URLBASE_CLIENT . Rotas::R_COFRE_RETIRADA_SACAR ?>",
            method: "post",
            dataType: "json",
            data: {
                token: $("#modalSacarInvestimentoToken").val(),
                pin: $("#modalSacarInvestimentoPin").val(),
                investimento: $("#modalSacarInvestimentoCodigo").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        showNotyAlert(json.mensagem, "s");
                        $("#modalSacarInvestimentoCancelar").prop("disabled", false).trigger("click");
                        getSaldoCofre(json.moeda);
                        //listarInvestimentos();
                        $("#modalSacarInvestimento").modal("hide");
                        location.reload();
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch(e) {
                    showNotyAlert(e, "e");
                }
                $("#modalSacarInvestimentoCancelar, #modalSacarInvestimentoReenviar, #modalSacarInvestimentoConfirmar").prop("disabled", false);
                
            }
        });
        
    }
</script>


<div class="modal inmodal" id="modalDepositar" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content animated bounceInRight">
            <div class="modal-header">
                
                <h4 class="modal-title"><?php echo $idioma->getText("confirmarTransacao") ?></h4>
            </div>
            <div class="modal-body">
                <input type="hidden" id="modalDepositarMoeda" name="modalDepositarMoeda" />
                <div class="form-group">
                    <label><?php echo $idioma->getText("volumeDepositar") ?></label>
                    <div class="input-group">
                        <input type="text"  class="form-control currency" id="modalDepositarVolume" >
                        <span class="input-group-btn"> 
                            <button type="button" onclick="depositarMeuSaldo();" class="btn btn-primary"><?php echo $idioma->getText("utilizarSaldo") ?></button> 
                        </span>
                    </div>
                    <p><?php echo $idioma->getText("modalDepositarSaldoAtual") ?> <span id="modalDepositarSaldoDisponivel"></span></p>
                </div>
                
                <div class="form-group">
                    <label>
                        <?php echo $idioma->getText("cofreModalDepositoLabelDescricao") ?>
                    </label> 

                    <div class="input-group">
                        <span class="input-group-addon"> 
                            <input type="checkbox" id="ck-habilitar-descricao-deposito" maxlength="30"> 
                        </span>
                        <input type="text" class="form-control"  id="modalDepositarSaldoDescricao"  maxlength="200"/>
                    </div>
                </div>
                
                <p>
                    <strong id="modalDepositarMeio"></strong>
                </p>
                
                <div class="form-group">
                    <label><?php echo $idioma->getText("informeToken") ?></label> 
                    <input type="text"  inputmode="numeric" pattern="[0-9]*" class="form-control" id="modalDepositarToken">
                </div>
                
                
                <div class="form-group">
                    <label><?php echo $idioma->getText("informePin") ?> </label> 
                    <input type="password"  class="form-control" id="modalDepositarPin">
                </div>
            </div>
            <div class="modal-footer">
                
                <div class="col-lg-3 col-xs-12 m-t-xs">
                <button type="button" class="btn btn-info full-width" onclick="reenviarToken();"  id="modalDepositarReenviar"><?php echo $idioma->getText("reenviar") ?></button>
                </div>
                <div class="col-lg-3 col-xs-12 m-t-xs"></div>
                <div class="col-lg-3 col-xs-12 m-t-xs">
                <button type="button" class="btn btn-white full-width" data-dismiss="modal" id="modalDepositarCancelar"><?php echo $idioma->getText("cancelar") ?></button>
                </div>
                <div class="col-lg-3 col-xs-12 m-t-xs">
                <button type="button" class="btn btn-success full-width" onclick="depositar();"  id="modalDepositarConfirmar"><?php echo $idioma->getText("confirmar") ?></button>
                </div>
                </div>
            </div>
        </div>
    </div>




<div class="modal inmodal" id="modalSacar" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content animated bounceInRight">
            <div class="modal-header">
                <h4 class="modal-title"><?php echo $idioma->getText("confirmaTransacao") ?></h4>
            </div>
            <div class="modal-body">
                <input type="hidden" id="modalSacarMoeda" >
                <p>
                    <strong id="modalSacarMeio"></strong>
                </p>
                
                <div class="form-group">
                    <label><?php echo $idioma->getText("informToken") ?> </label> 
                    <input type="text"  class="form-control" id="modalSacarToken">
                </div>
                
                
                <div class="form-group">
                    <label><?php echo $idioma->getText("informPin") ?> </label> 
                    <input type="password"  class="form-control" id="modalSacarPin">
                </div>
            </div>
            <div class="modal-footer">
                <div class="col-lg-3 col-xs-12 m-t-xs">
                <button type="button" class="btn btn-info full-width" onclick="reenviarToken();"  id="modalSacarReenviar"><?php echo $idioma->getText("reenviar") ?></button>
                </div>
                <div class="col-lg-3 col-xs-12 m-t-xs"></div>
                <div class="col-lg-3 col-xs-12 m-t-xs">
                <button type="button" class="btn btn-white full-width" data-dismiss="modal" id="modalSacarCancelar"><?php echo $idioma->getText("cancelar") ?></button>
                </div>
                <div class="col-lg-3 col-xs-12 m-t-xs">
                <button type="button" class="btn btn-success full-width" onclick="sacar();"  id="modalSacarConfirmar"><?php echo $idioma->getText("confirmar") ?></button>
                </div>
            </div>
        </div>
    </div>
</div>



<div class="modal inmodal" id="modalSacarInvestimento" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content animated bounceInRight">
            <div class="modal-header">
                <h4 class="modal-title"><?php echo $idioma->getText("confirmaTransacao") ?></h4>
            </div>
            <div class="modal-body">
                <input type="hidden" id="modalSacarInvestimentoCodigo" >
                <p>
                    <strong id="modalSacarInvestimentoMeio"></strong>
                </p>
                
                <div class="form-group">
                    <label><?php echo $idioma->getText("informToken") ?> </label> 
                    <input type="text"  class="form-control" id="modalSacarInvestimentoToken">
                </div>
                
                
                <div class="form-group">
                    <label><?php echo $idioma->getText("informPin") ?> </label> 
                    <input type="password"  class="form-control" id="modalSacarInvestimentoPin">
                </div>
            </div>
            <div class="modal-footer">
                <div class="col-lg-3 col-xs-12 m-t-xs">
                <button type="button" class="btn btn-info full-width" onclick="reenviarToken();"  id="modalSacarInvestimentoReenviar"><?php echo $idioma->getText("reenviar") ?></button>
                </div>
                <div class="col-lg-3 col-xs-12 m-t-xs"></div>
                <div class="col-lg-3 col-xs-12 m-t-xs">
                <button type="button" class="btn btn-white full-width" data-dismiss="modal" id="modalSacarInvestimentoCancelar"><?php echo $idioma->getText("cancelar") ?></button>
                </div>
                <div class="col-lg-3 col-xs-12 m-t-xs">
                <button type="button" class="btn btn-success full-width" onclick="sacarInvestimento();"  id="modalSacarInvestimentoConfirmar"><?php echo $idioma->getText("confirmar") ?></button>
                </div>
            </div>
        </div>
    </div>
</div>


