<?php
use Utils\Rotas;
$moeda = \Modules\principal\Controllers\Principal::getCurrency();
$moedas = (isset($_data["moedas"]) ? $_data["moedas"] : 0);

$idioma = new \Utils\PropertiesUtils("cofre", 'IDIOMA');
$configuracao = \Models\Modules\Cadastro\ConfiguracaoRn::get();

?>

<?php Utils\Layout::append("inspina/metas", $_data) ?>
<?php Utils\Layout::append("inspina/scripts", $_data) ?>
<?php Utils\Layout::append("inspina/menu", $_data) ?>
<div class="content-wrapper">
  <div class="row wrapper border-bottom page-heading" style="background: linear-gradient(to right, #fff, <?php echo $moeda->mainColor ?>) !important;">
    <div class="col-lg-9">
      <ol class="breadcrumb m-t-md" style="background-color: transparent !important;">
          <li>
            <?php echo $idioma->getText("subTitulo") ?>
          </li>
          <li class="active">
              <strong><?php echo $idioma->getText("titulo") ?>
          </li>
      </ol>
    </div>
    <div class="col-lg-3">
    <?php Utils\Layout::append("inspina/flags", $_data) ?>
    </div>
  </div>
</div>
<div class="wrapper wrapper-content  animated fadeInRight">
    
            <div class="tabs-container">
                <ul class="nav nav-tabs">
                    <?php
                    foreach ($moedas as $m) {
                    ?>
                    <li class="<?php echo ($m->id == 2 ? "active" : "") ?>">
                        <a data-toggle="tab" href="#tab-<?php echo $m->id?>">
                            <img src='<?php echo IMAGES ?>currencies/<?php echo $m->icone?>' style="width: 25px; height: 25px; " />
                            <?php echo $idioma->getText("info6") ?> <?php echo $m->nome?>
                        </a>
                    </li>
                    <?php
                    }
                    ?>
                </ul>
                
                
                <div class="tab-content">
                    <?php
                    foreach ($moedas as $m) {
                    ?>
                    <div id="tab-<?php echo $m->id?>" class="tab-pane <?php echo ($m->id == 2 ? "active" : "") ?>">
                        <div class="panel-body">
                            <div class="row" >
                                <div class="col-lg-12">
                                    <div class="tumb text-center">
                                        <img src="<?php echo IMAGES ?>profits.png" style="max-width: 100%; max-height: 200px;" />
                                    </div>
                                </div>
                            </div>
                            
                            <div class="row">
                                <div class="col col-lg-12 text-right">
                                    <br><br>
                                    <button class="btn btn-primary btn-sm" type="button" onclick="listarInvestimentos();">
                                        <i class="fa fa-refresh"></i> Atualizar Dados
                                    </button>
                                    <br><br>
                                </div>
                            </div>
                            
                            <div class="row" >
                                
                                <div class="col-lg-12 text-center">
                                    
                                    <div class="row">
                                        <div class="col col-md-4 m-b-xs">
                                            <h3>Saldo total investido</h3>
                                            
                                            <div class="alert alert-warning">
                                                <h1>
                                                    <img src="<?php echo IMAGES ?>currencies/<?php echo $m->icone ?>" style="max-width: 30px; max-height: 30px;"> 
                                                    <strong id="depositado-cofre-<?php echo $m->id ?>">
                                                    
                                                    </strong>
                                                    <br>
                                                    <small>Clientes: <strong id="clientes-cofre-<?php echo $m->id ?>"></strong></small><br>
                                                    <small>Não investindo: <strong id="clientes-nao-cofre-<?php echo $m->id ?>"></strong></small>
                                                </h1>
                                            </div> 
                                        </div>
                                        <div class="col col-md-4 m-b-xs">
                                            <h3>Rendimentos</h3>
                                            
                                            <div class="alert alert-success">
                                                <h1>
                                                    <img src="<?php echo IMAGES ?>currencies/<?php echo $m->icone ?>" style="max-width: 30px; max-height: 30px;"> 
                                                    <strong id="rendimento-cofre-<?php echo $m->id ?>">
                                                    
                                                    </strong>
                                                </h1>
                                            </div> 
                                        </div>
                                        
                                        
                                        <div class="col col-md-4 m-b-xs">
                                            <h3>Valor total passível de resgate</h3>
                                            
                                            <div class="alert alert-info">
                                                <h1>
                                                    <img src="<?php echo IMAGES ?>currencies/<?php echo $m->icone ?>" style="max-width: 30px; max-height: 30px;"> 
                                                    <strong id="total-cofre-<?php echo $m->id ?>">
                                                    
                                                    </strong>
                                                </h1>
                                            </div> 
                                        </div>
                                       
                                    </div>
                                    
                                    <div class="row">
                                        <div class="col col-md-4 m-b-xs">
                                            <h3>Saldo do Core</h3>
                                            
                                            <div class="alert alert-info">
                                                <h1>
                                                    <img src="<?php echo IMAGES ?>currencies/<?php echo $m->icone ?>" style="max-width: 30px; max-height: 30px;"> 
                                                    <strong id="total-core-<?php echo $m->id ?>">
                                                    
                                                    </strong>
                                                </h1>
                                            </div> 
                                        </div>
                                        <div class="col col-md-4 m-b-xs">
                                            <h3>Diferença Cofre x Core</h3>
                                            
                                            <div class="alert alert-info">
                                                <h1>
                                                    <img src="<?php echo IMAGES ?>currencies/<?php echo $m->icone ?>" style="max-width: 30px; max-height: 30px;"> 
                                                    <strong id="diferenca-cofre-<?php echo $m->id ?>">
                                                    
                                                    </strong>
                                                </h1>
                                            </div> 
                                        </div>
                                    </div>
                                    
                                    <div class="row">
                                        <div class="col col-lg-12 text-center">
                                            <h4>Previsão de provisão para os próximos 7 dias</h4>
                                        </div>
                                    </div>
                                    
                                    <div class="row">
                                        <div class="col col-lg-12 ">
                                            <table border="0" class="table">
                                                <tbody id="table-dias-<?php echo $m->id ?>">
                                                    
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                
                            </div>
                            
                            
                            <div class="row">
                                <div class="col col-lg-12">

                                    <table class="table table-bordered table-condensed table-hover table-striped">

                                        <thead>
                                            <tr>
                                                <th class="text-center">Cliente</th>
                                                <th class="text-center">Data do depósito</th>
                                                <th class="text-center">Taxa</th>
                                                <th class="text-center">Volume Depositado</th>
                                                <th class="text-center">Rendimentos</th>
                                                <th class="text-center">Previsão saque</th>
                                                <th class="text-center">Volume total</th>
                                                <th class="text-center">Status</th>
                                            </tr>
                                        </thead>
                                        <tbody id="tbody-<?php echo $m->id ?>">

                                        </tbody>
                                    </table>

                                </div>
                            </div>
                            
                        </div>
                    </div>
                    <?php
                    }
                    ?>
                    
                </div>


            </div>
            
</div>



<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>


<?php Utils\Layout::append("mensage_text", $_data) ?>



<script>
    
    $(document).ready(function () {
        
        listarInvestimentos();
        
    });
    
    
    
    function listarInvestimentos() {
    
        $("#tbody-2, #tbody-4, #tbody-7").html("<tr><td class='text-center' colspan='8' ><img src='<?php echo IMAGES ?>loading.gif' /></td><tr>");
        $.ajax({
            url: "<?php echo URLBASE_CLIENT . Rotas::R_COFRE_ADM_INVESTIMENTOS ?>",
            method: "post",
            dataType: "json",
            success: function (json) {
                try {
                    if (json.sucesso) {
                        
                                    
                        
                        $("#tbody-2").html(json.bitcoin.html);
                        $("#depositado-cofre-2").html(json.bitcoin.investido.toFixed(8));
                        $("#rendimento-cofre-2").html(json.bitcoin.rendimento.toFixed(8));
                        $("#total-cofre-2").html(json.bitcoin.valorTotal.toFixed(8));
                        $("#clientes-cofre-2").html(json.bitcoin.clientes);
                        $("#table-dias-2").html(json.bitcoin.dias);
                        $("#total-core-2").html(json.bitcoin.core.toFixed(8));
                        $("#diferenca-cofre-2").html(json.bitcoin.diferenca.toFixed(8));
                        $("#clientes-nao-cofre-2").html(json.clientesBitcoin);
                        
                        $("#tbody-4").html(json.litecoin.html);
                        $("#depositado-cofre-4").html(json.litecoin.investido.toFixed(8));
                        $("#rendimento-cofre-4").html(json.litecoin.rendimento.toFixed(8));
                        $("#total-cofre-4").html(json.litecoin.valorTotal.toFixed(8));
                        $("#table-dias-4").html(json.litecoin.dias);
                        $("#clientes-cofre-4").html(json.litecoin.clientes);
                        $("#total-core-4").html(json.litecoin.core.toFixed(8));
                        $("#diferenca-cofre-4").html(json.litecoin.diferenca.toFixed(8));
                        $("#clientes-nao-cofre-4").html(json.clientesLitecoin);
                        
                        $("#tbody-7").html(json.dash.html);
                        $("#depositado-cofre-7").html(json.dash.investido.toFixed(8));
                        $("#rendimento-cofre-7").html(json.dash.rendimento.toFixed(8));
                        $("#total-cofre-7").html(json.dash.valorTotal.toFixed(8));
                        $("#table-dias-7").html(json.dash.dias);
                        $("#clientes-cofre-7").html(json.dash.clientes);
                        $("#total-core-7").html(json.dash.core.toFixed(8));
                        $("#diferenca-cofre-7").html(json.dash.diferenca.toFixed(8));
                        $("#clientes-nao-cofre-7").html(json.clientesDash);
                    } else {
                        $("#tbody-2, #tbody-4, #tbody-7").html("<tr><td class='text-center' colspan='8' >"+json.mensagem+"</td><tr>");
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch(e) {
                    $("#tbody-2, #tbody-4, #tbody-7").html("<tr><td class='text-center' colspan='8' >"+e+"</td><tr>");
                    showNotyAlert(e, "e");
                }
            }
        });
    }
    
</script>
