<?php
use Utils\Rotas;

$idioma = new \Utils\PropertiesUtils("cofre", 'IDIOMA');
$configuracao = \Models\Modules\Cadastro\ConfiguracaoRn::get();
$autenticacao = (isset($_data["2fa"]) ? $_data["2fa"] : 'email');
$contratos = isset($_data["contratos"]) ? $_data["contratos"] : Array();
$investimentoAtivo = isset($_data["investimentoAtivo"]) ? $_data["investimentoAtivo"] : false;
$qtdInvestimento = isset($_data["qtdInvestimento"]) ? $_data["qtdInvestimento"] : false;

$_data["idiomaMenu"] = $idioma;
?>
<style>
    .border-edit {
        border: 1px solid #1c84c6 !important;
    }

</style>
<?php Utils\Layout::append("inspina/metas", $_data) ?>
<?php Utils\Layout::append("inspina/scripts", $_data) ?>
<?php Utils\Layout::append("inspina/menu", $_data) ?>
<link href="<?php echo TEMA; ?>css/plugins/switchery/switchery.css" rel="stylesheet">
<link href="<?php echo TEMA; ?>css/plugins/ionRangeSlider/ion.rangeSlider.css" rel="stylesheet">
<div class="row">
    <div class="col-lg-12 col-xs-12">
        <div class="fh-breadcrumb">
            <div class="fh-column">
                <ul class="list-group elements-list">
                    <a data-toggle="tab" href="#tab-investimento-1" aria-expanded="false" onclick="menuDinamico('liEmpresa');">
                        <li id="liEmpresa" class="list-group-item" style="padding-bottom: 5px !important; padding-top: 8px !important; padding-left: 15px !important; padding-right: 15px !important;" >                                
                            <strong><?php echo $idioma->getText("invest34") ?></strong>
                            <div class="small m-t-xs">
                                <p>
                                    <?php echo $idioma->getText("invest33") ?>
                                </p>
                            </div>                                
                        </li>
                    </a>
                    <a data-toggle="tab" href="#tab-investimento-2" aria-expanded="false" onclick="menuDinamico('liCliente'); getSaldoCofre();">
                        <li id="liCliente" class="list-group-item" style="padding-bottom: 5px !important; padding-top: 8px !important; padding-left: 15px !important; padding-right: 15px !important;" >
                            <strong><?php echo $idioma->getText("invest11") ?></strong>
                            <div class="small m-t-xs">
                                <p>
                                     <?php echo $idioma->getText("invest32") ?>
                                </p>
                            </div>
                        </li>
                    </a>                    
                    <a data-toggle="tab" href="#tab-investimento-3" aria-expanded="false" onclick="menuDinamico('liCalculadora'); listarContratos();">
                        <li id="liCalculadora" class="list-group-item" style="padding-bottom: 5px !important; padding-top: 8px !important; padding-left: 15px !important; padding-right: 15px !important;" >                                
                            <strong><?php echo $idioma->getText("invest9") ?></strong>
                            <div class="small m-t-xs">
                                <p>
                                   <?php echo $idioma->getText("invest10") ?>
                                </p>
                            </div>                                
                        </li>
                    </a> 
                     <?php if($qtdInvestimento) { ?>
                    <a data-toggle="tab" href="#tab-investimento-4" aria-expanded="false" onclick="menuDinamico('liExtrato'); listarHistoricoRendimentos(); listarInvestimentos();">
                        <li id="liExtrato" class="list-group-item" style="padding-bottom: 5px !important; padding-top: 8px !important; padding-left: 15px !important; padding-right: 15px !important;" >                                
                            <strong> <?php echo $idioma->getText("invest30") ?> </strong>
                            <div class="small m-t-xs">
                                <p>
                                    <?php echo $idioma->getText("invest31") ?>
                                </p>
                            </div>                                
                        </li>
                    </a>
                     <?php } ?>
                    <?php if($investimentoAtivo) { ?>
                    <a data-toggle="tab" href="#tab-investimento-5" aria-expanded="false" onclick="menuDinamico('liResgatar'); listarResgate();">
                        <li id="liResgatar" class="list-group-item" style="padding-bottom: 5px !important; padding-top: 8px !important; padding-left: 15px !important; padding-right: 15px !important;" >                                
                            <strong> <?php echo $idioma->getText("invest23") ?> </strong>
                            <div class="small m-t-xs">
                                <p>
                                    <?php echo $idioma->getText("invest24") ?>
                                </p>
                            </div>                                
                        </li>
                    </a>
                    <?php } ?>
                </ul>
            </div>

            <div class="full-height">
                <div class="full-height-scroll white-bg border-left" style="overflow: hidden; width: auto; height: 100%;">
                    <div class="element-detail-box">
                        <div class="tab-content">                            
                            <div id="tab-investimento-1" class="tab-pane active">
                                <div class="row">
                                    <div class="col <?php echo $qtdInvestimento ? "col-lg-6" : "col-lg-12"?>">
                                        <div class="row">
                                            <div class="col col-lg-12">
                                                <div class="">
                                                    <h2 class="page-header" style="margin-top: 0px !important;"><strong><?php echo $idioma->getText("invest46") ?></strong></h2>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col col-lg-12">
                                                <div class="widget yellw-bg no-padding">
                                                    <div class="p-m">
                                                        <h1 class="m-xs">₿ <span id="totalEmpresaInvest">0.0000</span></h1>

                                                        <h3 class="font-bold no-margins">
                                                            <?php echo $idioma->getText("invest47") ?>
                                                        </h3>
                                                        <small></small>
                                                    </div>
                                                    <div class="flot-chart">
                                                        <div class="flot-chart-content" id="flot-chart1" style="padding: 0px; position: relative;">
                                                            <canvas class="flot-base" width="525" height="100" style="direction: ltr; position: absolute; left: 0px; top: 0px; width: 525.5px; height: 100px;"></canvas>
                                                            <canvas class="flot-overlay" width="525" height="100" style="direction: ltr; position: absolute; left: 0px; top: 0px; width: 525.5px; height: 100px;"></canvas>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-lg-12">                                        
                                                <div>
                                                    <table class="table">
                                                        <tbody id="dadosEmpresa">
                                                            
                                                        </tbody>
                                                    </table>
                                                </div>                                        
                                            </div>
                                        </div>
                                    </div>
                                    <?php if($qtdInvestimento) { ?>
                                    <div class="col col-lg-6">
                                        <div class="row">
                                            <div class="col col-lg-12">
                                                <div class="">
                                                    <h2 class="page-header" style="margin-top: 0px !important;"><strong><?php echo $idioma->getText("invest48") ?></strong></h2>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col col-lg-12">
                                                <div class="widget yellw-bg no-padding">
                                                    <div class="p-m">
                                                        <h1 class="m-xs">₿ <span id="totalClienteInvest">0.0000</span></h1>

                                                        <h3 class="font-bold no-margins">
                                                            <?php echo $idioma->getText("invest49") ?>
                                                        </h3>
                                                        <small></small>
                                                    </div>
                                                    <div class="flot-chart">
                                                        <div class="flot-chart-content" id="flot-chart2" style="padding: 0px; position: relative;">
                                                            <canvas class="flot-base" width="525" height="100" style="direction: ltr; position: absolute; left: 0px; top: 0px; width: 525.5px; height: 100px;"></canvas>
                                                            <canvas class="flot-overlay" width="525" height="100" style="direction: ltr; position: absolute; left: 0px; top: 0px; width: 525.5px; height: 100px;"></canvas>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-lg-12">                                        
                                                <div>
                                                    <table class="table">
                                                        <tbody id="dadosCliente">
                                                            
                                                        </tbody>
                                                    </table>
                                                </div>                                        
                                            </div>
                                        </div>
                                    </div>
                                    <?php } ?>
                                </div>
                            </div>                            
                            <div id="tab-investimento-2" class="tab-pane">
                                <div class="row">
                                    <div class="col col-lg-12">
                                        <div class="">
                                            <h2 class="page-header" style="margin-top: 0px !important;"><strong><?php echo $idioma->getText("invest11") ?></strong></h2>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-7">
                                        <div class="table-responsive">
                                            <table class="table table-striped table-hover table-condensed table-bordered" style="font-size: 11px; background-color: #fff; table-layout: fixed;">
                                                <thead>
                                                    <tr> 
                                                        <th class="text-center"><?php echo $idioma->getText("invest12") ?></th>
                                                        <th class="text-center"><?php echo $idioma->getText("invest13") ?></th>
                                                    </tr>
                                                </thead>
                                                <tbody id="">
                                                    <tr>
                                                        <td class="text-center"><?php echo $idioma->getText("invest14") ?></td>
                                                        <td class="text-center" id="saldo">0.00000000</td>
                                                    </tr>              
                                                    <tr>
                                                        <td class="text-center"><?php echo $idioma->getText("invest15") ?></td>
                                                        <td class="text-center" id="depositado">0.00000000</td>
                                                    </tr>
                                                    <tr>
                                                        <td class="text-center"><strong><span id="mesesInvest"><?php echo $idioma->getText("invest21") ?></span></strong></td>
                                                        <td class="text-center"><strong><span id="valorInvest">0.00000000 BTC</span></strong></td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div> 
                                        <div class="row">
                                            <div class="col col-lg-6">               
                                                <div class="form-group">
                                                    <label><?php echo $idioma->getText("invest20") ?></label>
                                                    <div class="input-group">
                                                        <select class="form-control input-sm form-control input-s-sm inline full-width" id="contratos" name="contratos">
                                                            <option value="0"><?php echo $idioma->getText("invest21") ?></option>
                                                            <?php foreach ($contratos as $contrato) { ?>
                                                            <option value="<?php echo $contrato->id . "|" . $contrato->lucroNc . "?" . $contrato->tempoMeses ?>"><?php echo $idioma->getText("invest35") ?> <?php echo $contrato->tempoMeses ?> <?php echo $contrato->tempoMeses > 1 ? $idioma->getText("meses") :  $idioma->getText("mes") ?> - <?php echo $idioma->getText("invest36") ?> <?php echo $contrato->lucroNc ?>%</option>
                                                            <?php } ?>
                                                        </select>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col col-lg-6">               
                                                <div class="form-group">
                                                    <label><?php echo $idioma->getText("volumeDepositar") ?></label>
                                                    <div class="input-group">
                                                        <input type="text"  class="form-control currency full-width" id="volumeInvestimento" >
                                                        <span class="input-group-btn"> 
                                                            <button type="button" onclick="depositarMeuSaldo();" class="btn btn-primary"><?php echo $idioma->getText("utilizarSaldo") ?></button> 
                                                        </span>
                                                    </div>
                                                </div>
                                            </div>                                            
                                        </div>
                                        <div class="row">
                                            <div class="col col-lg-6"> 
                                                <div class="form-group">
                                                    <label><?php echo $idioma->getText("cofreModalDepositoLabelDescricao") ?></label>
                                                    <input type="text" class="form-control"  id="modalDepositarSaldoDescricao"  maxlength="200"/>
                                                </div>
                                            </div>
                                            <div class="col-lg-6" id="btnToken">
                                                <div class="form-group">
                                                    <label>&nbsp;</label>
                                                    <button type="button" class="btn btn-primary full-width" onclick="reenviarToken();"  id="modalDepositarConfirmar"><?php echo $idioma->getText("invest19") ?></button>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row" hidden="true" id="2fa">                                                    
                                            <div class="col col-lg-4">                                                  
                                                <div class="form-group">
                                                    <label><?php echo $idioma->getText("informePin") ?> </label> 
                                                    <input type="password"  class="form-control" id="modalDepositarPin">
                                                </div>
                                            </div>
                                            <div class="col col-lg-4">  
                                                <div class="form-group">
                                                    <label><?php echo $idioma->getText("informeToken") ?></label> 
                                                    <input type="text"  inputmode="numeric" pattern="[0-9]*" class="form-control" id="modalDepositarToken">
                                                    <?php if($autenticacao === "email"){ ?>
                                                    <a onclick="reenviarToken();"><?php echo $idioma->getText("invest18") ?></a>
                                                    <?php } ?>                                                    
                                                </div>
                                            </div>                                              
                                            <div class="col-lg-4">
                                                <div class="form-group">
                                                    <label>&nbsp;</label>
                                                    <button type="button" class="btn btn-success full-width" onclick="depositar();"  id="modalDepositarConfirmar"><?php echo $idioma->getText("invest22") ?></button>
                                                </div>
                                            </div>                                        
                                        </div> 
                                    </div>                                                                
                                    <div class="col-lg-5">
                                        <div id="vertical-timeline" class="vertical-container light-timeline no-margins">
                                            <div class="vertical-timeline-block">
                                                <div class="vertical-timeline-icon blue-bg">
                                                    <i class="fa fa-info fa-1x"></i>
                                                </div>
                                                <div class="vertical-timeline-content">
                                                    <strong class="text-center"><h5><?php echo $idioma->getText("informacoes") ?></h5></strong>
                                                    <small><ul>        
                                                            <li class="m-t-xs"><?php echo $idioma->getText("rendimentosPagoDiariamente") ?></li>                                                            
                                                            <li class="m-t-xs"><?php echo $idioma->getText("resgatePode") ?></li>               
                                                            <li class="m-t-xs"><?php echo str_replace("{var1}",$configuracao->prazoDiasSaqueCofre, $idioma->getText("info3")) ?></li>
                                                        </ul>                                                
                                                    </small> 
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div id="tab-investimento-3" class="tab-pane">                                
                                <div class="row text-center">
                                    <div class="col-lg-12 text-center">                                        
                                        <div class="row text-center">                                            
                                            <div class="col-lg-12 text-center" id="barChartDiv" style="align-content: center;">                                                    
                                                <canvas id="barChart" height="270" width="900" style="pointer-events: none !important;"></canvas>                                                 
                                            </div>                                            
                                        </div>
                                        </br>
                                         <hr class="hr-line-solid no-margins">
                                         </br>
                                        <div class="row text-center">                                            
                                            <div class="col-lg-4 col-lg-offset-1 text-center">
                                                <h3><?php echo $idioma->getText("invest2") ?></h3></br>
                                                 <input type="text" class="js-range-slider" id="valor" name="valor" value="" /> 
                                                 <a onclick="saldoSlider();"><?php echo $idioma->getText("invest50") ?></a>
                                            </div>
                                            <div class="col-lg-4 col-lg-offset-1 text-center">
                                                <h3><?php echo $idioma->getText("invest1") ?></h3></br>
                                                <input type="text" class="js-range-slider" id="mes" name="mes" value="" />
                                            </div>                                            
                                        </div>
                                        </br> 
                                        <hr class="hr-line-solid">
                                        <div class="row">
                                            <div class="col-lg-12">
                                                <h3><?php echo $idioma->getText("invest7") ?></h3>
                                                <div class="table-responsive">
                                                    <table class="table table-striped table-hover table-condensed table-bordered" style="font-size: 11px; background-color: #fff">
                                                        <tbody id="tempoLucro">                                                      
                                                        </tbody>
                                                    </table>
                                                </div>                                                
                                            </div>
                                        </div>
                                    </div>                                                                       
                                </div>
                            </div>
                            <?php if($qtdInvestimento) { ?>
                            <div id="tab-investimento-4" class="tab-pane">
                                <div class="row">
                                    <div class="col col-lg-12">
                                        <div class="">
                                            <h2 class="page-header" style="margin-top: 0px !important;"><strong><?php echo $idioma->getText("invest5") ?></strong></h2>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col col-lg-12 ">
                                        <h3><?php echo $idioma->getText("invest6") ?></h3>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col col-lg-12 ">
                                        <div class="table-responsive">
                                            <table id="tblMeusInvestimentos" class="table table-striped text-center" data-page-size="5"  style="font-size: 11px;">
                                                <thead>
                                                    <tr> 
                                                        <th class="text-center"><?php echo $idioma->getText("moeda") ?></th>
                                                        <th class="text-center"><?php echo $idioma->getText("cofreTabelaMeusInvestimentosControle") ?></th>
                                                        <th class="text-center"><?php echo $idioma->getText("descricao") ?></th>
                                                        <th class="text-center"><?php echo $idioma->getText("dataDeposito") ?></th>
                                                        <th class="text-center"><?php echo $idioma->getText("saldoDepositado") ?></th>
                                                        <th class="text-center"><?php echo $idioma->getText("saldoRendimentos") ?></th>
                                                        <th class="text-center"><?php echo $idioma->getText("saldoTotal") ?></th>
                                                        <th class="text-center"><?php echo $idioma->getText("vencimentoContrato") ?></th>
                                                        <th class="text-center">Status</th>
                                                    </tr>
                                                </thead>
                                                <tbody id="lista-meus-investimentos">
                                                </tbody>
                                                <tfoot>
                                                    <tr>
                                                        <td colspan="10">
                                                            <ul class="pagination pull-right"></ul>
                                                        </td>                                                        
                                                    </tr>
                                                </tfoot>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <hr class="hr-line-solid">
                                <div class="row">
                                    <div class="col col-lg-12 ">
                                        <h3><?php echo $idioma->getText("meuHistoricoRendimentos") ?></h3>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-12 col-xs-12">
                                        <div class="panel panel-default">
                                            <div class="panel-body">                    
                                                <div class="row">                                                    
                                                    <div class="col-lg-4">
                                                        <div data-toggle="buttons" class="btn-group" id="radioDatasConsolidado">
                                                            <label class="btn btn-sm btn-white" id="diaNota"> <input type="radio"  name="options" value="7">7 <?php echo $idioma->getText("invest38") ?></label>
                                                            <label class="btn btn-sm btn-white" id="semanaNota"> <input type="radio"  name="options" value="15">15 <?php echo $idioma->getText("invest38") ?></label>
                                                            <label class="btn btn-sm btn-white" id="mesNota"> <input type="radio"  name="options" value="30">30 <?php echo $idioma->getText("invest38") ?></label>
                                                            <label class="btn btn-sm btn-white active" id="todosNota"> <input type="radio"  name="options" value="todos"><?php echo $idioma->getText("invest39") ?></label>
                                                        </div>
                                                    </div>
                                                    <div class="col col-lg-3 m-t-xs">                     
                                                        <?php echo $idioma->getText("saldoConsolidado") ?>
                                                        <input type="checkbox" id="consolidado" class="js-switch" onchange="listarHistoricoRendimentos();" checked/>
                                                    </div> 
                                                </div>                                      
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col col-lg-12 ">
                                        <div class="table-responsive">
                                            <table id="tblConsolidado" class="table table-striped text-center" data-page-size="14"  style="font-size: 11px;">
                                                <thead>
                                                    <tr> 
                                                        <th class="text-center"><?php echo $idioma->getText("rendimentosData") ?></th>
                                                        <th class="text-center"><?php echo $idioma->getText("rendimentosMoeda") ?></th>
                                                        <th class="text-center"><?php echo $idioma->getText("rendimentosDescricao") ?></th>
                                                        <th class="text-center"><?php echo $idioma->getText("rendimentosValor") ?></th>
                                                    </tr>
                                                </thead>
                                                <tbody id="lista-meus-rendimentos">
                                                </tbody>
                                                <tfoot>
                                                    <tr>
                                                        <td colspan="4">
                                                            <ul class="pagination pull-right"></ul>
                                                        </td>                                                        
                                                    </tr>
                                                </tfoot>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <?php } ?>
                            <?php if($investimentoAtivo) { ?>
                            <div id="tab-investimento-5" class="tab-pane">
                                <div class="row">
                                    <div class="col col-lg-12">
                                        <div class="">
                                            <h2 class="page-header" style="margin-top: 0px !important;"><strong><?php echo $idioma->getText("invest23") ?></strong></h2>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col col-lg-12 ">
                                        <div class="table-responsive">
                                            <table id="tblResgatar" class="table table-striped text-center" data-page-size="5"  style="font-size: 11px;">
                                                <thead>
                                                    <tr> 
                                                        <th class="text-center"><?php echo $idioma->getText("moeda") ?></th>
                                                        <th class="text-center"><?php echo $idioma->getText("cofreTabelaMeusInvestimentosControle") ?></th>
                                                        <th class="text-center"><?php echo $idioma->getText("descricao") ?></th>
                                                        <th class="text-center"><?php echo $idioma->getText("dataDeposito") ?></th>
                                                        <th class="text-center"><?php echo $idioma->getText("saldoDepositado") ?></th>
                                                        <th class="text-center"><?php echo $idioma->getText("saldoRendimentos") ?></th>
                                                        <th class="text-center"><?php echo $idioma->getText("saldoTotal") ?></th>
                                                        <th class="text-center"><?php echo $idioma->getText("vencimentoContrato") ?></th>
                                                        <th class="text-center">Status</th>
                                                        <th class="text-center"><?php echo $idioma->getText("sacar") ?></th>
                                                    </tr>
                                                </thead>

                                                <tbody id="listaResgatar">

                                                </tbody>
                                                <tfoot>
                                                    <tr>
                                                        <td colspan="10">
                                                            <ul class="pagination pull-right"></ul>
                                                        </td>                                                        
                                                    </tr>
                                                </tfoot>
                                            </table>
                                        </div>
                                    </div>
                                </div>   
                                <hr class="hr-line-solid">
                                <div class="row">
                                    <div class="col-lg-7">
                                        <div class="text-center" id="carregar" hidden="true">
                                            <img src='<?php echo IMAGES ?>loading.gif' />
                                        </div>
                                        <div id="2faResgatar" hidden="true">
                                            <div class="row">                                                    
                                                <div class="col col-lg-6">                                                  
                                                    <div class="form-group">
                                                        <label><?php echo $idioma->getText("informePin") ?> </label> 
                                                        <input type="password"  class="form-control" id="modalSacarInvestimentoPin">
                                                    </div>
                                                </div>
                                                <div class="col col-lg-6">  
                                                    <div class="form-group">
                                                        <label><?php echo $idioma->getText("informeToken") ?></label> 
                                                        <input type="text"  inputmode="numeric" pattern="[0-9]*" class="form-control" id="modalSacarInvestimentoToken">
                                                        <?php if ($autenticacao === "email") { ?>
                                                            <a onclick="reenviarToken();"><?php echo $idioma->getText("invest18") ?></a>
                                                        <?php } ?>                                                    
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row">  
                                                <div class="col-lg-6">
                                                    <button type="button" class="btn btn-success full-width" onclick="sacarInvestimento();"  id="btnResgatar"><?php echo $idioma->getText("invest25") ?></button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-5">
                                        <div id="vertical-timeline" class="vertical-container light-timeline no-margins">
                                            <div class="vertical-timeline-block">
                                                <div class="vertical-timeline-icon blue-bg">
                                                    <i class="fa fa-info fa-1x"></i>
                                                </div>
                                                <div class="vertical-timeline-content">
                                                    <strong class="text-center"><h5><?php echo $idioma->getText("informacoes") ?></h5></strong>
                                                    <small><ul>
                                                            <li class="m-t-xs"><?php echo $idioma->getText("resgatePode") ?></li>
                                                            <li class="m-t-xs"><?php echo str_replace("{var1}",$configuracao->prazoDiasSaqueCofre, $idioma->getText("info3")) ?></li>                                                            
                                                        </ul>                                                
                                                    </small> 
                                                </div>
                                            </div>                                            
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <?php } ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="<?php echo TEMA; ?>js/plugins/chartJs/Chart.min.js"></script> 
<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>
<script src="<?php echo TEMA; ?>js/plugins/ionRangeSlider/ion.rangeSlider.min.js"></script>
<script src="<?php echo TEMA; ?>js/plugins/switchery/switchery.js"></script>
<script src="<?php echo TEMA; ?>js/plugins/flot/jquery.flot.js"></script>
<script src="<?php echo TEMA; ?>js/plugins/flot/jquery.flot.tooltip.min.js"></script>
<script src="<?php echo TEMA; ?>js/plugins/flot/jquery.flot.resize.js"></script>

<script>
    var dataConsolidado = 'todos';
    var meses = [];
    var lucroNc = [];
    var lucroPoup = [];
    var lucroTesouro = [];
    var lucroImoveis = [];
    var dados = [];
    var mesQtd = 9;
    var indiceMes = 6;
    var valorAtual = 2.5;
    var saldoDisponivelDeposito = 0;
    var investimento = 0;
    var numGrafico = [];
    var finalGrafico = [];
    var labels = [];
    var newc = '<?php echo $idioma->getText("invest26")?>';
    var poup = '<?php echo $idioma->getText("invest27")?>';
    var imovel = '<?php echo $idioma->getText("invest28")?>';
    var tesouro = '<?php echo $idioma->getText("invest29")?>';
    var valAux = $("#valor");
    var mesAux = $("#mes");
    var volumeAux = 0;
    var dadosCliente = [];
    var dadosClienteRend = [];
    var dadosEmpresa = [];
    var dadosEmpresaRend = [];
    var volumeEmpresa = 0;
    
    $(document).ready(function () {
        
        dadosGrafico();
        dadosEmpresaInvest();
        getSaldoCofre();
        listarContratos();
        
        labels.push(poup);
        labels.push(tesouro);
        labels.push(imovel); 
        labels.push(newc); 
        
        $("#radioDatasConsolidado input").on('change', function(){
            dataConsolidado = $('input[name="options"]:checked', '#radioDatasConsolidado').val();
            listarHistoricoRendimentos();   
        });
        
        loadCheckBox();
        $('#tblConsolidado').footable();
        $('#tblMeusInvestimentos').footable();
        $('#tblResgatar').footable();
        menuDinamico('liEmpresa');
        
        $("#valor").on("change", function () {
            valorAtual = 0;
            finalGrafico = [0, 0, 0, 0];    
            calcular();
        });
        
        $("#contratos").on("change", function () {  
            calcularInvestimento();
        });
        
        $("#mes").on("change", function () {
            finalGrafico = [0, 0, 0, 0];            
            calcular();         
        });
        
        $("#volumeInvestimento").keydown(function (event) {
            $(this).val(currency($(this).val(), 8, 8, event.keyCode));
            event.preventDefault();
            volumeAux = ($("#volumeInvestimento").val().length > 0 ? parseFloat(toFloat($("#volumeInvestimento").val())) : 0.00);
            
            if(volumeAux > 0){
                calcularInvestimento(); 
            }                 
        });
    });
    
    function contador(par2, par3) {
        Number.prototype.numberFormat1 = function(decimals, dec_point, thousands_sep) {
        dec_point = typeof dec_point !== 'undefined' ? dec_point : '.';
        thousands_sep = typeof thousands_sep !== 'undefined' ? thousands_sep : '';

        var parts = this.toFixed(decimals).split('.');
        parts[0] = parts[0].replace(/\B(?=(\d{3})+(?!\d))/g, thousands_sep);

        return parts.join(dec_point);
        };

        var counter = { var2: 0,
                        var3: 0};

         TweenMax.to(counter, 1, {
              var2: par2,
              var3: par3,

              onUpdate: function () {                      
                  var nwc2 = counter.var2.numberFormat1(8);
                  var nwc3 = counter.var3.numberFormat1(8);

                  $("#totalEmpresaInvest").html(nwc2);
                  $("#totalClienteInvest").html(nwc3);       
              },
              ease:Circ.easeOut
          });
    }

    function graficoDashboard() {
        var dataCliente = [
                { label: "Data 1", data: dadosClienteRend, color: '#127e68'},
                { label: "Data 2", data: dadosCliente, color: '#17a084' }
            ];
            
        var dataEmpresa = [
                { label: "Data 1", data: dadosEmpresaRend, color: '#127e68'},//'#17a084'
                { label: "Data 2", data: dadosEmpresa, color: '#17a084' } //'#127e68'
            ];
        
        $.plot($("#flot-chart1"), dataEmpresa, {
            xaxis: {
                tickDecimals: 0
            },
            series: {
                lines: {
                    show: true,
                    fill: true,
                    fillColor: {
                        colors: [{
                            opacity: 0.95
                        }, {
                            opacity: 0.95
                        }]
                    }
                },
                points: {
                    width: 0.1,
                    show: false
                }
            },
            grid: {
                show: false,
                borderWidth: 0
            },
            legend: {
                show: false
            }
        });

         $.plot($("#flot-chart2"), dataCliente, {
            xaxis: {
                tickDecimals: 0
            },
            series: {
                lines: {
                    show: true,
                    fill: true,
                    fillColor: {
                        colors: [{
                            opacity: 0.95
                        }, {
                            opacity: 0.95
                        }]
                    }
                },
                points: {
                    width: 0.1,
                    show: false
                }
            },
            grid: {
                show: false,
                borderWidth: 0
            },
            legend: {
                show: false
            }
        });
    }
    
    function dadosGrafico() {            
        $.ajax({
            url: "<?php echo URLBASE_CLIENT . Rotas::R_COFRE_DADOS_GRAFICO ?>",
            method: "post",
            dataType: "json",
            
            success: function (json) {
                try {
                    if (json.sucesso) {
                        dadosCliente = json.dadosCliente;
                        dadosClienteRend = json.dadosClienteRend;
                        dadosEmpresa = json.dadosEmpresa;
                        dadosEmpresaRend = json.dadosEmpresaRend;
                        graficoDashboard();
                    } else {                        
                        
                    }
                } catch(e) {                    
                }
            }
        });
    }
    
    function dadosEmpresaInvest() {    
        $("#dadosEmpresa").html("<tr><td class='text-center' colspan='1' ><img src='<?php echo IMAGES ?>loading.gif' /></td><tr>");
        $.ajax({
            url: "<?php echo URLBASE_CLIENT . Rotas::R_COFRE_DADOS_EMPRESA ?>",
            method: "post",
            dataType: "json",
            
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#dadosEmpresa").html(json.htmlEmpresa);
                        volumeEmpresa = json.totalEmpresa;
                    } else {                        
                        $("#dadosEmpresa").html("<tr><td class='text-center' colspan='1' >"+json.mensagem+"</td><tr>");
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch(e) {                    
                    $("#dadosEmpresa").html("<tr><td class='text-center' colspan='1' >"+e+"</td><tr>");
                    showNotyAlert(e, "e");
                }
            }
        });
    }
    
    function calcularInvestimento() {
        var totalInvest = 0;
        var porcMes = $("#contratos").val();
        var qtdMesAux = $("#contratos").val();
        var investVolume = volumeAux;
        var porcMesAux = null;
        
        if($("#contratos").val() === "0"){
           showNotyAlert("<?php echo $idioma->getText("invest37")?>", "e");           
        } else {            
            porcMes = parseFloat(porcMes.substr(porcMes.indexOf("|") + 1));
            qtdMesAux = parseFloat(qtdMesAux.substr(qtdMesAux.indexOf("?") + 1));
            porcMesAux = porcMes;
            porcMes = investVolume * (porcMes/ 100);
            totalInvest = investVolume + (porcMes * qtdMesAux);

            $("#mesesInvest").html("<?php echo $idioma->getText("invest51")?> " + qtdMesAux + " <?php echo $idioma->getText("invest52")?> " + porcMesAux +"%"); 
            $("#valorInvest").html(totalInvest.toFixed(8) + " BTC");           
        }
    }
    

    function marcaContratoResgate(contrato) {
        $('tr').css('background-color', '');
        $("#"+contrato).css('background-color', '#FFFFFF');
    }

    function saldoSlider(){
        
        var slider = valAux.data("ionRangeSlider");
        slider.update({
            skin: "modern",
            min: 0.0000,
            max: 5.0000,
            from: saldoDisponivelDeposito,
            step: 0.001,
            grid: false,
            postfix: " BTC"
        });
        valorAtual = saldoDisponivelDeposito;
        calcular();
    }
    
    function tempoSlider(mes){
        var instanceMes = mesAux.data("ionRangeSlider");
        instanceMes.update({
            skin: "modern",
            values: meses,
            type: 'single',
            grid: false,
            postfix: " Meses",
            from: mes
        });
        
        indiceMes = mes;
        calcular();
    }
    
    function calcular(){
        
        while (finalGrafico.length > 0) {
            finalGrafico.pop();
        }
        while (numGrafico.length > 0) {
            numGrafico.pop();
        }
        var valorVariavel = parseFloat(valorAtual);
        var porc = 0;
        var total = 0;

        numGrafico.push(parseFloat(lucroPoup[indiceMes]));
        numGrafico.push(parseFloat(lucroTesouro[indiceMes]));// Taxa de juros
        numGrafico.push(parseFloat(lucroImoveis[indiceMes])); // Taxa de juros
        numGrafico.push(parseFloat(lucroNc[indiceMes]));
       
        var mes1 = parseFloat(meses[indiceMes]); // Tempo

        for(i = 0; i < numGrafico.length; i++) {
            porc = valorVariavel * (numGrafico[i] / 100);
            total = valorVariavel + (porc * mes1);
            finalGrafico.push(total);
        }
        
        grafico();
        $("#tempo").html(mes1);
        $("#valorBtc").html(finalGrafico[0].toFixed(4));   
    }
    
    function grafico(){   
        
       Chart.defaults.global.defaultFontColor = '#567AD7';
       Chart.defaults.global.defaultFontSize = 18;
       Chart.defaults.global.defaultFontStyle = 'bold';
       Chart.defaults.global.hover.intersect = false;
       Chart.defaults.global.animation.duration = 1000;
       
       var myChart = new Chart(document.getElementById("barChart"),
        {"type":"bar",
            "data":{"labels": labels,
                    "datasets":[{"label":true,
                        "data": finalGrafico,
                        "fill":false,"backgroundColor":[
                            "#AAB5C1",
                            "#6495ED",
                            "#248EFF",
                            "rgba(0, 174, 77, 0.9)"],
                        "borderColor":[
                            "rgba(155, 155, 155, 0.3)",
                            "rgba(67, 136, 203, 0.5)",
                            "rgba(67, 136, 203, 0.7)",
                            "rgba(0, 174, 77, 0.9)"],
                        "borderWidth":1}]},
                 "options":{
                      hover:{
                          mode: "NC"
                     },
                      title: {
                            display: true,
                            text: '<?php echo $idioma->getText("invest9") ?>',
                            fontSize: 30,
                            fontFamily: 'open sans',
                            padding: 25,
                            fontColor: "#676A6C"
                        },
                     events:[],
                     responsive: true,                     
                tooltips: {                    
                    enabled: false
                },                                
                animation: {              
                    onComplete: function () {
                        var chartInstance = this.chart,
                        ctx = chartInstance.ctx;
                        ctx.textAlign = 'center';
                        ctx.fillStyle = "#485884";
                        ctx.textBaseline = 'bottom';
                        ctx.font = "600 18px open sans";

                        this.data.datasets.forEach(function (dataset, i) {
                            var meta = chartInstance.controller.getDatasetMeta(i);
                            meta.data.forEach(function (bar, index) {
                                var data = dataset.data[index];
                                data = data.toFixed(4) + " BTC";
                                ctx.fillText(data, bar._model.x, bar._model.y - 5);
                            });
                        });
                    }
                },
                legend:{
                    display: false
                },
                scales: {
                xAxes: [{                     
                    position: 'top',
                    offset: true,
                    barPercentage: 0.7, 
                    
                    ticks:{
                        padding: 0 },
                    gridLines: {
                        tickMarkLength: 50,
                        hidden: false,
                        display:false,
                        drawBorder: false
                    }
                }],
                yAxes: [{  
                        ticks:{
                        suggestedMin: 0.000,
                        suggestedMax: 6.000,
                        stepSize: 0.0010,
                        display: false,
                        beginAtZero: true },                    
                        display: false,
                    gridLines: {                         
                        hidden: true,
                        display:false
                    }   
                }]
            }}});


    }
    
    function listarHistoricoRendimentos() {    
        $("#lista-meus-rendimentos").html("<tr><td class='text-center' colspan='4' ><img src='<?php echo IMAGES ?>loading.gif' /></td><tr>");
        $.ajax({
            url: "<?php echo URLBASE_CLIENT . Rotas::R_COFRE_RENDIMENTOS_FILTRAR ?>",
            method: "post",
            dataType: "json",
            data: {
                moeda: $("#filtroMoeda").val(),
                dias: dataConsolidado,
                consolidado: $("#consolidado").is(":checked")
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#lista-meus-rendimentos").html(json.html);
                        $('#tblConsolidado').trigger('footable_initialize');
                        
                    } else {
                        $("#lista-meus-rendimentos").html("<tr><td class='text-center' colspan='4' >"+json.mensagem+"</td><tr>");
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch(e) {
                    $("#lista-meus-rendimentos").html("<tr><td class='text-center' colspan='4' >"+e+"</td><tr>");
                    showNotyAlert(e, "e");
                }
            }
        });
    }
    
    function listarInvestimentos() {
        $("#lista-meus-investimentos").html("<tr><td class='text-center' colspan='9' ><img src='<?php echo IMAGES ?>loading.gif' /></td><tr>");
        $.ajax({
            url: "<?php echo URLBASE_CLIENT . Rotas::R_COFRE_LISTAR ?>",
            method: "post",
            dataType: "json",
            data:{
                resgate: false
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#lista-meus-investimentos").html(json.html);
                        $('#tblMeusInvestimentos').trigger('footable_initialize');
                    } else {
                        $("#lista-meus-investimentos").html("<tr><td class='text-center' colspan='9' >"+json.mensagem+"</td><tr>");
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch(e) {
                    $("#lista-meus-investimentos").html("<tr><td class='text-center' colspan='9' >"+e+"</td><tr>");
                    showNotyAlert(e, "e");
                }
            }
        });
    }
    
    function listarResgate() {
        $("#listaResgatar").html("<tr><td class='text-center' colspan='10' ><img src='<?php echo IMAGES ?>loading.gif' /></td><tr>");
        $.ajax({
            url: "<?php echo URLBASE_CLIENT . Rotas::R_COFRE_LISTAR ?>",
            method: "post",
            dataType: "json",
            data:{
                resgate: true
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#listaResgatar").html(json.html);
                        $('#tblResgatar').trigger('footable_initialize');
                    } else {
                        $("#listaResgatar").html("<tr><td class='text-center' colspan='10' >"+json.mensagem+"</td><tr>");
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch(e) {
                    $("#listaResgatar").html("<tr><td class='text-center' colspan='10' >"+e+"</td><tr>");
                    showNotyAlert(e, "e");
                }
            }
        });
    }
    
    function listarContratos() {
        $("#tempoLucro").html("<tr><td class='text-center' colspan='2' ><img src='<?php echo IMAGES ?>loading.gif' /></td><tr>");
        $.ajax({
            url: "<?php echo URLBASE_CLIENT . Rotas::R_COFRE_CONTRATOS_LISTAR ?>",
            method: "post",
            dataType: "json",

            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#tempoLucro").html(json.html);
                        for(i = 0; i < json.meses.length; i++){
                            meses[i] = parseInt(json.meses[i]); 
                            lucroPoup[i] = json.lucroPoup[i];
                            lucroTesouro[i] = json.lucroTes[i]; 
                            lucroImoveis[i] = json.lucroImo[i];
                            lucroNc[i] = json.lucro[i];                            
                        }    
                        
                            $("#mes").ionRangeSlider({
                                skin: "modern",
                                values: meses,
                                type: 'single',
                                grid: false,
                                postfix: " Meses",
                                from: 6,
                                onFinish: function (data) {
                                    mesQtd  = parseInt(data.from_value);
                                    indiceMes = meses.indexOf(mesQtd);                                    
                                    calcular();                                   
                                }
                            });

                            $("#valor").ionRangeSlider({
                                skin: "modern",
                                min: 0.00,
                                max: 5.0000,
                                from: 2.500,
                                step: 0.001,
                                grid: false,
                                postfix: " BTC",
                                onFinish: function (data) {
                                    valorAtual = data.from;
                                    calcular();
                                }
                            }); 
                            
                            calcular();
                    } else {
                        $("#tempoLucro").html("<tr><td class='text-center' colspan='2' ><img src='<?php echo IMAGES ?>loading.gif' /></td><tr>");                        
                    }
                } catch(e) {
                    $("#tempoLucro").html("<tr><td class='text-center' colspan='2' ><img src='<?php echo IMAGES ?>loading.gif' /></td><tr>");
                }
            }
        });
        
        aux = 1;
    }
    
    
    
    function cadastrar() {
        $("#modalCadastrarMoedaForm").submit();
    }
    
    function menuDinamico(li) {
        $("li").removeClass("active");
        $("#"+li).addClass("active");
    }
    
    function loadCheckBox(){      
        
        var elems = Array.prototype.slice.call(document.querySelectorAll('.js-switch'));
        elems.forEach(function(html) {
          var switchery = new Switchery(html, {
                color: '#00cf7a', size: 'small', disabledOpacity: 0.3
                });
        });
    }
    
    function reenviarToken() {        
        $("#btnToken").hide();
        $("#2fa").show();
        $("#btnDepositar").show();        
        $.ajax({
            url: "<?php echo URLBASE_CLIENT . Rotas::R_COFRE_TOKEN ?>",
            method: "post",
            dataType: "json",
            success: function (json) {
                try {
                    if (json.sucesso) {
                        showNotyAlert(<?php echo $idioma->getText("foiEnviadoTokenEmailCel")?>, "s");
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch(e) {
                    showNotyAlert(e, "e");
                }
            }
        });
    }
    
    function depositarMeuSaldo() {
        $("#volumeInvestimento").val(saldoDisponivelDeposito.toFixed(8).replace(".", ","));
        volumeAux = saldoDisponivelDeposito;
        calcularInvestimento(); 
    }
    
    function depositar() {
        var contrato = $("#contratos").val();
        var contratoId = contrato.substr(0, contrato.indexOf('|'));
        $("#modalDepositarCancelar, #modalDepositarReenviar, #modalDepositarConfirmar").prop("disabled", true);
        $.ajax({
            url: "<?php echo URLBASE_CLIENT . Rotas::R_COFRE_DEPOSITAR ?>",
            method: "post",
            dataType: "json",
            data: {
                volume: $("#volumeInvestimento").val(),
                token: $("#modalDepositarToken").val(),
                pin: $("#modalDepositarPin").val(),
                descricao: $("#modalDepositarSaldoDescricao").val(),
                contrato: contratoId
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        showNotyAlert(json.mensagem, "s");
                        getSaldoCofre($("#modalDepositarMoeda").val());
                        //listarInvestimentos();
                        location.reload();
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch(e) {
                    showNotyAlert(e, "e");
                }
                $("#modalDepositarCancelar, #modalDepositarReenviar, #modalDepositarConfirmar").prop("disabled", false);
            }
        });        
    }
    
    function getSaldoCofre() {
        $("#dadosCliente").html("<tr><td class='text-center' colspan='1' ><img src='<?php echo IMAGES ?>loading.gif' /></td><tr>");
        $.ajax({
            url: "<?php echo URLBASE_CLIENT . Rotas::R_COFRE_SALDO ?>",
            method: "post",
            dataType: "json",            
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#dadosCliente").html(json.htmlCliente);
                        saldoDisponivelDeposito = parseFloat(json.saldo);
                        $("#depositado").html(json.depositado + " BTC");
                        $("#rendimento").html(json.rendimento.replace(".", ","));
                        $("#recebido").html(json.recebido.replace(".", ","));
                        $("#saldo").html(json.saldo + " BTC");
                        contador(volumeEmpresa, json.investidoRendimento);
                    } else {
                        showNotyAlert(json.mensagem, "e");
                         $("#dadosCliente").html("<tr><td class='text-center' colspan='1' ><img src='<?php echo IMAGES ?>loading.gif' /></td><tr>");
                    }
                } catch(e) {
                    showNotyAlert(e, "e");
                    $("#dadosCliente").html("<tr><td class='text-center' colspan='1' ><img src='<?php echo IMAGES ?>loading.gif' /></td><tr>");
                }
            }
        });
    }
    
    function saqueInvestimentoToken(invest){
        investimento = invest;
        $("#carregar").show();
        reenviarToken();
        $("#carregar").hide();
        $("#2faResgatar").show();
    }
    
    function sacarInvestimento() {
        $("#btnResgatar").prop("disabled", true);
        $.ajax({
            url: "<?php echo URLBASE_CLIENT . Rotas::R_COFRE_RETIRADA_SACAR ?>",
            method: "post",
            dataType: "json",
            data: {
                token: $("#modalSacarInvestimentoToken").val(),
                pin: $("#modalSacarInvestimentoPin").val(),
                investimento: investimento
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        showNotyAlert(json.mensagem, "s");
                        location.reload();
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch(e) {
                    showNotyAlert(e, "e");
                }
                $("#btnResgatar").prop("disabled", false);
                
            }
        });
        
    }
    
</script>


