<?php Utils\Layout::append("inspina/metas", $_data) ?>

<?php Utils\Layout::append("inspina/scripts", $_data) ?>
<?php
$moeda = \Modules\principal\Controllers\Principal::getCurrency();
$idioma= new \Utils\PropertiesUtils("notificacoes", IDIOMA);
?>
<style>
    code {
        white-space: pre-wrap;
        color: #047cc1;
    }
    code i {
        color: #545454;
    }
    
    
    .panel-heading.unread {
        
    }
    
    .panel-heading.read {
        background-color: #ffffff !important;
        font-weight: normal;
    }
    
    
    .panel-heading.unread .panel-title .icheckbox_square-green{
        margin-top: -10px;
    }
</style>

<?php Utils\Layout::append("inspina/menu", $_data) ?>


<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="row wrapper border-bottom page-heading" style="background: linear-gradient(to right, #fff, <?php echo $moeda->mainColor ?>) !important;">
        <div class="col-lg-10">
            <h2><?php echo $idioma->getText("titulo") ?></h2>

        </div>
    </div>
</div>
<br>      

<div class="wrapper wrapper-content animated fadeInRight">
     <div class="ibox-content">
                <div class="text-center">
                    <h2><strong><?php echo $idioma->getText("subTitulo") ?></strong></h2>
                </div>
            </div>
            <br>
            
            <div class="mail-box-header">
                <div class="row">
                <div class="col-lg-12 col-xs-12">
                <div class="mail-tools tooltip-demo">
                    <div class="col-lg-9 col-xs-12">
                    <button class="btn btn-white btn-sm" onclick="selecionarNaoLidas();" data-toggle="tooltip" data-placement="top" title="" data-original-title="Seleciona não lidas"><i class="fa fa-check"></i> <?php echo $idioma->getText("selNaoLidas") ?></button>
                    <button class="btn btn-white btn-sm" onclick="refresh();" data-toggle="tooltip" data-placement="top" title="" data-original-title="Atualizar"><i class="fa fa-refresh"></i> <?php echo $idioma->getText("atualizar") ?></button>
                    <button class="btn btn-white btn-sm" onclick="markAsRead();" data-toggle="tooltip" data-placement="top" title="Marcar como lida"><i class="fa fa-eye"></i> </button>
                    </div>
                    <div class="col-lg-3 col-xs-12 m-t-xs">
                    <form method="get" action="index.html" class="mail-search">
                    <div class="input-group">
                        <input type="text" class="form-control input-sm full-width" name="search" id="search" placeholder="<?php echo $idioma->getText("pesquisarMensagem") ?>">
                        <div class="input-group-btn">
                            <button type="button" class="btn btn-sm btn-primary full-width" onclick="refresh();">
                                <?php echo $idioma->getText("pesquisar") ?>
                            </button>
                        </div>
                    </div>
                    </form>
                    </div>
                </div>
                    </div>
                    </div>
            </div>
    
            <div class="row">
                <div class="col-lg-12">
                    <div class="ibox float-e-margins">

                        <div class="ibox-content">

                            <div class="panel-group" id="accordion">
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>




<div class="clearfix"></div>
</div>

<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>

<script>
    //var ft = null;
    //var ft = $('#table-mensagens').footable();
    $(document).ready(function(){
        
        filtrarMensagens();
    });
    
    
    
    var page = 1;
    function filtrarMensagens() {
        $(".no-more-messages").remove();
        $("#body-notifications").append("<tr class='unread no-more-messages'> <td class='mail-contact text-center'  colspan='4'> <img src='<?php echo IMAGES ?>loading.gif' style='width: 50px;' /> </td> </tr>");
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_NOTIFICACOES_ALL_FILTRAR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                filtro: $("#search").val(),
                pagina: page
            },
            success: function (json)  {
                try {
                    if (json.sucesso) {
                        $(".no-more-messages").remove();
                        $("#accordion").append(json.html);
                        
                        $('.i-checks-page-' + page).iCheck({
                            checkboxClass: 'icheckbox_square-green',
                            radioClass: 'iradio_square-green',
                        });
                        
                        
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
            }
        });
    }

    function nextPage() {
        page++;
        filtrarMensagens();
    }
    
    function refresh() {
        page = 1;
        $("#accordion").empty();
        filtrarMensagens();
    }
    
    
    function markAsRead() {
        
        var ids = [];
        $(".notification-check:checked").each(function () {
            ids.push($(this).val());
        });
        
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_NOTIFICACOES_READ ?>',
            method: 'post',
            dataType: 'json',
            data: {
                notificacoes: ids
            },
            success: function (json)  {
                try {
                    if (json.sucesso) {
                        var i = 0;
                        for(i=0; i < json.notificacoes.length; i++) {
                            var tr = $(".tr-"+json.notificacoes[i]);
                            $(tr).removeClass("unread").addClass("read").children("h5").first().children("div").first().children("input").first().iCheck("uncheck");
                            $(tr).children("h5").first().children("i").first().remove();
                        }
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
            }
        });
        
        
    }
    
    
    function selecionarNaoLidas() {
        $(".unread").each(function(){
            var input = $(this).children("h5").first().children("div").first().children("input").first();
            console.log(input);
            
            $(input).iCheck("toggle");
        });
    }
</script>

