<?php

$usuario = Utils\Geral::getLogado();


$brl = (isset($_data["brl"]) ? $_data["brl"] : new Models\Modules\Cadastro\Moeda());
$bitcoin = (isset($_data["bitcoin"]) ? $_data["bitcoin"] : new Models\Modules\Cadastro\Moeda());
$ethereum = (isset($_data["ethereum"]) ? $_data["ethereum"] : new Models\Modules\Cadastro\Moeda());
$litecoin = (isset($_data["litecoin"]) ? $_data["litecoin"] : new Models\Modules\Cadastro\Moeda());
$dash = (isset($_data["dash"]) ? $_data["dash"] : new Models\Modules\Cadastro\Moeda());
?>


<?php Utils\Layout::append("inspina/metas", $_data) ?>

<?php Utils\Layout::append("inspina/scripts", $_data) ?>

<style>
    
    @media(max-width: 991px) {
        .file-box {
            width: 98% !important;
            margin-left: 1% !important;
            margin-right: 1% !important;
        }
    }
    
    @media(min-width: 992px) and (max-width: 1300px) {
        .file-box {
            width: 48% !important;
            margin-left: 1% !important;
            margin-right: 1% !important;
            min-height: 350px !important;
        }
    }
    
    @media(min-width: 1301px) {
        .file-box {
            width: 31.3% !important;
            margin-left: 1% !important;
            margin-right: 1% !important;
            min-height: 350px !important;
        }
    }
    
</style>

<?php Utils\Layout::append("inspina/menu", $_data) ?>




<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Painel de Monitoramento</h2>
            <ol class="breadcrumb">
                <li>
                    Monitoramento
                </li>
                <li class="active">
                    <strong>Painel</strong>
                </li>
            </ol>
        </div>
    </div>
</div>

    <!-- Main content -->
<section class="content">
    
    <br><br>
    
    <div class="ibox-content">

        <div class="row">
            <div class="col col-12">
                
                <table class="table table-hover table-condensed table-striped table-bordered">
                    <thead>
                        <tr>
                            <th colspan="2" class="text-center">
                                Progresso da ICO NEWC Token
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><strong>Tokens distribuidos:</strong></td>
                            <td class="text-right" ><span id="tokens-distribuidos-ico"></span></td>
                        </tr>
                        <tr>
                            <td><strong>Tokens restantes:</strong></td>
                            <td class="text-right" ><span id="tokens-restantes-ico"></span></td>
                        </tr>
                        <tr>
                            <td><strong>Tokens vendidos:</strong></td>
                            <td class="text-right" ><span id="tokens-vendidos-ico"></span></td>
                        </tr>
                        <tr>
                            <td><strong>Tokens bonificados:</strong></td>
                            <td class="text-right" ><span id="tokens-bonificados-ico"></span></td>
                        </tr>
                        <tr>
                            <td><strong>BRL Arrecadado:</strong></td>
                            <td class="text-right" ><span id="tokens-brl-arrecadado-ico"></span></td>
                        </tr>
                        <tr>
                            <td><strong>BTC Arrecadado:</strong></td>
                            <td class="text-right" ><span id="tokens-btc-arrecadado-ico"></span></td>
                        </tr>
                        <tr>
                            <td><strong>LTC Arrecadado:</strong></td>
                            <td class="text-right" ><span id="tokens-ltc-arrecadado-ico"></span></td>
                        </tr>
                        <tr>
                            <td><strong>ETH Arrecadado:</strong></td>
                            <td class="text-right" ><span id="tokens-eth-arrecadado-ico"></span></td>
                        </tr>
                        <tr>
                            <td><strong>DASH Arrecadado:</strong></td>
                            <td class="text-right" ><span id="tokens-dash-arrecadado-ico"></span></td>
                        </tr>
                        <tr>
                            <td colspan="2">
                                <div class="progress">
                                    <div style="width: 0%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="0" id="progress-ico" role="progressbar" class="progress-bar progress-bar-success">
                                        <span class="sr-only"></span>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
                
            </div>
        </div>
        
        <div class="row">
            
            <div class="col-lg-3">
                <div class="ibox">
                    <div class="ibox-content">
                        <h5>Arrecadação de Moedas</h5>
                        
                        <strong>
                            <span style="color: <?php echo $brl->mainColor ?>"><?php echo $brl->simbolo ?></span>,
                            <span style="color: <?php echo $bitcoin->mainColor ?>"><?php echo $bitcoin->simbolo ?></span>,
                            <span style="color: <?php echo $ethereum->mainColor ?>"><?php echo $ethereum->simbolo ?></span>,
                            <span style="color: <?php echo $litecoin->mainColor ?>"><?php echo $litecoin->simbolo ?></span>,
                            <span style="color: <?php echo $dash->mainColor ?>"><?php echo $dash->simbolo ?></span>
                        </strong>
                        
                        <div class="text-center">
                            <div id="spark-arrecadacao-ico"></div>
                        </div>
                        
                    </div>
                </div>
            </div>
            
            <div class="col-lg-3">
                <div class="ibox">
                    <div class="ibox-content">
                        <h5>Relação de Tokens Vendidos x Bonificados</h5>
                        
                        <strong>
                            <span style="color: #1ab394;">Vendidos</span>,
                            <span style="color: #1c84c6;">Bonificados</span>.
                        </strong>
                        
                        <div class="text-center">
                            <div id="spark-relacao-venda-bonificacao-ico"></div>
                        </div>
                        
                    </div>
                </div>
            </div>
            
            <div class="col-lg-3">
                <div class="ibox">
                    <div class="ibox-content">
                        <h5>Distribuição de Tokens Por Categoria</h5>
                        
                        <strong>
                            <span style="color: #1ab394;">Vendidos</span>,
                            <span style="color: #1c84c6;">Bonificações</span>,
                            <span style="color: #f8ac59;">Compartilhamentos, redes sociais.</span>.
                        </strong>
                        
                        <div class="text-center">
                            <div id="spark-relacao-distribuicao-categoria-ico"></div>
                        </div>
                        
                    </div>
                </div>
            </div>
            
        </div>
        
        <div class="row">
            <div class="col col-xs-4">
                <table class="table table-hover table-condensed table-striped table-bordered">
                    <thead>
                        <tr>
                            <th colspan="2" class="text-center">
                                Status da Pré-venda
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><strong>Tokens distribuidos:</strong></td>
                            <td class="text-right" ><span id="tokens-distribuidos-fase-1"></span></td>
                        </tr>
                        <tr>
                            <td><strong>Tokens restantes:</strong></td>
                            <td class="text-right" ><span id="tokens-restantes-fase-1"></span></td>
                        </tr>
                        <tr>
                            <td><strong>Tokens vendidos:</strong></td>
                            <td class="text-right" ><span id="tokens-vendidos-fase-1"></span></td>
                        </tr>
                        <tr>
                            <td><strong>Tokens bonificados:</strong></td>
                            <td class="text-right" ><span id="tokens-bonificados-fase-1"></span></td>
                        </tr>
                        <tr>
                            <td><strong>BRL Arrecadado:</strong></td>
                            <td class="text-right" ><span id="tokens-brl-arrecadado-fase-1"></span></td>
                        </tr>
                        <tr>
                            <td><strong>BTC Arrecadado:</strong></td>
                            <td class="text-right" ><span id="tokens-btc-arrecadado-fase-1"></span></td>
                        </tr>
                        <tr>
                            <td><strong>LTC Arrecadado:</strong></td>
                            <td class="text-right" ><span id="tokens-ltc-arrecadado-fase-1"></span></td>
                        </tr>
                        <tr>
                            <td><strong>ETH Arrecadado:</strong></td>
                            <td class="text-right" ><span id="tokens-eth-arrecadado-fase-1"></span></td>
                        </tr>
                        <tr>
                            <td><strong>DASH Arrecadado:</strong></td>
                            <td class="text-right" ><span id="tokens-dash-arrecadado-fase-1"></span></td>
                        </tr>
                        <tr>
                            <td colspan="2">
                                <div class="progress">
                                    <div style="width: 0%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="0" id="progress-fase-1" role="progressbar" class="progress-bar progress-bar-success">
                                        <span class="sr-only"></span>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
                
            </div>
            <div class="col col-xs-4">
                <table class="table table-hover table-condensed table-striped table-bordered">
                    <thead>
                        <tr>
                            <th colspan="2" class="text-center">
                                Status da Fase 1
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><strong>Tokens distribuidos:</strong></td>
                            <td class="text-right" ><span id="tokens-distribuidos-fase-2"></span></td>
                        </tr>
                        <tr>
                            <td><strong>Tokens restantes:</strong></td>
                            <td class="text-right" ><span id="tokens-restantes-fase-2"></span></td>
                        </tr>
                        <tr>
                            <td><strong>Tokens vendidos:</strong></td>
                            <td class="text-right" ><span id="tokens-vendidos-fase-2"></span></td>
                        </tr>
                        <tr>
                            <td><strong>Tokens bonificados:</strong></td>
                            <td class="text-right" ><span id="tokens-bonificados-fase-2"></span></td>
                        </tr>
                        <tr>
                            <td><strong>BRL Arrecadado:</strong></td>
                            <td class="text-right" ><span id="tokens-brl-arrecadado-fase-2"></span></td>
                        </tr>
                        <tr>
                            <td><strong>BTC Arrecadado:</strong></td>
                            <td class="text-right" ><span id="tokens-btc-arrecadado-fase-2"></span></td>
                        </tr>
                        <tr>
                            <td><strong>LTC Arrecadado:</strong></td>
                            <td class="text-right" ><span id="tokens-ltc-arrecadado-fase-2"></span></td>
                        </tr>
                        <tr>
                            <td><strong>ETH Arrecadado:</strong></td>
                            <td class="text-right" ><span id="tokens-eth-arrecadado-fase-2"></span></td>
                        </tr>
                        <tr>
                            <td><strong>DASH Arrecadado:</strong></td>
                            <td class="text-right" ><span id="tokens-dash-arrecadado-fase-2"></span></td>
                        </tr>
                        <tr>
                            <td colspan="2">
                                <div class="progress">
                                    <div style="width: 0%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="0" id="progress-fase-2" role="progressbar" class="progress-bar progress-bar-success">
                                        <span class="sr-only"></span>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="col col-xs-4">
                <table class="table table-hover table-condensed table-striped table-bordered">
                    <thead>
                        <tr>
                            <th colspan="2" class="text-center">
                                Status da Fase 2
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><strong>Tokens distribuidos:</strong></td>
                            <td class="text-right" ><span id="tokens-distribuidos-fase-3"></span></td>
                        </tr>
                        <tr>
                            <td><strong>Tokens restantes:</strong></td>
                            <td class="text-right" ><span id="tokens-restantes-fase-3"></span></td>
                        </tr>
                        <tr>
                            <td><strong>Tokens vendidos:</strong></td>
                            <td class="text-right" ><span id="tokens-vendidos-fase-3"></span></td>
                        </tr>
                        <tr>
                            <td><strong>Tokens bonificados:</strong></td>
                            <td class="text-right" ><span id="tokens-bonificados-fase-3"></span></td>
                        </tr>
                        <tr>
                            <td><strong>BRL Arrecadado:</strong></td>
                            <td class="text-right" ><span id="tokens-brl-arrecadado-fase-3"></span></td>
                        </tr>
                        <tr>
                            <td><strong>BTC Arrecadado:</strong></td>
                            <td class="text-right" ><span id="tokens-btc-arrecadado-fase-3"></span></td>
                        </tr>
                        <tr>
                            <td><strong>LTC Arrecadado:</strong></td>
                            <td class="text-right" ><span id="tokens-ltc-arrecadado-fase-3"></span></td>
                        </tr>
                        <tr>
                            <td><strong>ETH Arrecadado:</strong></td>
                            <td class="text-right" ><span id="tokens-eth-arrecadado-fase-3"></span></td>
                        </tr>
                        <tr>
                            <td><strong>DASH Arrecadado:</strong></td>
                            <td class="text-right" ><span id="tokens-dash-arrecadado-fase-3"></span></td>
                        </tr>
                        <tr>
                            <td colspan="2">
                                <div class="progress">
                                    <div style="width: 0%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="0" id="progress-fase-3" role="progressbar" class="progress-bar progress-bar-success">
                                        <span class="sr-only"></span>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        
        <div class="row">
            
            <div class="col-lg-4">
                <div class="ibox">
                    <div class="ibox-content">
                        <h5>Arrecadação de Moedas Pré-venda</h5>
                        
                        <strong>
                            <span style="color: <?php echo $bitcoin->mainColor ?>"><?php echo $bitcoin->simbolo ?></span>,
                            <span style="color: <?php echo $ethereum->mainColor ?>"><?php echo $ethereum->simbolo ?></span>,
                            <span style="color: <?php echo $litecoin->mainColor ?>"><?php echo $litecoin->simbolo ?></span>,
                            <span style="color: <?php echo $dash->mainColor ?>"><?php echo $dash->simbolo ?></span>
                        </strong>
                        
                        <div class="text-center">
                            <div id="spark-arrecadacao-fase-1"></div>
                        </div>
                        
                    </div>
                </div>
            </div>
            
            <div class="col-lg-4">
                <div class="ibox">
                    <div class="ibox-content">
                        <h5>Arrecadação de Moedas Fase 1</h5>
                        
                        <strong>
                            <span style="color: <?php echo $bitcoin->mainColor ?>"><?php echo $bitcoin->simbolo ?></span>,
                            <span style="color: <?php echo $ethereum->mainColor ?>"><?php echo $ethereum->simbolo ?></span>,
                            <span style="color: <?php echo $litecoin->mainColor ?>"><?php echo $litecoin->simbolo ?></span>,
                            <span style="color: <?php echo $dash->mainColor ?>"><?php echo $dash->simbolo ?></span>
                        </strong>
                        
                        <div class="text-center">
                            <div id="spark-arrecadacao-fase-2"></div>
                        </div>
                        
                    </div>
                </div>
            </div>
            
            <div class="col-lg-4">
                <div class="ibox">
                    <div class="ibox-content">
                        <h5>Arrecadação de Moedas Fase 2</h5>
                        
                        <strong>
                            <span style="color: <?php echo $bitcoin->mainColor ?>"><?php echo $bitcoin->simbolo ?></span>,
                            <span style="color: <?php echo $ethereum->mainColor ?>"><?php echo $ethereum->simbolo ?></span>,
                            <span style="color: <?php echo $litecoin->mainColor ?>"><?php echo $litecoin->simbolo ?></span>,
                            <span style="color: <?php echo $dash->mainColor ?>"><?php echo $dash->simbolo ?></span>
                        </strong>
                        
                        <div class="text-center">
                            <div id="spark-arrecadacao-fase-3"></div>
                        </div>
                        
                    </div>
                </div>
            </div>
            
        </div>
        
        <div class="row">    
            <div class="col-lg-4">
                <div class="ibox">
                    <div class="ibox-content">
                        <h5>Relação de Tokens Vendidos x Bonificados Pré-venda</h5>
                        
                        <strong>
                            <span style="color: #1ab394;">Vendidos</span>,
                            <span style="color: #1c84c6;">Bonificados</span>.
                        </strong>
                        
                        <div class="text-center">
                            <div id="spark-relacao-venda-bonificacao-fase-1"></div>
                        </div>
                        
                    </div>
                </div>
            </div>
            
            <div class="col-lg-4">
                <div class="ibox">
                    <div class="ibox-content">
                        <h5>Relação de Tokens Vendidos x Bonificados Fase 1</h5>
                        
                        <strong>
                            <span style="color: #1ab394;">Vendidos</span>,
                            <span style="color: #1c84c6;">Bonificados</span>.
                        </strong>
                        
                        <div class="text-center">
                            <div id="spark-relacao-venda-bonificacao-fase-2"></div>
                        </div>
                        
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="ibox">
                    <div class="ibox-content">
                        <h5>Relação de Tokens Vendidos x Bonificados Fase 2</h5>
                        
                        <strong>
                            <span style="color: #1ab394;">Vendidos</span>,
                            <span style="color: #1c84c6;">Bonificados</span>.
                        </strong>
                        
                        <div class="text-center">
                            <div id="spark-relacao-venda-bonificacao-fase-3"></div>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
        
        <div class="row">
            <div class="col col-xs-6">
                <h4>Ultimas Compras Efetuadas</h4>
                <table class="table table-condensed table-bordered table-striped table-hover" >
                    
                    <thead>
                        <th>Data</th>
                        <th>Cliente</th>
                        <th>Moeda</th>
                        <th>Volume</th>
                        <th>Tokens</th>
                    </thead>
                    
                    <tbody id="listaUltimasCompras">
                        
                    </tbody>
                    
                </table>
                    
            </div>
            
            <div class="col col-xs-6">
                <h4>Ultimas Bonificações</h4>
                <table class="table table-condensed table-bordered table-striped table-hover" >
                    
                    <thead>
                        <th>Data</th>
                        <th>Cliente</th>
                        <th>Tokens</th>
                    </thead>
                    
                    <tbody id="listaUltimasBonificacoes">
                        
                    </tbody>
                    
                </table>
                    
            </div>
        </div>
    </div>
        
</section>
    
<div class="clearfix"></div>

<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>

<script>
    $(document).ready(function () {
        initializePainel();
    });
    
    function initializePainel(){
        ultimasCompras();
        ultimasBonificacoes();
        dadosFases();
    }
    
    function ultimasCompras() {
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_PAINEL_ICO_ULTIMASCOMPRAS  ?>',
            method: 'post',
            dataType: 'json',
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#listaUltimasCompras").html(json.html);
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                
            },
            error: function () {
                
            }
        });
    }
    
    
    function ultimasBonificacoes() {
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_PAINEL_ICO_ULTIMASBONIFICACOES  ?>',
            method: 'post',
            dataType: 'json',
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#listaUltimasBonificacoes").html(json.html);
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                
            },
            error: function () {
                
            }
        });
    }
    
    function dadosFases() {
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_PAINEL_ICO_DADOSFASES  ?>',
            method: 'post',
            dataType: 'json',
            success: function (json) {
                try {
                    if (json.sucesso) {
                        var ico = json.ico;
                        if (json.fases.length > 0) {
                            
                            var i = 0;
                            for (i = 0; i < json.fases.length; i++) {
                                var fase = json.fases[i];
                                $("#tokens-distribuidos-fase-"+fase.codigo).html(fase.distribuidos);
                                $("#tokens-restantes-fase-"+fase.codigo).html(fase.disponiveis);
                                $("#progress-fase-"+fase.codigo).width(fase.percentual + "%");
                                $("#progress-fase-"+fase.codigo).attr("aria-valuenow", fase.percentual);
                                
                                $("#tokens-vendidos-fase-"+fase.codigo).html(fase.vendidos);
                                $("#tokens-bonificados-fase-"+fase.codigo).html(fase.bonificados);
                                $("#tokens-brl-arrecadado-fase-"+fase.codigo).html(fase.brlArrecadado);
                                $("#tokens-btc-arrecadado-fase-"+fase.codigo).html(fase.btcArrecadado);
                                $("#tokens-ltc-arrecadado-fase-"+fase.codigo).html(fase.ltcArrecadado);
                                $("#tokens-eth-arrecadado-fase-"+fase.codigo).html(fase.ethArrecadado);
                                $("#tokens-dash-arrecadado-fase-"+fase.codigo).html(fase.dashArrecadado);
                                
                                let brlArrecadado = parseFloat(fase.brlArrecadado.replace(".", "").replace(",", "."));
                                let btcArrecadado = parseFloat(fase.btcArrecadado.replace(".", "").replace(",", "."));
                                let ltcArrecadado = parseFloat(fase.ltcArrecadado.replace(".", "").replace(",", "."));
                                let ethArrecadado = parseFloat(fase.ethArrecadado.replace(".", "").replace(",", "."));
                                let dashArrecadado = parseFloat(fase.dashArrecadado.replace(".", "").replace(",", "."));
                                
                                let tokensVendidos = parseFloat(fase.vendidos.replace(".", "").replace(",", "."));
                                let tokensBonificados = parseFloat(fase.bonificados.replace(".", "").replace(",", "."));
                                
                                $("#spark-arrecadacao-fase-"+fase.codigo).sparkline([btcArrecadado, ltcArrecadado, ethArrecadado, dashArrecadado], {
                                    type: 'pie',
                                    height: '140',
                                    sliceColors: ['<?php echo $bitcoin->mainColor?>', '<?php echo $litecoin->mainColor?>', '<?php echo $ethereum->mainColor?>', '<?php echo $dash->mainColor?>']
                                });

                                $("#spark-relacao-venda-bonificacao-fase-"+fase.codigo).sparkline([tokensVendidos, tokensBonificados], {
                                    type: 'pie',
                                    height: '140',
                                    sliceColors: ['#1ab394', '#1c84c6']
                                });
                                
                            }
                            
                        }
                        
                        $("#tokens-distribuidos-ico").html(ico.distribuidos);
                        $("#tokens-restantes-ico").html(ico.disponiveis);
                        $("#progress-ico").width(ico.percentual + "%");
                        $("#progress-ico").attr("aria-valuenow", ico.percentual);

                        $("#tokens-vendidos-ico").html(ico.vendidos);
                        $("#tokens-bonificados-ico").html(ico.bonificados);
                        $("#tokens-brl-arrecadado-ico").html(ico.brlArrecadado);
                        $("#tokens-btc-arrecadado-ico").html(ico.btcArrecadado);
                        $("#tokens-ltc-arrecadado-ico").html(ico.ltcArrecadado);
                        $("#tokens-eth-arrecadado-ico").html(ico.ethArrecadado);
                        $("#tokens-dash-arrecadado-ico").html(ico.dashArrecadado);
                        
                        var brlArrecadado = parseFloat(ico.brlArrecadado.replace(".", "").replace(",", "."));
                        var btcArrecadado = parseFloat(ico.btcArrecadado.replace(".", "").replace(",", "."));
                        var ltcArrecadado = parseFloat(ico.ltcArrecadado.replace(".", "").replace(",", "."));
                        var ethArrecadado = parseFloat(ico.ethArrecadado.replace(".", "").replace(",", "."));
                        var dashArrecadado = parseFloat(ico.dashArrecadado.replace(".", "").replace(",", "."));
                        
                        var tokensVendidos = parseFloat(ico.vendidos.replace(".", "").replace(",", "."));
                        var tokensBonificados = parseFloat(ico.bonificados.replace(".", "").replace(",", "."));
                        
                        $("#spark-arrecadacao-ico").sparkline([btcArrecadado, ltcArrecadado, ethArrecadado, dashArrecadado], {
                            type: 'pie',
                            height: '140',
                            sliceColors: ['<?php echo $bitcoin->mainColor?>', '<?php echo $litecoin->mainColor?>', '<?php echo $ethereum->mainColor?>', '<?php echo $dash->mainColor?>']
                        });
                        
                        $("#spark-relacao-venda-bonificacao-ico").sparkline([tokensVendidos, tokensBonificados], {
                            type: 'pie',
                            height: '140',
                            sliceColors: ['#1ab394', '#1c84c6']
                        });
                        
                        var tokensCategoriaVenda = 0;
                        var tokensCategoriaBonus = 0;
                        var tokensCategoriaRedesSociais = 0;
                        
                        var j = 0;
                        for (j = 0; j < json.origens.length; j++) {
                            switch (json.origens[j].codigo) {
                                case "5": tokensCategoriaVenda = parseFloat(json.origens[j].total); break;
                                case "4": tokensCategoriaBonus = parseFloat(json.origens[j].total); break;
                                case "9": tokensCategoriaRedesSociais = parseFloat(json.origens[j].total); break;
                            }
                        }
                        $("#spark-relacao-distribuicao-categoria-ico").sparkline([tokensCategoriaVenda, tokensCategoriaBonus, tokensCategoriaRedesSociais], {
                            type: 'pie',
                            height: '140',
                            sliceColors: ['#1ab394', '#1c84c6', "#f8ac59"]
                        });
                         
                        
                        
                        
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                
            },
            error: function () {
                
            }
        });
    }
    
    
    
</script>


<?php Utils\Layout::append("mensage_text", $_data) ?>