<?php

$usuario = Utils\Geral::getLogado();
$rotinas = (isset($_data["rotinas"]) ? $_data["rotinas"] : Array());
?>


<?php Utils\Layout::append("inspina/metas", $_data) ?>

<?php Utils\Layout::append("inspina/scripts", $_data) ?>

<style>
    
    @media(max-width: 991px) {
        .file-box {
            width: 98% !important;
            margin-left: 1% !important;
            margin-right: 1% !important;
        }
    }
    
    @media(min-width: 992px) and (max-width: 1300px) {
        .file-box {
            width: 48% !important;
            margin-left: 1% !important;
            margin-right: 1% !important;
            min-height: 350px !important;
        }
    }
    
    @media(min-width: 1301px) {
        .file-box {
            width: 31.3% !important;
            margin-left: 1% !important;
            margin-right: 1% !important;
            min-height: 350px !important;
        }
    }
    
</style>

<?php Utils\Layout::append("inspina/menu", $_data) ?>




<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Painel de Monitoramento</h2>
            <ol class="breadcrumb">
                <li>
                    Monitoramento
                </li>
                <li class="active">
                    <strong>Painel</strong>
                </li>
            </ol>
        </div>
    </div>
</div>

    <!-- Main content -->
<section class="content">
    
    <br><br>
    
    <div class="ibox-content">

        
        <div class="row">
            <div class="col col-lg-12 text-center">
                <img src="<?php echo IMAGES ?>loading.gif" class="loaderData" style="width: 30px; height: 30px; margin: 5px; display: none;" />
            </div>
        </div>
        
        <br><br>
        
        
        <div class="row">
            <div class="col col-xs-12">
                
                <?php if (isset($rotinas[Utils\CodigoRotinas::CLIENTES])) { ?>
                <div class="file-box">
                    
                    <div class="panel panel-success ">
                        <div class="panel-heading">
                            Dados de clientes
                            <a href="<?php echo URLBASE_CLIENT . Utils\Rotas::R_LISTACLIENTES ?>" target="_BLANK"  class="btn btn-link pull-right" style="margin-top: -5px;"><i class="fa fa-link"></i></a>
                        </div>
                        <div class="panel-body">
                            <ul class="list-group list-">
                                <li class="list-group-item">

                                    <div class="row">
                                        <div class="col col-sm-8">
                                            Clientes cadastrados no sistema
                                        </div>
                                        <div class="col col-sm-4 text-right" id="clientesTotal">

                                        </div>
                                    </div>

                                </li>


                                <li class="list-group-item" style="background-color: #e6e5e5 !important;">

                                    <div class="row">
                                        <div class="col col-sm-8">
                                            Clientes ativos no sistema
                                        </div>
                                        <div class="col col-sm-4 text-right" id="clientesAtivos">

                                        </div>
                                    </div>

                                </li>


                                <li class="list-group-item" >

                                    <div class="row">
                                        <div class="col col-sm-8">
                                            Clientes aguardando confirmação
                                        </div>
                                        <div class="col col-sm-4 text-right" id="clientesAguardando">

                                        </div>
                                    </div>

                                </li>


                                <li class="list-group-item" style="background-color: #e6e5e5 !important;">

                                    <div class="row">
                                        <div class="col col-sm-8">
                                            Clientes inativos no sistema
                                        </div>
                                        <div class="col col-sm-4 text-right" id="clientesInativos">

                                        </div>
                                    </div>

                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <?php } ?>
                
                
                <!-- 
                <div class="file-box">
                    
                    <div class="panel panel-success">
                        <div class="panel-heading">
                            Pedidos de cartão 
                            <a href="<?php echo URLBASE_CLIENT . Utils\Rotas::R_CARTOES  ?>" target="_BLANK" class="btn btn-link pull-right" style="margin-top: -5px;"><i class="fa fa-link"></i></a>
                        </div>
                        <div class="panel-body">
                            <ul class="list-group list-">
                                <li class="list-group-item">

                                    <div class="row">
                                        <div class="col col-sm-8">
                                            Cartões cadastrados no sistema
                                        </div>
                                        <div class="col col-sm-4 text-right" id="cartoesTotal">

                                        </div>
                                    </div>

                                </li>


                                <li class="list-group-item" style="background-color: #e6e5e5 !important;">

                                    <div class="row">
                                        <div class="col col-sm-8">
                                            Cartões ativos no sistema
                                        </div>
                                        <div class="col col-sm-4 text-right" id="cartoesAtivos">

                                        </div>
                                    </div>

                                </li>

                                <li class="list-group-item">

                                    <div class="row">
                                        <div class="col col-sm-8">
                                            Aguardando Pagamento
                                        </div>
                                        <div class="col col-sm-4 text-right" id="cartoesAguardando">

                                        </div>
                                    </div>

                                </li>


                                <li class="list-group-item" style="background-color: #e6e5e5 !important;">

                                    <div class="row">
                                        <div class="col col-sm-8">
                                            Pedidos Pagos
                                        </div>
                                        <div class="col col-sm-4 text-right" id="cartoesPagos" >

                                        </div>
                                    </div>

                                </li>


                                <li class="list-group-item" >

                                    <div class="row">
                                        <div class="col col-sm-8">
                                            Pedidos cancelados
                                        </div>
                                        <div class="col col-sm-4 text-right" id="cartoesCancelados">

                                        </div>
                                    </div>

                                </li>

                            </ul>
                        </div>
                    </div>
                </div>
                -->
                
                <!-- 
                <div class="file-box">
                    
                    <div class="panel panel-success">
                        <div class="panel-heading">
                            Recargas de Cartão
                            <a href="<?php echo URLBASE_CLIENT  . Utils\Rotas::R_RECARGAS  ?>" target="_BLANK" class="btn btn-link pull-right" style="margin-top: -5px;"><i class="fa fa-link"></i></a>
                        </div>
                        <div class="panel-body">
                            <ul class="list-group list-">
                                <li class="list-group-item">

                                    <div class="row">
                                        <div class="col col-sm-8">
                                            Recargas finalizadas
                                        </div>
                                        <div class="col col-sm-4 text-right" id="recargasFinalizadas">

                                        </div>
                                    </div>

                                </li>


                                <li class="list-group-item" style="background-color: #e6e5e5 !important;">

                                    <div class="row">
                                        <div class="col col-sm-8">
                                            Aguardando Pagamento
                                        </div>
                                        <div class="col col-sm-4 text-right" id="recargasAguardando">

                                        </div>
                                    </div>

                                </li>


                                <li class="list-group-item" >

                                    <div class="row">
                                        <div class="col col-sm-8">
                                            Recargas Pagas
                                        </div>
                                        <div class="col col-sm-4 text-right" id="recargasPagas">

                                        </div>
                                    </div>

                                </li>


                                <li class="list-group-item" style="background-color: #e6e5e5 !important;">

                                    <div class="row">
                                        <div class="col col-sm-8">
                                            Recargas Canceladas
                                        </div>
                                        <div class="col col-sm-4 text-right" id="recargasCanceladas">

                                        </div>
                                    </div>

                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                    -->
                    
                <?php if (isset($rotinas[Utils\CodigoRotinas::BOLETOS])) { ?>
                <div class="file-box">
                    <div class="panel panel-success">
                        <div class="panel-heading">
                            Pagamento de boletos
                            <a href="<?php echo URLBASE_CLIENT  . Utils\Rotas::R_BOLETOS ?>" target="_BLANK" class="btn btn-link pull-right" style="margin-top: -5px;"><i class="fa fa-link"></i></a>
                        </div>
                        <div class="panel-body">
                            <ul class="list-group list-">
                                <li class="list-group-item">

                                    <div class="row">
                                        <div class="col col-sm-8">
                                            Finalizados
                                        </div>
                                        <div class="col col-sm-4 text-right" id="boletosFinalizados">

                                        </div>
                                    </div>

                                </li>


                                <li class="list-group-item" style="background-color: #e6e5e5 !important;">

                                    <div class="row">
                                        <div class="col col-sm-8">
                                            Pagamento efetuado pelo cliente
                                        </div>
                                        <div class="col col-sm-4 text-right" id="boletosPagos">

                                        </div>
                                    </div>

                                </li>


                                <li class="list-group-item" >

                                    <div class="row">
                                        <div class="col col-sm-8">
                                            Aguardando pagamento
                                        </div>
                                        <div class="col col-sm-4 text-right" id="boletosAguardando">

                                        </div>
                                    </div>

                                </li>


                                <li class="list-group-item" style="background-color: #e6e5e5 !important;">

                                    <div class="row">
                                        <div class="col col-sm-8">
                                            Cancelados
                                        </div>
                                        <div class="col col-sm-4 text-right" id="boletosCancelados">

                                        </div>
                                    </div>

                                </li>
                            </ul>
                        </div>
                    </div>
                    
                </div>
                <?php }  ?>
                
                <?php if (isset($rotinas[Utils\CodigoRotinas::REMESSAS])) { ?>
                <div class="file-box">
                    <div class="panel panel-success">
                        <div class="panel-heading">
                            Remessas de dinheiro
                            <a href="<?php echo URLBASE_CLIENT . Utils\Rotas::R_REMESSAS  ?>" target="_BLANK" class="btn btn-link pull-right" style="margin-top: -5px;"><i class="fa fa-link"></i></a>
                        </div>
                        <div class="panel-body">
                            <ul class="list-group list-">
                                <li class="list-group-item">

                                    <div class="row">
                                        <div class="col col-sm-8">
                                            Finalizadas
                                        </div>
                                        <div class="col col-sm-4 text-right" id="remessasFinalizadas">

                                        </div>
                                    </div>

                                </li>


                                <li class="list-group-item" style="background-color: #e6e5e5 !important;">

                                    <div class="row">
                                        <div class="col col-sm-8">
                                            Pagas
                                        </div>
                                        <div class="col col-sm-4 text-right" id="remessasPagas">

                                        </div>
                                    </div>

                                </li>


                                <li class="list-group-item" >

                                    <div class="row">
                                        <div class="col col-sm-8">
                                            Aguardando pagamento
                                        </div>
                                        <div class="col col-sm-4 text-right" id="remessasAguardando">

                                        </div>
                                    </div>

                                </li>


                                <li class="list-group-item" style="background-color: #e6e5e5 !important;">

                                    <div class="row">
                                        <div class="col col-sm-8">
                                            Canceladas
                                        </div>
                                        <div class="col col-sm-4 text-right" id="remessasCanceladas">

                                        </div>
                                    </div>

                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <?php } ?>
                
                    
                <?php if (\Models\Modules\Acesso\ModuloRn::validar(Utils\Rotas::M_TRANSFERENCIAS, Utils\Constantes::ACESSO)) { ?>
                <div class="file-box">
                    <div class="panel panel-success">
                        <div class="panel-heading">
                            Transações Pendentes
                            <a href="<?php echo URLBASE_CLIENT . Utils\Rotas::R_PAINELBTC  ?>" target="_BLANK" class="btn btn-link pull-right" style="margin-top: -5px;"><i class="fa fa-link"></i></a>
                        </div>
                        <div class="panel-body">
                            <ul class="list-group list-">
                                <li class="list-group-item">

                                    <div class="row">
                                        <div class="col col-sm-8">
                                            Pendentes
                                        </div>
                                        <div class="col col-sm-4 text-right" id="transacoesPendentes">

                                        </div>
                                    </div>

                                </li>


                            </ul>
                        </div>
                    </div>
                </div>
                <?php } ?>
                    
                    
                <?php if (\Models\Modules\Acesso\ModuloRn::validar(Utils\Rotas::M_DEPOSITOS, Utils\Constantes::ACESSO)) { ?>    
                <div class="file-box">    
                    <div class="panel panel-success">
                        <div class="panel-heading">
                            Depósitos
                            <a href="<?php echo URLBASE_CLIENT . Utils\Rotas::R_DEPOSITOS  ?>" target="_BLANK" class="btn btn-link pull-right" style="margin-top: -5px;"><i class="fa fa-link"></i></a>
                        </div>
                        <div class="panel-body">
                            <ul class="list-group list-">
                                <li class="list-group-item">

                                    <div class="row">
                                        <div class="col col-sm-4">
                                            Confirmados
                                        </div>
                                        <div class="col col-sm-8 text-right" id="depositosConfirmados">

                                        </div>
                                    </div>

                                </li>


                                <li class="list-group-item" style="background-color: #e6e5e5 !important;">

                                    <div class="row">
                                        <div class="col col-sm-4">
                                            Pendentes
                                        </div>
                                        <div class="col col-sm-8 text-right" id="depositosPendentes">

                                        </div>
                                    </div>

                                </li>


                                <li class="list-group-item" >

                                    <div class="row">
                                        <div class="col col-sm-4">
                                            Cancelados
                                        </div>
                                        <div class="col col-sm-8 text-right" id="depositosCancelados">

                                        </div>
                                    </div>

                                </li>


                            </ul>
                        </div>
                    </div>
                </div>   
                <?php } ?>
                    
                <?php if (\Models\Modules\Acesso\ModuloRn::validar(Utils\Rotas::M_SAQUES, Utils\Constantes::ACESSO)) { ?>
                <div class="file-box">    
                    <div class="panel panel-success">
                        <div class="panel-heading">
                            Saques 
                            <a href="<?php echo URLBASE_CLIENT . Utils\Rotas::R_SAQUES  ?>" target="_BLANK" class="btn btn-link pull-right" style="margin-top: -5px;"><i class="fa fa-link"></i></a>
                        </div>
                        <div class="panel-body">
                            <ul class="list-group list-">
                                <li class="list-group-item">

                                    <div class="row">
                                        <div class="col col-sm-4">
                                            Confirmados
                                        </div>
                                        <div class="col col-sm-8 text-right" id="saquesConfirmados">

                                        </div>
                                    </div>

                                </li>


                                <li class="list-group-item" style="background-color: #e6e5e5 !important;">

                                    <div class="row">
                                        <div class="col col-sm-4">
                                            Pendentes
                                        </div>
                                        <div class="col col-sm-8 text-right" id="saquesPendentes">

                                        </div>
                                    </div>

                                </li>


                                <li class="list-group-item" >

                                    <div class="row">
                                        <div class="col col-sm-4">
                                            Cancelados
                                        </div>
                                        <div class="col col-sm-8 text-right" id="saquesCancelados">

                                        </div>
                                    </div>

                                </li>


                            </ul>
                        </div>
                    </div>
                </div>   
                <?php }  ?>
                    
                    
                <?php if (isset($rotinas[Utils\CodigoRotinas::PERFIL_UPGRADE_ANALISAR])) { ?>
                <div class="file-box">    
                    <div class="panel panel-success">
                        <div class="panel-heading">
                            Licenças de Software
                            <a href="<?php echo URLBASE_CLIENT . Utils\Rotas::R_PERFIL_UPGRADE_ANALISAR ?>" target="_BLANK" class="btn btn-link pull-right" style="margin-top: -5px;"><i class="fa fa-link"></i></a>
                        </div>
                        <div class="panel-body">
                            <ul class="list-group list-">
                                <li class="list-group-item">

                                    <div class="row">
                                        <div class="col col-sm-4">
                                            Aguardando Análise
                                        </div>
                                        <div class="col col-sm-8 text-right" id="franquiasAguardando">

                                        </div>
                                    </div>

                                </li>


                                <li class="list-group-item" style="background-color: #e6e5e5 !important;">

                                    <div class="row">
                                        <div class="col col-sm-4">
                                            Aprovados
                                        </div>
                                        <div class="col col-sm-8 text-right" id="franquiasAprovadas">

                                        </div>
                                    </div>

                                </li>

                            </ul>
                        </div>
                    </div>
                </div>
                <?php } ?>
                    
                    
                <div class="file-box">
                    <div class="panel panel-success">
                        <div class="panel-heading">
                            Status de Consumíveis
                        </div>
                        <div class="panel-body">
                            <ul class="list-group list-">
                                <li class="list-group-item">

                                    <div class="row">
                                        <div class="col col-sm-4">
                                            Créditos de SMS
                                        </div>
                                        <div class="col col-sm-8 text-right" id="consumiveisSms">

                                        </div>
                                    </div>

                                </li>


                                <li class="list-group-item" style="background-color: #e6e5e5 !important;">

                                    <div class="row">
                                        <div class="col col-sm-4">
                                            Validade do SMS
                                        </div>
                                        <div class="col col-sm-8 text-right" id="consumiveisValidadeSms">

                                        </div>
                                    </div>

                                </li>


                                <li class="list-group-item" style="background-color: #e6e5e5 !important;">

                                    <div class="row">
                                        <div class="col col-sm-8">
                                            Creditos de consulta de documento
                                        </div>
                                        <div class="col col-sm-4 text-right" id="consumiveisCreditosConsulta">

                                        </div>
                                    </div>

                                </li>
                            </ul>
                        </div>
                    </div>
                </div>    
                    
            </div>

        </div>
    </div>
        
</section>
    
<div class="clearfix"></div>

<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>

<script>
    $(document).ready(function () {
        getDados();
    });
    
    function getDados() {
        $(".loaderData").show();
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_MONITORAMENTO_REFRESH  ?>',
            method: 'post',
            dataType: 'json',
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#clientesTotal").html(json.clientesTotal);
                        $("#clientesAtivos").html(json.clientesAtivos);
                        $("#clientesInativos").html(json.clientesInativos);
                        $("#clientesAguardando").html(json.clientesAguardando);
                        
                        $("#cartoesTotal").html(json.cartoesTotal);
                        $("#cartoesAtivos").html(json.cartoesAtivos);
                        $("#cartoesAguardando").html(json.cartoesAguardando);
                        $("#cartoesPagos").html(json.cartoesPagos);
                        $("#cartoesCancelados").html(json.cartoesCancelados);
                        
                        $("#recargasFinalizadas").html(json.recargasFinalizadas);
                        $("#recargasAguardando").html(json.recargasAguardando);
                        $("#recargasPagas").html(json.recargasPagas);
                        $("#recargasCanceladas").html(json.recargasCanceladas);
                        
                        $("#remessasFinalizadas").html(json.remessasFinalizadas);
                        $("#remessasAguardando").html(json.remessasAguardando);
                        $("#remessasPagas").html(json.remessasPagas);
                        $("#remessasCanceladas").html(json.remessasCanceladas);
                        
                        $("#boletosFinalizados").html(json.boletosFinalizados);
                        $("#boletosAguardando").html(json.boletosAguardando);
                        $("#boletosPagos").html(json.boletosPagos);
                        $("#boletosCancelados").html(json.boletosCancelados);
                        
                        $("#saquesCancelados").html(json.saquesCancelados.qtd + " ( R$ " + json.saquesCancelados.valor + ")");
                        $("#saquesConfirmados").html(json.saquesConfirmados.qtd + " ( R$ " + json.saquesConfirmados.valor + ")");
                        $("#saquesPendentes").html(json.saquesPendentes.qtd + " ( R$ " + json.saquesPendentes.valor + ")");
                        
                        $("#depositosCancelados").html(json.depositosCancelados.qtd + " ( R$ " + json.depositosCancelados.valor + ")");
                        $("#depositosConfirmados").html(json.depositosConfirmados.qtd + " ( R$ " + json.depositosConfirmados.valor + ")");
                        $("#depositosPendentes").html(json.depositosPendentes.qtd + " ( R$ " + json.depositosPendentes.valor + ")");
                        
                        $("#transacoesPendentes").html(json.transacoesPendentes);
                        
                        $("#franquiasAguardando").html(json.solicitacoesFranquias);
                        $("#franquiasAprovadas").html(json.franquiasAprovadas);
                        
                        $("#consumiveisSms").html(json.qtdSms);
                        $("#consumiveisValidadeSms").html(json.valSms);
                        $("#consumiveisCreditosConsulta").html(json.consultas);
                        


                        
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $(".loaderData").hide();
                setTimeout('getDados()',20000);
            },
            error: function () {
                setTimeout('getDados()',20000);
            }
        });
    }
    
    
</script>


<?php Utils\Layout::append("mensage_text", $_data) ?>