<?php
$logs = isset($_data["logs"]) ? $_data["logs"] : Array();
?>

<html>
    <head>
        <title></title>
    </head>
    
    <body>
        
        <table style="width: 100%;"> 
            
            <tbody>
                <tr>
                    <td style="text-align: center;">
                        <h2>Extrato de Logs Conta Corrente da Empresa (BTC)</h2>
                        <br><br>
                    </td>
                </tr>
                
            </tbody>
            
        </table>
        
        
        <br><br>
        
        <table style="width: 100%; font-size: 10px;"> 
            
            <thead>
                <tr>
                    <th style="text-align: center; background: #999999; color: #ffffff;">
                        <strong>Data</strong>
                    </th>
                    <th style="background: #999999; color: #ffffff;">
                        <strong>Descrição</strong>
                    </th>
                    <th style="text-align: center; background: #999999; color: #ffffff;">
                        <strong>Usuário</strong>
                    </th>
                    <th style="text-align: center; background: #999999; color: #ffffff;">
                        <strong>Controle</strong>
                    </th>
                </tr>
            </thead>
            
            <tbody>
                <?php
                $i = 0;
                foreach ($logs as $log) {
                    //$log = new \Models\Modules\Cadastro\LogContaCorrenteBtcEmpresa();
                    
                    
                    $bg = (($i%2) > 0 ? "#cccccc" : "#ffffff");
                    $cl = (($i%2) > 0 ? "#000000" : "#000000");
                ?>
                <tr>
                    <td style="text-align: center; background: <?php echo $bg?>; color: <?php echo $cl ?>;">
                        <?php echo $log->data->formatar(Utils\Data::FORMATO_PT_BR_TIMESTAMP_LONGO) ?>
                    </td>
                    <td style="background: <?php echo $bg?>; color: <?php echo $cl ?>;">
                        <?php echo $log->descricao ?>
                    </td>
                    <td style="text-align: center; background: <?php echo $bg?>; color: <?php echo $cl ?>;">
                        <?php echo $log->getNome(); ?>
                    </td>
                    <td style="text-align: center; background: <?php echo $bg?>; color: <?php echo $cl ?>;">
                        <?php echo $log->idContaCorrenteBtcEmpresa ?>
                    </td>
                </tr>
                <?php 
                $i++;
                }
                ?>
            </tbody>
            
        </table>
        
    </body>
    
</html>