<?php
$dataInicial = new Utils\Data(date("d/m/Y"));
$dataFinal = new Utils\Data(date("d/m/Y"));
$dataInicial->subtrair(0, 0, 30);
$moeda = \Modules\principal\Controllers\Principal::getCurrency();
$paises = isset($_data["paises"]) ? $_data["paises"] : Array();
?>



<?php Utils\Layout::append("inspina/metas", $_data) ?>

<?php Utils\Layout::append("inspina/scripts", $_data) ?>


<?php Utils\Layout::append("inspina/menu", $_data) ?>


     <div class="content-wrapper">
    <!-- Content Header (Page header) -->
            <div class="row wrapper border-bottom page-heading" style="background: linear-gradient(to right, #fff, <?php echo $moeda->mainColor ?>) !important;">
                <div class="col-lg-10">
                    <h2>Pedidos de Cartões</h2>
                    <ol class="breadcrumb" style="background-color: transparent !important;">
                        <li>
                            Cartões
                        </li>
                        <li class="active">
                            <strong>Pedidos de Cartões</strong>
                        </li>
                    </ol>
                </div>
            </div>
</div>
    <br>   
   
    <!-- Main content -->
    <section class="content">
        
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <?php Utils\Layout::append("mensagem", $_data)?>
                    <div class="panel-heading">
                        Listagem de Pedidos 
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">

                        <div class="row">
                            <div class="col col-lg-4">
                                <div class="form-group">
                                    <label class="control-label">Data inicial</label>
                                    <input type="text" id="dataInicial" class="form-control" value="<?php echo $dataInicial->formatar(Utils\Data::FORMATO_PT_BR)?>"/>
                                </div>
                            </div>
                            <div class="col col-lg-4">
                                <div class="form-group">
                                    <label class="control-label">Data final </label>
                                    <input type="text" id="dataFinal" class="form-control" value="<?php echo $dataFinal->formatar(Utils\Data::FORMATO_PT_BR)?>" />
                                </div>
                            </div>
                            <div class="col col-lg-4">
                                <div class="form-group">
                                    <label class="control-label">Status</label>
                                    <select class="form-control" id="status" >
                                        <option value="T" >Qualquer Status</option>
                                        <option value="<?php echo Utils\Constantes::STATUS_PEDIDO_CARTAO_AGUARDANDO ?>" >Aguardando</option>
                                        <option value="<?php echo Utils\Constantes::STATUS_PEDIDO_CARTAO_PAGO ?>" >Pago</option>
                                        <option value="<?php echo Utils\Constantes::STATUS_PEDIDO_CARTAO_CANCELADO ?>" >Cancelado</option>
                                    </select>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col col-lg-4">
                                <div class="form-group">
                                    <label class="control-label">País</label>
                                    <select class="form-control" id="pais" >
                                        <option value="000" >Qualquer</option>
                                        <?php foreach ($paises as $pais) {
                                            ?>
                                        <option value="<?php echo $pais->codigo ?>" ><?php echo $pais->nome ?></option>
                                        <?php
                                        }?>
                                    </select>
                                </div>
                            </div>

                            <div class="col col-lg-3">
                                <div class="form-group">
                                    <label class="control-label">Status do Cartão</label>
                                    <select class="form-control" id="ativo" >
                                        <option value="T" >Qualquer</option>
                                        <option value="1" >Ativo</option>
                                        <option value="0" >Inativo</option>
                                    </select>
                                </div>
                            </div>

                            <div class="col col-lg-3">
                                <div class="form-group">
                                    <label class="control-label">Cancelados</label>
                                    <select class="form-control" id="cancelado" >
                                        <option value="T" >Todos</option>
                                        <option value="0" >Não</option>
                                        <option value="1" >Sim</option>
                                    </select>
                                </div>
                            </div>

                            <div class="col col-lg-2">
                                <div class="form-group">
                                    <label class="control-label">Bandeira</label>
                                    <select class="form-control" id="bandeira" >
                                        <option value="T" >Todas</option>
                                        <option value="<?php echo \Utils\Constantes::CARTAO_VISA ?>" >Visa</option>
                                        <option value="<?php echo \Utils\Constantes::CARTAO_MASTER ?>" >Mastercard</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col col-lg-12">
                                <div class="form-group">
                                    <label>Filtro Geral</label>
                                    <input type="text" id="filtro" class="form-control" />
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col col-lg-12 text-center">
                                <br>
                                <button class="btn btn-primary" onclick="listarPedidos();">
                                    <i class="fa fa-refresh"></i> Atualizar
                                </button>
                                <br>
                            </div>
                        </div>
                        </br>
                        <div class="row">
                            <div class="col col-lg-12 ">
                                <ul class="list-group">
                                    <li class="list-group-item bg-aqua" style="border-bottom: none;">
                                        <div class="row">
                                            <div class="col col-xs-6 col-sm-4">
                                                Pedidos Pendentes: <span id="pedidosPendentes"></span>
                                            </div>
                                            <div class="col col-xs-6 col-sm-4">
                                                Pedidos Pagos: <span id="pedidosPagos"></span>
                                            </div>
                                            <div class="col col-xs-6 col-sm-4">
                                                Pedidos Cancelados: <span id="pedidosCancelados"></span>
                                            </div>
                                        </div>
                                    </li>
                                    <li class="list-group-item bg-aqua" style="border-top: none;">
                                        <div class="row">
                                            <div class="col col-xs-6 col-sm-4">
                                                Cartões Ativos: <span id="cartoesAtivos"></span>
                                            </div>
                                            <div class="col col-xs-6 col-sm-4">
                                                Cartões Inativos: <span id="cartoesInativos"></span>
                                            </div>
                                            <div class="col col-xs-6 col-sm-4">
                                                Cartões Cancelados: <span id="cartoesCancelados"></span>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col col-lg-12" id="listaPedidos">
                            </div>
                        </div>
                    </div>
                    <!-- /.panel-body -->

                </div>
            </div>

        </div>
        
    </section>
    
    <div class="clearfix"></div>
</div>

<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>

<script>
    $(document).ready(function () {
        
        listarPedidos();
        $("#dataInicial, #dataFinal").datepicker().mask("99/99/9999");
        $("#modalInserirDadosCartaoNumeroCartao").mask("9999-9999-9999-9999");
        $("#modalInserirDadosCartaoValidadeCartao").mask("99/99");
        
    });
    
    function listarPedidos() {
        $("#listaPedidos").html("<div class='col-lg-12 text-center'><img src='<?php echo IMAGES ?>loading.gif' /></div>");
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_INVOICES_FILTRAR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                dataInicial:$("#dataInicial").val(),
                dataFinal:$("#dataFinal").val(),
                status:$("#status").val(),
                pais:$("#pais").val(),
                ativo:$("#ativo").val(),
                cancelado:$("#cancelado").val(),
                bandeira:$("#bandeira").val(),
                filtro: $("#filtro").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#listaPedidos").html(json.html);
                        $("#pedidosPendentes").html(json.pedidosPendentes);
                        $("#pedidosPagos").html(json.pedidosPagos);
                        $("#pedidosCancelados").html(json.pedidosCancelados);
                        $("#cartoesAtivos").html(json.cartoesAtivos);
                        $("#cartoesInativos").html(json.cartoesInativos);
                        $("#cartoesCancelados").html(json.cartoesCancelados);
                    } else {
                        $("#listaPedidos").html("<div class='col-lg-12 text-center'>"+json.mensagem+"</div>");
                        $("#pedidosPendentes").html("0");
                        $("#pedidosPagos").html("0");
                        $("#pedidosCancelados").html("0");
                        $("#cartoesAtivos").html("0");
                        $("#cartoesInativos").html("0");
                        $("#cartoesCancelados").html("0");
                    }
                } catch (e) {
                    $("#listaPedidos").html("<div class='col-lg-12 text-center'>"+e+"</div>");
                    $("#pedidosPendentes").html("0");
                    $("#pedidosPagos").html("0");
                    $("#pedidosCancelados").html("0");
                    $("#cartoesAtivos").html("0");
                    $("#cartoesInativos").html("0");
                    $("#cartoesCancelados").html("0");
                }
            }
        });
    }
    
    function detalhesPedidos(idPedido) {
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_INVOICES_GET ?>',
            method: 'post',
            dataType: 'json',
            data: {
                idPedidoCartao: idPedido
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        
                        $("#dialogDetalhesInvoiceHtml").html(json.html);
                        
                        $("#dialogDetalhesInvoice").modal();
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
            }
        });
    }
    
    
    function inserirDadosCartao(idPedidoCartao) {
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_INVOICES_CARTAO_GET ?>',
            method: 'post',
            dataType: 'json',
            data: {
                idPedidoCartao: idPedidoCartao
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#modalInserirDadosCartao").modal();
                        $("#modalInserirDadosCartaoIdPedidoCartao").val(json.pedido.id);
                        $("#modalInserirDadosCartaoNomeCartao").val(json.pedido.nomeCartao);
                        $("#modalInserirDadosCartaoNumeroCartao").val(json.pedido.numeroCartao);
                        $("#modalInserirDadosCartaoIdCartao").val(json.pedido.idCartao);
                        $("#modalInserirDadosCartaoSenhaCartao").val(json.pedido.senhaCartao);
                        $("#modalInserirDadosCartaoValidadeCartao").val(json.pedido.validade);
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
            }
        });
    }
    
    function salvarDadosCartao() {
        $("#modalInserirDadosCartaoFechar, #modalInserirDadosCartaoSalvar").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_INVOICES_CARTAO_SALVAR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                idPedidoCartao: $("#modalInserirDadosCartaoIdPedidoCartao").val(),
                nomeCartao: $("#modalInserirDadosCartaoNomeCartao").val(),
                numeroCartao: $("#modalInserirDadosCartaoNumeroCartao").val(),
                idCartao: $("#modalInserirDadosCartaoIdCartao").val(),
                senhaCartao: $("#modalInserirDadosCartaoSenhaCartao").val(),
                validade: $("#modalInserirDadosCartaoValidadeCartao").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#html-cartao-id-"+$("#modalInserirDadosCartaoIdPedidoCartao").val()).replaceWith(json.html);
                        $("#modalInserirDadosCartaoFechar").prop("disabled", false).trigger("click");
                        showNotyAlert(json.mensagem, "s");
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#modalInserirDadosCartaoFechar, #modalInserirDadosCartaoSalvar").prop("disabled", false);
            }
        });
    }
    
    
    function alterarStatusCartao(idPedidoCartao) {
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_INVOICES_CARTAO_STATUS ?>',
            method: 'post',
            dataType: 'json',
            data: {
                idPedidoCartao: idPedidoCartao
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#html-cartao-id-"+idPedidoCartao).replaceWith(json.html);
                        showNotyAlert(json.mensagem, "s");
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
            }
        });
    }
    
    function dialogCancelarCartao(idPedidoCartao) {
        $("#dialogCancelarCartaoIdPedidoCartao").val(idPedidoCartao);
        $("#dialogCancelarCartao").modal();
    }
    
    
    function confirmarCancelamentoPedido() {
        $("#dialogDetalhesInvoiceFechar, #dialogDetalhesInvoiceConfirmar").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_INVOICES_CANCELAR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                idPedidoCartao: $("#dialogCancelarCartaoIdPedidoCartao").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#html-cartao-id-"+$("#dialogCancelarCartaoIdPedidoCartao").val()).replaceWith(json.html);
                        $("#dialogDetalhesInvoiceFechar").prop("disabled", false).trigger("click");
                        showNotyAlert(json.mensagem, "s");
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#dialogDetalhesInvoiceFechar, #dialogDetalhesInvoiceConfirmar").prop("disabled", false);
            }
        });
    }
    
    
    function dialogPagarPedido(idPedidoCartao) {
        $("#dialogPagarPedidoCartaoIdPedidoCartao").val(idPedidoCartao);
        $("#dialogPagarPedidoCartao").modal();
    }
    
    function confirmarPagamentoPedidoCartao() {
        $("#dialogPagarPedidoCartaoFechar, #dialogPagarPedidoCartaoConfirmar").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_INVOICES_PAGAMENTO_CONFIRMAR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                idPedidoCartao: $("#dialogPagarPedidoCartaoIdPedidoCartao").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#html-li-status-id-"+$("#dialogPagarPedidoCartaoIdPedidoCartao").val()).replaceWith(json.html);
                        $("#dialogPagarPedidoCartaoFechar").prop("disabled", false).trigger("click");
                        showNotyAlert(json.mensagem, "s");
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#dialogPagarPedidoCartaoFechar, #dialogPagarPedidoCartaoConfirmar").prop("disabled", false);
            }
        });
    }
</script>


<div class="modal fade" id="dialogDetalhesInvoice" tabindex="-1" role="dialog" aria-labelledby="dialogDetalhesInvoice" aria-hidden="true" >
    <div class="modal-dialog" style="width: 800px;">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="dialogDetalhesInvoiceLabel">Detalhes da Invoice</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col col-lg-12" id="dialogDetalhesInvoiceHtml" style="height: 400px; overflow-y: scroll;">
                        
                    </div>
                    
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="dialogDetalhesInvoiceFechar" data-dismiss="modal">Fechar</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>


<div class="modal fade" id="modalInserirDadosCartao" tabindex="-1" role="dialog" aria-labelledby="modalInserirDadosCartao" aria-hidden="true" >
    <div class="modal-dialog" style="width: 800px;">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="modalInserirDadosCartaoLabel">Cadastrar Dados do Cartão</h4>
            </div>
            <div class="modal-body">
                <input type="hidden" id="modalInserirDadosCartaoIdPedidoCartao" />
                <div class="row">
                    <div class="col col-lg-6">
                        <div class="form-group">
                            <label>Nome do Cliente no Cartão</label>
                            <input type="text" class="form-control" id="modalInserirDadosCartaoNomeCartao" maxlength="40" />
                        </div>
                    </div>
                    <div class="col col-lg-6">
                        <div class="form-group">
                            <label>Número do Cartão</label>
                            <input type="text" class="form-control" id="modalInserirDadosCartaoNumeroCartao" maxlength="20" />
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col col-lg-4">
                        <div class="form-group">
                            <label>Validade do Cartão (MM/YY)</label>
                            <input type="text" class="form-control" id="modalInserirDadosCartaoValidadeCartao" maxlength="7" />
                        </div>
                    </div>
                    <div class="col col-lg-4">
                        <div class="form-group">
                            <label>Id do Cartão</label>
                            <input type="text" class="form-control" id="modalInserirDadosCartaoIdCartao" maxlength="20" />
                        </div>
                    </div>
                    <div class="col col-lg-4">
                        <div class="form-group">
                            <label>Senha do Cartão</label>
                            <input type="password" class="form-control" id="modalInserirDadosCartaoSenhaCartao" maxlength="4" />
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="modalInserirDadosCartaoFechar" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-primary" id="modalInserirDadosCartaoSalvar" onclick="salvarDadosCartao();">Salvar</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>




<div class="modal fade" id="dialogCancelarCartao" tabindex="-1" role="dialog" aria-labelledby="dialogCancelarCartao" aria-hidden="true" >
    <div class="modal-dialog" style="width: 800px;">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="dialogCancelarCartaoLabel">Cancelar Cartão</h4>
            </div>
            <div class="modal-body">
                <input type="hidden" id="dialogCancelarCartaoIdPedidoCartao" />
                <div class="row">
                    <div class="col col-lg-12" >
                        Tem certeza que deseja cancelar o cartão?
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="dialogDetalhesInvoiceFechar" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-danger" id="dialogDetalhesInvoiceConfirmar"  onclick="confirmarCancelamentoPedido();">Confirmar Cancelamento</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>




<div class="modal fade" id="dialogPagarPedidoCartao" tabindex="-1" role="dialog" aria-labelledby="dialogPagarPedidoCartao" aria-hidden="true" >
    <div class="modal-dialog modal-lg" >
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="dialogPagarPedidoCartaoLabel">Marcar como Pago</h4>
            </div>
            <div class="modal-body">
                <input type="hidden" id="dialogPagarPedidoCartaoIdPedidoCartao" />
                <div class="row">
                    <div class="col col-lg-12" >
                        Tem certeza que deseja marcar o pedido como pago?
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="dialogPagarPedidoCartaoFechar" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-success" id="dialogPagarPedidoCartaoConfirmar"  onclick="confirmarPagamentoPedidoCartao();">Pagar</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>