<?php
$dataInicial = new Utils\Data(date("d/m/Y"));
$dataFinal = new Utils\Data(date("d/m/Y"));
$dataInicial->subtrair(0, 0, 30);
$cartoes = isset($_data["cartoes"]) ? $_data["cartoes"] : Array();
$moeda = \Modules\principal\Controllers\Principal::getCurrency();
?>


<?php Utils\Layout::append("inspina/metas", $_data) ?>

<?php Utils\Layout::append("inspina/scripts", $_data) ?>


<?php Utils\Layout::append("inspina/menu", $_data) ?>





    <div class="content-wrapper">
    <!-- Content Header (Page header) -->
            <div class="row wrapper border-bottom page-heading" style="background: linear-gradient(to right, #fff, <?php echo $moeda->mainColor ?>) !important;">
                <div class="col-lg-10">
                    <h2>Recargas de Cartões</h2>
                    <ol class="breadcrumb" style="background-color: transparent !important;">
                        <li>
                            Cartões
                        </li>
                        <li class="active">
                            <strong>Recargas de Cartões</strong>
                        </li>
                    </ol>
                </div>
            </div>
</div>
    <br>
    <!-- Main content -->
    <section class="content">

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <?php Utils\Layout::append("mensagem", $_data)?>
                    <div class="panel-heading">
                        Listagem de Recargas 
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <div class="row">

                            <div class="row">
                                <div class="col col-xs-12 text-center">
                                    <button type="button" class="btn btn-primary btn-lg" onclick="dialogRecargaCartao();">
                                        <i class="fa fa-dollar"></i> Faça Agora mesmo uma Recarga
                                    </button>
                                    <br><br>
                                </div>
                            </div>

                            <div class="col col-md-2">
                                <div class="form-group">
                                    <label class="control-label">Data Inicial</label>
                                    <input type="text" id="dataInicial" class="form-control" value="<?php echo $dataInicial->formatar(\Utils\Data::FORMATO_PT_BR)?>"  onkeyup="listarRecargas();"/>
                                </div>
                            </div>
                            <div class="col col-md-2">
                                <div class="form-group">
                                    <label class="control-label">Data Final</label>
                                    <input type="text" id="dataFinal" class="form-control" value="<?php echo $dataFinal->formatar(\Utils\Data::FORMATO_PT_BR)?>"  onkeyup="listarRecargas();"/>
                                </div>
                            </div>

                            <div class="col col-md-4">
                                <div class="form-group">
                                    <label class="control-label">Status</label>
                                    <select class="form-control" id="status" onchange="listarRecargas();">
                                        <option value="T" >Todos</option>
                                        <option value="<?php echo \Utils\Constantes::STATUS_RECARGA_CARTAO_AGUARDANDO ?>" >Aguardando</option>
                                        <option value="<?php echo \Utils\Constantes::STATUS_RECARGA_CARTAO_PAGO ?>" >Pagas</option>
                                        <option value="<?php echo \Utils\Constantes::STATUS_RECARGA_CARTAO_FINALIZADO ?>" >Finalizadas</option>
                                        <option value="<?php echo \Utils\Constantes::STATUS_RECARGA_CARTAO_CANCELADO ?>" >Canceladas</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col col-lg-4">
                                <div class="form-group">
                                    <label class="control-label">Cartão</label>
                                    <select class="form-control" id="idPedidoCartao" onchange="listarRecargas();" >
                                        <option value="0" >Qualquer</option>
                                        <?php foreach ($cartoes as $cartao) {
                                            ?>
                                        <option value="<?php echo $cartao->id ?>" ><?php echo $cartao->numeroCartao ?></option>
                                        <?php
                                        }?>
                                    </select>
                                </div>
                            </div>

                        </div>
                        <div class="row">
                            <div class="col col-lg-12 text-center">
                                <br>
                                <button class="btn btn-primary" onclick="listarRecargas();">
                                    <i class="fa fa-refresh"></i> Atualizar
                                </button>
                                <br><br>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col col-lg-12">
                                <ul class="list-group">
                                    <li class="list-group-item">
                                        <div class="row">
                                            <div class="col col-xs-6 col-sm-3">
                                                Aguardando: <span id="aguardando"></span>
                                            </div>
                                            <div class="col col-xs-6 col-sm-3">
                                                Pagas: <span id="paga"></span>
                                            </div>
                                            <div class="col col-xs-6 col-sm-3">
                                                Finalizadas: <span id="finalizada"></span>
                                            </div>
                                            <div class="col col-xs-6 col-sm-3">
                                                Canceladas: <span id="cancelada"></span>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col col-lg-12" >
                                <ul class="list-group" id="listaRecargas">
                                    
                                </ul>
                            </div>
                        </div>
                    </div>
                    <!-- /.panel-body -->

                </div>
            </div>

        </div>

        <a  id="openOrder" target="_BLANK"></a>
    </section>
    
    <div class="clearfix"></div>
</div>

<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>

<script>
    $(document).ready(function () {
        
        listarRecargas();
        
        //$("#dataInicial, #dataFinal").datepicker().mask("99/99/9999");
        
        $("#recarregarMeuCartao, #recarregarCartaoTerceiro").change(function () {
            if ($("#recarregarMeuCartao").is(":checked")) {
                $("#containerMeuCartao").show();
                $("#containerCartaoTerceiro").hide();
            } else {
                $("#containerCartaoTerceiro").show();
                $("#containerMeuCartao").hide();
            }
        });
        
        $("#inputNumeroCartao").mask("9999-9999-9999-9999");
        $("#inputNumeroCartao").keyup(function () {
            validarCartao();
        });
        
        
        
        $("#valor").keydown(function(event) {
            $(this).val(currency($(this).val(), 2, 8, event.keyCode));
            event.preventDefault();
        });
        
        $("#dataInicial, #dataFinal").datepicker().mask("99/99/9999");
    });
    
    function listarRecargas() {
        $("#listaRecargas").html("<div class='col-lg-12 text-center'><img src='<?php echo IMAGES ?>loading.gif' /></div>");
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_RECHARGES_FILTRAR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                dataInicial:$("#dataInicial").val(),
                dataFinal:$("#dataFinal").val(),
                status:$("#status").val(),
                idPedidoCartao:$("#idPedidoCartao").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#listaRecargas").html(json.html);
                        $("#aguardando").html(json.dados.aguardando);
                        $("#paga").html(json.dados.pago);
                        $("#finalizada").html(json.dados.finalizado);
                        $("#cancelada").html(json.dados.cancelado);
                    } else {
                        $("#listaRecargas").html("<div class='col-lg-12 text-center'>"+json.mensagem+"</div>");
                        
                        $("#aguardando").html("0");
                        $("#paga").html("0");
                        $("#finalizada").html("0");
                        $("#cancelada").html("0");
                    }
                } catch (e) {
                    $("#listaRecargas").html("<div class='col-lg-12 text-center'>"+e+"</div>");
                    $("#aguardando").html("0");
                    $("#paga").html("0");
                    $("#finalizada").html("0");
                    $("#cancelada").html("0");
                }
            }
        });
    }
    
    
    
    function pagar(idRecargaCartao) {
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_RECHARGES_PAGAMENTO_DADOS  ?>',
            method: 'post',
            dataType: 'json',
            data: {
                idRecargaCartao: idRecargaCartao
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#dialogPagarRecargaNumero").html(json.id);
                        $("#dialogPagarRecargaValor").html(json.valor);
                        $("#dialogPagarRecargaAddress").html(json.address);
                        $("#dialogPagarRecargaQrCode").attr("src", "<?php echo URLBASE_CLIENT . Utils\Rotas::R_QRCODEINVOICE ?>/"+json.address);
                        $("#dialogPagarRecarga").modal();
                        
                        g_iCount = new Number();

                        g_iCount = json.timeToExpire;
                        if (timeout !== null) {
                            clearTimeout(timeout);
                        }
                        startCountdown();
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
            }
        });
    }
    
    
    
    function dialogFinalizarRecarga(idRecargaCartao) {
        $("#dialogFinalizarRecargaIdRecargaCartao").val(idRecargaCartao);
        $("#dialogFinalizarRecarga").modal();
    }
    
    
    function confirmarFinalizacaoRecarga() {
        $("#dialogFinalizarRecargaFechar, #dialogFinalizarRecargaConfirmar").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_RECHARGES_FINALIZAR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                idRecargaCartao: $("#dialogFinalizarRecargaIdRecargaCartao").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#recarga-"+$("#dialogFinalizarRecargaIdRecargaCartao").val()).replaceWith(json.html);
                        $("#dialogFinalizarRecargaFechar").prop("disabled", false).trigger("click");
                        showNotyAlert(json.mensagem, "s");
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#dialogFinalizarRecargaFechar, #dialogFinalizarRecargaConfirmar").prop("disabled", false);
            }
        });
    }
    
    
    function validarCartao() {
        var numero = "";
        var i = 0;
        for (i = 0; i < $("#inputNumeroCartao").val().length; i++) {
            if ($("#inputNumeroCartao").val().charAt(i) !== "_" && $("#inputNumeroCartao").val().charAt(i) !== "-") {
                numero += $("#inputNumeroCartao").val().charAt(i);
            }
        }
        $("#dialogRecarregarCartaoConfirmar").prop("disabled", true);
        if (numero.length === 16) {
            $.ajax({
                url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_RECHARGES_CARTAO_DADOS ?>',
                method: 'post',
                dataType: 'json',
                data: {
                    cartao: $("#inputNumeroCartao").val()
                },
                success: function (json) {
                    try {
                        if (json.sucesso) {
                            $("#cliente-cartao").html("Titular do cartão: " + json.cliente);
                            $("#erro-cartao").html("");
                            $("#dialogRecarregarCartaoConfirmar").prop("disabled", false);
                        } else {
                            $("#cliente-cartao").html("");
                            $("#erro-cartao").html(json.mensagem);
                            $("#dialogRecarregarCartaoConfirmar").prop("disabled", true);
                        }
                    } catch (e) {
                        $("#cliente-cartao").html("");
                        $("#erro-cartao").html(e);
                        $("#dialogRecarregarCartaoConfirmar").prop("disabled", true);
                    }
                }
            });
        }
    }
    
    
    function recarregar() {
        $("#dialogRecarregarCartaoConfirmar, #dialogRecarregarCartaoFechar").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_RECHARGES_CARTAO_VALIDAR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                cartao: ($("#recarregarMeuCartao").is(":checked") ? $("#selectIdPedidoCartao").val() : $("#recarregarCartaoTerceiro").is(":checked") ? $("#inputNumeroCartao").val() : ""),
                valor: $("#valor").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#dialogRecarregarCartaoFechar").prop("disabled", false).trigger("click");
                        listarRecargas();
                        pagar(json.recarga);
                    } else {
                        $("#erro-cartao").html(json.mensagem);
                    }
                } catch (e) {
                    $("#erro-cartao").html(e);
                }
                $("#dialogRecarregarCartaoConfirmar, #dialogRecarregarCartaoFechar").prop("disabled", false);
            }
        });

    }
    
    function dialogRecargaCartao() {
        $("#dialogRecarregarCartao").modal();
        $("#recarregarMeuCartao").prop("checked", true).trigger("change");
        $("#inputNumeroCartao, #valor").val("");
        $("#cliente-cartao, #erro-cartao").html("");
        
    }
    
    
    var g_iCount = new Number();
 
    var g_iCount = null;
    var timeout = null;
    function startCountdown(){
           if((g_iCount - 1) > 0){
                   g_iCount = g_iCount - 1;

                   var min = ((g_iCount - (g_iCount % 60)) / 60);
                   var seg = g_iCount % 60;

                   var sMin = (min < 10 ? "0"+ min : min);
                   var sSeg = (seg < 10 ? "0"+ seg : seg);
                   $("#dialogPagarRecargaTimeToExpire").html(sMin+':' + sSeg);
                   timeout = setTimeout('startCountdown()',1000);
           } else {
                $("#dialogPagarRecargaTimeToExpire").html("Expirada");
                
           }
    }
</script>


<div class="modal fade" id="dialogFinalizarRecarga" tabindex="-1" role="dialog" aria-labelledby="dialogFinalizarRecarga" aria-hidden="true" >
    <div class="modal-dialog" style="width: 800px;">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="dialogFinalizarRecargaLabel">Marcar Recarga como Finalizada</h4>
            </div>
            <div class="modal-body">
                <input type="hidden" id="dialogFinalizarRecargaIdRecargaCartao" />
                <div class="row">
                    <div class="col col-lg-12" >
                        Marcar a recarga como finalizada significa ter efetuado o crédito no cartão do cliente. Deseja continuar?
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="dialogFinalizarRecargaFechar" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-success" id="dialogFinalizarRecargaConfirmar" onclick="confirmarFinalizacaoRecarga();">Confirmar Finalização</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>



<div class="modal fade" id="dialogRecarregarCartao" tabindex="-1" role="dialog" aria-labelledby="dialogRecarregarCartao" aria-hidden="true" >
    <div class="modal-dialog" style="width: 800px;">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="dialogRecarregarCartaoLabel">Recarregar Cartão</h4>
            </div>
            <div class="modal-body">
                
                <div class="row">
                    <div class="col col-lg-6">
                        <div class="form-group">
                             <label class="radio-inline">
                                <input type="radio" name="tipoRecargaCartao" id="recarregarMeuCartao" value="1" checked="">Recarrgar meu Cartão
                            </label>
                        </div>
                    </div>
                    <div class="col col-lg-6">
                        <div class="form-group">
                             <label class="radio-inline">
                                <input type="radio" name="tipoRecargaCartao" id="recarregarCartaoTerceiro" value="2" checked="">Recarregar Cartão de Terceiro
                            </label>
                        </div>
                    </div>
                </div>
                
                <div class="row">
                    <div class="col col-lg-6" id="containerMeuCartao">
                        <div class="form-group">
                            <label>Selecione o cartão</label>
                            <select class="form-control" id="selectIdPedidoCartao">
                                <?php foreach ($cartoes as $cartao) { ?>
                                <option value="<?php echo $cartao->numeroCartao ?>"><?php echo $cartao->numeroCartao ?></option>
                                <?php }?>
                            </select>
                        </div>
                    </div>
                    <div class="col col-lg-6" id="containerCartaoTerceiro" >
                        <div class="form-group">
                            <label>Informe o número do cartão</label>
                            <input type="text" class="form-control" id="inputNumeroCartao"  />
                        </div>
                    </div>
                    <div class="col col-sm-6">
                        <div class="form-group">
                            <label>Valor da Recarga*</label>
                            <input type="text" class="form-control" id="valor"  />
                        </div>
                    </div>
                </div>
                
                
                <div class="row">
                    <div class="col col-xs-12" style="color: green;" id="cliente-cartao">

                    </div>
                </div>
                <div class="row">
                    <div class="col col-xs-12" style="color: red;"  id="erro-cartao">

                    </div>
                </div>
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="dialogRecarregarCartaoFechar" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-primary" id="dialogRecarregarCartaoConfirmar"  onclick="recarregar();">Confirmar Recarga</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>



<div class="modal fade" id="dialogPagarRecarga" tabindex="-1" role="dialog" aria-labelledby="dialogPagarRecarga" aria-hidden="true" >
    <div class="modal-dialog" style="width: 800px;">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="dialogPagarRecargaLabel">Dados para pagamento da recarga</h4>
            </div>
            <div class="modal-body">
                
                <div class="row" id="invoice">
                    <div class="col col-sm-12">
                        <h4>Número do pedido: <span id="dialogPagarRecargaNumero"></span></h4>
                        <h4>Envie exatamente o valor de <span id="dialogPagarRecargaValor"></span> para o enredereço:</h4>
                        <h3><span id="dialogPagarRecargaAddress"></span></h3>

                        <br><br>
                        <h4>Ordem expira em : <span id="dialogPagarRecargaTimeToExpire"></span></h4>
                    </div>
                </div>
                
                <div class="row">
                    <div class="col col-sm-12 text-center">
                        <img src="" id="dialogPagarRecargaQrCode" />
                    </div>
                </div>
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="dialogPagarRecargaFechar" data-dismiss="modal">Fechar</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

<?php Utils\Layout::append("mensage_text", $_data) ?>
