<?php Utils\Layout::append("inspina/metas", $_data) ?>

<?php Utils\Layout::append("inspina/scripts", $_data) ?>


<?php Utils\Layout::append("inspina/menu", $_data) ?>
<?php
$moeda = \Modules\principal\Controllers\Principal::getCurrency();
?>
    
    <!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
            <div class="row wrapper border-bottom page-heading" style="background: linear-gradient(to right, #fff, <?php echo $moeda->mainColor ?>) !important;">
                <div class="col-lg-10">
                    <h2>Geração de arquivo de Remessa de Recarga</h2>
                    <ol class="breadcrumb" style="background-color: transparent !important;">
                        <li>
                            Cartões
                        </li>
                        <li class="active">
                            <strong>Geração de arquivo de Remessa de Recarga</strong>
                        </li>
                    </ol>
                </div>
            </div>
</div>
<br>  
    <!-- Main content -->
    <section class="content">

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Recargas Pagas
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <div class="row">
                            <div class="col col-lg-12 text-center">
                                <br>
                                <button class="btn btn-primary" onclick="listar();">
                                    <i class="fa fa-refresh"></i> Atualizar
                                </button>
                                <br>
                            </div>
                        </div>
                        </br>
                        <div class="row">
                            <div class="col col-lg-12 text-center">
                                <br>
                                <a class="btn btn-primary pull-left" target="_DOWNLOAD_REMESSA" href="<?php echo URLBASE_CLIENT   . Utils\Rotas::R_REMRET_DOWNLOAD ?>">
                                    <i class="fa fa-download"></i> Gerar Arquivo Remessa
                                </a>
                                <button class="btn btn-primary pull-right" onclick="dialogImportarArquivo();">
                                    <i class="fa fa-upload"></i> Importar Arquivo Retorno
                                </button>
                                <br>
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col col-lg-12">
                                <ul class="list-group"  id="lista">
                                    
                                </ul>
                            </div>
                        </div>
                    </div>
                    <!-- /.panel-body -->

                </div>
            </div>

        </div>

    </section>
    
    <div class="clearfix"></div>
</div>

<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>

<script>
    $(document).ready(function () {
        
        listar();
        
        
        
        $("#formulario-importacao-excel").ajaxForm({
            beforeSubmit: function () {
                $("#importarExcelFechar, #importarExcelSalvar").prop("disabled", true);
            },
            dataType: 'json',
            success: function (json) {
                try {
                    if (json.sucesso) {
                        showNotyAlert(json.mensagem, "s");
                        listar();
                        $("#importarExcelFechar").prop("disabled", false).trigger("click");
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }

                $("#importarExcelFechar, #importarExcelSalvar").prop("disabled", false);
            }
        });
        
    });
    
    function listar() {
        $("#lista").html("<div class='col-lg-12 text-center'><img src='<?php echo IMAGES ?>loading.gif' /></div>");
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_REMRET_LISTAR ?>',
            method: 'post',
            dataType: 'json',
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#lista").html(json.html);
                    } else {
                        $("#lista").html("<div class='col-lg-12 text-center'>"+json.mensagem+"</div>");
                    }
                } catch (e) {
                    $("#lista").html("<div class='col-lg-12 text-center'>"+e+"</div>");
                }
            }
        });
    }
    
    function dialogImportarArquivo() {
        $("#importarExcel").modal();
        $("#tipo").val("Excel5");
    }
    
    
    function importarArquivoRetorno() {
        $("#formulario-importacao-excel").submit();
    }
</script>




<div class="modal fade" id="importarExcel" tabindex="-1" role="dialog" aria-labelledby="importarExcel" aria-hidden="true" >
    <div class="modal-dialog" style="width: 800px;">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="importarExcelLabel">Importação de Arquivo de Retorno</h4>
            </div>
            <div class="modal-body">
                <form action="<?php echo URLBASE_CLIENT . Utils\Rotas::R_REMRET_UPLOAD ?>" id="formulario-importacao-excel" method="post" enctype="multipart/form-data">
                    <div class="row">
                        
                        <div class="col col-lg-4">
                            <div class="form-group">
                                <label class="control-label">Tipo de Arquivo</label>
                                <select class="form-control" id="tipo" name="tipo">
                                    <option value="Excel5">Excel5</option>
                                    <option value="Excel2003XML">Excel 2003</option>
                                    <option value="Excel2007">Excel 2007</option>
                                </select>
                            </div>
                        </div>
                        <div class="col col-lg-8">
                            <div class="form-group">
                                <label>Arquivo Excel</label>
                                <input type="file" id="dados" name="dados" class="form-control"/>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="importarExcelFechar" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-primary" onclick="importarArquivoRetorno();" id="importarExcelSalvar" >Importar</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>