    <?php $idiomaAtual = new Utils\PropertiesUtils("login", IDIOMA);   
    ?>

    <div class="dropdown pull-right m-t-xs list-unstyled">
        <a class="btn btn-secondary dropdown-toggle" id="idiomaAtual" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
           <?php if($idiomaAtual->getLang() == "pt"){?>
                 <img  src="<?php echo IMAGES ?>flag-brazil.svg" style="width: 24px; height: 24px;" />
           <?php  } ?>
           <?php if($idiomaAtual->getLang() == "en"){ ?>
                 <img  src="<?php echo IMAGES ?>flag-usa.svg" style="width: 24px; height: 24px;" />
           <?php } ?>
            <?php if($idiomaAtual->getLang() == "es"){ ?>
                 <img  src="<?php echo IMAGES ?>flag-spain.svg" style="width: 24px; height: 24px;" />
           <?php } ?>
                 <i class="fa fa-caret-down" style="color: #FFF"></i>
        </a>

        <div class="dropdown-menu text-center" aria-labelledby="dropdownMenuLink" style="min-width: 115px; background-color: rgba(10,23,55,0.4);">
            <a class="dropdown-item m-t-xs" href="javascript:trocarIdioma('en-US');" id="Btlangen"><img  src="<?php echo IMAGES ?>flag-usa.svg" style="max-width: 28px; max-height: 28px;" /> </a>&nbsp;&nbsp;&nbsp;
            <a class="dropdown-item m-t-xs" href="javascript:trocarIdioma('pt-BR');" id="Btlangpt"><img  src="<?php echo IMAGES ?>flag-brazil.svg" style="max-width: 28px; max-height: 28px;" /> </a>&nbsp;&nbsp;&nbsp;
            <a class="dropdown-item m-t-xs" href="javascript:trocarIdioma('es-ES');" id="Btlanges"><img  src="<?php echo IMAGES ?>flag-spain.svg" style="max-width: 28px; max-height: 28px;" /> </a><br>
        </div>
    </div>
<script>
    function trocarIdioma(lang) {
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_IDIOMA_CHANGE ?>',
            method: 'post',
            dataType: 'html',
            data: {
                lang: lang
            },
            success: function () {                
                location.reload();
                
            }
        });
    }
</script>