<?php
use Utils\Rotas;
$moeda = \Modules\principal\Controllers\Principal::getCurrency();
$usuario = Utils\Geral::getLogado();
$cliente = Utils\Geral::getCliente();
$channelConnect = \Utils\Criptografia::encriptyPostId($cliente->id);
$idioma = new \Utils\PropertiesUtils("menu", IDIOMA);
$paridade = Modules\principal\Controllers\Principal::getParity();
?>
            </div>
        </div>
    </div>
</div>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<!-- <script src="<?php echo TEMA; ?>bootstrap/js/bootstrap.min.js"></script> -->
<script src="<?php echo TEMA; ?>plugins/jQuery/jquery-2.2.3.min.js?<?php echo time() ?>"></script>
<script src="<?php echo TEMA; ?>js/jquery-3.1.1.min.js?<?php echo time() ?>"></script>
<script src="<?php echo TEMA; ?>js/jquery.1.11.min.js"></script>
<script src="<?php echo TEMA; ?>js/jquery-ui.min.js"></script>
<script src="<?php echo TEMA; ?>js/jquery.ui.touch-punch.min.js"></script>
<script src="<?php echo TEMA; ?>dist/js/lobipanel.js"></script>
<script src="<?php echo TEMA; ?>lib/highlight/highlight.pack.js"></script>
<script src="<?php echo JS; ?>TweenMax.min.js"></script>
<script src="<?php echo TEMA; ?>js/datatables.js"></script>
<script src="<?php echo TEMA; ?>js/plugins/sweetalert/sweetalert.min.js"></script>
<script src="<?php echo TEMA; ?>js/plugins/metisMenu/jquery.metisMenu.js"></script>
<script src="<?php echo TEMA; ?>js/plugins/slimscroll/jquery.slimscroll.min.js"></script>
<script src="<?php echo TEMA; ?>js/plugins/codemirror/codemirror.js"></script>
<script src="<?php echo TEMA; ?>js/plugins/sparkline/jquery.sparkline.min.js"></script>
<script src="<?php echo TEMA; ?>js/plugins/chosen/chosen.jquery.js"></script>
<script src="<?php echo TEMA; ?>js/plugins/select2/select2.full.min.js"></script>
<script src="<?php echo TEMA; ?>js/plugins/pace/pace.min.js"></script>
<script src="<?php echo TEMA; ?>js/plugins/iCheck/icheck.min.js"></script>
<script src="<?php echo TEMA; ?>js/plugins/datapicker/bootstrap-datepicker.js"></script>
<script src="<?php echo JS; ?>jquery.maskedinput.min.js"></script>
<script src="<?php echo JS; ?>jquery.inputmask.js"></script>
<script src="<?php echo JS; ?>numberformat.js"></script>
<script src="<?php echo JS; ?>jquery.form.js"></script>
<script src="<?php echo JS; ?>jquery.alphanumeric.js"></script>
<script src="<?php echo TEMA; ?>js/plugins/jquery-ui/jquery-ui.min.js"></script>
<script src="<?php echo TEMA; ?>js/plugins/clipboard/clipboard.min.js" type="text/javascript"></script>
<script src="<?php echo TEMA; ?>js/plugins/cropper/cropper.min.js"></script>
<script src="<?php echo TEMA; ?>js/plugins/jasny/jasny-bootstrap.min.js"></script>
<script src="<?php echo TEMA; ?>js/plugins/codemirror/codemirror.js"></script>
<script src="<?php echo TEMA; ?>js/plugins/codemirror/mode/xml/xml.js"></script>
<script src="<?php echo TEMA; ?>js/plugins/nestable/jquery.nestable.js"></script>
<script src="<?php echo TEMA; ?>js/plugins/iCheck/icheck.min.js"></script>
<script src="<?php echo TEMA; ?>js/plugins/slimscroll/jquery.slimscroll.min.js"></script>
<script src="<?php echo TEMA; ?>js/plugins/footable/footable.all.min.js"></script>
<script src="<?php echo TEMA; ?>js/plugins/dropzone/dropzone.js"></script>
<script src="<?php echo TEMA; ?>js/plugins/blueimp/jquery.blueimp-gallery.min.js"></script>
<script src="<?php echo TEMA; ?>js/plugins/scrollto/jquery-scrollto.js"></script>
<script src="<?php echo JS; ?>currencymask.js"></script>
<script src="<?php echo TEMA; ?>js/jAlert/jAlert-functions.js?<?php echo time(); ?>"></script>
<script src="<?php echo TEMA; ?>js/jAlert/jAlert.js?<?php echo time(); ?>"></script>
<script src="<?php echo JS; ?>pusher.min.js"></script>

<script src="<?php echo TEMA; ?>js/plugins/toastr/toastr.min.js"></script>
<link href="<?php echo TEMA; ?>css.old/plugins/toastr/toastr.min.css" rel="stylesheet"> 

<head>
    <style>
        #toast-container > .toast {
            background-image: none !important;
        }
    </style>
</head>

<?php //\Utils\Layout::append("notificacoes/cadastro_notificacao", $_data)?>

<!-- <script>
        $.fn.modal.Constructor.prototype.enforceFocus = function() {};
</script>     -->
</body>
<script type="text/javascript">
function tool(){
    $('[data-toggle="tooltip"]').tooltip();
}

$(document).ready(function () {
        initPage();



        //CONNECT PUSHER
        var pusherBook = new Pusher('6d6796b91c225c158e45', {
            cluster: 'mt1'
        });

        var channel = pusherBook.subscribe('channel_<?php echo $channelConnect?>');

        channel.bind('notificacoes', function (json) {

            const data = json.message

            $('.'+data.queueReturnUid).html(data.msg)
            showNotyAlert(data.msg, 's');
        });
        
        $('#sair,#logout').click(function () {
            swal({
                title: "<?php echo $idioma->getText("temCerteza")?>",
                text: "<?php echo $idioma->getText("seraNecessario")?>" ,
                type: "success",
                showCancelButton: true,
                closeOnConfirm: false,
                showLoaderOnConfirm: true,
                confirmButtonColor: "#18a689",
                confirmButtonText: "<?php echo $idioma->getText("simQueroSair")?>",
                cancelButtonText: "<?php echo $idioma->getText("queroFicar")?>"
            },
                    function () {
                        setTimeout(function () {
                            swal("<?php echo $idioma->getText("sessaFinalizada")?>");
                            window.location.href = "<?php echo URLBASE_CLIENT . Utils\Rotas::R_LOGOUT ?>";
                        }, 1000);
                    });
        });
        
        $('.home').click(function () {
            swal({
                title: "<?php echo $idioma->getText("aviso")?>",
                text: "<?php echo $idioma->getText("redirecionando")?>",
                imageUrl: "<?php echo NC ?>images/img_site_seguro.png",
                timer: 6000,
                showConfirmButton: false

            },
                    function () {
                        setTimeout(function () {
                            swal("<?php echo $idioma->getText("sessaFinalizada")?>");
                            window.location.href = "<?php echo URLBASE_CLIENT ?>";
                        }, );
                    });
        });

        
        
    initPage();
        
        setInterval(function() {
                    initPage();
                  },10000);
         
        setInterval(function() {
                    //getTopMenuCotacoes();
                  },60000);
                  
                  
        setInterval(function() {
                    getNotificationsToUser();
                    getAlertsToUser();
                  },300000);
                  
    });

    var initFlag = false;
    function initPage() {
        if (!initFlag) { 
            
            
        }
    }

    function setCurrency(codigo) {
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_CURRENCY ?>',
            method: 'post',
            dataType: 'json',
            data: {
                codigo: codigo
            },
            success: function (json) {
                location.reload();
            }
        });
    }

    
    function launcherNotification(mensagem, usuario ,codigo, tipo) {
        
        toastr.options = {
            closeButton: true,
            debug: true,
            newestOnTop: true,
            progressBar: true,
            positionClass: 'toast-top-left',
            preventDuplicates: true,
            showDuration: 300,
            hideDuration: 1000,
            timeOut: 5000,
            extendedTimeOut: 1000,
            showEasing: 'swing',
            hideEasing: 'linear',
            showMethod: 'fadeIn',
            hideMethod: 'fadeOut',
            timeOut: 7500,
            positionClass: "toastr-bottom-center",
            onShown: function (){
                $.ajax({
                    url: "<?php echo URLBASE_CLIENT . Utils\Rotas::R_NOTIFICACOES_SHOWN ?>",
                    method: 'post',
                    dataType: 'json',
                    data: {
                        codigo: codigo
                    }
                });
            },
            onHidden: function () {
            }
        };
        
        if (tipo === "s") {
            toastr.success(usuario, mensagem);
        } else if (tipo === "e") {
            toastr.success(usuario, mensagem);
        } else if (tipo === "w") {
            toastr.warning(usuario, mensagem);
        } 
    }
    
    
    function showNotyAlert(mensagem, tipo) {
        toastr.options = {
            closeButton: true,
            debug: true,
            newestOnTop: true,
            progressBar: true,
            positionClass: 'toast-top-left',
            preventDuplicates: true,
            showDuration: 300,
            hideDuration: 1000,
            timeOut: 5000,
            extendedTimeOut: 1000,
            showEasing: 'swing',
            hideEasing: 'linear',
            showMethod: 'fadeIn',
            hideMethod: 'fadeOut',
            timeOut: 7500,
            positionClass: "toast-top-left",
        };
        
        if (tipo === "s") {
            toastr.success("<?php echo TITULO ?>", mensagem);
        } else if (tipo === "e") {
            toastr.error("<?php echo TITULO ?>", mensagem);
        } else if (tipo === "w") {
            toastr.warning("<?php echo TITULO ?>", mensagem);
        }

    }
    
    var notificationsToUserFlag = false;
    function getNotificationsToUser() {
        if (!notificationsToUserFlag) {
            $.ajax({
                url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_NOTIFICACOES_LISTAR_NAOEXIBIDAS ?>',
                method: 'post',
                dataType: 'json',
                beforeSend: function () {
                    notificationsToUserFlag = true;
                },
                complete: function () {
                    notificationsToUserFlag = false;
                },
                success: function (json) {
                    try {
                        if (json.sucesso) {
                            var i = 0;
                            for (i = 0; i < json.notificacoes.length; i++) {
                                launcherNotification(json.notificacoes[i].html, json.notificacoes[i].usuario.nome, json.notificacoes[i].id, json.notificacoes[i].tipo);
                            }
                        } else {
                            console.log(json.mensagem);
                        }
                    } catch (e) {
                        console.log(e);
                    }
                    notificationsToUserFlag = false;
                }
            });
        }
    }
    var topMenuCotacoesFlag = false;
    function getTopMenuCotacoes() {
        if (!topMenuCotacoesFlag) {
            $.ajax({
                url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_COTACOES_GET ?>',
                method: 'post',
                dataType: 'json',
                beforeSend: function() {
                    topMenuCotacoesFlag = true;
                },
                complete: function () {
                    topMenuCotacoesFlag = false;
                },
                success: function (json) {
                    try {
                        if (json.sucesso) {
                            if (typeof json.cotacoes !== 'undefined') {
                                var i = 0;
                                for (i = 0; i < json.cotacoes.length; i++) {
                                    var code = json.cotacoes[i].code;

                                    $("#top-currency-pricing-buy-"+code).html(json.cotacoes[i].buy);
                                    $("#top-currency-pricing-sell-"+code).html(json.cotacoes[i].sell);
                                    $("#top-currency-pricing-volume-"+code).html(json.cotacoes[i].volume);
                                }
                            }
                        } else {
                            console.log(json.mensagem);
                        }
                    } catch (e) {
                        console.log(e);
                    }
                    topMenuCotacoesFlag = false;
                }
            });
        }
    }
    
    var alertsToUserFlag = false;
    function getAlertsToUser() {
        if (!alertsToUserFlag) {
            $.ajax({
                url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_NOTIFICACOES_ALERTAS ?>',
                method: 'post',
                dataType: 'json',
                beforeSend: function () {
                    alertsToUserFlag = true;
                },
                complete: function () {
                    alertsToUserFlag = false;
                },
                success: function (json) {
                    try {
                        if (json.sucesso) {
                            $(".notifications-alert-dropdown").remove();
                            $(".drop-down-notifications").prepend(json.html);
                            $(".notifications-alert-news").html(json.qtd);
                        } else {
                            console.log(json.mensagem);
                        }
                    } catch (e) {
                        console.log(e);
                    }
                    alertsToUserFlag = false;
                }
            });
        }
    }
    
    
    
    function mascaraValor(valor) {
        valor = valor.toString().replace(/\D/g,"");
        valor = valor.toString().replace(/(\d)(\d{8})$/,"$1.$2");
        valor = valor.toString().replace(/(\d)(\d{5})$/,"$1.$2");
        valor = valor.toString().replace(/(\d)(\d{2})$/,"$1,$2");

        return valor;
    }
    
    <?php if (isset($cliente) && $cliente != null) { ?>
  
<?php } ?>
</script>
</html>
<?php //\Utils\Layout::append("estorno/estorno", $_data)?>
<?php //\Utils\Layout::append("chat/chat", $_data)?>


