<?php 
use Utils\Rotas;
$idioma = new \Utils\PropertiesUtils("menu", IDIOMA);

$clienteRn = new \Models\Modules\Cadastro\ClienteRn();
$cliente = Utils\Geral::getCliente();
$clienteRn->conexao->carregar($cliente);
\Utils\Geral::setLogado(null, $cliente);

$brand = \Models\Modules\Cadastro\BrandRn::getBrand();

$configuracao = \Models\Modules\Cadastro\ConfiguracaoRn::get();
\Utils\Geral::setCliente($cliente);


    if($cliente->modoOperacao === \Utils\Constantes::MODO_BASIC){
        $modo = true;
    } else {
        $modo = false;
    }

$sexo = (\Utils\Geral::isCliente() ? $cliente->sexo : "M");
if (strtolower($sexo) == "m") {
    $foto = TEMA . "dist/img/avatar5.png";
} else {
    $foto = TEMA . "dist/img/avatar2.png";
}

//if (\Utils\Geral::isCliente() && !empty($cliente->foto)) {
//    $foto = URLBASE_CLIENT . Rotas::R_FILESMANAGER  . "/" . \Utils\Criptografia::encriptyPostId($cliente->foto);
//}

$percentualPerfil = (\Utils\Geral::isCliente() ? $cliente->getPercentualPerfil() : 100);
$rota = $_data["_rota"];


$saldo = isset($_data["saldo"]) ? $_data["saldo"] : 0;
$moedaRn = new Models\Modules\Cadastro\MoedaRn();
$orderBookRn = new \Models\Modules\Cadastro\OrderBookRn();
$moedaReal = new \Models\Modules\Cadastro\Moeda(Array("id" => 1));
$moedaBitcoin = new \Models\Modules\Cadastro\Moeda(Array("id" => 2));
$moedaLitecoin = new \Models\Modules\Cadastro\Moeda(Array("id" => 4));
$moedaDash = new \Models\Modules\Cadastro\Moeda(Array("id" => 7));
$moedaDoge = new \Models\Modules\Cadastro\Moeda(Array("id" => 13));
$moedaEthereum = new \Models\Modules\Cadastro\Moeda(Array("id" => 3));
$moedaTrueUsd = new \Models\Modules\Cadastro\Moeda(Array("id" => 35));
$paridadeRn = new Models\Modules\Cadastro\ParidadeRn();
$paridadesReal = Array();
$paridadesBitcoin = Array();
$paridadesLitecoin = Array();
$paridadesDash = Array();
$paridadesDoge = Array();
$paridadesEthereum = Array();
$paridadesTrueUsd = Array();
$todasAsParidades = $paridadeRn->getListaTodasParidades(false);

foreach ($todasAsParidades as $paridade) {

    # 04/07/2019 - Caique fix $paridade->idMoedaTrade to $paridade->id 
    switch ($paridade->id) {
        case 1:
            $paridadesReal[] = $paridade;
            break;
        case 2:
            $paridadesBitcoin[] = $paridade;
            break;
        case 4:
            $paridadesLitecoin[] = $paridade;
            break;
        case 7:
            $paridadesDash[] = $paridade;
            break;
        case 13:
            $paridadesDoge[] = $paridade;
            break;
        case 3:
            $paridadesEthereum[] = $paridade;
            break;
        case 35:
            $paridadesTrueUsd[] = $paridade;
            break;

        default:
            break;
    }
}

$paridade = Modules\principal\Controllers\Principal::getParity();
$moeda = $paridade->moedaBook;

/*if (\Utils\Geral::isCliente()) {
    try {
        $estornoRn = new Models\Modules\Cadastro\EstornoRn();
        $estornos = $estornoRn->listarDepositosDadosPendentes($cliente);
    } catch (\Exception $e) {
        
    }
}*/

?>
<style>
    .testehover:hover {  
    text-decoration: none !important;
    background-color: #003759 !important;
    }
    .nav .open>a, .nav .open>a:focus, .nav .open>a:hover {
    background-color: #003759 !important;
    border-color: #337ab7 !important;
    }
    
    .top-navigation .navbar-brand {
        background: <?php echo $brand->colorBackground ?> !important;
    }
    .navbar-brand {
    float: none;
    }
      .navbar-collapse {
     max-height: calc(100vh - 50px)!important;
  }
</style>
<link href="<?php echo TEMA ?>bootstrap_nativo/css/bootstrap-toggle.min.css" rel="stylesheet">
<body class="top-navigation md-skin-config">
    <div id="wrapper">
    <nav class="navbar navbar-static-top text-center" role="navigation">
            <div class="navbar-header">
                <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
                    <i class="fa fa-reorder"></i>
                </button>
                <a href="book" class="navbar-brand text-center" style="width: 240px !important; color: <?php echo $brand->colorNome ?>; padding-top: 5px !important; padding-bottom: 5px !important; ">
                    <img src="<?php echo IMAGES . $brand->logo ?>" style="max-height: 50px; display: inline !important; " /> </a>
            </div>         
            <div class="navbar-collapse collapse" id="navbar">
                <ul class="nav navbar-nav">
                    <?php echo \Utils\Layout::menu($_data)?>
                    <li class="visible-xs">
                        <li class="visible-xs"><a href="<?php echo URLBASE_CLIENT . \Utils\Rotas::R_MEUSDADOS ?>"><?php echo $idioma->getText("meuPerfilD") ?></a></li>
                    </li>
                    <li class="visible-xs">
                        <a style="text-decoration: none !important; "><?php echo $idioma->getText("idioma") ?> - 
                            <span onclick="javascript:trocarIdioma('pt-BR');"> PT |</span>
                            <span onclick="javascript:trocarIdioma('en-US');"> EN |</span>
                            <span onclick="javascript:trocarIdioma('es-ES');">ES</span>
                        </a>
                    </li>
                    <li class="visible-xs">
                        <a href="#" id="logout">
                            <?php echo $idioma->getText("sair") ?>
                        </a>
                    </li>
                </ul>
                
                <ul class="nav navbar-nav navbar-right " style="display: flex !important; align-items: center !important;">
                    
                    <li class="visible-sm visible-md visible-lg visible-xl" style='color: #a7b1c2;'>
                        <small>
                            <?php 
                            $arrayNomeCliente = explode(" ",$cliente->nome);
                            $clienteNome = $arrayNomeCliente[0]. ' ' .$arrayNomeCliente[1];
                            $clienteNome = mb_convert_case($clienteNome, MB_CASE_LOWER, "UTF-8");
                            echo ucwords($clienteNome);
                            ?>
                        </small>
                    </li>
                    
                    
                    
                    
                    <li class="dropdown visible-sm visible-md visible-lg visible-xl">
                        <a role="button" class="dropdown-toggle testehover" data-toggle="dropdown">
                            <img  src="<?php echo $foto ?>" id="profileImagemUserMenuTop" class="img-circle m-b-xs" height="25px" width="25px" style="border: 1px #fff solid; margin-top: -15px !important; "/>
                            <span class="caret"></span>
                        </a>   
                        <ul class="dropdown-menu">
                            <li class="dropdown"><a href="<?php echo URLBASE_CLIENT . \Utils\Rotas::R_MEUSDADOS ?>"><?php echo $idioma->getText("meuPerfilD") ?></a></li>
                            <?php if($configuracao->nightMode > 0){ ?>
                            <li class="dropdown-submenu">
                                <a style="text-decoration: none !important; color: #676a6c !important;"> 
                                    <span onclick="javascript:modecolor('D');"> <?php echo $idioma->getText("mododia") ?> - <i class="fa fa-sun-o"></i> |</span>
                                    <span onclick="javascript:modecolor('N');"> <i class="fa fa-moon-o"></i> - <?php echo $idioma->getText("modonoite") ?></span>
                                </a>
                            </li>
                            <?php } ?>
                            <li class="dropdown-submenu">
                                <a style="text-decoration: none !important; color: #676a6c !important;"><?php echo $idioma->getText("idioma") ?> - 
                                    <span onclick="javascript:trocarIdioma('pt-BR');"> PT |</span>
                                    <span onclick="javascript:trocarIdioma('en-US');"> EN |</span>
                                    <span onclick="javascript:trocarIdioma('es-ES');">ES</span>
                                </a>
                            </li>
                            <li class="dropdown">
                                <a href="#" id="logout">
                                    <?php echo $idioma->getText("sair") ?>
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>

        <div id="page-wrapper" class="gray-bg">
        <div class="row border-bottom">
        
        <?php if (isset($estornos) && sizeof($estornos) > 0) { ?>
            <div class="row">
                <div class="col col-lg-12">
                    <div class="alert alert-warning">
                        <h4><?php echo $idioma->getText("vcPossuiProcedimento") ?><?php echo (sizeof($estornos) > 0 ? "(s)" : "") ?> <?php echo $idioma->getText("estornoPendente") ?><?php echo (sizeof($estornos) > 0 ? "s" : "") ?></h4> <br>
                        <?php 
                        foreach ($estornos as $estorno) {                           
                            ?>
                        <?php echo $idioma->getText("deposito") ?> <?php echo $estorno->id ?>: <a href="javascript:abrirModalContaEstorno('<?php echo \Utils\Criptografia::encriptyPostId($estorno->id)?>');"><?php echo $idioma->getText("cliqueAqui") ?></a> 
                        <?php echo $idioma->getText("paraInformarConta") ?>
                        <?php if ($estorno->status == \Utils\Constantes::EXTORNO_REJEITADO) { ?>
                        (<?php echo $idioma->getText("rejeitado") ?><?php echo $estorno->motivoRejeicao ?>).
                        <?php } ?>
                        <br>
                            <?php
                        }
                        ?>
                    </div>
                </div>
            </div>
        <?php } ?>    
            
        <?php if ($cliente->documentoVerificado == 0) { ?>
            <div class="row" id="informativoKyc">
            <div class="col col-lg-12">
                <div class="alert alert-info">
                    <h4><strong>Novidade na área</strong></h4>
                    <h5>Como sempre, nosso principal objetivo é manter a segurança e a privacidade de seus ativos digitais...</h5>
                    <h5>Pensando nisso, foi implementando o processo de verificação de conta, faça agora mesmo <a href="<?php echo URLBASE_CLIENT ?>myprofile" style="font-size: 14px;"><strong>CLICANDO 
                        AQUI</strong></a> e mantenha sua conta segura.</h5>
                </div>
            </div>
        </div>
    <?php } ?>
       
    </div>

<script src="<?php echo TEMA; ?>js/jquery-2.1.1.js"></script>
<script src="<?php echo TEMA ?>bootstrap_nativo/js/bootstrap-toggle.min.js"></script>
<script type="text/javascript">
         $(document).ready(function () {
          $('.dropdown-submenu a.test').on("click", function(e){
            $(this).next('ul').toggle();
            e.stopPropagation();
            e.preventDefault();
          });
          $("#modeLi").attr("hidden", false);
          $("#mode").attr("hidden", false);

          setInterval(online, 20000);
        });
        
        var flagClientesOnline = true;
        function online() {
            if (flagClientesOnline) {
                $.ajax({
                    url: '<?php echo URLBASE_CLIENT . \Utils\Rotas::R_CLIENTES_ONLINE?>',
                    dataType: 'json',
                    method: 'post',
                    beforeSend: function () {
                        flagClientesOnline = false;
                    },
                    success: function (json) {
                        try {
                            if (json.sucesso == false) {
                                showNotyAlert(json.mensagem, "e");   
                                location = json.url;
                            }
                        } catch (e) {
                            
                        }
                        flagClientesOnline = true;
                    },
                    complete: function () {
                        flagClientesOnline = true;
                    }
                });
            }
        }
        
        function trocarIdioma(lang) {
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_IDIOMA_CHANGE ?>',
            method: 'post',
            dataType: 'html',
            data: {
                lang: lang
            },
            success: function () {                
                location.reload();
                
            }
        });
    }
    
    function alertaKyc() {
        $("#informativoKyc").hide();
    } 
    
    
    function modecolor(mode) {
        var expires = new Date();
        expires.setTime(expires.getTime() + (7 * 24 * 60 * 60 * 1000));
        document.cookie = 'Color' + '=' + mode + ';expires=' + expires.toUTCString();
        location.reload();
    }    
</script>
<?php
if (AMBIENTE == "producao" && $cliente->documentoVerificado == 1) { ?>

        <script type="text/javascript">
        var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
        Tawk_API.visitor = {
            name  : '<?php echo ucwords($cliente->nome); ?>',
            email : '<?php echo $cliente->email; ?>',
            hash  : '<?php echo hash_hmac("sha256", $cliente->email, "0301f9d39bac149c44de8a63c9b58b6301351330"); ?>'
        };
        (function(){
        var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
        s1.async=true;
        s1.src='https://embed.tawk.to/5ff8508aa9a34e36b96a5a33/1ergvl7an';
        s1.charset='UTF-8';
        s1.setAttribute('crossorigin','*');
        s0.parentNode.insertBefore(s1,s0);
        })();

        </script>

<?php } ?>
        


    






