<?php
use Utils\Rotas;
$idioma = new \Utils\PropertiesUtils("menu", IDIOMA);

$clienteRn = new \Models\Modules\Cadastro\ClienteRn();
$cliente = Utils\Geral::getCliente();
$clienteRn->conexao->carregar($cliente);
\Utils\Geral::setLogado(null, $cliente);

$brand = \Models\Modules\Cadastro\BrandRn::getBrand();

$configuracao = \Models\Modules\Cadastro\ConfiguracaoRn::get();
\Utils\Geral::setCliente($cliente);

if($cliente->modoOperacao === \Utils\Constantes::MODO_BASIC){
    $modo = true;
} else {
    $modo = false;
}

$sexo = (\Utils\Geral::isCliente() ? $cliente->sexo : "M");
if (strtolower($sexo) == "m") {
    $foto = TEMA . "dist/img/avatar5.png";
} else {
    $foto = TEMA . "dist/img/avatar2.png";
}

$percentualPerfil = (\Utils\Geral::isCliente() ? $cliente->getPercentualPerfil() : 100);
$rota = $_data["_rota"];

$saldo = isset($_data["saldo"]) ? $_data["saldo"] : 0;
$moedaRn = new Models\Modules\Cadastro\MoedaRn();
$orderBookRn = new \Models\Modules\Cadastro\OrderBookRn();
$moedaReal = new \Models\Modules\Cadastro\Moeda(Array("id" => 1));
$moedaBitcoin = new \Models\Modules\Cadastro\Moeda(Array("id" => 2));
$moedaLitecoin = new \Models\Modules\Cadastro\Moeda(Array("id" => 4));
$moedaDash = new \Models\Modules\Cadastro\Moeda(Array("id" => 7));
$moedaDoge = new \Models\Modules\Cadastro\Moeda(Array("id" => 13));
$moedaEthereum = new \Models\Modules\Cadastro\Moeda(Array("id" => 3));
$moedaTrueUsd = new \Models\Modules\Cadastro\Moeda(Array("id" => 35));
$paridadeRn = new Models\Modules\Cadastro\ParidadeRn();
$paridadesReal = Array();
$paridadesBitcoin = Array();
$paridadesLitecoin = Array();
$paridadesDash = Array();
$paridadesDoge = Array();
$paridadesEthereum = Array();
$paridadesTrueUsd = Array();
$todasAsParidades = $paridadeRn->getListaTodasParidades(false);

foreach ($todasAsParidades as $paridade) {

    # 04/07/2019 - Caique fix $paridade->idMoedaTrade to $paridade->id 
    switch ($paridade->id) {
        case 1:
            $paridadesReal[] = $paridade;
            break;
        case 2:
            $paridadesBitcoin[] = $paridade;
            break;
        case 4:
            $paridadesLitecoin[] = $paridade;
            break;
        case 7:
            $paridadesDash[] = $paridade;
            break;
        case 13:
            $paridadesDoge[] = $paridade;
            break;
        case 3:
            $paridadesEthereum[] = $paridade;
            break;
        case 35:
            $paridadesTrueUsd[] = $paridade;
            break;

        default:
            break;
    }
}

$paridade = Modules\principal\Controllers\Principal::getParity();
$moeda = $paridade->moedaBook;

?>
<link rel="stylesheet" href="assets/css/style.css">

<body>
    <header id="dark-bb">
        <nav class="navbar navbar-expand-lg" id="dark">
            <a class="navbar-brand" href="<?php echo $_SERVER['EnvUrlProd'] ?>/portfolio"><img src="<?php echo IMAGES . "logo-ca.png" ?>" style="max-height: 40px;"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#headerMenu"
                aria-controls="headerMenu" aria-expanded="false" aria-label="Toggle navigation">
                <i class="icon ion-md-menu"></i>
            </button>

            <div class="collapse navbar-collapse" id="headerMenu">
                <ul class="navbar-nav mr-auto"  >
                    <li class="nav-item">
                        <?php echo \Utils\Layout::menu($_data)?>
                    </li>
                    <!-- <li class="nav-item">
                        tst
                    </li> -->
                </ul>


                <ul class="navbar-nav navbar-right " style="display: flex !important; align-items: center !important;">
                    <li class="nav-item dropdown"">
                        <!-- <a style="color:#00dfff;" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false">
                        <?php 
                            $arrayNomeCliente = explode(" ",$cliente->nome);
                            $clienteNome = $arrayNomeCliente[0]. ' ' .$arrayNomeCliente[1];
                            $clienteNome = mb_convert_case($clienteNome, MB_CASE_LOWER, "UTF-8");
                            echo ucwords($clienteNome);
                            ?>
                        </a> -->

                        <li class="nav-item dropdown header-img-icon">
                            <!-- <a style="color:#00dfff;" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true"
                                aria-expanded="false"> -->
                                <!-- <img src="assets/img/avatar.svg" alt="avatar"> -->
                                <?php 
                                //$arrayNomeCliente = explode(" ",$cliente->nome);
                                //$clienteNome = $arrayNomeCliente[0]. ' ' .$arrayNomeCliente[1];
                                //$clienteNome = mb_convert_case($clienteNome, MB_CASE_LOWER, "UTF-8");
                                //echo ucwords($clienteNome);
                                ?>
                            <!-- </a> -->

                            <!-- 
                            <div class="dropdown-menu">
                                    <div class="dropdown-header d-flex flex-column align-items-center">
                                    <div class="figure mb-3">
                                    <img src="assets/img/avatar.svg" alt="">
                                    </div>
                                    <div class="info text-center">
                                    <p class="name font-weight-bold mb-0">Tony Stark</p>
                                    <p class="email text-muted mb-3">tonystark@gmail.com</p>
                                    </div>
                                </div> -->

                                <!-- <div class="dropdown-body">
                                    <ul class="profile-nav">
                                        <li class="nav-item">
                                            <a class="nav-link" style="color:#00dfff;" href="<?php echo URLBASE_CLIENT . \Utils\Rotas::R_MEUSDADOS ?>">
                                                <i class="icon ion-md-person"></i>
                                                <span><?php echo $idioma->getText("meuPerfilD") ?></span>
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link red" href="#" id="logout">
                                                <i class="icon ion-md-power"></i>
                                                <?php echo $idioma->getText("sair") ?>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                                
                            </div>
                        -->
                            <li class="nav-item">
                                <a class="nav-link" style="color:#00dfff;" href="<?php echo URLBASE_CLIENT . \Utils\Rotas::R_MEUSDADOS ?>">
                                    <i class="icon ion-md-person"></i>
                                    <span><?php echo $idioma->getText("meuPerfilD") ?></span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link red" href="#" id="logout">
                                    <i class="icon ion-md-power"></i>
                                    <?php echo $idioma->getText("sair") ?>
                                </a>
                            </li>
                        </li>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
</body>

<script src="assets/js/jquery-3.4.1.min.js"></script>
<script src="assets/js/popper.min.js"></script>
<!-- <script src="assets/js/bootstrap.min.js"></script> -->
<script src="assets/js/amcharts-core.min.js"></script>
<script src="assets/js/amcharts.min.js"></script>
<script src="assets/js/jquery.mCustomScrollbar.js"></script>
<!-- <script src="assets/js/custom.js"></script> -->
<script>
$('tbody, .market-news ul').mCustomScrollbar({
    theme: 'minimal',
});
</script>

<script src="<?php echo TEMA; ?>js/jquery-2.1.1.js"></script>
<script src="<?php echo TEMA ?>bootstrap_nativo/js/bootstrap-toggle.min.js"></script>
<script type="text/javascript">
        $(document).ready(function () {
        $('.dropdown-submenu a.test').on("click", function(e){
            $(this).next('ul').toggle();
            e.stopPropagation();
            e.preventDefault();
        });
        $("#modeLi").attr("hidden", false);
        $("#mode").attr("hidden", false);

        setInterval(online, 20000);
        });

        var flagClientesOnline = true;
        function online() {
            if (flagClientesOnline) {
                $.ajax({
                    url: '<?php echo URLBASE_CLIENT . \Utils\Rotas::R_CLIENTES_ONLINE?>',
                    dataType: 'json',
                    method: 'post',
                    beforeSend: function () {
                        flagClientesOnline = false;
                    },
                    success: function (json) {
                        try {
                            if (json.sucesso == false) {
                                showNotyAlert(json.mensagem, "e");   
                                location = json.url;
                            }
                        } catch (e) {

                        }
                        flagClientesOnline = true;
                    },
                    complete: function () {
                        flagClientesOnline = true;
                    }
                });
            }
        }

    function trocarIdioma(lang) {
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_IDIOMA_CHANGE ?>',
            method: 'post',
            dataType: 'html',
            data: {
                lang: lang
            },
            success: function () {
                location.reload();

            }
        });
    }

    function alertaKyc() {
        $("#informativoKyc").hide();
    }

    function modecolor(mode) {
        var expires = new Date();
        expires.setTime(expires.getTime() + (7 * 24 * 60 * 60 * 1000));
        document.cookie = 'Color' + '=' + mode + ';expires=' + expires.toUTCString();
        location.reload();
    }

</script>






