<style type="text/css">
    @media only screen and (max-width: 1100px) {
        .mobile-hide{ display: none !important; }
    }
    @media only screen and (max-width: 1222px){
        .desktop-show-slick{ display: none !important; }
    }
    @media only screen and (min-width: 1221px) {
        .mobile-show-slick{ display: none !important; }
    }
    @media only screen and (max-width: 1100px) {
        .mobile{ display: inline !important; }
    }  

    @media only screen and (max-width: 950px) {
        .desktop-old{ display: inline !important; }
    }
    @media only screen and (min-width: 500px) {
        .desktop-hide{ display: none !important; }
    }
    
    .fileinput-filename{
        overflow: hidden !important;
        max-height: 20px !important;
        width: 70% !important;
    }
    
    .select2-container.select2-container--default.select2-container{
        /*z-index: 1;*/
    }
    
    .select2-close-mask {
        z-index: 2099 !important;
    }
    .select2-dropdown{
        z-index: 3051 !important;
    }
</style>

<?php 
$color = (isset($_COOKIE['Color'])) ? $_COOKIE['Color'] : 'D';
$version = mt_rand(0,9999);
?>


<link href="<?php echo TEMA; ?>font-awesome/css/font-awesome.css" rel="stylesheet">
<link href="<?php echo TEMA; ?>css/lobipanel.css" rel="stylesheet">
<link href="<?php echo TEMA; ?>lib/highlight/github.css" rel="stylesheet">


<link rel="stylesheet" href="<?php echo BOOK; ?>bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" href="<?php echo BOOK; ?>css/icons.css">
<link rel="stylesheet" href="<?php echo BOOK; ?>css/ui.css">
<link rel="stylesheet" href="<?php echo BOOK; ?>css/style.css">



<link href="<?php echo TEMA; ?>css/plugins/toastr/toastr.min.css" rel="stylesheet">
<link href="<?php echo TEMA; ?>css/plugins/dropzone/basic.css" rel="stylesheet">
<link href="<?php echo TEMA; ?>css/plugins/dropzone/dropzone.css" rel="stylesheet">
<link href="<?php echo TEMA; ?>js/plugins/gritter/jquery.gritter.css" rel="stylesheet">
<link href="<?php echo TEMA; ?>css/animate.css" rel="stylesheet">

<link href="<?php echo TEMA; ?>css/plugins/sweetalert/sweetalert.css" rel="stylesheet">
<link href="<?php echo TEMA; ?>css/plugins/datapicker/datepicker3.css" rel="stylesheet">
<link href="<?php echo TEMA; ?>css/plugins/cropper/cropper.min.css" rel="stylesheet">
<link href="<?php echo TEMA; ?>css/plugins/chosen/bootstrap-chosen.css" rel="stylesheet">
<link href="<?php echo TEMA; ?>css/plugins/select2/select2.min.css" rel="stylesheet">
<link href="<?php echo TEMA; ?>css/plugins/codemirror/codemirror.css" rel="stylesheet">
<link href="<?php echo TEMA; ?>css/plugins/codemirror/ambiance.css" rel="stylesheet">
<link href="<?php echo TEMA; ?>css/plugins/jasny/jasny-bootstrap.min.css" rel="stylesheet">
<link href="<?php echo TEMA; ?>css/plugins/codemirror/codemirror.css" rel="stylesheet">
<link href="<?php echo TEMA; ?>css/plugins/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.css" rel="stylesheet">
<link href="<?php echo JS; ?>slick-master/slick/slick.css" rel="stylesheet">
<link href="<?php echo JS; ?>slick-master/slick/slick-theme.css" rel="stylesheet">
<link href="<?php echo TEMA; ?>css/plugins/iCheck/custom.css" rel="stylesheet">
<link href="<?php echo TEMA; ?>css/plugins/codemirror/codemirror.css" rel="stylesheet">
<link href="<?php echo TEMA; ?>css/plugins/codemirror/ambiance.css" rel="stylesheet">
<link href="<?php echo TEMA; ?>css/plugins/jqGrid/ui.jqgrid.css" rel="stylesheet">
<link href="<?php echo TEMA; ?>css/plugins/footable/footable.core<?php echo $color ?>.css?<?php $version;?>" rel="stylesheet">
<link href="<?php echo TEMA; ?>css/plugins/blueimp/css/blueimp-gallery.min.css" rel="stylesheet">
<link href="<?php echo TEMA; ?>css/plugins/slick/slick.css" rel="stylesheet">
<link href="<?php echo TEMA; ?>css/plugins/nouslider/jquery.nouislider.css" rel="stylesheet">
<link href="<?php echo TEMA; ?>css/plugins/slick/slick-theme.css" rel="stylesheet">
<link href="<?php echo TEMA; ?>css/plugins/summernote/summernote.css" rel="stylesheet">
<link href="<?php echo TEMA; ?>css/plugins/summernote/summernote-bs3.css" rel="stylesheet">    
<link href="<?php echo TEMA; ?>css/bootstrap-toggle.min.css" rel="stylesheet">
<link href="<?php echo TEMA; ?>css/datatables.css" rel="stylesheet">
<link href="<?php echo TEMA; ?>css/jAlert/jAlert.css?<?php echo time(); ?>" rel="stylesheet">