<?php
$segmentosComercio = (isset($_data["segmentos"]) ? $_data["segmentos"] : Array());


$moeda = \Modules\principal\Controllers\Principal::getCurrency();
?>


<?php Utils\Layout::append("inspina/metas", $_data) ?>

<?php Utils\Layout::append("inspina/scripts", $_data) ?>


<?php Utils\Layout::append("inspina/menu", $_data) ?>




<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="row wrapper border-bottom page-heading" style="background: linear-gradient(to right, #fff, <?php echo $moeda->mainColor ?>) !important;">
        <div class="col-lg-10">
            <h2>Administrativo de Comércios</h2>
            <ol class="breadcrumb" style="background-color: transparent !important;">
                <li>
                    Administrativo
                </li>
                <li class="active">
                    <strong>Comércios</strong>
                </li>
            </ol>
        </div>
    </div>
</div>

    <!-- Main content -->
<section class="content">
    <br><br>
    
    <div class="row">
        
        <div class="col col-xs-6">
            <div class="form-group">
                <label>Categoria</label>
                <select class="form-control select2" id="segmento" onchange="filtrar();">
                    <option value="<?php echo \Utils\Criptografia::encriptyPostId(0) ?>">De qualquer categoria</option>
                    <?php
                    foreach ($segmentos as $segmento) {
                        ?>
                        <option value="<?php echo \Utils\Criptografia::encriptyPostId($segmento->id) ?>"><?php echo $segmento->nome ?></option>
                        <?php 
                    }
                    ?>
                </select>
            </div>
        </div>
        <div class="col col-xs-6">
            <div class="form-group">
                <label>Filtro</label>
                <input type="text" class="form-control" id="filtro" onkeyup="filtrar();" />
            </div>
        </div>
    </div>
    
    <div class="row">
        <div class="col col-lg-12 text-center">
            <button class="btn btn-default" type="button" onclick="limpar();">
                Limpar Filtros
            </button>
        </div>
    </div>
    
    <br><br>
    
    
    <div class="row">
        <div class="col col-xs-12 table-responsive">
            
            <table class="table table-hover table-bordered table-condensed table-striped">
                <thead>
                    <tr>
                        <th>Comércio</th>
                        <th>Cliente</th>
                        <th>Segmento</th>
                        <th>Detalhes</th>
                        <th>Alterar Status</th>
                    </tr>
                </thead>
                
                <tbody id="lista">
                    
                </tbody>
            </table>
            
        </div>
    </div>
    
</section>
    
<div class="clearfix"></div>

<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>

<script>
    $(document).ready(function () {
        $(".select2").select2();
        
        filtrar();
    });
    
    function limpar() {
        $("#segmento").children("option").first().prop("selected", true);
        $("#filtro").val("");
        $("#segmento").trigger("change");
    }
    
    function filtrar() {
        $("#listar").html("<tr><td class='text-center' colspan='5' ><img src='<?php echo IMAGES ?>loading.gif' /></td></tr>");
        $.ajax({
            url : "<?php echo URLBASE_CLIENT . Utils\Rotas::R_COMERCIOS_ADMINISTRATIVO_LISTAR ?>",
            method: "post",
            dataType: "json",
            data: {
                cliente: $("#cliente").val(),
                segmento: $("#segmento").val(),
                filtro: $("#filtro").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#lista").html(json.html);
                        
                        $(".popover-comercios").each(function () {
                            let controle = $(this).attr("data-controle");
                            let nome = $(this).attr("data-nome");
                            $(this).popover({
                                html: true,
                                trigger: "focus",
                                container: "body",
                                placement: "top",
                                title: "Comércio " + nome,
                                content: json.popover[controle]
                            });
                        });
                        
                    } else {
                        $("#listar").html("<tr><td class='text-center' colspan='5' >"+json.mensagem+"</td></tr>");
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    $("#listar").html("<tr><td class='text-center' colspan='5' >"+e+"</td></tr>");
                    showNotyAlert(e, "e");
                }
            }
        });
        
    }
    
    
    function alterarStatusAtivo(codigo) {
        
        $.ajax({
            url : "<?php echo URLBASE_CLIENT . Utils\Rotas::R_COMERCIOS_ADMINISTRATIVO_STATUS ?>",
            method: "post",
            dataType: "json",
            data: {
                codigo: codigo
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#comercio-"+json.codigo).replaceWith(json.html);
                        
                        $("#popover-comercios-"+json.codigo).each(function () {
                            let controle = $(this).attr("data-controle");
                            let nome = $(this).attr("data-nome");
                            $(this).popover({
                                html: true,
                                trigger: "focus",
                                container: "body",
                                placement: "top",
                                title: "Comércio " + nome,
                                content: json.popover[controle]
                            });
                        });
                        
                    } else {
                        $("#listar").html("<tr><td class='text-center' colspan='5' >"+json.mensagem+"</td></tr>");
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    $("#listar").html("<tr><td class='text-center' colspan='5' >"+e+"</td></tr>");
                    showNotyAlert(e, "e");
                }
            }
        });
        
    }
    
</script>


<?php Utils\Layout::append("mensage_text", $_data) ?>

