<?php
$clientes = isset($_data["clientes"]) ? $_data["clientes"] : Array();
$moeda = \Modules\principal\Controllers\Principal::getCurrency();
$adm = (\Utils\Geral::isUsuario() || \Utils\Geral::getLogado()->tipo == Utils\Constantes::ADMINISTRADOR);
?>
<?php Utils\Layout::append("inspina/metas", $_data) ?>

<?php Utils\Layout::append("inspina/scripts", $_data) ?>


<?php Utils\Layout::append("inspina/menu", $_data) ?>


<div class="content-wrapper">
  <div class="row wrapper border-bottom page-heading" style="background: linear-gradient(to right, #fff, <?php echo $moeda->mainColor ?>) !important;">
    <div class="col-lg-9">
      <ol class="breadcrumb m-t-md" style="background-color: transparent !important;">
          <li>
            Pontos PDV
          </li>
          <li class="active">
              <strong>Estabelecimentos</strong>
          </li>
      </ol>
    </div>
    <div class="col-lg-3">
    <?php Utils\Layout::append("inspina/flags", $_data) ?>
    </div>
  </div>
</div>
    
<div>
<br>   
    
    <!-- Main content -->
    <section class="content">

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <?php Utils\Layout::append("mensagem", $_data)?>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <div class="row">
                            
                            <?php if ($adm) { ?>
                            <div class="col col-lg-4">
                                <div class="form-group">
                                    <label>Cliente</label>
                                    <select class="form-control select2" id="idCliente" onchange="filtrar();">
                                        <option value="0">Todos os clientes</option>
                                        <?php 
                                            foreach ($clientes as $cliente) {
                                                ?>
                                                <option value="<?php echo Utils\Criptografia::encriptyPostId($cliente->id) ?>"><?php echo $cliente->nome ?></option>
                                                <?php
                                            }
                                        ?>
                                    </select>
                                </div>
                            </div>
                            <?php } ?>
                            <div class="col col-lg-<?php echo ($adm ? "4": "6")?>">
                                <div class="form-group">
                                    <label>
                                        <img src="<?php echo IMAGES ?>loader.GIF" style="width: 25px; height: 25px;" id="loaderEstabelecimentos"/>
                                        Estabelecimentos
                                    </label>
                                    <select class="form-control select2" id="idEstabelecimento"  onchange="filtrar();">
                                        
                                    </select>
                                </div>
                            </div>
                            <div class="col col-lg-4">
                                <div class="form-group">
                                    <label>Filtro Geral</label>
                                    <input type="text" id="filtro" class="form-control" onkeyup="filtrar();"/>
                                </div>
                            </div>

                            <div class="col col-lg-2">
                                <label></label>
                                <div class="form-group">
                                    <?php if (\Models\Modules\Acesso\RotinaRn::validar(\Utils\Rotas::R_PONTOSPDVS, \Utils\Constantes::CADASTRAR)) { ?>
                                <a class="btn btn-primary pull-right" href="<?php echo URLBASE_CLIENT . Utils\Rotas::R_PONTOSPDVS_CADASTRO ?>">
                                    <i class="fa fa-plus"></i> Cadastrar
                                </a>
                                <?php } ?>
                                </div>
                            </div>

                        </div>
                        
                        

                        <div class="row">
                            <div class="col col-lg-12" >
                                <ul class="list-group" id="lista">
                                    
                                </ul>
                            </div>
                        </div>
                    </div>
                    <!-- /.panel-body -->

                </div>
            </div>

        </div>

    </section>
    
    <div class="clearfix"></div>
</div>

<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>

<script>
    $(document).ready(function () {
        $("#idEstabelecimento").select2();
        $("#idCliente").select2();
        filtrar();
        
        $("#idCliente").change(function () {
            getEstabelecimentos();
        });
        
        getEstabelecimentos();
    });
    
    function filtrar() {
        $("#lista").html("<div class='col-lg-12 text-center'><img src='<?php echo IMAGES ?>loading.gif' /></div>");
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_PONTOSPDVS_LISTAR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                <?php if ($adm) { ?>
                idCliente: $("#idCliente").val(),
                <?php } ?>
                idEstabelecimento: $("#idEstabelecimento").val(),
                filtro: $("#filtro").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#lista").html(json.html);
                    } else {
                        $("#lista").html("<div class='col-lg-12 text-center'>"+json.mensagem+"</div>");
                    }
                } catch (e) {
                    $("#lista").html("<div class='col-lg-12 text-center'>"+e+"</div>");
                }
            }
        });
    }
    
    function alterarStatusAtivo(codigo) {
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_PONTOSPDVS_ALTERARSTATUS ?>',
            method: 'post',
            dataType: 'json',
            data: {
                id: codigo
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        filtrar();
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
            }
        });
    }
    
    function dialogExcluir(codigo) {
        $("#modalExclusaoCodigo").val(codigo);
        $("#modalExclusao").modal();
    }
    
    function excluir() {
        $("#modalExclusaoClose, #modalExclusaoExcluir").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_PONTOSPDVS_EXCLUIR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                id: $("#modalExclusaoCodigo").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        showNotyAlert(json.mensagem, "s");
                        $("#modalExclusaoClose").prop("disabled", false).trigger("click");
                        filtrar();
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#modalExclusaoClose, #modalExclusaoExcluir").prop("disabled", false);
            }
        });
    }
    
    
    
    function getEstabelecimentos() {
        $("#loaderEstabelecimentos").show();
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_ESTABELECIMENTOS_HTML_ESTABELECIMENTOSPORCLIENTE ?>',
            method: 'post',
            dataType: 'json',
            data: {
                id: $("#idCliente").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#idEstabelecimento").html(json.html);
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#loaderEstabelecimentos").hide();
            }
        });
    }
</script>


<div class="modal fade" id="modalExclusao" tabindex="-1" role="dialog" aria-labelledby="modalExclusao" aria-hidden="true" >
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="modalExclusaoLabel">Excluir Ponto</h4>
            </div>
            <div class="modal-body">
                <input type="hidden" id="modalExclusaoCodigo" />
                <div class="row">
                    <div class="col col-lg-12">
                        Deseja realmente excluir o ponto de PDV?
                    </div>
                </div>
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="modalExclusaoClose" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-danger" onclick="excluir();" id="modalExclusaoExcluir" >Excluir</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>