<?php 

$usuarioLogado = Utils\Geral::getLogado();

$estados = isset($_data["estados"]) ? $_data["estados"] : Array();
$cidades = isset($_data["cidades"]) ? $_data["cidades"] : Array();

$cliente = isset($_data["cliente"]) ? $_data["cliente"] : new Models\Modules\Cadastro\Cliente();

$sucesso = isset($_data["sucesso"]) ? $_data["sucesso"] : true;
$mensagem = isset($_data["mensagem"]) ? $_data["mensagem"] : true;

//exit(print_r($cliente));
?>

<?php Utils\Layout::append("inspina/metas", $_data) ?>

<?php Utils\Layout::append("inspina/scripts", $_data) ?>


<?php Utils\Layout::append("inspina/menu", $_data) ?>


<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Usuários
            <small></small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="<?php echo URLBASE_CLIENT ?>cadastros/clientes"> Clientes</a></li>
            <li class="active">Cadastro Visa</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">

        <?php if ($sucesso) { ?>
        
        <div class="row">
            <div class="col col-sm-12">
                <div class="form-group">
                    <label>Nome completo*</label>
                    <input type="text" class="form-control" id="nome" maxlength="200" value="<?php echo $cliente->nome ?>" />
                </div>
            </div>

        </div>

        <div class="row">
            <div class="col col-sm-6">
                <div class="form-group">
                    <label>Email*</label>
                    <input type="email" class="form-control" id="email" maxlength="200" value="<?php echo $cliente->email ?>"/>
                </div>
            </div>
            <div class="col col-sm-3">
                <div class="form-group">
                    <label>Celular*</label>
                    <input type="text" class="form-control" id="celular" maxlength="16" value="<?php echo $cliente->celular ?>" />
                </div>
            </div>
            <div class="col col-sm-3">
                <div class="form-group">
                    <label>Data de Nascimento*</label>
                    <input type="text" class="form-control" id="dataNascimento" maxlength="16" value="<?php echo ($cliente->dataNascimento != null ? $cliente->dataNascimento->formatar(\Utils\Data::FORMATO_PT_BR) : "") ?>" />
                </div>
            </div>
        </div>

        
        <div class="row">
            <div class="col col-sm-5">
                <div class="form-group">
                    <label>Nome do Pai*</label>
                    <input type="text" class="form-control" id="nomePai"  maxlength="80"  value="<?php echo $cliente->nomePai ?>" />
                </div>
            </div>
            <div class="col col-sm-5">
                <div class="form-group">
                    <label>Nome da Mãe*</label>
                    <input type="text" class="form-control" id="nomeMae"  maxlength="80" value="<?php echo $cliente->nomeMae ?>"  />
                </div>
            </div>
            <div class="col col-sm-2">
                <div class="form-group">
                    <label>Sexo*</label>
                    <select id="sexo" class="form-control" >
                        <option value="M" <?php echo ($cliente->sexo == "M" ? "selected='selected'" : "") ?> >Masculino</option>
                        <option value="F" <?php echo ($cliente->sexo == "F" ? "selected='selected'" : "") ?> >Feminino</option>
                    </select>
                </div>
            </div>
        </div>


        <div class="row">
            <div class="col col-sm-6">
                <div class="form-group">
                    <label>RG*</label>
                    <input type="text" class="form-control" id="rg" maxlength="27"  value="<?php echo $cliente->rg ?>" />
                </div>
            </div>
            <div class="col col-sm-6">
                <div class="form-group">
                    <label>CPF*</label>
                    <input type="text" class="form-control" id="documento" maxlength="14"  value="<?php echo $cliente->documento ?>"  />
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col col-sm-12">
                <div class="form-group">
                    <label>Endereço*</label>
                    <input type="text" class="form-control" id="endereco" maxlength="200"  value="<?php echo $cliente->endereco ?>"  />
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col col-sm-4">
                <div class="form-group">
                    <label>Num. End*</label>
                    <input type="text" class="form-control" id="numero" maxlength="20" value="<?php echo $cliente->numero ?>"  />
                </div>
            </div>
            <div class="col col-sm-8">
                <div class="form-group">
                    <label>Complemento</label>
                    <input type="text" class="form-control" id="complemento" maxlength="80"  value="<?php echo $cliente->complemento ?>" />
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col col-sm-4">
                <div class="form-group">
                    <label>CEP*</label>
                    <input type="text" class="form-control" id="cep"  value="<?php echo $cliente->cep ?>"  />
                </div>
            </div>
            <div class="col col-sm-8">
                <div class="form-group">
                    <label>Bairro*</label>
                    <input type="text" class="form-control" id="bairro" maxlength="80"  value="<?php echo $cliente->bairro ?>" />
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col col-sm-4">
                <div class="form-group">
                    <label>Estado*</label>
                    <select class="form-control" id="estado">
                        <?php
                        foreach ($estados as $estado) {
                            ?>
                            <option value="<?php echo $estado->sigla ?>" <?php echo ($cliente->estado == $estado->sigla ? "selected='selected'" : "") ?> ><?php echo $estado->sigla ?></option>
                            <?php
                        }
                        ?>
                    </select>
                </div>
            </div>
            <div class="col col-sm-8">
                <div class="form-group">
                    <label>
                        <img src="<?php echo IMAGES ?>loading.gif"  style="height: 15px; width: 15px; display: none;" id="loading-cidades"/>
                        Cidade*
                    </label>
                    <select class="form-control" id="cidade">
                        <?php
                        foreach ($cidades as $cidade) {
                            ?>
                        <option value="<?php echo $cidade->nome ?>" <?php echo (trim($cliente->cidade) == $cidade->nome ? "selected='selected'" : "") ?> ><?php echo $cidade->nome ?></option>
                            <?php
                        }
                        ?>
                    </select>
                </div>
            </div>
        </div>

        <?php } ?>
        
        <div class="row">
            <div class="col col-xs-12 error-container-msg">
                <?php if (!$sucesso) { 
                    echo $mensagem;
                } ?>
            </div>
        </div>

        
        <?php if ($sucesso) { ?>
        <div class="row">
            <div class="col-sm-12 text-center">
                <br><br>
                <a type="button" class="btn btn-default" id="cancelar" href="<?php echo URLBASE_CLIENT ?>cadastros/clientes">
                    Cancelar
                </a>
                <button type="button" class="btn btn-primary" id="enviar" onclick="salvarCadastroVisa();">
                    Enviar
                </button>
                <br><br>
            </div>
        </div>
        <?php } ?>
        
    </section>
    
    <div class="clearfix"></div>
</div>

<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>

<script>
    $(document).ready(function () {
        $("#celular").inputmask({
            mask: ["(99) 9999-9999", "(99) 99999-9999"],
            keepStatic: true
        });
        $("#dataNascimento").datepicker().mask("99/99/9999");
        $("#documento").mask("999.999.999-99");
        $("#cep").mask("99999-999");
        
    });
    
    function salvarCadastroVisa() {
        $("#cancelar, #enviar").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT ?>cadastros/clientes/enviarCadastroVisa',
            method: 'post',
            dataType: 'json',
            data: {
                id: <?php echo $cliente->id ?>,
                nome: $("#nome").val(),
                email: $("#email").val(),
                celular: $("#celular").val(),
                dataNascimento: $("#dataNascimento").val(),
                nomePai: $("#nomePai").val(),
                nomeMae: $("#nomeMae").val(),
                sexo: $("#sexo").val(),
                rg: $("#rg").val(),
                documento: $("#documento").val(),
                endereco: $("#endereco").val(),
                numero: $("#numero").val(),
                complemento: $("#complemento").val(),
                cep: $("#cep").val(),
                bairro: $("#bairro").val(),
                estado: $("#estado").val(),
                cidade: $("#cidade").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#cancelar").prop("disabled", false);
                        $("#cancelar").trigger("click");
                        listarUsuarios();
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                
                $("#cancelar, #enviar").prop("disabled", false);
            }
        });
    }
    
</script>

    </section>
      </div>
    </section>
  </div>
<?php Utils\Layout::append("inspina/footer_esp", $_data)?>
</body>
</html>
