<?php 

$usuarioLogado = Utils\Geral::getLogado();
$arvore = (isset($_data["arvore"]) ? $_data["arvore"] : Array());

?>

<?php Utils\Layout::append("inspina/metas", $_data) ?>

<?php Utils\Layout::append("inspina/scripts", $_data) ?>


<?php Utils\Layout::append("inspina/menu", $_data) ?>



  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
            <div class="row wrapper border-bottom white-bg page-heading">
                <div class="col-lg-10">
                    <h2>Usuários</h2>
                    <ol class="breadcrumb">
                        <li>
                            Cadastros
                        </li>
                        <li class="active">
                            <strong>Usuários</strong>
                        </li>
                    </ol>
                </div>
            </div>
</div>  
<br>    
    <!-- Main content -->
    <section class="content">

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <?php Utils\Layout::append("mensagem", $_data)?>
                    <div class="panel-heading">
                        Listagem de Usuários 

                        
                    </div>
                    <!-- /.panel-heading -->
                    
                    
                    <div class="panel-body">
                        


                        <div class="row">
                            <div class="col col-xs-10">
                                <input id="filtro" type="text" class="form-control" onkeyup="listarUsuarios();"> 
                            </div>
                            <div class="col col-xs-2">
                            <?php if (Models\Modules\Acesso\RotinaRn::validar("usuarios", \Utils\Constantes::CADASTRAR)) { ?>
                                <button type="button" class="btn btn-primary pull-right" onclick="cadastroUsuario(0);">
                                    Novo Usuário
                                </button>
                            <?php } ?>
                            </div>
                        </div>


                        <br>
                        <ul class="list-group">
                            <li class="list-group-item bg-blue">
                                <div class="row">
                                    <div class="col col-xs-4">
                                        Usuários: <span id="usuariosTotal"></span>
                                    </div>
                                    <div class="col col-xs-4">
                                        Ativos: <span id="usuariosAtivos"></span>
                                    </div>
                                    <div class="col col-xs-4">
                                        Inativos: <span id="usuariosInativos"></span>
                                    </div>
                                </div>
                            </li>
                        </ul>
                        
                        <ul class="list-group" id="listaUsuarios">
                            
                        </ul>
                    </div>
                    <!-- /.panel-body -->

                </div>
            </div>

        </div>

        <div id="confirmarExclusao" title="Excluir registro" style="display: none;">
            <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>
                O item e seus dependentes serão removidos. Deseja continuar?</p>
        </div>


    </section>
    
    <div class="clearfix"></div>
</div>

<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>

<script>
    $(document).ready(function () {
        $("#cadastroUsuarioDataExpiracao").datepicker().mask("99/99/9999");
        $("#cadastroUsuarioCpf").mask("99999999999");
        
        $(".permissao-modulo").change(function () {
            let cod = $(this).val();
            $(".mod-"+cod).prop("checked", $(this).is(":checked"));
        });
        
        $("#checkUncheckAll").change(function () {
            $(".permissao-modulo, .permissao-rotina").prop("checked", $(this).is(":checked"));
        });
        
        listarUsuarios();
    });
    
    function listarUsuarios() {
        $("#listaUsuarios").html("<div class='col-lg-12 text-center'><img src='<?php echo IMAGES ?>loading.gif' /></div>");
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_CADASTRO_USUARIO_LISTAR ?>',
            method: 'post',
            dataType: 'json',
            data: {f: $("#filtro").val()},
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#listaUsuarios").html(json.html);
                        $("#usuariosTotal").html(json.total);
                        $("#usuariosAtivos").html(json.ativos);
                        $("#usuariosInativos").html(json.inativos);
                    } else {
                        $("#listaUsuarios").html("<div class='col-lg-12 text-center'>"+json.mensagem+"</div>");
                        $("#usuariosTotal").html("0");
                        $("#usuariosAtivos").html("0");
                        $("#usuariosInativos").html("0");
                    }
                } catch (e) {
                    $("#listaUsuarios").html("<div class='col-lg-12 text-center'>"+e+"</div>");
                        $("#usuariosTotal").html("0");
                        $("#usuariosAtivos").html("0");
                        $("#usuariosInativos").html("0");
                }
            }
        });
    }
    
    function cadastroUsuario(idUsuario) {
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_CADASTRO_USUARIO_CADASTRO ?>',
            method: 'post',
            dataType: 'json',
            data: {
                idUsuario: idUsuario
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        
                        $("#cadastroUsuarioId").val(json.usuario.id);
                        $("#cadastroUsuarioNome").val(json.usuario.nome);
                        $("#cadastroUsuarioMatricula").val(json.usuario.matricula);
                        $("#cadastroUsuarioEmail").val(json.usuario.email);
                        $("#cadastroUsuarioCidade").val(json.usuario.cidade);
                        $("#cadastroUsuarioCelular").val(json.usuario.celular);
                        $("#cadastroUsuarioAnotacoes").val(json.usuario.anotacoes);
                        $("#cadastroUsuarioCpf").val(json.usuario.cpf);
                        $("#cadastroUsuarioDataExpiracao").val(json.usuario.dataExpiracao);
                        
                        $("#statusEnviarNotificacao").prop("checked", json.usuario.statusEnviarNotificacao > 0);
                        
                        $("#cadastroUsuarioTipoUsuarioVendedor").prop("checked", (json.usuario.tipo === "<?php echo Utils\Constantes::VENDEDOR?>"));
                        $("#cadastroUsuarioTipoUsuarioAdministrador").prop("checked", (json.usuario.tipo === "<?php echo Utils\Constantes::ADMINISTRADOR?>"));                  
                        $("#cadastroUsuarioSenha").val("");
                        $("#cadastroUsuarioConfirmacao").val("");
                        
                        $(".permissao-rotina").prop("checked", false);
                        if (typeof json.permissoesRotinas !== "undefined") {
                            let i = 0;
                            for(i = 0; i < json.permissoesRotinas.length; i++) {
                                $("#per-"+json.permissoesRotinas[i]).prop("checked", true);
                            }
                        }
                        
                        $(".permissao-modulo").prop("checked", false);
                        if (typeof json.permissoesModulos !== "undefined") {
                            let i = 0;
                            for(i = 0; i < json.permissoesModulos.length; i++) {
                                $("#mod-"+json.permissoesModulos[i]).prop("checked", true);
                            }
                        }
                        
                        if(json.usuario.tipoAutenticacao === '<?php echo \Utils\Constantes::TIPO_AUTH_SMS?>') {
                            $("#cadastroUsuarioTipoAuthSms").prop("checked", true);
                            $("#cadastroUsuarioTipoAuthEmail").prop("checked", false);
                        } else {
                            $("#cadastroUsuarioTipoAuthSms").prop("checked", false);
                            $("#cadastroUsuarioTipoAuthEmail").prop("checked", true);
                        }
                        
                        if (json.salvar) {
                            $("#cadastroUsuarioSalvar").show();
                        } else {
                            $("#cadastroUsuarioSalvar").hide();
                        }
                        
                        $("#cadastroUsuario").modal();
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
            }
        });
    }
    
    function salvarUsuario() {
        let permissoesRotina = [];
        let permissoesModulo = [];
        
        $(".permissao-rotina").each(function () {
            if ($(this).is(":checked")) {
                permissoesRotina.push($(this).val());
            }
        });
        
        $(".permissao-modulo").each(function () {
            if ($(this).is(":checked")) {
                permissoesModulo.push($(this).val());
            }
        });
    
        $("#cadastroUsuarioFechar, #cadastroUsuarioSalvar").prop("disabled", true);
        
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_CADASTRO_USUARIO_SALVAR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                idUsuario: $("#cadastroUsuarioId").val(),
                nome: $("#cadastroUsuarioNome").val(),
                matricula: $("#cadastroUsuarioMatricula").val(),
                email: $("#cadastroUsuarioEmail").val(),
                senha: $("#cadastroUsuarioSenha").val(),
                confirmacao: $("#cadastroUsuarioConfirmacao").val(),
                cidade: $("#cadastroUsuarioCidade").val(),
                celular: $("#cadastroUsuarioCelular").val(),
                anotacoes: $("#cadastroUsuarioAnotacoes").val(),
                dataExpiracao: $("#cadastroUsuarioDataExpiracao").val(),
                cpf: $("#cadastroUsuarioCpf").val(),
                statusEnviarNotificacao: $("#statusEnviarNotificacao").is(":checked"),
                permissoesRotina: permissoesRotina,
                permissoesModulo: permissoesModulo,
                tipoAutenticacao: $("input:radio[name='cadastroUsuarioTipoAuth']:checked").val()
                
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#cadastroUsuarioFechar").prop("disabled", false);
                        $("#cadastroUsuarioFechar").trigger("click");
                        listarUsuarios();
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                
                $("#cadastroUsuarioFechar, #cadastroUsuarioSalvar").prop("disabled", false);
            }
        });
    }
    
    function deletarUsuario(id) {
        if (id > 0) {
            dialogConfirmar = $( "#confirmarExclusao" ).dialog({
                resizable: false,
                height:200,
                modal: true,
                buttons: {
                  "Cancelar": function() {
                    $( this ).dialog( "close" );
                  },
                  "Confirmar": function() {
                        $.ajax({
                            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_CADASTRO_USUARIO_EXCLUIR ?>',
                            method: 'post',
                            dataType: 'json',
                            data: {
                                idUsuario: id
                            },
                            success: function(json) {
                                try {
                                    if (json.sucesso) {
                                        $("#usuario-"+id).remove();
                                        $( dialogConfirmar ).dialog( "close" );
                                    }
                                    showNotyAlert(json.mensagem, "e");
                                } catch (e) {
                                    showNotyAlert(e, "e");
                                }
                            }
                        });
                    }
                }
            });

        }
    }
    function alterarStatusUsuario(id) {
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_CADASTRO_USUARIO_ATIVO ?>',
            method: 'post',
            dataType: 'json',
            data: {
                idUsuario: id
            },
            success: function(json) {
                try {
                    if (json.sucesso) {
                        $("#usuario-"+id).replaceWith(json.html);
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
            }
        });
    }
</script>


<div class="modal fade" id="cadastroUsuario" tabindex="-1" role="dialog" aria-labelledby="cadastroUsuario" aria-hidden="true" >
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="cadastroUsuarioLabel"></h4>
            </div>
            <div class="modal-body">
                <input type="hidden" class="form-control" id="cadastroUsuarioId" />
                
                <div class="tabs-container">
                    <ul class="nav nav-tabs">
                        <li class="active"><a data-toggle="tab" href="#tab-1">Dados</a></li>
                        <?php //if (\Models\Modules\Acesso\RotinaRn::validar(\Utils\Rotas::R_LISTAUSUARIOS, \Utils\Constantes::PERMISSOES)) { ?>
                        <li class=""><a data-toggle="tab" href="#tab-2">Permissões</a></li>
                        <?php //} ?>
                        <li class=""><a data-toggle="tab" href="#tab-4">Outras Permissões</a></li>
                        <li class=""><a data-toggle="tab" href="#tab-3">Anotações</a></li>
                    </ul>
                    <div class="tab-content">
                        <div id="tab-1" class="tab-pane active">
                            <div class="panel-body">
                                <div class="row">
                                    <div class="col col-lg-6">
                                        <div class="form-group">
                                            <label class="control-label">Nome</label>
                                            <input type="text" class="form-control" id="cadastroUsuarioNome" />
                                        </div>
                                    </div>
                                    <div class="col col-lg-6">
                                        <div class="form-group">
                                            <label class="control-label">Email</label>
                                            <input type="email" class="form-control" id="cadastroUsuarioEmail" />
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col col-lg-4">
                                        <div class="form-group">
                                            <label class="control-label">CPF</label>
                                            <input type="text" class="form-control" id="cadastroUsuarioCpf" />
                                        </div>
                                    </div>
                                    <div class="col col-lg-4">
                                        <div class="form-group">
                                            <label class="control-label">Senha</label>
                                            <input type="password" class="form-control" id="cadastroUsuarioSenha" />
                                        </div>
                                    </div>
                                    <div class="col col-lg-4">
                                        <div class="form-group">
                                            <label class="control-label">Confirmacao de Senha</label>
                                            <input type="password" class="form-control" id="cadastroUsuarioConfirmacao" />
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="row">
                                    <div class="col col-lg-12">
                                        <div class="form-group">
                                            <label>Tipo de autenticação</label>
                                            <div class="radio-inline">
                                                <label>
                                                    <input type="radio" name="cadastroUsuarioTipoAuth" id="cadastroUsuarioTipoAuthEmail" value="email" checked="">Email
                                                </label>
                                            </div>
                                            <div class="radio-inline">
                                                <label>
                                                    <input type="radio" name="cadastroUsuarioTipoAuth" id="cadastroUsuarioTipoAuthSms" value="sms">SMS
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="row">

                                    <div class="col col-lg-6">
                                        <div class="form-group">
                                            <label class="control-label">Matricula</label>
                                            <input type="text" class="form-control" id="cadastroUsuarioMatricula" maxlength="20"  />
                                        </div>
                                    </div>

                                    <div class="col col-lg-6">
                                        <div class="form-group">
                                            <label class="control-label">Celular</label>
                                            <input type="text" class="form-control" id="cadastroUsuarioCelular"  maxlength="16" />
                                        </div>
                                    </div>

                                </div>
                                
                            </div>
                            
                            
                            
                        </div>
                        
                        
                        <?php //if (\Models\Modules\Acesso\RotinaRn::validar(\Utils\Rotas::R_LISTAUSUARIOS, \Utils\Constantes::PERMISSOES)) { ?>
                        
                        <div id="tab-2" class="tab-pane">
                            <div class="panel-body">
                                
                                <div class="row">
                                    <div class="col col-lg-12 text-righ">
                                        <div class="checkbox pull-right">
                                            <input type="checkbox" id="checkUncheckAll"> 
                                            <label for="checkUncheckAll">
                                                Marcar / Desmarcar todos
                                            </label>
                                        </div>
                                    </div>
                                </div>
                                
                                <ul class="list-group" style="height: 400px; overflow-y: scroll;">
                                <?php 
                                if (sizeof($arvore)  >0) { 
                                    foreach ($arvore as $dadosModulo) {
                                        $modulo = $dadosModulo["modulo"];
                                        $rotinas = $dadosModulo["rotinas"];
                                        $outrosNiveis = $dadosModulo["modulos"];
                                        $acoes = $dadosModulo["acoes"];
                                ?>
                                    <li class="list-group-item">
                                        <div class="alert alert-info">
                                            <div class="row">
                                                <div class="col col-md-6">
                                                    <strong style="font-size: 15px;"><?php echo $modulo->nome ?></strong>
                                                </div>
                                                <div class="col col-md-6">
                                                <?php 
                                                foreach ($acoes as $moduloHasAcao) {
                                                    ?>
                                                    <div class="checkbox">
                                                        <input type="checkbox" id="mod-<?php echo $moduloHasAcao->id ?>" class="permissao-modulo" value="<?php echo $moduloHasAcao->id ?>"> 
                                                        <label for="mod-<?php echo $moduloHasAcao->id ?>">
                                                            <?php echo $moduloHasAcao->acao->nome ?> - <?php echo $moduloHasAcao->acao->descricao ?>
                                                        </label>
                                                    </div>
                                                    <?php
                                                }
                                                ?>
                                                </div>
                                            </div>
                                        </div>
                                        
                                        <ul class="list-group">
                                            <?php
                                            foreach ($rotinas as $dadosRotinas) {
                                                $rotina = $dadosRotinas["rotina"];
                                                $acoes = $dadosRotinas["acoes"];
                                                ?>
                                            <li class="list-group-item padd-horizontal-15">
                                                <span class="label label-success"> 
                                                    <?php echo $rotina->nome ?>
                                                </span>
                                                
                                                    <?php 
                                                    foreach ($acoes as $rotinaHasAcao) {
                                                        ?>
                                                        <div class="checkbox">
                                                            <input type="checkbox" id="per-<?php echo $rotinaHasAcao->id ?>" class="permissao-rotina mod-<?php echo $moduloHasAcao->id ?>" value="<?php echo $rotinaHasAcao->id ?>"> 
                                                            <label for="per-<?php echo $rotinaHasAcao->id ?>">
                                                                <?php echo $rotinaHasAcao->acao->nome ?> - <?php echo $rotinaHasAcao->acao->descricao ?>
                                                            </label>
                                                        </div>
                                                        <?php
                                                    }
                                                    ?>
                                                
                                            </li>
                                                <?php
                                            }
                                            ?>
                                            
                                            
                                            <?php
                                            if (sizeof($outrosNiveis) > 0) {
                                                foreach ($outrosNiveis as $dadosSubModulo) {
                                                    $subModulo = $dadosSubModulo["modulo"];
                                                    $subAcoes = $dadosSubModulo["acoes"];
                                                    $subRotinas = $dadosSubModulo["rotinas"];
                                                ?>
                                                <li class="list-group-item padd-horizontal-15">
                                                    <div class="alert alert-info">
                                                        <strong style="font-size: 15px;"><?php echo $subModulo->nome ?></strong>

                                                        <?php 
                                                        foreach ($subAcoes as $subModuloHasAcao) {
                                                            ?>
                                                            <div class="checkbox pull-right">
                                                                <input type="checkbox" id="mod-<?php echo $subModuloHasAcao->id ?>" class="permissao-modulo" value="<?php echo $subModuloHasAcao->id ?>"> 
                                                                <label for="mod-<?php echo $subModuloHasAcao->id ?>">
                                                                    <?php echo $subModuloHasAcao->acao->nome ?> - <?php echo $subModuloHasAcao->acao->descricao ?>
                                                                </label>
                                                            </div>
                                                            <?php
                                                        }
                                                        ?>
                                                    </div>

                                                    <?php if (sizeof($subRotinas) > 0) { ?>
                                                    <ul class="list-group padd-horizontal-15">
                                                        
                                                        <?php
                                                            foreach ($subRotinas as $dadosSubRotinas) {
                                                                $subRotina = $dadosSubRotinas["rotina"];
                                                                $acoes = $dadosSubRotinas["acoes"];
                                                                ?>
                                                            <li class="list-group-item padd-horizontal-15">
                                                                <span class="label label-success"> 
                                                                    <?php echo $subRotina->nome ?>
                                                                </span>

                                                                    <?php 
                                                                    foreach ($acoes as $rotinaHasAcao) {
                                                                        ?>
                                                                        <div class="checkbox">
                                                                            <input type="checkbox" id="per-<?php echo $rotinaHasAcao->id ?>" class="permissao-rotina mod-<?php echo $subModuloHasAcao->id ?>" value="<?php echo $rotinaHasAcao->id ?>"> 
                                                                            <label for="per-<?php echo $rotinaHasAcao->id ?>">
                                                                                <?php echo $rotinaHasAcao->acao->nome ?> - <?php echo $rotinaHasAcao->acao->descricao ?>
                                                                            </label>
                                                                        </div>
                                                                        <?php
                                                                    }
                                                                    ?>

                                                            </li>
                                                            <?php
                                                        }
                                                        ?>
                                                        
                                                    </ul>
                                                    <?php } ?>
                                                </li>
                                                <?php
                                                }
                                            }
                                            ?>
                                            
                                        </ul>
                                        
                                    </li>
                                <?php
                                    }
                                } 
                                ?>
                                </ul>
                            </div>
                        </div>
                        <?php //} ?>
                        
                        <div id="tab-3" class="tab-pane">
                            <div class="panel-body">
                                <div class="row">
                                    <div class="col col-lg-12">
                                        <div class="form-group">
                                            <label class="control-label">Anotações</label>
                                            <textarea class="form-control" id="cadastroUsuarioAnotacoes" style="height: 400px;"></textarea>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        
                        <div id="tab-4" class="tab-pane">
                            <div class="panel-body">
                                <div class="row">
                                    <div class="col col-lg-6">
                                        <div class="checkbox">
                                            <input type="checkbox" id="statusEnviarNotificacao" class="statusEnviarNotificacao" value="1"> 
                                            <label for="statusEnviarNotificacao">
                                                Permitir que o usuário envie Notificações a clientes e outros usuários.
                                            </label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>


                </div>
                
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="cadastroUsuarioFechar" data-dismiss="modal">Fechar</button>
                <?php if (Models\Modules\Acesso\RotinaRn::validar("usuarios", \Utils\Constantes::EDITAR)) { ?>
                <button type="button" class="btn btn-primary" onclick="salvarUsuario();" id="cadastroUsuarioSalvar" >Salvar</button>
                <?php } ?>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

    </section>
      </div>
    </section>
  </div>
<?php Utils\Layout::append("inspina/footer_esp", $_data)?>
</body>
</html>
