<?php
$cliente = isset($_data["cliente"]) ? $_data["cliente"] : new \Models\Modules\Cadastro\Cliente();
$ref = isset($_data["ref"]) ? $_data["ref"] : null;

$sucesso =  isset($_data["sucesso"]) ? $_data["sucesso"] : false;
$mensagems =  isset($_data["mensagem"]) ? $_data["mensagem"] : "";
?>


<?php Utils\Layout::append("inspina/metas", $_data) ?>

<?php Utils\Layout::append("inspina/scripts", $_data) ?>


<?php Utils\Layout::append("inspina/menu", $_data) ?>


<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Lista de Pedidos do Cliente
            <small></small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Clientes</a></li>
            <li class="active">Pedidos</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">

        <?php if ($sucesso) { ?>
            
            <div class="row">
                <div class="col col-lg-12">
                    <div class="show-grid">
                        <div class="col-lg-12">
                            <div class="col col-lg-6">
                                Cliente: <?php echo $cliente->nome ?>
                            </div>
                            <div class="col col-lg-6">
                                Email: <?php echo $cliente->email ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="row">
                <div class="col col-lg-12" id="pedidosCartoes">
                    
                </div>
            </div>
            
        <?php } else { ?>
            <div class="row">
                <div class="col col-lg-12">
                    <div class="alert alert-danger">
                        Erro: <?php echo $mensagem ?>
                    </div>
                </div>
            </div>
        <?php } ?>
    </section>
    
    <div class="clearfix"></div>
</div>

<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>

    
<script>

    $(document).ready(function () {
        listarPedidosCartoes();


    });

    function listarPedidosCartoes() {
        $("#pedidosCartoes").html("<div class='col col-lg-12 text-center'><img src='<?php echo IMAGES ?>loading.gif' /></div>");
        $.ajax({
            url: '<?php echo URLBASE_CLIENT ?>principal/dashboard/listarInvoicesCliente',
            method: 'post',
            dataType: 'json',
            data: {
                idCliente: <?php echo $cliente->id?>
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#pedidosCartoes").html(json.html);
                    } else {
                        $("#pedidosCartoes").html("<div class='col col-lg-12 text-center'>"+json.mensagem+"</div>");
                    }
                } catch (e) {
                    $("#pedidosCartoes").html("<div class='col col-lg-12 text-center'>"+e+"</div>");
                }
            }
        });

    }

</script>


<div class="modal fade" id="confirmarPagamento" tabindex="-1" role="dialog" aria-labelledby="confirmarPagamento" aria-hidden="true" >
    <div class="modal-dialog" style="width: 800px;">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="confirmarPagamentoLabel"></h4>
            </div>
            <div class="modal-body">
                <input type="hidden" class="form-control" id="confirmarPagamentoIdCliente" />
                <div class="row">
                    <div class="col col-lg-12">
                        Tem certeza que deseja assinalar como paga a comissão referente ao cliente selecionado?
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="confirmarPagamentoFechar" data-dismiss="modal">Não</button>
                <button type="button" class="btn btn-primary" onclick="confirmarPagamento();" id="confirmarPagamentoSalvar" >Sim</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>