<?php  
$selectMoeda = (isset($_POST['moeda'])) ? $_POST['moeda'] : '';

$atarCliente = (isset($_data["atarCliente"]) ? $_data["atarCliente"]: null);

if($atarCliente == null){
    $hasAtar = false;
} else {
    $hasAtar = true;
}

$boletoAtivo = (isset($_data["boletoAtivo"]) ? $_data["boletoAtivo"]: false);

$selectCategoria = (isset($_POST['categoria'])) ? $_POST['categoria'] : '';

$contasBancarias = isset($_data["contas"]) ? $_data["contas"] : Array();
$configuracao = isset($_data["configuracao"]) ? $_data["configuracao"] : new \Models\Modules\Cadastro\Configuracao();

$valorMinimo = "R$ " . number_format($configuracao->valorMinimoDepositoReais, 2, ",", ".");

$idioma = new \Utils\PropertiesUtils("index_carteiras", IDIOMA);
$_data["idiomaMenu"] = $idioma;
$cliente = Utils\Geral::getCliente();
$mostrarBotaoDeposito = (Models\Modules\Acesso\ModuloRn::validar(Utils\Rotas::M_DEPOSITOS, \Utils\Constantes::CADASTRAR)  ? (Utils\Geral::isCliente() && ($cliente->statusDepositoBrl > 0)) : false);
$mostrarAbaDepositoReais = isset($_data["verificado"]) ? $_data["verificado"] : false;
$moeda = \Modules\principal\Controllers\Principal::getCurrency();
#Caique 26/07/2019 feature/t-33-info-mov-broker
$paridade = Modules\principal\Controllers\Principal::getParity();

$paridades = (isset($_data["paridades"]) ? $_data["paridades"]: Array() );

$casasDecimais = (isset($_data["casasDecimais"]) ? $_data["casasDecimais"]  : 2);
$dataInicial = new \Utils\Data(date("d/m/Y H:i:s"));
$dataInicial->subtrair(0, 1, 0);
$dataFinal = new \Utils\Data(date("d/m/Y H:i:s"));

$taxaCompra = (isset($_data["compra"]) ? $_data["compra"] : 0);
$taxaVenda = (isset($_data["venda"]) ? $_data["venda"] : 0);

$mostrarBotoes = ($paridade->ativo > 0 && $paridade->statusMercado > 0 && $cliente->statusMercado > 0 && $paridade->moedaBook->statusMercado > 0 && $paridade->moedaBook->ativo > 0);
$mostrarAlerta = false;
$mensagemAlerta = "";


if ($paridade->ativo < 1 || $paridade->moedaBook->ativo < 1) {
    $mostrarAlerta = true;
    $mensagemAlerta = $idioma->getText("mercadoEncerrado");
} else if ($paridade->statusMercado < 1 || $paridade->moedaBook->statusMercado < 1) {
    $mostrarAlerta = true;
    $mensagemAlerta = $idioma->getText("mercadoSupenso");
} else if ($cliente->statusMercado < 1) {
    $mensagemAlerta = $idioma->getText("compraVendaSuspensaConta");
    $mostrarAlerta = true;
}
# End Caique 26/07/2019 feature/t-33-info-mov-broker


?>
<style>
    .border-edit {
        border: 1px solid #1c84c6 !important;
    }
   .carregando {
   background: url("<?php echo IMAGES ?>loading.gif") center no-repeat;
    width: 200px;
    height: 200px;
    position: absolute;
    top: 30%;
    left: 45%;
    color: blue;
   }
   
   tr.strikeout td:before {
  content: " ";
  position: absolute;
  top: 50%;
  left: 0;
  border-bottom: 1px solid #111;
  width: 100%;
}

/* Caique 29/07/2019 */
    .table-new {
    width: 100%;
    max-width: 110%;
    margin-bottom: 20px;
    }

   
    /* end */

</style>
<?php Utils\Layout::append("inspina/metas", $_data) ?>
<?php Utils\Layout::append("inspina/scripts", $_data) ?>
<?php Utils\Layout::append("inspina/menu", $_data) ?>
<link href="<?php echo TEMA; ?>css/plugins/switchery/switchery.css" rel="stylesheet">
            <div class="carregando">
            </div>
<div class="wrapper wrapper-content mostrar">
   
        <div class="row">
            <div class="col-lg-2">
                <div class="ibox float-e-margins">
                    <div class="mailbox-content">
                        <div class="file-manager mostrar" id="lista">
                            
                            <div class="clearfix"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-10 animated fadeInLeft m-t-sm">
                <?php if($configuracao->statusDepositoBrl > 0 && $mostrarAbaDepositoReais) {?>
                <div class="" id="depositoReais" hidden="true">                   
                    <div class="row">
                            <div class="col-lg-7">     <!--Formulario deposito em Reais -->     
                                <h2 style="display: inline;"><?php echo $idioma->getText("depositoEmReais") ?></h2>&nbsp;&nbsp;<img src="" id="imagemBanco" height="30" width="30" style="margin-bottom: 10px;"/>
                                <div id="depositoBrl">
                                    <div class="">
                                        <ul class="list-group">
                                            <li class="list-group-item"><b><?php echo $idioma->getText("titular") ?> </b><span id="titular"></span></li>
                                            <li class="list-group-item"><b><?php echo $idioma->getText("cnpj") ?> </b><span id="cnpj"></span></li>
                                            <li class="list-group-item"><b><?php echo $idioma->getText("banco") ?> </b><span id="banco"></span></li>
                                            <li class="list-group-item">
                                                <div class="row">
                                                    <div class="col-lg-4"><b><?php echo $idioma->getText("tipo") ?> </b><span id="contaTipo"></span></div>
                                                    <div class="col-lg-4"><b><?php echo $idioma->getText("agencia") ?> </b><span id="agencia"></span></div>                                        
                                                    <div class="col-lg-4"><b><?php echo $idioma->getText("conta") ?> </b><span id="conta"></span></div>
                                                </div>
                                            </li>                                    
                                        </ul>
                                    </div>    
                                    
                                    <form action="<?php echo URLBASE_CLIENT . Utils\Rotas::R_REAIS_DEPOSITOS_SALVAR ?>" method="post" enctype="multipart/form-data" id="form-deposito" >
                                        <input type="hidden" value="<?php echo $deposito->id ?>" name="id" />
                                        <input type="hidden" value="" id="idContaBancariaEmpresa" name="idContaBancariaEmpresa"/>
                                        <div class="row">
                                            <div class="col col-lg-12">
                                                <div class="form-group">
                                                    <label><?php echo $idioma->getText("tipoDeposito") ?></label>
                                                    <select class="form-control" id="tipoDeposito" name="tipoDeposito" ><!--tipo de deposito-->
                                                        <option value="<?php echo Utils\Constantes::TED ?>" <?php echo ($deposito->tipoDeposito == Utils\Constantes::TED ? "selected='true'" : "") ?>><?php echo $idioma->getText("ted2") ?></option>
                                                        <option value="<?php echo Utils\Constantes::DOC ?>" <?php echo ($deposito->tipoDeposito == Utils\Constantes::DOC ? "selected='true'" : "") ?>><?php echo $idioma->getText("doc") ?></option>
                                                        <option value="<?php echo Utils\Constantes::TRANSF_ENTRE_CONTAS ?>" <?php echo ($deposito->tipoDeposito == Utils\Constantes::TRANSF_ENTRE_CONTAS ? "selected='true'" : "") ?>><?php echo $idioma->getText("transEntreContas") ?></option>
                                                    </select>
                                                    <div class="row" id="alerta-banco" style="display: none;">
                                                        <div class="col-lg-12">
                                                            <span style="color: #ff1e1e;" id="alerta-banco-observacoes"></span>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col col-lg-5 border-right">
                                                <div class="form-group">
                                                    <label><?php echo $idioma->getText("valorDepositado") ?></label><!--valor a ser depositado-->
                                                    <input type="text"  class="form-control" id="valor" name="valor" value="<?php echo number_format($deposito->valorDepositado, 2, ",", ".") ?>" />
                                                </div>
                                            </div>
                                            <div class="col-lg-7 m-t-md"><!--comprovante de deposito-->
                                                <small><?php echo $idioma->getText("comissaoDeposito") ?> (<span id="comissaoCobradaDeposito"><?php echo number_format($comissao, 2, ",", "") ?></span>%)</small></br>
                                                <small><?php echo $idioma->getText("seraCreditado") ?> <strong id="valorCreditado2"> </strong></small></br>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-lg-7">                                                        
                                                <div class="" style="display: block !important;">
                                                    <label><?php echo $idioma->getText("comprovanDeposito") ?></label>
                                                    <div class="fileinput fileinput-new input-group text-left" data-provides="fileinput" id="arquivo" >
                                                        <div class="form-control" data-trigger="fileinput">
                                                            <i class="glyphicon glyphicon-file fileinput-exists"></i> <span class="fileinput-filename" style="width: 60px !important;"></span>
                                                        </div>
                                                        <span class="input-group-addon btn btn-default btn-file">
                                                            <span class="fileinput-new"><?php echo $idioma->getText("selecionar") ?></span>
                                                            <span class="fileinput-exists"><?php echo $idioma->getText("alterar") ?></span>
                                                            <input class="full-width" type="file" id="comprovante" name="comprovante" accept=".pdf,.jpg,.jpeg,.png,.xps,.doc,.docx,.bmp" maxlength="15">
                                                        </span>
                                                        <a href="#" class="input-group-addon btn btn-default fileinput-exists" data-dismiss="fileinput"><?php echo $idioma->getText("remover") ?></a>
                                                    </div> 
                                                </div>
                                            </div><!--fim comprovante deposito-->
                                            <div class="col-lg-5">
                                                <div class="form-group">  
                                                    <label>&nbsp;</label>
                                                    <button class="btn btn-primary full-width" type="submit" id="btnSalvar"><!--botao cadastrar deposito-->
                                                        <?php echo $idioma->getText("cadastrarDeposito") ?>
                                                    </button>
                                                </div>
                                            </div>
                                        </div>                                                              
                                        <div class="row" id="progressDocumentsContainer">
                                            <div class="col col-lg-12">
                                                <div class="progress">
                                                    <div style="width: 0%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="0" role="progressbar" id="progressDocuments" class="progress-bar progress-bar-success">
                                                        <span class="sr-only" id="progressDocumentsLegend"></span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>  
                                <?php if($configuracao->atarAtivo == 1) { ?>
                                <div id="atar"> 
                                    <?php if($hasAtar){ ?>
                                        <div class="row">
                                            <div class="col-lg-12 text-center">                                                
                                                <div class="border-top-bottom text-center" id="infAtar">
                                                    <img class="m-b-sm m-t-sm" src="" id="qrcodeCointrade" width="158" height="158"/></br>
                                                    <span class="label label-default m-t-sm" style="cursor: pointer; font-size: 11px; letter-spacing: 2px;position: relative;" id="btncopyAtar" alt="<?php echo $idioma->getText("copiarEndereco") ?>">
                                                    </span>
                                                    </br>
                                                    <button class="btn-link m-t-xs m-b-sm" id="btn-link-ref" data-clipboard-target="#btncopyAtar">
                                                        <?php echo $idioma->getText("copiarEndereco1") ?>&nbsp;&nbsp;<i class="fa fa-copy"></i>
                                                    </button>
                                                </div>
                                            </div>                                            
                                        </div>
                                        </br> 
                                    <?php } ?>
                                         <?php if(!$hasAtar) { ?>
                                        <div class="row" id="token2faAtar">  
                                                <div class="col-lg-12">              
                                                    <ul class="list-group">
                                                        <li class="list-group-item" style="height: 30px !important; padding-bottom: 5px !important; padding-top: 5px !important;">
                                                            <div class="row">
                                                                <div class="col-lg-12">
                                                                    <b>Atar ID ou Documento:</b> <span><span id="labelIdAtar"></span></span>
                                                                </div>                                                                  
                                                            </div>
                                                        </li>
                                                        <li class="list-group-item">
                                                            <div class="row">
                                                                <div class="col-lg-6 text-left">
                                                                    <div class="form-group">
                                                                        <label><?php echo "PIN" ?></label>
                                                                        <input type="password" inputmode="numeric" maxlength="4" pattern="[0-9]*" class="form-control" id="pinAtar"/>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </li>
                                                        <li class="list-group-item text-center">
                                                            <div class="row">
                                                                <div class="col-lg-6">
                                                                    <button class="btn btn-white" style="width: 180px;" onclick="limparAtar();"><?php echo "Cancelar" ?></button>
                                                                </div>
                                                                <div class="col-lg-6">
                                                                    <button class="btn btn-success" style="width: 180px;" onclick="depositarAtar();" id="btnCadastrarConta" ><?php echo "Cadastrar" ?></button>
                                                                </div>
                                                            </div>
                                                        </li>
                                                    </ul>
                                                </div>                            
                                            </div>
                                        <div id="cadastroAtar">
                                                    <div class="row">                                            
                                                        <div class="col-lg-12">
                                                            <h4>Cadastre seu Atar ID ou Documento (CPF ou CNPJ) para receber os seus depósitos feitos na Atar.</h4>
                                                        </div>
                                                    </div>
                                                    <div class="row">
                                                        <div class="col-lg-6">
                                                            <div class="form-group">
                                                                <label><?php echo "Atar ID ou Documento" ?></label>
                                                                <input type="text"  class="form-control" id="idAtar" name="idAtar" value="" />
                                                            </div>
                                                        </div>                                                                                                 
                                                    </div>
                                                    <div class="row border-bottom">                                            
                                                        <div class="col-lg-6">
                                                            <div class="form-group">                                                    
                                                                <button class="btn btn-primary full-width" type="button" onclick="tokenAtar();" id="btnTokenAtar">
                                                                    <?php echo "Cadastrar Conta Atar" ?>
                                                                </button>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                         <?php } else { ?>
                                                <div id="atarAtivo">
                                                    </br>
                                                    <div class="row">                                            
                                                        <div class="col-lg-12">
                                                            <h4>Meu Cadastro Atar</h4>
                                                        </div>
                                                    </div>
                                                    <div class="row border-bottom">
                                                        <div class="col-lg-6">
                                                            <b>Atar ID ou Documento:</b> <span><?php echo $atarCliente->idAtar ?></span>
                                                        </div> 
                                                        </br>
                                                    </div>
                                                </div>
                                         <?php } ?>
                                            </br>
                                        </div>
                                    <?php } ?>
                                
                                <div id="depositoBoleto"> 
                                    </br>
                                    <div class="row">                                
                                        <div class="col-lg-12">
                                            <label><?php echo $idioma->getText("depositeBoleto") ?></label>
                                        </div>
                                    </div>
                                    </br>
                                    <div id="telaBoleto">
                                        <div class="row">
                                            <div class="col col-lg-5 border-right">
                                                <div class="form-group">
                                                    <label><?php echo $idioma->getText("valorDepositado") ?></label>
                                                    <input type="text"  class="form-control" id="valorBoleto" name="valorBoleto"/>
                                                </div>
                                            </div>
                                            <div class="col-lg-7 m-t-md">
                                                <small><?php echo $idioma->getText("comissaoDeposito") ?> (<span id="comissaoCobradaBoleto">R$ <?php echo number_format($tarifaBoleto, 2, ",", "") ?> + <?php echo number_format($comissao, 2, ",", "") ?></span>%)</small></br>
                                                <small><?php echo $idioma->getText("seraCreditado") ?> <strong id="valorCreditadoBoleto"> </strong></small>                                     
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-lg-4">                                    
                                                <button type="button" class="btn btn-primary full-width" onclick="tokenBoleto();" id="btnGerarBoleto"><?php echo $idioma->getText("gerarBoleto") ?></button>
                                            </div>
                                        </div>
                                    </div>                                    
                                    <div class="row" id="tokenBoleto" hidden="true">                                
                                            <div class="col-lg-12">                                     
                                                <label><?php echo $idioma->getText("insiraSeuToken") ?></label>                                    
                                                <ul class="list-group">
                                                    <li class="list-group-item" style="height: 30px !important; padding-bottom: 5px !important; padding-top: 5px !important;"><b>Valor do Boleto:</b> <span id="valorTotalBoleto"></span></li>
                                                    <li class="list-group-item" style="height: 30px !important; padding-bottom: 5px !important; padding-top: 5px !important;"><b>Valor à Creditar:</b> <span id="valorCreditarBoleto"></span></li>
                                                    <li class="list-group-item">
                                                        <div class="row">
                                                            <div class="col-lg-6">
                                                                <div class="form-group">
                                                                    <label><?php echo $idioma->getText("pin") ?></label>
                                                                    <input type="password" inputmode="numeric" pattern="[0-9]*" class="form-control" id="pinBoleto"/>
                                                                </div>
                                                            </div>
                                                            <div class="col-lg-6">
                                                                <div class="form-group m-b-none">
                                                                    <label><?php echo $idioma->getText("token2fa") ?></label>
                                                                    <input type="text" inputmode="numeric" pattern="[0-9]*" class="form-control" id="tokenBoletoDigito"/>
                                                                    <?php if ($cliente->tipoAutenticacao === \Utils\Constantes::TIPO_AUTH_EMAIL) { ?>
                                                                        <a href="javascript:tokenBoleto();" id="reenviarLink"><?php echo $idioma->getText("reenviar2fa") ?></a>
                                                                    <?php } ?>
                                                                </div>
                                                            </div> 
                                                        </div>
                                                    </li>
                                                    <li class="list-group-item text-center">
                                                        <div class="row">
                                                            <div class="col-lg-6">
                                                                <button class="btn btn-white" style="width: 180px;" onclick="cancelarBoleto();"><?php echo $idioma->getText("cancelar") ?></button>
                                                            </div>
                                                            <div class="col-lg-6">
                                                                <button class="btn btn-success" style="width: 180px;" onclick="salvarDepositoBoleto();"><?php echo $idioma->getText("confirmar") ?></button>
                                                            </div>
                                                        </div>
                                                    </li>
                                                </ul>
                                            </div>                            
                                        </div>
                                    <div class="text-center" id="carregaBoleto" hidden="true"></div>
                                    <div class="row m-t-md" id="boletoGerado" hidden >  
                                        <div class="col-lg-12">
                                            <ul class="list-group">
                                                <li class="list-group-item">
                                                    <strong><?php echo $idioma->getText("codigoBarras") ?>: </strong></br>
                                                    <div class="row m-t-xs">
                                                        <div class="col col-lg-12 text-center" id="modalBoletoGeradoImgBarcode"> 
                                                        </div>                                                
                                                    </div>
                                                    <div class="row">
                                                        <div class="col-lg-12 text-center">
                                                            <span id="codigoBarrasDigito" style="font-size: 16px;"></span>
                                                        </div>
                                                    </div>
                                                </li>                            
                                                <li class="list-group-item ">
                                                    <div class="row m-t-xs">
                                                        <div class="col-lg-6"><strong><?php echo $idioma->getText("dataVencimento") ?>: </strong><span id="modalBoletoGeradoVencimento"></span></div>
                                                    </div>
                                                </li>
                                                <li class="list-group-item">
                                                    <div class="row m-t-xs">
                                                        <div class="col-lg-6"><strong><?php echo "Comissão" ?>: </strong><span id="modalBoletoComissao"></span></div>
                                                        <div class="col-lg-6"><strong><?php echo "Valor Tarifa" ?>: </strong><span id="modalBoletoTaxa"></span></div>                                       
                                                    </div>
                                                </li>
                                                <li class="list-group-item ">
                                                    <div class="row m-t-xs">
                                                        <div class="col-lg-6"><strong><?php echo "Valor Boleto" ?>:</strong> <span id="modalBoletoGeradoValor"></span></div>
                                                        <div class="col-lg-6"><strong><?php echo "Valor à Creditar" ?>: <span id="modalBoletoValorCreditar"></span></strong></div>                                       
                                                    </div>
                                                </li>                                                
                                                
                                                    <div class="row text-center">
                                                        <div class="col-lg-6">
                                                            <a class="btn btn-md btn-success m-t-xs m-b-xs" style="text-decoration: none; color: #fff;" id="modalBoletoGeradoLink" href="" target="_BLANK"><?php echo $idioma->getText("downloadBoleto") ?> &nbsp;<i class="fa fa-download"></i></a>
                                                        </div>
                                                        <div class="col-lg-6">
                                                            <a class="btn btn-md btn-white m-t-xs m-b-xs" style="text-decoration: none;" data-clipboard-target="#codigoBarrasDigito" id="copiarCodigoBarras"><?php echo $idioma->getText("copiarBoleto") ?> &nbsp;<i class="fa fa-copy"></i></a>
                                                        </div>
                                                    </div>
                                                
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                                
                            </div>
                            <div class="col-lg-5">
                                <div id="vertical-timeline" class="vertical-container light-timeline no-margins">
                                    <div class="vertical-timeline-block">
                                        <div class="vertical-timeline-icon yellow-bg">
                                            <i class="fa fa-exclamation fa-1x"></i>
                                        </div>
                                        <div class="vertical-timeline-content">
                                            <strong class="text-center"><h5><?php echo $idioma->getText("atencao") ?> </h5></strong><!--atenção atencao-->
                                            <small><ul style="text-align: justify;">
                                                    <li class="m-t-xs"><?php echo $idioma->getText("naoPermitidoDepositoDinheiro") ?></li>
                                                    <li class="m-t-xs"><?php echo $idioma->getText("naoAceitamosDepositosTerceiros") ?></li>
                                                </ul></small>
                                        </div>
                                    </div>
                                    <?php if($configuracao->atarAtivo == 1){ ?>
                                    <div class="vertical-timeline-block">
                                        <div class="vertical-timeline-icon blue-bg">
                                            <i class="fa fa-info fa-1x"></i>
                                        </div>
                                        <div class="vertical-timeline-content">
                                            <strong class="text-center"><h5><?php echo "ATAR PAY" ?> </h5></strong><!--informacoes-->
                                            <small><ul>
                                                    <li class="m-t-xs"><?php echo "Depósitos via Atar Pay são instantâneos e 24/7." ?></li>
                                                    <li class="m-t-xs"><?php echo "Baixe o app Atar Pay e crie sua conta grátis em apenas 2 minutos." ?></li>
                                                    <li class="m-t-xs"><a href="https://apps.apple.com/br/app/atar-pay/id1144625341" target="atar_pay"><?php echo "Link iOS" ?></a></li>
                                                    <li class="m-t-xs"><a href="https://play.google.com/store/apps/details?id=com.wearatar.atarpay&hl=en" target="atar_pay"><?php echo "Link Android" ?></a></li>
                                                    <li class="m-t-xs"><?php echo "Tarifa para depósito: R$ " . number_format($configuracao->atarTarifaDeposito, 2, ",", ".")?></li>
                                                    <li class="m-t-xs"><?php echo "Taxa para depósito: R$ " . number_format($configuracao->atarTaxsDeposito, 2, ",", ".")?></li>
                                                </ul></small> 
                                        </div>
                                    </div>
                                    <?php } ?>
                                    <div id="infBanco">
                                        <div class="vertical-timeline-block">
                                            <div class="vertical-timeline-icon blue-bg">
                                                <i class="fa fa-info fa-1x"></i>
                                            </div>
                                            <div class="vertical-timeline-content">
                                                <strong class="text-center"><h5><?php echo $idioma->getText("informacoes") ?> </h5></strong><!--informacoes-->
                                                <small><ul>
                                                        <li class="m-t-xs"><?php echo str_replace("{var1}", $valorMinimo, $idioma->getText("valorMinimoDeposito")) ?></li>
                                                        <li class="m-t-xs"><?php echo str_replace("{var2}", $valorMinimo, $idioma->getText("ted")) ?></li>
                                                        <li class="m-t-xs"><?php echo $idioma->getText("doc2") ?></li>
                                                        <li class="m-t-xs"><?php echo $idioma->getText("informacoesEnvioArqLi4") ?></li>
                                                        <li class="m-t-xs"><?php echo $idioma->getText("informacoesEnvioArqLi1") ?></li>
                                                        <li class="m-t-xs"><?php echo $idioma->getText("informacoesEnvioArqLi2") ?></li>
                                                        <li class="m-t-xs"><?php echo $idioma->getText("informacoesEnvioArqLi3") ?></li>                                                 
                                                        <li class="m-t-xs"><?php echo $idioma->getText("informacoesEnvioArqLi5") ?></li>
                                                        <li class="m-t-xs"><?php echo $idioma->getText("informacoesEnvioArqLi6") ?></li>
                                                        <?php if($boletoAtivo) { ?>
                                                        <li class="m-t-xs"><?php echo "Boleto - Valor máximo de R$ " . number_format($configuracao->valorMaxBoleto, 2, ",", ".") ?></li>
                                                        <?php } ?>
                                                    </ul></small> 
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                </br>
                            </div>

                            <!--Tabela Reais-->
                            <div id="tabelaReais">
                                <div class="ibox-content">
                                    <div class="row">
                                        <div class="col-sm-2 ">
                                            <select class="form-control input-sm form-control input-s-sm inline" id="filtroStatus">
                                                <option value="T"><?php echo $idioma->getText("todos") ?></option>
                                                <option value="<?php echo Utils\Constantes::STATUS_DEPOSITO_PENDENTE ?>"><?php echo $idioma->getText("pendente") ?></option>
                                                <option value="<?php echo Utils\Constantes::STATUS_DEPOSITO_CONFIRMADO ?>"><?php echo $idioma->getText("confirmado") ?></option>
                                                <option value="<?php echo Utils\Constantes::STATUS_DEPOSITO_CANCELADO ?>"><?php echo $idioma->getText("cancelado") ?></option>
                                            </select>
                                        </div>
                                        <div class="col-sm-2 ">
                                            <select class="form-control input-sm form-control input-s-sm inline" id="filtroIdContaBancariaEmpresa">
                                                <option value="0"><?php echo $idioma->getText("todasContas") ?></option>
                                                <?php foreach ($contasBancarias as $contaBancaria) { ?>
                                                    <option value="<?php echo $contaBancaria->id ?>">
                                                        <?php echo "{$contaBancaria->banco->nome}  {$contaBancaria->agencia}/{$contaBancaria->conta}"; ?>
                                                    </option>
                                                <?php } ?>
                                            </select>
                                        </div>
                                        <div class="col-sm-2 ">
                                            <select class="form-control  input-sm form-control input-s-sm inline" id="filtroTipoDeposito">                                        
                                                <option value="Q"><?php echo $idioma->getText("todos") ?></option>
                                                <option value="<?php echo Utils\Constantes::TED ?>"><?php echo $idioma->getText("ted2") ?></option>
                                                <option value="<?php echo Utils\Constantes::DOC ?>"><?php echo $idioma->getText("doc") ?></option>
                                                <option value="<?php echo Utils\Constantes::DINHEIRO ?>"><?php echo $idioma->getText("dinheiro") ?></option>
                                                <option value="<?php echo Utils\Constantes::TRANSF_ENTRE_CONTAS ?>" <?php echo ($deposito->tipoDeposito == Utils\Constantes::TRANSF_ENTRE_CONTAS ? "selected='true'" : "") ?>><?php echo $idioma->getText("transEntreContas") ?></option>

                                            </select>
                                        </div>
                                        <div class="col-sm-3 ">
                                            <div data-toggle="buttons" class="btn-group" id="radioDatas">
                                                <label class="btn btn-sm btn-white" id="diaReal"> <input type="radio"  name="options" value="dia"><?php echo $idioma->getText("dia") ?></label>
                                                <label class="btn btn-sm btn-white active" id="semanaReal"> <input type="radio"  name="options" value="semana"><?php echo $idioma->getText("semana") ?></label>
                                                <label class="btn btn-sm btn-white" id="mesReal"> <input type="radio"  name="options" value="mes"><?php echo $idioma->getText("mes") ?></label>
                                                <label class="btn btn-sm btn-white" id="todosReal"> <input type="radio"  name="options" value="todos"><?php echo $idioma->getText("todos") ?></label>
                                            </div>
                                        </div>
                                        <div class="col-sm-3 ">
                                            <div class="input-group">
                                                <input type="text" id="filtroTextoReal" placeholder="<?php echo $idioma->getText("pesquisar") ?>" class="input-sm form-control"><span class="input-group-btn">
                                                    <button type="button" class="btn btn-sm btn-primary" onclick="filtrarReaisAux();">&nbsp;<i class="fa fa-search"></i></button>
                                                    <button type="button" class="btn btn-sm btn-default" onclick="limpaSearchReal();">&nbsp;<i class="fa fa-eraser"></i></button></span>
                                            </div>
                                        </div>
                                    </div>                            
                                    <div class="table-responsive m-t-sm">
                                        <table id="tbllistareais" class="table table-striped text-center" data-page-size="8"  style="font-size: 16px;">
                                            <thead>
                                                <tr>
                                                    <th class="text-center">
                                                        <?php echo $idioma->getText("controle") ?>
                                                    </th>
                                                    <th class="text-center">
                                                        <?php echo $idioma->getText("data") ?>
                                                    </th>
                                                    <th class="text-center">
                                                        <?php echo $idioma->getText("conta") ?>
                                                    </th>
                                                    <th class="text-center">
                                                        <?php echo $idioma->getText("deposito") ?> 
                                                    </th>
                                                    <th class="text-center">
                                                        <?php echo $idioma->getText("comissaoR") ?>
                                                    </th>
                                                    <th class="text-center">
                                                        <?php echo $idioma->getText("comissaoP") ?>
                                                    </th>
                                                    <th class="text-center">
                                                        <?php echo $idioma->getText("creditado") ?>
                                                    </th>
                                                    <th class="text-center">
                                                        <?php echo $idioma->getText("comp") ?>
                                                    </th>                                                    
                                                    <th class="text-center">
                                                        <?php echo $idioma->getText("status") ?>
                                                    </th>
                                                </tr>
                                            </thead>
                                            <tbody id="listaReais">

                                            </tbody>
                                            <tfoot>
                                                <tr>
                                                    <td colspan="10">
                                                        <ul class="pagination pull-right"></ul>
                                                    </td>
                                                </tr>
                                            </tfoot>
                                        </table>
                                    </div>                        
                                </div>
                            </div>
                            
                            <div id="tabelaAtar">
                                <div class="ibox-content">
                                    <div class="row">
                                        <div class="col-sm-3 ">
                                            <div data-toggle="buttons" class="btn-group" id="radioDatasAtar">
                                                <label class="btn btn-sm btn-white" id="diaAtar"> <input type="radio"  name="options" value="dia"><?php echo $idioma->getText("dia") ?></label>
                                                <label class="btn btn-sm btn-white active" id="semanaAtar"> <input type="radio"  name="options" value="semana"><?php echo $idioma->getText("semana") ?></label>
                                                <label class="btn btn-sm btn-white" id="mesAtar"> <input type="radio"  name="options" value="mes"><?php echo $idioma->getText("mes") ?></label>
                                                <label class="btn btn-sm btn-white" id="todosAtar"> <input type="radio"  name="options" value="todos"><?php echo $idioma->getText("todos") ?></label>
                                            </div>
                                        </div>
                                        <div class="col-sm-offset-6 col-sm-3 ">
                                            <div class="input-group">
                                                <input type="text" id="filtroTextoAtar" placeholder="<?php echo $idioma->getText("pesquisar") ?>" class="input-sm form-control"><span class="input-group-btn">
                                                    <button type="button" class="btn btn-sm btn-primary" onclick="filtrarAtarAux();">&nbsp;<i class="fa fa-search"></i></button>
                                                    <button type="button" class="btn btn-sm btn-default" onclick="limpaSearchAtar();">&nbsp;<i class="fa fa-eraser"></i></button></span>
                                            </div>
                                        </div>
                                    </div>                            
                                    <div class="table-responsive m-t-sm">
                                        <table id="tbllistaAtar" class="table table-striped text-center" data-page-size="8"  style="font-size: 16px;">
                                            <thead>
                                                <tr>                                                   
                                                    <th class="text-center">
                                                        <?php echo $idioma->getText("data") ?>
                                                    </th>
                                                    <th class="text-center">
                                                        <?php echo $idioma->getText("deposito") ?> 
                                                    </th>
                                                    <th class="text-center">
                                                         <?php echo $idioma->getText("comissaoP") ?>
                                                    </th>
                                                    <th class="text-center">
                                                       <?php echo $idioma->getText("tarifa") ?> 
                                                    </th>
                                                    <th class="text-center">
                                                        <?php echo $idioma->getText("creditado") ?>
                                                    </th>  
                                                    <th class="text-center">
                                                        <?php echo $idioma->getText("status") ?>
                                                    </th>
                                                </tr>
                                            </thead>
                                            <tbody id="listaAtar">

                                            </tbody>
                                            <tfoot>
                                                <tr>
                                                    <td colspan="10">
                                                        <ul class="pagination pull-right"></ul>
                                                    </td>
                                                </tr>
                                            </tfoot>
                                        </table>
                                    </div>                        
                                </div>
                            </div>
                            <!--Tabela Boleto -->
                            <div id="tabelaBoleto">
                                <div class="ibox-content">
                                    <div class="row">
                                        <div class="col-sm-3 m-b-xs">
                                            <select class="form-control input-sm form-control input-s-sm inline" id="filtroStatusBoleto">
                                                <option value="T"><?php echo $idioma->getText("todos") ?></option>
                                                <option value="<?php echo Utils\Constantes::STATUS_DEPOSITO_PENDENTE ?>"><?php echo $idioma->getText("pendente") ?></option>
                                                <option value="<?php echo Utils\Constantes::STATUS_DEPOSITO_CONFIRMADO ?>"><?php echo $idioma->getText("confirmado") ?></option>
                                                <option value="<?php echo Utils\Constantes::STATUS_DEPOSITO_CANCELADO ?>"><?php echo $idioma->getText("cancelado") ?></option>
                                            </select>
                                        </div>
                                        <div class="col-sm-3 m-b-xs">
                                            <div data-toggle="buttons" class="btn-group" id="radioDatasBoleto">
                                                <label class="btn btn-sm btn-white" id="diaReal"> <input type="radio"  name="options" value="dia"><?php echo $idioma->getText("dia") ?></label>
                                                <label class="btn btn-sm btn-white active" id="semanaReal"> <input type="radio"  name="options" value="semana"><?php echo $idioma->getText("semana") ?></label>
                                                <label class="btn btn-sm btn-white" id="mesReal"> <input type="radio"  name="options" value="mes"><?php echo $idioma->getText("mes") ?></label>
                                                <label class="btn btn-sm btn-white" id="todosReal"> <input type="radio"  name="options" value="todos"><?php echo $idioma->getText("todos") ?></label>
                                            </div>
                                        </div>
                                        <div class="col-sm-3 col-sm-offset-3 m-b-xs">
                                            <div class="input-group">
                                                <input type="text" id="filtroTextoBoleto" placeholder="<?php echo $idioma->getText("pesquisar") ?>" class="input-sm form-control"><span class="input-group-btn">
                                                    <button type="button" class="btn btn-sm btn-primary" onclick="boletoAux();">&nbsp;<i class="fa fa-search"></i></button>
                                                    <button type="button" class="btn btn-sm btn-default" onclick="limpaSearchBoleto();">&nbsp;<i class="fa fa-eraser"></i></button></span>
                                            </div>
                                        </div>
                                    </div>                            
                                    <div class="table-responsive m-t-sm">
                                        <table id="tblListaBoleto" class="table table-striped text-center" data-page-size="8"  style="font-size: 16px;">
                                            <thead>
                                                <tr>
                                                    <th class="text-center">
                                                        <?php echo $idioma->getText("controle") ?>
                                                    </th>
                                                    <th class="text-center">
                                                        <?php echo $idioma->getText("data") ?>
                                                    </th>
                                                    <th class="text-center">
                                                        <?php echo $idioma->getText("pagamento") ?>
                                                    </th>
                                                    <th class="text-center">
                                                        <?php echo $idioma->getText("deposito") ?> 
                                                    </th>
                                                    <th class="text-center">
                                                        <?php echo $idioma->getText("tarifa") ?> 
                                                    </th>
                                                    <th class="text-center">
                                                        <?php echo $idioma->getText("comissaoR") ?>
                                                    </th>
                                                    <th class="text-center">
                                                        <?php echo $idioma->getText("comissaoP") ?>
                                                    </th>
                                                    <th class="text-center">
                                                        <?php echo $idioma->getText("creditado") ?>
                                                    </th>                                                    
                                                    <th class="text-center">
                                                        <?php echo $idioma->getText("status") ?>
                                                    </th>
                                                </tr>
                                            </thead>
                                            <tbody id="listaBoleto">

                                            </tbody>
                                            <tfoot>
                                                <tr>
                                                    <td colspan="5">
                                                        <ul class="pagination pull-right"></ul>
                                                    </td>
                                                </tr>
                                            </tfoot>
                                        </table>
                                    </div>                        
                                </div>
                            </div>
                        </div>
                </div>
                <?php } ?>
                <div id="depositoMoedas" hidden="true">
                    <div class="row">
                        <div class="col-lg-7">
                            <h2 id="tituloMoeda" style="display: inline;"></h2>&nbsp;&nbsp;<img id="icone" src="" height="25" width="25" style="margin-bottom: 10px;"/>
                            <div class="border-top-bottom text-center" id="infMoeda">
                            <img class="m-b-sm m-t-sm" src="" id="imagemWallet" width="158" height="158"/></br>
                            <span class="label label-default m-t-sm" style="cursor: pointer; font-size: 11px; letter-spacing: 2px;position: relative;left: -15px" id="btncopy" alt="<?php echo $idioma->getText("copiarEndereco") ?>">
                             </span>
                            </br>
                            <button class="btn-link m-t-xs m-b-sm" id="btn-link-ref" data-clipboard-target="#btncopy">
                                   <?php echo $idioma->getText("copiarEndereco1") ?>&nbsp;&nbsp;<i class="fa fa-copy"></i>
                            </button>
                        </div>
                        <div class="border-top-bottom text-center" id="infSemMoeda" hidden="true" style="height: 236px; width: 526.062px;display: table-cell; vertical-align: middle;">             
                                <i class="fa fa-question fa-5x m-b-md"></i></br>
                                <span class="label label-default m-t-sm m-b-md" style="cursor: pointer; font-size: 18px; letter-spacing: 2px;">- - - - - - - - - - - - - - - - - - - - - - - - -</span></br></br>
                                <button class="btn-link" id="btn-link-carteira" onclick="salvar();">
                                   <?php echo $idioma->getText("criarCarteira") ?>&nbsp;&nbsp;<i class="fa fa-plus-circle"></i>
                                </button>
                        </div>
                        </div>
                        <div class="col-lg-5">
                            <div id="vertical-timeline" class="vertical-container light-timeline no-margins">
                                <div class="vertical-timeline-block">
                                    <div class="vertical-timeline-icon blue-bg">
                                        <i class="fa fa-info fa-1x"></i>
                                    </div>
                                    <div class="vertical-timeline-content">
                                        <strong class="text-center"><h5><?php echo $idioma->getText("informacoes")?></h5></strong>
                                        <small><ul>
                                                <li id="naoTaxaDeposito"></li>
                                        </ul></small>                    
                                    </div>
                                </div>
                                <div class="vertical-timeline-block">
                                    <div class="vertical-timeline-icon yellow-bg">
                                        <i class="fa fa-exclamation fa-1x"></i>
                                    </div>
                                    <div class="vertical-timeline-content">
                                        <strong class="text-center"><h5><?php echo $idioma->getText("atencao") ?></h5></strong>
                                        <small><ul>
                                                <li id="envieSomente"></li>
                                        </ul></small>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div></br></br>
                    <!--Tabela Moeda-->
                    <div id="tabelaMoeda">
                        <div class="ibox-content">
                            <div class="row">
                                <div class="col-sm-4 ">
                                    <div data-toggle="buttons" class="btn-group" id="radioDatasBtc">
                                        <label class="btn btn-sm btn-white" id="diaBtc"> <input type="radio" id="" name="optionsBtc" value="dia"><?php echo $idioma->getText("dia") ?></label>
                                        <label class="btn btn-sm btn-white active" id="semanaBtc"> <input type="radio" id="" name="optionsBtc" value="semana"><?php echo $idioma->getText("semana") ?></label>
                                        <label class="btn btn-sm btn-white" id="mesBtc"> <input type="radio" id="" name="optionsBtc" value="mes"><?php echo $idioma->getText("mes") ?></label>
                                        <label class="btn btn-sm btn-white" id="todosBtc"> <input type="radio" id="" name="optionsBtc" value="todos"><?php echo $idioma->getText("todos") ?></label>
                                    </div>
                                </div>
                                <div class=" col-sm-4 pull-left m-t-sm">
                                        <?php echo $idioma->getText("recompensa") ?>
                                        <input type="checkbox" id="referencia" class="js-switch" onchange="filtrarBtc()"/>                                    
                                </div>
                                <div class="col-sm-offset-1 col-sm-3 pull-left">
                                    <div class="input-group">
                                        <input type="text" id="filtroTextoBtc" placeholder="<?php echo $idioma->getText("pesquisar") ?>" class="input-sm form-control"><span class="input-group-btn">
                                        <button type="button" class="btn btn-sm btn-primary" onclick="filtrarBtcAux();">&nbsp;<i class="fa fa-search"></i></button>
                                        <button type="button" class="btn btn-sm btn-default" onclick="limpaSearchBtc();">&nbsp;<i class="fa fa-eraser"></i></button></span>
                                    </div>
                                </div>
                            </div>   
                            
                        <div class="table-responsive ">
                                <table id="tbllistabtc" class="table table-striped text-center" data-page-size="6"  style="font-size: 16px;">
                                    <thead>
                                    <tr>
                                        <th class="text-center"><?php echo $idioma->getText("controle") ?></th>
                                        <th class="text-center"><?php echo $idioma->getText("volume") ?></th>
                                        <th class="text-center"><?php echo $idioma->getText("comp") ?></th>
                                        <th class="text-center"><?php echo $idioma->getText("data") ?></th>
                                        <th class="text-center"><?php echo $idioma->getText("endereco") ?></th>
                                    </tr>
                                    </thead>
                                    <tbody id="listaBtc">                                    
                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <td colspan="5">
                                                <ul class="pagination pull-right"></ul>
                                            </td>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>
                    </div>
                    </div>
                </div>
                <div id="ultimosDepositos" class="mostrar" hidden="true">
                    <div class="row">
                        <div class="col-lg-12">
                            <h2 style="display: inline;"><?php echo $idioma->getText("meusUltimosDepositos") ?></h2>
                            <div class="table-responsive" style="margin-top: 33px;">
                                <input type="text" class="form-control input-sm m-b-xs col-offset-4 col-lg-2" id="filter"
                                   placeholder="<?php echo $idioma->getText("pesquisar") ?>" style="margin-bottom: 10px !important;">

                                        <table id="tblultimosdepositos" class="table table-stripped text-center" data-page-size="15" data-filter=#filter style="font-size: 16px;">
                                    <thead>
                                    <tr>
                                        <th class="text-center"><?php echo $idioma->getText("data") ?></th>
                                        <th class="text-center"><?php echo $idioma->getText("hora") ?></th>
                                        <th class="text-center"><?php echo $idioma->getText("tipoTabela") ?></th>
                                        <th class="text-center"><?php echo $idioma->getText("volume") ?></th>
                                        <th class="text-center"><?php echo $idioma->getText("comprovante") ?></th>
                                        <th class="text-center"><?php echo $idioma->getText("status") ?></th>
                                    </tr>
                                    </thead>
                                    <tbody id="listaDepositos">                                    
                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <td colspan="6">
                                                <ul class="pagination pull-right"></ul>
                                            </td>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            
            </div>                
            <div class="clearfix"></div>
        </div>
    </div>

    <?php Utils\Layout::append("inspina/footer_esp", $_data) ?>
    <script src="<?php echo TEMA; ?>js/plugins/switchery/switchery.js"></script>
    <script>
        
    var comissao = <?php echo number_format($comissao, 2, ".", "")?>;
    var comissaoBoleto = <?php echo number_format($comissaoBoleto, 2, ".", "")?>;
    var tarifaBoleto = <?php echo number_format($tarifaBoleto, 2, ".", "")?>;

    var comissaoDinheiroAte2 = <?php echo number_format($configuracao->percentualDepositos, 2, ".", "")?>;
    var comissaoDinheiro2a5 = <?php echo number_format($configuracao->depositoDoisCinco, 2, ".", "")?>;
    var comissaoDinheiro5a10 = <?php echo number_format($configuracao->depositoCincoDez, 2, ".", "")?>;
    var comissaoDinheiro10a50 = <?php echo number_format($configuracao->depositoDezCinquenta, 2, ".", "")?>;
    var comissaoDinheiro50acima = <?php echo number_format($configuracao->depositoCinquentaAcima, 2, ".", "")?>;   
    var dataReal = "";
    var dataCoin = "";
    var dataAtar = "";
    var moeda = "";
    var banco = "";
    var tarifaAtar = 0;
    var taxaAtar = 0;
    var boleto = false;
    

    $(document).ready(function () {  
        new Clipboard("#barCode");
        new Clipboard("#copiarCodigoBarras");        
        
        listarParidadesBook();
        setInterval(listarParidadesBook, 5000);
        loadCheckBox();
        
        
        $("#ticker-paridade").change(function () {
            listarParidadesBook();
        }); 
        

        $('#tblultimosdepositos').footable();
        $('#tbllistabtc').footable();
        $('#tbllistareais').footable();
        $('#tblListaBoleto').footable();
        $('#tbllistaAtar').footable();
        
        $("#filtroStatus").change(function () {
           filtrarReais();  
        }); 
        
        $("#filtroStatusBoleto").change(function () {
           boletoAux();  
        });  
        
        $("#filtroStatusBtc").change(function () {
           filtrarBtc();  
        });
        $("#filtroTipoDeposito").change(function () {
            filtrarReais();  
        });
        $("#filtroIdContaBancariaEmpresa").change(function () {
           filtrarReais();  
        });
        
        $("#radioDatas input").on('change', function(){
            dataReal = $('input[name="options"]:checked', '#radioDatas').val();
            filtrarReais();  
       });
       
       $("#radioDatasAtar input").on('change', function(){
            dataAtar = $('input[name="options"]:checked', '#radioDatasAtar').val();
            filtrarAtar();  
       });
       
        $("#radioDatasBoleto input").on('change', function(){
            dataReal = $('input[name="options"]:checked', '#radioDatasBoleto').val();
            boletoAux();  
       });
       
        $("#radioDatasBtc input").on('change', function(){
            dataCoin = $('input[name="optionsBtc"]:checked', '#radioDatasBtc').val();
            filtrarBtc();  
       });
       
       $('#btnSalvar').attr('disabled',true);
       
       $('#comprovante').change(function(){           
            if($('#comprovante').val() == ''){               
                $('#btnSalvar').attr('disabled',true);
            } else {                 
                $('#btnSalvar').attr('disabled',false);
            }
        });
        
        new Clipboard("#btn-link-ref");
             
            filtrarReais();  
            filtrarBtc();
             
            $("#depositoReais").hide();
            $("#depositoMoedas").hide();
            $("#moeda, #filtroMoeda").select2();
            $(".mostrar").show();
            listar();
            listaDeposito();
            
           $("#valor").keydown(function (event) {
            $(this).val(currency($(this).val(), 2, 8, event.keyCode));
                event.preventDefault();
                calcularValorCreditado();
            });
            
            $("#valorAtar").keydown(function (event) {
            $(this).val(currency($(this).val(), 2, 8, event.keyCode));
                event.preventDefault();
                calcularValorAtar();
            });
            
            $("#valorBoleto").keydown(function (event) {
            $(this).val(currency($(this).val(), 2, 8, event.keyCode));
                event.preventDefault();
                calcularValorBoleto();
            });
 
            
            $("#form-deposito").ajaxForm({
            dataType: 'json',
            beforeSubmit: function () {
                $("#btnSalvar").prop("disabled", true);
                $("#idContaBancariaEmpresa").val(banco);
            },
            uploadProgress: function(event, position, total, percentComplete) {
                $("#progressDocumentsContainer").show();
                var percentVal = percentComplete + '%';
                $("#progressDocuments").width(percentVal);
                $("#progressDocumentsLegend").html("<?php echo $idioma->getText("carregando")?> "+percentVal + "%");
                },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("a[data-dismiss='fileinput']").trigger("click");
                        $("#idContaBancariaEmpresa").children("option").first().prop("selected", true);
                        $("#tipoDeposito").children("option").first().prop("selected", true);
                        $("#valor").val("0,00").trigger("keydown");
                        showNotyAlert("<?php echo $idioma->getText("solicitacaoDepositoSucesso")?>", "s");
                        limparCampos();
                        filtrarReais();
                        
                        if (json.boleto) {
                            modalGerarBoleto(json.deposito);
                        }                        
                        
                    } else {
                        showNotyAlert(json.mensagem, "e");
                        limparCampos();
                    }
                } catch (e){
                    showNotyAlert(e, "e");
                    limparCampos();
                }                
                $("#progressDocumentsContainer").hide();
                $("#progressDocuments").width("0%");
                $("#progressDocumentsLegend").html("");
                limparCampos();
            }
           
        });
        
        $("#tipoDeposito").change(function () {
            if ($(this).val() === '<?php echo Utils\Constantes::DINHEIRO ?>' && $("#alerta-banco-observacoes").html().length > 0) {
                $("#alerta-banco").show();
            } else {
                $("#alerta-banco").hide();
            }
        });
            
                    
            $("#tipoDeposito").change(function () {
                if ($(this).val() === '<?php echo \Utils\Constantes::GERENCIA_NET?>') {
                    $("#idContaBancariaEmpresa").val(0);
                    $("#idContaBancariaEmpresa").prop("disabled", true);
                    $("#comprovante").prop("disabled", true).trigger("change");
                    $("#item-list-logo-banco").show();
                    $("#logo-banco").attr("src", "<?php echo IMAGES ?>logo.png");
                    $("#contaTitular, #contaCnpj, #contaNomeBanco, #contaTipo, #contaAgencia, #contaNumero").val("");
                } else {
                    $("#idContaBancariaEmpresa").prop("disabled", false);
                    $("#item-list-logo-banco").hide();
                    $("#logo-banco").attr("src", "");
                    $("#comprovante").prop("disabled", false).trigger("change");
                }
                calcularValorCreditado();
            });
            
            if (('<?php echo $selectMoeda ?>' != '') && ('<?php echo $selectCategoria ?>' != '')){
            console.log('1')
                showCoin('<?php echo $selectMoeda ?>', '<?php echo $selectCategoria ?>');
                console.log('2')
            }
            
            
        });


        // 01/08/2019 Caique - Atualizando infos
             var initFlag = false;
             function initPage() {
                if (!initFlag) { 
                    
                    $.ajax({
                        url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_INIT ?>',
                        method: 'post',
                        dataType: 'json',
                        beforeSend: function () {
                            initFlag = true;
                        },
                        data: {
                            casasCurrency: 4
                        },
                        complete: function () {
                            initFlag = false;
                        },
                        success: function (json) {
                            try {
        
                                if (typeof json.redirect !== "undefined" && json.redirect) {
                                    location = json.url;
                                }
        
                                  if (json.sucesso) {
                                      
                                      $("#valorcompra").html(json.compraf);
                                      $("#valorvenda").html(json.vendaf);
                                      $("#volume").html(json.volumef);
                                       $("#valorcompraM").html(json.compram);
                                      $("#valorvendaM").html(json.vendam);
            
                                  } else {
                                      
                                      $("#valorcompra").html('0,00');
                                      $("#valorvenda").html('0,00');
                                       $("#volume").html('0.00');
                                       $("#valorcompraM").html('0.00');
                                        $("#valorvendaM").html('0.00');
                                    }
                                } catch (e) {
                                }
                                initFlag = false;
                         }
                      });
                    }
              }
             // end

        // Caique 26/07/2019 feature/t-33-info-mov-broker        
        var flagParidadesBook = true;
        function listarParidadesBook() {
            
            if (flagParidadesBook) {
                $.ajax({
                    url: '<?php echo URLBASE_CLIENT . \Utils\Rotas::R_BOOK_PARIDADES_LISTAR ?>',
                    dataType: 'json',
                    method: 'post',
                    data: {
                        moeda: $("#ticker-paridade").val()
                    },
                    beforeSend: function () {
                        flagParidadesBook = false;
                    },
                    success: function (json) {
                        try {
                            if (json.sucesso) {
                                $("#body-paridades").html(json.html);

                                $(".change-parity").each(function () {
                                    $(this).click(function () {
                                        var paridade = $(this).parent("tr").attr("data-paridade");
                                        mudarParidade(paridade);
                                    });
                                });

                                filtrarParidadesBook();
                            } else {
                                //console.log(json.mensagem);
                            }
                        } catch (e) {
                            //console.log(e);
                        }
                        flagParidadesBook = true;
                    },
                    complete: function () {
                        flagParidadesBook = true;
                    }
                });
            }
        }

        function mudarParidade(paridade) {
            $.ajax({
                url: '<?php echo URLBASE_CLIENT . \Utils\Rotas::R_CURRENCY ?>',
                dataType: 'json',
                method: 'post',
                data: {
                    codigo: paridade
                },
                beforeSend: function () {

                },
                success: function (json) {
                    try {
                        if (json.sucesso) {

                            location = location.href;

                        } else {
                            
                        }
                    } catch (e) {
                       
                    }

                },
                complete: function () {

                }
            });
        }

         function filtrarParidadesBook() {

                var filtro = $("#ticker-search").val().toLowerCase();
                $("#body-paridades tr").each(function () {
                    var mostrar = true;

                    if (filtro.length > 0) {
                        var name = $(this).children("td.column-paridade").first().attr("data-name").toLowerCase();
                        var content = $(this).children("td.column-paridade").first().html().toLowerCase();

                        var mostrar = (name.indexOf(filtro) !== -1 || content.indexOf(filtro) !== -1);

                    } 

                    if (mostrar && somenteFavoritas) {
                        mostrar = $(this).hasClass("favorite-parity");
                    }

                    if (mostrar) {
                        $(this).show();
                    } else {
                        $(this).hide();
                    }

                });

            }
        //End Caique 26/07/2019 feature/t-33-info-mov-broker    

        function listaDeposito(categoria) {
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_DEPOSITOS_ULTIMOS_DEPOSITOS ?>',
            method: 'post',
            dataType: 'json',
            data:{
                categoria: categoria
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#listaDepositos").html(json.html);
                        $('#tblultimosdepositos').trigger('footable_initialize');
                        $(".carregando").hide();
                    } else {
                        $("#listaDepositos").html("<tr><td colspan='5'>"+json.mensagem+"</td></tr>");
                    }
                } catch (e) {
                    $("#listaDepositos").html("<tr><td colspan='5'>"+e+"</td></tr>");
                }
                
            }
        });
    }
        
        function filtrarBtcAux(){
            dataCoin = "todos";
            filtrarBtc();
        }
        
        function filtrarBtc() {
        $("#listaBtc").html("<tr><td colspan='7' class='text-center'><img src='<?php echo IMAGES ?>loading.gif' /></td></tr>");
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_BTC_CONTA_LANCAMENTOS ?>',
            method: 'post',
            dataType: 'json',
            data: {
                data: dataCoin,
                idCliente: $("#filtroIdCliente").val(),
                tipo: 'E',
                filtro: $("#filtroTextoBtc").val(),
                idMoeda: moeda ,      
                referencia: $("#referencia").is(":checked")
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#listaBtc").html(json.html);
                        $('#tbllistabtc').trigger('footable_initialize');
                    } else {
                        $("#listaBtc").html("<tr><td colspan='7'>"+json.mensagem+"</td></tr>");
                    }
                } catch (e) {
                    $("#listaBtc").html("<tr><td colspan='7'>"+e+"</td></tr>");
                }
                 
            }
        });
    }
    
    function getDadosContaBancaria() {
        if ($("#idContaBancariaEmpresa").val() > 0) {
            $.ajax({
                url: '<?php echo URLBASE_CLIENT  . Utils\Rotas::R_REAIS_DEPOSITOS_DADOSCONTA ?>',
                method: 'post',
                dataType: 'json',
                data: {
                    idContaBancariaEmpresa: $("#idContaBancariaEmpresa").val()
                },
                success: function (json) {
                    try {
                        if (json.sucesso) {
                            
                            if (json.conta.banco.logo !== null) {
                                $("#item-list-logo-banco").show();
                                $("#logo-banco").attr("src", "<?php echo IMAGES ?>bancos/" + json.conta.banco.logo);
                            } else {
                                $("#item-list-logo-banco").hide();
                            }
                            
                            $("#contaNomeBanco").html(json.conta.banco.nome);
                            $("#contaTipo").html(json.conta.tipoConta);
                            $("#contaAgencia").html(json.conta.agencia);
                            $("#contaNumero").html(json.conta.conta);
                            $("#contaTitular").html(json.conta.titular);
                            $("#contaCnpj").html(json.conta.cnpj);
                            $("#alerta-banco-observacoes").html(json.conta.observacoes);
                            
                            if ($("#tipoDeposito").val() === '<?php echo Utils\Constantes::DINHEIRO ?>' && json.conta.observacoes.length > 0) {
                                $("#alerta-banco").show();
                            } else {
                                $("#alerta-banco").hide();
                            }                            
                        } else {
                            showNotyAlert(json.mensagem, "e");
                        }
                    } catch (e) {
                        showNotyAlert(e, "e");
                    }
                }
            });
        }
    }
        
    
        function listar() {            
            $.ajax({
                url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_CARTEIRAS_LISTAR ?>',
                method: 'post',
                dataType: 'json',
                data: {
                    f: $("#filtro").val(), 
                    moeda: $("#filtroMoeda").val(),
                    idCliente: $("#filtroIdCliente").val()
                },
                success: function (json) {
                    try {
                        if (json.sucesso) {
                            $(".carregando").hide();
                            $("#lista").html(json.html);
                        } else {
                            $("#lista").html("<tr ><td class='text-center' colspan='9'>"+json.mensagem+"</td></tr>");
                        }
                    } catch (e) {
                        $("#lista").html("<tr ><td class='text-center' colspan='9'>"+e+"</td></tr>");
                    }
                }
            });
        }
        
        function ativaUltimosDepositos(categoria){
            listaDeposito(categoria);
            $("#depositoMoedas").hide();                                           
            $("#depositoReais").hide(); 
            $("#ultimosDepositos").show(); 
            
        }
        
        function showCoin(codigo, tipo) {
            banco = codigo;
            $.ajax({
                url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_DEPOSITOS_WALLETS_SHOW ?>',
                method: 'post',
                dataType: 'json',
                data: {
                    codigo: codigo, 
                    tipo: tipo
                },
                success: function (json) {
                    try {
                        if (json.sucesso) {                            
                            if (tipo === "b") {
                              if(json.codigo !== '000' && json.codigo !== '1000'){
                                $("#debositoBoleto").hide();
                                $("#depositoMoedas").hide();
                                $("#ultimosDepositos").hide(); 
                                $("#depositoBoleto").hide(); 
                                $("#tabelaAtar").hide();
                                $("#atar").hide();                                
                                $("#depositoBrl").show(); 
                                $("#depositoReais").show(); 
                                $("#infBanco").show();
                                $("#imagemBanco").attr("src", json.logo);
                                $("#idContaBancariaEmpresa").val(banco);
                                $("#contaTipo").html(json.tipoConta);
                                $("#agencia").html(json.agencia);
                                $("#conta").html(json.conta);
                                $("#banco").html(json.banco);
                                $("#titular").html(json.titular);
                                $("#cnpj").html(json.cnpj);
                                $("#alerta-banco-observacoes").html(json.observacoes);
                                } else {    
                                  if(json.codigo === '000'){
                                      depositoBoleto(json);
                                  } else { 
                                      depositoAtar(json);
                                  }
                                  
                                }
                            } else {
                                if(json.valido){
                                    moeda = codigo;  
                                    $("#ultimosDepositos").hide();   
                                    $("#depositoReais").hide();
                                    $("#depositoMoedas").show();
                                    $("#infSemMoeda").hide();
                                    $("#infMoeda").show();
                                    $("#tituloMoeda").html(json.nomeMoeda);
                                    $("#imagemWallet").attr("src", "qrcodes/"+json.endereco+".png");
                                    $("#icone").attr("src", json.icone);
                                    $("#btncopy").html(json.endereco);
                                    $("#naoTaxaDeposito").html(json.naoTaxaDeposito);
                                    $("#envieSomente").html(json.envieSomente); 
                                    limpaSearchBtc();
                                    filtrarBtc();
                                
                                } else {
                                    moeda = codigo; 
                                    $("#ultimosDepositos").hide(); 
                                    $("#depositoReais").hide();
                                    $("#infMoeda").hide();
                                    $("#depositoMoedas").show();                                    
                                    $("#tituloMoeda").html(json.nomeMoeda);
                                    $("#icone").attr("src", json.icone);
                                    $("#infSemMoeda").show();
                                    $("#imagemWallet").attr("src", "");
                                    $("#btncopy").html("");
                                    $("#naoTaxaDeposito").html(json.naoTaxaDeposito);
                                    $("#envieSomente").html(json.envieSomente); 
                                    limpaSearchBtc();
                                    filtrarBtc();
                                }
                            }
                        } else {
                            showNotyAlert(json.mensagem, "e");
                        }
                    } catch (e) {
                            showNotyAlert(json.mensagem, "e");
                    }
                }
            });
        }       
    
    function salvar() {
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_CARTEIRAS_NOVA ?>',
            method: 'post',
            dataType: 'json',
            data: {
                idMoeda: moeda
            },
            success: function (json) {
                try {
                if (json.sucesso) {
                    $("#infSemMoeda").hide();
                    $("#infMoeda").show();
                    showCoin(moeda, 'c');

                } else {
                    showNotyAlert(json.mensagem, "e");
                }
            } catch (e) {
                showNotyAlert(e, "e");
            }
              
            }
        });
    }
        
    function limpaSearchBtc(){    
        $("#filtroTextoBtc").val("");
        $("#diaBtc").removeClass("active");
        $("#mesBtc").removeClass("active");
        $("#todosBtc").removeClass("active");
        $("#semanaBtc").addClass("active");
        $("#semanaBtc").click();
        dataCoin = "semana";
        filtrarBtc();
    }
        
    
    function limpaSearchReal(){ 
        $("#semanaReal").addClass("active");
        $("#filtroIdContaBancariaEmpresa").prop('selectedIndex',0);
        $("#filtroStatus").prop('selectedIndex',0);
        $("#filtroTipoDeposito").prop('selectedIndex',0);
        $("#filtroTextoReal").val("");
        $("#diaReal").removeClass("active");
        $("#mesReal").removeClass("active");
        $("#todosReal").removeClass("active");
        $("#semanaReal").click();        
        dataReal = "semana";
        filtrarReais();
    }
    
    function limpaSearchAtar(){ 
        $("#semanaReal").addClass("active");        
        $("#filtroTextoAtar").val("");
        $("#diaAtar").removeClass("active");
        $("#mesAtar").removeClass("active");
        $("#todosAtar").removeClass("active");
        $("#semanaAtar").click();        
        dataReal = "semana";
        filtrarAtar();
    }
    
    function limpaSearchBoleto(){ 
        $("#semanaReal").addClass("active");
        $("#filtroTextoBoleto").val("");
        $("#diaReal").removeClass("active");
        $("#mesReal").removeClass("active");
        $("#todosReal").removeClass("active");
        $("#semanaReal").click();        
        dataReal = "semana";
        boletoAux();
    }
    
    function calcularValorCreditado() {
        var valor = ($("#valor").val().length > 0 ? parseFloat(toFloat($("#valor").val())) : 0);
        
        var comissao = <?php echo number_format($comissao, 2, ".", "")?>;
        if ($("#tipoDeposito").val() === "<?php echo \Utils\Constantes::DINHEIRO ?>") {
            
            if (valor >= 50000) {
                var comissao = comissaoDinheiro50acima;
            } else if (valor >= 10000) {
                var comissao = comissaoDinheiro10a50;
            } else if (valor >= 5000) {
                var comissao = comissaoDinheiro5a10;
            } else if (valor >= 2000) {
                var comissao = comissaoDinheiro2a5;
            } else {
                var comissao = comissaoDinheiroAte2;
            }
            
        }        
        var resultado = (valor - ((valor * comissao) / 100));

        $("#comissaoCobradaDeposito").html(comissao.toFixed(2).replace(".", ","));
        
        if (resultado <= 0) {
            resultado = 0;
        }
        
        $("#valorCreditado2").html("R$ " + mascaraValor(resultado.toFixed(2)));
    }
    
    
    function calcularValorBoleto() {
        var valor = ($("#valorBoleto").val().length > 0 ? parseFloat(toFloat($("#valorBoleto").val())) : 0);
        
        var tarifaExtra = tarifaBoleto;
        var comissao = <?php echo number_format($comissaoBoleto, 2, ".", "")?>;
        
        var resultado = (valor - tarifaExtra - ((valor * comissao / 100)));
        $("#comissaoCobradaBoleto").html("R$ "+ tarifaBoleto.toFixed(2).replace(".", ",") + " + "+comissao.toFixed(2).replace(".", ","));
        
        if (resultado <= 0) {
            resultado = 0;
        }
        
        $("#valorCreditadoBoleto").html("R$ " + mascaraValor(resultado.toFixed(2)));
    }
    
    
    function modalGerarBoleto(deposito) {
       $("#modalGerarBoletoDeposito").val(deposito);
       $("#modalGerarBoleto").modal();
    }
    
    function cancelarBoleto() {
        $("#boletoGerado").hide();
        $("#telaBoleto").hide();
        $("#tokenBoleto").hide();
        $("#telaBoleto").show();
        $("#btnGerarBoleto").prop("disabled", false); 
        $("#valorBoleto").val("0,00"); 
    }
    
    function tokenBoleto() {
        $("#btnGerarBoleto").prop("disabled", true); 
        $("#boletoGerado").hide();
        $("#telaBoleto").hide();
        $("#tokenBoleto").hide();
        $("#carregaBoleto").show();
        $("#carregaBoleto").html("<img src='<?php echo IMAGES ?>loading.gif' />");
        $("#pinBoleto").val("");
        $("#tokenBoletoDigito").val("");
        $.ajax({
        url: "<?php echo URLBASE_CLIENT  . Utils\Rotas::R_DEPOSITO_BOLETO_TOKEN  ?>",
        method: "post",
        dataType: "json",
        data: {            
            valor: $("#valorBoleto").val()
        },
        success: function (json) {
            try {
                if (json.sucesso) {
                    $("#carregaBoleto").hide();
                    $("#tokenBoleto").show();
                    $("#valorCreditarBoleto").html(json.creditarBoleto);
                    $("#valorTotalBoleto").html(json.totalBoleto);                  
                    showNotyAlert(json.mensagem, "s");                  
                } else {
                    showNotyAlert(json.mensagem, "e");
                    $("#carregaBoleto").hide();
                    $("#tokenBoleto").hide();
                    $("#telaBoleto").show();
                    $("#btnGerarBoleto").prop("disabled", false);                     
                }
            } catch (e) {
                showNotyAlert(e, "e");
                $("#btnGerarBoleto").prop("disabled", false);                 
            }
            
            }
        });
    }
    
 
    function salvarDepositoBoleto() {
        $("#btnGerarBoleto").prop("disabled", true); 
        $("#boletoGerado").hide();
        $("#tokenBoleto").hide();
        $.ajax({
        url: "<?php echo URLBASE_CLIENT  . Utils\Rotas::R_REAIS_DEPOSITOS_SALVAR  ?>",
        method: "post",
        dataType: "json",
        data: {
            tipoDeposito: '<?php echo \Utils\Constantes:: GERENCIA_NET ?>',
            valor: $("#valorBoleto").val()
        },
        success: function (json) {
            try {
                if (json.sucesso) {
                    gerarBoleto(json.deposito);                   
                } else {
                    showNotyAlert(json.mensagem, "e");
                    $("#btnGerarBoleto").prop("disabled", false);                     
                }
            } catch (e) {
                showNotyAlert(e, "e");
                $("#btnGerarBoleto").prop("disabled", false);                 
            }
            
            }
        });
        
    }


    function gerarBoleto(deposito) {  
        $("#telaBoleto").hide();
        $("#tokenBoleto").hide();
        $("#carregaBoleto").show();
        $("#carregaBoleto").html("<img src='<?php echo IMAGES ?>loading.gif' />");
        $.ajax({
            url: "<?php echo URLBASE_CLIENT  . Utils\Rotas::R_DEPOSITO_BOLETO_GERAR ?>",
            method: "post",
            dataType: "json",
            data: {
                deposito: deposito,
                pin: $("#pinBoleto").val(),
                token: $("#tokenBoletoDigito").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#carregaBoleto").hide();
                        $("#boletoGerado").show();
                        $("#codigoBarrasDigito").html(json.barras);
                        $("#modalBoletoGeradoVencimento").html(json.vencimento);
                        $("#modalBoletoGeradoValor").html(json.valor);
                        $("#modalBoletoValorCreditar").html(json.valorCreditar);
                        $("#modalBoletoComissao").html(json.comissao);
                        $("#modalBoletoTaxa").html(json.taxa);
                        $("#modalBoletoGeradoLink").attr("href",  json.link);
                        $("#modalBoletoGeradoImgBarcode").html(json.img);                      

                    } else {
                        $("#carregaBoleto").hide();
                        $("#telaBoleto").show();
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    $("#carregaBoleto").hide();
                    $("#telaBoleto").show();
                    showNotyAlert(e, "e");
                }
                $("#btnGerarBoleto").prop("disabled", false);
                $("#carregaBoleto").hide();
                boletoAux();
            }
        });
    }
    
    function filtrarReaisAux(){
        dataReal = "todos";
        filtrarReais();
    }
    
    function filtrarAtarAux(){
        dataAtar = "todos";
        filtrarAtar();
    }
    
    function boletoAux(){
       boleto = true;
       filtrarReais();       
    }
    
    function filtrarReais() {         
        var boletoAux = boleto;
        var status = "";
        var search = "";
        if(boleto){
            $("#tabelaReais").hide();
            $("#tabelaBoleto").show();   
            $("#listaBoleto").html("<tr><td colspan='13' class='text-center'><img src='<?php echo IMAGES ?>loading.gif' /></td></tr>");
            status = $("#filtroStatusBoleto").val();
            search = $("#filtroTextoBoleto").val();
        } else {            
            $("#tabelaBoleto").hide();
            $("#tabelaReais").show();
            status = $("#filtroStatus").val();
            search = $("#filtroTextoReal").val(),
            $("#listaReais").html("<tr><td colspan='12' class='text-center'><img src='<?php echo IMAGES ?>loading.gif' /></td></tr>");
        }


        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_REAIS_DEPOSITOS_LISTAR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                data: dataReal,
                idContaBancariaEmpresa: $("#filtroIdContaBancariaEmpresa").val(),
                status: status,
                tipoDeposito: $("#filtroTipoDeposito").val(),
                filtro: search,
                boleto: boleto
            },
            success: function (json) {                 
                try {
                    if (json.sucesso) {                       
                        if(boletoAux){                           
                            $("#listaBoleto").html(json.html);
                            
                                $(".boleto-codigo").each(function () {
                                let codigoBarras = $(this).attr("data-motivo");                            
                                $(this).popover({
                                    html: true,
                                    trigger: "focus",
                                    container: "body",
                                    placement: "top",
                                    title: "Boleto - Código de Barras",
                                    content: codigoBarras
                                });
                            });
                            $('#tblListaBoleto').trigger('footable_initialize');
                        } else {
                            $("#listaReais").html(json.html);
                            
                                $(".btn-popover-deposito").each(function () {
                                    let controle = $(this).attr("data-controle");
                                    $(this).popover({
                                    html: true,
                                    trigger: "focus",
                                    container: "body",
                                    placement: "top",
                                    title: "<?php echo $idioma->getText("depositoJs")?>" + controle,
                                    content: json.popover[controle]
                                });
                            });
                        
                            $(".deposito-motivo").each(function () {
                                let motivo = $(this).attr("data-motivo");
                                let controle = $(this).attr("data-controle");
                                $(this).popover({
                                    html: true,
                                    trigger: "focus",
                                    container: "body",
                                    placement: "top",
                                    title: "<?php echo $idioma->getText("depositoJs")?>" + controle,
                                    content: motivo
                                });
                            });
                            $('#tbllistareais').trigger('footable_initialize');
                        }
                        
                    } else {
                        if(!boletoAux){
                            $("#listaReais").html("<tr><td colspan='12' class='text-center'>"+json.mensagem+"</td></tr>");
                        } else {
                            $("#listaBoleto").html("<tr><td colspan='13' class='text-center'>"+json.mensagem+"</td></tr>");
                        }
                    }
                } catch (e) {
                    $("#listaReais").html("<tr><td colspan='12' class='text-center'>"+e+"</td></tr>");
                    $("#listaBoleto").html("<tr><td colspan='13' class='text-center'>"+e+"</td></tr>");
                }
            }
        });
        boleto = false;
    }
    
    function limparCampos(){
        $("#comprovante").val("");
        $("#tipoDeposito").val(1);
        $("#valor").val("0,00");
        $("#valorBoleto").val("0,00");
        $("#valorAtar").val("");
        $("#idAtar").val("");        
        $("#pinAtar").val("");        
        $("#labelIdAtar").html("");        
        $("#idContaBancariaEmpresa").val(banco);
        
    }

    function depositoBoleto(json) {
        limparCampos();
        $("#valorCreditadoBoleto").html("R$ 0,00");        
        $("#depositoMoedas").hide();
        $("#ultimosDepositos").hide(); 
        $("#depositoBrl").hide();
        $("#atar").hide();
        $("#depositoReais").show();   
        $("#depositoBoleto").show();
        $("#tabelaAtar").hide();
        $("#telaBoleto").show();
        $("#boletoGerado").hide();
        $("#imagemBanco").attr("src", json.logo);
    }
    
    function depositoAtar(json) {

        limparCampos();
        $("#depositoMoedas").hide();
        $("#ultimosDepositos").hide(); 
        $("#depositoBrl").hide();
        $("#depositoBoleto").hide();
        $("#boletoGerado").hide();
        $("#tabelaReais").hide();
        $("#token2faAtar").hide();
        $("#infBanco").hide();
        $("#depositoReais").show();   
        $("#atar").show();
        $("#tabelaAtar").show();
        $("#cadastroAtar").show();
        $("#btncopyAtar").html(json.idAtarEmpresa);
        
        taxaAtar = parseFloat(json.taxaAtar);
        tarifaAtar = parseFloat(json.tarifaAtar);
        
        $("#comissaoAtar").html(json.taxaAtar.replace(".",","));
        $("#tarifaAtar").html("R$ " + json.tarifaAtar.replace(".",","));
        
        $("#imagemBanco").attr("src", json.logo);
        $("#qrcodeCointrade").attr("src", "qrcodes/"+json.idAtarEmpresa+".png");
        
    }
    
    function limparAtar() {
        limparCampos();
        $("#depositoMoedas").hide();
        $("#ultimosDepositos").hide(); 
        $("#depositoBrl").hide();
        $("#depositoBoleto").hide();
        $("#boletoGerado").hide();
        $("#tabelaReais").hide();
        $("#token2faAtar").hide();
        $("#depositoReais").show();   
        $("#atar").show();
        $("#tabelaAtar").show();
        $("#cadastroAtar").show();
        
    }
    
    <?php if($configuracao->atarAtivo == 1){ ?>
    function filtrarAtar() {            
            $.ajax({
                url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_ATAR_DEP_LISTAR ?>',
                method: 'post',
                dataType: 'json',
                data: {
                    data: dataAtar, 
                    filtro: $("#filtroTextoAtar").val()
                },
                success: function (json) {
                    try {
                        if (json.sucesso) {
                            $(".carregando").hide();
                            $("#listaAtar").html(json.html);
                            $('#tbllistaAtar').trigger('footable_initialize');
                        } else {
                            $("#listaAtar").html("<tr ><td class='text-center' colspan='7'>"+json.mensagem+"</td></tr>");
                        }
                    } catch (e) {
                        $("#listaAtar").html("<tr ><td class='text-center' colspan='7'>"+e+"</td></tr>");
                    }
                }
            });
        }
        
    function depositarAtar() {   
            $("#btnCadastrarConta").prop("disabled", true);
            $.ajax({
                url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_ATAR_DEP_SALVAR ?>',
                method: 'post',
                dataType: 'json',
                data: {
                    idAtar: $("#labelIdAtar").html(),                    
                    pin: $("#pinAtar").val()
                },
                beforeSend: function(){
                    $('#btnCadastrarConta').html('<i class="fa fa-spinner fa-pulse fa-fw"></i>');
                },
                success: function (json) {
                    try {
                        if (json.sucesso) {
                            $("#cadastroAtar").hide();
                            $("#token2faAtar").hide();
                            limparCampos();
                            showNotyAlert(json.mensagem, "s");
                            location.reload();                           
                        } else {
                            showNotyAlert(json.mensagem, "e");
                        }
                    } catch (e) {
                       showNotyAlert(json.mensagem, "e");
                    }
                    $('#btnCadastrarConta').html('Cadastrar');
                    $("#btnCadastrarConta").prop("disabled", false);
                }
            });
            
        }
        
        function tokenAtar() {    
            $('#btnTokenAtar').html('<i class="fa fa-spinner fa-pulse fa-fw"></i>');
            $("#btnTokenAtar").prop("disabled", true);
            $.ajax({
                url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_ATAR_DEP_TOKEN ?>',
                method: 'post',
                dataType: 'json',
                data: {
                    idAtar: $("#idAtar").val()
                    
                },
                beforeSend: function(){
                    $('#btnTokenAtar').html('<i class="fa fa-spinner fa-pulse fa-fw"></i>');
                },
                success: function (json) {
                    try {
                        if (json.sucesso) {
                            limparCampos();
                            $("#cadastroAtar").hide();
                            $("#labelIdAtar").html(json.idAtar);                            
                           
                            $("#token2faAtar").show();
                                                        
                        } else {
                            showNotyAlert(json.mensagem, "e");
                        }
                    } catch (e) {
                       showNotyAlert(json.mensagem, "e");
                    }
                    $("#btnTokenAtar").html("Cadastrar Conta Atar");    
                    $("#btnTokenAtar").prop("disabled", false);
                }
                
            });
        }
        
    function calcularValorAtar() {
        var valor = ($("#valorAtar").val().length > 0 ? parseFloat(toFloat($("#valorAtar").val())) : 0);
        var tarAtar = parseFloat(tarifaAtar);
        var taxAtar = parseFloat(taxaAtar);
        
        var resultado = valor - (valor * (taxAtar / 100)) - tarAtar;
        
        if (resultado <= 0) {
            resultado = 0;
        }
        
        $("#valorCreditadoAtar").html("R$ " + mascaraValor(resultado.toFixed(2)));
    }
        
    <?php } ?>
    
    function loadCheckBox(){   
        var elems = Array.prototype.slice.call(document.querySelectorAll('.js-switch'));
        elems.forEach(function(html) {
          var switchery = new Switchery(html, {
                color: '#1ab394', size: 'small', disabledOpacity: 0.3
                });
        });
    }

    
    </script>
    <?php Utils\Layout::append("inspina/footer_esp", $_data) ?>
    </body>
</html>

