
	<?php Utils\Layout::append("inspina/metas", $_data) ?>
	<?php Utils\Layout::append("inspina/scripts", $_data) ?>
	<?php Utils\Layout::append("inspina/menu", $_data) ?>




<div class="wrapper wrapper-content">


<div class="row">
	<div class="col-md-12">
		<div class="panel panel-primary" >
			<div class="panel-heading" >
				<h4 class="panel-title">
					<?php echo $_data["item"]["idioma"]->getText("moedaSimbolo") ?> <label id="lbitcoin"></label>
					<div class="pull-right">
						<a href="#" data-perform="panel-dismiss" class="btn btn-primary btn-xs pull-right"><i class="fa fa-times"></i></a>
						<a href="#" data-perform="panel-collapse" class="btn btn-primary btn-xs pull-right"><i class="fa fa-minus"></i></a>
					</div>
				</h4>
			</div>

			<div class="panel-wrapper collapse in">
				<div class="panel-body" >
					<div class="row col-lg-2" >
			            <a class="currency-div ">
			                <button class="btn btn-warning" type="button" style="margin-top:22px" >
			                <i class="fa fa-line-chart fa-1x"></i> <?php echo $_data["item"]["idioma"]->getText("paridade:") ?>  
			                </button>
			            </a>
   					</div>    

					    <div class="row date-div" >
					        <div class='col-sm-2' >
					          <label><?php echo $_data["item"]["idioma"]->getText("dataInicial") ?>   </label>  <input type='text' class="form-control" id='datetimepicker1' />
					        </div>
					         <div class='col-sm-2'>
					          <label><?php echo $_data["item"]["idioma"]->getText("dataFinal") ?>  </label>  <input type='text' class="form-control" id='datetimepicker2' />
					        </div>
					        <div class="col-sm-4">
					            <a class="filter-div ">
					                <button class="btn btn-success btn-filter" type="button" style="margin-top:22px" >
					                <i class="fa fa-filter fa-1x"></i> <?php echo $_data["item"]["idioma"]->getText("filtro:") ?>  
					                </button>
					            </a>					        	
					        </div>

					    </div>

				</div>
			</div>
		</div>
	</div>




	<div class="row">
		
	</div>

          <div id="div-cripto"  style="margin-left: 15px;margin-top:20px;display: none" >
            <div class="sidebar-container">
                <ul class="nav nav-tabs" style="width: 240px;">

                    <li class="<?php echo ($_data["item"]["paridade"]->idMoedaTrade == 1 ? "active" : "") ?> tp1" data-value="<?php echo $_data["item"]["paridade"]->idMoedaTrade; ?>" style="width: 60px;">
                        <a data-toggle="tab" href="#top-currencies-pricing-1">
                            <img src="<?php echo IMAGES ?>currencies/BRL.png" style="width: 25px; height: 25px;" />
                        </a>
                    </li>
                    <li class="<?php echo ($_data["item"]["paridade"]->idMoedaTrade == 2 ? "active" : "") ?> tp2" data-value="<?php echo $_data["item"]["paridade"]->idMoedaTrade; ?>" style="width: 60px;">
                        <a data-toggle="tab" href="#top-currencies-pricing-2">
                            <img src="<?php echo IMAGES ?>currencies/BTC.png" style="width: 25px; height: 25px;" />
                        </a>
                    </li>
                    <li class="<?php echo ($_data["item"]["paridade"]->idMoedaTrade == 13 ? "active" : "") ?> tp3" data-value="<?php echo $_data["item"]["paridade"]->idMoedaTrade; ?>" style="width: 60px;">
                        <a data-toggle="tab" href="#top-currencies-pricing-13">
                            <img src="<?php echo IMAGES ?>currencies/TUSD.png" style="width: 25px; height: 25px;" />
                        </a>
                    </li>
                    <li class="<?php echo ($_data["item"]["paridade"]->idMoedaTrade == 17 ? "active" : "") ?> tp4" data-value="<?php echo $_data["item"]["paridade"]->idMoedaTrade; ?>" style="width: 60px;">
                        <a data-toggle="tab" href="#top-currencies-pricing-17">
                            <img src="<?php echo IMAGES ?>currencies/USDT.png" style="width: 25px; height: 25px;" />
                        </a>
                    </li>
                    <li class="<?php echo ($_data["item"]["paridade"]->idMoedaTrade == 3 ? "active" : "") ?> tp5"  data-value="<?php echo $_data["item"]["paridade"]->idMoedaTrade; ?>" style="width: 60px;">
                        
                    </li>
                    <li class="<?php echo ($_data["item"]["paridade"]->idMoedaTrade == 35 ? "active" : "") ?> tp6" data-value="<?php echo $_data["item"]["paridade"]->idMoedaTrade; ?>" style="width: 60px;">
                        
                    </li>
                    
                </ul>

                <div class="tab-content">
                    <div id="top-currencies-pricing-1" class="tab-pane <?php echo ($_data["item"]["paridade"]->idMoedaTrade == 1 ? "active" : "") ?> anchor-currencytrade"   data-value="1">
                        
                        <div>
                            <?php
                            	

                            foreach ($_data["item"]["paridadesReal"]  as $paridadeReal) {

                            ?>
                            <div class="sidebar-message">
                                <a class="anchor-parity" data-item="<?php echo $paridadeReal->idMoedaBook ?>" data-value="1" data-symbol="<?php echo $paridadeReal->symbol ?>">
                                    <div class="pull-left text-center">
                                        <img alt="<?php echo $paridadeReal->moedaBook->nome ?>" class="img-circle message-avatar" src="<?php echo IMAGES ?>currencies/<?php echo $paridadeReal->moedaBook->icone ?>">
                                    </div>
                                    <div class="media-body">
                                        
                                        <?php echo $_data["item"]["idioma"]->getText("compra:") ?>  <span id="top-currency-pricing-buy-<?php echo $paridadeReal->id ?>"></span> <?php echo $paridadeReal->moedaTrade->simbolo ?>
                                        
                                        <br>
                                        <?php echo $_data["item"]["idioma"]->getText("venda:") ?>  <span id="top-currency-pricing-sell-<?php echo $paridadeReal->id ?>"></span> <?php echo $paridadeReal->moedaTrade->simbolo ?>
                                        
                                        <br>
                                        <?php echo $_data["item"]["idioma"]->getText("volume") ?>  <span id="top-currency-pricing-volume-<?php echo $paridadeReal->id ?>"></span> <?php echo $paridadeReal->moedaBook->simbolo ?>
                                        
                                        <br>
                                    </div>
                                </a>
                            </div>
                            
                            <?php 
                            }
                            ?>
                        </div>

                    </div>

                    <div id="top-currencies-pricing-2" class="tab-pane <?php echo ($_data["item"]["paridade"]->idMoedaTrade  == 2 ? "active" : "") ?> anchor-currencytrade"   data-value="2" >

                        <div>
                            <?php
                            foreach ($_data["item"]["paridadesBitcoin"] as $paridadeBitcoin) {
                            ?>
                            <div class="sidebar-message">
                                <a data-item="<?php echo $paridadeBitcoin->idMoedaBook  ?>" class="anchor-parity" data-value="2" data-symbol="<?php echo $paridadeBitcoin->symbol ?>">
                                    <div class="pull-left text-center">
                                        <img alt="<?php echo $paridadeBitcoin->moedaBook->nome ?>" class="img-circle message-avatar" src="<?php echo IMAGES ?>currencies/<?php echo $paridadeBitcoin->moedaBook->icone ?>">
                                    </div>
                                    <div class="media-body">
                                        <?php echo $_data["item"]["idioma"]->getText("compra:") ?> <span id="top-currency-pricing-buy-<?php echo $paridadeBitcoin->id ?>"></span> <?php echo $paridadeBitcoin->moedaTrade->simbolo ?>
                                        <br>
                                        <?php echo $_data["item"]["idioma"]->getText("venda:") ?> <span id="top-currency-pricing-sell-<?php echo $paridadeBitcoin->id ?>"></span> <?php echo $paridadeBitcoin->moedaTrade->simbolo ?>
                                        <br>
                                        <?php echo $_data["item"]["idioma"]->getText("volume") ?> <span id="top-currency-pricing-volume-<?php echo $paridadeBitcoin->id ?>"></span> <?php echo $paridadeBitcoin->moedaBook->simbolo ?>
                                        <br>
                                    </div>
                                </a>
                            </div>
                            
                            <?php 
                            }
                            ?>
                        </div>

                    </div>

                    <div id="top-currencies-pricing-3" class="tab-pane <?php echo ($_data["item"]["paridade"]->idMoedaTrade == 4 ? "active" : "") ?> anchor-currencytrade"   data-value="4" >
                        <div>
                            <?php
                            foreach ($_data["item"]["paridadesLitecoin"] as $paridadeLitecoin) {
                            ?>
                            <div class="sidebar-message">
                                <a class="anchor-parity" data-value="4"  data-item="<?php echo  $paridadeLitecoin->idMoedaBook  ?>" data-symbol="<?php echo $paridadeLitecoin->symbol ?>">
                                    <div class="pull-left text-center">
                                        <img alt="<?php echo $paridadeLitecoin->moedaBook->nome ?>" class="img-circle message-avatar" src="<?php echo IMAGES ?>currencies/<?php echo $paridadeLitecoin->moedaBook->icone ?>" >
                                    </div>
                                    <div class="media-body">
                                        <?php echo $_data["item"]["idioma"]->getText("compra:") ?>  <span id="top-currency-pricing-buy-<?php echo $paridadeLitecoin->id ?>"></span> <?php echo $paridadeLitecoin->moedaTrade->simbolo ?>
                                        <br>
                                        <?php echo $_data["item"]["idioma"]->getText("venda:") ?>  <span id="top-currency-pricing-sell-<?php echo $paridadeLitecoin->id ?>"></span> <?php echo $paridadeLitecoin->moedaTrade->simbolo ?>
                                        <br>
                                        <?php echo $_data["item"]["idioma"]->getText("volume") ?>  <span id="top-currency-pricing-volume-<?php echo $paridadeLitecoin->id ?>"></span> <?php echo $paridadeLitecoin->moedaBook->simbolo ?>
                                        <br>
                                    </div>
                                </a>
                            </div>
                            
                            <?php 
                            }
                            ?>
                        </div>
                    </div>
                    
                    <div id="top-currencies-pricing-4" class="tab-pane <?php echo ($_data["item"]["paridade"]->idMoedaTrade  == 5 ? "active" : "") ?> anchor-currencytrade"   data-value="5"  >
                        <div>
                            <?php
                            foreach ($_data["item"]["paridadesDash"] as $paridadeDash) {
                            ?>
                            <div class="sidebar-message">
                                <a class="anchor-parity" data-value="5"  data-item="<?php echo $paridadeDash->idMoedaBook ?>" data-symbol="<?php echo $paridadeDash->symbol ?>" > 
                                    <div class="pull-left text-center">
                                        <img alt="<?php echo $paridadeDash->moedaBook->nome ?>" class="img-circle message-avatar" src="<?php echo IMAGES ?>currencies/<?php echo $paridadeDash->moedaBook->icone ?>">
                                    </div>
                                    <div class="media-body">
                                        <?php echo $_data["item"]["idioma"]->getText("compra:") ?>  <span id="top-currency-pricing-buy-<?php echo $paridadeDash->id ?>"></span> <?php echo $paridadeDash->moedaTrade->simbolo ?>
                                        <br>
                                        <?php echo $_data["item"]["idioma"]->getText("venda:") ?>  <span id="top-currency-pricing-sell-<?php echo $paridadeDash->id ?>"></span> <?php echo $paridadeDash->moedaTrade->simbolo ?>
                                        <br>
                                        <?php echo $_data["item"]["idioma"]->getText("volume") ?>  <span id="top-currency-pricing-volume-<?php echo $paridadeDash->id ?>"></span> <?php echo $paridadeDash->moedaBook->simbolo ?>
                                        <br>
                                    </div>
                                </a>
                            </div>
                            
                            <?php 
                            }
                            ?>
                        </div>
                    </div>                   
                    
                    <div id="top-currencies-pricing-5" class="tab-pane <?php echo ($_data["item"]["paridade"]->idMoedaTrade  == 7 ? "active" : "") ?> anchor-currencytrade"    data-value="7" >
                        <div>
                            <?php
                            foreach ($_data["item"]["paridadesDoge"] as $paridadeDoge) {
                            ?>
                            <div class="sidebar-message">
                                <a class="anchor-parity" data-value="7"  data-item="<?php echo $paridadeDoge->idMoedaBook  ?>" data-symbol="<?php echo $paridadeDoge->symbol ?>" >
                                    <div class="pull-left text-center">
                                        <img alt="<?php echo $paridadeDoge->moedaBook->nome ?>" class="img-circle message-avatar" src="<?php echo IMAGES ?>currencies/<?php echo $paridadeDoge->moedaBook->icone ?>">
                                    </div>
                                    <div class="media-body">
                                        <?php echo $_data["item"]["idioma"]->getText("compra:") ?>  <span id="top-currency-pricing-buy-<?php echo $paridadeDoge->id ?>"></span> <?php echo $paridadeDoge->moedaTrade->simbolo ?>
                                        <br>
                                        <?php echo $_data["item"]["idioma"]->getText("venda:") ?> <span id="top-currency-pricing-sell-<?php echo $paridadeDoge->id ?>"></span> <?php echo $paridadeDoge->moedaTrade->simbolo ?>
                                        <br>
                                        <?php echo $_data["item"]["idioma"]->getText("volume") ?>  <span id="top-currency-pricing-volume-<?php echo $paridadeDoge->id ?>"></span> <?php echo $paridadeDoge->moedaBook->simbolo ?>
                                        <br>
                                    </div>
                                </a>
                            </div>                            
                            <?php 
                            }
                            ?>
                        </div>
                    </div>
                    
                    
                    
                    <div id="top-currencies-pricing-13" class="tab-pane <?php echo ($_data["item"]["paridade"]->idMoedaTrade  == 13 ? "active" : "") ?> anchor-currencytrade"    data-value="13" >
                        <div>
                            <?php
                            foreach ($_data["item"]["paridadesTusd"] as $paridadeTusd) {
                            ?>
                            <div class="sidebar-message">
                                <a class="anchor-parity" data-value="13"  data-item="<?php echo $paridadeTusd->idMoedaBook ?>" data-symbol="<?php echo $paridadeTusd->symbol ?>" > 
                                    <div class="pull-left text-center">
                                        <img alt="<?php echo isset($paridadeTusd->moedaBook->nome) ?>" class="img-circle message-avatar" src="<?php echo IMAGES ?>currencies/<?php echo isset($paridadeTusd->moedaBook->icone) ?>">
                                    </div>
                                    <div class="media-body">
                                        <?php echo $_data["item"]["idioma"]->getText("compra:") ?>  <span id="top-currency-pricing-buy-<?php echo $paridadeTusd->id ?>"></span> <?php echo $paridadeTusd->moedaTrade->simbolo ?>
                                        <br>
                                        <?php echo $_data["item"]["idioma"]->getText("venda:") ?> <span id="top-currency-pricing-sell-<?php echo $paridadeTusd->id ?>"></span> <?php echo $paridadeTusd->moedaTrade->simbolo ?>
                                        <br>
                                        <?php echo $_data["item"]["idioma"]->getText("volume") ?>  <span id="top-currency-pricing-volume-<?php echo $paridadeTusd->id ?>"></span> <?php echo $paridadeTusd->moedaBook->simbolo ?>
                                        <br>
                                    </div>
                                </a>
                            </div>                            
                            <?php 
                            }
                            ?>
                        </div>
                    </div>
                    
                    <div id="top-currencies-pricing-17" class="tab-pane <?php echo ($_data["item"]["paridade"]->idMoedaTrade == 17 ? "active" : "") ?> anchor-currencytrade"   data-value="17">
                        <div>
                            <?php
                            foreach ($_data["item"]["paridadesUsdt"] as $paridadeUsdt) {
                            ?>
                            <div class="sidebar-message">
                                <a  class="anchor-parity" data-value="17"  data-item="<?php echo $paridadeUsdt->idMoedaBook  ?>" ata-symbol="<?php echo $paridadeUsdt->symbol ?>" >
                                    <div class="pull-left text-center">
                                        <img alt="<?php echo $paridadeUsdt->moedaBook->nome ?>" class="img-circle message-avatar" src="<?php echo IMAGES ?>currencies/<?php echo $paridadeUsdt->moedaBook->icone ?>"  >
                                    </div>
                                    <div class="media-body">
                                        <?php echo $_data["item"]["idioma"]->getText("compra:") ?>  <span id="top-currency-pricing-buy-<?php echo $paridadeUsdt->id ?>"></span> <?php echo $paridadeUsdt->moedaTrade->simbolo ?>
                                        <br>
                                        <?php echo $_data["item"]["idioma"]->getText("venda:") ?> <span id="top-currency-pricing-sell-<?php echo $paridadeUsdt->id ?>"></span> <?php echo $paridadeUsdt->moedaTrade->simbolo ?>
                                        <br>
                                        <?php echo $_data["item"]["idioma"]->getText("volume") ?>  <span id="top-currency-pricing-volume-<?php echo $paridadeUsdt->id ?>"></span> <?php echo $paridadeUsdt->moedaBook->simbolo ?>
                                        <br>
                                    </div>
                                </a>
                            </div>                            
                            <?php 
                            }
                            ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>	





	<div class="row">
		<div class="col-md-12" style="margin-left: 15px;width: 98.5%">
			<div class="panel panel-primary" >
				<div class="panel-heading" >
					<h4 class="panel-title">
						<?php echo $_data["item"]["idioma"]->getText("resultado") ?> 
						<div class="pull-right">
							<a href="#" data-perform="panel-dismiss" class="btn btn-primary btn-xs pull-right"><i class="fa fa-times"></i></a>
							<a href="#" data-perform="panel-collapse" class="btn btn-primary btn-xs pull-right"><i class="fa fa-minus"></i></a>
						</div>
					</h4>
				</div>

				<div class="panel-wrapper collapse in">
					<div class="panel-body" >

					    <div class="row hidden div-datatable" style="margin-left: 15px;margin-right: 15px">
							<table id="MyTable" class="display" cellspacing="0" width="90%">  
							        <thead>  
							            <tr> 
							                <!--<th class="hidden">#id</th> -->
							                <th>Ranking</th>  
							                <th>%</th>  
							                <th>Nome</th>  
							            </tr>  
							        </thead>  
							        <tfoot>  
							            <tr>  
							                <th>Name</th>  

							            </tr>  
							        </tfoot id="tfoot-div">  
							        <tbody id="tbody-follow">  



							        </tbody>  
							    </table>

							 

					    </div>   

					     <label id="label-message" style="display: none"></label>  

					</div>
				</div>
			</div>
		</div>




        <br><hr>

         

	</div>	

<script >
		
var tabla;		
// created André 23/07/2019
$(document).ready(function () {

 
   	
   //active datepicker	FORMAT
   $('#datetimepicker1').datepicker({
            format: "dd/mm/yyyy",
            language: "pt-BR",
            autoclose: true
      });


   $('#datetimepicker2').datepicker({
            format: "dd/mm/yyyy",
            language: "pt-BR",
            autoclose: true
      });

   	//get date actual between 01 and 30-31
	var date = new Date();
	var primeiroDia = new Date(date.getFullYear(), date.getMonth(), 1);
	var ultimoDia = new Date(date.getFullYear(), date.getMonth() + 1, 0);

	//insert date picker view
	$('#datetimepicker1').datepicker("setDate",primeiroDia);
	$('#datetimepicker2').datepicker("setDate",ultimoDia);

	//create data table
	tabla =  $('#MyTable').DataTable( {  
	        initComplete: function () {  
	            this.api().columns().every( function () {  
	                var column = this;  
	                var select = $('<select><option value=""></option></select>')  
	                    .appendTo( $(column.footer()).empty() )  
	                    .on( 'change', function () {  
	                        var val = $.fn.dataTable.util.escapeRegex(  
	                            $(this).val()  
	                        );  
	                //to select and search from grid  
	                        column  
	                            .search( val ? '^'+val+'$' : '', true, false )  
	                            .draw();  
	                    } );  
	   
	                column.data().unique().sort().each( function ( d, j ) {  
	                    select.append( '<option value="'+d+'">'+d+'</option>' )  
	                } );  
	            } );  
	        }  
	    } );

	//initialize date default open view
	initialize(primeiroDia,ultimoDia);
	$("#lbitcoin").text("BTC:BRL");
	//end initialize


   //choose currency parity
   $('.currency-div').on('click' ,function(){
   		$('#div-cripto').toggle();
   		//$('.btn-filter').css('display','none');
   		//$('.date-div').css('display','none');
   		//var ctdt = tabla.rows().count();

   		//clear datatable
   		tabla.rows().remove().draw();
   		$('#label-message').hide();

   })


     //get value click table
	$('#MyTable tbody').on( 'click', 'tr', function () {
	    console.log( tabla.row( this ).data() );
	} );


   var currency;
   var parity;

   //button parity click and get values currency
   $('.anchor-parity').on('click',function(){

   		//console.log('id-moeda:', $(this).data('item'),'- id-paridade: ',$(this).data('value'),'- simbolo: ',$(this).data('symbol'));

   		//label top symbol view
   		$("#lbitcoin").text($(this).data('symbol'));

   		currency = $(this).data('item');
   		parity   = $(this).data('value');



   		$('#div-cripto').toggle();
   		//$('.btn-filter').toggle();
   		//$('.date-div').toggle();  		


   })

  
    //execute filter 
   	$(document).on('click', '.btn-filter', function() {

        console.log(parity,currency);
        if(typeof currency === "undefined" && typeof parity === "undefined"){
              parity   = 1;
              currency = 2;
        }

		//clear datatable
		tabla.rows().remove().draw();

   		console.log(currency,parity,$('#datetimepicker1').val(),$('#datetimepicker2').val())

   		

		$.ajax({
		            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_CLIENTES_FOLLOW_FILTER ?>',
		            method: 'post',
		            dataType: 'json',
		            data: {currency:currency,parity:parity,date1: $('#datetimepicker1').val() ,date2: $('#datetimepicker2').val()},
		            success: function (data) {

				            	console.log(data)		              

		            	if(data.success){

		            			var rows;
		            			var percent ;
		            			var i = 1;

			                 	$.each(data["response"], function (j, item) {
							     	

								   	rows = rows + "<tr >";
								   			rows = rows + "<td class='hide tdid"+item.id_comprador+"' data-id='"+item.id_comprador +"'>"+item.id_comprador+"</td>";
										   	rows = rows + "<td class='tdranking"+i+"' data-value='"+i +"'>"+i+"</td>";
											rows = rows + "<td class='tdpercent"+i+"' data-value='"+parseFloat(item.percent).toFixed(2) +"'>"+parseFloat(item.percent).toFixed(2)+"</td>";
											rows = rows + "<td class='tdname"+i+"' data-value='"+item.nome +"'>"+item.nome+"</td>";
											rows = rows + "</tr>";

											tabla.row.add( 
							                [
							                	//item.id_comprador,
							                	i,
							                	parseFloat(item.percent).toFixed(2),
							                	item.nome
							                 ]).draw(false);


										   	i=i+1;    						    
								});
		
								$('.div-datatable').removeClass('hidden');

		            			$('#label-message').show();
		            			$('#label-message').text(data.message)
		            	}else{


		            			$('#label-message').show();
		            			$('#label-message').text(data.message)	

		            	}

		            }
		        });  
   })



});

//initialize default datatable
function initialize(d1,d2){

		parity   = 1;
		currency = 2;

	

			var formattedDate = new Date(d1);
			var d = formattedDate.getDate();
			var m =  formattedDate.getMonth();
			m += 1;  // JavaScript months are 0-11
			var y = formattedDate.getFullYear();

			d1 = y + "-" + m + "-" + d;

		

			d="";
			m="";
			y="";

			formattedDate = new Date(d2);
			d = formattedDate.getDate();
			m =  formattedDate.getMonth();
			m += 1;  // JavaScript months are 0-11
			y = formattedDate.getFullYear();

			d2 = y + "-" + m + "-" + d;


			//console.log(d1,d2);return;			
			

			$.ajax({
			            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_CLIENTES_FOLLOW_FILTER ?>',
			            method: 'post',
			            dataType: 'json',
			            data: {currency:currency,parity:parity,date1: d1 ,date2: d2},
			            success: function (data) {

					            	console.log(data)		              

			            	if(data.success){

			            			var rows;
			            			var percent ;
			            			var i = 1;

				                 	$.each(data["response"], function (j, item) {
								     	

									   	rows = rows + "<tr >";
									   			rows = rows + "<td class='hide tdid"+item.id_comprador+"' data-id='"+item.id_comprador +"'>"+item.id_comprador+"</td>";
											   	rows = rows + "<td class='tdranking"+i+"' data-value='"+i +"'>"+i+"</td>";
												rows = rows + "<td class='tdpercent"+i+"' data-value='"+parseFloat(item.percent).toFixed(2) +"'>"+parseFloat(item.percent).toFixed(2)+"</td>";
												rows = rows + "<td class='tdname"+i+"' data-value='"+item.nome +"'>"+item.nome+"</td>";
												rows = rows + "</tr>";

												tabla.row.add( 
								                [
								                	//item.id_comprador,
								                	i,
								                	parseFloat(item.percent).toFixed(2),
								                	item.nome
								                 ]).draw(false);


											   	i=i+1;    						    
									});
			
									$('.div-datatable').removeClass('hidden');

			            			$('#label-message').show();
			            			$('#label-message').text(data.message)
			            	}else{


			            			$('#label-message').show();
			            			$('#label-message').text(data.message)	

			            	}

			            }
			        });  

	}


</script>


	<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>

