<?php
$idioma = new \Utils\PropertiesUtils("docs_aceitacao", IDIOMA);
$mensagem = ((isset($_data['mensagem'])) ? ($_data['mensagem']) : "");
$sucesso = (isset($_data['sucesso']) ? ($_data['sucesso']) : false);
$cliente = \Utils\Geral::getCliente();
$lista = ((isset($_data['lista'])) ? ($_data['lista']) : Array());
$tipo = $cliente->tipoAutenticacao;
$brand = Models\Modules\Cadastro\BrandRn::getBrand();
$empresa = Models\Modules\Cadastro\EmpresaRn::getEmpresa();
?>

<!DOCTYPE html>
<html class="wide wow-animation smoothscroll scrollTo" lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo TITULO ?></title>
    <link href="<?php echo TEMA; ?>css/bootstrap.min.css" rel="stylesheet">
    <link href="<?php echo TEMA; ?>font-awesome/css/font-awesome.css" rel="stylesheet">
    <link href="<?php echo TEMA; ?>css/animate.css" rel="stylesheet">
    <link href="<?php echo TEMA; ?>css/styleD.css" rel="stylesheet">
    <link href="<?php echo TEMA; ?>css/plugins/iCheck/custom.css" rel="stylesheet">
</head>

<body>
    <div class="vh-100 d-flex justify-content-center">
        <div class="my-auto middle-box text-center loginscreen animated fadeInDown">
            <div class="m-t-lg m-b-lg">
                <div class="">
                    <div class="m-t-lg m-b-lg">
                        <a href="<?php echo $empresa->homePage ?>">
                            <img alt="image"  width="250px" src="<?php echo IMAGES; ?>logo-ca.png" class="logo">
                        </a>
                    </div>
                    <br>
                    <div>
                        <li class="text-center m-t-md list-unstyled">
                            <a href="javascript:trocarIdioma('en-US');" id="Btlangen">EN </a>
                            &nbsp;&nbsp;
                            <a href="javascript:trocarIdioma('pt-BR');" id="Btlangpt">PT </a>
                            &nbsp;&nbsp;
                            <a href="javascript:trocarIdioma('es-ES');" id="Btlanges">ES </a>
                        </li>
                    </div>
                    <div class="mt-lg-4">
                        <div class="col-lg-12">
                        <h2><?php echo $idioma->getText("docsLegais") ?></h2>
                        <br><br>
                        <p>
                        <h3><?php echo $idioma->getText("paraSaberUtilizar") ?></h3>
                        <p>
                        </p>
                        <p></p>
                        <br><br>
                        <?php foreach ($lista as $documentoSistema) { ?>
                        <div class="row" id="container-<?php echo $documentoSistema->codigo ?>">
                            <div class="col col-lg-6">
                                <!-- <div class="form-group"> -->
                                    <div class="row text-left" >
                                        <div class="custom-checkbox">
                                            <input class="" type="checkbox" name="<?php echo $documentoSistema->codigo ?>" id="<?php echo $documentoSistema->codigo ?>" >
                                        </div>&nbsp;&nbsp;
                                        <label class="" for="<?php echo $documentoSistema->codigo ?>" style="font-size: 15px">
                                            <a href="<?php echo $documentoSistema->link?>" target="<?php echo $documentoSistema->id ?>"><?php echo $documentoSistema->descricao?></a>
                                        </label>
                                <!-- </div> -->
                                </div>
                            </div>
                        </div>
                        <?php } ?>
                        <br><br>
                        <div class="row" id="container-alert" style="display: none;">
                            <div class="col col-lg-12">
                                <div class="alert alert-danger">
                                </div>
                            </div>
                        </div>
                        <br><br>
                        <div class="row">
                            <div class="col-xs-12 col-lg-12 text-center">
                                <button class="btn btn-primary full-width" type="button" onclick="aceitar();" id="btn-aceitar">
                                    <?php echo $idioma->getText("liEConcordo") ?>
                                </button>
                            </div>
                        </div>
                        <br>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

<!-- Bootstrap 3.3.6 -->
<script src="<?php echo TEMA; ?>js/jquery-3.1.1.min.js"></script>
<script src="<?php echo TEMA; ?>bootstrap/js/bootstrap.min.js"></script>
<script src="<?php echo TEMA; ?>js/plugins/iCheck/icheck.min.js"></script>
<script>
    $(document).ready(function () {
        // $('.i-checks').iCheck({
        //     checkboxClass: 'icheckbox_square-green',
        //     radioClass: 'iradio_square-green'
        // });
    });

    function aceitar() {
        $("#btn-aceitar").prop("disabled", true);
        $("#container-alert").hide();
        $('#container-alert alert').html("");

        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_DOCS_ACEITACAO_SALVAR ?>',
            dataType: 'json',
            method: 'post',
            data: {
                <?php
                foreach ($lista as $doc) {
                    ?>
                    <?php echo $doc->codigo ?>: $("#<?php echo $doc->codigo ?>").is(":checked"),
                    <?php
                }
                ?>
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        location = "<?php echo URLBASE_CLIENT . Utils\Rotas::R_DOCS_ACEITACAO?>";
                    } else {
                        var i = 0;
                        for(i=0; i<json.aceites.length; i++) {
                            $("#container-"+json.aceites[i]).remove();
                        }
                        
                        $("#container-alert").show();
                        $('#container-alert .col .alert').html(json.mensagem);
                    }
                } catch (e) {
                    $("#container-alert").show();
                    $('#container-alert .col .alert').html(e);
                }
                $("#btn-aceitar").prop("disabled", false);
            }
        });
    }
    
    function trocarIdioma(lang) {
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_IDIOMA_CHANGE ?>',
            method: 'post',
            dataType: 'html',
            data: {
                lang: lang
            },
            success: function () {

                location.reload();
            }
        });
    }
</script>
</body>
</html>