<?php
$available_langs = array('pt-br','en','es','fr');
if(in_array($_POST['lang'], $available_langs)) {       
    $_SESSION['lang'] = $_POST['lang'];
  }
$idioma = (isset($_SESSION['lang']) ? $_SESSION['lang'] : "pt-br");
$homeBase = URLBASE_CLIENT . 'Modules/acesso/views/';
include('Modules/acesso/views/languages/'.$idioma.'/lang.'.$idioma.'.php');
$brand = Models\Modules\Cadastro\BrandRn::getBrand();
$empresa = Models\Modules\Cadastro\EmpresaRn::getEmpresa();
$idReferencia = \Utils\Get::get($_data, 0, "");
?>
<!DOCTYPE html>
<html>
<head>
    <?php if(AMBIENTE == "producao") { ?>

    <?php } ?>
    <title><?php echo TITULO ?></title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="cache-control" content="max-age=0" />
    <meta http-equiv="cache-control" content="no-cache" />
    <meta http-equiv="expires" content="Tue, 01 Jan 2030 1:00:00 GMT" />
    <meta http-equiv="pragma" content="no-cache" />
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <link href="<?php echo TEMA; ?>css/bootstrap.min.css" rel="stylesheet">
    <link href="<?php echo TEMA; ?>font-awesome/css/font-awesome.css" rel="stylesheet">
    <link href="<?php echo TEMA; ?>css/animate.css" rel="stylesheet">
    <link href="<?php echo TEMA; ?>css/plugins/toastr/toastr.min.css" rel="stylesheet">
    <link href="<?php echo TEMA; ?>css/plugins/sweetalert/sweetalert.css" rel="stylesheet">
    <link href="<?php echo TEMA; ?>css/styleD.css" rel="stylesheet">
    <link href="<?php echo TEMA; ?>css/plugins/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.css" rel="stylesheet">
    <link href="<?php echo CSS; ?>passwordRequirements.css" rel="stylesheet">
    
    <script src="https://www.google.com/recaptcha/api.js"></script>
    
</head>
<script type="text/javascript">
    var AMBIENTE = '<?php echo AMBIENTE ?>';
</script>
<body class="m-lg" style="background-color: <?php echo $brand->colorBackground ?>">
    <div class="middle-box text-center loginscreen  animated fadeInDown">
                <div class="m-t-lg m-b-lg">
                    <a href="<?php echo $empresa->homePage ?>">
                    <img alt="image"  width="150px" src="<?php echo IMAGES; ?>logo-cointrade.png" class="logo">
                    </a>
                </div>
            </br>
            <form action="<?php echo URLBASE_CLIENT . \Utils\Rotas::R_CADASTRO?>" method="post" id="form-cadastro" class="form-cadastro mt-lg-4">
                <div class="form-group">
                    <input style="border-radius: 3px; background-color: transparent !important; color: #fff !important;" type="text" class="form-control" id="nome" name="nome" placeholder="<?php echo $lang['home11']; ?>" class="input">
                </div>
                <div class="form-group">
                    <input style="border-radius: 3px; background-color: transparent !important; color: #fff !important;" type="email" class="form-control" id="email" name="email" placeholder="E-mail" class="input" autocomplete='email'>
                    <input style="border-radius: 3px; background-color: transparent !important; color: #fff !important;" type="hidden" id="referencia" name="referencia" value="<?php echo $idReferencia ?>" class="input">
                </div>
                <div class="form-group">
                    <input style="border-radius: 3px; background-color: transparent !important; color: #fff !important;" type="password" class="form-control pr-password" id="senha" name="senha" placeholder="<?php echo $lang['home36']; ?>" class="input">
                </div>
                <div class="form-group">
                    <input style="border-radius: 3px; background-color: transparent !important; color: #fff !important;" type="password" class="form-control" id="senhaConfirmar" name="senhaConfirmar" placeholder="<?php echo $lang['home37']; ?>" class="input">
                </div>
                <div class="form-group m-t-lg">
                    <div style="text-align: center;">
                        <div  id="google" name="google" atrpage="register" class="g-recaptcha" data-callback="validarBotao" data-sitekey="<?php echo GOOGLESITE; ?>" data-theme="light" style="transform:scale(0.85);-webkit-transform:scale(0.85);transform-origin:0 0;-webkit-transform-origin:0 0; display: inline-block !important; margin-left: 25px !important;" ></div>
                    </div>
                </div>
                
                <div class="form-group">
                    <div class="icheckbox_square-green">
                        <label>
                            <input type="checkbox" id="termos" name="termos" class="i-checks">
                            <a href="https://broker.cointradecx.com/resources/docs/2018/08/Contrato-de-Licenca-da-Interface-de-Programacao-de-Aplicacoes.pdf" target="_terms" style="color: #fff !important;" class="label-link"><?php echo $lang['home13']; ?></a>
                        </label>
                    </div>
                </div>
                
                <div class="form-group">
                    <button id="conta-gratis" type="submit"  class="btn btn-primary block full-width m-b"><?php echo $lang['home14']; ?></button>
                </div>
                <div class="form-group m-b-lg">
                    <div class="row">
                        <div class="col-xs-6 text-left">
                            <a class="" href="<?php echo URLBASE_CLIENT . \Utils\Rotas::R_LOGIN ?>" style="color: #e5e6e7;"><?php echo $lang['home10']; ?></a>
                        </div>
                        <div class="col-xs-6 text-right">
                            <a class="" href="<?php echo URLBASE_CLIENT . \Utils\Rotas::R_RECUPERACAO ?>" style="color: #e5e6e7;"><?php echo $lang['modal4']; ?></a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
<div class="footer navbar-fixed-bottom center">
    <small ><?php echo $empresa->nomeEmpresarial ?> <?php echo $empresa->anoInicio ?> - <?php echo date('Y');?></small> 
</div>
    <script src="<?php echo TEMA; ?>js/jquery-3.1.1.min.js"></script>

    <script src="<?php echo TEMA; ?>js/bootstrap.min.js"></script>
    <script src="<?php echo TEMA; ?>js/plugins/toastr/toastr.min.js"></script>
    
    
    <?php Utils\Layout::append("inspina/notificacao", null); ?>

    
    <script src="<?php echo TEMA; ?>js/plugins/iCheck/icheck.min.js"></script>
</body>

<?php if(AMBIENTE == "producao") { ?>

<?php } ?>
</html>
