<?php
$available_langs = array('pt-br','en','es','fr');
if(in_array($_POST['lang'], $available_langs)) {       
    $_SESSION['lang'] = $_POST['lang'];
  }
$idioma = (isset($_SESSION['lang']) ? $_SESSION['lang'] : "pt-br");
$homeBase = URLBASE_CLIENT . 'Modules/acesso/views/';
include('Modules/acesso/views/languages/'.$idioma.'/lang.'.$idioma.'.php');
$brand = Models\Modules\Cadastro\BrandRn::getBrand();
$empresa = Models\Modules\Cadastro\EmpresaRn::getEmpresa();
?>
<!DOCTYPE html>
<html>
<head>
    <?php if(AMBIENTE == "producao") { ?>

    <?php } ?>
    <script src="https://www.google.com/recaptcha/api.js"></script>

    <title><?php echo TITULO ?></title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="cache-control" content="max-age=0" />
    <meta http-equiv="cache-control" content="no-cache" />
    <meta http-equiv="expires" content="Tue, 01 Jan 2030 1:00:00 GMT" />
    <meta http-equiv="pragma" content="no-cache" />
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <!-- <link href="<?php echo TEMA; ?>css/bootstrap.min.css" rel="stylesheet"> -->
    <link href="<?php echo TEMA; ?>font-awesome/css/font-awesome.css" rel="stylesheet">
    <link href="<?php echo TEMA; ?>css/animate.css" rel="stylesheet">
    <link href="<?php echo TEMA; ?>css/plugins/toastr/toastr.min.css" rel="stylesheet">
    <!-- <link href="<?php echo TEMA; ?>css/styleD.css" rel="stylesheet"> -->
    
     <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Crypo</title>
  <link rel="icon" href="assets/img/favicon.png" type="image/x-icon">
  <link rel="stylesheet" href="<?php echo TEMA; ?>/css/style.css">

</head>
<script type="text/javascript">
    var AMBIENTE = '<?php echo AMBIENTE ?>';    
</script>
<body>
  <div class="vh-100 d-flex justify-content-center">
    <div class="form-access my-auto middle-box text-center loginscreen animated fadeInDown">
    <div class="m-t-lg m-b-lg">

        <div class="m-t-lg m-b-lg">
            <a href="<?php echo $empresa->homePage ?>">
                <img alt="image"  width="250px" src="<?php echo IMAGES; ?>logo-ca.png" class="logo">
            </a>
        </div>
        <br>
        <form method="post" id="form-login" class="form-cadastro mt-lg-4">
            <span>Login</span>

            <div class="form-group">
                <input style="border-radius: 3px; background-color: transparent !important; color: #000 !important;"  type="email" id="email_login" class="form-control" placeholder="<?php echo $lang['modal1']; ?>">
            </div>
            <div class="form-group">
                <input style="border-radius: 3px; background-color: transparent !important; color: #000 !important;"  type="password" id="senha" class="form-control" placeholder="<?php echo $lang['modal2']; ?>" autocomplete="current-password">
            </div>
            <div class="col-xs-12 text-right">
                <a class="" href="<?php echo URLBASE_CLIENT . \Utils\Rotas::R_RECUPERACAO ?>" style="color: #2351ff;"><?php echo $lang['modal4']; ?></a>
            </div>
            <br>
            <div style="text-align: center;">
                <div  id="google" name="google" atrpage="login" class="g-recaptcha" data-callback="validarBotao" data-sitekey="<?php echo getenv('GoogleSite'); ?>" data-theme="light" style="transform:scale(0.85);-webkit-transform:scale(0.85);transform-origin:0 0;-webkit-transform-origin:0 0; display: inline-block !important; margin-left: 25px !important;" ></div>
            </div>
            <button id="acessar-painel" disabled="disabled" style="background-color: #2351ff; border-color: #2351ff; color:black;" type="submit" class="btn btn-primary block full-width m-b" ><?php echo $lang['modal3']; ?></button>
    </form>
    <!-- <h2>Don't have an account? <a href="signup-light.html">Sign up here</a></h2> -->
    <div class="col-xs-6 text-center">
        <h2>
            <?php echo $lang['home9']; ?>
            <a
            class=""
            href="<?php echo URLBASE_CLIENT . \Utils\Rotas::R_REGISTER ?>"
            style="color: #2351ff;">
                <?php echo $lang['home99']; ?>
            </a>
        </h2>
    </div>
    </div>
    <!-- <div class="footer navbar-fixed-bottom center">
        <small ><?php echo $empresa->nomeEmpresarial ?> <?php echo $empresa->anoInicio ?> - <?php echo date('Y');?></small> 
    </div> -->
  </div>
  <script src="assets/js/jquery-3.4.1.min.js"></script>
  <script src="assets/js/popper.min.js"></script>
  <script src="assets/js/bootstrap.min.js"></script>
  <script src="assets/js/amcharts-core.min.js"></script>
  <script src="assets/js/amcharts.min.js"></script>
  <script src="assets/js/custom.js"></script>
  <?php Utils\Layout::append("inspina/notificacao", null); ?>
</body>

</html>

