<?php
$idioma1 = new \Utils\PropertiesUtils("recuperar", IDIOMA);
$mensagem = isset($_data["mensagem"]) ? $_data["mensagem"] : "";
$brand = Models\Modules\Cadastro\BrandRn::getBrand();
$empresa = Models\Modules\Cadastro\EmpresaRn::getEmpresa();
$idioma = (isset($_SESSION['lang']) ? $_SESSION['lang'] : "pt-br");
include('Modules/acesso/views/languages/'.$idioma.'/lang.'.$idioma.'.php');
?>


<!DOCTYPE html>
<html lang="en">
<head>
    <?php if(AMBIENTE == "producao") { ?>

    <?php } ?>
    <script src="https://www.google.com/recaptcha/api.js"></script>
    <title><?php echo TITULO ?></title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="cache-control" content="max-age=0" />
    <meta http-equiv="cache-control" content="no-cache" />
    <meta http-equiv="expires" content="Tue, 01 Jan 2030 1:00:00 GMT" />
    <meta http-equiv="pragma" content="no-cache" />
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <link href="<?php echo TEMA; ?>css/bootstrap.min.css" rel="stylesheet">
    <link href="<?php echo TEMA; ?>font-awesome/css/font-awesome.css" rel="stylesheet">
    <link href="<?php echo TEMA; ?>css/animate.css" rel="stylesheet">
    <link href="<?php echo TEMA; ?>css/plugins/toastr/toastr.min.css" rel="stylesheet">
    <link href="<?php echo TEMA; ?>css/styleD.css" rel="stylesheet">
</head>


<body class="m-lg" style="background-color: <?php echo $brand->colorBackground ?>">
    <div class="middle-box text-center loginscreen  animated fadeInDown">
        <div class="m-t-lg m-b-lg">
            <a href="<?php echo $empresa->homePage ?>">
            <img alt="image"  width="150px" src="<?php echo IMAGES; ?>logo-cointrade.png" class="logo">
            </a>
        </div>
<form class="form-login mt-lg-4" method="post" id="form-recover" action="<?php echo URLBASE_CLIENT . Utils\Rotas::R_RECUPERACAO ?>">
    <div class="pss-dados">
        <div class="form-group">
            <input style="border-radius: 3px; background-color: transparent !important; color: #fff !important;" type="text" id="email" name='email' class="form-control" placeholder="<?php echo $idioma1->getText("digiteEmailCadastrado") ?>" >
        </div>  
        <div class="form-group m-t-lg">
            <div style="text-align: center;">
                <div  id="google" name="google" atrpage="recovery" class="g-recaptcha" data-callback="validarBotao" data-sitekey="<?php echo getenv('GoogleSite'); ?>" data-theme="light" style="transform:scale(0.85);-webkit-transform:scale(0.85);transform-origin:0 0;-webkit-transform-origin:0 0; display: inline-block !important; margin-left: 25px !important;" ></div>
            </div>
        </div>
        <button class="btn btn-primary block full-width m-b pss-dados" disabled="disabled" type="button" onclick="validarDados();" id="btn-send">
            <?php echo $idioma1->getText("recuperarSenha") ?> 
        </button>
    </div>   
    <div class="pss-token" hidden="true">
        <div class="form-group pss-token">
            <input type="text" id="token" name='token' class="form-control" hidden placeholder="<?php echo ($tipo == \Utils\Constantes::TIPO_AUTH_EMAIL ? $idioma1->getText("codEnviadoEmail") : ($tipo == \Utils\Constantes::TIPO_AUTH_GOOGLE ? $idioma1->getText("googleAutherticator") : $idioma1->getText("codigoPorSMS"))) ?>">
        </div>
        <button class="btn btn-primary block full-width m-b pss-token" type="button" onclick="recuperar();" id="btn-validate">
            <?php echo $idioma1->getText("validarToken") ?>
        </button>
    </div>  
    <div class="pss-key" hidden="true">
        <div class="form-group pss-key" hidden>
            <input type="text" id="key" name='key' class="form-control" placeholder="<?php echo $idioma1->getText("coleChave") ?>">
        </div>
        <button class="btn btn-primary block full-width m-b pss-key" hidden type="button" onclick="validar();" id="btn-key">
            <?php echo $idioma1->getText("validarChave") ?>
        </button>
    </div>
    <div class="form-group m-b-lg">
            <div class="row">
                <div class="col-xs-6 text-left">
                    <a class="" href="<?php echo URLBASE_CLIENT . \Utils\Rotas::R_LOGIN ?>" style="color: #e5e6e7;"><?php echo $idioma1->getText("entrar"); ?></a>
                </div>
                <div class="col-xs-6 text-right">    
                    <a class="" href="<?php echo URLBASE_CLIENT . \Utils\Rotas::R_REGISTER ?>" style="color: #e5e6e7;"><?php echo $idioma1->getText("cadastrar"); ?></a>
                </div>
            </div>
        </div>
</form>
</div>
<div class="footer navbar-fixed-bottom center">
    <small ><?php echo $empresa->nomeEmpresarial ?> <?php echo $empresa->anoInicio ?> - <?php echo date('Y');?></small> 
</div>


    
    <div class="overlay"></div>
    <script src="<?php echo TEMA; ?>js/jquery-3.1.1.min.js"></script>
    <script src="<?php echo TEMA; ?>js/bootstrap.min.js"></script>
    <script src="<?php echo TEMA; ?>js/plugins/toastr/toastr.min.js"></script>
    <?php Utils\Layout::append("inspina/notificacao", null); ?>
    
</body>
<?php if(AMBIENTE == "producao") { ?>

<?php } ?>
</html>
