<?php 

$nome = isset($_data["nome"]) ? $_data["nome"] : "";
$idNavegador = isset($_data["idNavegador"]) ? $_data["idNavegador"] : "";
$idCliente = isset($_data["idCliente"]) ? $_data["idCliente"] : "";
$localizacao = isset($_data["localizacao"]) ? $_data["localizacao"] : "";
$navegador = isset($_data["navegador"]) ? $_data["navegador"] : "";
$sistemaOperacional = isset($_data["so"]) ? $_data["so"] : "";
$data = isset($_data["data"]) ? $_data["data"] : "";
$data = new Utils\Data($data);
$ip = isset($_data["ip"]) ? $_data["ip"] : "";
$idioma = new \Utils\PropertiesUtils("email_manager", IDIOMA);

$emailManager = isset($_data["email_manager"]) ? $_data["email_manager"] : null;
$mensagem = isset($_data["mensagem"]) ? $_data["mensagem"] : null;

if(empty($mensagem)){
  $mensagem = $idioma->getText($emailManager->mensagem);
}

$brand = Models\Modules\Cadastro\BrandRn::getBrand();
$empresa = Models\Modules\Cadastro\EmpresaRn::getEmpresa();
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
	<!--[if (gte mso 9)|(IE)]>
	<xml>
		<o:OfficeDocumentSettings>
			<o:AllowPNG/>
			<o:PixelsPerInch>96</o:PixelsPerInch>
		</o:OfficeDocumentSettings>
	</xml>
	<![endif]-->
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<title><?php echo $idioma->getText("titulo") ?></title>

	<!-- Google Fonts Link -->
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
	<link href="https://fonts.googleapis.com/css?family=Lora:400,700" rel="stylesheet" />
	<style type="text/css">

		/*------ Client-Specific Style ------ */
		@-ms-viewport{width:device-width;}
		table, td{mso-table-lspace:0pt; mso-table-rspace:0pt;}
		img{-ms-interpolation-mode:bicubic; border: 0;}
		p, a, li, td, blockquote{mso-line-height-rule:exactly;}
		p, a, li, td, body, table, blockquote{-ms-text-size-adjust:100%; -webkit-text-size-adjust:100%;}
		#outlook a{padding:0;}
		.ReadMsgBody{width:100%;} .ExternalClass{width:100%;}
		.ExternalClass,.ExternalClass div,.ExternalClass font,.ExternalClass p,.ExternalClass span,.ExternalClass td,img{line-height:100%;}

		/*------ Reset Style ------ */
		*{-webkit-text-size-adjust:none;-webkit-text-resize:100%;text-resize:100%;}
		table{border-spacing: 0 !important;}
		h1, h2, h3, h4, h5, h6, p{display:block; Margin:0; padding:0;}
		img, a img{border:0; height:auto; outline:none; text-decoration:none;}
		#bodyTable, #bodyCell{ margin:0; padding:0; width:100%;}
		body {height:100%; margin:0; padding:0; width:100%;}

		.appleLinks a {color: #c2c2c2 !important; text-decoration: none;}
                span.preheader { display: none !important; }

		/*------ Google Font Style ------ */
		[style*="Open Sans"] {font-family:'Open Sans', Helvetica, Arial, sans-serif !important;}
		[style*="Lora"] {font-family:'Lora', Georgia, Times, serif !important;}

		/*------ General Style ------ */
		.wrapperWebview, .wrapperBody, .wrapperFooter{width:100%; max-width:600px; Margin:0 auto;}

		/*------ Column Layout Style ------ */
		.tableCard {text-align:center; font-size:0;}

		/*------ Images Style ------ */
		.imgHero img{ width:600px; height:auto; }

	</style>

	<style type="text/css">
		/*------ Media Width 480 ------ */
		@media screen and (max-width:640px) {
			table[class="wrapperWebview"]{width:100% !important; }
			table[class="wrapperEmailBody"]{width:100% !important; }
			table[class="wrapperFooter"]{width:100% !important; }
			td[class="imgHero"] img{ width:100% !important;}
			.hideOnMobile {display:none !important; width:0; overflow:hidden;}
		}
	</style>

</head>

<body style="background-color:#F9F9F9;">
<center>
		<table border="0" cellpadding="0" cellspacing="0" width="100%" style="table-layout:fixed;background-color:#F9F9F9;" id="bodyTable">
	<tbody><tr>
		<td align="center" valign="top" style="padding-right:10px;padding-left:10px;" id="bodyCell">
		<!--[if (gte mso 9)|(IE)]><table align="center" border="0" cellspacing="0" cellpadding="0" style="width:600px;" width="600"><tr><td align="center" valign="top"><![endif]-->

		<!-- Email Wrapper Webview Open //-->
                <table border="0" cellpadding="0" cellspacing="0" style="max-width:600px;" width="100%" class="wrapperWebview">
                    <tbody style="background-color: <?php echo $brand->colorBackground ?> !important;">
                        <tr>
                            <td align="center" valign="top">
                                <!-- Content Table Open // -->
                                <table border="0" cellpadding="0" cellspacing="0" width="100%">
                                    <tbody><tr>
                                            <td align="center" valign="middle" style="padding-top: 0px; padding-right: 0px;" class="webview">
                                                <!-- Email View in Browser // -->
                                                <a href="<?php echo $empresa->homePage ?>" target="_blank">
                                                    <img src="<?php echo IMAGES . $brand->logo ?>">
                                                </a>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                                <!-- Content Table Close // -->
                            </td>
                        </tr>
                    </tbody>
                </table>

		<!-- Email Wrapper Body Open // -->
                <table border="0" cellpadding="0" cellspacing="0" style="max-width:600px;" width="100%" class="wrapperBody">
                    <tbody><tr>
                            <td align="center" valign="top">

                                <!-- Table Card Open // -->
                                <table border="0" cellpadding="0" cellspacing="0" style="background-color: rgb(255, 255, 255); box-shadow: rgb(216, 216, 216) 0px 0px 10px;" width="100%" class="tableCard">

                                    <tbody><tr>
                                            <!-- Header Top Border // -->
                                            <td height="3" style="background-color: rgb(190, 218, 25); font-size: 1px; line-height: 3px;" class="topBorder">&nbsp;</td>
                                        </tr>


                                        <tr>
                                            <td align="center" valign="top" style="padding-bottom: 20px;" class="imgHero">
                                                <!-- Hero Image // -->
                                                <a href="#" target="_blank" style="text-decoration:none;" class="">
                                                    <img src="<?php echo IMAGES . $emailManager->imagemCentro ?>" width="600" alt="" border="0" style="width:100%; max-width:600px; height:auto; display:block;" class="">
                                                </a>
                                            </td>
                                        </tr>

                                        <tr>
                                            <td align="center" valign="top" style="padding-bottom: 5px; padding-left: 20px; padding-right: 20px;" class="mainTitle">
                                                <!-- Main Title Text // -->
                                                <h2 class="text" style="color:#000000; font-family:'Poppins', Helvetica, Arial, sans-serif; font-size:22px; font-weight:500; font-style:normal; letter-spacing:normal; line-height:36px; text-transform:none; text-align:center; padding:0; margin:0"><?php echo $idioma->getText($emailManager->tituloMensagem) ?>
                                                </h2>
                                            </td>
                                        </tr>

                                        <tr>
                                            <td align="center" valign="top" style="padding-bottom: 30px; padding-left: 20px; padding-right: 20px;" class="subTitle">
                                                <!-- Sub Title Text // -->
                                                <h4 class="text" style="color:#999999; font-family:'Poppins', Helvetica, Arial, sans-serif; font-size:14px; font-weight:500; font-style:normal; letter-spacing:normal; line-height:24px; text-transform:none; text-align:center; padding:0; margin:0">
                                                    <?php echo $mensagem ?></h4>
                                            </td>
                                        </tr>

                                        <tr>
                                            <td align="center" valign="top" style="padding-left:20px;padding-right:20px;" class="containtTable ui-sortable">

                                                <?php if($emailManager->logAcesso > 0) { ?>
                                                <table border="0" cellpadding="0" cellspacing="0" width="100%" class="tableTitleDescription" style="">
								<tbody>
								<tr>
									<td align="center" valign="top" style="padding-bottom: 20px;" class="description">
										<!-- Description Text// -->
										<p class="text" style="color:#666666; font-family:'Open Sans', Helvetica, Arial, sans-serif; font-size:10px; font-weight:400; font-style:normal; letter-spacing:normal; line-height:22px; text-transform:none; text-align:center; padding:0; margin:0">
                                                                                        <strong><?php echo $idioma->getText("localizacao") ?></strong> <?php echo $localizacao ?><br>                                                                                        
                                                                                        <strong><?php echo $idioma->getText("sistemaOperacional") ?></strong> <?php echo $sistemaOperacional ?><br> 
                                                                                        <strong><?php echo $idioma->getText("navegador") ?></strong> <?php echo $navegador ?><br></br>
											<strong><?php echo $idioma->getText("dataHora") ?></strong> <?php echo $data->formatar(\Utils\Data::FORMATO_PT_BR_TIMESTAMP_LONGO); ?><br>
											<strong><?php echo $idioma->getText("ipAcesso") ?> </strong> <?php echo $ip ?><br>
                                                                                        <strong><?php echo $idioma->getText("casoNaoSejaVoce") ?></strong><br> 
                                                                                        
                                                                                        <form action="<?php echo URLBASE_CLIENT ?>revogar" method="post" enctype="multipart/form-data" target="_BLANK">
                                                                                            <input type="hidden" value="<?php echo $idCliente ?>" name="cnc"/>
                                                                                            <input type="hidden" value="<?php echo $idNavegador ?>" name="nnc"/>
                                                                                            <button type="submit" style="background-color: #CC0000; color: #FFFFFF; border-radius: 5px; border-bottom-color: #CC0000; font-size: 12px; font-weight: bold;" ><?php echo $idioma->getText("revogarAcesso") ?></button>
                                                                                        </form>
										</p>
									</td>
								</tr>
							</tbody>
                                                        </table>
                                                <?php } ?>

                                            </td>
                                        </tr>

                                        <tr>
                                            <td height="20" style="font-size:1px;line-height:1px;">&nbsp;</td>
                                        </tr>

                                    </tbody>
                                </table>
                                <!-- Table Card Close// -->

                                <!-- Space -->
                                <table border="0" cellpadding="0" cellspacing="0" width="100%" class="space">
                                    <tbody><tr>
                                            <td height="30" style="font-size:1px;line-height:1px;">&nbsp;</td>
                                        </tr>
                                    </tbody>
                                </table>
                                 <?php if(!empty($empresa->marketingEmail) && ($emailManager->imagemMarketing > 1) ){ ?>
                                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="background-color:#FFFFFF;border-color:#E5E5E5; border-style:solid; border-width:1px" class="offerCard">
                                    <tbody><tr>
                                            <td align="center" valign="middle">                                               
                                                <table border="0" cellpadding="0" cellspacing="0" width="100%" class="offerTable" style="border:10px solid #FFFFFF;background-color:#EEEEEE">
                                                    <tbody><tr>
                                                            <td align="center" valign="middle" class="offerImg" style="">
                                                                <!-- Logo and Link // -->
                                                                <a href="#" target="_blank" style="text-decoration:none;">
                                                                    <img mc:edit="offer" src="<?php echo IMAGES ?>mail/campanha/<?php echo $empresa->marketingEmail ?>" alt="" width="580" border="0" style="width:100%; max-width:580px;height:auto; display:block;">
                                                                </a>
                                                            </td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                               
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                                 <?php } ?>

                                <table border="0" cellpadding="0" cellspacing="0" width="100%" class="space">
                                    <tbody><tr>
                                            <td height="30" style="font-size:1px;line-height:1px;">&nbsp;</td>
                                        </tr>
                                    </tbody></table>
                            </td>
                        </tr>
                    </tbody></table>
<!-- Email Wrapper Body Close // -->

		<!-- Email Wrapper Footer Open // -->
		<table border="0" cellpadding="0" cellspacing="0" style="max-width:600px;" width="100%" class="wrapperFooter">
			<tbody><tr>
				<td align="center" valign="top">
					<!-- Content Table Open// -->
					<table border="0" cellpadding="0" cellspacing="0" width="100%" class="footer">
						<tbody>
                                                    <?php if($emailManager->redesSociais > 0 ){ ?>
                                                    <tr>
							<td align="center" valign="top" style="padding-top:10px;padding-bottom:10px;padding-left:10px;padding-right:10px;" class="socialLinks">
								<!-- Social Links (Facebook)// -->
                                                                <?php if(!empty($empresa->facebook)) { ?>
								<a href="https://www.facebook.com/<?php echo $empresa->facebook ?>" target="_blank" style="display: inline-block;" class="facebook">
									<img src="http://grapestheme.com/notify/img/social/color/facebook.png" alt="" width="40" border="0" style="height:auto; width:100%; max-width:40px; margin-left:2px; margin-right:2px" class="">
								</a>
                                                                <?php } ?>
                                                                
                                                                <?php if(!empty($empresa->twitter)) { ?>
								<!-- Social Links (Twitter)// -->
								<a href="https://twitter.com/<?php echo $empresa->twitter ?>" target="_blank" style="display: inline-block;" class="twitter">
									<img src="http://grapestheme.com/notify/img/social/color/twitter.png" alt="" width="40" border="0" style="height:auto; width:100%; max-width:40px; margin-left:2px; margin-right:2px" class="">
								</a>
                                                                <?php } ?>
								
                                                                <?php if(!empty($empresa->instagram)) { ?> 
								<!-- Social Links (Instagram)// -->
								<a href="https://www.instagram.com/<?php echo $empresa->instagram ?>" target="_blank" style="display: inline-block;" class="instagram">
									<img src="http://grapestheme.com/notify/img/social/color/instagram.png" alt="" width="40" border="0" style="height:auto; width:100%; max-width:40px; margin-left:2px; margin-right:2px" class="">
								</a>
                                                                <?php } ?>
                                                                
                                                                <?php if(!empty($empresa->linkedin)) { ?> 
								<!-- Social Links (Linkdin)// -->
								<a href="https://www.linkedin.com/<?php echo $empresa->linkedin ?>" target="_blank" style="display: inline-block;" class="linkdin">
									<img src="http://grapestheme.com/notify/img/social/color/linkdin.png" alt="" width="40" border="0" style="height:auto; width:100%; max-width:40px; margin-left:2px; margin-right:2px" class="">
								</a>
                                                                <?php } ?>
                                                                
                                                               <?php if(!empty($empresa->youtube)) { ?> 
                                                                <a href="https://www.youtube.com/<?php echo $empresa->youtube ?>" target="_blank" style="display: inline-block;" class="youtube">
                                                                    <img src="http://grapestheme.com/notify/img/social/color/youtube.png" alt="" width="40" border="0" style="height:auto; width:100%; max-width:40px; margin-left:2px; margin-right:2px" class="">
                                                                </a>
                                                               <?php } ?>
                                                                
                                                                <?php if(!empty($empresa->medium)) { ?> 
                                                                <a href="https://medium.com/<?php echo $empresa->medium ?>" target="_blank" style="display: inline-block;" class="medium">
                                                                    <img src="http://grapestheme.com/notify/img/social/color/medium.png" alt="" width="40" border="0" style="height:auto; width:100%; max-width:40px; margin-left:2px; margin-right:2px" class="">
                                                                </a>
                                                                <?php } ?>
                                                        </td>
                                                    </tr>
                                                    <?php } ?>
                                                    
                                                <?php if($emailManager->enderecoRodape > 0) { ?>    
						<tr>
							<td align="center" valign="top" style="padding: 10px 10px 5px;" class="brandInfo">
								<!-- Brand Information // -->
								<p class="text" style="color:#777777; font-family:'Open Sans', Helvetica, Arial, sans-serif; font-size:12px; font-weight:400; font-style:normal; letter-spacing:normal; line-height:20px; text-transform:none; text-align:center; padding:0; margin:0;">
                                                                    ©&nbsp;<?php echo $empresa->nomeFantasia . " | " . $empresa->logradouro . "," . $empresa->numero . " - " . $empresa->complemento . " - " . $empresa->bairro . " | " . $empresa->municipio . " - " . $empresa->estado . " - " . $empresa->cep. " | " . $empresa->pais ; ?>
                                                                </p>
							</td>
						</tr>
                                                <?php } ?>

						<tr>
							<td align="center" valign="top" style="padding: 0px 10px 20px;" class="footerLinks">
								<!-- Use Full Links (Privacy Policy)// -->
								<p class="text" style="color:#777777; font-family:'Open Sans', Helvetica, Arial, sans-serif; font-size:12px; font-weight:400; font-style:normal; letter-spacing:normal; line-height:20px; text-transform:none; text-align:center; padding:0; margin:0;"></p>
							</td>
						</tr>

						<tr>
							<td align="center" valign="top" style="padding: 0px 10px 10px;" class="footerEmailInfo">
								<!-- Information of NewsLetter (Subscribe Info)// -->
								<p class="text" style="color:#777777; font-family:'Open Sans', Helvetica, Arial, sans-serif; font-size:12px; font-weight:400; font-style:normal; letter-spacing:normal; line-height:20px; text-transform:none; text-align:center; padding:0; margin:0;"><?php echo $idioma->getText("emailDoSistema") ?></br> <?php echo $idioma->getText("casoNaoTenhaCadastro") ?></p>
							</td>
						</tr>
                                                    

						<tr>
							<td align="center" valign="top" style="padding-top:10px;padding-bottom:10px;padding-left:10px;padding-right:10px;" class="appLinks">
								<!-- App Links (Anroid)// -->

								<!-- App Links (IOs)// -->

							</td>
						</tr>

						<!-- Space -->
						<tr>
							<td height="30" style="font-size:1px;line-height:1px;">&nbsp;</td>
						</tr>
					</tbody></table>
					<!-- Content Table Close// -->
				</td>
			</tr>

			<!-- Space -->
			<tr>
				<td height="30" style="font-size:1px;line-height:1px;">&nbsp;</td>
			</tr>
		</tbody>
                
                </table>
		<!-- Email Wrapper Footer Close // -->

		<!--[if (gte mso 9)|(IE)]></td></tr></table><![endif]-->
		</td>
	</tr>
</tbody></table>
	</center>
</body>
</html>
