<?php
$estabelecimento = isset($_data["estabelecimento"]) ? $_data["estabelecimento"] : new \Models\Modules\Cadastro\Estabelecimento();
$estados = isset($_data["estados"]) ? $_data["estados"] : Array();
$moeda = \Modules\principal\Controllers\Principal::getCurrency();
$cliente = isset($_data["cliente"]) ? $_data["cliente"] : new Models\Modules\Cadastro\Cliente();

$salvar = false;

if ($estabelecimento->id > 0) {
    if (\Models\Modules\Acesso\RotinaRn::validar(\Utils\Rotas::R_ESTABELECIMENTOS, \Utils\Constantes::EDITAR)) {
        $salvar = true;
    }
} else {
    if (\Models\Modules\Acesso\RotinaRn::validar(\Utils\Rotas::R_ESTABELECIMENTOS, \Utils\Constantes::CADASTRAR)) {
        $salvar = true;
    }
}


?>
<?php Utils\Layout::append("inspina/metas", $_data) ?>

<?php Utils\Layout::append("inspina/scripts", $_data) ?>


<?php Utils\Layout::append("inspina/menu", $_data) ?>


    
    
<div class="content-wrapper">
  <div class="row wrapper border-bottom page-heading" style="background: linear-gradient(to right, #fff, <?php echo $moeda->mainColor ?>) !important;">
    <div class="col-lg-9">
      <ol class="breadcrumb m-t-md" style="background-color: transparent !important;">
          <li>
            Estabelecimentos
          </li>
          <li class="active">
              <strong>Cadastro</strong>
          </li>
      </ol>
    </div>
    <div class="col-lg-3">
    <?php Utils\Layout::append("inspina/flags", $_data) ?>
    </div>
  </div>
</div>
    
<div>
<br>

    <!-- Main content -->
    <section class="content">

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <?php Utils\Layout::append("mensagem", $_data)?>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <input type="hidden" id="id" value="<?php echo Utils\Criptografia::encriptyPostId($estabelecimento->id)?>" />
                        <div class="row">
                            <div class="col col-lg-6">
                                <div class="form-group">
                                    <label>Nome do Estabelecimento<strong>*</strong></label>
                                    <input type="text" class="form-control" id="nome" value="<?php echo $estabelecimento->nome ?>" maxlength="200" />
                                </div>
                            </div>
                            <div class="col col-lg-3">
                                <div class="form-group">
                                    <label>CNPJ</label>
                                    <input type="text" class="form-control" id="cnpj" value="<?php echo $estabelecimento->cnpj ?>" />
                                </div>
                            </div>
                            <div class="col col-lg-3">
                                <div class="form-group">
                                    <label>CPF</label>
                                    <input type="text" class="form-control" id="cpf" value="<?php echo $estabelecimento->cpf ?>" />
                                </div>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col col-lg-5">
                                <div class="form-group">
                                    <label>Endereço</label>
                                    <input type="text" class="form-control" id="endereco" value="<?php echo $estabelecimento->endereco ?>" maxlength="200" />
                                </div>
                            </div>
                            <div class="col col-lg-2">
                                <div class="form-group">
                                    <label>Numero</label>
                                    <input type="text" class="form-control" id="numero" value="<?php echo $estabelecimento->numero ?>" maxlength="10" />
                                </div>
                            </div>
                            <div class="col col-lg-5">
                                <div class="form-group">
                                    <label>Complemento</label>
                                    <input type="text" class="form-control" id="complemento" value="<?php echo $estabelecimento->complemento ?>" maxlength="200" />
                                </div>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col col-lg-2">
                                <div class="form-group">
                                    <label>CEP</label>
                                    <input type="text" class="form-control" id="cep" value="<?php echo $estabelecimento->cep ?>" maxlength="9" />
                                </div>
                            </div>
                            <div class="col col-lg-4">
                                <div class="form-group">
                                    <label>Bairro</label>
                                    <input type="text" class="form-control" id="bairro" value="<?php echo $estabelecimento->bairro ?>" maxlength="200" />
                                </div>
                            </div>
                            <div class="col col-lg-2">
                                <div class="form-group">
                                    <label>Estado<strong>*</strong></label>
                                    <select class="form-control" id="idEstado">
                                        <?php 
                                            foreach ($estados as $estado) {
                                                ?>
                                                <option  value="<?php echo Utils\Criptografia::encriptyPostId($estado->id) ?>"><?php echo $estado->sigla ?></option>
                                                <?php
                                            }
                                        ?>
                                    </select>
                                </div>
                            </div>
                            <div class="col col-lg-4">
                                <div class="form-group">
                                    <label>
                                        <img src="<?php echo IMAGES ?>loader.GIF" id="loaderCidades" style="width: 25px; height: 25px;" />
                                        Cidade<strong>*</strong>
                                    </label>
                                    <select class="form-control" id="codigoCidade">
                                        
                                    </select>
                                </div>
                            </div>
                        </div>
                        
                        
                        <div class="row">
                            <div class="col col-lg-3">
                                <div class="form-group">
                                    <label>Telefone</label>
                                    <input type="text" class="form-control" id="telefone" value="<?php echo $estabelecimento->telefone ?>" maxlength="20" />
                                </div>
                            </div>
                            <div class="col col-lg-3">
                                <div class="form-group">
                                    <label>Telefone 2</label>
                                    <input type="text" class="form-control" id="telefone2" value="<?php echo $estabelecimento->telefone2 ?>" maxlength="20" />
                                </div>
                            </div>
                            <div class="col col-lg-6">
                                <div class="form-group">
                                    <label>email</label>
                                    <input type="text" class="form-control" id="email" value="<?php echo $estabelecimento->email ?>" maxlength="200" />
                                </div>
                            </div>
                        </div>
                        
                        
                        <div class="row">
                            <div class="col col-lg-4">
                                <div class="form-group">
                                    <label>Callback de retorno API Wallets</label>
                                    <input type="text" class="form-control" id="callbackProducao" value="<?php echo $estabelecimento->callbackProducao ?>" maxlength="200" />
                                </div>
                            </div>
                            <div class="col col-lg-4">
                                <div class="form-group">
                                    <label>Callback de retorno API Wallets (SANDBOX)</label>
                                    <input type="text" class="form-control" id="callbackHomologacao" value="<?php echo $estabelecimento->callbackHomologacao ?>" maxlength="200" />
                                </div>
                            </div>
                            <div class="col col-lg-4">
                                <div class="form-group">
                                    <label>Comissão cobrada pelo estabelecimento ao sacar</label>
                                    <div class="input-group">
                                        <input type="text" class="form-control" id="comissaoEstabelecimento" value="<?php echo number_format($estabelecimento->comissaoEstabelecimento, 8, ",", "") ?>" />
                                        <div class="input-group-addon">
                                            
                                            <select name="tipoComissaoEstabelecimento" id="tipoComissaoEstabelecimento">
                                                <option value="p" <?php echo ($estabelecimento->tipoComissaoEstabelecimento == "p" ? "selected" : "") ?> >%</option>
                                                <option value="v" <?php echo ($estabelecimento->tipoComissaoEstabelecimento == "v" ? "selected" : "") ?> >BTC</option>
                                            </select>
                                            
                                        </div>
                                    </div>
                                </div>
                                
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col col-lg-12">
                                <div class="input-group m-b">
                                    <span class="input-group-addon bg-primary"> 
                                        <input type="checkbox" id="habilitarSaqueAutomatico" <?php echo ($estabelecimento->habilitarSaqueAutomatico? "checked" : "") ?>> <label for="habilitarSaqueAutomatico">Habilitar saque automático </label>
                                    </span> 
                                    <input type="text" class="form-control" id="walletSaqueAutomatico" placeholder="Wallet para saque automático" value="<?php echo $estabelecimento->walletSaqueAutomatico ?>" maxlength="200" />
                                </div>
                            </div>
                        </div>
                        
                        <br><br><br>
                        
                        <div class="row " id="rowApiKey" style="<?php echo (empty($estabelecimento->chave) ? "display: none;" : "") ?>">
                            <div class="col col-lg-12">
                                <strong>API Key: <span id="apiKey"><?php echo $estabelecimento->chave ?></span></strong>
                            </div>
                        </div>
                        <div class="row " id="rowApiKeySandbox" style="<?php echo (empty($estabelecimento->chaveSandbox) ? "display: none;" : "") ?>">
                            <div class="col col-lg-12">
                                <strong>API Key (Sandbox): <span id="apiKeySandbox"><?php echo $estabelecimento->chaveSandbox ?></span></strong>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col col-lg-12">
                                <div class="form-actions text-center">
                                    <button class="btn" onclick="cancelar();" id="btnCancelar">
                                        Cancelar
                                    </button>
                                    
                                    
                                    <?php if ($salvar) { ?>
                                    <button class="btn btn-primary btn-lg" onclick="salvar();" id="btnSalvar">
                                        Salvar
                                    </button>
                                    <?php } ?>
                                    
                                    
                                </div>
                            </div>
                        </div>
                        
                        
                    </div>
                    <!-- /.panel-body -->

                </div>
            </div>

        </div>

    </section>
    
    <div class="clearfix"></div>
</div>

<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>

<script>
    $(document).ready(function () {
        
        $("#cpf").mask("999.999.999-99");
        $("#cnpj").mask("99.999.999/9999-99");
        $("#cep").mask("99999-999");
        
        $("#telefone, #telefone2").inputmask({
            mask: ["(99) 9999-9999"],
            keepStatic: true
        });
        
        <?php if (!empty($estabelecimento->codigoCidade) && $estabelecimento->cidade != null && $estabelecimento->cidade->idEstado > 0) { ?>
                $("#idEstado").val('<?php echo Utils\Criptografia::encriptyPostId($estabelecimento->cidade->idEstado) ?>');
        <?php } ?>
        
        
        $("#idEstado").change(function () {
            getCidades();
        });
        
        
        $("#comissaoEstabelecimento").keydown(function (event) {
            $(this).val(currency($(this).val(), 8, 8, event.keyCode));
            calcularTaxaTotal();
            event.preventDefault();
        });
        
        getCidades();
        
        calcularTaxaTotal();
    });
    
    function calcularTaxaTotal() {
        var nc = <?php echo number_format($cliente->taxaTransferenciaRemota, 8, ".", "") ?>;
        var est = parseFloat(($("#comissaoEstabelecimento").val().length > 0 ? $("#comissaoEstabelecimento").val().replace(",", ".") : 0));
        var total = parseFloat(nc + est);
        $("#taxaTotalCobrada").html(total.toFixed("8"));
    }
    
    function cancelar() {
        location = "<?php echo URLBASE_CLIENT . Utils\Rotas::R_ESTABELECIMENTOS ?>";
    }
    
    function salvar() {
        $("#btnCancelar, #btnSalvar").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_ESTABELECIMENTOS_SALVAR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                id: $("#id").val(),
                nome: $("#nome").val(),
                endereco: $("#endereco").val(),
                numero: $("#numero").val(),
                complemento: $("#complemento").val(),
                bairro: $("#bairro").val(),
                codigoCidade: $("#codigoCidade").val(),
                cep: $("#cep").val(),
                cnpj: $("#cnpj").val(),
                cpf: $("#cpf").val(),
                telefone: $("#telefone").val(),
                telefone2: $("#telefone2").val(),
                email: $("#email").val(),
                callbackHomologacao: $("#callbackHomologacao").val(),
                callbackProducao: $("#callbackProducao").val(),
                walletSaqueAutomatico: $("#walletSaqueAutomatico").val(),
                habilitarSaqueAutomatico: ($("#habilitarSaqueAutomatico").is(":checked") ? 1 : 0),
                comissaoEstabelecimento :$("#comissaoEstabelecimento").val(),
                tipoComissaoEstabelecimento: $("#tipoComissaoEstabelecimento").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        showNotyAlert(json.mensagem, "s");
                        $("#id").val(json.id);
                        
                        $("#rowApiKey, #rowApiKeySandbox").show();
                        $("#apiKey").html(json.chave);
                        $("#apiKeySandbox").html(json.chaveSandbox);
                        
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#btnCancelar, #btnSalvar").prop("disabled", false);
            }
        });
    }
    
    function getCidades() {
        $("#loaderCidades").show();
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_ESTABELECIMENTOS_CIDADES_LISTAR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                idEstado: $("#idEstado").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#codigoCidade").html(json.html);
                        
                        <?php if (!empty($estabelecimento->codigiCidade)) { ?>
                                var element = $("#codigoCidade").children("option:[value='<?php echo $estabelecimento->codigoCidade ?>'").first();
                                if (element !== null && typeof element !== 'undefined') {
                                    $("#codigoCidade").val('<?php echo $estabelecimento->codigoCidade ?>');
                                }
                        <?php } ?>
                        
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#loaderCidades").hide();
            }
        });
    }
    
</script>