<?php

$idioma = new \Utils\PropertiesUtils("perfil", IDIOMA);
$tab = (isset($_data["_parameters"][0]) ? $_data["_parameters"][0] : "");
$moeda = \Modules\principal\Controllers\Principal::getCurrency();
//$estado = isset($_data["estado"]) ? $_data["estado"] : new \Models\Modules\Cadastro\Estado();
//$cidadeAtual = isset($_data["cidade"]) ? $_data["cidade"] : new \Models\Modules\Cadastro\Cidade();
$licenca = isset($_data["licenca"]) ? $_data["licenca"] : null;
$solicitacaoLicenca = isset($_data["solicitacaoLicenca"]) ? $_data["solicitacaoLicenca"] : null;
$estados = isset($_data["estados"]) ? $_data["estados"] : array();
$cidades = isset($_data["cidades"]) ? $_data["cidades"] : array();
$paises = isset($_data["paises"]) ? $_data["paises"] : array();
$configuracao = isset($_data["configuracao"]) ? $_data["configuracao"] : new \Models\Modules\Cadastro\Configuracao();
$taxasMoedas = isset($_data["taxas"]) ? $_data["taxas"] : array();
$cliente = isset($_data["cliente"]) ? $_data["cliente"] : new \Models\Modules\Cadastro\Cliente();
$comissao = isset($_data["comissao"]) ? $_data["comissao"] : new \Models\Modules\Cadastro\ClienteHasComissao();
$bancos = isset($_data["todosOsBancos"]) ? $_data["todosOsBancos"] : array();
$clienteVerificado = isset($_data["clienteVerificado"]) ? $_data["clienteVerificado"] : null;
$brand = \Models\Modules\Cadastro\BrandRn::getBrand();
$idioma2 = new \Utils\PropertiesUtils("menu", IDIOMA);

$nome = $cliente->nome;
$email = $cliente->email;
$celular = $cliente->celular;
$ddi = !empty($cliente->ddi) ? $cliente->ddi : "55";
$rg = $cliente->rg;
$nomeMae = $cliente->nomeMae;
$nomePai = $cliente->nomePai;
$sexo = $cliente->sexo;
$endereco = $cliente->endereco;
$numero = $cliente->numero;
$complemento = $cliente->complemento;
$bairro = $cliente->bairro;
$cep = $cliente->cep;
$cidade = $cliente->cidade;
$dataNascimento = $cliente->dataNascimento != null ? $cliente->dataNascimento->formatar(Utils\Data::FORMATO_PT_BR) : "";
$twoFactorAuth = $cliente != null && $cliente->twoFactorAuth > 0 ? 1 : 0;
$tipoAutenticacao = $cliente->tipoAutenticacao;
$idPais = $cliente->idPais > 0 ? $cliente->idPais : 0;
$idPaisNaturalidade = $cliente->idPaisNaturalidade > 0 ? $cliente->idPaisNaturalidade : 0;
$cpf = $cliente->documento;

$pin = $cliente->pin;
$fraseSeguranca = $cliente->fraseSeguranca;
$fotoClienteVerificada = $cliente->fotoClienteVerificada;
$fotoResidenciaVerificada = $cliente->fotoResidenciaVerificada;
$fotoDocumentoVerificada = $cliente->fotoDocumentoVerificada;
$fotoOutroDocumentoVerificada = $cliente->fotoOutroDocumentoVerificada;

$documentosEntregue = $clienteVerificado;
if ($configuracao->kyc == 1) {
    if (($fotoDocumentoVerificada == Utils\Constantes::DOCUMENTO_VERIFICADO) && ($fotoResidenciaVerificada == Utils\Constantes::DOCUMENTO_VERIFICADO) && ($fotoClienteVerificada == Utils\Constantes::DOCUMENTO_VERIFICADO)) {
        $documentosEntregue = true;
    }
}

$seguranca = false;
if ($cliente->tipoAutenticacao == \Utils\Constantes::TIPO_AUTH_GOOGLE && !empty($cliente->pin) && !empty($cliente->fraseSeguranca)) {
    $seguranca = true;
}


$dataPin = new Utils\Data("00/00/0000 00:00");
$dataPin->somar(0, 0, 0, $configuracao->horasUpdatePin);
$tempoPin = " 0 dia(s) e {$dataPin->data->format('H')} hora(s).";

$dataFraseSeguranca = new Utils\Data("00/00/0000 00:00");
$dataFraseSeguranca->somar(0, 0, 0, $configuracao->horasUpdateFraseSeguranca);
$tempoFraseSeguranca = " 0 dia(s) e {$dataFraseSeguranca->data->format('H')} hora(s).";

$dataSenha = new Utils\Data("00/00/0000 00:00");
$dataSenha->somar(0, 0, 0, $configuracao->horasUpdateSenha);
$tempoSenha = " {$dataSenha->data->format('d')} dia(s) e {$dataSenha->data->format('H')} hora(s).";

$data2fa = new Utils\Data("00/00/0000 00:00");
$data2fa->somar(0, 0, 0, $configuracao->horasUpdateTwofa);
$tempo2fa = " {$data2fa->data->format('d')} dia(s) e {$data2fa->data->format('H')} hora(s).";

$estadoAtual = $estado->nome;

$motivoRecusaFotoResidencia = $cliente->motivoRecusaFotoResidencia;
$motivoRecusaFotoDocumento = $cliente->motivoRecusaFotoDocumento;
$motivoRecusaFotoOutroDocumento = $cliente->motivoRecusaFotoOutroDocumento;
$motivoRecusaFotoCliente = $cliente->motivoRecusaFotoCliente;

$fotoCliente = $cliente->fotoCliente;
$fotoResidencia = $cliente->fotoResidencia;
$fotoDocumento = $cliente->fotoDocumento;
$fotoDocumentoVerso = $cliente->fotoDocumentoVerso;
$fotoOutroDocumento = $cliente->fotoOutroDocumento;

$documentoTipo = $cliente->documentoTipo;
$utilizaSaqueDepositoBrl = $cliente->utilizaSaqueDepositoBrl;

if (strtolower($sexo) == "m") {
    $foto = TEMA . "dist/img/avatar5.png";
} else {
    $foto = TEMA . "dist/img/avatar2.png";
}

$empresa = \Models\Modules\Cadastro\EmpresaRn::getEmpresa();

if ($documentosEntregue) {
    if ($fotoOutroDocumentoVerificada == \Utils\Constantes::DOCUMENTO_VERIFICADO) {
        $statusConta = $idioma->getText("verificadaPj");
    } else {
        $statusConta = $idioma->getText("verificada");
    }
} else {
    $statusConta = $idioma->getText("basica");
}


$_data["idiomaMenu"] = $idioma;

?>


<style>
    .text-kyc-success {
        color: green;
    }

    .border-edit {
        border: 1px solid #1c84c6 !important;
    }

    .check-success {
        background-color: #1bb394 !important;
        color: #1bb394;
    }

    /* Timeline */
    .timeline,
    .timeline-horizontal {
        list-style: none;
        padding: 20px;
        position: relative;
    }

    .timeline:before {
        top: 40px;
        bottom: 0;
        position: absolute;
        content: " ";
        width: 3px;
        background-color: #eeeeee;
        left: 50%;
        margin-left: -1.5px;
    }

    .timeline .timeline-item {
        margin-bottom: 20px;
        position: relative;

    }

    .timeline .timeline-item:before,
    .timeline .timeline-item:after {
        content: "";
        display: table;
    }

    .timeline .timeline-item:after {
        clear: both;
    }

    .timeline .timeline-item .timeline-badge {
        color: #fff;
        width: 54px;
        height: 54px;
        line-height: 52px;
        font-size: 22px;
        text-align: center;
        position: absolute;
        top: 18px;
        left: 50%;
        margin-left: -25px;
        background-color: #7c7c7c;
        border: 3px solid #ffffff;
        z-index: 100;
        border-top-right-radius: 50%;
        border-top-left-radius: 50%;
        border-bottom-right-radius: 50%;
        border-bottom-left-radius: 50%;

        min-height: 50px;
        max-height: 50px;
    }

    .timeline .timeline-item .timeline-badge i,
    .timeline .timeline-item .timeline-badge .fa,
    .timeline .timeline-item .timeline-badge .glyphicon {
        top: 2px;
        left: 0px;
    }

    .timeline .timeline-item .timeline-badge.primary {
        background-color: #1f9eba;
    }

    .timeline .timeline-item .timeline-badge.info {
        background-color: #5bc0de;
    }

    .timeline .timeline-item .timeline-badge.success {
        background-color: #59ba1f;
    }

    .timeline .timeline-item .timeline-badge.warning {
        background-color: #d1bd10;
    }

    .timeline .timeline-item .timeline-badge.danger {
        background-color: #ba1f1f;
    }

    .timeline .timeline-item .timeline-panel {
        position: relative;
        width: 46%;
        float: left;
        right: 16px;
        border: 1px solid #c0c0c0;
        background: #ffffff;
        border-radius: 2px;
        padding: 20px;
        -webkit-box-shadow: 0 1px 6px rgba(0, 0, 0, 0.175);
        box-shadow: 0 1px 6px rgba(0, 0, 0, 0.175);
        height: 160px;
    }

    .timeline .timeline-item .timeline-panel:before {
        position: absolute;
        top: 26px;
        right: -16px;
        display: inline-block;
        border-top: 16px solid transparent;
        border-left: 16px solid #c0c0c0;
        border-right: 0 solid #c0c0c0;
        border-bottom: 16px solid transparent;
        content: " ";
    }

    .timeline .timeline-item .timeline-panel .timeline-title {
        margin-top: 0;
        color: inherit;
    }

    .timeline .timeline-item .timeline-panel .timeline-body > p,
    .timeline .timeline-item .timeline-panel .timeline-body > ul {
        margin-bottom: 0;
    }

    .timeline .timeline-item .timeline-panel .timeline-body > p + p {
        margin-top: 5px;
    }

    .timeline .timeline-item:last-child:nth-child(even) {
        float: right;
    }

    .timeline .timeline-item:nth-child(even) .timeline-panel {
        float: right;
        left: 16px;
    }

    .timeline .timeline-item:nth-child(even) .timeline-panel:before {
        border-left-width: 0;
        border-right-width: 14px;
        left: -14px;
        right: auto;
    }

    .timeline-horizontal {
        list-style: none;
        position: relative;
        padding: 20px 0px 20px 0px;
        display: inline-block;
        max-width: 30px;
        min-width: 30px;
    }

    .timeline-horizontal:before {
        height: 3px;
        top: auto;
        bottom: 26px;
        left: 56px;
        right: 0;
        margin-bottom: 10px;
    }

    .timeline-horizontal .timeline-item {
        display: table-cell;
        height: 280px;
        width: 20%;
        min-width: 320px;
        float: none !important;
        padding-left: 0px;
        padding-right: 20px;
        margin: 0 auto;
        vertical-align: bottom;
    }

    .timeline-horizontal .timeline-item .timeline-panel {
        top: auto;
        bottom: 64px;
        display: inline-block;
        float: none !important;
        left: 0 !important;
        right: 0 !important;
        width: 100%;
        margin-bottom: 10px;
    }

    .timeline-horizontal .timeline-item .timeline-panel:before {
        top: auto;
        bottom: -16px;
        left: 28px !important;
        right: auto;
        border-right: 16px solid transparent !important;
        border-top: 16px solid #c0c0c0 !important;
        border-bottom: 0 solid #c0c0c0 !important;
        border-left: 16px solid transparent !important;
    }

    .timeline-horizontal .timeline-item:before,
    .timeline-horizontal .timeline-item:after {
        display: none;
    }

    .timeline-horizontal .timeline-item .timeline-badge {
        top: auto;
        bottom: 0px;
        left: 43px;
    }

    .btn-resend {
        margin-top: -5px !important;
        margin-left: -14px !important;
    }
</style>
<?php Utils\Layout::append("inspina/metas", $_data) ?>
<?php Utils\Layout::append("inspina/scripts", $_data) ?>
<?php Utils\Layout::append("inspina/menu", $_data) ?>
<link href="<?php echo TEMA; ?>css.old/plugins/toastr/toastr.min.css" rel="stylesheet"> 
<link href="<?php echo TEMA; ?>css/plugins/switchery/switchery.css" rel="stylesheet">
<link href="<?php echo TEMA; ?>css/plugins/iCheck/custom.css" rel="stylesheet">
<script src="https://code.iconify.design/2/2.2.1/iconify.min.js"></script>
<!-- Main content -->

<body>
  <div class="settings mtb15">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12 col-lg-3">
          <div class="nav flex-column nav-pills settings-nav" id="v-pills-tab" role="tablist"
            aria-orientation="vertical">

            <a class="nav-link active" id="settings-main-tab" data-toggle="pill" href="#settings-main" role="tab"
              aria-controls="settings-main" aria-selected="false"><i class="icon ion-md-bulb"></i> Meu Perfil</a>

            <a class="nav-link" onclick="getDocStats()" id="settings-documentos-tab" data-toggle="pill" href="#settings-documentos" role="tab"
            aria-controls="settings-documentos" aria-selected="false"><i class="icon ion-md-person"></i> <?php echo $idioma->getText("documentos") ?></a>

            <a class="nav-link" id="settings-preferences-tab" data-toggle="pill" href="#settings-preferences" role="tab"
            aria-controls="settings-preferences" aria-selected="false"><i class="icon ion-md-settings"></i> <?php echo $idioma->getText("perfil75") ?></a>

            <a class="nav-link" id="settings-security-tab" data-toggle="pill" href="#settings-security" role="tab"
            aria-controls="settings-security" aria-selected="false"><i class="icon ion-md-lock"></i> <?php echo $idioma->getText("abaSeguranca") ?></a>

            <a class="nav-link" id="settings-bank-tab" data-toggle="pill" href="#settings-banks" role="tab"
            aria-controls="settings-banks" aria-selected="false"><i class="icon ion-md-briefcase"></i> <?php echo $idioma->getText("perfil50") ?></a>

            <a class="nav-link" onclick="listaEmpresa();" id="settings-company-tab" data-toggle="pill" href="#settings-company" role="tab"
            aria-controls="settings-company" aria-selected="false"><i class="icon ion-md-business"></i> <?php echo "Empresa" ?></a>

            <a class="nav-link" id="settings-api-tab" data-toggle="pill" href="#settings-api" role="tab"
            aria-controls="settings-api" aria-selected="false"><i class="icon iconify" data-icon="ion:terminal"></i> <?php echo $idioma->getText("perfil20") ?></a>

            <a class="nav-link" onclick="listaNavegadores();" id="settings-hist-tab" data-toggle="pill" href="#settings-hist" role="tab"
            aria-controls="settings-hist" aria-selected="false"><i class="icon ion-md-exit"></i> <?php echo $idioma->getText("perfil21") ?></a>

            <?php if ($documentosEntregue && $configuracao->aparelhos == 1) { ?>
              <a class="nav-link" onclick="listarDispositivosMobile(); parear();" id="settings-devices-tab" data-toggle="pill" href="#settings-devices" role="tab"
              aria-controls="settings-devices" aria-selected="false"><i class="icon ion-md-phone-portrait"></i> <?php echo $idioma->getText("perfil1") ?></a>
            <?php } ?>
            <a class="nav-link" onclick="meusLimites(); getTaxas();" id="settings-limits-tab" data-toggle="pill" href="#settings-limits" role="tab"
            aria-controls="settings-limits" aria-selected="false"><i class="icon ion-md-cash"></i> <?php echo $idioma->getText("perfil24") ?></a>
            </div>
        </div>
        <div class="col-md-12 col-lg-9">
          <div class="tab-content" id="v-pills-tabContent">

            <div class="tab-pane fade show active" id="settings-main" role="tabpanel" aria-labelledby="settings-main-tab">
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title"><?php echo $idioma2->getText("idioma") ?></h5>
                    <button class="btn btn-sm btn-primary" onclick="javascript:trocarIdioma('pt-BR');"> Português </button>
                    <button class="btn btn-sm btn-primary" onclick="javascript:trocarIdioma('en-US');"> English </button>
                    <button class="btn btn-sm btn-primary" onclick="javascript:trocarIdioma('es-ES');"> Español </button>
                </div>
              </div>

                <div class="card">
                  <div class="card-body">
                    <h5 class="card-title">Notifications</h5>
                    <div class="settings-main">
                      <div>
                          <span class="text-left pull-left">
                              <span class="alert alert-info col-lg-12 col-sm-12 " style="margin-top:10px;display:none">
                                  <!-- TExto de notificação -->
                              </span>
                          </span>
                              <span class="text-right pull-right" style="padding:5px !important;">

                              <button id="btn_kycStart" class="btn btn-link" type="button" id="btn-salvar">
                                  <?php
                                  if ($cliente->documentoVerificado == 0 || $cliente->documentoVerificado == null) {
                                      echo '<div class="badge-danger" style="padding:10px;border-radius:20px;"><i class="fa fa-shield fa-1x" aria-hidden="true"></i>&nbsp;Conta não verificada</div>';
                                  } else if ($cliente->documentoVerificado == 1) {
                                      echo '<div class="badge-primary" style="padding:10px;border-radius:20px;"><i class="fa fa-shield fa-1x" aria-hidden="true"></i>&nbsp;Conta verificada</div>';
                                  } else if ($cliente->documentoVerificado == 2) {
                                      echo '<div class="badge-warning" style="padding:10px;border-radius:20px;"><i class="fa fa-shield fa-1x" aria-hidden="true"></i>&nbsp;Verificação pendente</div>';
                                  } else if ($cliente->documentoVerificado == 3) {
                                      echo '<div class="badge-danger" style="padding:10px;border-radius:20px;"><i class="fa fa-shield fa-1x" aria-hidden="true"></i>&nbsp;Conta não verificada</div>';
                                  }
                                  ?>
                              </button>
                          </span>
                          </div>

                          <div class="">
                            <p>
                              <?php
                              echo '<i class="fa fa-check-circle-o fa-1x text-kyc-success "  aria-hidden="true"></i>&nbsp;E-mail Verificado<br/>';
                              echo '<i class="fa fa-calendar-o fa-1x text-kyc-success "  aria-hidden="true"></i>&nbsp;Cadastrado em ' . $cliente->dataCadastro->formatar(\Utils\Data::FORMATO_PT_BR) . ' <br/>';
                              ?>
                            </p>
                            <!-- <p> </p> -->
                              <?php if ($cliente->documentoVerificado == 1) { ?>
                                <!-- <li class="timeline-item"> -->
                                  <!-- <div class="timeline-badge check-success" style="padding-top:10px;"><i
                                              class="fa fa-check"></i></div> -->
                                  <div class="timeline-panel">
                                    <div class="timeline-heading">
                                      <h6 class="timeline-title">Conta nível I</h6>
                                    </div>
                                      <div class="timeline-body">
                                          <p>
                                              <?php
                                              echo '<i class="fa fa-check-circle-o fa-1x text-kyc-success" aria-hidden="true"></i>&nbsp;Liberação de operações<br/>';
                                              echo '<i class="fa fa-check-circle-o fa-1x text-kyc-success" aria-hidden="true"></i>&nbsp;Saques/Depósitos BRL<br/>';
                                              echo '<i class="fa fa-check-circle-o fa-1x text-kyc-success" aria-hidden="true"></i>&nbsp;Saque/Depósito Cripto<br/>';
                                              ?>
                                          </p>
                                      </div>
                                  </div>
                                </li>
                              <?php } ?>
                              <p>
                              <?php
                                $kyc_status_button = 'disabled';
                                $kyc_status_name = 'verificarContaInicio';
                                if ($cliente->documentoVerificado == 0) {
                                    $kyc_status_button = '';
                                    echo '<i class="fa fa-info-circle  fa-1x " aria-hidden="true"></i>&nbsp;Insira seus dados na aba Documentos</br><i class="fa fa-check-circle-o fa-1x " aria-hidden="true"></i>&nbsp;Documentos pessoais<br/><i class="fa fa-check-circle-o  fa-1x " aria-hidden="true"></i>&nbsp;Selfie<br/>';
                                    // echo '<br/><button id="btn_kycStartBtn" class="btn btn-primary m-b-xs"  type="button" id="btn-salvar" onclick="kycStart()">' . $idioma->getText($kyc_status_name) . '</button>  ';
                                } else if ($cliente->documentoVerificado == 3) {
                                    $kyc_status_name = 'verificarContaPendente';
                                    echo '<i class="fa fa-check-circle-o fa-1x text-danger" aria-hidden="true"></i>&nbsp;Documentos pessoais<br/><i class="fa fa-check-circle-o  fa-1x text-danger" aria-hidden="true"></i>&nbsp;Selfie<br/>';
                                    echo '<small>Não foi possível verificar sua conta</small></br>';
                                    echo '<br/><button id="btn_kycStartBtn" class="btn btn-primary m-b-xs"  type="button" id="btn-salvar" onclick="kycStart()">Verificar novamente</button>  ';
                                } else if ($cliente->documentoVerificado == 2) {
                                    $kyc_status_name = 'verificarContaPendente';
                                    echo '<i class="fa fa-check-circle-o fa-1x text-warning" aria-hidden="true"></i>&nbsp;Documentos pessoais<br/><i class="fa fa-check-circle-o  fa-1x text-warning" aria-hidden="true"></i>&nbsp;Selfie<br/>';
                                    echo '<br/><small>Aguardando você concluir</small><br/><small>Enviamos o e-mail para ' . $cliente->email . ' <br/>
                                            <button id="btn_smsresend" class="btn btn-link btn-resend" type="button" onclick="kycSmsResend()">Reenviar E-mail</small>';
                                } else if ($cliente->documentoVerificado == 1) {
                                    $kyc_status_name = 'verificarContaAprovada';
                                    echo '<i class="fa fa-check-circle-o fa-1x text-kyc-success "  aria-hidden="true"></i>&nbsp;Documentos pessoais<br/><i class="fa fa-check-circle-o  fa-1x text-kyc-success"  aria-hidden="true"></i>&nbsp;Selfie<br/>';
                                    echo '<br/><small>Conta verificada</small>';
                                }
                              ?>
                          </p>
                      </div>
                    </div>
                  </div>
                </div>

                <div class="card">
                  <div class="card-body">
                    <h5 class="card-title">Timeline</h5>
                    <div class="col-lg-5">
                        <div id="vertical-timeline"
                              class="vertical-container light-timeline no-margins">
                            <div class="vertical-timeline-block">
                                <div class="vertical-timeline-icon navy-bg">
                                    <i class="fa fa-user fa-1x"></i>
                                </div>
                                <div class="vertical-timeline-content">
                                    <div class="">
                                        <div class="m-t-md">
                                            <h4 class="">
                                                <?php echo $cliente->nome ?>
                                            </h4>
                                            <small><?php echo $idioma->getText("clienteDesde") ?><?php echo !empty($cliente->dataCadastro) ? $cliente->dataCadastro->formatar(\Utils\Data::FORMATO_PT_BR) : "-" ?></small>
                                            </br>
                                            <?php if ($configuracao->kyc == 1) { ?>
                                                <small>
                                                    <?php echo str_replace("{var}", $statusConta, $idioma->getText("conta")) ?>
                                                </small></br>
                                            <?php } ?>
                                            <small>
                                                <?php echo $idioma->getText("fraseSeguranca") ?><?php echo $fraseSeguranca ?>
                                            </small>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <?php if (!$documentosEntregue) { ?>

                                <div class="vertical-timeline-block">
                                    <div class="vertical-timeline-icon blue-bg">
                                        <i class="fa fa-info fa-1x"></i>
                                    </div>
                                    <div class="vertical-timeline-content">
                                        <strong class="text-center">
                                            <h4><?php echo strtoupper(str_replace("{var}", $brand->nome, $idioma->getText("parabensVoceCliente"))) ?></h4>
                                        </strong>
                                        <strong class="text-center">
                                            <h5><?php echo $idioma->getText("informacoes") ?></h5>
                                        </strong>
                                        <small>
                                            <ul>
                                                <li class="m-t-xs"><?php echo $idioma->getText("todosOsCamposDevem") ?></li>
                                                <li class="m-t-xs"><?php echo $idioma->getText("casoNaoTenhaAlgum") ?></li>
                                                <li class="m-t-xs"><?php echo $idioma->getText("agoraQueVoce2") ?></li>
                                                <li class="m-t-xs"><?php echo $idioma->getText("documentosLiberado") ?></li>
                                            </ul>
                                        </small>
                                    </div>
                                </div>
                            <?php } ?>
                        </div>
                    </div>
                  </div>
                </div>
            </div>

            <div class="tab-pane fade" id="settings-documentos" role="tabpanel"
              aria-labelledby="settings-documentos-tab">
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title"><?php echo $idioma->getText("dadosPessoais2") ?></h5>
                  <div class="settings-profile">
                    <form id="form-perfil"
                      action="<?php echo URLBASE_CLIENT . \Utils\Rotas::R_MEUSDADOS_SALVAR?>"
                      method="POST" enctype="multipart/form-data" autocomplete="off">
                      <div class="form-row mt-4">

                        <div class="col-md-6">
                          <div class="form-group <?php echo(empty($nome) ? "has-error" : "") ?>">
                            <label for="nome"><?php echo $idioma->getText("nome") ?> *</label>
                            <input class="form-control " <?php echo $configuracao->kyc == 0 ? "" : "disabled" ?>  <?php echo $cliente->documentoVerificado == 0 ? "" : "disabled" ?>
                              id="nome"
                              placeholder="<?php echo $idioma->getText("digiteNomeCompleto") ?>"
                              name="nome" maxlength="200"
                              value="<?php echo $nome ?>"/>
                            </div>
                        </div>

                        <div class="col-md-6">
                          <div class="form-group <?php echo(empty($email) ? "has-error" : "") ?>">
                            <label for="email"><?php echo $idioma->getText("email") ?></label>
                            <!-- <input id="formLast" type="text" class="form-control" placeholder="Last name"> -->
                            <input class="form-control" disabled="true" id="email"
                              name="email" maxlength="200"
                              value="<?php echo $email ?>" autocomplete='off'/>
                          </div>
                        </div>

                        <div class="col-md-6">
                          <div class="form-group <?php echo(empty($sexo) ? "has-error" : "") ?>">
                            <label for="sexo"><?php echo $idioma->getText("sexo") ?> *</label>
                            <!-- <input id="emailAddress" type="text" class="form-control" placeholder="Enter your email"> -->
                            <select class="custom-select" name="sexo"
                                id="sexo" <?php //echo $cliente->documentoVerificado == 0 ? "" : " disabled " ?>>
                              <option value="M" <?php echo($sexo == "M" ? "selected" : "") ?>><?php echo $idioma->getText("masculino") ?></option>
                              <option value="F" <?php echo($sexo == "F" ? "selected" : "") ?>><?php echo $idioma->getText("feminino") ?></option>
                            </select>
                          </div>
                        </div>

                        <div class="col-md-6">
                          <div class="form-group <?php echo(empty($dataNascimento) ? "has-error" : "") ?>">
                            <label for="dataNascimento"><?php echo $idioma->getText("nascimento") ?></label>
                            <input type="text"
                              class="form-control" <?php echo $cliente->documentoVerificado == 0 ? "" : " disabled " ?>
                              id="dataNascimento" name="dataNascimento"
                              maxlength="10"
                              value="<?php echo $dataNascimento ?>"/>
                          </div>
                        </div>

                        <div class="col-md-6">
                          <div class="form-group <?php echo(empty($celular) ? "has-error" : "") ?>">
                            <label for="ddi">DDI</label>
                            <select class="custom-select custom-sl"
                                    name="ddi"
                                    id="ddi" <?php echo $cliente->documentoVerificado == 0 ? "" : " disabled " ?>>
                                <?php foreach ($paises as $pais) {
                                    if (!empty($pais->ddi)) { ?>
                                        <option value="<?php echo $pais->ddi ?>" <?php echo(empty($cliente->ddi) && $pais->id == Utils\Constantes::BRASIL
                                          ? "selected='true'" 
                                          : (!empty($cliente->ddi) && $cliente->ddi == $pais->ddi
                                          ? "selected='true'" 
                                          : "")) ?> ><?php echo $pais->nome . " - " . $pais->ddi ?></option>
                                    <?php }
                                } ?>
                            </select>
                          </div>
                        </div>

                        <div class="col-md-6">
                          <div class="form-group <?php echo(empty($celular) ? "has-error" : "") ?>">
                            <label for="celular"><?php echo "DDD + " . $idioma->getText("celular") ?></label>
                            <input class="form-control full-width" id="celular"
                                  name="celular" maxlength="16"
                                  value="<?php echo $celular ?>"/>
                          </div>
                        </div>

                        <div class="col-md-6">
                          <!-- <div class="form-group <?php echo(!($cpf > 0) ? "has-error" : "") ?>"> -->
                            <label for="documentoTipo"><?php echo $idioma->getText("tipoDocumentoTitulo") ?></label>
                            <select style="width: 100%" class="custom-select" name="documentoTipo"
                                    id="documentoTipo" <?php echo $cliente->documentoVerificado == 0 ? "" : " disabled " ?>>
                                <option value="<?php echo \Utils\Constantes::DOCUMENTO_CPF ?>" <?php echo($documentoTipo == \Utils\Constantes::DOCUMENTO_CPF ? "selected" : "") ?>><?php echo $idioma->getText("tipoDocumento" . Utils\Constantes::DOCUMENTO_CPF) ?></option>
                            </select>
                          <!-- </div> -->
                        </div>

                        <div class="col-md-6">
                          <!-- <div class="form-group <?php echo(!($cpf > 0) ? "has-error" : "") ?>"> -->
                            <label for="cpf"><?php echo $idioma->getText("documento") ?></label>
                            <input class="form-control" <?php echo $cliente->documentoVerificado == 0 ? "" : " disabled " ?>
                                    id="cpf" name="cpf" maxlength="20"
                                    value="<?php echo $cpf ?>"/>
                          <!-- </div> -->
                        </div>

                        <div class="col-md-6">
                          <div class="form-group <?php echo(!($idPais > 0) ? "has-error" : "") ?>">
                            <label for="pais"><?php echo $idioma->getText("paisNaturalidade") ?></label>
                            <select class="custom-select" name="idPaisNaturalidade"
                                id="pais">
                              <option value="<?php echo \Utils\Criptografia::encriptyPostId(0) ?>"><?php echo $idioma->getText("selecionePaisNaturalidade") ?></option>
                              <?php foreach ($paises as $pais) { ?>

                                  <option value="<?php echo \Utils\Criptografia::encriptyPostId($pais->id) ?>" <?php echo(($idPaisNaturalidade > 0 && $pais->id === $idPaisNaturalidade) ? "selected='true'" : "") ?>> <?php echo $pais->nome ?></option>
                              <?php } ?>
                            </select>
                          </div>
                        </div>

                        <div class="col-md-6">
                          <div class="form-group <?php echo(empty($cep) ? "has-error" : "") ?>">
                            <label for="cep">CEP</label>
                            <input class="form-control full-width" id="cep"
                                  name="cep" maxlength="8"
                                  value="<?php echo $cep ?>"/>
                          </div>
                        </div>

                        <div class="col-md-6">
                          <div class="form-group <?php echo(empty($endereco) ? "has-error" : "") ?>">
                            <label for="endereco">Logradouro</label>
                            <input class="form-control full-width" id="endereco"
                                  name="endereco" maxlength="32"
                                  value="<?php echo $endereco ?>"/>
                          </div>
                        </div>

                        <div class="col-md-6">
                          <div class="form-group <?php echo(empty($numero) ? "has-error" : "") ?>">
                            <label for="numero">Numero</label>
                            <input class="form-control full-width" id="numero"
                                  name="numero" maxlength="16"
                                  value="<?php echo $numero ?>"/>
                          </div>
                        </div>

                        <div class="col-md-6">
                          <div class="form-group <?php echo(empty($cliente->cidade) ? "has-error" : "") ?>">
                            <label for="cidade">Cidade</label>
                            <input class="form-control full-width" id="cidade"
                                  name="cidade" maxlength="23"
                                  value="<?php echo $cliente->cidade ?>"/>
                          </div>
                        </div>

                        <div class="col-md-6">
                          <div class="form-group <?php echo(empty($bairro) ? "has-error" : "") ?>">
                            <label for="bairro">Bairro</label>
                            <input class="form-control full-width" id="bairro"
                                  name="bairro" maxlength="30"
                                  value="<?php echo $bairro ?>"/>
                          </div>
                        </div>

                        <div class="col-md-6">
                          <div class="form-group <?php echo(empty($cliente->estado) ? "has-error" : "") ?>">
                            <label for="estado">UF</label>
                            <input class="form-control full-width" id="estado"
                                  name="estado" maxlength="2"
                                  value="<?php echo $cliente->estado ?>"/>
                          </div>
                        </div>

                        <div class="col-md-6">
                          <div class="form-group <?php echo(empty($complemento) ? "has-error" : "") ?>">
                            <label for="complemento">Complemento</label>
                            <input class="form-control full-width" id="complemento"
                                  name="complemento" maxlength="50"
                                  value="<?php echo $complemento ?>"/>
                          </div>
                        </div>

                        <div class="col-md-12">
                          <input type="submit" value="<?php echo $idioma->getText("salvarAlteracaoPerfilBtn") ?>" id="btn-salvar">
                        </div>
                      </div>
                    </form>
                  </div>
                </div>
              </div>

              <div class="card">
                <div class="card-body">
                  <h5 class="card-title">Documentos</h5>
                  <div class="settings-profile">

                    <form id="form-documentos"
                      action="<?php echo URLBASE_CLIENT . \Utils\Rotas::R_KYC_ENVIAR_DOCS?>"
                      method="POST" enctype="multipart/form-data" autocomplete="off"
                    >
                      <div class="form-row mt-4">

                        <div class="col-md-6">
                          <div class="form-group">
                            <!-- <div class="custom-file "> -->
                              <input type="file" class="custom-file-input" name="frente" id="frente">
                              <label class="custom-file-label" for="doc_front">CNH/RG Frente</label>
                            <!-- </div> -->
                          </div>
                        </div>

                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

                        <div class="col-md-5">
                          <div class="form-group" id="st-frente">
                            <!-- status -->
                          </div>
                        </div>

                        <div class="col-md-6">
                          <div class="form-group">
                            <!-- <div class="custom-file"> -->
                              <input type="file" class="custom-file-input" name="verso" id="verso">
                              <label class="custom-file-label" for="doc_back">CNH/RG Verso</label>
                            <!-- </div> -->
                          </div>
                        </div>

                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

                        <div class="col-md-5">
                          <div class="form-group" id="st-verso">
                            status
                          </div>
                        </div>

                        <div class="col-md-6">
                          <div class="form-group">
                            <!-- <div class="custom-file"> -->
                              <input type="file" class="custom-file-input" name="selfie" id="selfie">
                              <label class="custom-file-label" for="doc_selfie">Selfie com Documento</label>
                            <!-- </div> -->
                          </div>
                        </div>

                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

                        <div class="col-md-5">
                          <div class="form-group" id="st-selfie">
                            status
                          </div>
                        </div>

                        <div class="col-md-12">
                          <input type="submit" value="Enviar" id="btn-salvar-docs">
                        </div>
                      </div>
                    </form>

                  </div>
                </div>
              </div>
            </div>

            <div class="tab-pane fade" id="settings-preferences" role="tabpanel"
              aria-labelledby="settings-preferences-tab">
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title"><?php echo $idioma->getText("perfil76") ?></h5>

                  <div class="settings-profile">
                    <div class="form-group">
                      <div class="i-checks text-left"  >
                          <div class="icheckbox_square-green " style="position: relative;">
                              <input type="checkbox" id="market_check" name="market_check"
                                    value="<?php echo $cliente->campanhaMarketReceber === 1 ? true : false; ?>"
                                    <?php echo $cliente->campanhaMarketReceber ? 'checked' : ''; ?>
                                    class="doc"

                              >
                          </div>&nbsp;&nbsp;
                          <label  >
                              <?php echo $idioma->getText("perfil77") ?>
                          </label>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <!-- <div class="tab-pane fade" id="settings-preferences" role="tabpanel" aria-labelledby="settings-wallet-tab">
              <div class="wallet">
                <div class="row">
                  <div class="col-md-12 col-lg-4">
                    <div class="nav flex-column nav-pills" role="tablist" aria-orientation="vertical">
                      <a class="nav-link d-flex justify-content-between align-items-center active" data-toggle="pill"
                        href="#coinBTC" role="tab" aria-selected="true">
                        <div class="d-flex">
                          <img src="assets/img/icon/18.png" alt="btc">
                          <div>
                            <h2>BTC</h2>
                            <p>Bitcoin</p>
                          </div>
                        </div>
                        <div>
                          <h3>4.5484254</h3>
                          <p class="text-right"><i class="icon ion-md-lock"></i> 0.0000000</p>
                        </div>
                      </a>
                      <a class="nav-link d-flex justify-content-between align-items-center" data-toggle="pill"
                        href="#coinETH" role="tab" aria-selected="true">
                        <div class="d-flex">
                          <img src="assets/img/icon/1.png" alt="btc">
                          <div>
                            <h2>ETH</h2>
                            <p>Ethereum</p>
                          </div>
                        </div>
                        <div>
                          <h3>13.454845</h3>
                          <p class="text-right"><i class="icon ion-md-lock"></i> 0.0000000</p>
                        </div>
                      </a>
                      <a class="nav-link d-flex justify-content-between align-items-center" data-toggle="pill"
                        href="#coinBNB" role="tab" aria-selected="true">
                        <div class="d-flex">
                          <img src="assets/img/icon/9.png" alt="btc">
                          <div>
                            <h2>BNB</h2>
                            <p>Binance</p>
                          </div>
                        </div>
                        <div>
                          <h3>35.4842458</h3>
                          <p class="text-right"><i class="icon ion-md-lock"></i> 0.0000000</p>
                        </div>
                      </a>
                      <a class="nav-link d-flex justify-content-between align-items-center" data-toggle="pill"
                        href="#coinTRX" role="tab" aria-selected="true">
                        <div class="d-flex">
                          <img src="assets/img/icon/6.png" alt="btc">
                          <div>
                            <h2>TRX</h2>
                            <p>Tron</p>
                          </div>
                        </div>
                        <div>
                          <h3>4.458941</h3>
                          <p class="text-right"><i class="icon ion-md-lock"></i> 0.0000000</p>
                        </div>
                      </a>
                      <a class="nav-link d-flex justify-content-between align-items-center" data-toggle="pill"
                        href="#coinEOS" role="tab" aria-selected="true">
                        <div class="d-flex">
                          <img src="assets/img/icon/2.png" alt="btc">
                          <div>
                            <h2>EOS</h2>
                            <p>Eosio</p>
                          </div>
                        </div>
                        <div>
                          <h3>33.478951</h3>
                          <p class="text-right"><i class="icon ion-md-lock"></i> 0.0000000</p>
                        </div>
                      </a>
                      <a class="nav-link d-flex justify-content-between align-items-center" data-toggle="pill"
                        href="#coinXMR" role="tab" aria-selected="true">
                        <div class="d-flex">
                          <img src="assets/img/icon/7.png" alt="btc">
                          <div>
                            <h2>XMR</h2>
                            <p>Monero</p>
                          </div>
                        </div>
                        <div>
                          <h3>99.465975</h3>
                          <p class="text-right"><i class="icon ion-md-lock"></i> 0.0000000</p>
                        </div>
                      </a>
                      <a class="nav-link d-flex justify-content-between align-items-center" data-toggle="pill"
                        href="#coinKCS" role="tab" aria-selected="true">
                        <div class="d-flex">
                          <img src="assets/img/icon/4.png" alt="btc">
                          <div>
                            <h2>KCS</h2>
                            <p>Kstarcoin</p>
                          </div>
                        </div>
                        <div>
                          <h3>114.57564</h3>
                          <p class="text-right"><i class="icon ion-md-lock"></i> 0.0000000</p>
                        </div>
                      </a>
                    </div>
                  </div>
                  <div class="col-md-12 col-lg-8">
                    <div class="tab-content">
                      <div class="tab-pane fade show active" id="coinBTC" role="tabpanel">
                        <div class="card">
                          <div class="card-body">
                            <h5 class="card-title">Balances</h5>
                            <ul>
                              <li class="d-flex justify-content-between align-items-center">
                                <div class="d-flex align-items-center">
                                  <i class="icon ion-md-cash"></i>
                                  <h2>Total Equity</h2>
                                </div>
                                <div>
                                  <h3>5.5894 BTC</h3>
                                </div>
                              </li>
                              <li class="d-flex justify-content-between align-items-center">
                                <div class="d-flex align-items-center">
                                  <i class="icon ion-md-checkmark"></i>
                                  <h2>Available Margin</h2>
                                </div>
                                <div>
                                  <h3>2.480 BTC</h3>
                                </div>
                              </li>
                            </ul>
                            <button class="btn green">Deposit</button>
                            <button class="btn red">Withdraw</button>
                          </div>
                        </div>
                        <div class="card">
                          <div class="card-body">
                            <h5 class="card-title">Wallet Deposit Address</h5>
                            <div class="row wallet-address">
                              <div class="col-md-8">
                                <p>Deposits to this address are unlimited. Note that you may not be able to withdraw all
                                  of your
                                  funds at once if you deposit more than your daily withdrawal limit.</p>
                                <div class="input-group">
                                  <input type="text" class="form-control" value="Ad87deD4gEe8dG57Ede4eEg5dREs4d5e8f4e">
                                  <div class="input-group-prepend">
                                    <button class="btn btn-primary">COPY</button>
                                  </div>
                                </div>
                              </div>
                              <div class="col-md-4">
                                <img src="assets/img/qr-code-dark.svg" alt="qr-code">
                              </div>
                            </div>
                          </div>
                        </div>
                        <div class="card">
                          <div class="card-body">
                            <h5 class="card-title">Latest Transactions</h5>
                            <div class="wallet-history">
                              <table class="table">
                                <thead>
                                  <tr>
                                    <th>No.</th>
                                    <th>Date</th>
                                    <th>Status</th>
                                    <th>Amount</th>
                                  </tr>
                                </thead>
                                <tbody>
                                  <tr>
                                    <td>1</td>
                                    <td>25-04-2019</td>
                                    <td><i class="icon ion-md-checkmark-circle-outline green"></i></td>
                                    <td>4.5454334</td>
                                  </tr>
                                  <tr>
                                    <td>2</td>
                                    <td>25-05-2019</td>
                                    <td><i class="icon ion-md-checkmark-circle-outline green"></i></td>
                                    <td>0.5484468</td>
                                  </tr>
                                  <tr>
                                    <td>3</td>
                                    <td>25-06-2019</td>
                                    <td><i class="icon ion-md-close-circle-outline red"></i></td>
                                    <td>2.5454545</td>
                                  </tr>
                                  <tr>
                                    <td>4</td>
                                    <td>25-07-2019</td>
                                    <td><i class="icon ion-md-checkmark-circle-outline green"></i></td>
                                    <td>1.45894147</td>
                                  </tr>
                                  <tr>
                                    <td>3</td>
                                    <td>25-08-2019</td>
                                    <td><i class="icon ion-md-close-circle-outline red"></i></td>
                                    <td>2.5454545</td>
                                  </tr>
                                </tbody>
                              </table>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="tab-pane fade" id="coinETH" role="tabpanel">
                        <div class="card">
                          <div class="card-body">
                            <h5 class="card-title">Balances</h5>
                            <ul>
                              <li class="d-flex justify-content-between align-items-center">
                                <div class="d-flex align-items-center">
                                  <i class="icon ion-md-cash"></i>
                                  <h2>Total Equity</h2>
                                </div>
                                <div>
                                  <h3>4.1542 ETH</h3>
                                </div>
                              </li>
                              <li class="d-flex justify-content-between align-items-center">
                                <div class="d-flex align-items-center">
                                  <i class="icon ion-md-checkmark"></i>
                                  <h2>Available Margin</h2>
                                </div>
                                <div>
                                  <h3>1.334 ETH</h3>
                                </div>
                              </li>
                            </ul>
                            <button class="btn green">Deposit</button>
                            <button class="btn red">Withdraw</button>
                          </div>
                        </div>
                        <div class="card">
                          <div class="card-body">
                            <h5 class="card-title">Wallet Deposit Address</h5>
                            <div class="row wallet-address">
                              <div class="col-md-8">
                                <p>Deposits to this address are unlimited. Note that you may not be able to withdraw all
                                  of your
                                  funds at once if you deposit more than your daily withdrawal limit.</p>
                                <div class="input-group">
                                  <input type="text" class="form-control" value="Ad87deD4gEe8dG57Ede4eEg5dREs4d5e8f4e">
                                  <div class="input-group-prepend">
                                    <button class="btn btn-primary">COPY</button>
                                  </div>
                                </div>
                              </div>
                              <div class="col-md-4">
                                <img src="assets/img/qr-code-dark.svg" alt="qr-code">
                              </div>
                            </div>
                          </div>
                        </div>
                        <div class="card">
                          <div class="card-body">
                            <h5 class="card-title">Latest Transactions</h5>
                            <div class="wallet-history">
                              <table class="table">
                                <thead>
                                  <tr>
                                    <th>No.</th>
                                    <th>Date</th>
                                    <th>Status</th>
                                    <th>Amount</th>
                                  </tr>
                                </thead>
                                <tbody>
                                  <tr>
                                    <td>1</td>
                                    <td>25-04-2019</td>
                                    <td><i class="icon ion-md-checkmark-circle-outline green"></i></td>
                                    <td>4.5454334</td>
                                  </tr>
                                  <tr>
                                    <td>2</td>
                                    <td>25-05-2019</td>
                                    <td><i class="icon ion-md-checkmark-circle-outline green"></i></td>
                                    <td>0.5484468</td>
                                  </tr>
                                  <tr>
                                    <td>3</td>
                                    <td>25-06-2019</td>
                                    <td><i class="icon ion-md-close-circle-outline red"></i></td>
                                    <td>2.5454545</td>
                                  </tr>
                                  <tr>
                                    <td>4</td>
                                    <td>25-07-2019</td>
                                    <td><i class="icon ion-md-checkmark-circle-outline green"></i></td>
                                    <td>1.45894147</td>
                                  </tr>
                                  <tr>
                                    <td>3</td>
                                    <td>25-08-2019</td>
                                    <td><i class="icon ion-md-close-circle-outline red"></i></td>
                                    <td>2.5454545</td>
                                  </tr>
                                </tbody>
                              </table>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="tab-pane fade" id="coinBNB" role="tabpanel">
                        <div class="card">
                          <div class="card-body">
                            <h5 class="card-title">Balances</h5>
                            <ul>
                              <li class="d-flex justify-content-between align-items-center">
                                <div class="d-flex align-items-center">
                                  <i class="icon ion-md-cash"></i>
                                  <h2>Total Equity</h2>
                                </div>
                                <div>
                                  <h3>7.342 BNB</h3>
                                </div>
                              </li>
                              <li class="d-flex justify-content-between align-items-center">
                                <div class="d-flex align-items-center">
                                  <i class="icon ion-md-checkmark"></i>
                                  <h2>Available Margin</h2>
                                </div>
                                <div>
                                  <h3>0.332 BNB</h3>
                                </div>
                              </li>
                            </ul>
                            <button class="btn green">Deposit</button>
                            <button class="btn red">Withdraw</button>
                          </div>
                        </div>
                        <div class="card">
                          <div class="card-body">
                            <h5 class="card-title">Wallet Deposit Address</h5>
                            <div class="row wallet-address">
                              <div class="col-md-8">
                                <p>Deposits to this address are unlimited. Note that you may not be able to withdraw all
                                  of your
                                  funds at once if you deposit more than your daily withdrawal limit.</p>
                                <div class="input-group">
                                  <input type="text" class="form-control" value="Ad87deD4gEe8dG57Ede4eEg5dREs4d5e8f4e">
                                  <div class="input-group-prepend">
                                    <button class="btn btn-primary">COPY</button>
                                  </div>
                                </div>
                              </div>
                              <div class="col-md-4">
                                <img src="assets/img/qr-code-dark.svg" alt="qr-code">
                              </div>
                            </div>
                          </div>
                        </div>
                        <div class="card">
                          <div class="card-body">
                            <h5 class="card-title">Latest Transactions</h5>
                            <div class="wallet-history">
                              <table class="table">
                                <thead>
                                  <tr>
                                    <th>No.</th>
                                    <th>Date</th>
                                    <th>Status</th>
                                    <th>Amount</th>
                                  </tr>
                                </thead>
                                <tbody>
                                  <tr>
                                    <td>1</td>
                                    <td>25-04-2019</td>
                                    <td><i class="icon ion-md-checkmark-circle-outline green"></i></td>
                                    <td>4.5454334</td>
                                  </tr>
                                  <tr>
                                    <td>2</td>
                                    <td>25-05-2019</td>
                                    <td><i class="icon ion-md-checkmark-circle-outline green"></i></td>
                                    <td>0.5484468</td>
                                  </tr>
                                  <tr>
                                    <td>3</td>
                                    <td>25-06-2019</td>
                                    <td><i class="icon ion-md-close-circle-outline red"></i></td>
                                    <td>2.5454545</td>
                                  </tr>
                                  <tr>
                                    <td>4</td>
                                    <td>25-07-2019</td>
                                    <td><i class="icon ion-md-checkmark-circle-outline green"></i></td>
                                    <td>1.45894147</td>
                                  </tr>
                                  <tr>
                                    <td>3</td>
                                    <td>25-08-2019</td>
                                    <td><i class="icon ion-md-close-circle-outline red"></i></td>
                                    <td>2.5454545</td>
                                  </tr>
                                </tbody>
                              </table>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="tab-pane fade" id="coinTRX" role="tabpanel">
                        <div class="card">
                          <div class="card-body">
                            <h5 class="card-title">Balances</h5>
                            <ul>
                              <li class="d-flex justify-content-between align-items-center">
                                <div class="d-flex align-items-center">
                                  <i class="icon ion-md-cash"></i>
                                  <h2>Total Equity</h2>
                                </div>
                                <div>
                                  <h3>4.3344 TRX</h3>
                                </div>
                              </li>
                              <li class="d-flex justify-content-between align-items-center">
                                <div class="d-flex align-items-center">
                                  <i class="icon ion-md-checkmark"></i>
                                  <h2>Available Margin</h2>
                                </div>
                                <div>
                                  <h3>1.453 TRX</h3>
                                </div>
                              </li>
                            </ul>
                            <button class="btn green">Deposit</button>
                            <button class="btn red">Withdraw</button>
                          </div>
                        </div>
                        <div class="card">
                          <div class="card-body">
                            <h5 class="card-title">Wallet Deposit Address</h5>
                            <div class="row wallet-address">
                              <div class="col-md-8">
                                <p>Deposits to this address are unlimited. Note that you may not be able to withdraw all
                                  of your
                                  funds at once if you deposit more than your daily withdrawal limit.</p>
                                <div class="input-group">
                                  <input type="text" class="form-control" value="Ad87deD4gEe8dG57Ede4eEg5dREs4d5e8f4e">
                                  <div class="input-group-prepend">
                                    <button class="btn btn-primary">COPY</button>
                                  </div>
                                </div>
                              </div>
                              <div class="col-md-4">
                                <img src="assets/img/qr-code-dark.svg" alt="qr-code">
                              </div>
                            </div>
                          </div>
                        </div>
                        <div class="card">
                          <div class="card-body">
                            <h5 class="card-title">Latest Transactions</h5>
                            <div class="wallet-history">
                              <table class="table">
                                <thead>
                                  <tr>
                                    <th>No.</th>
                                    <th>Date</th>
                                    <th>Status</th>
                                    <th>Amount</th>
                                  </tr>
                                </thead>
                                <tbody>
                                  <tr>
                                    <td>1</td>
                                    <td>25-04-2019</td>
                                    <td><i class="icon ion-md-checkmark-circle-outline green"></i></td>
                                    <td>4.5454334</td>
                                  </tr>
                                  <tr>
                                    <td>2</td>
                                    <td>25-05-2019</td>
                                    <td><i class="icon ion-md-checkmark-circle-outline green"></i></td>
                                    <td>0.5484468</td>
                                  </tr>
                                  <tr>
                                    <td>3</td>
                                    <td>25-06-2019</td>
                                    <td><i class="icon ion-md-close-circle-outline red"></i></td>
                                    <td>2.5454545</td>
                                  </tr>
                                  <tr>
                                    <td>4</td>
                                    <td>25-07-2019</td>
                                    <td><i class="icon ion-md-checkmark-circle-outline green"></i></td>
                                    <td>1.45894147</td>
                                  </tr>
                                  <tr>
                                    <td>3</td>
                                    <td>25-08-2019</td>
                                    <td><i class="icon ion-md-close-circle-outline red"></i></td>
                                    <td>2.5454545</td>
                                  </tr>
                                </tbody>
                              </table>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="tab-pane fade" id="coinEOS" role="tabpanel">
                        <div class="card">
                          <div class="card-body">
                            <h5 class="card-title">Balances</h5>
                            <ul>
                              <li class="d-flex justify-content-between align-items-center">
                                <div class="d-flex align-items-center">
                                  <i class="icon ion-md-cash"></i>
                                  <h2>Total Equity</h2>
                                </div>
                                <div>
                                  <h3>33.35 EOS</h3>
                                </div>
                              </li>
                              <li class="d-flex justify-content-between align-items-center">
                                <div class="d-flex align-items-center">
                                  <i class="icon ion-md-checkmark"></i>
                                  <h2>Available Margin</h2>
                                </div>
                                <div>
                                  <h3>4.445 EOS</h3>
                                </div>
                              </li>
                            </ul>
                            <button class="btn green">Deposit</button>
                            <button class="btn red">Withdraw</button>
                          </div>
                        </div>
                        <div class="card">
                          <div class="card-body">
                            <h5 class="card-title">Wallet Deposit Address</h5>
                            <div class="row wallet-address">
                              <div class="col-md-8">
                                <p>Deposits to this address are unlimited. Note that you may not be able to withdraw all
                                  of your
                                  funds at once if you deposit more than your daily withdrawal limit.</p>
                                <div class="input-group">
                                  <input type="text" class="form-control" value="Ad87deD4gEe8dG57Ede4eEg5dREs4d5e8f4e">
                                  <div class="input-group-prepend">
                                    <button class="btn btn-primary">COPY</button>
                                  </div>
                                </div>
                              </div>
                              <div class="col-md-4">
                                <img src="assets/img/qr-code-dark.svg" alt="qr-code">
                              </div>
                            </div>
                          </div>
                        </div>
                        <div class="card">
                          <div class="card-body">
                            <h5 class="card-title">Latest Transactions</h5>
                            <div class="wallet-history">
                              <table class="table">
                                <thead>
                                  <tr>
                                    <th>No.</th>
                                    <th>Date</th>
                                    <th>Status</th>
                                    <th>Amount</th>
                                  </tr>
                                </thead>
                                <tbody>
                                  <tr>
                                    <td>1</td>
                                    <td>25-04-2019</td>
                                    <td><i class="icon ion-md-checkmark-circle-outline green"></i></td>
                                    <td>4.5454334</td>
                                  </tr>
                                  <tr>
                                    <td>2</td>
                                    <td>25-05-2019</td>
                                    <td><i class="icon ion-md-checkmark-circle-outline green"></i></td>
                                    <td>0.5484468</td>
                                  </tr>
                                  <tr>
                                    <td>3</td>
                                    <td>25-06-2019</td>
                                    <td><i class="icon ion-md-close-circle-outline red"></i></td>
                                    <td>2.5454545</td>
                                  </tr>
                                  <tr>
                                    <td>4</td>
                                    <td>25-07-2019</td>
                                    <td><i class="icon ion-md-checkmark-circle-outline green"></i></td>
                                    <td>1.45894147</td>
                                  </tr>
                                  <tr>
                                    <td>3</td>
                                    <td>25-08-2019</td>
                                    <td><i class="icon ion-md-close-circle-outline red"></i></td>
                                    <td>2.5454545</td>
                                  </tr>
                                </tbody>
                              </table>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="tab-pane fade" id="coinXMR" role="tabpanel">
                        <div class="card">
                          <div class="card-body">
                            <h5 class="card-title">Balances</h5>
                            <ul>
                              <li class="d-flex justify-content-between align-items-center">
                                <div class="d-flex align-items-center">
                                  <i class="icon ion-md-cash"></i>
                                  <h2>Total Equity</h2>
                                </div>
                                <div>
                                  <h3>34.333 XMR</h3>
                                </div>
                              </li>
                              <li class="d-flex justify-content-between align-items-center">
                                <div class="d-flex align-items-center">
                                  <i class="icon ion-md-checkmark"></i>
                                  <h2>Available Margin</h2>
                                </div>
                                <div>
                                  <h3>2.354 XMR</h3>
                                </div>
                              </li>
                            </ul>
                            <button class="btn green">Deposit</button>
                            <button class="btn red">Withdraw</button>
                          </div>
                        </div>
                        <div class="card">
                          <div class="card-body">
                            <h5 class="card-title">Wallet Deposit Address</h5>
                            <div class="row wallet-address">
                              <div class="col-md-8">
                                <p>Deposits to this address are unlimited. Note that you may not be able to withdraw all
                                  of your
                                  funds at once if you deposit more than your daily withdrawal limit.</p>
                                <div class="input-group">
                                  <input type="text" class="form-control" value="Ad87deD4gEe8dG57Ede4eEg5dREs4d5e8f4e">
                                  <div class="input-group-prepend">
                                    <button class="btn btn-primary">COPY</button>
                                  </div>
                                </div>
                              </div>
                              <div class="col-md-4">
                                <img src="assets/img/qr-code-dark.svg" alt="qr-code">
                              </div>
                            </div>
                          </div>
                        </div>
                        <div class="card">
                          <div class="card-body">
                            <h5 class="card-title">Latest Transactions</h5>
                            <div class="wallet-history">
                              <table class="table">
                                <thead>
                                  <tr>
                                    <th>No.</th>
                                    <th>Date</th>
                                    <th>Status</th>
                                    <th>Amount</th>
                                  </tr>
                                </thead>
                                <tbody>
                                  <tr>
                                    <td>1</td>
                                    <td>25-04-2019</td>
                                    <td><i class="icon ion-md-checkmark-circle-outline green"></i></td>
                                    <td>4.5454334</td>
                                  </tr>
                                  <tr>
                                    <td>2</td>
                                    <td>25-05-2019</td>
                                    <td><i class="icon ion-md-checkmark-circle-outline green"></i></td>
                                    <td>0.5484468</td>
                                  </tr>
                                  <tr>
                                    <td>3</td>
                                    <td>25-06-2019</td>
                                    <td><i class="icon ion-md-close-circle-outline red"></i></td>
                                    <td>2.5454545</td>
                                  </tr>
                                  <tr>
                                    <td>4</td>
                                    <td>25-07-2019</td>
                                    <td><i class="icon ion-md-checkmark-circle-outline green"></i></td>
                                    <td>1.45894147</td>
                                  </tr>
                                  <tr>
                                    <td>3</td>
                                    <td>25-08-2019</td>
                                    <td><i class="icon ion-md-close-circle-outline red"></i></td>
                                    <td>2.5454545</td>
                                  </tr>
                                </tbody>
                              </table>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="tab-pane fade" id="coinKCS" role="tabpanel">
                        <div class="card">
                          <div class="card-body">
                            <h5 class="card-title">Balances</h5>
                            <ul>
                              <li class="d-flex justify-content-between align-items-center">
                                <div class="d-flex align-items-center">
                                  <i class="icon ion-md-cash"></i>
                                  <h2>Total Equity</h2>
                                </div>
                                <div>
                                  <h3>86.577 KCS</h3>
                                </div>
                              </li>
                              <li class="d-flex justify-content-between align-items-center">
                                <div class="d-flex align-items-center">
                                  <i class="icon ion-md-checkmark"></i>
                                  <h2>Available Margin</h2>
                                </div>
                                <div>
                                  <h3>5.78 KCS</h3>
                                </div>
                              </li>
                            </ul>
                            <button class="btn green">Deposit</button>
                            <button class="btn red">Withdraw</button>
                          </div>
                        </div>
                        <div class="card">
                          <div class="card-body">
                            <h5 class="card-title">Wallet Deposit Address</h5>
                            <div class="row wallet-address">
                              <div class="col-md-8">
                                <p>Deposits to this address are unlimited. Note that you may not be able to withdraw all
                                  of your
                                  funds at once if you deposit more than your daily withdrawal limit.</p>
                                <div class="input-group">
                                  <input type="text" class="form-control" value="Ad87deD4gEe8dG57Ede4eEg5dREs4d5e8f4e">
                                  <div class="input-group-prepend">
                                    <button class="btn btn-primary">COPY</button>
                                  </div>
                                </div>
                              </div>
                              <div class="col-md-4">
                                <img src="assets/img/qr-code-dark.svg" alt="qr-code">
                              </div>
                            </div>
                          </div>
                        </div>
                        <div class="card">
                          <div class="card-body">
                            <h5 class="card-title">Latest Transactions</h5>
                            <div class="wallet-history">
                              <table class="table">
                                <thead>
                                  <tr>
                                    <th>No.</th>
                                    <th>Date</th>
                                    <th>Status</th>
                                    <th>Amount</th>
                                  </tr>
                                </thead>
                                <tbody>
                                  <tr>
                                    <td>1</td>
                                    <td>25-04-2019</td>
                                    <td><i class="icon ion-md-checkmark-circle-outline green"></i></td>
                                    <td>4.5454334</td>
                                  </tr>
                                  <tr>
                                    <td>2</td>
                                    <td>25-05-2019</td>
                                    <td><i class="icon ion-md-checkmark-circle-outline green"></i></td>
                                    <td>0.5484468</td>
                                  </tr>
                                  <tr>
                                    <td>3</td>
                                    <td>25-06-2019</td>
                                    <td><i class="icon ion-md-close-circle-outline red"></i></td>
                                    <td>2.5454545</td>
                                  </tr>
                                  <tr>
                                    <td>4</td>
                                    <td>25-07-2019</td>
                                    <td><i class="icon ion-md-checkmark-circle-outline green"></i></td>
                                    <td>1.45894147</td>
                                  </tr>
                                  <tr>
                                    <td>3</td>
                                    <td>25-08-2019</td>
                                    <td><i class="icon ion-md-close-circle-outline red"></i></td>
                                    <td>2.5454545</td>
                                  </tr>
                                </tbody>
                              </table>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div> -->

            <div class="tab-pane fade" id="settings-security" role="tabpanel" aria-labelledby="settings-tab">
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title"><?php echo $idioma->getText("perfil55") ?></h5>
                  <!-- <div class="settings-notification">
                    <ul>
                      <li>
                        <div class="notification-info">
                          <p>Update price</p>
                          <span>Get the update price in your dashboard</span>
                        </div>
                        <div class="custom-control custom-switch">
                          <input type="checkbox" class="custom-control-input" id="notification1">
                          <label class="custom-control-label" for="notification1"></label>
                        </div>
                      </li>
                      <li>
                        <div class="notification-info">
                          <p>2FA</p>
                          <span>Unable two factor authentication service</span>
                        </div>
                        <div class="custom-control custom-switch">
                          <input type="checkbox" class="custom-control-input" id="notification2" checked>
                          <label class="custom-control-label" for="notification2"></label>
                        </div>
                      </li>
                      <li>
                        <div class="notification-info">
                          <p>Latest news</p>
                          <span>Get the latest news in your mail</span>
                        </div>
                        <div class="custom-control custom-switch">
                          <input type="checkbox" class="custom-control-input" id="notification3">
                          <label class="custom-control-label" for="notification3"></label>
                        </div>
                      </li>
                      <li>
                        <div class="notification-info">
                          <p>Email Service</p>
                          <span>Get security code in your mail</span>
                        </div>
                        <div class="custom-control custom-switch">
                          <input type="checkbox" class="custom-control-input" id="notification4" checked>
                          <label class="custom-control-label" for="notification4"></label>
                        </div>
                      </li>
                      <li>
                        <div class="notification-info">
                          <p>Phone Notify</p>
                          <span>Get transition notification in your phone </span>
                        </div>
                        <div class="custom-control custom-switch">
                          <input type="checkbox" class="custom-control-input" id="notification5" checked>
                          <label class="custom-control-label" for="notification5"></label>
                        </div>
                      </li>
                    </ul>
                  </div> -->
                  <!-- <div class="row"> -->
                                    <div class="col-lg-7">
                                        <div id="alterarSenha">
                                            <form id="form-alterar-senha"
                                                  action="<?php echo URLBASE_CLIENT . Utils\Rotas::R_MEUSDADOS_SENHA_ATUALIZAR ?>"
                                                  method="post" enctype="multipart/form-data" autocomplete="off">
                                                <h3 class="page-header m-t-xs">
                                                    <strong><?php echo $idioma->getText("alterarSenha") ?></strong></h3>
                                                <div class="row" id="row-form-alteracao-senha">
                                                    <div class="col col-sm-12">
                                                        <div class="row">
                                                            <div class="col-sm-3 ">
                                                                <div class="form-group">
                                                                    <label><?php echo $idioma->getText("senhaAtual") ?></label>
                                                                    <input type="password" class="form-control"
                                                                           id="senhaAtual" name="senhaAtual"
                                                                           maxlength="200" style="font-size: 20px;"/>
                                                                </div>
                                                            </div>
                                                            <div class="col-sm-4 ">
                                                                <div class="form-group">
                                                                    <label><?php echo $idioma->getText("novaSenha") ?></label>
                                                                    <input type="password" class="form-control"
                                                                          id="senha" name="senha" maxlength="200"
                                                                          style="font-size: 20px;"/>
                                                                    <div class="progress m-t-xs" style="height: 5px;">
                                                                        <div style="width: 0%;" aria-valuemax="100"
                                                                            aria-valuemin="0" aria-valuenow="35"
                                                                            role="progressbar" class="progress-bar"
                                                                            id="barraForcaSenha"></div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                            <div class="col-sm-3">
                                                                <div class="form-group">
                                                                    <label><?php echo $idioma->getText("confirmarSenha") ?></label>
                                                                    <div class="input-group">
                                                                        <input type="password"
                                                                                class="input-sm form-control"
                                                                                id="confirmacao" name="confirmacao"
                                                                                maxlength="200" style="font-size: 20px">
                                                                        <span class="input-group-btn">
                                                                          <!-- <button class="btn btn-sm  btn-primary"
                                                                                  id="btn-pwd-matches">
                                                                              <i class="fa fa-check"></i>
                                                                          </button>  -->
                                                                        </span>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                            <div class="col-sm-1 ">
                                                                <div class="form-group">
                                                                    <div class="input-group">
                                                                        <span class="input-group-btn">
                                                                    <label>&nbsp;&nbsp;&nbsp;</label>
                                                                          <button class="btn btn-sm  btn-primary"
                                                                                  id="btn-pwd-matches">
                                                                              <i class="fa fa-check"></i>
                                                                          </button> 
                                                                        </span>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="row">
                                                            <div class="col-sm-4 ">
                                                                <button class="btn btn-primary full-width" type="submit"
                                                                        id="btnAlterarSenha">
                                                                    <?php echo $idioma->getText("altararSenhaBtn") ?>
                                                                </button>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                        <div id="seguranca" class="m-t-lg">
                                            <form id="form-seguranca"
                                                  action="<?php echo URLBASE_CLIENT . Utils\Rotas::R_MEUSDADOS_SEGURANCA_ATUALIZAR ?>"
                                                  method="post" enctype="multipart/form-data" autocomplete="off">
                                                <div class="">
                                                    <h3 class="page-header m-t-none">
                                                        <strong><?php echo $idioma->getText("pinFrase") ?></strong></h3>
                                                </div>
                                                <div class="">
                                                    <div class="row">
                                                        <?php if (empty($pin)) { ?>
                                                            <div class="col-lg-6">
                                                                <div class="form-group">
                                                                    <label><?php echo $idioma->getText("pin") ?></label>
                                                                    <input type="number" inputmode="numeric"
                                                                          pattern="[0-9]*" min="0"
                                                                          style="-webkit-text-security:disc; font-size: 30px;"
                                                                          ng-model="loginData.pincode"
                                                                          class="form-control" id="pin" name="pin"
                                                                          maxlength="4" value=""
                                                                          style="font-size: 30px"/>
                                                                </div>
                                                            </div>
                                                            <div class="col-lg-6">
                                                                <div class="form-group">
                                                                    <label><?php echo $idioma->getText("confirmePin") ?></label>
                                                                    <input type="number" inputmode="numeric"
                                                                           pattern="[0-9]*" min="0"
                                                                           style="-webkit-text-security:disc; font-size: 30px;"
                                                                           ng-model="loginData.pincode"
                                                                           class="form-control" id="confirmarPin"
                                                                           name="confirmarPin" maxlength="4" value=""
                                                                           style="font-size: 30px"/>
                                                                </div>
                                                            </div>
                                                        <?php } else { ?>
                                                            <div class="col-lg-12">
                                                                <div class="form-group">
                                                                    <label><?php echo $idioma->getText("pin") ?>:
                                                                        **** </label><br>
                                                                    <p><?php echo $idioma->getText("entreContatoSac") ?>
                                                                        <a href="<?php echo "mailto:" . $empresa->emailSuporte ?>"><?php echo $empresa->emailSuporte ?></a>
                                                                    </p>
                                                                </div>
                                                            </div>
                                                        <?php } ?>
                                                    </div>
                                                    <div class="row">
                                                        <div class="col-sm-12">
                                                            <div class="form-group">
                                                                <label><?php echo $idioma->getText("fraseSeguranca2") ?></label>
                                                                <input type="text" class="form-control text-center"
                                                                      id="fraseSeguranca" name="fraseSeguranca"
                                                                      maxlength="50"
                                                                      value="<?php echo $fraseSeguranca ?>"/>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="row">
                                                        <div class="col-sm-12">
                                                            <fieldset>
                                                                <input type="hidden" id="tipoAutenticacaoToken"
                                                                        name="tipoAutenticacaoToken"/>
                                                                <input type="hidden" id="authSecretHidden"
                                                                        name="authSecretHidden"/>
                                                                <label><?php echo $idioma->getText("autenticacao2passos") ?></label><br>
                                                                <div class="radio radio-inline">
                                                                    <input type="radio" name="tipoAutenticacao"
                                                                            id="tipoAutenticacaoEmail" <?php echo($tipoAutenticacao == \Utils\Constantes::TIPO_AUTH_EMAIL ? "checked" : "") ?>
                                                                            value="email" checked="">
                                                                    <label for="tipoAutenticacaoEmail"><?php echo $idioma->getText("emailOp") ?></label>
                                                                </div>
                                                                </br>
                                                                <div class="radio radio-inline">
                                                                    <input type="radio" name="tipoAutenticacao"
                                                                            id="tipoAutenticacaoGoogle" <?php echo($tipoAutenticacao == \Utils\Constantes::TIPO_AUTH_GOOGLE ? "checked" : "") ?>
                                                                            value="google">
                                                                    <label for="tipoAutenticacaoGoogle"><?php echo $idioma->getText("googleOp") ?></label>
                                                                </div>
                                                                </br></br>
                                                                <?php if ($cliente->tipoAutenticacao != \Utils\Constantes::TIPO_AUTH_GOOGLE) { ?>
                                                                    <div class="row" id="google-auth-container"
                                                                          style="display: none;">
                                                                        <div class="col col-lg-12">
                                                                            <div class="alert alert-info text-center">
                                                                                <strong><?php echo $idioma->getText("chaveSecreta") ?> </strong><br>
                                                                                <h4 id="authSecret"></h4>
                                                                                <img src=""
                                                                                     style="height: 200px; width: 200px;"
                                                                                     id="authSecretQrCode"/> <br>

                                                                                <small><?php echo $idioma->getText("digiteCodigoAcimaGoogle") ?></small>
                                                                            </div>
                                                                            </br>
                                                                            <div class="form-group">
                                                                                <label><?php echo $idioma->getText("informeCodigoGerado") ?></label>
                                                                                <input class="form-control"
                                                                                       id="authCodigo2faAtivar"
                                                                                       name="authCodigo2faAtivar"
                                                                                       maxlength="6"/>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                <?php } ?>
                                                            </fieldset>
                                                            <div class="form-group" id="tokenChange" hidden="true">
                                                                <label id="msgToken">Token</label>&nbsp;<a
                                                                        id="reenviarToken" hidden="true"
                                                                        onclick="modalConfirmarAlteracao();"><?php echo $idioma->getText("reenviarToken") ?></a>
                                                                <input class="form-control" type="number"
                                                                       id="tokenConfirm"/>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    </br>
                                                    <div class="row">
                                                        <div class="col-xs-12 col-sm-6">
                                                            <button class="btn btn-primary full-width" type="button"
                                                                    id="btn-salvar-seguranca"
                                                                    onclick="confirmarAlteracao();">
                                                                <?php echo $idioma->getText("salvarConfiguracoesSegurancaBtn") ?>
                                                            </button>
                                                        </div>
                                                    </div>
                                                    </br>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                    <div class="col-lg-5">
                                        <div id="vertical-timeline"
                                             class="vertical-container light-timeline no-margins">
                                            <div class="vertical-timeline-block">
                                                <div class="vertical-timeline-icon navy-bg">
                                                    <i class="fa fa-info fa-1x"></i>
                                                </div>
                                                <div class="vertical-timeline-content">
                                                    <strong class="text-center">
                                                        <h5><?php echo $idioma->getText("criacaoSenha") ?></h5></strong>
                                                    <small>
                                                        <ul>
                                                            <li class="m-t-xs"><?php echo $idioma->getText("naoCrieSequencia") ?></li>
                                                            <li class="m-t-xs"><?php echo $idioma->getText("naoUseDadosPessoais") ?></li>
                                                            <li class="m-t-xs"><?php echo $idioma->getText("senhaDeveConter") ?>
                                                                <ul>
                                                                    <li><?php echo $idioma->getText("digitoSenha") ?></li>
                                                                    <li><?php echo $idioma->getText("1letraMaiuscula") ?></li>
                                                                    <li><?php echo $idioma->getText("1numero") ?></li>
                                                                    <li><?php echo $idioma->getText("1caractereEspecial") ?></li>
                                                                </ul>
                                                            </li>
                                                            <li class="m-t-xs"><?php echo $idioma->getText("naoPasseSuaSenha") ?></li>
                                                            <li class="m-t-xs"><?php echo $idioma->getText("aconselhamosUsoGoogle") ?></li>
                                                        </ul>
                                                    </small>
                                                </div>
                                            </div>
                                            <div class="vertical-timeline-block">
                                                <div class="vertical-timeline-icon blue-bg">
                                                    <i class="fa fa-info fa-1x"></i>
                                                </div>

                                                <div class="vertical-timeline-content">
                                                    <strong class="text-center">
                                                        <h5><?php echo $idioma->getText("informacoesSeguranca") ?></h5>
                                                    </strong>
                                                    <small>
                                                        <ul style="text-align: justify;">
                                                            <li class="m-t-xs">Caso você atualize seu modo de usar o
                                                                2FA, deverá fazer a verificação de conta novamente.
                                                            </li>
                                                            <li class="m-t-xs"><?php echo $idioma->getText("aposAtualizar") ?></li>
                                                            <ul>
                                                                <li><?php echo str_replace("{var}", $tempoFraseSeguranca, $idioma->getText("tempoFraseSeguranca")) ?></li>
                                                                <li><?php echo str_replace("{var}", $tempoPin, $idioma->getText("tempoPin")) ?></li>
                                                                <li><?php echo str_replace("{var}", $tempoSenha, $idioma->getText("tempoSenha")) ?></li>
                                                                <li><?php echo str_replace("{var}", $tempo2fa, $idioma->getText("tempo2fa")) ?></li>
                                                            </ul>
                                                            <li class="m-t-xs"><?php echo $idioma->getText("oPinDeSegurancaCodigo") ?></li>
                                                            <li class="m-t-xs"><?php echo $idioma->getText("aFraseDeSegurancaFormaReduzir") ?></li>
                                                            <li class="m-t-xs"><?php echo $idioma->getText("aAutenticaoEmDoisPassos") ?></li>
                                                        </ul>
                                                    </small>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                <!-- </div> -->
              </div>
                <!-- <div class="card settings-profile">
                  <div class="card-body">
                    <h5 class="card-title">Create API Key</h5>
                    <div class="form-row">
                      <div class="col-md-6">
                        <label for="generateKey">Generate key name</label>
                        <input id="generateKey" type="text" class="form-control" placeholder="Enter your key name">
                      </div>
                      <div class="col-md-6">
                        <label for="rewritePassword">Confirm password</label>
                        <input id="rewritePassword" type="password" class="form-control"
                          placeholder="Confirm your password">
                      </div>
                      <div class="col-md-12">
                        <input type="submit" value="Create API key">
                      </div>
                    </div>
                  </div>
                </div> -->

              <!-- <div class="card">
                <div class="card-body">
                  <h5 class="card-title">Your API Keys</h5>
                  <div class="wallet-history">
                    <table class="table">
                      <thead>
                        <tr>
                          <th>No.</th>
                          <th>Key</th>
                          <th>Status</th>
                          <th>Action</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td>1</td>
                          <td>zRmWVcrAZ1C0RZkFMu7K5v0KWC9jUJLt</td>
                          <td>
                            <div class="custom-control custom-switch">
                              <input type="checkbox" class="custom-control-input" id="apiStatus1" checked>
                              <label class="custom-control-label" for="apiStatus1"></label>
                            </div>
                          </td>
                          <td><i class="icon ion-md-trash"></i></td>
                        </tr>
                        <tr>
                          <td>2</td>
                          <td>Rv5dgnKdmVPyHwxeExBYz8uFwYQz3Jvg</td>
                          <td>
                            <div class="custom-control custom-switch">
                              <input type="checkbox" class="custom-control-input" id="apiStatus2">
                              <label class="custom-control-label" for="apiStatus2"></label>
                            </div>
                          </td>
                          <td><i class="icon ion-md-trash"></i></td>
                        </tr>
                        <tr>
                          <td>3</td>
                          <td>VxEYIs1HwgmtKTUMA4aknjSEjjePZIWu</td>
                          <td>
                            <div class="custom-control custom-switch">
                              <input type="checkbox" class="custom-control-input" id="apiStatus3">
                              <label class="custom-control-label" for="apiStatus3"></label>
                            </div>
                          </td>
                          <td><i class="icon ion-md-trash"></i></td>
                        </tr>
                        <tr>
                          <td>4</td>
                          <td>M01DueJ4x3awI1SSLGT3CP1EeLSnqt8o</td>
                          <td>
                            <div class="custom-control custom-switch">
                              <input type="checkbox" class="custom-control-input" id="apiStatus4">
                              <label class="custom-control-label" for="apiStatus4"></label>
                            </div>
                          </td>
                          <td><i class="icon ion-md-trash"></i></td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div> -->
            </div>

            <div class="tab-pane fade" id="settings-banks" role="tabpanel" aria-labelledby="settings-banks-tab">
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title"> <?php echo $idioma->getText("perfil56")?> </h5>
                  <!-- <div class="settings-notification">
                    <ul>
                      <li>
                        <div class="notification-info">
                          <p>Update price</p>
                          <span>Get the update price in your dashboard</span>
                        </div>
                        <div class="custom-control custom-switch">
                          <input type="checkbox" class="custom-control-input" id="notification1">
                          <label class="custom-control-label" for="notification1"></label>
                        </div>
                      </li>
                      <li>
                        <div class="notification-info">
                          <p>2FA</p>
                          <span>Unable two factor authentication service</span>
                        </div>
                        <div class="custom-control custom-switch">
                          <input type="checkbox" class="custom-control-input" id="notification2" checked>
                          <label class="custom-control-label" for="notification2"></label>
                        </div>
                      </li>
                      <li>
                        <div class="notification-info">
                          <p>Latest news</p>
                          <span>Get the latest news in your mail</span>
                        </div>
                        <div class="custom-control custom-switch">
                          <input type="checkbox" class="custom-control-input" id="notification3">
                          <label class="custom-control-label" for="notification3"></label>
                        </div>
                      </li>
                      <li>
                        <div class="notification-info">
                          <p>Email Service</p>
                          <span>Get security code in your mail</span>
                        </div>
                        <div class="custom-control custom-switch">
                          <input type="checkbox" class="custom-control-input" id="notification4" checked>
                          <label class="custom-control-label" for="notification4"></label>
                        </div>
                      </li>
                      <li>
                        <div class="notification-info">
                          <p>Phone Notify</p>
                          <span>Get transition notification in your phone </span>
                        </div>
                        <div class="custom-control custom-switch">
                          <input type="checkbox" class="custom-control-input" id="notification5" checked>
                          <label class="custom-control-label" for="notification5"></label>
                        </div>
                      </li>
                    </ul>
                  </div> -->
                  <div class="row">
                      <div class="col-lg-7">
                          <div class="row">
                              <div class="col-lg-6">
                                  <div class="form-group">
                                      <label><?php echo $idioma->getText("nomeTitular") ?></label>
                                      <input type="text" class="form-control" id="nomeTitular"
                                              disabled="true" value="<?php echo $cliente->nome ?>"/>
                                  </div>
                              </div>
                              <div class="col-lg-5">
                                  <div class="form-group">
                                      <label><?php echo $idioma->getText("documento") ?></label>
                                      <select class="form-control" id="documentoConta">
                                          <option value="<?php echo \Utils\Criptografia::encriptyPostId(\Utils\Constantes::DOCUMENTO_CPF) ?>"><?php echo "CPF: " . $cliente->documento ?></option>
                                          <?php if (!empty($cliente->cnpj)) { ?>
                                              <option value="<?php echo \Utils\Criptografia::encriptyPostId(\Utils\Constantes::DOCUMENTO_CNPJ) ?>"><?php echo "CNPJ: " . $cliente->cnpj ?></option>
                                          <?php } ?>
                                      </select>

                                  </div>
                              </div>
                          </div>
                          <div class="row">
                              <div class="col-lg-6">
                                  <div class="form-group">
                                      <label><?php echo $idioma->getText("instituicaoBancariaC") ?></label>
                                      <select class="form-control select2-selection__rendered"
                                              id="cadastroContaIdBanco" style="width: 100%;">
                                          <option value="0">
                                              <?php echo $idioma->getText("seleInstiBancariaC") ?>
                                          </option>
                                          <?php foreach ($bancos as $banco) { ?>
                                              <option value="<?php echo $banco->id ?>">
                                                  <?php echo "{$banco->codigo}-{$banco->nome}"; ?>
                                              </option>
                                          <?php } ?>
                                      </select>
                                  </div>
                              </div>
                              <div class="col-lg-5">
                                  <div class="form-group">
                                      <label><?php echo $idioma->getText("tipoContaC") ?></label>
                                      <select class="form-control" id="cadastroContaTipoConta">
                                          <option value="<?php echo Utils\Constantes::CONTA_CORRENTE ?>"><?php echo $idioma->getText("contaCorrenteC") ?></option>
                                      </select>
                                  </div>
                              </div>
                          </div>
                          <div class="row">
                              <div class="col-lg-6">
                                  <div class="form-group">
                                      <label><?php echo $idioma->getText("agenciaC") ?></label>
                                      <input type="text" class="form-control" id="cadastroContaAgencia"
                                              maxlength="10" minlength="4"/>
                                  </div>
                              </div>
                              <div class="col-lg-5">
                                  <div class="form-group">
                                      <label><?php echo $idioma->getText("agenciaDigitoC") ?></label>
                                      <input type="text" class="form-control"
                                              id="cadastroContaAgenciaDigito" maxlength="1"/>
                                  </div>
                              </div>
                          </div>
                          <div class="row">
                              <div class="col-lg-6">
                                  <div class="form-group">
                                      <label><?php echo $idioma->getText("contaC") ?></label>
                                      <input type="text" class="form-control" id="cadastroContaConta"
                                              maxlength="10"/>
                                  </div>
                              </div>
                              <div class="col-lg-5">
                                  <div class="form-group">
                                      <label><?php echo $idioma->getText("contaDigitoC") ?></label>
                                      <input type="text" class="form-control"
                                              id="cadastroContaContaDigito" maxlength="1"/>
                                  </div>
                              </div>
                          </div>
                          <div class="row">
                              <div class="col-lg-4">
                                  <button type="button" class="btn btn-primary text-center full-width"
                                          onclick="salvarConta();"
                                          id="cadastroContaSalvar"><?php echo $idioma->getText("salvarContaC") ?></button>
                              </div>
                          </div>
                          </br>
                          </br>
                      </div>
                      <div class="col-lg-5">
                          <div id="vertical-timeline"
                                class="vertical-container light-timeline no-margins">
                              <div class="vertical-timeline-block">
                                  <div class="vertical-timeline-icon blue-bg">
                                      <i class="fa fa-info fa-1x"></i>
                                  </div>
                                  <div class="vertical-timeline-content">
                                      <strong class="text-center">
                                          <h5><?php echo $idioma->getText("informacoes") ?> </h5></strong>
                                      <small>
                                          <ul>
                                              <li class="m-t-xs"><?php echo $idioma->getText("cadastreApenas") ?></li>
                                          </ul>
                                      </small>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
                </div>
              </div>
            </div>

            <div class="tab-pane fade" id="settings-company" role="tabpanel"
              aria-labelledby="settings-company-tab">
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title">Empresa</h5>
                    <div class="panel-body">
                      <div class="row">
                          <div class="col-lg-12">
                              <h3 class="page-header m-t-xs"><strong>Associar Empresa</strong></h3>
                          </div>
                      </div>
                      <div class="row">
                          <div class="col-lg-7">
                              <div class="row">
                                  <div class="col-lg-4">
                                      <div class="form-group">
                                          <label><?php echo "CNPJ" ?></label>
                                          <input type="text" class="form-control"
                                                  id="cnpj" <?php echo empty($cliente->cnpj) ? "" : "readonly" ?>/>
                                      </div>
                                  </div>
                                  <div class="col-lg-8">
                                      <div class="form-group">
                                          <label><?php echo "Razão Social" ?></label>
                                          <input type="text" class="form-control" id="razaoSocial"
                                                  readonly="true"/>
                                      </div>
                                  </div>
                              </div>
                              <div class="row">
                                  <div class="col-lg-4">
                                      <?php if (empty($cliente->cnpj)) { ?>
                                          <button type="button" class="btn btn-primary text-center full-width"
                                                  id="btn-salvar-cnpj"
                                                  onclick="salvarCnpj();"><?php echo "Salvar Empresa" ?></button>
                                      <?php } ?>
                                  </div>
                              </div>
                              </br>
                              </br>
                          </div>
                          <div class="col-lg-5">
                              <div id="vertical-timeline"
                                    class="vertical-container light-timeline no-margins">
                                  <div class="vertical-timeline-block">
                                      <div class="vertical-timeline-icon blue-bg">
                                          <i class="fa fa-info fa-1x"></i>
                                      </div>
                                      <div class="vertical-timeline-content">
                                          <strong class="text-center">
                                              <h5><?php echo $idioma->getText("informacoes") ?> </h5></strong>
                                          <small>
                                              <ul>
                                                  <li class="m-t-xs"><?php echo $idioma->getText("perfil57") ?></li>
                                                  <li class="m-t-xs"><?php echo $idioma->getText("perfil58") ?></li>
                                              </ul>
                                          </small>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                    </div>
                </div>
              </div>
            </div>

            <div class="tab-pane fade" id="settings-api" role="tabpanel"
              aria-labelledby="settings-api-tab">
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title"><?php echo $idioma->getText("perfil20")?></h5>
                    <div class="panel-body">
                    <div class="row">
                          <div class="col-lg-7">
                              <div class="row">
                                  <div class="col-lg-12">
                                      <h4><?php echo $idioma->getText("perfil61") ?></h4>
                                  </div>
                              </div>
                              <div class="row m-t-md" id="solicitarApi">
                                  <div class="col-lg-12 text-center">
                                      <button class="btn btn-primary" type="button"
                                              onclick="getTokenApiKey();" id="btnGetTokenApi">
                                          <strong><?php echo $idioma->getText("perfil63") ?></strong></button>
                                  </div>
                              </div>
                              <div class="row m-t-md" id="solicitarApiToken" hidden="true">
                                  <div class="col-lg-6">
                                      <div class="form-group">
                                          <label><?php echo $idioma->getText("perfil62") ?></label>
                                          <input type="text" class="form-control full-width" id="tokenApi"
                                                  maxlength="6" minlength="6"/>
                                      </div>
                                  </div>
                                  <div class="col-lg-6">
                                      <div class="form-group">
                                          <label>&nbsp;&nbsp;</label>
                                          <button class="btn btn-success full-width" type="button"
                                                  onclick="gerarApiKey();" id="btnGerarTokenApi">
                                              <strong><?php echo $idioma->getText("perfil64") ?></strong>
                                          </button>
                                      </div>
                                  </div>
                              </div>
                          </div>
                          <div class="col col-lg-5 m-t-xs">
                              <div id="vertical-timeline"
                                    class="vertical-container light-timeline no-margins">
                                  <div class="vertical-timeline-block">
                                      <div class="vertical-timeline-icon blue-bg">
                                          <i class="fa fa-info fa-1x"></i>
                                      </div>
                                      <div class="vertical-timeline-content">
                                          <strong class="text-center">
                                              <h5><?php echo $idioma->getText("cuidadosComSuaApi") ?></h5>
                                          </strong>
                                          <small>
                                              <ul>
                                                  <li class="m-t-xs"><?php echo $idioma->getText("perfil71") ?></li>
                                                  <li><?php echo $idioma->getText("essaChaveSecreta") ?></li>
                                                  <li class="m-t-xs"><?php echo $idioma->getText("naoPodeSerCompartilhada") ?></li>
                                                  <li class="m-t-xs"><?php echo $idioma->getText("naoPodeUsadaOutrosSistemas") ?></li>
                                                  <li class="m-t-xs"><?php echo $idioma->getText("perfil70") ?></li>
                                              </ul>
                                          </small>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                    </div>
                </div>
              </div>
            </div>

            <div class="tab-pane fade" id="settings-hist" role="tabpanel"
              aria-labelledby="settings-hist-tab">
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title"><?php echo $idioma->getText("perfil65") ?> </h5>
                    <div class="row">
                      <div class=" col-lg-12 table-responsive m-t-sm">
                          <table id="tblnavegadores" class="table table-striped text-center"
                                data-page-size="14" style="font-size: 11px;">
                              <thead>
                              <tr>
                                  <th class="text-center"><?php echo $idioma->getText("navegador1") ?></th>
                                  <th class="text-center"><?php echo $idioma->getText("navegador3") ?></th>
                                  <th class="text-center"><?php echo $idioma->getText("navegador2") ?></th>
                                  <th class="text-center"><?php echo $idioma->getText("navegador4") ?></th>
                                  <th class="text-center"><?php echo $idioma->getText("navegador5") ?></th>
                              </tr>
                              </thead>
                              <tbody id="listaNavegadores">

                              </tbody>
                              <tfoot>
                              <tr>
                                  <td colspan="5">
                                      <ul class="pagination pull-right"></ul>
                                  </td>
                              </tr>
                              </tfoot>
                          </table>
                      </div>
                  </div>
                </div>
              </div>
            </div>

            <div class="tab-pane fade" id="settings-devices" role="tabpanel"
              aria-labelledby="settings-devices-tab">
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title"><?php echo $idioma->getText("perfil66") ?></h5>
                  <div class="panel-body">
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <h3 class="page-header m-t-xs">
                                                <strong><?php echo $idioma->getText("perfil66") ?></strong></h3>
                                        </div>
                                    </div>
                                    <div class="row" id="">
                                        <div class="col col-sm-7">
                                            <h3 class="page-header m-t-xs">
                                                <strong><?php echo $idioma->getText("perfil67") ?></strong></h3>
                                            <div class="row">
                                                <div class="col-sm-12">
                                                    <div class="row">
                                                        <div class="col-lg-12 text-center">
                                                            <img class="m-b-sm m-t-sm"
                                                                 src='<?php echo IMAGES ?>loading.gif'
                                                                 id="qrcodeDispositivo" width="158" height="158"/></br>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <br>
                                        </div>
                                        <div class="col-sm-5">
                                            <div id="vertical-timeline"
                                                 class="vertical-container light-timeline no-margins">
                                                <div class="vertical-timeline-block">
                                                    <div class="vertical-timeline-icon blue-bg">
                                                        <i class="fa fa-info fa-1x"></i>
                                                    </div>
                                                    <div class="vertical-timeline-content">
                                                        <strong class="text-center">
                                                            <h5><?php echo $idioma->getText("informacoes") ?></h5>
                                                        </strong>
                                                        <small>
                                                            <ul>
                                                                <li class="m-t-xs"><?php echo $idioma->getText("perfil68") ?></li>
                                                            </ul>
                                                        </small>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    </br></br>
                                    <div class="ibox-content">
                                        <h3 class="page-header m-t-xs"><strong><?php echo "Dispositivos" ?></strong>
                                        </h3>
                                        <div class="table-responsive m-t-sm">
                                            <table id="tblaparelhos" class="table table-striped text-center"
                                                   data-page-size="14" style="font-size: 11px;">
                                                <thead>
                                                <tr>
                                                    <th class="text-center">
                                                        <strong><?php echo $idioma->getText("perfil2") ?></strong></th>
                                                    <th class="text-center">
                                                        <strong><?php echo $idioma->getText("perfil3") ?></strong></th>
                                                    <th class="text-center">
                                                        <strong><?php echo $idioma->getText("perfil6") ?></strong></th>
                                                    <th class="text-center">
                                                        <strong><?php echo $idioma->getText("perfil7") ?></strong></th>
                                                    <th class="text-center">
                                                        <strong><?php echo $idioma->getText("perfil9") ?></strong></th>
                                                    <th class="text-center">
                                                        <strong><?php echo $idioma->getText("perfil10") ?></strong></th>
                                                </tr>
                                                </thead>
                                                <tbody id="lista-dispositivos-mobile">
                                                </tbody>
                                                <tfoot>
                                                <tr>
                                                    <td colspan="6">
                                                        <ul class="pagination pull-right"></ul>
                                                    </td>
                                                </tr>
                                                </tfoot>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                </div>
              </div>
            </div>

            <div class="tab-pane fade" id="settings-limits" role="tabpanel"
              aria-labelledby="settings-limits-tab">
              <div class="card">
                <div class="card-body">
                  <!-- <h5 class="card-title"><?php echo $idioma->getText("perfil69")?></h5> -->
                  <h5 class="card-title"><?php echo $idioma->getText("limite25") ?></h5>
                    <div class="panel-body">
                    <div class="row">
                          <div class="col-lg-12">
                              <div class="ibox m-b-none">
                                  <div class="ibox-content">
                                      <div class="table-responsive" style="margin-top: 5px;">
                                          <input type="text"
                                                  class="form-control input-sm m-b-xs col-offset-4 col-lg-2"
                                                  id="filterCriptomoedas"
                                                  placeholder="<?php echo $idioma->getText("limite22") ?>"
                                                  style="margin-bottom: 10px !important;" autocomplete="false">
                                          <table id="tblCriptomoedas" class="table table-stripped text-center"
                                                  data-page-size="8" data-filter=#filterCriptomoedas
                                                  style="font-size: 11px;">
                                              <thead>
                                              <tr>
                                                  <th class="text-center"><?php echo $idioma->getText("limite17") ?></th>
                                                  <th class="text-center"><?php echo $idioma->getText("limite18") ?></th>
                                                  <th class="text-center"><?php echo $idioma->getText("limite19") ?></th>
                                                  <th class="text-center"><?php echo $idioma->getText("limite20") ?></th>
                                                  <th class="text-center"><?php echo $idioma->getText("limite21") ?></th>
                                                  <th class="text-center"><?php echo $idioma->getText("limite29") ?></th>
                                                  <th class="text-center"><?php echo $idioma->getText("limite30") ?></th>
                                                  <th class="text-center"><?php echo $idioma->getText("limite31") ?></th>
                                                  <th class="text-center"><?php echo $idioma->getText("limite32") ?></th>
                                              </tr>
                                              </thead>
                                              <tbody id="">
                                              <?php foreach ($taxasMoedas as $infMoeda) { ?>
                                                  <tr class="" style="">
                                                      <td class="text-center"><img
                                                                  src="<?php echo IMAGES ?>currencies/<?php echo $infMoeda["icone"] ?>"
                                                                  style="width: 20px; height: 20px;"/></td>
                                                      <td class="text-center"><?php echo $infMoeda["sigla"] ?></td>
                                                      <td class="text-center"><?php echo $infMoeda["nome"] ?></td>


                                                      <td class="text-center"><?php
                                                          if (empty($infMoeda["moedaTaxa"])) {
                                                              echo $infMoeda["taxaTrans"] . " " . $infMoeda["sigla"];
                                                          } else {
                                                              if (empty($infMoeda["taxaMoedaTransferencia"])) {
                                                                  echo $infMoeda["taxaMoedaTaxa"] . " " . $infMoeda["simboloMoedaTaxa"];
                                                              } else {
                                                                  echo $infMoeda["taxaMoedaTransferencia"] . " " . $infMoeda["simboloMoedaTaxa"];
                                                              }
                                                          }
                                                          ?></td>


                                                      <td class="text-center"><?php echo $infMoeda["minConfirm"] ?></td>
                                                      <td class="text-center"><?php echo $infMoeda["compraAtiva"] ?>
                                                          %
                                                      </td>
                                                      <td class="text-center"><?php echo $infMoeda["vendaAtiva"] ?>
                                                          %
                                                      </td>
                                                      <td class="text-center"><?php echo $infMoeda["compraPassiva"] ?>
                                                          %
                                                      </td>
                                                      <td class="text-center"><?php echo $infMoeda["vendaPassiva"] ?>
                                                          %
                                                      </td>
                                                  </tr>
                                              <?php } ?>
                                              </tbody>
                                              <tfoot>
                                              <tr>
                                                  <td colspan="9">
                                                      <ul class="pagination pull-right"></ul>
                                                  </td>
                                              </tr>
                                              </tfoot>
                                          </table>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                    </div>
                </div>
              </div>
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title"><?php echo $idioma->getText("limite24") ?></h5>
                    <div class="panel-body">
                    <div class="row">
                          <div class="col-lg-12">
                                  <div class="ibox-content">
                                      <div class="table-responsive" style="margin-top: 5px;">
                                          <input type="text"
                                                  class="form-control input-sm m-b-xs col-offset-4 col-lg-2"
                                                  id="filterReais"
                                                  placeholder="<?php echo $idioma->getText("limite22") ?>"
                                                  style="margin-bottom: 10px !important;" autocomplete="false">

                                          <table id="tblTaxasReais" class="table table-stripped"
                                                  data-page-size="8" data-filter=#filterReais
                                                  style="font-size: 11px;">
                                              <thead>
                                              <tr>
                                                  <th class="text-center"><?php echo $idioma->getText("limite26") ?></th>
                                                  <th class="text-center"><?php echo $idioma->getText("limite27") ?></th>
                                                  <th class="text-center"><?php echo $idioma->getText("limite28") ?></th>
                                              </tr>
                                              </thead>
                                              <tbody id="tblTaxa">
                                              <tr>
                                                  <td><?php echo $idioma->getText("depositoCriptoLabel") ?></td>
                                                  <td class="text-center"><?php echo $idioma->getText("depositoCripto") ?></td>
                                                  <td class="text-center" id="">0.00000000</td>
                                              </tr>

                                              <tr>
                                                  <td><?php echo $idioma->getText("taxaDeposito") ?></td>
                                                  <td class="text-center"><?php echo $idioma->getText("depositoTaxa") ?></td>
                                                  <td class="text-center" id="taxaDeposito"></td>
                                              </tr>
                                              <tr>
                                                  <td><?php echo $idioma->getText("estornoDeposito") ?></td>
                                                  <td class="text-center"><?php echo $idioma->getText("depositoTaxa") ?></td>
                                                  <td class="text-center" id="estornoDeposito"></td>
                                              </tr>

                                              <tr>
                                                  <td><?php echo $idioma->getText("percentualDepositoZeroAteDoisMil") ?></td>
                                                  <td class="text-center"><?php echo $idioma->getText("depositoTaxa") ?></td>
                                                  <td class="text-center"
                                                      id="percentualDepositoZeroAteDoisMil"></td>
                                              </tr>
                                              <tr>
                                                  <td><?php echo $idioma->getText("percentualDepositoDoisAteCincoMil") ?></td>
                                                  <td class="text-center"><?php echo $idioma->getText("depositoTaxa") ?></td>
                                                  <td class="text-center"
                                                      id="percentualDepositoDoisAteCincoMil"></td>
                                              </tr>
                                              <tr>
                                                  <td><?php echo $idioma->getText("percentualDepositoCincoAteDezMil") ?></td>
                                                  <td class="text-center"><?php echo $idioma->getText("depositoTaxa") ?></td>
                                                  <td class="text-center"
                                                      id="percentualDepositoCincoAteDezMil"></td>
                                              </tr>
                                              <tr>
                                                  <td><?php echo $idioma->getText("percentualDepositoDezAteCinquentaMil") ?></td>
                                                  <td class="text-center"><?php echo $idioma->getText("depositoTaxa") ?></td>
                                                  <td class="text-center"
                                                      id="percentualDepositoDezAteCinquentaMil"></td>
                                              </tr>
                                              <tr>
                                                  <td><?php echo $idioma->getText("percentualDepositoAcimaCinquentaMil") ?></td>
                                                  <td class="text-center"><?php echo $idioma->getText("depositoTaxa") ?></td>
                                                  <td class="text-center"
                                                      id="percentualDepositoAcimaCinquentaMil"></td>
                                              </tr>


                                              <tr>
                                                  <td><?php echo $idioma->getText("percentualSaque") ?></td>
                                                  <td class="text-center"><?php echo $idioma->getText("saqueTaxa") ?></td>
                                                  <td class="text-center" id="percentualSaque"></td>
                                              </tr>
                                              <tr>
                                                  <td><?php echo $idioma->getText("tarifaTed") ?></td>
                                                  <td class="text-center"><?php echo $idioma->getText("saqueTaxa") ?></td>
                                                  <td class="text-center" id="tarifaTed"></td>
                                              </tr>
                                              <tr>
                                                  <td><?php echo $idioma->getText("valorMinimoSaque") ?></td>
                                                  <td class="text-center"><?php echo $idioma->getText("saqueTaxa") ?></td>
                                                  <td class="text-center" id="valorMinimoSaque"></td>
                                              </tr>


                                              <tr>
                                                  <td><?php echo $idioma->getText("percentualCompraAtiva") ?></td>
                                                  <td class="text-center"><?php echo $idioma->getText("compraVendaTaxa") ?></td>
                                                  <td class="text-center" id="percentualCompraAtiva"></td>
                                              </tr>
                                              <tr>
                                                  <td><?php echo $idioma->getText("percentualCompraPassiva") ?></td>
                                                  <td class="text-center"><?php echo $idioma->getText("compraVendaTaxa") ?></td>
                                                  <td class="text-center" id="percentualCompraPassiva"></td>
                                              </tr>
                                              <tr>
                                                  <td><?php echo $idioma->getText("percentualVendaAtiva") ?></td>
                                                  <td class="text-center"><?php echo $idioma->getText("compraVendaTaxa") ?></td>
                                                  <td class="text-center" id="percentualVendaAtiva"></td>
                                              </tr>
                                              <tr>
                                                  <td><?php echo $idioma->getText("percentualVendaPassiva") ?></td>
                                                  <td class="text-center"><?php echo $idioma->getText("compraVendaTaxa") ?></td>
                                                  <td class="text-center" id="percentualVendaPassiva"></td>
                                              </tr>


                                              <tr>
                                                  <td><?php echo $idioma->getText("comissaoTransferenciaInternaReais") ?></td>
                                                  <td class="text-center"><?php echo $idioma->getText("transTaxa") ?></td>
                                                  <td class="text-center"
                                                      id="comissaoTransferenciaInternaReais"></td>
                                              </tr>
                                              <tr>
                                                  <td><?php echo $idioma->getText("comissaoTransferenciaReaisMinima") ?></td>
                                                  <td class="text-center"><?php echo $idioma->getText("transTaxa") ?></td>
                                                  <td class="text-center"
                                                      id="comissaoTransferenciaReaisMinima"></td>
                                              </tr>

                                              </tbody>
                                              <tfoot>
                                              <tr>
                                                  <td colspan="6">
                                                      <ul class="pagination pull-right"></ul>
                                                  </td>
                                              </tr>
                                              </tfoot>
                                          </table>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                    </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <script src="assets/js/jquery-3.4.1.min.js"></script>
  <script src="assets/js/popper.min.js"></script>
  <script src="assets/js/bootstrap.min.js"></script>
  <script src="assets/js/amcharts-core.min.js"></script>
  <script src="assets/js/amcharts.min.js"></script>
  <script src="assets/js/custom.js"></script>
</body>

<!-- End Main content -->


<div class="clearfix"></div>

<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>
<script src="<?php echo TEMA; ?>js/plugins/datapicker/bootstrap-datepicker.js"></script>
<script src="<?php echo TEMA; ?>js/plugins/switchery/switchery.js"></script>
<script src="<?php echo TEMA; ?>js/plugins/iCheck/icheck.min.js"></script>

<script>
    var dataNota = "";
    var dataAfiliado = "todos";
    var inicial = 0;
    var pareamento = true;


    function getDocStats() {
        $.ajax({
            url: "<?php echo URLBASE_CLIENT . Utils\Rotas::R_KYC_DOCS_STATS ?>",
            method: "post",
            dataType: "json",
            data: {},
            success: function (json) {
                try {
                    if (json.status == 'success') {
                        $("#st-frente").html(json.data.Frente.message);
                        $("#st-verso").html(json.data.Verso.message);
                        $("#st-selfie").html(json.data.Selfie.message);
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
            }
        });
    }

    function getAuthSecret() {
        $.ajax({
            url: "<?php echo URLBASE_CLIENT . Utils\Rotas::R_MEUSDADOS_GOOGLEAUTH_GETSECRET ?>",
            method: "post",
            dataType: "json",
            data: {},
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#authSecretHidden").val(json.secret);
                        $("#authSecret").html(json.secret);
                        $("#authSecretQrCode").attr("src", json.qrCode);
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
            }
        });
    }

    $(document).ready(function () {
        getDocStats();

        $('.i-checks').iCheck({
            checkboxClass: 'icheckbox_square-green',
            radioClass: 'iradio_square-green'
        });
        $('#market_check').on('ifChanged', function(event){
            $.ajax({
                url: "<?php echo URLBASE_CLIENT . Utils\Rotas::R_MERKETUPDATE ?>",
                method: "post",
                dataType: "json",
                success: function (json) {
                    try {

                        if (json.sucesso) {
                            showNotyAlert(json.msg, "s");

                        } else {
                            showNotyAlert(json.msg, "e");
                        }
                    } catch (e) {
                        showNotyAlert( e.msg, 'e');
                    }
                }

            });
        });

        new Clipboard('#copyRef');

        $('#tblnavegadores').footable();
        $('#tblnotasfiscais').footable();
        $('#tblaparelhos').footable();
        $('#tblAfiliado').footable();
        $('#tblCriptomoedas').footable();
        $('#tblTaxasReais').footable();
        $('#tblContasBancarias').footable();

        $('#idPaisNaturalidade').select2();
        $('#cadastroContaIdBanco').select2();
        // $('#idPais').select2();
        // $('#estado').select2();
        // $('#cidade').select2();
        $('').select2();

        $("#estado").change(function () {
            //getCidades();
        });

        $("#filtroStatusNota").change(function () {
            listaNotaFiscal();
        });

        $("#filtroTipoNota").change(function () {
            listaNotaFiscal();
        });

        $("#radioDatasNota input").on('change', function () {
            dataNota = $('input[name="options"]:checked', '#radioDatasNota').val();
            listaNotaFiscal();
        });

        $("#radioDatasAfiliado input").on('change', function () {
            dataAfiliado = $('input[name="options"]:checked', '#radioDatasAfiliado').val();
            listaAfiliado();
        });


        $("#idPaisNaturalidade").change(function () {
            if ($("#idPaisNaturalidade").val() === "<?php echo Utils\Criptografia::encriptyPostId(Utils\Constantes::BRASIL)?>") {
                $("#documentoTipo").val(<?php echo Utils\Constantes::DOCUMENTO_CPF ?>);

                <?php if($cliente->documentoVerificado == 0){ ?>
                $("#cpf").prop("disabled", false);
                <?php } ?>
                //$("#documentoTipo").prop("disabled", true);
                $("#containerCheckboxMovimentacaoBrl").hide();
            } else {
                //$("#documentoTipo").prop("disabled", false);
                $("#containerCheckboxMovimentacaoBrl").show();
                $("#utilizaSaqueDepositoBrl").trigger("change");
            }
        });

        $("#idPais").change(function () {
            getEstados();
        });

        $("#authCodigo2faAtivar").numeric();
        $("#authSecret").html("");
        $("input:radio[name='tipoAutenticacao']").click(function () {
            if ($(this).val() === "<?php echo \Utils\Constantes::TIPO_AUTH_GOOGLE?>") {
                $("#google-auth-container").show();
                getAuthSecret();
                $("#reenviarToken").show();
                $("#msgToken").html('<?php echo $idioma->getText("insiraEmailEnviado") ?>');
                $("#tokenChange").show();
                modalConfirmarAlteracao();
            } else {
                $("#google-auth-container").hide();
                $("#reenviarToken").hide();
                $("#msgToken").html('<?php echo $idioma->getText("insiraGoogleAuth") ?>');
                $("#tokenChange").show();
            }
        });

        $("#tokenChange").hide();

        $("[data-toggle='tab']").click(function () {
            if (isMobile()) {
                $(this).ScrollTo({
                    duration: 500,
                    easing: 'swing'
                });
            }
        });

        $("#pin").numeric();
        $("#confirmarPin").numeric();


        <?php if (!empty($tab)) { ?>

        $("a[href='#<?php echo $tab ?>']").trigger("click");

        <?php } ?>

        $("#pin").numeric();
        $("#confirmarPin").numeric();
        $("#pinAlterarSenha").numeric();

        $("#cpf").numeric();


        $("#idPais").trigger('change');

        //$('#estado').select2({readonly: true});
        $("#dataNascimento").datepicker({format: "dd/mm/yyyy"}).mask("99/99/9999");

        $("#senha").keyup(function () {
            forcaSenha();
            verificarSenhas();
        });

        $("#confirmacao").keyup(function () {
            verificarSenhas();
        });

        $("input:radio[name='tipoPerfil']").change(function () {
            showDescricaoPerfil();
        }).trigger("change");

        $("#form-perfil").ajaxForm({
            dataType: "json",
            beforeSubmit: function () {
                $("#btn-salvar").prop("disabled", true);
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        showNotyAlert(json.mensagem, "s");
                        location = "<?php echo URLBASE_CLIENT . Utils\Rotas::R_MEUSDADOS ?>";
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#btn-salvar").prop("disabled", false);
            }
        });

        $("#form-documentos").ajaxForm({ 
            dataType: "json",
            beforeSubmit: function () {
                $("btn-salvar-docs").prop("disabled", true);
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        showNotyAlert(json.mensagem, "s");
                        location = "<?php echo URLBASE_CLIENT . Utils\Rotas::R_MEUSDADOS ?>";
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("btn-salvar-docs").prop("disabled", false);
            }
        });

        $("#form-seguranca").ajaxForm({
            dataType: "json",
            beforeSubmit: function () {
                $("#btn-salvar-seguranca").prop("disabled", true);

                $("#modalConfirmarAlteracaoConfirmar, #modalConfirmarAlteracaoCancelar, #modalConfirmarAlteracaoReenviar").prop("disabled", true);
            },
            success: function (json) {
                $("#tipoAutenticacaoToken").val("");
                try {
                    if (json.sucesso) {
                        location = "<?php echo URLBASE_CLIENT . Utils\Rotas::R_LOGOUT ?>";
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#btn-salvar-seguranca").prop("disabled", false);
                $("#modalConfirmarAlteracaoConfirmar, #modalConfirmarAlteracaoCancelar, #modalConfirmarAlteracaoReenviar").prop("disabled", false);
            }
        });


        $("#form-documentos-pf").ajaxForm({
            dataType: "json",
            beforeSubmit: function () {
                $("#btn-salvar-doc-pf").prop("disabled", true);
            },
            uploadProgress: function (event, position, total, percentComplete) {
                $("#progressDocumentsContainer").show();
                var percentVal = percentComplete + '%';
                $("#progressDocuments").width(percentVal);
                $("#progressDocumentsLegend").html("Carregando: " + percentVal + "%");
            },
            success: function (json) {
                try {
                    if (json.sucesso) {


                        location = "<?php echo URLBASE_CLIENT . Utils\Rotas::R_MEUSDADOS ?>/tab-7";

                    } else {

                        if (typeof json.camposDocumento !== 'undefined' && json.camposDocumento.length > 0) {
                            $("#camposInvalidosDocumento").html(<?php echo $idioma->getText("necessarioPreencherCampos")?> +json.camposDocumento + ".");
                        }

                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#btn-salvar-doc-pf").prop("disabled", false);
                $("#progressDocumentsContainer").hide();
                $("#progressDocuments").width("0%");
                $("#progressDocumentsLegend").html("");
            }
        });


        $("#form-alterar-senha").ajaxForm({
            dataType: "json",
            beforeSubmit: function () {
                $("#btnAlterarSenha").prop("disabled", true);
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        location = "<?php echo URLBASE_CLIENT . Utils\Rotas::R_LOGOUT ?>";
                        showNotyAlert(json.mensagem, "s");
                    } else {
                        limparCamposSenha();
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(json.mensagem, "e");
                }
                $("#btnAlterarSenha").prop("disabled", false);
            }
        });


        $(".btnOpenMudarFoto").click(function () {
            abrirMudarFotoPerfil();
        });

        //getCidades();

        $(".tab-etapas-perfil").click(function () {
            activeTab = $(this).attr("href");
        });


        $("#idPaisNaturalidade").trigger("change");

    });

    var $input = $("#pin");
    $input.keyup(function (e) {
        var max = 4;
        if ($input.val().length > max) {
            $input.val($input.val().substr(0, max));

        }
    });

    var $input2 = $("#confirmarPin");
    $input2.keyup(function (e) {
        var max = 4;
        if ($input2.val().length > max) {
            $input2.val($input2.val().substr(0, max));

        }
    });

    let activeTab = null;

    function refresh() {
        if (activeTab !== null && activeTab.length > 0) {

        } else {

        }
    }

    function isMobile() {
        try {
            document.createEvent("TouchEvent");
            return true;
        } catch (e) {
            return false;
        }
    }

    function toogleAlterarSenha() {
        $("#row-form-alteracao-senha").toggle();
    }

    function getEstados() {
        $("#loadingEstados").show();
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_MEUSDADOS_STATES_LIST ?>',
            method: 'post',
            dataType: 'json',
            data: {
                pais: $("#idPais").val(),
                estado: '<?php echo \Utils\Criptografia::encriptyPostId($estado->id) ?>'
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#estado").html(json.html);
                        $("#estado").trigger('change');
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }

                $("#loadingEstados").hide();
            }
        });
    }

    function listaNavegadores() {
        $("#listaNavegadores").html("<tr><td colspan='6' class='text-center'><img src='<?php echo IMAGES ?>loading.gif' /></td></tr>");
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_MEUSDADOS_NAVEGADOR_LIST ?>',
            method: 'post',
            dataType: 'json',
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#listaNavegadores").html(json.html);
                        $('#tblnavegadores').trigger('footable_initialize');
                    } else {
                        $("#listaNavegadores").html("<tr><td colspan='6'>" + json.mensagem + "</td></tr>");
                    }
                } catch (e) {
                    $("#listaNavegadores").html("<tr><td colspan='6'></td></tr>");
                }
            }
        });
    }

    function getCidades() {
        $("#loadingCidades").show();
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_POSTGETCIDADESPERFIL ?>',
            method: 'post',
            dataType: 'json',
            data: {
                estado: $("#estado").val(),
                cidade: '<?php echo $cidade ?>'
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#cidade").html(json.html);
                        $("#cidade").trigger('change');
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }

                $("#loadingCidades").hide();
            }
        });
    }

    function forcaSenha() {

        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_MEUSDADOS_SENHA_FORCA ?>',
            method: 'POST',
            dataType: 'json',
            data: {
                senha: $("#senha").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#barraForcaSenha").css("width", (json.percentual * 10) + "%");
                        $("#barraForcaSenha").removeClass("progress-bar-warning").removeClass("progress-bar-danger");

                        if (json.forca < 4) {
                            $("#barraForcaSenha").addClass("progress-bar-danger");
                        } else if (json.forca < 6) {
                            $("#barraForcaSenha").addClass("progress-bar-warning");
                        }

                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
            }

        });

    }

    function verificarSenhas() {
        $("#btn-pwd-matches").removeClass("btn-primary").removeClass("btn-danger");
        if ($("#senha").val() === $("#confirmacao").val()) {
            $("#btn-pwd-matches").addClass("btn-primary");
            $("#btnAlterarSenha").prop("disabled", false);
        } else {
            $("#btn-pwd-matches").addClass("btn-danger");
            $("#btnAlterarSenha").prop("disabled", true);
        }
    }

    function getTokenApiKey() {
        $("#btnGetTokenApi").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_MEUSDADOS_CHAVES_PREPARAR ?>',
            method: 'post',
            dataType: 'json',
            success: function (json) {
                try {
                    if (json.sucesso) {

                        $("#solicitarApi").hide();
                        $("#tokenApi").val("");
                        $("#solicitarApiToken").show();

                        showNotyAlert(json.mensagem, "s");
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#btnGetTokenApi").prop("disabled", false);
            }
        });
    }

    function gerarApiKey() {

        $("#btnGerarTokenApi").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_MEUSDADOS_CHAVES_GERAR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                token: $("#tokenApi").val(),
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        showNotyAlert(json.mensagem, "s");

                        $("#solicitarApi").show();
                        $("#solicitarApiToken").hide();

                    } else {
                        showNotyAlert(json.mensagem, "e");

                        $("#solicitarApi").show();
                        $("#solicitarApiToken").hide();
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#btnGerarTokenApi").prop("disabled", false);
            }
        });
    }

    function modalConfirmarAlteracao() {
        $("#tokenConfirm").val("");

        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_MEUSDADOS_AUTORIZACAO_TOKEN ?>',
            method: 'post',
            dataType: 'json',
            data: {
                tipo: $("input:radio[name='tipoAutenticacao']:checked").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {

                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
            }
        });
    }

    function confirmarAlteracao() {
        $("#tipoAutenticacaoToken").val($("#tokenConfirm").val());
        $("#form-seguranca").submit();
    }

    function limparCamposSenha() {
        $("#senha, #senhaAtual, #confirmacao, #pinAlterarSenha").val("");
    }

    function listarDispositivosMobile() {
        $("#lista-dispositivos-mobile").html("<tr><td colspan='6' class='text-center'><img src='<?php echo IMAGES ?>loading.gif' /></td></tr>");
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_DISPOSITIVOS_LISTAR ?>',
            method: 'post',
            dataType: 'json',
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#lista-dispositivos-mobile").html(json.html);
                        $('#tblaparelhos').trigger('footable_initialize');
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
            }
        });
    }

    function parear() {
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_DISPOSITIVOS_PAREAR ?>',
            method: 'post',
            dataType: 'json',
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#qrcodeDispositivo").attr("src", "qrcodes/" + json.qrcode + ".png");
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
            }
        });
    }

    function ativarPareamento() {
        if (pareamento) {
            $.ajax({
                url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_DISPOSITIVOS_PAREAMENTO ?>',
                method: 'post',
                dataType: 'json',
                success: function (json) {
                    try {
                        if (json.sucesso) {
                            if (json.ativado) {
                                pareamento = false;
                                listarDispositivosMobile();
                            }
                        } else {
                            showNotyAlert(json.mensagem, "e");
                        }
                    } catch (e) {
                        showNotyAlert(e, "e");
                    }
                }
            });
        }
    }


    function alterarStatusAtivoDispositivoMobile(codigo) {
        $("#lista-dispositivos-mobile").html("<tr><td colspan='6' class='text-center'><img src='<?php echo IMAGES ?>loading.gif' /></td></tr>");
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_DISPOSITIVOS_ALTERARSTATUS ?>',
            method: 'post',
            dataType: 'json',
            data: {codigo: codigo},
            success: function (json) {
                try {
                    if (json.sucesso) {
                        showNotyAlert(json.mensagem, "s");
                        listarDispositivosMobile();
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
            }
        });
    }

    function salvarNotificacao(codigo) {
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_MEUSDADOS_NOTIFICACAO_SALVAR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                id: codigo,
                status: $("#" + codigo).is(":checked")
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        showNotyAlert(json.mensagem, "s");
                        getNotificacao();
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
            }
        });
    }

    function getTaxas() {
        //$("#tblTaxa").html("<tr><td colspan='5' class='text-center'><img src='<?php echo IMAGES ?>loading.gif' /></td></tr>");
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_MEUSDADOS_TAXAS ?>',
            method: 'post',
            dataType: 'json',
            success: function (json) {
                try {
                    if (json.sucesso) {
                        //Depósito
                        $("#taxaDeposito").html(json.deposito.taxaDeposito + "%");
                        $("#estornoDeposito").html(json.deposito.estornoDeposito + "%");

                        //Depósito especie
                        $("#percentualDepositoZeroAteDoisMil").html(json.dinheiro.percentualDepositoZeroAteDoisMil + "%");
                        $("#percentualDepositoDoisAteCincoMil").html(json.dinheiro.percentualDepositoDoisAteCincoMil + "%");
                        $("#percentualDepositoCincoAteDezMil").html(json.dinheiro.percentualDepositoCincoAteDezMil + "%");
                        $("#percentualDepositoDezAteCinquentaMil").html(json.dinheiro.percentualDepositoDezAteCinquentaMil + "%");
                        $("#percentualDepositoAcimaCinquentaMil").html(json.dinheiro.percentualDepositoAcimaCinquentaMil + "%");

                        //Saque
                        $("#percentualSaque").html(json.saque.percentualSaque + "%");
                        $("#tarifaTed").html("R$ " + json.saque.tarifaTed);
                        $("#valorMinimoSaque").html("R$ " + json.saque.valorMinimoSaque);

                        //Venda/Compra Ativa/Passiva
                        $("#percentualCompraAtiva").html(json.negociacoes.percentualCompraAtiva + "%");
                        $("#percentualCompraPassiva").html(json.negociacoes.percentualCompraPassiva + "%");
                        $("#percentualVendaAtiva").html(json.negociacoes.percentualVendaAtiva + "%");
                        $("#percentualVendaPassiva").html(json.negociacoes.percentualVendaPassiva + "%");

                        //Transferencia internet
                        $("#comissaoTransferenciaInternaReais").html("R$ " + json.transferencia.comissaoTransferenciaInternaReais);
                        $("#comissaoTransferenciaReaisMinima").html("R$ " + json.transferencia.comissaoTransferenciaReaisMinima);

                    } else {
                    }
                } catch (e) {

                }
            }
        });
    }

    function meusLimites() {
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_MEUSDADOS_LIMITES ?>',
            method: 'post',
            dataType: 'json',
            success: function (json) {
                try {
                    if (json.sucesso) {
                        if (json.verificado) {
                            $("#panelBasica").removeClass("panel-primary");
                            $("#footerBasica").removeClass("panel-primary");
                            $("#footerBasica").attr("hidden", true);
                            $("#panelVerificada").addClass("panel-primary");
                            $("#footerVerificada").addClass("panel-primary");
                            $("#footerVerificada").attr("hidden", false);
                        } else {
                            $("#panelBasica").addClass("panel-primary");
                            $("#footerBasica").addClass("panel-primary");
                            $("#footerBasica").attr("hidden", false);
                            $("#panelVerificada").removeClass("panel-primary");
                            $("#footerVerificada").removeClass("panel-primary");
                            $("#panelVerificada").addClass("panel-default");
                            $("#footerVerificada").attr("hidden", true);
                        }
                        $("#panelVerificada").attr("hidden", false);
                        $("#panelBasica").attr("hidden", false);
                    }
                } catch (e) {

                }
            }
        });
    }

    function loadCheckBox() {
        var swObjs = Array.prototype.slice.call(document.querySelectorAll('.js-switch'));
        $("input[type=checkbox]").each(function (index, element) {
            if (!element.getAttribute('data-switchery')) {
                var init = new Switchery(element, {
                    color: '#1ab394', size: 'small', disabledOpacity: 0.3
                });

                swObjs[element.id] = init;
            }
        });
    }

    function salvarConta() {
        $("#cadastroContaFechar, #cadastroContaSalvar").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_CADASTROSALVARCONTABANCARIA ?>',
            method: 'post',
            dataType: 'json',
            data: {
                agencia: $("#cadastroContaAgencia").val(),
                conta: $("#cadastroContaConta").val(),
                agenciaDigito: $("#cadastroContaAgenciaDigito").val(),
                contaDigito: $("#cadastroContaContaDigito").val(),
                idBanco: $("#cadastroContaIdBanco").val(),
                tipoConta: $("#cadastroContaTipoConta").val(),
                documento: $("#documentoConta").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        listarContasBancarias();
                        limparConta();
                        showNotyAlert(json.mensagem, "s");
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }

                $("#cadastroContaFechar, #cadastroContaSalvar").prop("disabled", false);
            }
        });
    }

    function limparConta() {
        $("#cadastroContaAgencia").val("");
        $("#cadastroContaConta").val("");
        $("#cadastroContaAgenciaDigito").val("");
        $("#cadastroContaContaDigito").val("");
        $("#cadastroContaIdBanco").val(0).select2();
        $("#cadastroContaTipoConta").prop('selectedIndex', 0);
    }

    function listarContasBancarias() {
        $("#listaContasBancarias").html("<tr><td colspan='9' class='text-center' ><img src='<?php echo IMAGES ?>loading.gif' /></td></tr>");
        $.ajax({
            url: "<?php echo URLBASE_CLIENT . Utils\Rotas::R_CONTASBANCARIAS_LISTAR ?>",
            method: "post",
            dataType: "json",
            data: {},
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#listaContasBancarias").html(json.html);
                        loadCheckBox();
                        $('#tblContasBancarias').trigger('footable_initialize');
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
            }
        });
    }

    function alterarStatusContaBancaria(codigo) {
        $.ajax({
            url: "<?php echo URLBASE_CLIENT . Utils\Rotas::R_CONTASBANCARIAS_STATUS_ALTERAR ?>",
            method: "post",
            dataType: "json",
            data: {
                codigo: codigo
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        listarContasBancarias();
                        showNotyAlert(json.mensagem, "s");
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
            }
        });
    }

    function salvarCnpj() {

        $("#btn-salvar-cnpj").prop("disabled", true);
        $.ajax({
            url: "<?php echo URLBASE_CLIENT . Utils\Rotas::R_CNPJ_SALVAR ?>",
            method: "post",
            dataType: "json",
            data: {
                cnpj: $("#cnpj").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        showNotyAlert(json.mensagem, "s");
                        $("#cnpj").prop("disabled", true);

                        $("#cnpj").val(json.cnpj);
                        $("#razaoSocial").val(json.razaoSocial);
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#btn-salvar-cnpj").prop("disabled", false);
            }
        });
    }

    function listaEmpresa() {
        $.ajax({
            url: "<?php echo URLBASE_CLIENT . Utils\Rotas::R_CNPJ_MOSTRAR ?>",
            method: "post",
            dataType: "json",
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#cnpj").val(json.cnpj);
                        $("#razaoSocial").val(json.razaoSocial);
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#btn-salvar-cnpj").prop("disabled", false);
            }
        });
    }

    function kycSmsResend() {
        // btn_smsresend
        $('#btn_smsresend').attr("disabled", true);
        $("#btn_smsresend").html('<small>Processando ...</small>');
        $.ajax({
            url: "<?php echo URLBASE_CLIENT . Utils\Rotas::R_KYC_SMS_RESEND ?>",
            method: "post",
            dataType: "json",
            success: function (json) {
                if (json.sucesso) {
                    $("#btn_smsresend").html('<small>Enviando ...</small> ');
                    $('#btn_smsresend').addClass(json.queueReturnUid);
                }
                else
                {
                    $('#btn_smsresend').attr("disabled", false);
                    $("#btn_smsresend").html('<small>Reenviar E-mail</small> ');
                    showNotyAlert(json.msg, json.msgType);
                }

            }
        })


    }

    function kycStart() {
        $('#btn_kycStartBtn').attr("disabled", true);
        $("#btn_kycStartBtn").html('Enviando ...');

        $.ajax({
            url: "<?php echo URLBASE_CLIENT . Utils\Rotas::R_KYC_START ?>",
            method: "post",
            dataType: "json",
            success: function (json) {
                try {

                    if (json.sucesso) {
                        $('#btn_kycStartBtn').attr("disabled", true);
                        $("#btn_kycStartBtn").html('Aguardando envio do E-mail');
                        $('#btn_kycStartBtn').addClass(json.queueReturnUid);
                        $('#btn_kycStart').attr("disabled", false);
                    } else {
                        showNotyAlert(json.msg, json.msgType);
                        $("#btn_kycStartBtn").html('Verificar minha conta');
                    }
                } catch (e) {
                    $('#btn_kycStart').attr("disabled", false);
                    showNotyAlert(e.msg, e.msgType);
                }
            },
            error: function () {
                $('#btn_kycStart').html(btnTitulo);
                $('#btn_kycStart').attr("disabled", false);
                showNotyAlert('Falha ao processar requisição', 'e');
            }
        });
    }

</script>
<?php Utils\Layout::append("mensage_text", $_data) ?>
