<?php
$cliente = isset($_data["cliente"]) ? $_data["cliente"] : new Models\Modules\Cadastro\Cliente();
$order = isset($_data["order"]) ? $_data["order"] : null;
$numeroPedido = isset($_data["numeroPedido"]) ? $_data["numeroPedido"] : null;
$dataPedido = isset($_data["dataPedido"]) ? $_data["dataPedido"] : null;

$dataExpiracao = new \Utils\Data(str_replace("T", " ", $order->ExpirationDate));

?>
<html>







    
    <head>
        <title>Comprovante Invoice</title>
    </head>







    
    <body>




    <div class="range range-xs-center ">
        <div class="cell-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="range range-sm">
                      <div class="cell-md-6">
                          <center><img width='300' height='70' src='<?php echo NC ?>images/intense/logo-dark.png' alt=''/></center>
                      </div>
                    </div>
                </div>
            </div>
        </div>
</div>



        
        <table style="width: 100%;">
            
            <tr>
                <td style="text-align: center; padding: 10px;">
                    <h1>Comprovante</h1>
                </td>
                
            </tr>
            
            <tr>
                <td style=" padding: 10px;"><strong>Cliente: </strong><?php echo $cliente->nome ?></td>
            </tr>
            
            <tr>
                <td style="padding: 10px;"><strong>Email: </strong><?php echo $cliente->email ?></td>
            </tr>
            <tr>
                <td style="padding: 10px;"><strong>Celular: </strong><?php echo $cliente->celular ?></td>
            </tr>
            <tr>
                <td style="padding: 10px;"><strong>Número do Pedido: </strong><?php echo $numeroPedido ?></td>
            </tr>
            <tr>
                <td style="padding: 10px;"><strong>Número da Invoice: </strong><?php echo $order->InvoiceId ?></td>
            </tr>
            <tr>
                <td style="padding: 10px;">
                    <strong>Status: </strong>
                    <?php
                        if (in_array($order->Status, Array("NEW", "UNDERPAID", "RECEIVED","OVERPAID))) {
                            echo "Aguardando Pagamento";
                        } else if (in_array($order->Status, Array("PAID"))) {
                            echo "Pago";
                        } else if (in_array($order->Status, Array("CANCELED", "EXPIRED"))) {
                            echo "Cancelado";
                        }
                    ?>
                </td>
            </tr>
            <tr>
                <td style="padding: 10px;"><strong>Endereço de Pagamento: </strong><?php echo $order->DigitalCurrencyAddress ?></td>
            </tr>
            <tr>
                <td style="padding: 10px;"><strong>Valor total: </strong><?php echo number_format($order->CurrencyTotal, 2, ",", ".") ?></td>
            </tr>
            <tr>
                <td style="padding: 10px;"><strong>Data do Pedido: </strong><?php echo $dataPedido->formatar(\Utils\Data::FORMATO_PT_BR_TIMESTAMP_LONGO) ?></td>
            </tr>
            <tr>
                <td style=" padding: 10px;"><strong>Data de Expiração: </strong><?php echo $dataExpiracao->formatar(\Utils\Data::FORMATO_PT_BR_TIMESTAMP_LONGO) ?></td>
            </tr>
            <tr>
                <td style=" padding: 10px;"><strong>Moeda Digital: </strong><?php echo $order->DigitalCurrency ?></td>
            </tr>
            <tr>
                <td style="padding: 10px;"><strong>Cotação da moeda digital: </strong><?php echo number_format($order->DigitalCurrencyQuotation, 2, ",", ".") ?></td>
            </tr>
        </table>
        
    </body>
    
</html>