<div class="container">
            <div class="footer">
                <div class="row">
                    <div class="col-md-6 col-xs-12 links">
                        <ul>
                            <li><a href="https://cointradecx.com" target="_site">Institucional</a></li>
                            <li><a href="https://cointradecx.blog" target="_blog">Blog</a></li>
                            <li><a href="https://cointradecx.com/" target="_about">About</a></li>
                            <li><a href="https://cointradecx.com/termos-legais" target="_terms">Terms</a></li>
                            <li><a href="/fees">Fees</a></li>
                            <li><a href="/contact">Contact</a></li>
                        </ul>
                    </div>
                    <div class="col-md-6 col-xs-12 social">
                        <ul>
                            <li><a href=""><i class="socialFooter fab fa-facebook-f"></i></a></li>
                            <li><a href=""><i class="socialFooter fab fa-instagram"></i></a></li>
                            <li><a href=""><i class="socialFooter fab fa-twitter"></i></a></li>
                            <li><a href=""><i class="socialFooter fab fa-linkedin"></i></li>
                            <li><a href=""><i class="socialFooter fab fa-youtube"></i></a></li>
                            <li><a href=""><i class="socialFooter fab fa-telegram"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="row copy-bar">
                <div class="col-md-8 col-xs-12 copy">
                    <p>COINTRADE BLOCKCHAIN TECHNOLOGY S/A 2017 - 2019</p>
                </div>
                <div class="col-md-4 col-xs-12 statistics">
                    <p><span id="btcNotation" class="">BTC 24h Volume: <span> {{btcprice}}</span></p>
                </div>
            </div>
        </div>