<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0">
<title><?php echo TITULO ?></title>
<meta name="author" content="">
<meta name="description" content="">
<meta name="keywords" content="">
<link rel="canonical" href="">
<meta name="theme-color" content="#310f72">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Favicon 
    <link rel="apple-touch-icon" sizes="57x57" href="img/favicon/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="img/favicon/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="img/favicon/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="img/favicon/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="img/favicon/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="img/favicon/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="img/favicon/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="img/favicon/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="img/favicon/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="img/favicon/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="img/favicon/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/favicon/favicon-16x16.png">
    <link rel="manifest" href="img/favicon/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="img/favicon/ms-icon-144x144.png">
-->
    <!-- Bootstrap CSS -->
<link rel="stylesheet" href="<?php echo TEMACSS; ?>bootstrap.min.css">
<link rel="stylesheet" href="<?php echo TEMACSS; ?>dataTables.bootstrap4.min.css">
<!-- Color Switch -->
<link rel="stylesheet" href="<?php echo TEMACSS; ?>jquery.colorpanel.css">
<!-- Default Style CSS -->
<link rel="stylesheet" href="<?php echo TEMACSS; ?>default.css">
<link rel="stylesheet" href="<?php echo TEMACSS; ?>responsive.css">
<!-- Color Skin -->
<link rel="stylesheet" id="cpswitch" href="">
<script src="<?php echo TEMAJS; ?>angularjs/angular.min.js"></script>
<script type="text/javascript">
    var AMBIENTE = '<?php echo AMBIENTE ?>';
</script>