<nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="index.html"><img class="logo" src="<?php echo TEMAIMG; ?>logo-cointrade.png" alt=""></a>
            <?php Utils\Layout::append("cointrade/nav_menu", $_data) ?>
        </div>
    </nav>