<div class="collapse navbar-collapse justify-content-md-center" id="navbarToggler">
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><img src="<?php echo TEMAIMG; ?>icons/exchange-icon.png"><span class="name">Exchange</span></a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="trade.html">
                                Basic
                            </a>
                            <a class="dropdown-item" href="advanced.html">
                                Advanced
                            </a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href=""><img src="<?php echo TEMAIMG; ?>icons/lab-icon.png"><span class="name">Labs</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href=""><img src="<?php echo TEMAIMG; ?>icons/rocket-icon.png"><span class="name">LaunchPad</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link last" href="info.html"><img src="<?php echo TEMAIMG; ?>icons/info-icon.png"><span class="name">Info</span></a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="">Join Us</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="">Support</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="">News</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="login.html">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="register.html">Register</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">English</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="">
                                Portugues
                            </a>
                            <a class="dropdown-item" href="">
                                Ingles
                            </a>
                            <a class="dropdown-item" href="">
                                Espanhol
                            </a>
                        </div>
                    </li>
                    
                </ul>
                <div id="colorPanel" class="colorPanel ml-auto">
                    <ul style="display: block;">
                        <li id="ColorSelect" ><a href="#" id="hrefColor" class="linka align-middle"></a></li>
                    </ul> 
                </div>
            </div>