<script src="<?php echo TEMAJS; ?>jquery.min.js"></script>
<script src="<?php echo TEMAJS; ?>popper.min.js"></script>
<script src="<?php echo TEMAJS; ?>bootstrap/4.0.0/bootstrap.min.js"></script>
<script defer src="<?php echo TEMAJS; ?>releases/v5.0.6/all.js"></script>
<!-- Color Switcher -->
<script src="<?php echo TEMAJS; ?>jquery.colorpanel.js"></script>
<script src="<?php echo TEMAJS; ?>script.js"></script>