<?php Utils\Layout::append("inspina/metas", $_data) ?>

<?php Utils\Layout::append("inspina/scripts", $_data) ?>


<?php Utils\Layout::append("inspina/menu", $_data) ?>


<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
            <div class="row wrapper border-bottom white-bg page-heading">
                <div class="col-lg-10">
                    <h2>Historico</h2>
                    <ol class="breadcrumb">
                        <li>
                            Transações
                        </li>
                        <li class="active">
                            <strong>Historico</strong>
                        </li>
                    </ol>
                </div>
            </div>
</div>

<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>


