<?php

$brand = Models\Modules\Cadastro\BrandRn::getBrand();

$idioma = new \Utils\PropertiesUtils("index_wellcome", IDIOMA);
$_data["idiomaMenu"] = $idioma;
use Utils\Rotas;
$usuario = Utils\Geral::getLogado();
$cliente = Utils\Geral::getCliente();
$sexo = (\Utils\Geral::isCliente() ? $cliente->sexo : "M");
if (strtolower($sexo) == "m") {
    $foto = TEMA . "dist/img/avatar5.png";
} else {
    $foto = TEMA . "dist/img/avatar2.png";
}
if (\Utils\Geral::isCliente() && !empty($cliente->foto)) {
    $foto = URLBASE_CLIENT . UPLOADS . $cliente->foto;
} else if (!empty ($usuario->foto)){
    $foto = URLBASE_CLIENT . UPLOADS . $usuario->foto;
}

$clienteVerificado = isset($_data["clienteVerificado"]) ? $_data["clienteVerificado"] : false;

$fraseSeguranca = (\Utils\Geral::isCliente() ? $cliente->fraseSeguranca : "");
$carteiraPrincipal = isset($_data["carteiraPrincipal"]) ? $_data["carteiraPrincipal"] : null;
$moedaFavorita = isset($_data["moedaFavorita"]) ? $_data["moedaFavorita"] : null;
$configuracao = isset($_data["configuracao"]) ? $_data["configuracao"] : null;
$moeda1 = isset($_data["moeda1"]) ? $_data["moeda1"] : null;
$moeda2 = isset($_data["moeda2"]) ? $_data["moeda2"] : null;
//$listaSaquesDepositos = isset($_data["saquesDepositos"]) ? $_data["saquesDepositos"] : null;

$moedaCripto = Utils\Criptografia::encriptyPostId($moedaFavorita->id);

?>
    
<?php Utils\Layout::append("inspina/metas", $_data) ?>
<style>
    .move{
        cursor: move !important;
    }
</style>
<?php Utils\Layout::append("inspina/scripts", $_data);  ?>
<?php Utils\Layout::append("inspina/menu", $_data);  ?>
<div class="m-t-md">
    <div>
        <div class="row list-items sortable-view" id="minhas-moedas">

        </div>  
    </div>
</div>
<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>
<?php Utils\Layout::append("mensage_text", $_data) ?>
<script src="<?php echo TEMA; ?>js/jquery-ui.min.js"></script>
<script src="<?php echo TEMA; ?>js/jquery.ui.touch-punch.min.js"></script>

<script type="text/template" data-template="listitem">
    <div class="col-sm-6 col-md-4 move">
    <div class="social-feed-box b-r-md" style="background-color: ${color} !important; border-color: ${color} !important ">
        <div class="pull-right social-action dropdown">
            <button data-toggle="dropdown" class="dropdown-toggle btn-white" aria-expanded="false" style="background-color: ${color} !important; border: 1px solid ${color}">
                <i class="fa fa-angle-down" style="color:${fonte}"></i>
            </button>
            <ul class="dropdown-menu m-t-xs">
                <li><a href="javascript:selectAction('${id}', 'c', 'R_SAQUES');">Saque</a></li>
                <li><a href="javascript:selectAction('${id}', 'c', 'R_DEPOSITOS');">Depósito</a></li>
                <li><a href="javascript:setMoedaFavorita('${id}')">Definir Favorita</a></li>
            </ul>
        </div>
        <div class="social-avatar">
            <div class="pull-left"><img alt="${nome}" src="${img}">
            <span style="color: ${fonte};word-wrap: break-word;">${nome}</span>
            </div>
            <div class="media-body">
                <div class="row">                    
                    <div class="col-lg-12 text-right">
                        <h2 class="font-bold" style="margin-top: -3px !important; color: ${fonte}">${total}</h2>
                        <h5 class="text-muted text-right" style="margin-top: 5px !important; color: ${fonte}">Em ordem: ${emOrdem}</h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</script>

    
<script>
    $(document).ready(function () {
        setInterval(listarMinhasMoedas(),60000);
        
    });
    
    function render(props) {
        return function(tok, i) {
          return (i % 2) ? props[tok] : tok;
        };
      }

    function listarMinhasMoedas() {
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . \Utils\Rotas::R_DASHBOARD_MINHASMOEDAS_NOVO ?>',
            method: 'post',
            dataType:'json',
            success: function (json) {
                try {
                    if (json.sucesso) {
                        var show = "";
                         
                        for (var i = 0; i < json.dados.length; i++) {
                           var items = [{
                                  color: json.dados[i].cor,
                                  fonte: json.dados[i].fonte,
                                  img:  json.dados[i].imagem,
                                  nome: json.dados[i].nome,
                                  simbolo: json.dados[i].simbolo,
                                  total: json.dados[i].saldoTotal,
                                  emOrdem: json.dados[i].saldoBloqueado,
                                  id: json.dados[i].id
                                }];
                           
                           var itemTpl = $('script[data-template="listitem"]').text().split(/\$\{(.+?)\}/g);
                           
                           $('.list-items').append(items.map(function(item) {
                                return itemTpl.map(render(item    )).join('');
                              }));
                           
                        }
                    } else {
                        $("#minhas-moedas").html("");
                    }
                } catch (e) {
                    $("#minhas-moedas").html("");
                }
            }
        });
    }
  

    function contador(par1, par2, par3) {
   
        Number.prototype.numberFormat = function(decimals, dec_point, thousands_sep) {
            dec_point = typeof dec_point !== 'undefined' ? dec_point : ',';
            thousands_sep = typeof thousands_sep !== 'undefined' ? thousands_sep : '.';

            var parts = this.toFixed(decimals).split('.');
            parts[0] = parts[0].replace(/\B(?=(\d{3})+(?!\d))/g, thousands_sep);

            return parts.join(dec_point);
            }
            Number.prototype.numberFormat1 = function(decimals, dec_point, thousands_sep) {
            dec_point = typeof dec_point !== 'undefined' ? dec_point : '.';
            thousands_sep = typeof thousands_sep !== 'undefined' ? thousands_sep : '';

            var parts = this.toFixed(decimals).split('.');
            parts[0] = parts[0].replace(/\B(?=(\d{3})+(?!\d))/g, thousands_sep);

            return parts.join(dec_point);
            }
            
            var counter = { var1: 0, 
                            var2: 0,
                            var3: 0};

             TweenMax.to(counter, 1, {
                  var1: par1,
                  var2: par2,
                  var3: par3,
                  onUpdate: function () {
                      var nwc1 = counter.var1.<?php echo $moeda1->casasDecimais == 8 ? "numberFormat1(8)" : "numberFormat(2)" ?>;
                      var nwc2 = counter.var2.<?php echo $moeda2->casasDecimais == 8 ? "numberFormat1(8)" : "numberFormat(2)" ?>;
                      var nwc3 = counter.var3.numberFormat1(8);
                      $("#totalMoeda1").html(nwc1);
                      $("#totalMoeda2").html(nwc2);
                      $("#totalFavorita").html(nwc3);       
                  },
                  ease:Circ.easeOut
              });
    }
    
    
    function setMoedaFavorita(moeda) {
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . \Utils\Rotas::R_DASHBOARD_MOEDA_FAVORITA ?>',
            method: 'post',
            dataType:'json',
            data: {
                moeda: moeda
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        location.reload();
                    } else {
                        location.reload();
                    }
                } catch (e) {
                   
                }
            }
        });
    }
    
    function selectAction(moeda,categoria,url){
        if (url == 'R_DEPOSITOS'){
            var actionForm = $('<form>', {'action': '<?php echo URLBASE_CLIENT . \Utils\Rotas::R_DEPOSITOS ?>', 'method': 'post'}).append($('<input>', {'name': 'moeda', 'value': moeda, 'type': 'hidden'}), $('<input>', {'name': 'categoria', 'value': categoria, 'type': 'hidden'}));
            }else {    
            var actionForm = $('<form>', {'action': '<?php echo URLBASE_CLIENT . \Utils\Rotas::R_SAQUES ?>', 'method': 'post'}).append($('<input>', {'name': 'moeda', 'value': moeda, 'type': 'hidden'}), $('<input>', {'name': 'categoria', 'value': categoria, 'type': 'hidden'}));
            }
        $(document.body).append(actionForm);
        actionForm.submit();
    }

</script>

