<?php
$usuario = Utils\Geral::getLogado();
$moedas = (isset($_data["moedas"]) ? $_data["moedas"] : Array());
?>


<?php Utils\Layout::append("inspina/metas", $_data) ?>

<?php Utils\Layout::append("inspina/scripts", $_data) ?>


<?php Utils\Layout::append("inspina/menu", $_data) ?>


<div class="row wrapper border-bottom white-bg page-heading">
                <div class="col-lg-10">
                    <h2>Principal</h2>
                    <ol class="breadcrumb">
                        <li>
                            Dashboards
                        </li>
                        <li class="active">
                            <strong>Principal</strong>
                        </li>
                    </ol>
                </div>
            </div>

    <!-- Main content -->
    <section class="content">
        
        <br>
        
        <div class="row">
            <div class="col-lg-2">
                <div class="widget navy-bg p-lg text-center">
                    <div class="m-b-md">
                        
                        <h2 class="m-xs">S - <strong id="qtdCadastros">0</strong></h2>
                        <h2 class="m-xs">I - <strong id="qtdCadastrosIco">0</strong></h2>
                        <h3 class="font-bold no-margins">
                            Cadastrados - <strong id="totalCadastros">0</strong>
                        </h3>
                    </div>
                </div>
            </div>
            
            
            <div class="col-lg-2">
                <div class="widget blue-bg p-lg text-center">
                    <div class="m-b-md">
                        
                        <label class="m-xs h1" id="qtdVerificados">0</label><label class="m-xs" id="qtdVerificadosPorc">| 0%</label>
                        
                        <h3 class="font-bold no-margins">
                            Verificados
                        </h3>
                    </div>
                </div>
            </div>
            
            <div class="col-lg-2">
                <div class="widget red-bg p-lg text-center">
                    <div class="m-b-md">
                       
                        <h1 class="m-xs h1" id="qtdBloqueados">0</h1>
                        <h3 class="font-bold no-margins">
                            Bloqueados
                        </h3>
                    </div>
                </div>
            </div>
            <div class="col-lg-2">
                <div class="widget p-lg text-center" style="background-color: #DDDDDD">
                    <div class="m-b-md">
                        
                        <h1 class="m-xs h1" id="qtdPendentes" style="color: #FFFFFF">0</h1>
                        <h3 class="font-bold no-margins" style="color: #FFFFFF">
                            Pendentes
                        </h3>
                    </div>
                </div>
            </div>
            
            
            <div class="col-lg-2">
                <div class="widget yellow-bg p-lg text-center">
                    <div class="m-b-md">
                        
                        <h1 class="m-xs h1" id="qtdEspera">0</h1>
                        <h3 class="font-bold no-margins">
                            Aguardando
                        </h3>
                    </div>
                </div>
            </div>
            
            <div class="col-lg-2">
                <div class="widget lazur-bg p-lg text-center">
                    <div class="m-b-md">
                        
                        <h1 class="m-xs h1" id="qtdOnline">0</h1>
                        <h3 class="font-bold no-margins">
                            Online
                        </h3>
                    </div>
                </div>
            </div>
            
        </div>
        <div class="row">
            <div  id="dadosCadastroDia">                
            </div>
            <div id="filtro-clientes">                
            </div>
        </div>
        <div class="row">
                <div id="dadosCadastroMes">
                </div>
        </div>
        
        <div class="row">
            <div class="col col-lg-6">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>BRL => Depósitos | Saques | Remessa de Valores | Boletos</h5>
                    </div>
                    <div class="ibox-content table-responsive">
                        <table class="table table-hover table-bordered table-condensed table-striped" style="font-size: 10px;"> 
                            <thead>
                                <tr>
                                    <th class="text-center">
                                        E/S
                                    </th>
                                    <th class="text-center">
                                        Controle
                                    </th>
                                    <th class="text-center">
                                        Data
                                    </th>
                                    <th class="text-center"> 
                                        Cliente
                                    </th>
                                    <th class="text-center">
                                        Valor
                                    </th>
                                    <th class="text-center">
                                        Status
                                    </th>
                                    <th class="text-center">
                                        Movimento + Link
                                    </th>
                                </tr>
                            </thead>
                            <tbody id="movimentos-reais">
                                
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            
            <div class="col col-lg-6">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Criptomoedas => Depósitos | Saques </h5>
                    </div>
                    <div class="ibox-content table-responsive" id="atividades-pendentes">
                        <table class="table table-hover table-bordered table-condensed table-striped" style="font-size: 10px;"> 
                            <thead>
                                <tr>
                                    <th class="text-center">
                                        E/S
                                    </th>
                                    <th class="text-center">
                                        Moeda
                                    </th>
                                    <th class="text-center">
                                        Controle + Link
                                    </th>
                                    <th class="text-center">
                                        Data
                                    </th>
                                    <th class="text-center">
                                        Cliente
                                    </th>
                                    <th class="text-center">
                                        Valor
                                    </th>
                                    <th class="text-center">
                                        Status
                                    </th>
                                    <th class="text-center">
                                        Movimento
                                    </th>
                                </tr>
                                </tr>
                            </thead>
                            <tbody id="body-currency">
                                
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            
            
        </div>
        
        <div class="row">
            <div class="col col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <a href="<?php echo URLBASE_CLIENT . \Utils\Rotas::R_CLIENTES ?>"><h5>Clientes aguardando análise</h5></a>
                    </div>
                    <div class="ibox-content table-responsive" >
                        <table class="table table-hover table-bordered table-condensed table-striped" style="font-size: 10px;"> 
                            <thead>
                                <tr>
                                    <th class="text-center">
                                        Foto
                                    </th>
                                    <th class="text-center">
                                        Nome
                                    </th>
                                    <th class="text-center">
                                        Data de Cadastro
                                    </th>
                                    <th class="text-center">
                                        Documento
                                    </th>
                                    <th class="text-center">
                                        Residencia
                                    </th>
                                    <th class="text-center">
                                        Selfie
                                    </th>
                                </tr>
                            </thead>
                            <tbody id="clientes-aguardando">
                                
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="row">
            <div class="col col-lg-6">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Clientes online no sistema</h5>
                    </div>
                    <div class="ibox-content table-responsive" >
                        <table class="table table-hover table-bordered table-condensed table-striped" style="font-size: 10px;"> 
                            <thead>
                                <tr>
                                    <th class="text-center">
                                        País
                                    </th>
                                    <th class="text-center">
                                        Sigla
                                    </th>
                                    <th class="text-center">
                                        Foto
                                    </th>
                                    <th class="text-center">
                                        Cliente
                                    </th>
                                    <th class="text-center">
                                        Ip
                                    </th>
                                    <th class="text-center">
                                        Tempo de Atividade
                                    </th>
                                    <th class="text-center">
                                        Moeda Atual
                                    </th>
                                </tr>
                            </thead>
                            <tbody id="clientes-logados">
                                
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            
            <div class="col col-lg-6">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Order Book</h5>
                    </div>
                    <div class="ibox-content table-responsive" >
                        <table class="table table-hover table-bordered table-condensed table-striped" style="font-size: 10px;"> 
                            <thead>
                                <tr>
                                    <th class="text-center">
                                        Moeda
                                    </th>
                                    <th class="text-center">
                                        Ator 1
                                    </th>
                                    <th class="text-center">
                                        Ação
                                    </th>
                                    <th class="text-center">
                                        Ator 2
                                    </th>
                                    <th class="text-center">
                                        Volume
                                    </th>
                                    <th class="text-center">
                                        Cotação
                                    </th>
                                    <th class="text-center">
                                        Data e hora
                                    </th>
                                </tr>
                            </thead>
                            <tbody id="orderbook">
                                
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
            
        
        <div class="row">
            <div class="col col-lg-6">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Movimentaçõe em Carteiras Remotas</h5>
                    </div>
                    <div class="ibox-content table-responsive">
                        <table class="table table-hover table-bordered table-condensed table-striped" style="font-size: 10px;"> 
                            <thead>
                                <tr>
                                    <th class="text-center">
                                        E/S
                                    </th>
                                    <th class="text-center">
                                        Estabelecimento
                                    </th>
                                    <th class="text-center">
                                        Wallet
                                    </th>
                                    <th class="text-center">
                                        Data
                                    </th>
                                    <th class="text-center">
                                        Valor
                                    </th>
                                    <th class="text-center">
                                        Tipo
                                    </th>
                                </tr>
                            </thead>
                            <tbody id="movimentos-remote-walltes">
                                
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            
            <div class="col col-lg-6">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Movimentaçõe em Invoices (Pagas)</h5>
                    </div>
                    <div class="ibox-content table-responsive">
                        <table class="table table-hover table-bordered table-condensed table-striped" style="font-size: 10px;"> 
                            <thead>
                                <tr>
                                    <th class="text-center">
                                        Etabelecimento
                                    </th>
                                    <th class="text-center">
                                        PDV
                                    </th>
                                    <th class="text-center">
                                        Data
                                    </th>
                                    <th class="text-center">
                                        Valor BRL
                                    </th>
                                    <th class="text-center">
                                        Valor BTC
                                    </th>
                                    <th class="text-center">
                                        Valor Recebido BTC
                                    </th>
                                    <th class="text-center">
                                        Status
                                    </th>
                                </tr>
                            </thead>
                            <tbody id="movimentos-invoices">
                                
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="row">
            
            <div class="col col-lg-12">
                
                <div class="ibox">
                    <div class="ibox-content table-responsive">
                        
                        <h2 class="text-center"><strong>Status das Moedas</strong></h2>
                        
                        <table class="table table-striped table-hover table-condensed table-bordered">
                            <thead>
                                <tr>
                                    <th class="text-center" ><strong>Moeda</strong></th>
                                    <th class="text-center" ><strong>Clientes</strong></th>
                                    <th class="text-center" ><strong>Empresa</strong></th>
                                    <th class="text-center" ><strong>Investido</strong></th>
                                    <th class="text-center" ><strong>Total</strong></th>
                                    <th class="text-center" ><strong>CORE</strong></th>
                                    <th class="text-center" ><strong>Ult. Atu. API</strong></th>
                                    <th class="text-center" ><strong>Ult. Leitura CORE</strong></th>
                                </tr>
                            </thead>
                            <tbody>

                                <tr>
                                    <td>Real</td>
                                    <td class="text-center" id="saldo-clientes-1"><?php echo number_format(0, 2, ",", ".")?></td>
                                    <td class="text-center" id="saldo-empresa-1"><?php echo number_format(0, 2, ",", ".")?></td>
                                    <td class="text-center">-</td>
                                    <td class="text-center" id="saldo-saldos-1"><?php echo number_format(0, 2, ",", ".")?></td>
                                    <td class="text-center" colspan="3"></td>
                                </tr>

                                <?php 
                                foreach ($moedas as $moeda) {
                                    ?>

                                <tr>
                                    <td><?php echo $moeda->nome ?></td>
                                    <td class="text-center" id="saldo-clientes-<?php echo $moeda->id ?>"><?php echo number_format(0, 2, ",", ".")?></td>
                                    <td class="text-center" id="saldo-empresa-<?php echo $moeda->id ?>"><?php echo number_format(0, 2, ",", ".")?></td>
                                    <td class="text-center" id="saldo-investido-<?php echo $moeda->id ?>">-</td>
                                    <td class="text-center" id="saldo-saldos-<?php echo $moeda->id ?>"><?php echo number_format(0, 2, ",", ".")?></td>
                                    <td class="text-center" id="saldo-core-<?php echo $moeda->id ?>"></td>
                                    <td class="text-center" >
                                        <i id="dt-api-ico-<?php echo $moeda->id ?>" class="fa "></i>&nbsp;<span id="dt-api-<?php echo $moeda->id ?>"></span>
                                    </td>
                                    <td class="text-center">
                                        <i id="dt-core-ico-<?php echo $moeda->id ?>" class="fa "></i>&nbsp;<span id="dt-core-<?php echo $moeda->id ?>"></span>
                                    </td>
                                </tr>
                                    <?php
                                }
                                ?>


                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            
            
            
        </div>
        
        
        
        
    
        
    </section>
    <br><br>
    <div class="clearfix"></div>

<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>


<script>
    $(document).ready(function () {
        saldos();
        getTasksPendentes();
        
        setInterval(function() {
                    saldos();
                    getTasksPendentes();
                    getMovimentosWalltsPendentes();
                    getMovimentosInvoices();
                  },10000);
    });
    
    
    
    function saldos() {
        
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_DASHBOARD_SALDOS_CLIENTES ?>',
            dataType: "json",
            method: "post",
            success: function (json) {
                try {
                    if (json.sucesso) {
                        
                        var i = 0;
                        for (i = 0; i < json.clientes.length; i++) {
                            var m = json.clientes[i];
                            $("#saldo-clientes-" + m.id).html(m.saldo);
                        }
                        for (i = 0; i < json.empresa.length; i++) {
                            var m = json.empresa[i];
                            $("#saldo-empresa-" + m.id).html(m.saldo);
                        }
                        
                        for (i = 0; i < json.investido.length; i++) {
                            var m = json.investido[i];
                            $("#saldo-investido-" + m.id_moeda).html(m.volume_total);
                        }
                        
                        for (i = 0; i < json.saldo.length; i++) {
                            var m = json.saldo[i];
                            $("#saldo-saldos-" + m.id).html(m.saldo);
                        }
                        for (i = 0; i < json.core.length; i++) {
                            var c = json.core[i];
                            var t = json.saldo[i + 1];
                            var coreSaldo = parseFloat(c.saldo);
                            var totalSaldo = parseFloat(t.saldo);
                            
                            $("#saldo-core-" + c.id).html(c.saldo).css("color", (totalSaldo > coreSaldo ? "#ff1e1e" : "#1ab394"));
                        }
                        
                        
                        for (i = 0; i < json.datas.length; i++) {
                            var m = json.datas[i];
                            $("#dt-core-" + m.moeda).html(m.core);
                            $("#dt-core-ico-" + m.moeda).css("color", (m.alertaCore ? "#ff1e1e" : "#1ab394"));
                            $("#dt-core-ico-" + m.moeda).addClass(m.alertaCore ? "fa-times-rectangle" : "fa-check-square");
                            $("#dt-api-" + m.moeda).html(m.api);
                            $("#dt-api-ico-" + m.moeda).css("color", (m.alertaApi ? "#ff1e1e" : "#1ab394"));
                            $("#dt-api-ico-" + m.moeda).addClass(m.alertaApi ? "fa-times-rectangle" : "fa-check-square");
                        }                        
                    }
                } catch (e) {
                    
                }
            }  
        });
        
    }
    
    var cods = [];
    var aguardando = 0;
    function getTasksPendentes() {
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . \Utils\Rotas::R_DASHBOARD_TASKS_PENDENTES ?>',
            method: 'post',
            dataType: 'json',
            data: {
                
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                       var i = 0;
                       var tocar = false;
                       
                       for(i = 0; i < json.cods.length; i++) {
                           var j = 0;
                           var adicionar = true;
                           
                           if (cods.length > 0) {
                                for (j = 0; j < cods.length; j++) {
                                    if (cods[j] === json.cods[i]) {
                                        adicionar = false;
                                        j = cods.length;
                                    }
                                }
                                if (adicionar) {
                                    tocar = true;
                                    cods.push(json.cods[i]);
                                }
                            } else {
                                tocar = true;
                                cods.push(json.cods[i]);
                            }
                       }
                       
                       $("#movimentos-reais").html(json.movimentosReais);
                       $("#body-currency").html(json.htmlCriptocurrencies);
                       
                       $("#saques-reais").html(json.saquesReais);
                       $("#depositos-reais").html(json.depositosReais);
                       $("#clientes-aguardando").html(json.clientesAguardando);
                       $("#clientes-logados").html(json.clientesOnline);
                       $("#orderbook").html(json.orderBook);
                       $("#filtro-clientes").html(json.cadastroClientes);
                       $("#dadosCadastroMes").html(json.dadosCadastroMes);
                       $("#dadosCadastroDia").html(json.dadosCadastroDia);
                       
                       
                        $("#qtdPendentes").html(json.qtdPendentes);
                        $("#qtdBloqueados").html(json.qtdBloqueados);
                        $("#qtdVerificados").html(json.qtdVerificados);
                        $("#qtdVerificadosPorc").html(json.qtdVerificadosPorc);
                        $("#qtdCadastros").html(json.qtdCadastros);
                        $("#qtdCadastrosIco").html(json.qtdCadastrosIco);
                        $("#totalCadastros").html(json.totalCadastros); 
                        $("#qtdEspera").html(json.qtdEspera);
                        $("#qtdOnline").html(json.qtdOnline);
                       
                       if (json.qtdEspera > aguardando) {
                           document.getElementById("nova-task-audio").play();
                       }
                       aguardando = json.qtdEspera;
                       
                       
                       if (tocar) {
                           document.getElementById("nova-task-audio").play();
                       }
                    }
                } catch(e) {
                }
            }
        });
    }
    
    
    
    function getMovimentosWalltsPendentes() {
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . \Utils\Rotas::R_DASHBOARD_HISTORICO_REMOTEWALLETS ?>',
            method: 'post',
            dataType: 'json',
            data: {
                
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                       $("#movimentos-remote-walltes").html(json.html);
                    }
                } catch(e) {
                }
            }
        });
    
    }
    
    
    
    function getMovimentosInvoices() {
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . \Utils\Rotas::R_DASHBOARD_HISTORICO_REMOTEINVOICES ?>',
            method: 'post',
            dataType: 'json',
            data: {
                
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                       $("#movimentos-invoices").html(json.html);
                    }
                } catch(e) {
                }
            }
        });
    
    }
    
</script>