<!DOCTYPE html>
<html lang="pt-br">
<?php Utils\Layout::append("site/head") ?>
<style>
    p {
        margin: 0;
        text-indent: 3ch;
    }
</style>
<body>
<?php Utils\Layout::append("site/header") ?>
<section class="breadcrumb-area bread-bg">
    <div class="overlay"></div>
    <div class="container">
        <div class="breadcrumb-content d-flex flex-wrap align-items-center justify-content-between position-relative">
            <h2 class="sec-title text-white my-2">Sobre nós</h2>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb justify-content-center">
                    <li class="breadcrumb-item"><a href="<?php echo URLBASE_CLIENT; ?>">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Sobre nós</li>
                </ol>
            </nav>
        </div>
    </div>
</section>
<div class="container">
    <div class="row padding-top-30px">
        <div class="col-lg-12 mb-2 mb-lg-0">
            <div class="card">
                <div class="card-body">
                    <h3 class="mb-3">Isis soluções de blockchain</h3>
                    <div class="title-shape mb-4"><span></span></div>
                    <p class="mb-2 font-weight-normal">
                        Somos uma Exchange voltada a segurança e confiabilidade, nosso desenvolvimento permitiu criar uma plataforma de negociações rápida e extremamente confiável.
                    </p>
                    <p class="mb-2 font-weight-normal">
                        Estamos empenhados a fornecer uma solução completa dentro do mundo cripto, o objetivo do nosso trabalho é encontrar soluções eficazes para otimizar a experiência de nossos usuários, tornando as criptomoedas acessível a todos.
                    </p>
                    <p class="mb-2 font-weight-normal">
                        Criamos a Isis Trade para ajudar aqueles que acreditam no potencial das criptomoedas a alcaçar seus objetivos e liberdade financeira.
                    </p>
                    <p class="mb-4 font-weight-normal">
                        Somos uma equipe de profissionais totalmente capacitados e preparados para pensar a frente, nosso time conta com mais de uma década de experiência em programação voltada ao criptomercado.
                    </p>
                    <h5 class="mb-2">
                        Serviços
                    </h5>
                    <ul>
                        <li>
                            ✓) Exchange completa para compra e venda de criptoativos;
                        </li>
                        ✓) Carteiras cripto únicas e intransferíveis;
                        <li>
                            ✓) Suporte especializado;
                        </li>
                        <li>
                            ✓) Plataforma responsiva, dessa forma não é necessário a instalação de nenhum APP para fazer operações em seu smartfone;
                        </li>
                        <li>
                            ✓) Taxas acessíveis para transações e saques.
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<?php Utils\Layout::append("site/footer") ?>
<?php Utils\Layout::append("site/script") ?>
</body>
</html>