<!DOCTYPE html>
<html lang="pt-br">
<?php Utils\Layout::append("site/head") ?>
<style>
    p {
        margin: 0;
        text-indent: 3ch;
    }
</style>
<body>
<?php Utils\Layout::append("site/header") ?>
<section class="breadcrumb-area bread-bg">
    <div class="overlay"></div>
    <div class="container">
        <div class="breadcrumb-content d-flex flex-wrap align-items-center justify-content-between position-relative">
            <div class="my-2">
                <h2 class="sec-title text-white mb-2">Regras de compliance</h2>
                <p class="text-white">Última revisão: 23 março, 2022</p>
            </div>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb justify-content-center">
                    <li class="breadcrumb-item"><a href="<?php echo URLBASE_CLIENT; ?>">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Regras de compliance</li>
                </ol>
            </nav>
        </div>
    </div>
</section>
<section class="terms-area section--padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <h3 class="card-text mb-3"><strong>REGRAS DE COMPLIANCE &ndash; ISIS TRADE</strong></h3>
                        <p class="card-text mb-2">Compliance &eacute; um conjunto de pr&aacute;ticas adotadas pelo mercado financeiro internacional, fundada em preceitos &eacute;ticos e em total observ&acirc;ncia ao conjunto de leis onde ser&atilde;o desenvolvidas suas atividades, buscando prevenir toda e qualquer exposi&ccedil;&atilde;o a riscos, sejam eles legais, regulat&oacute;rios ou de imagem.</p>
                        <p class="card-text mb-2">A <strong>ISIS TRADE</strong> preza pela seguran&ccedil;a, confiabilidade e transpar&ecirc;ncia de suas opera&ccedil;&otilde;es. Por isso, estabeleceu suas regras de compliance baseando&shy;se na Resolu&ccedil;&atilde;o do Conselho Monet&aacute;rio Nacional no 4.595, de 30 de agosto de 2017, bem como na Lei 12.846/2013 &ndash; Lei Anticorrup&ccedil;&atilde;o, tendo como compromisso principal a implementa&ccedil;&atilde;o e manuten&ccedil;&atilde;o de pol&iacute;ticas efetivas capazes de reduzir os riscos e conferir transpar&ecirc;ncia &agrave;s suas opera&ccedil;&otilde;es, com uma divis&atilde;o clara de responsabilidades dos seus colaboradores e clientes, gerenciando e mitigando os riscos eventualmente encontrados, com absoluta observ&acirc;ncia &agrave; legisla&ccedil;&atilde;o an&aacute;loga aplic&aacute;vel.</p>
                        <p class="card-text mb-2">Para isso, foram estabelecidos procedimentos de valida&ccedil;&atilde;o de nossa base de clientes, diligenciando sempre que necess&aacute;rio &agrave; verifica&ccedil;&atilde;o de dados e documentos enviados pelos clientes, de modo a conhecer individualmente cada um dos interessados em ingressar na plataforma, validando os dados apresentados no formul&aacute;rio on line disponibilizado aos interessados, reservando&shy;se no direito de aprovar ou recusar o cadastro, se o caso.</p>
                        <p class="card-text mb-2">Al&eacute;m disso, a <strong>ISIS TRADE</strong> supervisiona de maneira rigorosa as opera&ccedil;&otilde;es de sua plataforma, n&atilde;o aceitando qualquer tipo de dep&oacute;sito em moeda corrente sem identifica&ccedil;&atilde;o do depositante, exigindo que seus clientes sempre o fa&ccedil;am atrav&eacute;s de <strong>ISIS SOLUCOES DE BLOCKCHAIN LTDA</strong>. (denominada &ldquo;<strong>ISIS TRADE</strong>&rdquo;) transfer&ecirc;ncia eletr&ocirc;nica do mesmo titular ou, se o caso, atrav&eacute;s de dep&oacute;sitos identificados na origem. Aos nossos clientes, informamos que todas as opera&ccedil;&otilde;es suspeitas realizadas dentro da plataforma ser&atilde;o analisadas e devidamente reportadas aos &oacute;rg&atilde;os competentes.</p>
                        <p class="card-text mb-2">Com este conjunto de pr&aacute;ticas, a <strong>ISIS TRADE</strong> refor&ccedil;a sua conduta e ades&atilde;o &agrave;s pr&aacute;ticas internacionais de preven&ccedil;&atilde;o de atos il&iacute;citos, como Lavagem de Dinheiro e outras atividades de financiamento de pr&aacute;ticas ilegais.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<?php Utils\Layout::append("site/footer") ?>
<?php Utils\Layout::append("site/script") ?>
</body>
</html>