<?php
$empresa = Models\Modules\Cadastro\EmpresaRn::getEmpresa();
?>
<!DOCTYPE html>
<html lang="pt-br">
<?php Utils\Layout::append("site/head") ?>
<link rel="<?php echo SITE; ?>stylesheet" href="css/leaflet.css"/>
<body>
<?php Utils\Layout::append("site/header") ?>
<section class="breadcrumb-area bread-bg">
    <div class="overlay"></div>
    <div class="container">
        <div class="breadcrumb-content d-flex flex-wrap align-items-center justify-content-between position-relative">
            <h2 class="sec-title text-white my-2">Nossos contatos</h2>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb justify-content-center">
                    <li class="breadcrumb-item"><a href="<?php echo URLBASE_CLIENT; ?>">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Nossos contatos</li>
                </ol>
            </nav>
        </div>
    </div>
</section>
<section class="contact-area section-padding-contact">
    <div class="container">
        <div class="alert alert-success alert-message mb-3" role="alert"></div>
        <div class="row my-5">
            <div class="col-lg-6 col-md-6">
                <div class="card hover-y text-center">
                    <div class="card-body">
                        <div class="icon-element">
                            <i class="fal fa-map-marker-alt"></i>
                        </div>
                        <h4 class="card-title mt-4">Nossa localização</h4>
                        <p class="card-text"><?php echo $empresa->municipio . ' - '. $empresa->estado . ', '. $empresa->pais?></p>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-md-6">
                <div class="card hover-y text-center">
                    <div class="card-body">
                        <div class="icon-element">
                            <i class="fal fa-envelope"></i>
                        </div>
                        <h4 class="card-title mt-4">E-mail para contato</h4>
                        <p class="card-text"><a href="mailto:<?php echo $empresa->emailSuporte ?>" class="btn-link"><?php echo $empresa->emailSuporte ?></a></p>
                    </div>
                </div>
            </div>
        </div>
        <div id="map" style="height: 400px"></div>
    </div>
</section>
<?php Utils\Layout::append("site/footer") ?>
<?php Utils\Layout::append("site/script") ?>
<script src="<?php echo SITE; ?>js/leaflet.js"></script>
<script src="<?php echo SITE; ?>js/map.js"></script>
</body>
</html>