<!DOCTYPE html>
<html lang="pt-br">
<?php Utils\Layout::append("site/head") ?>
<body>
<?php Utils\Layout::append("site/header") ?>
<section class="breadcrumb-area bread-bg">
    <div class="overlay"></div>
    <div class="container">
        <div class="breadcrumb-content d-flex flex-wrap align-items-center justify-content-between position-relative">
            <div class="my-2">
                <h2 class="sec-title text-white mb-2">Documentação de nossa API</h2>
            </div>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb justify-content-center">
                    <li class="breadcrumb-item"><a href="<?php echo URLBASE_CLIENT; ?>">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Documentação API</li>
                </ol>
            </nav>
        </div>
    </div>
</section>
<section class="terms-area section--padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <div class="container">
                            <div class="row">
                                <div class="col-lg-12">

                                    <div class="accordion" id="body-itens">
                                        <div class="card">
                                            <div class="card-header" id="headingOne">
                                                <button class="btn" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                                                    Metodos e detalhes
                                                    <i class="fal fa-plus"></i>
                                                </button>
                                            </div>
                                            <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExampleFaq">
                                                <div class="card-body">
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<?php Utils\Layout::append("site/footer") ?>
<?php Utils\Layout::append("site/script") ?>
<script>
        $( document ).ready(function() {
            docs();
            function docs() {
                let url = "<?php echo DOCS;?>";
                let trHTML = "";
                try {
                    $.ajax(ajaxSettings("GET", url))
                        .done(function (json, status) {
                            console.log(json.item);
                                for(let i = 0; i < json.item.length; i++){

                                    trHTML += '' +
                                        json.item[i]['name'];
                                        json.item[i]['description'];
                                }
                                $('#body-itens').html(trHTML);


                        })
                        .fail(function () {
                            setTimeout(listParBook, 20000);
                        })
                } catch (e) {
                    setTimeout(listParBook, 20000)
                }
            }
        })
</script>
</body>
</html>