<!DOCTYPE html>
<html lang="pt-br">
<?php Utils\Layout::append("site/head") ?>
<body>
<?php Utils\Layout::append("site/header") ?>
<section class="breadcrumb-area bread-bg">
    <div class="overlay"></div>
    <div class="container">
        <div class="breadcrumb-content d-flex flex-wrap align-items-center justify-content-between position-relative">
            <div class="my-2">
                <h2 class="sec-title text-white mb-2">Perguntas frequentes</h2>
            </div>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb justify-content-center">
                    <li class="breadcrumb-item"><a href="<?php echo URLBASE_CLIENT; ?>">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Faq</li>
                </ol>
            </nav>
        </div>
    </div>
</section>
<section class="faq-area section--padding">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <ul class="nav nav-pills nav-fill" id="btn-itens">
                </ul>
            </div>
        </div>
            <div class="tab-content clearfix" id="category-itens">
            </div>
        </div>
</section>
<?php Utils\Layout::append("site/footer") ?>
<?php Utils\Layout::append("site/script") ?>
<script src="<?php echo SITE; ?>js/jquery.min.js"></script>
<script src="<?php echo SITE; ?>js/bootstrap.min.js"></script>
<script>
    $( document ).ready(function() {
        var ind = 0;
        var pe = 0;
        docs();
        function conten(p,item,posi,l){
            var trHTMLcontent = "";
            let c = 0;
                for(Object.keys(item[c]); c < posi; ++c) {
                    $.each(Object.keys(item[c]), function(p) {
                        pe++;
                    })
                    trHTMLcontent += '<div class="col-md-6">' +
                        '<div class="accordion" id="a' + c + '">' +
                        '<div class="card">' +
                        '<div class="card-header" id="h' + c + '">' +
                        '<button class="btn" type="button" data-toggle="collapse" data-target="#c' + pe + '" aria-expanded="false" aria-controls="c' + c + '">' +
                        item[c].pergunta +
                        '<i class="fal fa-plus"></i>' +
                        '</button>' +
                        '</div>' +
                        '<div id="c' + pe + '" class="collapse" aria-labelledby="h' + pe + '" data-parent="#a' + c + '">' +
                        '<div class="card-body">' +
                        item[c].resposta +
                        '</div>' +
                        '</div>' +
                        '</div>' +
                        '</div>' +
                        '</div>';
                };
            return trHTMLcontent;
        }

        function docs() {
            let url = "<?php echo FAQS;?>";
            let trHTML = "";
            let trHTMLcard = "";
            try {
                $.ajax(ajaxSettings("GET", url))
                    .done(function (json) {
                        var p = json.faqs
                        let b = 0;
                        ind = Object.keys(p).length
                        let q = 0;

                        $.each(p, function(i) {
                            b++;
                            trHTML +=  '<li class="nav-item '+ b +'a mb-2">' +
                                            '<a class="nav-link '+ b +'a" href="#'+ b +'a" data-toggle="tab">'+ i +'</a>' +
                                        '</li>';
                            });
                        let l = 0;
                        $.each(p, function(i, item) {
                            let posi = Object.keys(item).length;
                            l++;
                            trHTMLcard +=  '<div class="tab-pane" id="'+ l +'a">' +
                                '<div class="row mt-4">' +
                                conten(p,item,posi,l) +
                                '</div>' +
                                '</div>';
                        });
                        $('#btn-itens').html(trHTML);
                        $('#category-itens').html(trHTMLcard);
                        $(".1a").addClass('active');
                        $("#1a").addClass('active');
                        $(".1a").trigger('click');
                    })
                    .fail(function () {
                        setTimeout(docs, 20000);
                    })
            } catch (e) {
                setTimeout(docs, 20000)
            }
        }
    })
</script>
</body>
</html>