<!DOCTYPE html>
<html lang="pt-br">
<?php Utils\Layout::append("site/head") ?>
<style>
    p {
        margin: 0;
        text-indent: 3ch;
    }
</style>
<body>
<?php Utils\Layout::append("site/header") ?>
<section class="breadcrumb-area bread-bg">
    <div class="overlay"></div>
    <div class="container">
        <div class="breadcrumb-content d-flex flex-wrap align-items-center justify-content-between position-relative">
            <div class="my-2">
                <h2 class="sec-title text-white mb-2">Normativa 1888</h2>
                <p class="text-white">Última revisão: 10 julho, 2019</p>
            </div>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb justify-content-center">
                    <li class="breadcrumb-item"><a href="<?php echo URLBASE_CLIENT; ?>">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Normativa 1888</li>
                </ol>
            </nav>
        </div>
    </div>
</section>
<section class="terms-area section--padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body justificado">
                        <h3>Instrução normativa RFB Nº 1888</h3>
                        </br>
                        <p>Institui e disciplina a obrigatoriedade de prestação de informações relativas às operações realizadas com criptoativos à Secretaria Especial da Receita Federal do Brasil (RFB).</p>
                        </br>
                        <h4 class="card-title mb-2">
                            O que define a IN 1888 2019?
                        </h4>
                        <p class="card-text mb-2">
                            A Instrução Normativa ou IN 1888 2019, de 3 de maio de 2019, <strong>institui e disciplina a obrigatoriedade de prestação de informações relativas às operações realizadas com criptoativos à Secretaria Especial da Receita Federal do Brasil</strong> entrando em vigor na data de sua publicação no Diário Oficial da União e passando a produzir efeitos a partir de 1º de agosto de 2019.
                        </p>
                        <p class="card-text mb-2">
                        Nela é definido o que são criptoativos e exchanges de criptoativos sob a ótica da RFB. Vejamos:
                        </p>
                        <p class="card-text mb-2">
                            <strong>I – criptoativo:</strong> a representação digital de valor denominada em sua própria unidade de conta, cujo preço pode ser expresso em moeda soberana local ou estrangeira, transacionado eletronicamente com a utilização de criptografia e de tecnologias de registros distribuídos, que pode ser utilizado como forma de investimento, instrumento de transferência de valores ou acesso a serviços, e que não constitui moeda de curso legal;
                        </p>
                        <p class="card-text mb-4">
                            <strong>II – exchange de criptoativo:</strong> a pessoa jurídica, ainda que não financeira, que oferece serviços referentes a operações realizadas com criptoativos, inclusive intermediação, negociação ou custódia, e que pode aceitar quaisquer meios de pagamento, inclusive outros criptoativos.Parágrafo único. Incluem-se no conceito de intermediação de operações realizadas com criptoativos, a disponibilização de ambientes para a realização das operações de compra e venda de criptoativo realizadas entre os próprios usuários de seus serviços.
                        </p>
                        <h4 class="card-title mb-2">
                        Quem está obrigado a prestar informações?
                        </h4>
                        <p class="card-text mb-2">
                            O art. 6º da IN 1888 especifica quem está obrigado a prestar informações. Assim, as pessoas obrigadas a prestação de informações são todas as <strong>exchanges de criptoativos domiciliadas</strong> para fins tributários no Brasil e toda <strong>pessoa física</strong> ou <strong>jurídica</strong> residente ou domiciliada no Brasil quando <strong>suas as operações forem realizadas em exchange domiciliada no exterior ou  quando suas as operações não forem realizadas em exchange (P2P)</strong>.
                        </p>
                        <p class="card-text mb-2">
                        Ou seja, no caso das exchanges brasileiras, deverão  ser informadas todas as operações dos clientes que ali transacionam, ademais a IN 1888 abrange as operações realizadas através de P2P cujo valor mensal das operações, isolado ou conjuntamente, ultrapasse R$ 30.000,00 (trinta mil reais).
                        </p>
                        <p class="card-text mb-4">
                        Por “operação” entende-se qualquer que seja a compra e venda, permuta, doação, transferência de criptoativo para a exchange, retirada de criptoativo da exchange, cessão temporária (aluguel), dação em pagamento, emissão e outras operações que impliquem em transferência de criptoativos.
                        </p>
                        <h4 class="card-title mb-2">
                        IN 1888 2019: Por onde devo informar?
                        </h4>
                        <p class="card-text mb-2">
                            <s>O conjunto de informações deverá ser enviado<strong> de forma eletrônica</strong>,  assinado digitalmente pela pessoa física, pelo representante legal da pessoa jurídica ou pelo procurador, constituído nos termos da Instrução Normativa RFB nº 1.751, de 16 de outubro de 2017, mediante o uso de <strong>certificado digital</strong> válido, emitido por entidade credenciada pela Infraestrutura de Chaves Públicas Brasileira (ICP-Brasil).</s>
                        </p>
                        <p class="card-text mb-4">
                            As informações a que se refere a IN 1888 deverão ser prestadas com a utilização do <strong>sistema Coleta Nacional</strong>, disponibilizado por meio do Centro Virtual de Atendimento (e-CAC) da RFB (https://cav.receita.fazenda.gov.br/autenticacao/login), em formato a ser definido e publicado no prazo de até 60 dias, contado a partir de 03/05/2019. Ademais, a Copes deverá editar e divulgar o manual de orientação do sistema Coleta Nacional.
                        </p>
                        <h4 class="card-title mb-2">
                        IN 1888/2019: O que devo informar?
                        </h4>
                        <p class="card-text mb-2">
                            No caso das <strong>exchanges brasileiras</strong> e pessoas físicas ou jurídicas que realizaram <strong>transações via P2P</strong> (operações que não forem realizadas em exchange), deverão ser reportadas as seguintes informações:
                        </p>
                        <ul>
                            <li>
                                a) a data da operação;
                            </li>
                                b) o tipo da operação (compra e venda, permuta, doação, etc.);
                            <li>
                                c) os titulares da operação;
                            </li>
                            <li>
                                d) os criptoativos usados na operação;
                            </li>
                            <li>
                                e) a quantidade de criptoativos negociados, em unidades, até a décima casa decimal;
                            </li>
                            <li>
                                f) o valor da operação, em reais, excluídas as taxas de serviço cobradas para a execução da operação, quando houver;
                            </li>
                            <li>
                                g) o valor das taxas de serviços cobradas para a execução da operação, em reais, quando houver; e
                            </li>
                            <li>
                                h) o endereço da wallet de remessa e de recebimento, se houver.
                            </li>
                        </ul>
                        <p class="card-text mb-2">
                        No caso de a pessoa física ou jurídica ter realizado quaisquer das <strong>operações</strong> acima mencionadas em <strong>exchange domiciliada no exterior</strong>, deverá reportar as seguintes informações:
                        </p>
                        <ul>
                            <li>
                        a) a identificação da exchange;
                            </li>
                            <li>
                        b) a data da operação;
                            </li>
                        c) o tipo de operação (compra e venda, permuta, doação, etc.);
                            </li>
                            <li>
                        d) os criptoativos usados na operação;
                            </li>
                            <li>
                        e) a quantidade de criptoativos negociados, em unidades, até a décima casa decimal;
                            </li>
                            <li>
                        f) o valor da operação, em reais, excluídas as taxas de serviço cobradas para a execução da operação, quando houver;
                            </li>
                            <li>
                        g) o valor das taxas de serviços cobradas para a execução da operação, em reais, quando houver; e
                            </li>
                            <li>
                        h) o endereço da wallet de remessa e de recebimento, se houver.
                            </li>
                        </ul>
                        <p class="card-text mb-4">
                        Ademais, deverão constar junto às informações acima mencionadas, a identificação dos titulares das operações e incluir nome, nacionalidade, domicílio fiscal, endereço, número de inscrição no Cadastro de Pessoas Físicas (CPF) ou no Cadastro Nacional da Pessoa Jurídica (CNPJ) ou Número de Identificação Fiscal (NIF) no exterior, quando houver, nome empresarial e demais informações cadastrais.
                        </p>
                        <h4 class="card-title mb-2">
                        Qual o prazo para informar?
                        </h4>
                        <p class="card-text mb-2">
                        As <strong>exchanges brasileiras</strong>, pessoas físicas ou jurídicas que realizaram transações via P2P (operações que não forem realizadas em exchange) ou operações em exchange domiciliada no exterior, deverão reportar as informações até às 23h59min59s do <strong>último dia útil</strong> do mês-calendário subsequente àquele em que ocorreu o conjunto de operações realizadas com criptoativos.
                        </p>
                        <p class="card-text mb-2">
                        Outrossim, as exchanges brasileiras deverão reportar também, o saldo de moedas fiduciárias (em reais), o custo, em reais, de obtenção de cada espécie de criptoativo declarado pelo usuário e o saldo de cada espécie de criptoativo (em unidade dos respectivos criptoativos)  de todos os usuários de seus serviços, relativo a 31 de dezembro de cada ano, até as 23h59min59s do último dia útil do mês de <strong>janeiro</strong> do <strong>ano-calendário subsequente</strong>.
                        </p>
                        <p class="card-text mb-4">
                        O primeiro reporte de informações a ser entregue será em setembro de 2019 referente às operações realizadas em agosto de 2019.
                        </p>
                        <h4 class="card-title mb-2">
                        Poderei retificar as informações enviadas?
                        </h4>
                        <p class="card-text mb-4">
                        Caso a pessoa física ou jurídica constate que as informações prestadas contêm erros, inexatidões ou omissões, poderá corrigi-los ou supri-las, conforme o caso, mediante apresentação de retificação, não incidindo multa relativamente aos erros, inexatidões e omissões desde que sejam corrigidos ou supridas antes de iniciado qualquer procedimento de ofício.
                        </p>
                        <h4 class="card-title mb-2">
                        O que acontece se eu deixar de informar?
                        </h4>
                        <p class="card-text mb-2">
                        Conforme a IN 1888 2019, a pessoa física ou jurídica que deixar de prestar as informações a que estiver obrigada ou que prestá-las fora dos prazos ou que omitir informações ou prestar informações inexatas, incompletas ou incorretas, ficará sujeita à multa, conforme o caso. Vejamos:
                        </p>
                        <ul>
                            <li>
                                <strong>I – pela prestação extemporânea:</strong>
                            </li>
                            <li>
                                a) <strong>R$ 500,00</strong> (quinhentos reais) <strong>por mês ou fração de mês</strong>, se o declarante for pessoa jurídica em início de atividade, imune ou isenta, optante pelo Regime Especial Unificado de Arrecadação de Tributos e Contribuições devidos pelas Microempresas e Empresas de Pequeno Porte (Simples Nacional), instituído pela Lei Complementar nº 123, de 14 de dezembro de 2006, ou que na última declaração apresentada tenha apurado o Imposto sobre a Renda da Pessoa Jurídica (IRPJ) com base no lucro presumido;
                            </li>
                            <li>
                                b) <strong>R$ 1.500,00</strong> (mil e quinhentos reais) <strong>por mês ou fração de mês</strong>, se o declarante for pessoa jurídica não incluída na alínea “a”; ou
                            </li>
                            <li>
                                c) <strong>R$ 100,00</strong> (cem reais) por mês ou fração, se <strong>pessoa física</strong>;
                            </li>
                            <li>
                                II – <strong>pela prestação com informações inexatas, incompletas ou incorretas ou com omissão de informação:</strong>
                            </li>
                            <li>
                                a) <strong>3%</strong> (três por cento) do <strong>valor da operação</strong> a que se refere a informação omitida, inexata, incorreta ou incompleta, não inferior a R$ 100,00 (cem reais), se o declarante for pessoa jurídica; ou
                            </li>
                            <li>
                                b) <strong>1,5%</strong> (um inteiro e cinco décimos por cento) do valor da operação a que se refere a informação omitida, inexata, incorreta ou incompleta, se o declarante for pessoa física; e
                            </li>
                            <li>
                                III – <strong>pelo não cumprimento à intimação da RFB para cumprir obrigação acessória ou para prestar esclarecimentos nos prazos estipulados pela autoridade fiscal, o valor de R$ 500,00 (quinhentos reais) por mês-calendário;</strong>
                            </li>
                            <li>
                        Caso o declarante seja pessoa jurídica optante pelo Simples Nacional, a multa de 3% do valor da operação informada, prevista na alínea “a” do inciso II do caput, será reduzida em 70%.
                            </li>
                            <li>
                        A multa de R$ 1.500,00 por mês ou fração de mês, prevista na alínea “b” do inciso I do caput, será aplicada também, em caso de apresentação das informações fora do prazo à pessoa jurídica que na última declaração tenha utilizado mais de uma forma de apuração do lucro ou tenha realizado operação de reorganização societária.
                            </li>
                            <li>
                                Nos casos em que a obrigação acessória for cumprida antes de qualquer procedimento de ofício, a multa prevista no inciso I do caput será <strong>reduzida à metade</strong>.
                            </li>
                        </ul>
                        Por fim, poderá ser formalizada comunicação ao Ministério Público Federal sempre que houver indícios da ocorrência dos crimes previstos no art. 1º da Lei nº 9.613/1998, que dispõe sobre os crimes de “lavagem” ou ocultação de bens, direitos e valores, sem prejuízo da aplicação de multa.
                        <p class="card-text mb-2">
                        IN 1888 2019 – Links úteis:
                        </p>

                        <cite>
                        http://www.in.gov.br/en/web/dou/-/instru%C3%87%C3%83o-normativa-n%C2%BA-1.888-de-3-de-maio-de-2019-87070039?fbclid=IwAR2SsqXxjnuwd48D6UAUX1HcIquRvJI4wkbnnEFzEvzRD1WwGYNOiR5wNv0
                        </br>
                            https://g1.globo.com/economia/noticia/2019/05/07/operacoes-com-criptomoedas-terao-que-ser-informadas-a-receita.ghtml
                        </cite>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<?php Utils\Layout::append("site/footer") ?>
<?php Utils\Layout::append("site/script") ?>
</body>
</html>