<!DOCTYPE html>
<html lang="pt-br">
<?php Utils\Layout::append("site/head") ?>
<style>
    p {
        margin: 0;
        text-indent: 3ch;
    }
</style>
<body>
<?php Utils\Layout::append("site/header") ?>
<section class="breadcrumb-area bread-bg">
    <div class="overlay"></div>
    <div class="container">
        <div class="breadcrumb-content d-flex flex-wrap align-items-center justify-content-between position-relative">
            <div class="my-2">
                <h2 class="sec-title text-white mb-2">Política de privacidade</h2>
                <p class="text-white">Última revisão: 23 março, 2022</p>
            </div>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb justify-content-center">
                    <li class="breadcrumb-item"><a href="<?php echo URLBASE_CLIENT; ?>">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Política de privacidade</li>
                </ol>
            </nav>
        </div>
    </div>
</section>
<section class="terms-area section--padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <h3 class="card-text mb-3"><strong>POL&Iacute;TICA DE PRIVACIDADE</strong></h3>
                        <p class="card-text mb-2">A <strong>ISIS TRADE</strong> tem o compromisso de proteger e respeitar a privacidade de seus usu&aacute;rios. Por isso estabelece, atrav&eacute;s de sua Pol&iacute;tica de Privacidade, as regras referentes &agrave; coleta, utiliza&ccedil;&atilde;o, prote&ccedil;&atilde;o e divulga&ccedil;&atilde;o de informa&ccedil;&otilde;es pessoais de seus usu&aacute;rios, que acessam e utilizam os servi&ccedil;os oferecidos nos Termos e Condi&ccedil;&otilde;es de Uso, aceitos pelo usu&aacute;rio.</p>
                        <p class="card-text mb-2">Esta Pol&iacute;tica de Privacidade integra os Termos e Condi&ccedil;&otilde;es na forma de anexo.</p>
                        </br>
                        <h5 class="card-text mb-2"><strong>1. DO ACEITE E DAS ALTERA&Ccedil;&Otilde;ES</strong></h5>
                        <p class="card-text mb-2">1.1. Ao aceitar os Termos e Condi&ccedil;&otilde;es, o usu&aacute;rio declara expressamente que leu, entendeu e compreendeu todas as informa&ccedil;&otilde;es l&aacute; dispon&iacute;veis, bem como todos os direitos e obriga&ccedil;&otilde;es determinados na presente Pol&iacute;tica de Privacidade, concordando que se sujeita a todas as disposi&ccedil;&otilde;es do presente instrumento.&nbsp;</p>
                        <p class="card-text mb-2">1.2. A <strong>ISIS TRADE</strong> recomenda a verifica&ccedil;&atilde;o peri&oacute;dica desta Pol&iacute;tica de Privacidade, que poder&aacute; ser alterada a qualquer momento, pois est&aacute; sujeita a constantes melhorias e aprimoramentos.&nbsp;</p>
                        <p class="card-text mb-2">1.3. Todas as altera&ccedil;&otilde;es desta Pol&iacute;tica de Privacidade ser&atilde;o disponibilizadas aos usu&aacute;rios em sua &aacute;rea privada, bem como estar&atilde;o dispon&iacute;veis na p&aacute;gina inicial da plataforma <strong>ISIS TRADE</strong> para todos os interessados e o p&uacute;blico em geral.</p>
                        </br>
                        <h5 class="card-text mb-2"><strong>2. DA COLETA E UTILIZA&Ccedil;&Atilde;O DAS INFORMA&Ccedil;&Otilde;ES</strong></h5>
                        <p class="card-text mb-2">2.1. As informa&ccedil;&otilde;es conhecidas por cada uma das partes deste instrumento somente poder&atilde;o ser utilizadas para os fins dos servi&ccedil;os ora ofertados pela <strong>ISIS TRADE</strong>, sendo estas informa&ccedil;&otilde;es estritamente confidenciais.&nbsp;&nbsp;</p>
                        <p class="card-text mb-2">2.2. As Informa&ccedil;&otilde;es Confidenciais s&atilde;o aquelas indicadas como confidenciais por uma das partes ou que, pelo bom senso, devam ser consideradas confidenciais em vista da natureza das informa&ccedil;&otilde;es, assim especialmente consideradas aquelas em rela&ccedil;&atilde;o aos dados pessoais fornecidos pelo usu&aacute;rio no momento do seu cadastro na plataforma e que ser&atilde;o utilizados para fins da presente Pol&iacute;tica de Privacidade.</p>
                        <p class="card-text mb-2">2.3. Concordam as partes em proteger o sigilo das Informa&ccedil;&otilde;es Confidenciais da outra Parte, da mesma forma como atua na prote&ccedil;&atilde;o do sigilo de suas pr&oacute;prias informa&ccedil;&otilde;es exclusivas e confidenciais do mesmo tipo.</p>
                        <p class="card-text mb-2">2.4. A <strong>ISIS TRADE</strong> coletar&aacute; suas informa&ccedil;&otilde;es pessoas, com o intuito de identificar os usu&aacute;rios, sempre que estes se cadastrarem na plataforma ou fizerem qualquer tipo de contato com a <strong>ISIS TRADE</strong>, para fins de atendimento e utiliza&ccedil;&atilde;o dos servi&ccedil;os.</p>
                        <p class="card-text mb-2">2.5. Os usu&aacute;rios sempre ser&atilde;o informados sobre os dados que ser&atilde;o coletados, ficando a seu exclusivo crit&eacute;rio fornec&ecirc;-los ou n&atilde;o, dando-lhes ci&ecirc;ncia das consequ&ecirc;ncias de cada decis&atilde;o.</p>
                        <p class="card-text mb-2">2.6. Todas as informa&ccedil;&otilde;es coletadas dos usu&aacute;rios e que trafegam pela internet estar&atilde;o sujeitas &agrave; criptografia, a fim de garantir a seguran&ccedil;a dessas informa&ccedil;&otilde;es.</p>
                        <p class="card-text mb-2">2.7. O usu&aacute;rio confirma e garante a veracidade e exatid&atilde;o dos dados pessoais que fornecer &agrave; <strong>ISIS TRADE</strong>, assumindo a responsabilidade caso os mesmos n&atilde;o sejam exatos. Ainda, &eacute; de total responsabilidade dos usu&aacute;rios manter atualizados seus dados cadastrais e pessoais, para os devidos fins de manuten&ccedil;&atilde;o do sistema.</p>
                        <p class="card-text mb-2">2.9. As informa&ccedil;&otilde;es ser&atilde;o utilizadas pela <strong>ISIS TRADE</strong>, para permitir aos usu&aacute;rios abrir sua &ldquo;conta&rdquo; na plataforma e utilizar-se de todos os servi&ccedil;os oferecidos nos Termos e Condi&ccedil;&otilde;es. Tamb&eacute;m, poder&aacute; a <strong>ISIS TRADE</strong> utilizar as informa&ccedil;&otilde;es de seus usu&aacute;rios para implementa&ccedil;&atilde;o de servi&ccedil;os e melhorias identificadas ou solicitadas pelos usu&aacute;rios, al&eacute;m de buscar melhorar a qualidade dos servi&ccedil;os em favor dos usu&aacute;rios e proteger os seus interesses rec&iacute;procos.</p>
                        <p class="card-text mb-2">2.10. A <strong>ISIS TRADE</strong> poder&aacute;, ainda, utilizar as informa&ccedil;&otilde;es de seus usu&aacute;rios para: a) fornecer mais seguran&ccedil;a e confiabilidade aos seus usu&aacute;rios, fornecendo-lhes o suporte solicitado aos servi&ccedil;os; b) resolver disputas e solucionar problemas; c) evitar atividades potencialmente proibidas, ilegais ou de qualquer forma em desacordo com a legisla&ccedil;&atilde;o vigente, conforme as Regras de Compliance estabelecidas pela <strong>ISIS TRADE</strong>; d) fazer cumprir os Termos e Condi&ccedil;&otilde;es; e) fornecer ao usu&aacute;rio uma experi&ecirc;ncia de marketing exclusiva, de acordo com seus usos e expectativas, al&eacute;m de ofertas, promo&ccedil;&otilde;es e atualiza&ccedil;&otilde;es de seus servi&ccedil;o.</p>
                        <p class="card-text mb-2">2.11. Poder&aacute; a <strong>ISIS TRADE</strong>, ainda, utilizar as informa&ccedil;&otilde;es de seus usu&aacute;rios com finalidades espec&iacute;ficas &agrave; promo&ccedil;&atilde;o de Marketing, Estat&iacute;sticas e Comunica&ccedil;&atilde;o entre a plataforma e seus usu&aacute;rios.</p>
                        <p class="card-text mb-2">2.12. As informa&ccedil;&otilde;es coletadas dos usu&aacute;rios s&atilde;o de acesso exclusivo e restrito aos funcion&aacute;rios e pessoas autorizadas para esta finalidade. Aqueles que se utilizarem indevidamente de informa&ccedil;&otilde;es, ferindo esta pol&iacute;tica de privacidade, estar&atilde;o sujeitos &agrave;s penalidades previstas na Lei vigente.</p>
                        <p class="card-text mb-2">2.13. Os dados e informa&ccedil;&otilde;es dos usu&aacute;rios, bem como suas atividades na plataforma, tamb&eacute;m poder&atilde;o ser compartilhados com demais empresas em caso de reorganiza&ccedil;&atilde;o societ&aacute;ria e para atender solicita&ccedil;&otilde;es judiciais, de ag&ecirc;ncias reguladoras e/ou &oacute;rg&atilde;os do governo e para instruir processos investigativos nacionais ou de coopera&ccedil;&atilde;o internacional.</p>
                        </br>
                        <h5 class="card-text mb-2"><strong>3. DA ALTERA&Ccedil;&Atilde;O E EXCLUS&Atilde;O DE INFORMA&Ccedil;&Otilde;ES</strong></h5>
                        <p class="card-text mb-2">3.1. Aos usu&aacute;rios, cumpre a obriga&ccedil;&atilde;o de manter suas informa&ccedil;&otilde;es atualizadas, podendo a qualquer tempo as revisar e alter&aacute;-las, se o caso. No caso de t&eacute;rmino da rela&ccedil;&atilde;o entre as partes, poder&aacute; o usu&aacute;rio solicitar a exclus&atilde;o dos seus dados e informa&ccedil;&otilde;es diretamente &agrave; <strong>ISIS TRADE</strong> que, no prazo de 30 dias, adotar&aacute; as medidas e procedimentos cab&iacute;veis para concretizar o procedimento de exclus&atilde;o.</p>
                        <p class="card-text mb-2">3.2. Inobstante &agrave; exclus&atilde;o dos dados do USU&Aacute;RIO, a <strong>ISIS TRADE</strong> reserva-se ao direito de armazenar os dados das transa&ccedil;&otilde;es, opera&ccedil;&otilde;es e servi&ccedil;os utilizados pelo USU&Aacute;RIO, pelo prazo de 10 (dez) anos, preconizado no art. 205 do C&oacute;digo Civil, como forma de garantir a seguran&ccedil;a empresarial, resguardando direitos e prevenindo responsabilidades futuras em rela&ccedil;&atilde;o &agrave;s suas opera&ccedil;&otilde;es.</p>
                        </br>
                        <h5 class="card-text mb-2"><strong>4. OUTRAS DISPOSI&Ccedil;&Otilde;ES</strong></h5>
                        <p class="card-text mb-2">4.1. A <strong>ISIS TRADE</strong> poder&aacute; ceder os direitos previstos nesta Pol&iacute;tica de Privacidade, no todo ou em parte, independentemente de qualquer aviso ou notifica&ccedil;&atilde;o aos seus usu&aacute;rios, nos casos de altera&ccedil;&otilde;es societ&aacute;rias internas, respeitadas a legisla&ccedil;&atilde;o vigente &agrave; &eacute;poca e as demais normas aplic&aacute;veis aos termos desta Pol&iacute;tica de Privacidade.</p>
                        <p class="card-text mb-2">4.2. A plataforma se reserva no direito de manter informa&ccedil;&otilde;es pelo per&iacute;odo que entender necess&aacute;rio, justificadamente, para o bom cumprimento de seus neg&oacute;cios e atendimento &agrave;s regulamenta&ccedil;&otilde;es vigentes, mesmo ap&oacute;s o encerramento da conta do usu&aacute;rio.</p>
                        <p class="card-text mb-2">4.3. A toler&acirc;ncia das Partes em rela&ccedil;&atilde;o ao descumprimento de qualquer uma das obriga&ccedil;&otilde;es assumidas nesta pol&iacute;tica de privacidade n&atilde;o implicar&aacute;, sob nenhuma hip&oacute;tese, em nova&ccedil;&atilde;o ou ren&uacute;ncia de direito, podendo exigir, a qualquer tempo, o fiel e cabal cumprimento desta Pol&iacute;tica de Privacidade.</p>
                        <p class="card-text mb-2">4.4. A presente pol&iacute;tica de privacidade vincula as Partes e seus sucessores a qualquer t&iacute;tulo.</p>
                        <p class="card-text mb-2">4.5. A inviabilidade da execu&ccedil;&atilde;o ou invalidade, ainda que em virtude de decis&atilde;o judicial, de alguma cl&aacute;usula, n&atilde;o afetar&aacute; a validade das demais cl&aacute;usulas desta pol&iacute;tica de privacidade, que permanecer&aacute; v&aacute;lido e execut&aacute;vel conforme seus termos.</p>
                        <p class="card-text mb-2">4.6. Todas as d&uacute;vidas dos usu&aacute;rios poder&atilde;o ser encaminhadas para o e-mail: suporte@isistrade.com.br e ser&atilde;o respondidas em breve.</p>
                        <p class="card-text mb-2">4.7. As Partes elegem o foro da comarca da cidade de Vinhedo, Estado de S&atilde;o Paulo, para dirimir qualquer controv&eacute;rsia oriunda da presente Pol&iacute;tica de Privacidade, renunciando expressamente a qualquer outro, por mais privilegiado que seja</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<?php Utils\Layout::append("site/footer") ?>
<?php Utils\Layout::append("site/script") ?>
</body>
</html>