<?php

$idioma = new \Utils\PropertiesUtils("book", IDIOMA);
$casasDecimais = (isset($_data["casasDecimais"]) ? $_data["casasDecimais"]  : 2);

$taxaCompra = (isset($_data["compra"]) ? number_format($_data["compra"], $casasDecimais, ".", "")  : 0);
$taxaVenda = (isset($_data["venda"]) ? number_format($_data["venda"], $casasDecimais, ".", "")  : 0 );

$paridade = Modules\principal\Controllers\Principal::getParity();

if (!empty($paridade->casasDecimaisMoedaTrade) && $paridade->casasDecimaisMoedaTrade > 0) {
    $paridade->moedaTrade->casasDecimais = $paridade->casasDecimaisMoedaTrade;
}

$cliente = Utils\Geral::getCliente();

$mostrarBotoes = ($paridade->ativo > 0 && $paridade->statusMercado > 0 && $cliente->statusMercado > 0 && $paridade->moedaBook->statusMercado > 0 && $paridade->moedaBook->ativo > 0);

$mostrarAlerta = false;
$mensagemAlerta = "";

if ($paridade->ativo < 1 || $paridade->moedaBook->ativo < 1) {
    $mostrarAlerta = true;
    $mensagemAlerta = $idioma->getText("mercadoEncerrado");
} else if ($paridade->statusMercado < 1 || $paridade->moedaBook->statusMercado < 1) {
    $mostrarAlerta = true;
    $mensagemAlerta = $idioma->getText("mercadoSupenso");
} else if ($cliente->statusMercado < 1) {
    $mensagemAlerta = $idioma->getText("compraVendaSuspensaConta");
    $mostrarAlerta = true;
}

$_data["idiomaMenu"] = $idioma;
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="<?php echo BOOK; ?>bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="<?php echo BOOK; ?>css/icons.css">
    <link rel="stylesheet" href="<?php echo BOOK; ?>css/ui.css">
    <link rel="stylesheet" href="<?php echo BOOK; ?>css/style.css">
</head>



<body id="theme" class="crypt-light">
<header>
    <div class="container-full-width">
        <div class="crypt-header">
            <div class="row">
                <div class="col-xl-4 col-lg-4 col-md-4 col-sm-5">
                    <div class="row">
                        <div class="col-xs-2">
                            <div class="crypt-logo"><img src="" alt=""></div>
                        </div>
                        <div class="col-xs-2">

                        </div>
                    </div>
                </div>

                <div class="col-xl-8 col-lg-8 col-md-8 d-none d-md-block d-lg-block">
                    <ul class="crypt-heading-menu fright">



                        <li><button id="theme-switcher">Temas!</button></li>


                    </ul>
                </div><i class="menu-toggle pe-7s-menu d-xs-block d-sm-block d-md-none d-sm-none"></i></div>
        </div>
    </div>
    <div class="crypt-mobile-menu">
        <ul class="crypt-heading-menu">
            <li class="active"><a href="">Exchange</a></li>
            <li><a href="">Market Cap</a></li>
            <li><a href="">Treanding</a></li>
            <li><a href="">Tools</a></li>
            <li class="crypt-box-menu menu-red"><a href="">register</a></li>
            <li class="crypt-box-menu menu-green"><a href="">login</a></li>
        </ul>
        <div class="crypt-gross-market-cap">
            <h5>$34.795.90 <span class="crypt-up pl-2">+3.435 %</span></h5>
            <h6>0.7925.90 BTC <span class="crypt-down pl-2">+7.435 %</span></h6></div>
    </div>
</header>
<div class="container-fluid">
    <div class="row sm-gutters ">
        <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-3 col-xxl-2">
            <div class="crypt-market-status mt-4">
                <div>
                    <ul class="nav nav-tabs" id="crypt-tab">
                        <li role="presentation"><a href="#usd" class="active" data-toggle="tab">usdt</a></li>
                        <li role="presentation"><a href="#btc" data-toggle="tab">btc</a></li>
                        <li role="presentation"><a href="#eth" data-toggle="tab">eth</a></li>
                    </ul>
                    <div class="tab-content crypt-tab-content">
                        <div role="tabpanel" class="tab-pane active mb-4" id="usd">
                            <table class="table table-striped">
                                <thead>
                                <tr>
                                    <th scope="col">Coin</th>
                                    <th scope="text-center">Last Price</th>
                                    <th class="text-right">Change</th>
                                </tr>
                                </thead>
                                <tbody class="crypt-table-hover">
                                <tr>
                                    <td class="align-middle">
                                        <img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> BTC/USDT</td>
                                    <td class="crypt-down">
                                        <span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.00004356</span>
                                    </td>
                                    <td class="text-right">
                                        <b class="crypt-down">-5.4%</b>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> LTC/USDT</td>
                                    <td class="crypt-down align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.00005640</span></td>
                                    <td class="text-right"><b class="crypt-up">+6.7%</b> </td>
                                </tr>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> ETH/USDT</td>
                                    <td class="crypt-down align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.00002340</span></td>
                                    <td class="text-right"><b class="crypt-down">-7.7%</b> </td>
                                </tr>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> DOGE/USDT</td>
                                    <td class="crypt-up align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.00003644</span></td>
                                    <td class="text-right"><b class="crypt-up">+3.7%</b> </td>
                                </tr>

                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> ERC20/USDT</td>
                                    <td class="align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.000344</span></td>
                                    <td class="text-right"> <span class="crypt-up"><b>+3.7%</b></span> </td>
                                </tr>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> RIF/USDT</td>
                                    <td class="align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.000344</span></td>
                                    <td class="text-right"><span class="crypt-up"><b>+3.7%</b></span> </td>
                                </tr>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> BTC/USDT</td>
                                    <td class="crypt-down align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.00004356</span></td>
                                    <td class="text-right"><b class="crypt-down">-5.4%</b> </td>
                                </tr>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> LTC/USDT</td>
                                    <td class="crypt-down align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.00005640</span></td>
                                    <td class="text-right"><b class="crypt-up">+6.7%</b> </td>
                                </tr>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> ETH/USDT</td>
                                    <td class="crypt-down align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.00002340</span></td>
                                    <td class="text-right"><b class="crypt-down">-7.7%</b> </td>
                                </tr>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> DOGE/USDT</td>
                                    <td class="crypt-up align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.00003644</span></td>
                                    <td class="text-right"><b class="crypt-up">+3.7%</b> </td>
                                </tr>

                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> ERC20/USDT</td>
                                    <td class="align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.000344</span></td>
                                    <td class="text-right"> <span class="crypt-up"><b>+3.7%</b></span> </td>
                                </tr>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> RIF/USDT</td>
                                    <td class="align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.000344</span></td>
                                    <td class="text-right"><span class="crypt-up"><b>+3.7%</b></span> </td>
                                </tr>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> BTC/USDT</td>
                                    <td class="crypt-down align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.00004356</span></td>
                                    <td class="text-right"><b class="crypt-down">-5.4%</b> </td>
                                </tr>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> LTC/USDT</td>
                                    <td class="crypt-down align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.00005640</span></td>
                                    <td class="text-right"><b class="crypt-up">+6.7%</b> </td>
                                </tr>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> ETH/USDT</td>
                                    <td class="crypt-down align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.00002340</span></td>
                                    <td class="text-right"><b class="crypt-down">-7.7%</b> </td>
                                </tr>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> DOGE/USDT</td>
                                    <td class="crypt-up align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.00003644</span></td>
                                    <td class="text-right"><b class="crypt-up">+3.7%</b> </td>
                                </tr>

                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> ERC20/USDT</td>
                                    <td class="align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.000344</span></td>
                                    <td class="text-right"> <span class="crypt-up"><b>+3.7%</b></span> </td>
                                </tr>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> RIF/USDT</td>
                                    <td class="align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.000344</span></td>
                                    <td class="text-right"><span class="crypt-up"><b>+3.7%</b></span> </td>
                                </tr>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> BTC/USDT</td>
                                    <td class="crypt-down align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.00004356</span></td>
                                    <td class="text-right"><b class="crypt-down">-5.4%</b> </td>
                                </tr>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> LTC/USDT</td>
                                    <td class="crypt-down align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.00005640</span></td>
                                    <td class="text-right"><b class="crypt-up">+6.7%</b> </td>
                                </tr>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> ETH/USDT</td>
                                    <td class="crypt-down align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.00002340</span></td>
                                    <td class="text-right"><b class="crypt-down">-7.7%</b> </td>
                                </tr>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> DOGE/USDT</td>
                                    <td class="crypt-up align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.00003644</span></td>
                                    <td class="text-right"><b class="crypt-up">+3.7%</b> </td>
                                </tr>

                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> ERC20/USDT</td>
                                    <td class="align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.000344</span></td>
                                    <td class="text-right"> <span class="crypt-up"><b>+3.7%</b></span> </td>
                                </tr>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> RIF/USDT</td>
                                    <td class="align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.000344</span></td>
                                    <td class="text-right"><span class="crypt-up"><b>+3.7%</b></span> </td>
                                </tr>


                                </tbody>
                            </table>
                        </div>
                        <div role="tabpanel" class="tab-pane" id="btc">
                            <table class="table table-striped">
                                <thead>
                                <tr>
                                    <th scope="col">Coin</th>
                                    <th scope="col">Last Price</th>
                                    <th scope="col">Change</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> ETH/BTC</td>
                                    <td class="align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.0000234</span></td>
                                    <td> <span class="d-block">6.6768876</span> <b class="crypt-down">-7.7%</b> </td>
                                </tr>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> EOS/BTC</td>
                                    <td class="crypt-down align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.000056</span></td>
                                    <td> <span class="d-block">5.3424984</span> <b class="crypt-down">-5.4%</b> </td>
                                </tr>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> LTC/BTC</td>
                                    <td class="align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.0000564</span></td>
                                    <td> <span class="d-block">6.6768876</span> <span>6.7%</span> </td>
                                </tr>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> DOGE/BTC</td>
                                    <td class="align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.000344</span></td>
                                    <td> <span class="d-block">6.6768876</span> <b class="crypt-up">+3.7%</b> </td>
                                </tr>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> XMR/BTC</td>
                                    <td class="align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.000344</span></td>
                                    <td> <span class="d-block">6.6768876</span> <span>3.7%</span> </td>
                                </tr>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> LINK/BTC</td>
                                    <td class="align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.000344</span></td>
                                    <td> <span class="d-block">6.6768876</span> <span class="crypt-up"><b>+3.7%</b></span> </td>
                                </tr>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> FTN/BTC</td>
                                    <td class="align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.000344</span></td>
                                    <td> <span class="d-block">6.6768876</span> <span class="crypt-up"><b>+3.7%</b></span> </td>
                                </tr>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> RIF/BTC</td>
                                    <td class="align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.000344</span></td>
                                    <td> <span class="d-block">6.6768876</span> <span class="crypt-up"><b>+3.7%</b></span> </td>
                                </tr>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> NEO/BTC</td>
                                    <td class="align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.56723</span></td>
                                    <td> <span class="d-block">9.34546</span> <span>6.7%</span> </td>
                                </tr>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> TRX/BTC</td>
                                    <td class="align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.56723</span></td>
                                    <td> <span class="d-block">9.34546</span> <span>6.7%</span> </td>
                                </tr>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> LSK/BTC</td>
                                    <td class="align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.56723</span></td>
                                    <td> <span class="d-block">9.34546</span> <span>6.7%</span> </td>
                                </tr>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> XRP/BTC</td>
                                    <td class="align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.000344</span></td>
                                    <td> <span class="d-block">6.6768876</span> <span class="crypt-up"><b>+3.7%</b></span> </td>
                                </tr>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> CNB/BTC</td>
                                    <td class="align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.56723</span></td>
                                    <td> <span class="d-block">9.34546</span> <span>6.7%</span> </td>
                                </tr>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> VEN/BTC</td>
                                    <td class="align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.56723</span></td>
                                    <td> <span class="d-block">9.34546</span> <span>6.7%</span> </td>
                                </tr>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> DASH/BTC</td>
                                    <td class="align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.56723</span></td>
                                    <td> <span class="d-block">9.34546</span> <span>6.7%</span> </td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                        <div role="tabpanel" class="tab-pane" id="eth">
                            <table class="table table-striped">
                                <thead>
                                <tr>
                                    <th scope="col">Coin</th>
                                    <th scope="col">Last Price</th>
                                    <th scope="col">Change</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> BTC/ETH</td>
                                    <td class="crypt-down align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.000056</span></td>
                                    <td> <span class="d-block">5.3424984</span> <b class="crypt-down">-5.4%</b> </td>
                                </tr>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> LTC/ETH</td>
                                    <td class="align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.0000564</span></td>
                                    <td> <span class="d-block">6.6768876</span> <span>6.7%</span> </td>
                                </tr>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> ERC20/ETH</td>
                                    <td class="align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.0000234</span></td>
                                    <td> <span class="d-block">6.6768876</span> <b class="crypt-down">-7.7%</b> </td>
                                </tr>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> DOGE/ETH</td>
                                    <td class="align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.000344</span></td>
                                    <td> <span class="d-block">6.6768876</span> <b class="crypt-up">+3.7%</b> </td>
                                </tr>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> XMR/ETH</td>
                                    <td class="align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.000344</span></td>
                                    <td> <span class="d-block">6.6768876</span> <span>3.7%</span> </td>
                                </tr>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> HMB/ETH</td>
                                    <td class="align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.000344</span></td>
                                    <td> <span class="d-block">6.6768876</span> <span class="crypt-up"><b>+3.7%</b></span> </td>
                                </tr>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> FTN/ETH</td>
                                    <td class="align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.000344</span></td>
                                    <td> <span class="d-block">6.6768876</span> <span class="crypt-up"><b>+3.7%</b></span> </td>
                                </tr>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> MGC/ETH</td>
                                    <td class="align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.000344</span></td>
                                    <td> <span class="d-block">6.6768876</span> <span class="crypt-up"><b>+3.7%</b></span> </td>
                                </tr>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> IOTE/ETH</td>
                                    <td class="align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.56723</span></td>
                                    <td> <span class="d-block">9.34546</span> <span>6.7%</span> </td>
                                </tr>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> YTA/ETH</td>
                                    <td class="align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.56723</span></td>
                                    <td> <span class="d-block">9.34546</span> <span>6.7%</span> </td>
                                </tr>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> PQR/ETH</td>
                                    <td class="align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.56723</span></td>
                                    <td> <span class="d-block">9.34546</span> <span>6.7%</span> </td>
                                </tr>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> PAX/ETH</td>
                                    <td class="align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.000344</span></td>
                                    <td> <span class="d-block">6.6768876</span> <span class="crypt-up"><b>+3.7%</b></span> </td>
                                </tr>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> VBT/ETH</td>
                                    <td class="align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.56723</span></td>
                                    <td> <span class="d-block">9.34546</span> <span>6.7%</span> </td>
                                </tr>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> CCE/ETH</td>
                                    <td class="align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.56723</span></td>
                                    <td> <span class="d-block">9.34546</span> <span>6.7%</span> </td>
                                </tr>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> QTUM/ETH</td>
                                    <td class="align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.56723</span></td>
                                    <td> <span class="d-block">9.34546</span> <span>6.7%</span> </td>
                                </tr>
                                <tr>
                                    <td class="align-middle"><img class="crypt-star pr-1" alt="star" src="<?php echo BOOK; ?>images/star.svg" width="15"> BOA/ETH</td>
                                    <td class="align-middle"><span class="pr-2" data-toggle="tooltip" data-placement="right" title="$ 0.05">0.56723</span></td>
                                    <td> <span class="d-block">9.34546</span> <span>6.7%</span> </td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-lg-6 col-xl-6 col-xxl-8">
            <div class="crypt-gross-market-cap mt-4">
                <div class="row">
                    <div class="col-3 col-sm-6 col-md-6 col-lg-6">
                        <div class="row">
                            <div class="col-sm-6 col-md-6 col-lg-6">
                                <p>84568.85</p>
                                <p>≈$8378.6850 USDT</p>
                            </div>
                            <div class="col-sm-6 col-md-6 col-lg-6">
                                <p>24H Change</p>
                                <p class="crypt-down">-0.0234230 -3.35%</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-3 col-sm-2 col-md-3 col-lg-2">
                        <p>24H High</p>
                        <p class="crypt-up">0.435453</p>
                    </div>
                    <div class="col-3 col-sm-2 col-md-3 col-lg-2">
                        <p>24H Low</p>
                        <p class="crypt-down">0.09945</p>
                    </div>
                    <div class="col-3 col-sm-2 col-md-3 col-lg-2">
                        <p>24H Volume</p>
                        <p>12.33445</p>
                    </div>
                </div>
            </div>
            <div class="tradingview-widget-container">
                <div id="crypt-candle-chart">
                    <iframe style="border: none;" seamless="seamless" src="<?php echo DIR_TV ?>/index.html?lang=<?php echo $idioma->getLang()?>&symbol=<?php echo $paridade->symbol ?>" width="100%" height="290px"></iframe>
                </div>



                <div class="crypt-boxed-area">

                    <div class="row no-gutters">
                        <div class="col-md-6">
                            <div class="crypt-buy-sell-form">
                                <p>Buy <span class="crypt-up">BTC</span> <span class="fright">Available: <b class="crypt-up">0.00 BTC</b></span></p>
                                <div class="crypt-buy">
                                    <div class="input-group mb-1">
                                        <div class="input-group-prepend"> <span class="input-group-text">Price</span> </div>
                                        <input type="text" class="form-control" placeholder="0.02323476" readonly>
                                        <div class="input-group-append"> <span class="input-group-text">USDT</span> </div>
                                    </div>
                                    <div class="input-group mb-1">
                                        <div class="input-group-prepend"> <span class="input-group-text">Amount</span> </div>
                                        <input type="number" class="form-control">
                                        <div class="input-group-append"> <span class="input-group-text">BTC</span> </div>
                                    </div>
                                    <div class="input-group mb-1">
                                        <div class="input-group-prepend"> <span class="input-group-text">Total</span> </div>
                                        <input type="text" class="form-control" readonly>
                                        <div class="input-group-append"> <span class="input-group-text">BTC</span> </div>
                                    </div>
                                    <div>
                                        <p>Fee: <span class="fright">100%x0.2=0.02</span></p>
                                    </div>
                                    <div class="text-center mt-1 mb-1 crypt-up">
                                        <p style="margin-bottom: 0.6rem !important;">You will approximately pay</p>
                                        <h4>0.09834 BTC</h4></div>
                                    <div class="menu-green"><a href="" class="crypt-button-green-full">Buy</a></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="crypt-buy-sell-form">
                                <p>Sell <span class="crypt-down">BTC</span> <span class="fright">Available: <b class="crypt-down">0.00 BTC</b></span></p>
                                <div class="crypt-sell">
                                    <div class="input-group mb-1">
                                        <div class="input-group-prepend"> <span class="input-group-text">Price</span> </div>
                                        <input type="text" class="form-control" placeholder="0.02323476" readonly>
                                        <div class="input-group-append"> <span class="input-group-text">USDT</span> </div>
                                    </div>
                                    <div class="input-group mb-1">
                                        <div class="input-group-prepend"> <span class="input-group-text">Amount</span> </div>
                                        <input type="number" class="form-control">
                                        <div class="input-group-append"> <span class="input-group-text">BTC</span> </div>
                                    </div>
                                    <div class="input-group mb-1">
                                        <div class="input-group-prepend"> <span class="input-group-text">Total</span> </div>
                                        <input type="text" class="form-control" readonly>
                                        <div class="input-group-append"> <span class="input-group-text">BTC</span> </div>
                                    </div>
                                    <div>
                                        <p style="margin-bottom: 0.6rem !important;">Fee: <span class="fright">100%x0.2=0.02</span></p>
                                    </div>
                                    <div class="text-center mt-1 mb-1 crypt-down">
                                        <p>You will approximately pay</p>
                                        <h4>0.09834 BTC</h4></div>
                                    <div class=" menu-green"><a href="" class="crypt-button-red-full">Sell</a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-lg-6 col-xl-3 col-xxl-2">
            <div class="crypt-market-status mt-4">
                <div>
                    <ul class="nav nav-tabs">
                        <li role="presentation"><a href="#history" class="active" data-toggle="tab">Order Book</a></li>
                        <li role="presentation"><a href="#market-trading" data-toggle="tab">market trading</a></li>
                    </ul>
                    <div class="tab-content">
                        <div role="tabpanel" class="tab-pane active" id="history">
                            <table class="table table-striped" style="margin-bottom: 0 !important;">
                                <thead>
                                <tr>
                                    <th scope="col">Price</th>
                                    <th class="text-right" scope="col">Quantity</th>
                                    <th class="text-right" scope="col">Total</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td class="crypt-down">6590.08</td>
                                    <td class="text-right">0.0000234</td>
                                    <td class="text-right">4.3456600</td>
                                </tr>
                                <tr>
                                    <td class="crypt-down">6590.08</td>
                                    <td class="text-right">0.0000234</td>
                                    <td class="text-right">4.3456600</td>
                                </tr>
                                <tr>
                                    <td class="crypt-down">6590.08</td>
                                    <td class="text-right">0.0000234</td>
                                    <td class="text-right">4.3456600</td>
                                </tr>
                                <tr>
                                    <td class="crypt-down">6590.08</td>
                                    <td class="text-right">0.0000234</td>
                                    <td class="text-right">4.3456600</td>
                                </tr>
                                <tr>
                                    <td class="crypt-down">6590.08</td>
                                    <td class="text-right">0.0000234</td>
                                    <td class="text-right">4.3456600</td>
                                </tr><tr>
                                    <td class="crypt-down">6590.08</td>
                                    <td class="text-right">0.0000234</td>
                                    <td class="text-right">4.3456600</td>
                                </tr><tr>
                                    <td class="crypt-down">6590.08</td>
                                    <td class="text-right">0.0000234</td>
                                    <td class="text-right">4.3456600</td>
                                </tr>
                                <tr>
                                    <td class="crypt-down">6590.08</td>
                                    <td class="text-right">0.0000234</td>
                                    <td class="text-right">4.3456600</td>
                                </tr>
                                <tr>
                                    <td class="crypt-down">6590.08</td>
                                    <td class="text-right">0.0000234</td>
                                    <td class="text-right">4.3456600</td>
                                </tr>
                                <tr>
                                    <td class="crypt-down">6590.08</td>
                                    <td class="text-right">0.0000234</td>
                                    <td class="text-right">4.3456600</td>
                                </tr>
                                <tr>
                                    <td class="crypt-down">6590.08</td>
                                    <td class="text-right">0.0000234</td>
                                    <td class="text-right">4.3456600</td>
                                </tr>
                                <tr>
                                    <td class="crypt-down">6590.08</td>
                                    <td class="text-right">0.0000234</td>
                                    <td class="text-right">4.3456600</td>
                                </tr>
                                </tbody>
                            </table>
                            <h6 class="text-center">29384798 <span>938475</span></h6>
                            <table class="table table-striped">
                                <tbody>
                                <tr>
                                    <td class="crypt-up">4300.67</td>
                                    <td class="text-right">0.0000567</td>
                                    <td class="text-right">4.3456600</td>
                                </tr>
                                <tr>
                                    <td class="crypt-up">9510.56</td>
                                    <td class="text-right">0.0000564</td>
                                    <td class="text-right">6.6768876</td>
                                </tr>
                                <tr>
                                    <td class="crypt-up">9080.67</td>
                                    <td class="text-right">0.000056</td>
                                    <td class="text-right">5.3424984</td>
                                </tr>
                                <tr>
                                    <td class="crypt-up">2346.64</td>
                                    <td class="text-right">0.0000564</td>
                                    <td class="text-right">6.6768876</td>
                                </tr>
                                <tr>
                                    <td class="crypt-up">5478.87</td>
                                    <td class="text-right">0.0000234</td>
                                    <td class="text-right">4.3456600</td>
                                </tr>
                                <tr>
                                    <td class="crypt-up">5689.78</td>
                                    <td class="text-right">0.0000234</td>
                                    <td class="text-right">4.3456600</td>
                                </tr>
                                <tr>
                                    <td class="crypt-up">4518.56</td>
                                    <td class="text-right">0.0000567</td>
                                    <td class="text-right">4.3456600</td>
                                </tr>
                                <tr>
                                    <td class="crypt-up">6900.67</td>
                                    <td class="text-right">0.0000234</td>
                                    <td class="text-right">4.3456600</td>
                                </tr>
                                <tr>
                                    <td class="crypt-up">6898.56</td>
                                    <td class="text-right">0.0000567</td>
                                    <td class="text-right">4.3456600</td>
                                </tr>
                                <tr>
                                    <td class="crypt-up">7894.34</td>
                                    <td class="text-right">0.0000564</td>
                                    <td class="text-right">6.6768876</td>
                                </tr>
                                <tr>
                                    <td class="crypt-up">8765.90</td>
                                    <td class="text-right">0.0000234</td>
                                    <td class="text-right">4.3456600</td>
                                </tr>
                                <tr>
                                    <td class="crypt-up">5674.76</td>
                                    <td class="text-right">0.0000234</td>
                                    <td class="text-right">4.3456600</td>
                                </tr>
                                <tr>
                                    <td class="crypt-up">3452.09</td>
                                    <td class="text-right">0.0000567</td>
                                    <td class="text-right">4.3456600</td>
                                </tr>
                                <tr>
                                    <td class="crypt-up">7689.65</td>
                                    <td class="text-right">0.0000234</td>
                                    <td class="text-right">4.3456600</td>
                                </tr>
                                <tr>
                                    <td class="crypt-up">3468.34</td>
                                    <td class="text-right">0.0000567</td>
                                    <td class="text-right">4.3456600</td>
                                </tr>
                                <tr>
                                    <td class="crypt-up">8794.12</td>
                                    <td class="text-right">0.0000564</td>
                                    <td class="text-right">6.6768876</td>
                                </tr>
                                <tr>
                                    <td class="crypt-up">2315.86</td>
                                    <td class="text-right">0.0000234</td>
                                    <td class="text-right">4.3456600</td>
                                </tr>
                                <tr>
                                    <td class="crypt-up">463.98</td>
                                    <td class="text-right">0.0000234</td>
                                    <td class="text-right">4.3456600</td>
                                </tr>
                                <tr>
                                    <td class="crypt-up">673.67</td>
                                    <td class="text-right">0.0000567</td>
                                    <td class="text-right">4.3456600</td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                        <div role="tabpanel" class="tab-pane" id="market-trading">
                            <table class="table table-striped">
                                <thead>
                                <tr>
                                    <th scope="col">Time</th>
                                    <th class="text-right">Amount</th>
                                    <th class="text-right">Volume</th>
                                </tr>
                                </thead>
                                <tbody >
                                <tr>
                                    <td class="text-left">22:35:59</td>
                                    <td class="text-right">0.0000564</td>
                                    <td class="text-right">6.6768876</td>
                                </tr>
                                <tr>
                                    <td class="text-left">22:35:59</td>
                                    <td class="text-right">0.0000564</td>
                                    <td class="text-right">6.6768876</td>
                                </tr>
                                <tr>
                                    <td class="text-left">22:35:59</td>
                                    <td class="text-right">0.0000564</td>
                                    <td class="text-right">6.6768876</td>
                                </tr>
                                <tr>
                                    <td class="text-left">22:35:59</td>
                                    <td class="text-right">0.0000564</td>
                                    <td class="text-right">6.6768876</td>
                                </tr>
                                <tr>
                                    <td class="text-left">22:35:59</td>
                                    <td class="text-right">0.0000564</td>
                                    <td class="text-right">6.6768876</td>
                                </tr>
                                <tr>
                                    <td class="text-left">22:35:59</td>
                                    <td class="text-right">0.0000564</td>
                                    <td class="text-right">6.6768876</td>
                                </tr>
                                <tr>
                                    <td class="text-left">22:35:59</td>
                                    <td class="text-right">0.0000564</td>
                                    <td class="text-right">6.6768876</td>
                                </tr>
                                <tr>
                                    <td class="text-left">22:35:59</td>
                                    <td class="text-right">0.0000564</td>
                                    <td class="text-right">6.6768876</td>
                                </tr>
                                <tr>
                                    <td class="text-left">22:35:59</td>
                                    <td class="text-right">0.0000564</td>
                                    <td class="text-right">6.6768876</td>
                                </tr>
                                <tr>
                                    <td class="text-left">22:35:59</td>
                                    <td class="text-right">0.0000564</td>
                                    <td class="text-right">6.6768876</td>
                                </tr>
                                <tr>
                                    <td class="text-left">22:35:59</td>
                                    <td class="text-right">0.0000564</td>
                                    <td class="text-right">6.6768876</td>
                                </tr>
                                <tr>
                                    <td class="text-left">22:35:59</td>
                                    <td class="text-right">0.0000564</td>
                                    <td class="text-right">6.6768876</td>
                                </tr>
                                <tr>
                                    <td class="text-left">22:35:59</td>
                                    <td class="text-right">0.0000564</td>
                                    <td class="text-right">6.6768876</td>
                                </tr>
                                <tr>
                                    <td class="text-left">22:35:59</td>
                                    <td class="text-right">0.0000564</td>
                                    <td class="text-right">6.6768876</td>
                                </tr>
                                <tr>
                                    <td class="text-left">22:35:59</td>
                                    <td class="text-right">0.0000564</td>
                                    <td class="text-right">6.6768876</td>
                                </tr>
                                <tr>
                                    <td class="text-left">22:35:59</td>
                                    <td class="text-right">0.0000564</td>
                                    <td class="text-right">6.6768876</td>
                                </tr>
                                <tr>
                                    <td class="text-left">22:35:59</td>
                                    <td class="text-right">0.0000564</td>
                                    <td class="text-right">6.6768876</td>
                                </tr>
                                <tr>
                                    <td class="text-left">22:35:59</td>
                                    <td class="text-right">0.0000564</td>
                                    <td class="text-right">6.6768876</td>
                                </tr>
                                <tr>
                                    <td class="text-left">22:35:59</td>
                                    <td class="text-right">0.0000564</td>
                                    <td class="text-right">6.6768876</td>
                                </tr>
                                <tr>
                                    <td class="text-left">22:35:59</td>
                                    <td class="text-right">0.0000564</td>
                                    <td class="text-right">6.6768876</td>
                                </tr>
                                <tr>
                                    <td class="text-left">22:35:59</td>
                                    <td class="text-right">0.0000564</td>
                                    <td class="text-right">6.6768876</td>
                                </tr>
                                <tr>
                                    <td class="text-left">22:35:59</td>
                                    <td class="text-right">0.0000564</td>
                                    <td class="text-right">6.6768876</td>
                                </tr>
                                <tr>
                                    <td class="text-left">22:35:59</td>
                                    <td class="text-right">0.0000564</td>
                                    <td class="text-right">6.6768876</td>
                                </tr>
                                <tr>
                                    <td class="text-left">22:35:59</td>
                                    <td class="text-right">0.0000564</td>
                                    <td class="text-right">6.6768876</td>
                                </tr>
                                <tr>
                                    <td class="text-left">22:35:59</td>
                                    <td class="text-right">0.0000564</td>
                                    <td class="text-right">6.6768876</td>
                                </tr>
                                <tr>
                                    <td class="text-left">22:35:59</td>
                                    <td class="text-right">0.0000564</td>
                                    <td class="text-right">6.6768876</td>
                                </tr>
                                <tr>
                                    <td class="text-left">22:35:59</td>
                                    <td class="text-right">0.0000564</td>
                                    <td class="text-right">6.6768876</td>
                                </tr>
                                <tr>
                                    <td class="text-left">22:35:59</td>
                                    <td class="text-right">0.0000564</td>
                                    <td class="text-right">6.6768876</td>
                                </tr>
                                <tr>
                                    <td class="text-left">22:35:59</td>
                                    <td class="text-right">0.0000564</td>
                                    <td class="text-right">6.6768876</td>
                                </tr>
                                <tr>
                                    <td class="text-left">22:35:59</td>
                                    <td class="text-right">0.0000564</td>
                                    <td class="text-right">6.6768876</td>
                                </tr>
                                <tr>
                                    <td class="text-left">22:35:59</td>
                                    <td class="text-right">0.0000564</td>
                                    <td class="text-right">6.6768876</td>
                                </tr>
                                <tr>
                                    <td class="text-left">22:35:59</td>
                                    <td class="text-right">0.0000564</td>
                                    <td class="text-right">6.6768876</td>
                                </tr>

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row sm-gutters">
        <div class="col-xl-5">

        </div>
        <div class="col-xl-12">
            <div>
                <div class="crypt-market-status">
                    <div>
                        <ul class="nav nav-tabs">
                            <li role="presentation"><a href="#active-orders" class="active" data-toggle="tab">Active Orders</a></li>
                            <li role="presentation"><a href="#closed-orders" data-toggle="tab">Closed Orders</a></li>
                            <li role="presentation"><a href="#balance" data-toggle="tab">Balance</a></li>
                        </ul>
                        <div class="tab-content">
                            <div role="tabpanel" class="tab-pane active" id="active-orders">
                                <table class="table table-striped">
                                    <thead>
                                    <tr>
                                        <th scope="col">Moeda</th>
                                        <th scope="col">Movimento</th>
                                        <th scope="col">Data</th>
                                        <th scope="col">Cotação</th>
                                        <th scope="col">Volume</th>
                                        <th scope="col">Valor Total</th>
                                        <th scope="col">Pendente</th>
                                        <th scope="col">Status</th>
                                        <th scope="col">Ação</th>
                                    </tr>
                                    </thead>
                                </table>
                                <div class="no-orders text-center p-160"><img src="<?php echo BOOK; ?>images/empty.svg" alt="no-orders"></div>
                            </div>
                            <div role="tabpanel" class="tab-pane" id="closed-orders">
                                <table class="table table-striped">
                                    <thead>
                                    <tr>
                                        <th scope="col">Moeda</th>
                                        <th scope="col">Movimento</th>
                                        <th scope="col">Data</th>
                                        <th scope="col">Cotação</th>
                                        <th scope="col">Volume</th>
                                        <th scope="col">Valor Total</th>
                                        <th scope="col">Pendente</th>
                                        <th scope="col">Status</th>
                                        <th scope="col">Ação</th>
                                    </tr>
                                    </thead>
                                    <tbody class="closed-orders">
                                    <tr>
                                        <th>22:35:59</th>
                                        <td class="crypt-up">Buy</td>
                                        <td class="crypt-up">0.000056</td>
                                        <td class="crypt-up">0.000056</td>
                                        <td class="crypt-up">0.0003456</td>
                                        <td>5.3424984</td>
                                    </tr>
                                    <tr>
                                        <th>22:35:59</th>
                                        <td class="crypt-down">Sell</td>
                                        <td class="crypt-down">0.000056</td>
                                        <td class="crypt-down">0.000056</td>
                                        <td class="crypt-down">0.0003456</td>
                                        <td>5.3424984</td>
                                    </tr>
                                    <tr>
                                        <th>22:35:59</th>
                                        <td class="crypt-up">Buy</td>
                                        <td class="crypt-up">0.000056</td>
                                        <td class="crypt-up">0.000056</td>
                                        <td class="crypt-up">0.0003456</td>
                                        <td>5.3424984</td>
                                    </tr>
                                    <tr>
                                        <th>22:35:59</th>
                                        <td class="crypt-down">Sell</td>
                                        <td class="crypt-down">0.000056</td>
                                        <td class="crypt-down">0.000056</td>
                                        <td class="crypt-down">0.0003456</td>
                                        <td>5.3424984</td>
                                    </tr>
                                    <tr>
                                        <th>22:35:59</th>
                                        <td class="crypt-up">Buy</td>
                                        <td class="crypt-up">0.000056</td>
                                        <td class="crypt-up">0.000056</td>
                                        <td class="crypt-up">0.0003456</td>
                                        <td>5.3424984</td>
                                    </tr>
                                    <tr>
                                        <th>22:35:59</th>
                                        <td class="crypt-down">Sell</td>
                                        <td class="crypt-down">0.000056</td>
                                        <td class="crypt-down">0.000056</td>
                                        <td class="crypt-down">0.0003456</td>
                                        <td>5.3424984</td>
                                    </tr>
                                    <tr>
                                        <th>22:35:59</th>
                                        <td class="crypt-up">Buy</td>
                                        <td class="crypt-up">0.000056</td>
                                        <td class="crypt-up">0.000056</td>
                                        <td class="crypt-up">0.0003456</td>
                                        <td>5.3424984</td>
                                    </tr>
                                    <tr>
                                        <th>22:35:59</th>
                                        <td class="crypt-down">Sell</td>
                                        <td class="crypt-down">0.000056</td>
                                        <td class="crypt-down">0.000056</td>
                                        <td class="crypt-down">0.0003456</td>
                                        <td>5.3424984</td>
                                    </tr>
                                    <tr>
                                        <th>22:35:59</th>
                                        <td class="crypt-up">Buy</td>
                                        <td class="crypt-up">0.000056</td>
                                        <td class="crypt-up">0.000056</td>
                                        <td class="crypt-up">0.0003456</td>
                                        <td>5.3424984</td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                            <div role="tabpanel" class="tab-pane" id="balance">
                                <table class="table table-striped ">
                                    <thead>
                                    <tr>
                                        <th width="30px"></th>
                                        <th class="text-left">Moeda</th>
                                        <th class="text-center">Em Ordem</th>
                                        <th class="text-right">Disponivel</th>
                                        <th class="text-right">Total</th>
                                    </tr>
                                    </thead>
                                    <tbody class="balance">
                                    <tr>
                                        <th width="30px"></th>
                                        <th>BTC</th>
                                        <td class="text-center">0.0000564</td>
                                        <td class="text-right">6.6768876</td>
                                        <td class="text-right">6.6768876</td>
                                    </tr>
                                    <tr>
                                        <th width="30px"></th>

                                        <th>ETC</th>
                                        <td class="text-center">0.000056</td>
                                        <td class="text-right">5.3424984</td>
                                        <td class="text-right">6.6768876</td>
                                    </tr>
                                    <tr>
                                        <th width="30px"></th>
                                        <th>LTC</th>
                                        <td class="text-center">0.0000234</td>
                                        <td class="text-right">4.3456600</td>
                                        <td class="text-right">6.6768876</td>
                                    </tr>
                                    <tr>
                                        <th width="30px"></th>
                                        <th>XMR</th>
                                        <td class="text-center">0.0000234</td>
                                        <td class="text-right">4.3456600</td>
                                        <td class="text-right">6.6768876</td>
                                    </tr>
                                    <tr>
                                        <th width="30px"></th>
                                        <th>BIT</th>
                                        <td class="text-center">0.0000567</td>
                                        <td class="text-right">4.3456600</td>
                                        <td class="text-right">6.6768876</td>
                                    </tr>
                                    <tr>
                                        <th width="30px"></th>
                                        <th>EGF</th>
                                        <td class="text-center">0.0000234</td>
                                        <td class="text-right">4.3456600</td>
                                        <td class="text-right">6.6768876</td>
                                    </tr>
                                    <tr>
                                        <th width="30px"></th>
                                        <th>EER</th>
                                        <td class="text-center">0.0000567</td>
                                        <td class="text-right">4.3456600</td>
                                        <td class="text-right">6.6768876</td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<footer>

</footer>
<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>
<script src="<?php echo JS; ?>underscore-min.js"></script>
<script type="text/javascript">
    document.addEventListener("DOMContentLoaded", function(event) {

        var themeSwitcher = document.getElementById("theme-switcher");
        let themas = document.querySelector('#theme');

        themeSwitcher.onclick = function() {
            var currentTheme = themas.getAttribute("class");
            var switchToTheme = currentTheme === "crypt-dark" ? "crypt-light" : "crypt-dark"

            themas.setAttribute("class", switchToTheme);
        }
    });




    var amountCompra = 0;
    var amountVenda = 0;
    var precoCompra = 0;
    var precoVenda = 0;
    var balanceMode = 1;
    var somenteFavoritas = false;
    var casasDecimaisReal = <?php echo empty($paridade->casasDecimaisMoedaTrade) ? $paridade->moedaTrade->casasDecimais : $paridade->casasDecimaisMoedaTrade ?>;
    var pageWidth, pageHeight;
    var data = "todos";
    var tipo = "todos";
    var limite = 10;
    var listMinhasOrdens = "";
    var listTrade = "";
    var basePage = {
    width: 2048,
    height: 768,
    scale: 1,
    scaleX: 1,
    scaleY: 1
    };


    $(document).ready(function () {
        //alertaKyc();
        //listarBook();
        //listarParidadesBook();
        //listarSaldoMoedasBook();
        setInterval(listarTicker, 10000);
        //setInterval(listarParidadesBook, 10000);
        //setInterval(listarSaldoMoedasBook, 5000);
       // setInterval(listarBook, 3000);

    }

</script>
</body>
