<?php
use Utils\Rotas;
$moeda = \Modules\principal\Controllers\Principal::getCurrency();
$usuario = Utils\Geral::getLogado();
$cliente = Utils\Geral::getCliente();
$idioma = new \Utils\PropertiesUtils("menu", IDIOMA);
$paridade = Modules\principal\Controllers\Principal::getParity();
$layout = \Models\Modules\Cadastro\LayoutRn::getLayout($cliente->id);
$layoutJson = json_decode($layout->orderBook);



?>
<style type="text/css">
    .row1 {
        padding: 1px !important;
        margin-bottom: 1px !important;
    }
    .row2 {
        padding: 1px !important;
        height: 286px !important;
        margin-bottom: 2px !important;
    }
    .row3 {
        padding: 1px !important;
        height: 315px !important;
        margin-bottom: 2px !important;
    }
    .row4 {
        padding: 1px !important;
        margin-bottom: 1px !important;
    }
    .row5 {
        padding: 1px !important;
        margin-bottom: 1px !important;
    }
    .market {
        height: 284px !important;
    }
    .chartMarketP {
        height: 284px !important;
    } 
    .moduleAction {
        height: 315px !important;

    }
    .marketBuy {
        height: 315px !important;
    }
    .marketSell {
        height: 315px !important;
    }
    .marketHistory {

    }
    .myOrder {
        margin-top: 5px !important;
        margin-bottom: 5px !important;
    }
    .myOrderHistory {
        margin-top: 5px !important;
        margin-bottom: 5px !important;
    }
    .ibox {
    }   
    .actbuy {
        background-color: #1ab394 !important;
        color: #ffffff !important;
        border-top-left-radius:  5px !important;
        border-bottom-left-radius:  5px !important;
    }
    .actsell {
        background-color: #ed5565 !important;
        color: #ffffff !important;
        border-top-right-radius:  5px !important;
        border-bottom-right-radius:  5px !important;
    }

    .panel {
        margin-bottom: 1px !important;
        border: 0px transparent !important;
    }
    .panel-body {
        padding: 5px !important;
    }
    .panel-heading {
        padding: 0px 0px !important;
    }
    .input-group-addon.le {
        background-color: #fff;
        border-left: 1px solid #E5E6E7;
        border-top: 1px solid #E5E6E7; 
        border-bottom: 1px solid #E5E6E7;
        border-right: none;
        border-radius: 5px;
        color: inherit;
        font-size: 14px;
        font-weight: 400;
        line-height: 1;
        padding: 6px 12px;
        text-align: center;
    }
    .input-group{
         text-align: center !important;
    }
    .form-control.le{
        border-left: none !important;
    }
    .form-control:focus:focus {
        border-color: #E5E6E7 !important;
    }
    .noUi-tooltip {
        display: none;
    }
    .noUi-active .noUi-tooltip {
        display: block;
    }
    table.scroll {
        width: 100%; 
        border-spacing: 0;
    }
    table.scroll tbody,
    table.scroll thead { 
        display: grid; 
    }
    table.scroll tbody {
        height: 265px;
        overflow-y: auto;
        overflow-x: hidden;
        -ms-overflow-style: none;  /* IE and Edge */
        scrollbar-width: none;  /* Firefox */
    }
    table.scroll tbody::-webkit-scrollbar {
        display: none;
    }
    tbody td, thead th {
        width: 20%; 
    }
    tbody td:last-child, thead th:last-child {
        border-right: none;
    }
    table.scrollh {
        width: 100%; 
        border-spacing: 0;
    }
    table.scrollh tbody,
    table.scrollh thead { 
        display: grid;
    }
    table.scrollh tbody {
        height: 549px;
        overflow-y: scroll !important;
        overflow-x: hidden !important;
        -ms-overflow-style: none;  /* IE and Edge */
        scrollbar-width: none;  /* Firefox */
    }
    table::-webkit-scrollbar {
        display: none;
      }
    table.scrollh tbody::-webkit-scrollbar {
        display: none;
    }
    label {
        display: inline-block;
        max-width: 100%;
        margin-bottom: 5px;
        font-size: 11px !important;
}
    span {
        display: inline-block;
        max-width: 100%;
        font-size: 11px !important;
}
    .rounded-circle{
        width: 30px !important;
        height: 30px !important;
}
    .colHeadTable{
        width: 100% !important;
}
    .partialBuy:hover{
        background-color: #1ab3942e !important;
}
    .partialSell:hover{
        background-color: #ed556526 !important;
}
    .favoriteStar:hover{
        color: yellow !important;
}
    .move{
    cursor: move !important;
}
#selectCoin,#selectMarket{
    border:none;
    border-bottom: 1px solid #1ab394 !important;
    padding: 5px 10px 0px;
    outline: none;
 }


</style>

<?php Utils\Layout::append("inspina/metas", $_data) ?>
<?php Utils\Layout::append("inspina/scripts", $_data) ?>
<?php Utils\Layout::append("inspina/menu", $_data) ?>
<!--<link href="<?php //echo TEMA; ?>slider/nouislider.min.css" rel="stylesheet">-->

<div class="page_content" onload="">
    <div class="row sortable-view" id="rowTeste">
            <div class="col-sm-12 col-md-6 row1 marketBook" id="marketBook">
                <div class="panel panel-body move">
                    <div class="row m-xs">
                        <div class="col-xs-2 text-center">
                            <img class="rounded-circle " src="<?php echo IMAGES . "currencies/" . $paridade->moedaBook->icone ?>">
                        </div>
                        <div class="col-xs-10">
                            <div class="row">
                                <div class="col-xs-6 col-md-3 text-center m-b-sm">
                                    <label>VOLUME 24h</label><br>
                                    <span id="volume">-</span>
                                </div>
                                <div class="col-xs-6 col-md-3 text-center m-b-sm">
                                    <label>MENOR</label><br>
                                    <span id="menoPreco">-</span>
                                </div>
                                <div class="col-xs-6 col-md-3 text-center m-b-sm">
                                    <label>MAIOR</label><br>
                                    <span id="maiorPreco">-</span>
                                </div>
                                <div class="col-xs-6 col-md-3 text-center m-b-sm">
                                    <label>ÚLTIMO</label><br>
                                    <span id="ultimoPreco">-</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-md-3 row1 coinBook" id="coinBook">
                <div class="panel panel-body move">
                    <div class="row m-xs">
                        <div class="col-xs-2 text-center">
                            <img class="rounded-circle" src="<?php echo IMAGES . "currencies/" . $paridade->moedaTrade->icone ?>">
                        </div>
                        <div class="col-xs-5 text-center m-b-sm">
                            <label>DISPONÍVEL</label><br>
                            <span id="saldoTrade">-</span>
                        </div>
                        <div class="col-xs-5 text-center m-b-sm">
                            <label>EM ORDEM</label><br>
                            <span id="saldoTradeOrdem">-</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-md-3 row1 coinTrade " id="coinTrade">
                <div class="panel panel-body move">
                    <div class="row m-xs">
                        <div class="col-xs-2 text-center">
                            <img class="rounded-circle" src="<?php echo IMAGES . "currencies/" . $paridade->moedaBook->icone ?>">
                        </div>
                        <div class="col-xs-5 text-center m-b-sm">
                            <label>DISPONÍVEL</label><br>
                            <span id="saldoBook">-</span>
                        </div>
                        <div class="col-xs-5 text-center m-b-sm">
                            <label>EM ORDEM</label><br>
                            <span id="saldoBookOrdem">-</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row sortable-view">
            <div class="col-sm-12 col-md-9">
                <div class="row sortable-view ui-state-default">
                    <div class="col-sm-12 col-md-4 row2 " id="layoutMercado">
                        <div class="panel panel-body market">
                            <div class="panel-heading move">
                                <label class="move">Mercados</label> 
                            </div>
                            <div class="row">
                                <div class="col-sm-12 col-md-12">
                                       <div class="row">
                                           <div class="col-sm-6">
                                               <input type="text" class="form-control text-left" id="selectCoin" placeholder="Coin?">
                                           </div>
                                           <div class="col-sm-6">
                                               <select class="form-control m-b" name="account" id="selectMarket">
                                                    <option>option 1</option>
                                                    <option>option 2</option>
                                                    <option>option 3</option>
                                                    <option>option 4</option>
                                                </select>
                                           </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row ">
                                <div class="col-sm-12 col-md-12">
                                    
                                    <div class="paridade">
                                        <table style="font-size: 14px;" class="table table-striped" id="">
                                            <thead class="thead-h thead-h1 ">
                                                <tr class="tr-h">                                        
                                                    <th class="text-left" style="width: 40% !important;">
                                                        <span>Moeda</span>
                                                    </th>
                                                    <th class="text-left" style="width: 40% !important;">
                                                        <span>Cotação</span>
                                                    </th>
                                                    <th class="text-right" style="width: 20% !important;">
                                                        <span>Oscilação</span>
                                                    </th>
                                                </tr>
                                            </thead>
                                            <tbody id="body-paridades" class="tbody-h tbody-h1" style="cursor: pointer;">
                                                <tr class=" tr-h">                    
                                                    <td class="text-left" >
                                                        <span onclick="addFavorito('');"><i class="fa  fa-star-o favoriteStar" style="color: gray"></i> BTC/BRL</span>                 
                                                    </td>
                                                    <td class="text-left" >
                                                        62.156,0279
                                                    </td>
                                                    <td class="text-right">
                                                        0,0%
                                                    </td>           
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                    <div class="col-md-8 row2">
                        <iframe style="border: none;" seamless="seamless" src="<?php echo GRAFICO ?>/index.html?lang=<?php echo $idioma->getLang()?>&symbol=<?php echo $paridade->symbol ?>" width="100%" height="55%"></iframe>
<!--                        <div class="panel panel-body chartMarketP" id="chartMarket">

                        </div>-->
                    </div>
                </div>
                <div class="row sortable-view  ui-state-default">
                    <div id="" class="col-sm-12 col-md-4 row3" id="operacao">
                        <div class="panel panel-body moduleAction">
                            <div class="panel-heading move">
                                <label class="move">Executar Operação</label> 
                    </div>
                            <div class="form-group">
                                <div class="input-group m-b">
                                    <span class="input-group-addon actbuy selectActbuySell" style="cursor: pointer;" value="buy">COMPRAR</span>

                                    <span class="input-group-addon actsell selectActbuySell" style="cursor: pointer;" value="sell">VENDER</span>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="input-group m-b" style="width: 100%">
                                    <span class="input-group-addon le" style="cursor: default;width: 70px;">Preço</span>
                                    <input type="text" class="form-control le text-right">
                                    <span class="input-group-addon ri" style="cursor: pointer;">BRL</span>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="input-group m-b">
                                    <span class="input-group-addon le" style="cursor: default;width: 70px;">Volume</span>
                                    <input type="text" class="form-control le text-right"> 
                                    <span class="input-group-addon ri" style="cursor: pointer;">BTC</span>
                                </div>
                            </div>             
                            <div class="form-group">
                                <div class="input-group m-b">
                                    <span class="input-group-addon le" style="cursor: default;width: 70px;">Total</span>
                                    <input type="text" class="form-control le text-right" id="buytotal"> 
                                    <span class="input-group-addon" style="cursor: pointer;"> BRL </span>
                                </div>
                            </div>
                            <div class="form-group text-center">
                                <div class="btn-group">
                                    <button class="btn btn-white btn-sm partial partialBuy" onclick="salvarLayout();"type="button" value="0">0</button>
                                    <button class="btn btn-white btn-sm partial partialBuy" onclick="montarLayout();"type="button" value="10">10%</button>
                                    <button class="btn btn-white btn-sm partial partialBuy" type="button" value="20">20%</button>
                                    <button class="btn btn-white btn-sm partial partialBuy" type="button" value="30">30%</button>
                                    <button class="btn btn-white btn-sm partial partialBuy" type="button" value="50">50%</button>
                                    <button class="btn btn-white btn-sm partial partialBuy" type="button" value="80">80%</button>
                                    <button class="btn btn-white btn-sm partial partialBuy" type="button" value="100">100%</button>
                                </div>
                            </div>
                          
                            <div class="form-actions text-center">                                                                     
                                <button type="button" class="btn btn-primary full-width m-t-xs" id="btnOrderBuySell" value="buy">
                                    Registrar Ordem de Compra
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 row3" id="ordensCompra">
                        <div class="panel panel-body marketBuy">
                    <div class="panel-heading move">
                        <label class="move">Ordens de Compra</label> 
                    </div> 
                    <table class="table table-hover table-bordered table-condensed table-stripped scroll" style="font-size: 11px;background-color: #fff">
                        <thead>
                            <tr>
                                <th class="text-center">Cotação - BRL</th>
                                <th class="text-center">Volume - BTC</th>
                                <th class="text-center">Valor Total</th>
                            </tr>
                        </thead>
                        <tbody id="buy-list">
                            <tr class="order-item-V" style="color: #1ab394; cursor: pointer; font-size: 10px;">
                                <td class="text-center">
                                    BRL 58.899,9999            </td>
                                <td class="text-center">
                                    0.00541057            </td>
                                <td class="text-center">
                                    BRL 318,6826            </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                    </div>
                    <div class="col-md-4 row3" id="ordemVenda">
                        <div class="panel panel-body marketSell">
                    <div class="panel-heading panel-default move">
                        <label class="move">Ordens de Venda</label> 
                    </div> 
                    <table class="table table-hover table-bordered table-condensed table-stripped scroll" style="font-size: 11px;background-color: #fff">
                        <thead>
                            <tr>
                                <th class="text-center">Cotação - BRL</th>
                                <th class="text-center">Volume - BTC</th>
                                <th class="text-center">Total</th>
                            </tr>
                        </thead>
                        <tbody id="sell-list">
                            <tr class="order-item-V" style="color: #ed5565; cursor: pointer; font-size: 10px;">
                                <td class="text-center">
                                    BRL 58.899,9999            </td>
                                <td class="text-center">
                                    0.00541057            </td>
                                <td class="text-center">
                                    BRL 318,6826            </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>

                    </div>
                </div>

            <div class="col-md-3 row1" id="historicoOrdem">
                <div class="panel panel-body">
                    <div class="panel-heading move">
                        <label class="move">Histórico de Ordens</label>
                    </div> 
                    <table class="table table-hover table-bordered table-condensed table-strippe scrollh" style="font-size: 11px;background-color: #fff">
                        <thead>
                            <tr>
                                <th class="text-center">Cotação - BRL</th>
                                <th class="text-center">Volume - BTC</th>
                                <th class="text-center">Evento</th>
                            </tr>
                        </thead>
                        <tbody id="sell-list">
                            <tr class="order-item-V" style="color: #ff1e1e;; cursor: pointer; font-size: 10px;">
                                <td class="text-center">
                                    BRL 58.899,9999            </td>
                                <td class="text-center">
                                    0.00541057            </td>
                                <td class="text-center">
                                    BRL 318,6826            </td>
                            </tr>
                            <tr class="order-item-V" style="color: #ff1e1e;; cursor: pointer; font-size: 10px;">
                                <td class="text-center">
                                    BRL 58.899,9999            </td>
                                <td class="text-center">
                                    0.01236316            </td>
                                <td class="text-center">
                                    BRL 728,1901            </td>
                            </tr>
                            <tr class="order-item-V" style="color: #ff1e1e;; cursor: pointer; font-size: 10px;">
                                <td class="text-center">
                                    BRL 58.899,9999            </td>
                                <td class="text-center">
                                    0.01236316            </td>
                                <td class="text-center">
                                    BRL 728,1901            </td>
                            </tr>
                            <tr class="order-item-V" style="color: #ff1e1e;; cursor: pointer; font-size: 10px;">
                                <td class="text-center">
                                    BRL 58.899,9999            </td>
                                <td class="text-center">
                                    0.01236316            </td>
                                <td class="text-center">
                                    BRL 728,1901            </td>
                            </tr>
                            <tr class="order-item-V" style="color: #ff1e1e;; cursor: pointer; font-size: 10px;">
                                <td class="text-center">
                                    BRL 58.899,9999            </td>
                                <td class="text-center">
                                    0.01236316            </td>
                                <td class="text-center">
                                    BRL 728,1901            </td>
                            </tr>
                            <tr class="order-item-V" style="color: #ff1e1e;; cursor: pointer; font-size: 10px;">
                                <td class="text-center">
                                    BRL 58.899,9999            </td>
                                <td class="text-center">
                                    0.01236316            </td>
                                <td class="text-center">
                                    BRL 728,1901            </td>
                            </tr>
                            <tr class="order-item-V" style="color: #ff1e1e;; cursor: pointer; font-size: 10px;">
                                <td class="text-center">
                                    BRL 58.899,9999            </td>
                                <td class="text-center">
                                    0.01236316            </td>
                                <td class="text-center">
                                    BRL 728,1901            </td>
                            </tr>
                            <tr class="order-item-V" style="color: #ff1e1e;; cursor: pointer; font-size: 10px;">
                                <td class="text-center">
                                    BRL 58.899,9999            </td>
                                <td class="text-center">
                                    0.01236316            </td>
                                <td class="text-center">
                                    BRL 728,1901            </td>
                            </tr>
                            <tr class="order-item-V" style="color: #ff1e1e;; cursor: pointer; font-size: 10px;">
                                <td class="text-center">
                                    BRL 58.899,9999            </td>
                                <td class="text-center">
                                    0.01236316            </td>
                                <td class="text-center">
                                    BRL 728,1901            </td>
                            </tr>
                            <tr class="order-item-V" style="color: #ff1e1e;; cursor: pointer; font-size: 10px;">
                                <td class="text-center">
                                    BRL 58.899,9999            </td>
                                <td class="text-center">
                                    0.01236316            </td>
                                <td class="text-center">
                                    BRL 728,1901            </td>
                            </tr>
                            <tr class="order-item-V" style="color: #ff1e1e;; cursor: pointer; font-size: 10px;">
                                <td class="text-center">
                                    BRL 58.899,9999            </td>
                                <td class="text-center">
                                    0.01236316            </td>
                                <td class="text-center">
                                    BRL 728,1901            </td>
                            </tr>
                            <tr class="order-item-V" style="color: #ff1e1e;; cursor: pointer; font-size: 10px;">
                                <td class="text-center">
                                    BRL 58.899,9999            </td>
                                <td class="text-center">
                                    0.01236316            </td>
                                <td class="text-center">
                                    BRL 728,1901            </td>
                            </tr>
                            <tr class="order-item-V" style="color: #ff1e1e;; cursor: pointer; font-size: 10px;">
                                <td class="text-center">
                                    BRL 58.899,9999            </td>
                                <td class="text-center">
                                    0.01236316            </td>
                                <td class="text-center">
                                    BRL 728,1901            </td>
                            </tr>
                            <tr class="order-item-V" style="color: #ff1e1e;; cursor: pointer; font-size: 10px;">
                                <td class="text-center">
                                    BRL 58.899,9999            </td>
                                <td class="text-center">
                                    0.01236316            </td>
                                <td class="text-center">
                                    BRL 728,1901            </td>
                            </tr>
                            <tr class="order-item-V" style="color: #ff1e1e;; cursor: pointer; font-size: 10px;">
                                <td class="text-center">
                                    BRL 58.899,9999            </td>
                                <td class="text-center">
                                    0.01236316            </td>
                                <td class="text-center">
                                    BRL 728,1901            </td>
                            </tr>
                            <tr class="order-item-V" style="color: #ff1e1e;; cursor: pointer; font-size: 10px;">
                                <td class="text-center">
                                    BRL 58.899,9999            </td>
                                <td class="text-center">
                                    0.01236316            </td>
                                <td class="text-center">
                                    BRL 728,1901            </td>
                            </tr>
                            <tr class="order-item-V" style="color: #ff1e1e;; cursor: pointer; font-size: 10px;">
                                <td class="text-center">
                                    BRL 58.899,9999            </td>
                                <td class="text-center">
                                    0.01236316            </td>
                                <td class="text-center">
                                    BRL 728,1901            </td>
                            </tr>
                            <tr class="order-item-V" style="color: #ff1e1e;; cursor: pointer; font-size: 10px;">
                                <td class="text-center">
                                    BRL 58.899,9999            </td>
                                <td class="text-center">
                                    0.01236316            </td>
                                <td class="text-center">
                                    BRL 728,1901            </td>
                            </tr>
                            <tr class="order-item-V" style="color: #ff1e1e;; cursor: pointer; font-size: 10px;">
                                <td class="text-center">
                                    BRL 58.899,9999            </td>
                                <td class="text-center">
                                    0.01236316            </td>
                                <td class="text-center">
                                    BRL 728,1901            </td>
                            </tr>
                            <tr class="order-item-V" style="color: #ff1e1e;; cursor: pointer; font-size: 10px;">
                                <td class="text-center">
                                    BRL 58.899,9999            </td>
                                <td class="text-center">
                                    0.01236316            </td>
                                <td class="text-center">
                                    BRL 728,1901            </td>
                            </tr>
                            <tr class="order-item-V" style="color: #ff1e1e;; cursor: pointer; font-size: 10px;">
                                <td class="text-center">
                                    BRL 58.899,9999            </td>
                                <td class="text-center">
                                    0.01236316            </td>
                                <td class="text-center">
                                    BRL 728,1901            </td>
                            </tr>
                            <tr class="order-item-V" style="color: #ff1e1e;; cursor: pointer; font-size: 10px;">
                                <td class="text-center">
                                    BRL 58.899,9999            </td>
                                <td class="text-center">
                                    0.01236316            </td>
                                <td class="text-center">
                                    BRL 728,1901            </td>
                            </tr>
                            <tr class="order-item-V" style="color: #ff1e1e;; cursor: pointer; font-size: 10px;">
                                <td class="text-center">
                                    BRL 58.899,9999            </td>
                                <td class="text-center">
                                    0.01236316            </td>
                                <td class="text-center">
                                    BRL 728,1901            </td>
                            </tr>
                            <tr class="order-item-V" style="color: #ff1e1e;; cursor: pointer; font-size: 10px;">
                                <td class="text-center">
                                    BRL 58.899,9999            </td>
                                <td class="text-center">
                                    0.01236316            </td>
                                <td class="text-center">
                                    BRL 728,1901            </td>
                            </tr>
                            <tr class="order-item-V" style="color: #ff1e1e;; cursor: pointer; font-size: 10px;">
                                <td class="text-center">
                                    BRL 58.899,9999            </td>
                                <td class="text-center">
                                    0.01236316            </td>
                                <td class="text-center">
                                    BRL 728,1901            </td>
                            </tr>
                            <tr class="order-item-V" style="color: #ff1e1e;; cursor: pointer; font-size: 10px;">
                                <td class="text-center">
                                    BRL 58.899,9999            </td>
                                <td class="text-center">
                                    0.01236316            </td>
                                <td class="text-center">
                                    BRL 728,1901            </td>
                            </tr>
                            <tr class="order-item-V" style="color: #ff1e1e;; cursor: pointer; font-size: 10px;">
                                <td class="text-center">
                                    BRL 58.899,9999            </td>
                                <td class="text-center">
                                    0.01236316            </td>
                                <td class="text-center">
                                    BRL 728,1901            </td>
                            </tr>
                            <tr class="order-item-V" style="color: #ff1e1e;; cursor: pointer; font-size: 10px;">
                                <td class="text-center">
                                    BRL 58.899,9999            </td>
                                <td class="text-center">
                                    0.01236316            </td>
                                <td class="text-center">
                                    BRL 728,1901            </td>
                            </tr>
                            <tr class="order-item-V" style="color: #ff1e1e;; cursor: pointer; font-size: 10px;">
                                <td class="text-center">
                                    BRL 58.899,9999            </td>
                                <td class="text-center">
                                    0.01236316            </td>
                                <td class="text-center">
                                    BRL 728,1901            </td>
                            </tr>
                            <tr class="order-item-V" style="color: #ff1e1e;; cursor: pointer; font-size: 10px;">
                                <td class="text-center">
                                    BRL 58.899,9999            </td>
                                <td class="text-center">
                                    0.01236316            </td>
                                <td class="text-center">
                                    BRL 728,1901            </td>
                            </tr>
                            <tr class="order-item-V" style="color: #ff1e1e;; cursor: pointer; font-size: 10px;">
                                <td class="text-center">
                                    BRL 58.899,9999            </td>
                                <td class="text-center">
                                    0.01236316            </td>
                                <td class="text-center">
                                    BRL 728,1901            </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            </div>



            


        
        
        <div class="row sortable-view ui-state-default">
        <div class="row row4">
            <div class="col-12 col-sm-12  myOrder" id="myOrder">
                    <div class="panel panel-body" style="">
                        <div class="panel-heading move">
                            <label class="move">Ordens Abertas</label> 
                        </div> 
                        <table class="table table-hover table-bordered" style="font-size: 11px;background-color: #fff">
                            <thead>
                                <tr>
                                    <th class="text-left">Data</th>
                                    <th class="text-left">Paridade</th>
                                    <th class="text-left">Tipo</th>
                                    <th class="text-left">Media</th>
                                    <th class="text-left">Preço</th>
                                    <th class="text-left">Volume</th>
                                    <th class="text-left">Executado</th>
                                    <th class="text-left">Total</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr class="" style="color: #1ab394; cursor: pointer; font-size: 10px;">
                                    <td class="text-left">08-07 15:29:09</td>
                                    <td class="text-left">BRL/BTC</td>
                                    <td class="text-left">Venda</td>
                                    <td class="text-left">BRL 58.899,99</td>
                                    <td class="text-left">BRL 58.899,9999</td>
                                    <td class="text-left">0.22945621</td>
                                    <td class="text-left">0.05186498</td>
                                    <td class="text-left">BRL 51.899,99</td>
                                </tr>
                            </tbody>
                        </table>
                </div>
            </div>
        </div>

        <div class="row row5">
            <div class="col-12 col-sm-12  myOrderHistory" id="myOrderHistory">
                    <div class="panel panel-body" style="">
                        <div class="panel-heading panel-default move">
                            <label class="move">Historico 24hs</label> 
                        </div>
                        <table class="table table-hover table-bordered table-condensed table-strippe" style="font-size: 11px;background-color: #fff">
                            <thead>
                                <tr>
                                    <th class="text-left">Data</th>
                                    <th class="text-center">Paridade</th>
                                    <th class="text-center">Tipo</th>
                                    <th class="text-center">Media</th>
                                    <th class="text-center">Preço</th>
                                    <th class="text-center">Volume</th>
                                    <th class="text-center">Executado</th>
                                    <th class="text-center">Total</th>
                                </tr>
                            </thead>
                            <tbody id="">
                                <tr class="" style="color: #1ab394; cursor: pointer; font-size: 10px;">
                                    <td class="text-left">08-07 15:29:09</td>
                                    <td class="text-center">BRL/BTC</td>
                                    <td class="text-center">Venda</td>
                                    <td class="text-center">BRL 58.899,99</td>
                                    <td class="text-center">BRL 58.899,9999</td>
                                    <td class="text-center">0.22945621</td>
                                    <td class="text-center">0.05186498</td>
                                    <td class="text-center">BRL 51.899,99</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
            </div>
        </div>
    </div>

</div>
<script src="<?php echo TEMA; ?>plugins/jQuery/jquery-2.2.3.min.js?<?php echo time() ?>"></script>
<script src="<?php echo TEMA; ?>js/jquery-3.1.1.min.js?<?php echo time() ?>"></script>
<script src="<?php echo TEMA; ?>js/jquery.1.11.min.js"></script>
<script src="<?php echo TEMA; ?>js/jquery-ui.min.js"></script>
<script src="<?php echo TEMA; ?>js/jquery.ui.touch-punch.min.js"></script>
<script src="<?php echo TEMA; ?>bootstrap/js/bootstrap.min.js"></script>
<script src="<?php echo TEMA; ?>js/plugins/metisMenu/jquery.metisMenu.js"></script>
<script src="<?php echo TEMA; ?>js/plugins/sweetalert/sweetalert.min.js"></script>
<script src="<?php echo TEMA; ?>js/jAlert/jAlert-functions.js?<?php echo time(); ?>"></script>
<script src="<?php echo TEMA; ?>js/jAlert/jAlert.js?<?php echo time(); ?>"></script>
<script src="<?php echo TEMA; ?>js/plugins/toastr/toastr.min.js"></script>
<script type="text/javascript" src="https://s3.tradingview.com/tv.js"></script>




<script type="text/javascript">
$( document ).ready(function() {  
    
    dadosParidade();
    dadosSaldos();
    setInterval(dadosParidade, 5000);
    setInterval(dadosSaldos, 3000);
    
    $( ".sortable-view" ).sortable();
    $( ".sortable-view" ).disableSelection();
    
    $('.selectActbuySell').click(function() {
        if($(this).attr('value')=='buy'){
            $('#btnOrderBuySell').addClass('btn-primary').removeClass('btn-danger').val('buy').text('Registrar Ordem de Compra');
            $('.partial').addClass('partialBuy').removeClass('partialSell');
        }else{
            $('#btnOrderBuySell').addClass('btn-danger').removeClass('btn-primary').val('sell').text('Registrar Ordem de Venda');
            $('.partial').addClass('partialSell').removeClass('partialBuy');
        }
    });
    
    $('.partial').click(function() {
        console.log($(this).val());
    });
    
    });

        $('#sair,#logout').click(function () {
            swal({
                title: "<?php echo $idioma->getText("temCerteza")?>",
                text: "<?php echo $idioma->getText("seraNecessario")?>" ,
                type: "success",
                showCancelButton: true,
                closeOnConfirm: false,
                showLoaderOnConfirm: true,
                confirmButtonColor: "#18a689",
                confirmButtonText: "<?php echo $idioma->getText("simQueroSair")?>",
                cancelButtonText: "<?php echo $idioma->getText("queroFicar")?>"
            },
                    function () {
                        setTimeout(function () {
                            swal("<?php echo $idioma->getText("sessaFinalizada")?>");
                            window.location.href = "<?php echo URLBASE_CLIENT . Utils\Rotas::R_LOGOUT ?>";
                        }, 1000);
                    });
        });


    $(function () {
        $('.mall-slider-handles').each(function () {
            var el = this;
            noUiSlider.create(el, {
                start: [0],
                tooltips: true,
                format: wNumb({
                    decimals: 0,
                    suffix: ' %'
                }),
                step: 5,
                connect: [true, false],
                range: {
                    min: [0],
                    max: [100]
                },

            });
        })
    });
// Change the selector if needed
    var $table = $('table.scroll'),
            $bodyCells = $table.find('tbody tr:first').children(),
            colWidth;

// Adjust the width of thead cells when window resizes
    $(window).resize(function () {
        // Get the tbody columns width array
        colWidth = $bodyCells.map(function () {
            return $(this).width();
        }).get();

        // Set the width of thead columns
        $table.find('thead tr').children().each(function (i, v) {
            $(v).width(colWidth[i]);
        });
    }).resize(); // Trigger resize handler


    new TradingView.widget(
            {
                "height": "100%",
                "height": "100%",
                "symbol": "MERCADO:BTCBRL",
                "interval": "D",
                "timezone": "Etc/UTC",
                "theme": "light",
                "style": "1",
                "locale": "ptbr",
                "enable_publishing": false,
                "hide_side_toolbar": false,
                "allow_symbol_change": true,
                "container_id": "chartMarket",
                "toolbar_bg": "#131722",

            }
    );
    
    var initial = [];
    $(function() {
          //Initialize scenarios sortable
          //$( ".linha1" ).sortable();
          //Capture Initial List
          
          
          //Restore default list
//          $('body').on('click', '.restore-scenarios', function(){
//            $('.ui-state-default').each(function(index, anchor) {
//              anchor.innerHTML = initial[index];
//            });
//          });
         }); 
         
   function salvainicio(){
   $('.ui-state-default').each(function(index, anchor) {
              initial.push(anchor.innerHTML);
              console.log('gravado: ' + anchor.innerHTML)
          });
    }
         
         
    
    function salvarLayout() {
        console.log($("#rowTeste" ).sortable("toArray"));
        console.log($("#marketBook").attr("class"));
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . \Utils\Rotas::R_BOOK_LAYOUT_SALVAR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                marketBook: $("#marketBook").attr("class"),
                coinBook: $("#coinBook").attr("class"),
                coinTrade: $("#coinTrade").attr("class"),
                layoutMercado: $("#layoutMercado").attr("class"),
                operacao: $("#operacao").attr("class"),
                ordensCompra: $("#ordensCompra").attr("class"),
                ordemVenda: $("#ordemVenda").attr("class"),
                historicoOrdem: $("#historicoOrdem").attr("class"),
                myOrder: $("#myOrder").attr("class"),
                myOrderHistory: $("#myOrderHistory").attr("class"),
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(json.mensagem, "e");
                }
            }
        });
    }
    
    function montarLayout() {
        
//        $("#marketBook").removeClass().addClass('<?php //echo $layoutJson->marketBook ?>');
//        $("#coinBook").removeClass().addClass('<?php //echo $layoutJson->coinBook ?>');
//        $("#coinTrade").removeClass().addClass('<?php //echo $layoutJson->coinTrade ?>');
//        $("#layoutMercado").removeClass().addClass('<?php //echo $layoutJson->layoutMercado ?>');
//        $("#operacao").removeClass().addClass('<?php //echo $layoutJson->operacao ?>');
//        $("#ordensCompra").removeClass().addClass('<?php //echo $layoutJson->ordensCompra ?>');
//        $("#ordemVenda").removeClass().addClass('<?php //echo $layoutJson->ordemVenda ?>');
//        $("#historicoOrdem").removeClass().addClass('<?php //echo $layoutJson->historicoOrdem ?>');
//        $("#myOrder").removeClass().addClass('<?php //echo $layoutJson->myOrder ?>');
//        $("#myOrderHistory").removeClass().addClass('<?php //echo $layoutJson->myOrderHistory ?>');
//        
        
        console.log($("#rowTeste" ).sortable("toArray"));
        
        $("#rowTeste").sortable(["coinTrade", "coinBook", "marketBook"]);
        $("#rowTeste").sortable( "refreshPositions" );
       // $("#rowTeste").sortable();
      //   $("#rowTeste").disableSelection();
               
//        coinBook: $("#coinBook").attr("class"),
//        coinTrade: $("#coinTrade").attr("class"),
//        layoutMercado: $("#layoutMercado").attr("class"),
//        operacao: $("#operacao").attr("class"),
//        ordensCompra: $("#ordensCompra").attr("class"),
//        ordemVenda: $("#ordemVenda").attr("class"),
//        historicoOrdem: $("#historicoOrdem").attr("class"),
//        myOrder: $("#myOrder").attr("class"),
//        myOrderHistory: $("#myOrderHistory").attr("class"),
           
    }
    
    var flagParidade = true;
    function dadosParidade() { 
        if(flagParidade){
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . \Utils\Rotas::R_BOOK_PARIDADE ?>',
            method: 'post',
            dataType:'json',
            beforeSend: function () {
                flagParidade = false;
            },        
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#volume").html(json.volume);
                        $("#menorPreco").html(json.menor);
                        $("#maiorPreco").html(json.maior);
                        $("#ultimoPreco").html(json.ultimo);
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {                   
                    showNotyAlert(e, "e");
                }
                flagParidade = true;
            },
            complete: function () {
                flagParidade = true;
            }
        });
        }
    }
    
    var flagSaldo = true;
    function dadosSaldos() { 
        if(flagSaldo){
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . \Utils\Rotas::R_BOOK_SALDOS ?>',
            method: 'post',
            dataType:'json',
            beforeSend: function () {
                flagSaldo = false;
            },        
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#saldoTrade").html(json.tradeDisponivel);
                        $("#saldoTradeOrdem").html(json.tradeBloqueado);
                        $("#saldoBook").html(json.bookBloqueado);
                        $("#saldoBookOrdem").html(json.bookDisponivel);
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {                   
                    showNotyAlert(e, "e");
                }
                flagSaldo = true;
            },
            complete: function () {
                flagSaldo = true;
            }
        });
        }
    }
    
</script>
</body>
