<?php

$cliente = Utils\Geral::getCliente();
$mostrarBotoes = ($paridade->ativo > 0 && $paridade->statusMercado > 0 && $cliente->statusMercado > 0 && $paridade->moedaBook->statusMercado > 0 && $paridade->moedaBook->ativo > 0);
$mostrarAlerta = false;
$mensagemAlerta = "";

$idioma = new \Utils\PropertiesUtils("compra_venda_direta", IDIOMA);

if ($paridade->ativo < 1 || $paridade->moedaBook->ativo < 1) {
    $mostrarAlerta = true;
    $mensagemAlerta = $idioma->getText("mercadoEncerrado");
} else if ($paridade->statusMercado < 1 || $paridade->moedaBook->statusMercado < 1) {
    $mostrarAlerta = true;
    $mensagemAlerta = $idioma->getText("mercadoSupenso");
} else if ($cliente->statusMercado < 1) {
    $mensagemAlerta = $idioma->getText("compraVendaSuspensaConta");
    $mostrarAlerta = true;
}

$_data["idiomaMenu"] = $idioma;
?>
<style>
    .border-edit {
        border: 1px solid #1c84c6 !important;
    }

    .carregando {
        background: url("<?php echo IMAGES ?>loading.gif") center no-repeat;
        width: 200px;
        height: 200px;
        position: absolute;
        top: 30%;
        left: 45%;
        color: blue;
    }

    .box {
        border-radius: 10px !important;
    }

    .box-conversion-custom {
        padding-right: 3px !important;
        padding-left: 3px !important;
    }

    .row {
        margin-right: 0 !important;
        margin-left: 0 !important;
    }


    * {
        font-family: "Segoe UI", Roboto, sans-serif;
    }

    .choose-position .select2-container {
        width: 100% !important;
    }

    .choose-position .select2-container--default .select2-selection--single {
        width: 100% !important;
        display: flex;
        align-items: center;
        padding: 0 30px;
        height: 50px;
        line-height: 50px;
        font-weight: 500;
        font-size: 16px;
        background-color: #fafafa;
        border: 1px solid #eeeeee;
        border-top-right-radius: 25px;
        border-bottom-right-radius: 25px;
        transition: 0.1s;
    }

    .select2-dropdown {
        border: 1px solid #eeeeee !important;
    }

    .choose-position .select2-search {
        display: none;
    }

    .choose-position .choose-input {
        width: 100% !important;
        display: flex;
        align-items: center;
        padding: 0 30px;
        height: 50px;
        line-height: 50px;
        font-weight: 500;
        font-size: 16px;
        background-color: #fafafa;
        border: 1px solid #eeeeee;
        border-top-left-radius: 25px;
        border-bottom-left-radius: 25px;
        border-top-right-radius: 4px;
        border-bottom-right-radius: 4px;
    }

    .choose-position .select2-results__option {
        display: flex;
        align-items: center;
    }

    .choose-position .select2-results__option .img-flag {
        width: 40px;
        height: 40px;
        border-radius: 50%;
        object-fit: cover;
        margin-right: 10px;
    }

    .choose-position .select2-container--default.select2-container--focus .select2-selection--single {
        border: 1px solid #c9c9c9 !important;
        outline: 0;
    }

    .choose-position span.select2-selection.select2-selection--single {
        outline: none;
    }

    .choose-position .select2-container--default .select2-selection--single .select2-selection__arrow {
        height: 35px;
        top: 50%;
        transform: translateY(-50%);
        right: 10px;
        width: 35px;
        background-color: #fff;
        border-radius: 50%;
        display: flex;
        align-items: center;
        justify-content: center;
        box-shadow: 0 5px 20px rgba(35, 49, 45, 0.14);
    }

    .select2-container--default .select2-selection--single {}
</style>
<?php Utils\Layout::append("inspina/metas", $_data) ?>
<?php Utils\Layout::append("inspina/scripts", $_data) ?>
<?php Utils\Layout::append("inspina/menu", $_data) ?>
<link href="<?php echo TEMA; ?>css.old/plugins/ladda/ladda-themeless.min.css" rel="stylesheet">

<!-- <div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-12">
    </div>
</div> -->

<div class="wrapper wrapper-content mostrar">
    <div class="settings mtb15">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12 col-md-11 mx-auto">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Conversão de Ativos</h5>
                            <div class="">
                                <div class="row choose-position">
                                    <div class="col-lg-6 box-conversion-custom">
                                        <div class="form-group">
                                            <label for="from" class="d-flex justify-content-between">
                                                <div class="info_saldo">Saldo: <a
                                                        href="javascript:inserirSaldo();"><span
                                                            id="saldo_disponivel"></span></a></div>
                                            </label>
                                            <input type="text" class="form-control choose-input" id="from"
                                                placeholder="Valor para conversão">
                                        </div>
                                    </div>

                                    <div class="col-lg-6 box-conversion-custom">
                                        <div class="form-group">
                                            <label for="from" class="d-flex justify-content-between">
                                                <div>De:</div>
                                            </label>
                                            <select id="cryptoFrom"
                                                class="crypto custom-select choose-position choose-position-input"></select>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="">
                                <div class="row choose-position">
                                    <div class="col-lg-6 box-conversion-custom">
                                        <div class="form-group">
                                            <label for="to" class="d-flex justify-content-between">
                                                <div>Total Aproximado:</div>
                                            </label>
                                            <input type="text" class="form-control choose-input" id="to"
                                                placeholder="Insira o valor total">

                                        </div>
                                    </div>

                                    <div class="col-lg-6 box-conversion-custom">
                                        <div class="form-group">
                                            <label for="to" class="d-flex justify-content-between">
                                                <div>Para:</div>
                                            </label>
                                            <select id="cryptoTo" class="crypto custom-select"></select>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="">
                                <div class="choose-position">
                                    <div class="col-lg-12 p-5 box-conversion-custom p-3 text-center">

                                        <div id="confirm-conversion" class="confirm-conversion">
                                            <div class="justify-content-between">
                                                <span>Cotação:</span>&nbsp;<span id="cotacao">0,0000</span>
                                                <br>
                                            </div>
                                            <div class="justify-content-between border-bottom">
                                                <span>Será aproximadamente creditado em sua conta</span>
                                                <h5 id="creditado_conta">0.00000000</h5>
                                            </div>
                                            <div class="justify-content-between" style="font-size: 12px;">
                                                <span>Por favor, confirmar no tempo máximo de 15 Segundos.</span>
                                            </div>
                                            <div class="d-flex align-items-center" style="margin: 20px 0">
                                                <button id="cancel"
                                                    class="btn btn-back btn-lg btn-primary d-flex align-items-center justify-content-center"
                                                    style="margin-right: 10px; flex: 1;">Recomeçar</button>
                                                <button id="convert" onclick="inserirOrdem();"
                                                    class="ladda-button btn btn-conversion btn-lg btn-primary d-flex align-items-center justify-content-center"
                                                    data-style="expand-right" style="flex: 1;">Converter em
                                                    (15s)</button>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="">
                                        <div class="col-lg-12 p-5">
                                            <button id="btn_conversao" class="btn btn-lg btn-primary full-width"
                                                onclick="consultarPreco();">
                                                Calcular Conversão
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>
<link href="<?php echo TEMA; ?>css.old/plugins/toastr/toastr.min.css" rel="stylesheet">
<script src="<?php echo JS; ?>maskMoney.min.js"></script>
<script>
    var preco = 0;
    var time = 0;
    var saldo = 0;
    var regressor = null;
    var casaDecimal = 8;

    $(document).ready(function () {
        $("#btn_conversao").prop("disabled", true);
        $("#cryptoFrom").select2();
        $("#cryptoTo").select2();

        $('#confirm-conversion').hide();
        $('#loading').hide();

        $("#cryptoFrom").on('select2:select', function (e) {
            $("#saldo_disponivel").html("");
            saldo = 0;
            casaDecimal = $("#cryptoFrom option:selected").attr("data-decimal");
            cancelar();
            var data = $("#cryptoFrom").val();
            carregarTo(data);
        });

        $("#cryptoTo").on('select2:select', function (e) {
            cancelar();
            $("#from").val("");
            $("#to").val("");
        });

        $('#cancel').click(function (evt) {
            evt.preventDefault();
            cancelar();
        });

        $("#from, #to").maskMoney({
            decimal: ',',
            thousands: '.',
            allowZero: true,
            allowNegative: false,
            precision: casaDecimal
        });

        $("#from").keyup(function () {
            calculadora("FROM");
        });
        $("#to").keyup(function () {
            calculadora("TO");
        });

        var option = '';
        $.ajax({
            url: "<?php echo URLBASE_CLIENT . \Utils\Rotas::R_MERCADO_BALANCE ?>",
            method: "POST",
            dataType: 'json',
            success: function (json) {

                if (json.sucesso && json.moedas.lenght) {
                    json.moedas.forEach(element => {
                        option += '<option value="' + element.id_moeda + '" title="' + element.imagem + '" data-decimal="' + element.decimal + '">' + element.simbolo + ' - ' + element.nome + '</option>';
                    });
                    $('#cryptoFrom').html(option);

                    $(".crypto").select2({
                        templateResult: function (coin) {
                            var $span = $("<span><img style='width: 25px;' src=" + coin.title + " /> " + coin.text + "</span>");
                            return $span;
                        },
                        templateSelection: function (coin) {
                            var $span = $("<span><img style='width: 25px;' src=" + coin.title + " /> " + coin.text + "</span>");
                            return $span;
                        }
                    });
                    $("#btn_conversao").prop("disabled", false);
                    carregarTo($("#cryptoFrom").val());
                }
            }
        });
    });

    function cancelar() {
        $("#from").val("");
        $("#to").val("");
        $('#btn_conversao').show();
        $('#confirm-conversion').hide();
        clearInterval(regressor);
        preco = 0;
        time = 0;
    }

    function inserirSaldo() {
        saldo = parseFloat(saldo);
        $('#from').maskMoney('mask', saldo);
        calculadora("FROM");
    }

    function consultarPreco() {

        $("#btn_conversao").prop("disabled", true);

        var tipo = $("#cryptoTo option:selected").attr("data-tipo");
        var par = $("#cryptoTo option:selected").attr("data-par");

        $('#creditado_conta').html("");
        $('#cotacao').html("");

        $.ajax({
            url: '<?php echo URLBASE_CLIENT . \Utils\Rotas::R_MERCADO_PRECO ?>',
            method: 'post',
            dataType: 'json',
            data: {
                amount: $("#from").val(),
                from: $('#cryptoFrom').val(),
                tipo: tipo,
                to: $('#cryptoTo').val(),
                par: par
            },
            success: function (json) {
                try {
                    if (json.sucesso) {

                        $('#btn_conversao').hide();
                        $('#loading').hide();

                        $('#convert').text("Converter em (15s)");

                        clearInterval(regressor);

                        if (json.preco > 0) {
                            $("#convert").prop("disabled", false);
                            regressor = setInterval(tempoAprovacao, 1000);

                        } else {
                            $("#convert").prop("disabled", true);
                        }

                        $('#creditado_conta').html(json.volume_format);
                        $('#to').val(json.volume.replace(".", ","));
                        $('#cotacao').html(json.preco_format);
                        preco = json.preco;

                        $('#confirm-conversion').show();

                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#btn_conversao").prop("disabled", false);
            }
        });
    }

    function carregarTo(moeda) {
        $("#cryptoTo").prop("disabled", true);
        $("#cryptoTo").val(null).trigger("change");
        $("#btn_conversao").prop("disabled", true);

        $("#from").val("");
        $("#to").val("");

        var option = '';
        $.ajax({
            url: "<?php echo URLBASE_CLIENT . \Utils\Rotas::R_MERCADO_PARIDADES ?>",
            method: "POST",
            dataType: 'json',
            data: {
                moeda: moeda
            },
            success: function (json) {
                if (json.sucesso) {

                    json.moedas.forEach(element => {
                        option += '<option data-par="' + element.par + '" data-preco="' + element.preco + '" data-tipo="' + element.tipo + '" value="' + element.id_moeda + '" title="' + element.imagem + '">' + element.simbolo + ' - ' + element.nome + '</option>';
                    });
                    $('#cryptoTo').html(option);

                    $(".crypto").select2({
                        templateResult: function (coin) {
                            var $span = $("<span><img style='width: 25px;' src=" + coin.title + " /> " + coin.text + "</span>");
                            return $span;
                        },
                        templateSelection: function (coin) {
                            var $span = $("<span><img style='width: 25px;' src=" + coin.title + " /> " + coin.text + "</span>");
                            return $span;
                        }
                    });
                }
                $("#saldo_disponivel").html(json.saldo_format);
                saldo = json.saldo;
                $("#cryptoTo").prop("disabled", false);
                $("#btn_conversao").prop("disabled", false);
            }
        });
    }

    function tempoAprovacao() {
        $('#convert').text("Converter em (" + (15 - time) + "s)");
        time++;

        if (time == (15 + 1)) {
            clearInterval(regressor);
            $("#convert").prop("disabled", true);
            time = 0;
        }
    }

    function calculadora(origem) {

        var entrada = 0;
        var total = 0;
        var parTipo = $("#cryptoTo option:selected").attr("data-tipo");
        var parPreco = $("#cryptoTo option:selected").attr("data-preco");

        switch (origem) {
            case "FROM":
                entrada = $("#from").maskMoney('unmasked')[0];
                if (entrada > 0) {
                    if (parTipo == "C") {
                        total = entrada / parPreco;
                    } else if (parTipo == "V") {
                        total = parPreco * entrada;
                    }
                    $("#to").maskMoney('mask', total);
                }
                break;

            case "TO":
                entrada = $("#to").maskMoney('unmasked')[0];
                if (entrada > 0) {
                    if (parTipo == "C") {
                        total = entrada * parPreco;
                    } else if (parTipo == "V") {
                        total = entrada / parPreco;
                    }
                    $("#from").maskMoney('mask', total);
                }
                break;
        }
    }

    function inserirOrdem() {
        var parTipo = $("#cryptoTo option:selected").attr("data-tipo");
        var par = $("#cryptoTo option:selected").attr("data-par");
        var total = ($("#to").val().length > 0 ? parseFloat($("#to").val().replace(",", ".")) : 0);
        var entrada = ($("#from").val().length > 0 ? parseFloat($("#from").val().replace(",", ".")) : 0);

        if (parTipo == "C") {
            salvarOrdemCompra(total, par);
        } else if (parTipo == "V") {
            salvarOrdemVenda(entrada, par);
        }
    }

    function salvarOrdemCompra(total, par) {
        $("#convert, #cancel").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . \Utils\Rotas::R_MERCADO_COMPRAR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                par: par,
                amount: total,
                price: preco
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        showNotyAlert(json.mensagem, "s");
                        $('#convert').text("Finalizado");
                        clearInterval(regressor);
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }

                } catch (e) {
                }
                $("#cancel").prop("disabled", false);
            }
        });
    }

    function salvarOrdemVenda(entrada, par) {
        $("#convert, #cancel").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . \Utils\Rotas::R_MERCADO_VENDER ?>',
            method: 'post',
            dataType: 'json',
            data: {
                par: par,
                amount: entrada,
                price: preco
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        showNotyAlert(json.mensagem, "s");
                        $('#convert').text("Finalizado");
                        clearInterval(regressor);
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                }
                $("#cancel").prop("disabled", false);
            }
        });
    }
</script>
<?php Utils\Layout::append("mensage_text", $_data) ?>