<?php
use Utils\Rotas;
$precoBitcoin = (isset($_data["precoBitcoin"]) ? $_data["precoBitcoin"] : 0);
$precoLitecoin = (isset($_data["precoLitecoin"]) ? $_data["precoLitecoin"] : 0);
$precoDash = (isset($_data["precoDash"]) ? $_data["precoDash"] : 0);
$precoEthereum = (isset($_data["precoEthereum"]) ? $_data["precoEthereum"] : 0);
$precoReais = (isset($_data["precoReais"]) ? $_data["precoReais"] : 0);


$saldoBitcoin = (isset($_data["saldoBtc"]) ? $_data["saldoBtc"] : 0);
$saldoLitecoin = (isset($_data["saldoLtc"]) ? $_data["saldoLtc"] : 0);
$saldoDash = (isset($_data["saldoDash"]) ? $_data["saldoDash"] : 0);
$saldoEthereum = (isset($_data["saldoEth"]) ? $_data["saldoEth"] : 0);
$saldoReais = (isset($_data["saldoBrl"]) ? $_data["saldoBrl"] : 0);

$faseAtual = (isset($_data["faseAtual"]) ? $_data["faseAtual"] : 0);

$idioma = new \Utils\PropertiesUtils("compraico", IDIOMA);

$_data["idiomaMenu"] = $idioma;

//$faseAtual = new \Models\Modules\ICO\FaseIco();
?>
<style>
    .border-edit {
        border: 1px solid #1c84c6 !important;
    }
</style>
<?php Utils\Layout::append("inspina/metas", $_data) ?>
<?php Utils\Layout::append("inspina/scripts", $_data) ?>
<?php Utils\Layout::append("inspina/menu", $_data) ?>
<?php Utils\Layout::append("inspina/breadcrumb", $_data) ?>
<div class="wrapper wrapper-content  animated fadeInRight">
    
    
    <div class="row m-b-lg">
        <div class="col col-12">
            <div class="alert alert-info">
                <?php echo $idioma->getText("compraico1") ?>
            </div>
        </div>
    </div>
        
    <div class="row">
        <div class="col-lg-12">
            <div class="contact-box">

                <div class="col-sm-3">
                    <div class="text-center">
                        <img alt="image" class="img-circle m-t-xs img-responsive" style="max-width: 80px; max-height: 80px;" src="<?php echo IMAGES .  "currencies/BRL.png" ?>">
                    </div>
                </div>
                <div class="col-sm-5">
                    <h3><strong><?php echo $idioma->getText("compraico2") ?> BRL</strong></h3>
                    <p>
                        <?php echo number_format($precoReais, 4, ".", "")?> BRL = 1 NEWC Token
                    </p>
                    <h4><strong><?php echo $idioma->getText("compraico7") ?>  <?php echo number_format($saldoReais, 8, ".", "")?> BRL</strong></h4>
                </div>

                <div class="col-sm-4">
                    <label><?php echo $idioma->getText("compraico3") ?> BRL: </label>
                    <div class="input-group">
                        <input type="text" class="form-control" id="compraIcoAmountBRL"> 
                        <span class="input-group-btn"> 
                            <button type="button" onclick="modalComprar('BRL');" class="btn btn-success"><?php echo $idioma->getText("compraico6") ?>  BRL</button>  
                        </span>
                    </div>

                    <div class="row mt-2">
                        <div class="col-xs-12">
                            <p>
                                <?php echo $idioma->getText("compraico4") ?> <span  id="compraIcoTokensCompradosBRL"></span> NEWC.
                                + <span  id="compraIcoTokensBonusBRL"></span>  <?php echo $idioma->getText("compraico5") ?> (<?php echo number_format($faseAtual->bonus, 2, ",", "")?>%).
                            </p>
                        </div>
                    </div>


                </div>

                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    
    <div class="row">
        <div class="col-lg-12">
            <div class="contact-box">

                <div class="col-sm-3">
                    <div class="text-center">
                        <img alt="image" class="img-circle m-t-xs img-responsive" style="max-width: 80px; max-height: 80px;" src="<?php echo IMAGES .  "currencies/BTC.png" ?>">
                    </div>
                </div>
                <div class="col-sm-5">
                    <h3><strong><?php echo $idioma->getText("compraico2") ?> Bitcoin</strong></h3>
                    <p>
                        <?php echo number_format($precoBitcoin, 8, ".", "")?> BTC = 1 NEWC Token
                    </p>
                    <h4><strong><?php echo $idioma->getText("compraico7") ?>  <?php echo number_format($saldoBitcoin, 8, ".", "")?> BTC</strong></h4>
                </div>

                <div class="col-sm-4">
                    <label><?php echo $idioma->getText("compraico3") ?> BTC: </label>
                    <div class="input-group">
                        <input type="text" class="form-control votacao" id="compraIcoAmountBTC"> 
                        <span class="input-group-btn"> 
                            <button type="button" onclick="modalComprar('BTC');" class="btn btn-success"><?php echo $idioma->getText("compraico6") ?>  BTC</button>  
                        </span>
                    </div>

                    <div class="row mt-2">
                        <div class="col-xs-12">
                            <p>
                                <?php echo $idioma->getText("compraico4") ?> <span  id="compraIcoTokensCompradosBTC"></span> NEWC.
                                + <span  id="compraIcoTokensBonusBTC"></span>  <?php echo $idioma->getText("compraico5") ?> (<?php echo number_format($faseAtual->bonus, 2, ",", "")?>%).
                            </p>
                        </div>
                    </div>


                </div>

                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    
    
    <div class="row">
        <div class="col-lg-12">
            <div class="contact-box">

                <div class="col-sm-3">
                    <div class="text-center">
                        <img alt="image" class="img-circle m-t-xs img-responsive" style="max-width: 80px; max-height: 80px;" src="<?php echo IMAGES .  "currencies/LTC.png" ?>">
                    </div>
                </div>
                <div class="col-sm-5">
                    <h3><strong><?php echo $idioma->getText("compraico2") ?> Litecoin</strong></h3>
                    <p>
                        <?php echo number_format($precoLitecoin, 8, ".", "")?> LTC = 1 NEWC Token
                    </p>
                    <h4><strong><?php echo $idioma->getText("compraico7") ?>  <?php echo number_format($saldoLitecoin, 8, ".", "")?> LTC</strong></h4>

                </div>

                <div class="col-sm-4">
                    <label><?php echo $idioma->getText("compraico3") ?> LTC: </label>
                    <div class="input-group">
                        <input type="text" class="form-control votacao" id="compraIcoAmountLTC"> 
                        <span class="input-group-btn"> 
                            <button type="button" onclick="modalComprar('LTC');" class="btn btn-success"><?php echo $idioma->getText("compraico6") ?> LTC</button> 
                        </span>
                    </div>

                    <div class="row mt-2">
                        <div class="col-xs-12">
                            <p>
                                <?php echo $idioma->getText("compraico4") ?> <span  id="compraIcoTokensCompradosLTC"></span> NEWC.
                                + <span  id="compraIcoTokensBonusLTC"></span> <?php echo $idioma->getText("compraico5") ?> (<?php echo number_format($faseAtual->bonus, 2, ",", "")?>%).
                            </p>
                        </div>
                    </div>


                </div>

                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    
    
    <div class="row">
        <div class="col-lg-12">
            <div class="contact-box">

                <div class="col-sm-3">
                    <div class="text-center">
                        <img alt="image" class="img-circle m-t-xs img-responsive" style="max-width: 80px; max-height: 80px;" src="<?php echo IMAGES .  "currencies/DASH.png" ?>">
                    </div>
                </div>
                <div class="col-sm-5">
                    <h3><strong><?php echo $idioma->getText("compraico2") ?> DASH</strong></h3>
                    <p>
                        <?php echo number_format($precoDash, 8, ".", "")?> DASH = 1 NEWC Token
                    </p>
                    <h4><strong><?php echo $idioma->getText("compraico7") ?>  <?php echo number_format($saldoDash, 8, ".", "")?> DASH</strong></h4>

                </div>

                <div class="col-sm-4">
                    <label><?php echo $idioma->getText("compraico3") ?> DASH: </label>
                    <div class="input-group">
                        <input type="text" class="form-control votacao" id="compraIcoAmountDASH"> 
                        <span class="input-group-btn"> 
                            <button type="button" onclick="modalComprar('DASH');" class="btn btn-success"><?php echo $idioma->getText("compraico6") ?> DASH</button> 
                        </span>
                    </div>

                    <div class="row mt-2">
                        <div class="col-xs-12">
                            <p>
                                <?php echo $idioma->getText("compraico4") ?> <span  id="compraIcoTokensCompradosDASH"></span> NEWC.
                                + <span  id="compraIcoTokensBonusDASH"></span> <?php echo $idioma->getText("compraico5") ?> (<?php echo number_format($faseAtual->bonus, 2, ",", "")?>%).
                            </p>
                        </div>
                    </div>


                </div>

                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    
    
    <div class="row">
        <div class="col-lg-12">
            <div class="contact-box">

                <div class="col-sm-3">
                    <div class="text-center">
                        <img alt="image" class="img-circle m-t-xs img-responsive" style="max-width: 80px; max-height: 80px;" src="<?php echo IMAGES .  "currencies/ETH.png" ?>">
                    </div>
                </div>
                <div class="col-sm-5">
                    <h3><strong><?php echo $idioma->getText("compraico2") ?> Ethereum</strong></h3>
                    <p>
                        <?php echo number_format($precoEthereum, 8, ".", "")?> ETH = 1 NEWC Token
                    </p>
                    <h4><strong><?php echo $idioma->getText("compraico7") ?>  <?php echo number_format($saldoEthereum, 8, ".", "")?> ETH</strong></h4>

                </div>

                <div class="col-sm-4">
                    <label><?php echo $idioma->getText("compraico3") ?> ETH: </label>
                    <div class="input-group">
                        <input type="text" class="form-control votacao" id="compraIcoAmountETH"> 
                        <span class="input-group-btn"> 
                            <button type="button" onclick="modalComprar('ETH');" class="btn btn-success"><?php echo $idioma->getText("compraico6") ?> ETH</button> 
                        </span>
                    </div>

                    <div class="row mt-2">
                        <div class="col-xs-12">
                            <p>
                                <?php echo $idioma->getText("compraico4") ?> <span  id="compraIcoTokensCompradosETH"></span> NEWC.
                                + <span  id="compraIcoTokensBonusETH"></span> <?php echo $idioma->getText("compraico5") ?> (<?php echo number_format($faseAtual->bonus, 2, ",", "")?>%).
                            </p>
                        </div>
                    </div>

                </div>

                <div class="clearfix"></div>
            </div>
        </div>
    </div>
          
</div>



<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>


<?php Utils\Layout::append("mensage_text", $_data) ?>



<script>
    
    var precoBitcoin = <?php echo number_format($precoBitcoin, 8, ".", "")?>;
    var precoLitecoin = <?php echo number_format($precoLitecoin, 8, ".", "")?>;
    var precoDash = <?php echo number_format($precoDash, 8, ".", "")?>;
    var precoEthereum = <?php echo number_format($precoEthereum, 8, ".", "")?>;
    var precoReais = <?php echo number_format($precoReais, 4, ".", "")?>;
    
    var bonificacao = <?php echo number_format($faseAtual->bonus, 2, ".", "")?>;
    
    $(document).ready(function () {
        
        
        $("#compraIcoAmountETH").keydown(function (event) {
            $(this).val(currency($(this).val(), 8, 8, event.keyCode));
            calcularVolumeTokens("ETH");
            event.preventDefault();
        });
        
        $("#compraIcoAmountBTC").keydown(function (event) {
            $(this).val(currency($(this).val(), 8, 8, event.keyCode));
            calcularVolumeTokens("BTC");
            event.preventDefault();
        });
        
        
        $("#compraIcoAmountDASH").keydown(function (event) {
            $(this).val(currency($(this).val(), 8, 8, event.keyCode));
            calcularVolumeTokens("DASH");
            event.preventDefault();
        });
        
        $("#compraIcoAmountLTC").keydown(function (event) {
            $(this).val(currency($(this).val(), 8, 8, event.keyCode));
            calcularVolumeTokens("LTC");
            event.preventDefault();
        });
        
        $("#compraIcoAmountBRL").keydown(function (event) {
            $(this).val(currency($(this).val(), 4, 8, event.keyCode));
            calcularVolumeTokens("BRL");
            event.preventDefault();
        });
        
        function calcularVolumeTokens(moeda) {
            var preco = 0;
            var amount = parseFloat($("#compraIcoAmount"+moeda).val().length > 0 ? $("#compraIcoAmount"+moeda).val().replace(",", ".") : 0);
            
            switch(moeda) {
                case "BTC": preco = precoBitcoin; break;
                case "LTC": preco = precoLitecoin; break;
                case "DASH": preco = precoDash; break;
                case "ETH": preco = precoEthereum; break;
                case "BRL": preco = precoReais; break;
            }
            
            var vol = parseFloat(amount / preco);
            var bonus = (vol * bonificacao / 100);
            
            $("#compraIcoTokensComprados"+moeda).html(vol.toFixed(8));
            $("#compraIcoTokensBonus"+moeda).html(bonus.toFixed(8));
        }
        
    });
    
    
    
    function modalComprar(moeda) {
        var preco = 0;
        var amount = parseFloat($("#compraIcoAmount"+moeda).val().length > 0 ? $("#compraIcoAmount"+moeda).val().replace(",", ".") : 0);
        var img = "";

        switch(moeda) {
            case "BTC": 
                img = "<?php echo IMAGES ?>currencies/BTC.png";
                preco = precoBitcoin; 
                break;
            case "LTC": 
                img = "<?php echo IMAGES ?>currencies/LTC.png";
                preco = precoLitecoin; 
                break;
            case "DASH": 
                img = "<?php echo IMAGES ?>currencies/DASH.png";
                preco = precoDash; 
                break;
            case "ETH": 
                img = "<?php echo IMAGES ?>currencies/ETH.png";
                preco = precoEthereum; 
                break;
            case "BRL": 
                img = "<?php echo IMAGES ?>currencies/BRL.png";
                preco = precoReais; 
                break;
        }

        var vol = parseFloat(amount / preco);
        var bonus = (vol * bonificacao / 100);
        
        var valido = true;
        var error = "";
        
        if (!amount > 0) {
            valido = false;
            error = "<?php echo $idioma->getText("compraico13") ?>";
            error = error.replace("{var1}", moeda);
        } else if (!vol > 0) {
            valido = false;
            error = "<?php echo $idioma->getText("compraico14") ?>";
        }
        
        if (valido) {
            var msg1 = "<?php echo $idioma->getText("compraico11") ?>";
            var msg2 = "<?php echo $idioma->getText("compraico12") ?>";

            msg1 = msg1.replace("{var1}", vol.toFixed(8)).replace("{var2}", amount.toFixed(8)).replace("{var3}", moeda);
            msg2 = msg2.replace("{var1}", bonus.toFixed(8));

           $("#modalComprarIcoImg").attr("src", img);
           $("#modalComprarIcoMsg").html(msg1);
           $("#modalComprarIcoMsg2").html(msg2);
           $("#modalComprarIcoMoeda").val(moeda);
           $("#modalComprarIcoVolume").val(amount);
           $("#modalComprarIco").modal();
       } else {
           showNotyAlert(error, "e");
       }
    }
    
    
    function confirmarCompra() {
        $("#modalComprarIcoCancelar, #modalComprarIcoConfirmar").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Rotas::R_BOOK_ICO_COMPRAR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                moeda: $("#modalComprarIcoMoeda").val(),
                volume: $("#modalComprarIcoVolume").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        
                        $("#modalComprarIcoCancelar").prop("disabled", false).trigger("click");
                        
                        showNotyAlert(json.mensagem, "s");
                        
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#modalComprarIcoCancelar, #modalComprarIcoConfirmar").prop("disabled", false);
            }
        });
    }
    
    
    
</script>


<div class="modal inmodal" id="modalComprarIco" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content animated bounceInRight">
            <div class="modal-header">
                
                <h4 class="modal-title "><?php echo $idioma->getText("compraico10") ?></h4>
            </div>
            <div class="modal-body">
                
                <input type="hidden" id="modalComprarIcoMoeda"  />
                <input type="hidden" id="modalComprarIcoVolume"  />
                
                <div class="row">
                    <div class="col col-lg-6 text-center">
                        <img src="" id="modalComprarIcoImg" style="max-width: 140px; max-height: 140px;" />
                    </div>
                    <div class="col col-lg-6 text-center">
                        <img src="<?php echo IMAGES ?>currencies/NEWC.png"  style="max-width: 160px; max-height: 160px;" />
                    </div>
                </div>
                <br>
                <div class="row ">
                    <div class="col col-xs-12">
                        
                        <p id="modalComprarIcoMsg"></p>
                        <p id="modalComprarIcoMsg2"></p>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <div class="col-lg-6 col-xs-12 m-t-xs">
                    <button type="button" class="btn btn-white full-width" data-dismiss="modal" id="modalComprarIcoCancelar"><?php echo $idioma->getText("compraico8") ?></button>
                </div>
                <div class="col-lg-6 col-xs-12 m-t-xs">
                    <button type="button" class="btn btn-success full-width" onclick="confirmarCompra();"  id="modalComprarIcoConfirmar"><?php echo $idioma->getText("compraico9") ?></button>
                </div>
            </div>
        </div>
    </div>
</div>
