<?php

$paridades = (isset($_data["paridades"]) ? $_data["paridades"]: Array() );

$casasDecimais = (isset($_data["casasDecimais"]) ? $_data["casasDecimais"]  : 2);
$dataInicial = new \Utils\Data(date("d/m/Y H:i:s"));
$dataInicial->subtrair(0, 1, 0);
$dataFinal = new \Utils\Data(date("d/m/Y H:i:s"));

$taxaCompra = (isset($_data["compra"]) ? $_data["compra"] : 0);
$taxaVenda = (isset($_data["venda"]) ? $_data["venda"] : 0);

$paridade = Modules\principal\Controllers\Principal::getParity();
$cliente = Utils\Geral::getCliente();
$mostrarBotoes = ($paridade->ativo > 0 && $paridade->statusMercado > 0 && $cliente->statusMercado > 0 && $paridade->moedaBook->statusMercado > 0 && $paridade->moedaBook->ativo > 0);
$mostrarAlerta = false;
$mensagemAlerta = "";

$idioma = new \Utils\PropertiesUtils("compra_venda_direta", IDIOMA);

if ($paridade->ativo < 1 || $paridade->moedaBook->ativo < 1) {
    $mostrarAlerta = true;
    $mensagemAlerta = $idioma->getText("mercadoEncerrado");
} else if ($paridade->statusMercado < 1 || $paridade->moedaBook->statusMercado < 1) {
    $mostrarAlerta = true;
    $mensagemAlerta = $idioma->getText("mercadoSupenso");
} else if ($cliente->statusMercado < 1) {
    $mensagemAlerta = $idioma->getText("compraVendaSuspensaConta");
    $mostrarAlerta = true;
}

$_data["idiomaMenu"] = $idioma;
?>
<style>
    .border-edit {
        border: 1px solid #1c84c6 !important;
    }
    .row.vdivide [class*='col-']:not(:last-child):after {
    background: #e0e0e0;
    content: "";
    display:block;
    position: absolute;
    top:0;
    bottom: 0;
    right: 0;
    min-height: 50px;
    }
    
    .row.vdivide1 [class*='col-']:not(:last-child):after {
    background: #1c84c6;
    width: 2px;
    content: "";
    display:block;
    position: absolute;
    top:0;
    bottom: 0;
    right: 0;
    min-height: 200px;
    }
    
    .fh-column {
    background: none !important;
    width: 100% !important;
    float: left !important;
    }
    .linkActive {
    font-size: 20px;
    font-weight: bold;
    cursor: default;
    }
   .verticalText {
    vertical-align:middle;
    height:50px;
    display:flex;
    justify-content:center;
    align-items: center;
   }
   .ontent-btnbuysell {
   height:50px;
   }
   .content-buysell {
    height:200px;
    border-bottom: 1px solid #e7eaec;
   }
   .content-orders {
    height: calc(100% - 251px)!important;
    border-bottom: 2px solid #e7eaec;
    overflow: hidden !important;
   }
    .my-custom-scrollbar {
    position: relative;
    height: 100%;
    overflow: hidden !important;
    }
    html, body {
    overflow: hidden !important;
    }
    .full-height-scroll{

    }
    .fix{
        overflow: hidden;
    }
    
    .mycoins{
    height: calc(47% - 25px);
    border-bottom: 1px solid #e7eaec;
    }
    
    .mybalance{
    height: calc(44% - 25px);
    border-bottom: 1px solid #e7eaec;
    }
    
    .tbody-h {
        display:block;
        height:320px;
        overflow:auto;
    }        
    .tbody-saldo {
        display:block;
        height:259px;
        overflow:auto;
    }
    
    .thead-h, .tbody-h1 .tr-h {
        display:table;
        width:100%;
        table-layout:fixed;
    }
    .thead-h1 {
        width: calc( 100% - 1em )
    }
    
    .page_content{
      width:2048px;
      height:1024px;

      -ms-transform-origin: top left;
      -webkit-transform-origin: top left;
      transform-origin: top left;
      -webkit-transition: all 500ms ease-in-out !important;
    }
    
    .orders{
        height: 60.8%;
    }
    
    .historico{
        height: 70.3%;
    }


</style>
<?php Utils\Layout::append("inspina/metas", $_data) ?>
<?php Utils\Layout::append("inspina/scripts", $_data) ?>
<?php Utils\Layout::append("inspina/menu", $_data) ?>

<div id="container">
    <div class="page_content">
<div class="row row-fluid">
    <div class="col col-lg-4">
        <div class="fh-column">
            <div class="row mycoins">
                <div class="ibox">
                    <div class="ibox-title">
                        <h3 style="display: inline;"><strong><?php echo $idioma->getText("direta28") ?> - <?php echo $paridade->symbol ?></strong>
                    </div>
                    <div class="ibox-content no-padding">
                        <div class="row" style="padding-top: 10px; padding-right: 15px;">                            
                            <div class="col col-md-5">
                                <div class="form-group">
                                    <div class="input-group" style="padding-left: 15px;">
                                        <input type="text" class="form-control input-sm" id="ticker-search" />
                                        <span class="input-group-addon">
                                            <i class="fa fa-search"></i>
                                        </span>
                                    </div>
                                </div>
                            </div>
                            <div class="col col-md-5">
                                <div class="form-group">
                                    <select class="form-control input-sm" id="ticker-paridade">
                                        <?php
                                        foreach ($paridades as $moedaTrade) {
                                            $selected = ($paridade->idMoedaTrade == $moedaTrade->id);
                                            ?>
                                            <option value="<?php echo $moedaTrade->id ?>" <?php echo ($selected ? "selected" : "") ?> ><?php echo $moedaTrade->nome ?></option>
                                            <?php
                                        }
                                        ?>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-2">
                                <button class="btn btn-white text-warning btn-sm"  onclick="setSomenteFavoritas();">
                                        <i class="fa fa-star-o" id="filtro-favoritas" style="font-size: 20px; color: gray;"></i>
                                    </button>
                            </div>
                        </div>

                        <div class="table-responsive paridade" style="">
                            <table style="font-size: 14px;" class="table table-striped" id="tickers-table">
                                <thead class="thead-h thead-h1">
                                    <tr class="tr-h">                                        
                                        <th class="text-center" style="width: 20% !important;"><?php echo $idioma->getText("direta22") ?></th>
                                        <th class="text-right" style="width: 25% !important;"><?php echo $idioma->getText("direta4") ?></th>
                                        <th class="text-right" style="width: 20% !important;">%</th>
                                        <th class="text-right" style="width: 20% !important;">Volume</th>
                                        <th class="text-center" style="width: 15% !important;"></th>
                                    </tr>
                                </thead>
                                <tbody id="body-paridades" class="tbody-h tbody-h1" style="cursor: pointer;">

                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>

            </div>
            <div class="row mybalance" style="background-color: #FFFFFF">
                <div class="ibox">
                    <div class="ibox-title">
                        <h3><strong><?php echo $idioma->getText("direta24") ?></strong></h3>
                    </div>
                    <div class="ibox-content no-padding">
                        <div class="row" style="padding-left: 15px; padding-top: 15px;">
                            <div class="col col-md-8">
                                <div class="form-group">
                                    <div class="input-group">
                                        <input type="text" class="form-control input-sm" id="balances-search" />
                                        <span class="input-group-addon">
                                            <i class="fa fa-search"></i>
                                        </span>
                                    </div>
                                </div>
                            </div>

                            <div class="col col-md-4 text-right" style="padding-right: 30px;">
                                
                            </div>
                        </div>
                        <div class="row">
                            <div class="col col-xs-12">
                                <div class="table-responsive saldo">
                                    <table style="font-size: 14px;" class="table table-hover table-condensed table-striped ">
                                        <thead class="thead-h thead-h1">
                                            <tr class="tr-h">
                                                <th class="text-left" style="padding-left: 28px !important; width: 44%">
                                                    <?php echo $idioma->getText("direta22") ?>
                                                </th>
                                                <th class="text-right" style="width: 150px;">
                                                    <?php echo $idioma->getText("direta29") ?>
                                                </th>
                                                <th class="text-right" style="width: 130px;">
                                                    <?php echo $idioma->getText("direta23") ?>
                                                </th>
                                            </tr>
                                        </thead>
                                        <tbody id="body-balances" class="tbody-h tbody-saldo" >
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>  
            </div>
        </div> 
    </div>    
    
    
    <div class="col col-md-8  ">
        
        <?php if ($mostrarAlerta) { ?>
        <div class="alert alert-warning text-center">
            <h4><i class="fa fa-exclamation-triangle fa-2x" ></i> &nbsp;&nbsp; <span ><?php echo $mensagemAlerta ?> </span></h4>
        </div>
        <?php } ?>        
        <div class="">
            <div class="">
                <div class="tabs-container">
                    <ul class="nav nav-tabs content-btnbuysell " >
                        <div class="row vdivide " >
                            <div class="col-sm-4" data-toggle="tab" href="#tab-1" id="tab-compra" class="linkActive">
                                <span class="verticalText centralizado">
                                    <?php echo $idioma->getText("comprar") ?> <?php echo $paridade->moedaBook->nome ?>
                                </span>
                            </div>
                            <div class="col-sm-4" data-toggle="tab" href="#tab-2" id="tab-venda">
                                <span class="verticalText">
                                    <?php echo $idioma->getText("vender") ?> <?php echo $paridade->moedaBook->nome ?>
                                </span>
                            </div> 
                            <div class="col-sm-4" data-toggle="tab" href="#tab-3" id="tab-historico">
                                <span class="verticalText">
                                    <?php echo $idioma->getText("direta27") ?>
                                </span>
                            </div>
                         </div>  
                    </ul>
                    <div class="tab-content ">
                        <div id="tab-1" class="tab-pane active m-t-md"> 
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="panel">
                                        <div class="panel-body">
                                            <div class="row">
                                                <div class="col-lg-4">
                                                    <div class="form-group">
                                                        <label><?php echo $idioma->getText("valorTotal") ?>: <?php echo $paridade->moedaTrade->nome ?></label>
                                                        <div class="input-group">                                               
                                                            <input type="text" class="form-control real" id="buytotal"  data-base=""> 
                                                            <span class="input-group-btn" > <button type="button" class="btn btn-default" onclick="initbuysell('b', 'a');"><?php echo $idioma->getText("direta26") ?></button>
                                                        </div> 
                                                    </div>
                                                </div>
                                                <div class="col-lg-4">
                                                    <div class="form-group">
                                                        <label><?php echo $idioma->getText("preco") ?>: <?php echo $paridade->moedaTrade->nome ?></label>                                                         
                                                        <input type="text" class="form-control digital-currency"  disabled id="buyprice" data-ref="">
                                                    </div>
                                                </div>
                                                <div class="col-lg-4">
                                                    <div class="form-group">
                                                        <label>&nbsp;</label>
                                                    <?php if (\Models\Modules\Acesso\RotinaRn::validar(\Utils\Rotas::R_MERCADO, \Utils\Constantes::CADASTRAR)) { ?>
                                                        <?php if ($mostrarBotoes) { ?>
                                                            <button type="button" class="btn btn-primary full-width" id="btn-order-buy" onclick="salvarOrdemCompra();">
                                                                <?php echo $idioma->getText("compraDiretaBtn") ?>
                                                            </button>
                                                        <?php } ?>
                                                    <?php } ?>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="panel-footer">
                                            <div class="row">
                                                <div class="col-lg-4">
                                                    <p><?php echo $idioma->getText("receberaAprox") ?>: <span class="real" id="buyreceive" ></span></p>
                                                </div>
                                                <div class="col-lg-4">
                                                    <p><?php echo $idioma->getText("direta18") ?>: <span id="label-taxa-compra"></span></p>
                                                </div>
                                                <div class="col-lg-4">
                                                    <p><?php echo $idioma->getText("direta19") ?>: <span id="label-estimativa-taxa-compra"></span></p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div id="tab-2" class="tab-pane m-t-md">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="panel">
                                        <div class="panel-body">
                                            <div class="row">
                                                <div class="col-lg-4">
                                                    <div class="form-group">
                                                        <label><?php echo $idioma->getText("volumeVender")  ?>: <?php echo $paridade->moedaBook->nome ?></label>
                                                        <div class="input-group m-b">
                                                            <input type="text" class="form-control digital-currency" id="sellamount"> 
                                                            <span class="input-group-addon"  onclick="initbuysell('s', 'a');" style="cursor: pointer;"><?php echo $idioma->getText("direta26") ?></span>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-lg-4">
                                                    <div class="form-group">
                                                        <label><?php echo $idioma->getText("precoMedio")  ?>: <?php echo $paridade->moedaTrade->nome ?></label>                                                        
                                                        <input type="text" class="form-control real" id="sellprice" disabled data-base="">  
                                                    </div>
                                                </div>
                                                <div class="col-lg-4">
                                                    <div class="form-group">
                                                        <label>&nbsp;</label>
                                                        <?php if (\Models\Modules\Acesso\RotinaRn::validar(\Utils\Rotas::R_MERCADO, \Utils\Constantes::CADASTRAR)) { ?>
                                                        <?php if ($mostrarBotoes) { ?>
                                                        <button type="button" class="btn btn-danger full-width" id="btn-order-sell" onclick="salvarOrdemVenda();">
                                                            <?php echo $idioma->getText("vendaDiretaBtn") ?>
                                                        </button>
                                                        <?php } ?>
                                                        <?php } ?>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="panel-footer">
                                            <div class="row">
                                                <div class="col-lg-4">
                                                    <p><?php echo $idioma->getText("receberaAproxVender") ?>: <span class="real" id="sellreceive" ></span> </p>
                                                </div>
                                                <div class="col-lg-4">
                                                    <p><?php echo $idioma->getText("direta18") ?>: <span id="label-taxa-venda"></span></p>
                                                </div>
                                                <div class="col-lg-4">
                                                    <p><?php echo $idioma->getText("direta19") ?>: <span id="label-estimativa-taxa-venda"></span></p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>                        
                        <div id="tab-3" class="tab-pane m-t-md">
                            <div class="panel">
                                <div class="panel-body">
                                    <div class="row ">
                                        <div class="col-sm-3 m-b-xs">
                                            <div data-toggle="buttons" class="btn-group" id="radioTipoBtc">
                                                <label class="btn btn-sm btn-white" id="compraBtc"> <input type="radio"  name="optionsBtc" value="compra"><?php echo $idioma->getText("direta11") ?></label>
                                                <label class="btn btn-sm btn-white" id="vendaBtc"> <input type="radio" name="optionsBtc" value="venda"><?php echo $idioma->getText("direta12") ?></label>
                                                <label class="btn btn-sm btn-white active" id="todosBtc"> <input type="radio" id="" name="optionsBtc" value="todos"><?php echo $idioma->getText("direta13") ?></label>
                                            </div>
                                        </div>
                                        <div class="col-sm-6 m-b-xs">
                                            <div data-toggle="buttons" class="btn-group" id="radioDatas">
                                                <label class="btn btn-sm btn-white" id="diaBtc"> <input type="radio" name="optionsBtc" value="dia"><?php echo $idioma->getText("direta7") ?></label>
                                                <label class="btn btn-sm btn-white active" id="semanaBtc"> <input type="radio"  name="optionsBtc" value="semana"><?php echo $idioma->getText("direta8") ?></label>
                                                <label class="btn btn-sm btn-white" id="mesBtc"> <input type="radio" name="optionsBtc" value="mes"><?php echo $idioma->getText("direta9") ?></label>
                                                <label class="btn btn-sm btn-white" id="todosDataBtc"> <input type="radio"  name="optionsBtc" value="todos"><?php echo $idioma->getText("direta10") ?></label>
                                            </div>
                                        </div>
                                        <div class="col-sm-3">
                                            <div class="input-group">
                                                <input type="text" id="filterorders" placeholder="<?php echo $idioma->getText("pesquisar") ?>" class="input-sm form-control">
                                                <span class="input-group-btn">
                                                    <button type="button" class="btn btn-sm btn-primary" onclick="listarMinhasOrdens();">&nbsp;<i class="fa fa-search"></i></button>
                                                    <button type="button" class="btn btn-sm btn-default" onclick="limpaSearch();">&nbsp;<i class="fa fa-eraser"></i></button>
                                                </span>
                                            </div>
                                        </div>                                
                                    </div>
                                </div>
                            </div>                                                        
                            <div class="table-wrapper-scroll-y my-custom-scrollbar" style="margin-top: -15px;">
                                </br>
                                <div class="ibox-content historico">
                                    <table id="tblMyOrders" class="footable table table-stripped" data-page-size="22" data-filter=#filterorders style="font-size: 11px;">
                                        <thead>
                                            <tr>
                                                <th class="text-center"><?php echo $idioma->getText("direta1") ?></th>
                                                <th class="text-center"><?php echo $idioma->getText("direta2") ?></th>
                                                <th class="text-center"><?php echo $idioma->getText("direta3") ?></th>
                                                <th class="text-center"><?php echo $idioma->getText("direta4") ?></th>
                                                <th class="text-center"><?php echo $idioma->getText("direta5") ?></th>
                                                <th class="text-center"><?php echo $idioma->getText("direta6") ?></th>					
                                            </tr>
                                        </thead> 
                                        <tbody id="listaMyOrders">
                                        </tbody>
                                        <tfoot class="">
                                            <tr>
                                                <td colspan="6">
                                                    <ul class="pagination pull-right"></ul>
                                                </td>
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div>
                            </div>
                        </div>
                         </br>
                         <div class="">
                                 <div class="row m-t-lg text-center" id="book" style="margin-top: -10px;">
                                     <div class="col-lg-6 text-center">                                         
                                         <div class="ibox-content orders">
                                             <h3 style="color: #1ab394;"><?php echo $idioma->getText("direta20") ?></h3>
                                             <table class="table table-striped" style="font-size: 11px;">
                                                 <thead>
                                                     <tr>
                                                         <th class="text-center " style="max-width: 100% !important;"><?php echo $idioma->getText("direta30") ?></th>
                                                         <th class="text-center " style="max-width: 100% !important;"><?php echo $idioma->getText("direta14") ?></th>
                                                         <th class="text-center " style="max-width: 100% !important;"><?php echo $idioma->getText("direta16") ?></th>
                                                     </tr>
                                                 </thead>
                                                 <tbody id="tabelaBookCompra">                                        
                                                 </tbody>
                                             </table>
                                         </div> 
                                         </br></br>
                                     </div>
                                     <div class="col-lg-6 text-center">                                         
                                         <div class="ibox-content orders">
                                             <h3 style="color: #ed5565;"><?php echo $idioma->getText("direta25") ?></h3>
                                             <table class="table table-striped" style="font-size: 11px;">
                                                 <thead>
                                                     <tr>
                                                         <th class="text-center " style="max-width: 100% !important;"><?php echo $idioma->getText("direta30") ?></th>
                                                         <th class="text-center " style="max-width: 100% !important;"><?php echo $idioma->getText("direta14") ?></th>
                                                         <th class="text-center " style="max-width: 100% !important;"><?php echo $idioma->getText("direta17") ?></th>
                                                     </tr>
                                                 </thead>
                                                 <tbody id="tabelaBookVenda">                                        
                                                 </tbody>
                                             </table>
                                         </div>  
                                     </div>
                             </div>
                         </div>
                         </br>
                    </div>
                </div>                
            </div>
        </div>
    </div>
    
</div>
    </div>
</div>
        <div></br></br></br></div>
        
        <?php Utils\Layout::append("inspina/footer_esp", $_data) ?>
        <script src="<?php echo JS; ?>underscore-min.js"></script>
        <script>
            var amountCompra = 0;
            var amountVenda = 0;
            var precoCompra = 0;
            var precoVenda = 0;
            var somenteFavoritas = false;
            var casasDecimaisReal = <?php echo $casasDecimais ?>;
            var data = "semana";
            var tipo = "todos";
            var pageWidth, pageHeight;
            var basePage = {
                width: 2048,
                height: 1024,
                scale: 1,
                scaleX: 1,
                scaleY: 1
              };
            
            $(document).ready(function () {
                setInterval(listarParidadesBook, 4000);
                setInterval(listarSaldoMoedasBook, 3000);
                setInterval(listarBook, 6000);
                
                $("#radioDatas input").on('change', function(){
                    data = $('input[name="optionsBtc"]:checked', '#radioDatas').val();
                    listarMinhasOrdens();
                });
                
                $("#radioTipoBtc input").on('change', function(){
                    tipo = $('input[name="optionsBtc"]:checked', '#radioTipoBtc').val();
                    listarMinhasOrdens();
                });
                
                $('#tblMyOrders').footable();
                $("#tab-compra").addClass("linkActive");
                $("#tab-venda").css( 'cursor', 'pointer' );
                $("#tab-compra").css( 'background-color', '#dcdcdc' );
                
                
                
                $(".real").each(function () {
                    currencymask($(this), 8, casasDecimaisReal, ",");
                });
                $(".digital-currency").each(function () {
                    currencymask($(this), 8, <?php echo $paridade->moedaBook->casasDecimais ?>, ",");
                });
                $("#buytotal").keyup(function () {
                    consultarPreco('<?php echo \Utils\Constantes::ORDEM_COMPRA ?>');
                });
                $("#sellamount").keyup(function () {
                    consultarPreco('<?php echo \Utils\Constantes::ORDEM_VENDA ?>');
                });
               
               $("#ticker-paridade").change(function () {
                    listarParidadesBook();
                }); 

                $("#ticker-search").keyup(function () {
                    filtrarParidadesBook();
                });

                $("#balances-search").keyup(function () {
                    filtrarMoedasBook();
                });
                
                $("#btn-blocked-balance-show").click(function () {
                    $(".table-blocked-balance").show();
                    balanceMode = 1;
                });

                $("#btn-blocked-balance-hide").click(function () {
                    $(".table-blocked-balance").hide();
                    balanceMode = 2;
                });

            });
            
            $(function(){
            var $page = $('.page_content');

            getPageSize();
            scalePages($page, pageWidth, pageHeight);
            $(window).resize(_.debounce(function () {
              getPageSize();            
              scalePages($page, pageWidth, pageHeight);
            }, 150));


          function getPageSize() {
            pageHeight = $('#container').height();
            pageWidth = $('#container').width();
          }

          function scalePages(page, maxWidth, maxHeight) {                              
            scaleX = maxWidth / basePage.width;
            scaleY = maxHeight / basePage.height;
            basePage.scaleX = scaleX;
            basePage.scaleY = scaleY;
            basePage.scale = (scaleX > scaleY) ? scaleY : scaleX;

            var newLeftPos = Math.abs(Math.floor(((basePage.width * basePage.scale) - maxWidth)/2));
            var newTopPos = Math.abs(Math.floor(((basePage.height * basePage.scale) - maxHeight)/2));

            page.attr('style', '-webkit-transform:scale(' + basePage.scale + ');left:' + newLeftPos + 'px;top:' + newTopPos + 'px;');
          }
          });
            
            
            
            var balanceMode = 1;
    
            function mudarParidade(paridade) {
                $.ajax({
                    url: '<?php echo URLBASE_CLIENT . \Utils\Rotas::R_CURRENCY ?>',
                    dataType: 'json',
                    method: 'post',
                    data: {
                        codigo: paridade
                    },
                    beforeSend: function () {

                    },
                    success: function (json) {
                        try {
                            if (json.sucesso) {

                                location = location.href;

                            } else {
                                //console.log(json.mensagem);
                            }
                        } catch (e) {
                            //console.log(e);
                        }

                    },
                    complete: function () {

                    }
                });
            }
            
            function setSomenteFavoritas() {
                somenteFavoritas = !somenteFavoritas;

                if (somenteFavoritas) {
                    $("#filtro-favoritas").removeClass("fa-star-o").addClass("fa-star");
                } else {
                    $("#filtro-favoritas").removeClass("fa-star").addClass("fa-star-o");
                }

                filtrarParidadesBook();
            }

            function filtrarParidadesBook() {

                var filtro = $("#ticker-search").val().toLowerCase();

                $("#body-paridades tr").each(function () {
                    var mostrar = true;

                    if (filtro.length > 0) {
                        var name = $(this).children("td.column-paridade").first().attr("data-name").toLowerCase();
                        var content = $(this).children("td.column-paridade").first().html().toLowerCase();

                        var mostrar = (name.indexOf(filtro) !== -1 || content.indexOf(filtro) !== -1);

                    } 

                    if (mostrar && somenteFavoritas) {
                        mostrar = $(this).hasClass("favorite-parity");
                    }

                    if (mostrar) {
                        $(this).show();
                    } else {
                        $(this).hide();
                    }

                });

            }
            
            function filtrarMoedasBook() {
        
                var filtro = $("#balances-search").val().toLowerCase();

                $("#body-balances tr").each(function () {
                    if (filtro.length > 0) {
                        var name = $(this).children("td.column-balance").first().attr("data-name").toLowerCase();
                        var content = $(this).children("td.column-balance").first().html().toLowerCase();

                        if (name.indexOf(filtro) !== -1 || content.indexOf(filtro) !== -1) {
                            $(this).show();
                        } else {
                            $(this).hide();
                        }
                    } else {
                        $(this).show();
                    }
                });

            }
            
            var flagAddParidadeFavorita = true;
            function addFavorito(codigo) {
                if (flagAddParidadeFavorita) {
                    $.ajax({
                        url: '<?php echo URLBASE_CLIENT . \Utils\Rotas::R_BOOK_FAVORITO_ADD ?>',
                        dataType: 'json',
                        method: 'post',
                        data: {
                            paridade: codigo
                        },
                        beforeSend: function () {
                            flagAddParidadeFavorita = false;
                        },
                        success: function (json) {
                            try {
                                if (json.sucesso) {
                                    $("#btn-favorito-"+json.codigo).html(json.html);


                                } else {
                                    console.log(json.mensagem);
                                }
                            } catch (e) {
                                console.log(e);
                            }
                            flagAddParidadeFavorita = true;
                        },
                        complete: function () {
                            flagAddParidadeFavorita = true;
                        }
                    });
                }
            }
            
            var flagRemoverParidadeFavorita = true;
            function removerFavorito(codigo) {
                if (flagRemoverParidadeFavorita) {
                    $.ajax({
                        url: '<?php echo URLBASE_CLIENT . \Utils\Rotas::R_BOOK_FAVORITO_REMOVE ?>',
                        dataType: 'json',
                        method: 'post',
                        data: {
                            paridade: codigo
                        },
                        beforeSend: function () {
                            flagRemoverParidadeFavorita = false;
                        },
                        success: function (json) {
                            try {
                                if (json.sucesso) {
                                    $("#btn-favorito-"+json.codigo).html(json.html);


                                } else {
                                    console.log(json.mensagem);
                                }
                            } catch (e) {
                                console.log(e);
                            }
                            flagRemoverParidadeFavorita = true;
                        },
                        complete: function () {
                            flagRemoverParidadeFavorita = true;
                        }
                    });
                }
            }

            var flagParidadesBook = true;
            function listarParidadesBook() {
                if (flagParidadesBook) {
                    $.ajax({
                        url: '<?php echo URLBASE_CLIENT . \Utils\Rotas::R_BOOK_PARIDADES_LISTAR ?>',
                        dataType: 'json',
                        method: 'post',
                        data: {
                            moeda: $("#ticker-paridade").val()
                        },
                        beforeSend: function () {
                            flagParidadesBook = false;
                        },
                        success: function (json) {
                            try {
                                if (json.sucesso) {
                                    $("#body-paridades").html(json.html);

                                    $(".change-parity").each(function () {
                                        $(this).click(function () {
                                            var paridade = $(this).parent("tr").attr("data-paridade");
                                            mudarParidade(paridade);
                                        });
                                    });

                                    filtrarParidadesBook();
                                } else {
                                    console.log(json.mensagem);
                                }
                            } catch (e) {
                                console.log(e);
                            }
                            flagParidadesBook = true;
                        },
                        complete: function () {
                            flagParidadesBook = true;
                        }
                    });
                }
            }


            var flagSaldoMoedas = true;
            function listarSaldoMoedasBook() {

                if (flagSaldoMoedas) {
                    $.ajax({
                        url: '<?php echo URLBASE_CLIENT . \Utils\Rotas::R_BOOK_MOEDAS_SALDO ?>',
                        dataType: 'json',
                        method: 'post',
                        data: {
                            balanceMode: balanceMode
                        },
                        beforeSend: function () {
                            flagSaldoMoedas = false;
                        },
                        success: function (json) {
                            try {
                                if (json.sucesso) {
                                    $("#body-balances").html(json.html);

                                    if(balanceMode === 2) {
                                        $(".table-blocked-balance").hide();
                                    } else {
                                        $(".table-blocked-balance").show();
                                    }

                                    filtrarMoedasBook();
                                } else {
                                    console.log(json.mensagem);
                                }
                            } catch (e) {
                                console.log(e);
                            }
                            flagSaldoMoedas = true;
                        },
                        complete: function () {
                            flagSaldoMoedas = true;
                        }
                    });
                }
            }
            
            var flagListarBook = true;
            function listarBook() {
                if(flagListarBook){
                $.ajax({
                    url: '<?php echo URLBASE_CLIENT . \Utils\Rotas::R_MERCADO_LISTAR_BOOK?>',
                    method: 'post',
                    dataType: 'json',    
                    beforeSend: function () {
                            flagListarBook = false;
                        },
                    success: function (json) {
                        try {
                            if (json.sucesso) {
                                $("#tabelaBookCompra").html(json.htmlCompra); 
                                $("#tabelaBookVenda").html(json.htmlVenda); 
                            } else {
                                console.log(json.mensagem);
                            }
                        } catch (e) {
                            console.log(e);
                        }
                        flagListarBook = true;
                    },
                    complete: function () {
                        flagListarBook = true;
                    }
                });
                }
            }
            
            
            
            $("#tab-compra").click(function () {
                $("#book").show();
                $("#tab-venda").removeClass("linkActive");
                $("#tab-venda").css( 'cursor', 'pointer' );
                $("#tab-venda").css( 'background-color', '' );
                $("#tab-historico").removeClass("linkActive");
                $("#tab-historico").css( 'cursor', 'pointer' );
                $("#tab-historico").css( 'background-color', '' );
                $(this).addClass("linkActive");
                $("#tab-compra").css( 'cursor', 'default' );
                $("#tab-compra").css( 'background-color', '#dcdcdc' );
           });
                
                
            $("#tab-venda").click(function () {
                $("#book").show();
                $("#tab-historico").removeClass("linkActive");
                $("#tab-historico").css( 'cursor', 'pointer' );
                $("#tab-historico").css( 'background-color', '' );
                $("#tab-compra").removeClass("linkActive");
                $("#tab-compra").css( 'cursor', 'pointer' );
                $("#tab-compra").css( 'background-color', '' );
                $(this).addClass("linkActive");
                $("#tab-venda").css( 'cursor', 'default' );
                $("#tab-venda").css( 'background-color', '#dcdcdc' );
            });
            
            $("#tab-historico").click(function () {
                $("#book").hide();
                $("#tab-venda").removeClass("linkActive");
                $("#tab-venda").css( 'cursor', 'pointer' );
                $("#tab-venda").css( 'background-color', '' );
                $("#tab-compra").removeClass("linkActive");
                $("#tab-compra").css( 'cursor', 'pointer' );
                $("#tab-compra").css( 'background-color', '' );
                $(this).addClass("linkActive");
                $("#tab-historico").css( 'cursor', 'default' );
                $("#tab-historico").css( 'background-color', '#dcdcdc' );
                listarMinhasOrdens();
            });

            $("#dataInicial,#dataFinal").datepicker({
                format: "dd/mm/yyyy",
                todayBtn: "linked",
                language: "pt-BR",
                orientation: "top left",
                autoclose: true,
                todayHighlight: true,
                toggleActive: true
            });

            let buytax = <?php echo number_format($taxaCompra, 4, ".", "")?>;
            let selltax = <?php echo number_format($taxaVenda, 4, ".", "")?>;;

            function consultarPreco(tipo) {
                
                if (!calcularPrecoMedio(tipo)) {
                    
                    $("#label-taxa-compra").html("&nbsp;");
                    $("#label-taxa-venda").html("&nbsp;");
                    $("#btn-order-buy, #btn-order-sell").prop("disabled", true);
                    $.ajax({
                        url: '<?php echo URLBASE_CLIENT . \Utils\Rotas::R_MERCADO_PRECO ?>',
                        method: 'post',
                        dataType: 'json',
                        data: {
                            amount: (tipo === '<?php echo \Utils\Constantes::ORDEM_COMPRA ?>' ? $("#buytotal").val() : $("#sellamount").val()),
                            price: $("#buyprice").val(),
                            tipo: tipo
                        },
                        success: function (json) {
                            try {
                                if (json.sucesso) {

                                    if (tipo === '<?php echo \Utils\Constantes::ORDEM_COMPRA ?>') {
                                        amountCompra =json.volume;
                                        precoCompra = json.preco;

                                        $("#buyprice").val(json.preco);
                                        $("#buyamount").val(json.volume);
                                        $("#buyprice").attr("data-base", json.base);
                                        buytax = json.taxa;
                                        calcularSoma('b');
                                        $("#label-taxa-compra").html(json.taxa.replace(".", ",") + "%.");
                                    } else {
                                        precoVenda = json.preco;
                                        $("#sellprice").val(json.preco);
                                        $("#sellprice").attr("data-base", json.base);
                                        selltax = json.taxa;
                                        calcularSoma('s');
                                        $("#label-taxa-venda").html(json.taxa.replace(".", ",") + "%.");
                                    }

                                } else {
                                    showNotyAlert(json.mensagem, "e");
                                }
                            } catch (e) {
                                showNotyAlert(e, "e");
                            }
                        }
                    });
                    $("#btn-order-buy, #btn-order-sell").prop("disabled", false);
                }
            }



            function calcularSoma(m) {
                if (m === 'b') {
                    let receive = (amountCompra - (amountCompra * (buytax / 100)));
                    let receiveVolume = (amountCompra - receive);
                    $("#buyreceive").html(receive.toFixed(<?php echo $paridade->moedaBook->casasDecimais ?>).replace(".", ",") + " <?php echo $paridade->moedaBook->simbolo ?>");
                    $("#label-estimativa-taxa-compra").html(receiveVolume.toFixed(<?php echo $paridade->moedaBook->casasDecimais ?>).replace(".", ",") + " <?php echo $paridade->moedaBook->simbolo ?>");
                    
                } else {
                    let amount = ($("#sellamount").val().length > 0 ? parseFloat($("#sellamount").val().replace(",", ".")) : 0);
                    let total = amount * precoVenda;
                    $("#selltotal").val(total.toFixed(casasDecimaisReal).replace(".", ","));
                    let receive = (total - (total * (selltax / 100)));
                    $("#sellreceive").html(receive.toFixed(casasDecimaisReal).replace(".", ",") + " " + '<?php echo $paridade->moedaTrade->simbolo ?>');
                    $("#label-estimativa-taxa-venda").html((total - receive).toFixed(<?php echo $casasDecimais ?>).replace(".", ",") + " <?php echo $paridade->moedaTrade->simbolo ?>");
                }
            }
            
            function limpar(){
                $('#pesquisa').each (function(){
                this.reset();
                listarMinhasOrdens();
            });
    }

            function salvarOrdemCompra() {
                $("#btn-order-buy").prop("disabled", true);
                $.ajax({
                    url: '<?php echo URLBASE_CLIENT . \Utils\Rotas::R_MERCADO_COMPRAR ?>',
                    method: 'post',
                    dataType: 'json',
                    data: {
                        amount: amountCompra,
                        price: precoCompra,
                        reference: $("#buyprice").attr("data-base")
                    },
                    success: function (json) {
                        try {
                            if (json.sucesso) {
                                $("#buyamount, #buytotal, #buyreceive, #buyprice").val('');
                                listarMinhasOrdens();
                                showNotyAlert(json.mensagem, "s");
                            } else {
                                showNotyAlert(json.mensagem, "e");
                            }
                            
                        } catch (e) {
                        }
                        $("#btn-order-buy").prop("disabled", false);
                    }
                });
            }

            function salvarOrdemVenda() {
                $("#btn-order-sell").prop("disabled", true);
                $.ajax({
                    url: '<?php echo URLBASE_CLIENT . \Utils\Rotas::R_MERCADO_VENDER ?>',
                    method: 'post',
                    dataType: 'json',
                    data: {
                        amount: $("#sellamount").val(),
                        price: $("#sellprice").val()
                    },
                    success: function (json) {
                        try {
                            if (json.sucesso) {
                                $("#sellamount, #selltotal, #sellreceive, #sellprice").val('');
                                listarMinhasOrdens();
                                showNotyAlert(json.mensagem, "s");
                            } else {
                                showNotyAlert(json.mensagem, "e");
                            }
                            listarMinhasOrdens();
                        } catch (e) {
                        }
                        $("#btn-order-sell").prop("disabled", false);
                    }
                });
            }



            function initbuysell(m, f) {
                $.ajax({
                    url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_INIT ?>',
                    method: 'post',
                    dataType: 'json',
                    data: {
                    },
                    success: function (json) {
                        try {
                            if (json.sucesso) {
                                var fieldAmount = (m === 'b' ? "#buyamount" : "#sellamount");
                                var fieldPrice = (m === 'b' ? "#buyprice" : "#sellprice");
                                var fieldTotal = (m === 'b' ? "#buytotal" : "#selltotal");
                                if (f === 'a') {
                                    if (m === 'b') {
                                        $(fieldTotal).val(json.saldobrl.replace(".", ""));
                                        $(fieldPrice).val(json.venda);
                                        consultarPreco("C");
                                        atualizarTotalCompra();
                                        calcularSoma(m);
                                    } else {
                                        $(fieldAmount).val(json.saldobtc);
                                        consultarPreco((m === "b" ? "C" : "V"));
                                    }
                                } else if (f === 'p') {
                                    if (m === 'b') {
                                        $(fieldPrice).val(json.venda);
                                    } else {
                                        $(fieldPrice).val(json.compra);
                                    }
                                    calcularSoma(m);
                                } else if (f === 't') {
                                    $(fieldTotal).val(json.saldobrl.replace(".", ""));
                                    consultarPreco((m === "b" ? "C" : "V"));
                                }
                            }
                        } catch (e) {
                            
                        }
                    }
                });
            }


            function atualizarTotalCompra() {
                var total = ($("#buytotal").val().length > 0 ? parseFloat($("#buytotal").val().replace(",", ".")) : 0);
                var preco = ($("#buyprice").val().length > 0 ? parseFloat($("#buyprice").val().replace(",", ".")) : 0);
                var amount = (total / preco);
                $("#buyamount").val(amount.toFixed(casasDecimaisReal).replace(".", ","));
            }
            
            
            function listarMinhasOrdens() {
                $("#listaMyOrders").html("<tr><td colspan='6' class='text-center'><img src='<?php echo IMAGES ?>loading.gif' /></td></tr>");
                $.ajax({
                    url: '<?php echo URLBASE_CLIENT . \Utils\Rotas::R_MERCADO_EXTRATO_FILTRAR ?>',
                    method: 'post',
                    dataType: 'json',
                    data: {
                        data: data,
                        tipo: tipo,
                        nresultado: $("#filterorders").val()
                    },
                    success: function (json) {
                        try {
                            if (json.sucesso) {
                                $("#listaMyOrders").html(json.html);
                                $('#tblMyOrders').trigger('footable_initialize');
                            } else {
                            }
                        } catch (e) {
                        }
                    }
                });
            }
            
            function limpaSearch(){ 
                $("#semanaNota").addClass("active");
                $("#filterorders").val("");
                $("#diaBtc").removeClass("active");
                $("#mesBtc").removeClass("active");
                $("#todosDataBtc").removeClass("active");
                $("#compraBtc").removeClass("active");
                $("#vendaBtc").removeClass("active");
                $("#todosBtc").addClass("active");
                data = "semana";
                tipo = "todos";
                listarMinhasOrdens();    
            }
            
            
            function calcularPrecoMedio(tipo) {
                var volumeNegociado = (tipo === "C" ? $("#buytotal").val() : $("#sellamount").val());
                volumeNegociado = (volumeNegociado.length > 0 ? volumeNegociado.replace(',', '.'): 0);
               
                var volumeRestante = 0;
                
                if (volumeNegociado > 0) {
                    
                    var trs = null;
                    if (tipo === 'V') {
                        trs = $("#tabelaBookCompra tr");
                    } else {
                        trs = $("#tabelaBookVenda tr");
                    }
                    
                    volumeRestante = volumeNegociado;
                    var valorTotal = 0;
                    var volumeExecutado = 0;
                    
                    var vezes1 = 0;
                    var vezes2 = 0;
                    var precobase = 0;
                    $(trs).each(function () {
                        
                        var preco = parseFloat($(this).children(".td-price").first().children("span").first().html().replace(".", "").replace(",", "."));
                        var volume = parseFloat($(this).children(".td-volume").html().replace(",", "."));
                        
                        
                        if (volumeRestante > 0) { 
                            
                            var val = (tipo === "C" ? (volume * preco) :  volume);
                            
                            if (val >= volumeRestante) {
                                
                                volumeExecutado += (tipo === "C" ? (volumeRestante / preco) : volumeRestante);
                                valorTotal += (tipo === "C" ? volumeRestante : (volumeRestante * preco));
                                volumeRestante = 0;

                                vezes1++;
                            } else {
                                volumeExecutado += volume;
                                valorTotal += (tipo === "C" ? val : (volume * preco));
                                
                                volumeRestante -= (tipo === "C" ? val : volume);
                                
                                vezes2++;
                            }
                            
                            precobase = preco;
                        }
                    });
                    
                    if (!(volumeRestante) > 0) {
                        var preco = (valorTotal / volumeExecutado);
                        
                        if(tipo === 'C') {
                            amountCompra = volumeExecutado;
                            precoCompra = preco;
                            $("#buyprice").val(preco.toFixed(casasDecimaisReal));
                            $("#label-taxa-compra").html(buytax + "%.");
                            $("#buyprice").attr("data-base", precobase);
                            calcularSoma("b");
                        } else {
                            precoVenda = precobase;
                            $("#sellprice").val(precobase.toFixed(casasDecimaisReal)); 
                            $("#sellprice").attr("data-base", precobase);
                            calcularSoma("s");
                            $("#label-taxa-venda").html(selltax + "%.");
                            
                        }
                        
                        return true;
                    }
                    
                }
            
                return false;
            }

        </script>
        <?php Utils\Layout::append("mensage_text", $_data) ?>

