<?php
$erro = $_data["erro"];
$mensagem = $_data["mensagem"];
?>
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title><?php echo TITLE ?> | <?php echo $erro ?> Error</title>

    <link href="<?php echo TEMA ?>css/bootstrap.min.css" rel="stylesheet">
    <link href="<?php echo TEMA ?>font-awesome/css/font-awesome.css" rel="stylesheet">

    <link href="<?php echo TEMA ?>css/animate.css" rel="stylesheet">
    <link href="<?php echo TEMA ?>css/style.css" rel="stylesheet">

</head>

<body class="gray-bg">


    <div class="middle-box text-center animated fadeInDown">
        <h1><?php echo $erro ?></h1>
        <h3 class="font-bold"><?php echo $mensagem ?></h3>

        <div class="error-desc">
            Desculpe. Parece que tivemos um problema.
            
            <br><br><br>
            
            <a href="<?php echo URLBASE_CLIENT ?>/login" class="btn btn-success">Retornar para o site.</a>
            
            <!--
            <form class="form-inline m-t" role="form">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search for page">
                </div>
                <button type="submit" class="btn btn-primary">Search</button>
            </form>
            -->
        </div>
    </div>

    <!-- Mainly scripts -->
    <script src="<?php echo TEMA ?>js/jquery-3.1.1.min.js"></script>
    <script src="<?php echo TEMA ?>js/bootstrap.min.js"></script>

</body>

</html>
