

<?php Utils\Layout::append("inspina/metas", $_data) ?>
<?php Utils\Layout::append("inspina/scripts", $_data) ?>
<?php Utils\Layout::append("inspina/menu", $_data) ?>
<div class="content-wrapper">
  <div class="row wrapper border-bottom page-heading" style="background: linear-gradient(to right, #fff, <?php echo $moeda->mainColor ?>) !important;">
    <div class="col-lg-9">
      <ol class="breadcrumb m-t-md" style="background-color: transparent !important;">
          <li>
            <?php echo $idioma->getText("subTitulo") ?>
          </li>
          <li class="active">
              <strong><?php echo $idioma->getText("titulo") ?>
          </li>
      </ol>
    </div>
    <div class="col-lg-3">
    <?php Utils\Layout::append("inspina/flags", $_data) ?>
    </div>
  </div>
</div>

    <!-- Main content -->
<section class="content">
    <br><br>
    
    
    <div class="row">
        <div class="col col-xs-12">
            <div class="form-group">
                <label>Filtro</label>
                <input type="text" class="form-control" id="filtro" onkeyup="filtrar();" />
            </div>
        </div>
    </div>
    
    <div class="row">
        <div class="col col-lg-12 text-center">
            <button type="button" class="btn btn-default" onclick="limpar();">
                Limpar Filtros
            </button>
            
            <button type="button"  class="btn btn-success pull-right" onclick="cadastroSegmento('<?php \Utils\Criptografia::encriptyPostId(0)?>')">
                Novo Cadastro
            </button>
        </div>
    </div>
    
    <br><br>
    
    <div class="row">
        <div class="col col-xs-12">
            
            <table class="table table-hover table-bordered table-condensed table-striped">
                <thead>
                    <tr>
                        <th class="text-center">Segmento</th>
                        <th class="text-center">Alterar Status</th>
                        <th class="text-center">Editar</th>
                        <th class="text-center">Excluir</th>
                    </tr>
                </thead>
                
                <tbody id="lista">
                    
                </tbody>
            </table>
            
        </div>
    </div>
    
</section>
    
<div class="clearfix"></div>

<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>

<script>
    $(document).ready(function () {
        filtrar();
    });
    
    function limpar() {
        $("#filtro").val("");
        filtrar();
    }
    
    function filtrar() {
        $("#listar").html("<tr><td class='text-center' colspan='4' ><img src='<?php echo IMAGES ?>loading.gif' /></td></tr>");
        $.ajax({
            url : "<?php echo URLBASE_CLIENT . Utils\Rotas::R_COMERCIOS_SEGMENTOS_LISTAR ?>",
            method: "post",
            dataType: "json",
            data: {
                filtro: $("#filtro").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#lista").html(json.html);
                    } else {
                        $("#listar").html("<tr><td class='text-center' colspan='4' >"+json.mensagem+"</td></tr>");
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    $("#listar").html("<tr><td class='text-center' colspan='4' >"+e+"</td></tr>");
                    showNotyAlert(e, "e");
                }
            }
        });
        
    }
    
    
    function cadastroSegmento(codigo) {
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_COMERCIOS_SEGMENTOS_CADASTRO ?>',
            method: 'POST',
            dataType: 'json',
            data: {
                codigo: codigo
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#dialogEditarSegmentoComercioId").val(json.codigo);
                        $("#dialogEditarSegmentoComercioNome").val(json.nome);
                        $("#dialogEditarSegmentoComercio").modal();
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch(e) {
                    showNotyAlert(e, "e");
                }
            }
        });
    }
    
    
    function salvarSegmento() {
        $("#dialogEditarSegmentoComercioClose , #dialogEditarSegmentoComercioSalvar").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_COMERCIOS_SEGMENTOS_SALVAR ?>',
            method: 'POST',
            dataType: 'json',
            data: {
                codigo: $("#dialogEditarSegmentoComercioId").val(),
                nome: $("#dialogEditarSegmentoComercioNome").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        filtrar();
                        showNotyAlert(json.mensagem, "s");
                        $("#dialogEditarSegmentoComercioClose").prop("disabled", false).trigger("click");
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch(e) {
                    showNotyAlert(e, "e");
                }
                $("#dialogEditarSegmentoComercioClose , #dialogEditarSegmentoComercioSalvar").prop("disabled", false);
            }
        });
    }
    
    function dialogExcluirSegmentoComercio(id) {
        $("#dialogExcluirSegmentoComercio").modal();
        $("#dialogExcluirSegmentoComercioId").val(id);
    }
    
    
    function excluirSegmentoComercio() {
        $("#dialogExcluirSegmentoComercioClose, #dialogExcluirSegmentoComercioExcluir").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_COMERCIOS_SEGMENTOS_EXCLUIR ?>',
            method: 'POST',
            dataType: 'json',
            data: {
                codigo: $("#dialogExcluirSegmentoComercioId").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        filtrar();
                        $("#dialogExcluirSegmentoComercioClose").prop("disabled", false).trigger("click");
                        showNotyAlert("Segmento comercial excluído com sucesso!", "s");
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch(e) {
                    showNotyAlert(e, "e");
                }
                $("#dialogExcluirSegmentoComercioClose, #dialogExcluirSegmentoComercioExcluir").prop("disabled", false);
            }
        });
    }
    
    function alterarStatusAtivo(codigo) {
        
        $.ajax({
            url : "<?php echo URLBASE_CLIENT . Utils\Rotas::R_COMERCIOS_SEGMENTOS_STATUS ?>",
            method: "post",
            dataType: "json",
            data: {
                codigo: codigo
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        filtrar();
                        showNotyAlert("Status alterado com sucesso!", "s");
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
            }
        });
        
    }
    
</script>


<?php Utils\Layout::append("mensage_text", $_data) ?>


<div class="modal fade" id="dialogEditarSegmentoComercio" tabindex="-1" role="dialog" aria-labelledby="dialogEditarSegmentoComercio" aria-hidden="true" >
    <div class="modal-dialog modal-md" >
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="dialogEditarSegmentoComercioLabel">Cadastro de Comercio</h4>
            </div>
            <div class="modal-body">
                <input type="hidden" id="dialogEditarSegmentoComercioId" />
                <div class="row">
                    <div class="col col-lg-12">
                        <div class="form-group">
                            <label>Nome do segmento comercial</label>
                            <input type="text" id="dialogEditarSegmentoComercioNome" class="form-control" />
                        </div>
                    </div>
                </div>
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="dialogEditarSegmentoComercioClose" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-primary" onclick="salvarSegmento();" id="dialogEditarSegmentoComercioSalvar" >Salvar</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>


<div class="modal fade" id="dialogExcluirSegmentoComercio" tabindex="-1" role="dialog" aria-labelledby="dialogExcluirSegmentoComercio" aria-hidden="true" >
    <div class="modal-dialog modal-sm" >
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="dialogExcluirSegmentoComercioLabel">Excluir Comércio</h4>
            </div>
            <div class="modal-body">
                <input type="hidden" id="dialogExcluirSegmentoComercioId" />
                <div class="row">
                    <div class="col col-lg-12">
                        Tem certeza que deseja excluir o segmento comercial?
                    </div>
                </div>
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="dialogExcluirSegmentoComercioClose" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-danger" onclick="excluirSegmentoComercio();" id="dialogExcluirSegmentoComercioExcluir" >Excluir</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
