<?php
$dataInicial = new Utils\Data(date("d/m/Y"));
$dataFinal = new Utils\Data(date("d/m/Y"));
$dataInicial->subtrair(0, 0, 30);
$saldo = isset($_data["saldo"]) ? $_data["saldo"] : 0;
$cliente = Utils\Geral::getCliente();
$configuracao = isset($_data["configuracao"]) ? $_data["configuracao"] : new Models\Modules\Cadastro\Configuracao();
$adm = (\Utils\Geral::isUsuario() && \Utils\Geral::getLogado()->tipo == Utils\Constantes::ADMINISTRADOR);
$taxa = isset($_data["taxa"]) ? $_data["taxa"] : 0;

$moeda = \Modules\principal\Controllers\Principal::getCurrency();

$mostrarBotaoTransferir = (Utils\Geral::isCliente() && ($cliente->statusSaqueCurrency > 0));
$mostrarBotaoTransferirReais = (Utils\Geral::isCliente() && ($cliente->statusSaqueBrl > 0));

$mostrarAbaTransfReais = ($cliente->fotoClienteVerificada > 0 && $cliente->fotoDocumentoVerificada > 0 && $cliente->fotoResidenciaVerificada > 0 && $cliente->utilizaSaqueDepositoBrl > 0);

 $idioma = new \Utils\PropertiesUtils("transferencia_btc", IDIOMA);

$_data["idiomaMenu"] = $idioma;
?>
<style>
    .border-edit {
        border: 1px solid #1c84c6 !important;
    }
</style>
<?php Utils\Layout::append("inspina/metas", $_data) ?>
<?php Utils\Layout::append("inspina/scripts", $_data) ?>
<?php Utils\Layout::append("inspina/menu", $_data) ?>
<?php Utils\Layout::append("inspina/breadcrumb", $_data) ?>
<br>
    <div class="row">
        <div class="col-lg-12">
            <div class="tabs-container">
                <ul class="nav nav-tabs">

                    <?php if (\Utils\Geral::isCliente()) { ?>
                    
                    <?php if ($configuracao->statusTransferenciaCurrency > 0 && $moeda->statusSaque > 0) { ?>
                    <li class="nav-item active">
                        <a data-toggle="tab" href="#tab-1" id='tab1' data-target="#tab-1, #tab-2-1" style="color: <?php echo $moeda->corFonte ?>">
                            <img src="<?php echo IMAGES?>currencies/<?php echo $moeda->icone ?>" style="max-width: 20px; height: 20px;" />
                            <?php echo $idioma->getText("abaTransfMoeda") ?> <?php echo $moeda->nome ?>
                        </a>
                    </li>
                    <?php } ?>
                    
                    <?php if ($configuracao->statusTransferenciaBrl > 0 && $mostrarAbaTransfReais) { ?>
                    <li class="nav-item">
                        <a data-toggle="tab" href="#tab-2" id='tab2' data-target="#tab-2, #tab-2-2">
                            <img src="<?php echo IMAGES?>currencies/BRL.png" style="max-width: 20px; height: 20px;" />
                             <?php echo $idioma->getText("abaTransfReais") ?>
                        </a>
                    </li>
                    <?php } ?>
                    
                    <?php } ?>

                    <?php if (\Models\Modules\Acesso\ModuloRn::validar(Utils\Rotas::M_TRANSFERENCIAS, Utils\Constantes::TRANSFERIR_PARA_EMPRESA)) { ?>
                    <li class="nav-item">
                        <a data-toggle="tab" href="#tab-4" id='tab4'>
                            <?php echo $idioma->getText("abaTransfNewCash") ?>
                        </a>
                    </li>
                    <?php } ?>
                </ul>
                <div class="tab-content">

                    <?php if (\Utils\Geral::isCliente()) { ?>
                    
                    <?php if ($configuracao->statusTransferenciaCurrency > 0 && $moeda->statusSaque > 0) { ?>
                    <div id="tab-1" class="tab-pane active ">
                        <div class="panel" style="background-color: <?php echo $moeda->mainColor ?>">
                            <div class="panel-body ">

                                <div class="row">
                                    <div class="col-sm-6 b-r">
                                        <div class="form-group">
                                            <label>
                                                <?php echo str_replace("{var}", $moeda->nome, $idioma->getText("enderDestino")) ?>
                                            </label> 
                                            <input type="text" class="form-control"  id="enderecoBitcoinCurrency" maxlength="40"/>
                                        </div>
                                        <div class="form-group">
                                            <label>
                                                <?php echo $idioma->getText("descTransferencia") ?>
                                            </label> 
                                            
                                            <div class="input-group">
                                                <span class="input-group-addon"> 
                                                    <input type="checkbox" id="ck-habilitar-descricao-currency"> 
                                                </span>
                                                <input type="text" class="form-control"  id="descricaoCurrency"  maxlength="60"/>
                                            </div>
                                        </div>
                                        
                                        <div class="form-group">
                                            <label>
                                                <?php echo $idioma->getText("volumeEm") ?> <?php echo $moeda->simbolo ?>
                                            </label>
                                            <div class="input-group">
                                                <input type="text" inputmode="numeric" pattern="[0-9]*" class="form-control" id="transferenciaContaValorCurrency">
                                                <span class="input-group-btn">
                                                    <button type="button" class="btn btn-primary" onclick="utilizarSaldo('c');"><?php echo $idioma->getText("meuVolumeTotal") ?></button>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="widget style1 " style="background-color: <?php echo $moeda->mainColor ?> !important;">
                                                <div class="row text-center" >
                                                    <span style="color: <?php echo $moeda->corFonte ?>"> <?php echo $moeda->nome ?> </span>
                                                <h1 class="font-bold" style="color: <?php echo $moeda->corFonte ?>" <label id="transferenciaContaTotalCurrency">0.00000000 <?php echo $moeda->simbolo ?></label></h1>
                                                </div>

                                        </div>
                                        <p><?php echo $idioma->getText("taxa") ?> <?php echo number_format($taxa, 8, ",", "")?> <?php echo $moeda->simbolo ?></p>
                                        <p></p>
                                        <p style="color: #ed5565"><?php echo $idioma->getText("valorDaTranferenciaMaior") ?> <?php echo number_format($taxa, 8, ",", "")?> <?php echo $moeda->simbolo ?></p>


                                        <?php if (Models\Modules\Acesso\ModuloRn::validar(Utils\Rotas::M_TRANSFERENCIAS, \Utils\Constantes::CADASTRAR)) { ?>
                                        <div class="col-xs-12 col-lg-4 pull-right">
                                        <?php if ($mostrarBotaoTransferir) { ?>
                                        <button type="button" class="btn btn-primary pull-right full-width" id="transferenciaContaBtnTransferirCurrency" onclick="modalTransferirCurrency();"><?php echo $idioma->getText("btTransferir") ?> <?php echo $moeda->simbolo ?></button>
                                        </div>
                                        <?php } ?>

                                        <?php } ?>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php } ?>
                    
                    <?php if ($configuracao->statusTransferenciaBrl > 0 && $mostrarAbaTransfReais) { ?>
                    <div id="tab-2" class="tab-pane">
                        <div class="panel panel-primary">
                            <div class="panel-body">


                                <div class="row">
                                    <div class="col-sm-6 b-r">
                                        <div class="form-group">
                                            <label><?php echo $idioma->getText("carteiraDestino") ?></label>
                                            <div class="form-group">
                                                <input type="text" class="form-control"  id="transferenciaContaCarteiraReais"/>
                                                <input type="hidden" id="idClienteDestiantarioReais"/>

                                            </div>
                                            <p>
                                                <?php echo str_replace("{var}", $moeda->nome, $idioma->getText("atencaoUtilize")) ?>
                                            </p>
                                        </div>
                                        
                                        <div class="form-group">
                                            <label>
                                                <?php echo $idioma->getText("descParaEssaTransf") ?>
                                            </label> 
                                            <div class="input-group">
                                                <span class="input-group-addon"> 
                                                    <input type="checkbox" id="ck-habilitar-descricao-reais"> 
                                                </span>
                                                <input type="text" class="form-control"  id="descricaoReais"  maxlength="60"/>
                                            </div>
                                        </div>
                                        
                                        <label><?php echo $idioma->getText("valorReais") ?></label>
                                        <div class="input-group">
                                            <input type="text" inputmode="numeric" pattern="[0-9]*" class="form-control" id="transferenciaContaValorReais"  />
                                            <span class="input-group-btn">
                                                <button type="button" class="btn btn-primary" onclick="utilizarSaldo('r');"><?php echo $idioma->getText("meuSaldoTotal") ?></button>
                                            </span>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">

                                        <span id="transferenciaContaNomeClienteDestinatarioReais" class="label label-warning" style="font-size: 16px;"></span>
                                        <span id="transferenciaContaNaoEncontradoContainerReais" class="label label-danger" style="font-size: 16px; display: none;"><?php echo $idioma->getText("carteiraInvalida") ?></span>


                                        <div class="widget navy-bg">
                                                <div class="row text-center">
                                                        <span> <?php echo $idioma->getText("reais") ?> </span>
                                                        
                                                        <h1 class="font-bold"> <label id="transferenciaContaTotalReais2">R$ 0,00</label></h1>
                                                </div>
                                        </div>

                                        <p><?php echo $idioma->getText("taxaR") ?> <?php echo number_format($configuracao->taxaTransferenciaInternaReais, 2, ",", "")?></p>
                                        <p></p>
                                        <p style="color: #ed5565"><?php echo $idioma->getText("valorTransferenciaMaiorR") ?> <?php echo number_format($configuracao->taxaTransferenciaInternaReais, 2, ",", "")?></p>

                                        <?php if (Models\Modules\Acesso\ModuloRn::validar(Utils\Rotas::M_TRANSFERENCIAS, \Utils\Constantes::CADASTRAR)) { ?>
                                        <div class="col-xs-12 col-lg-4 pull-right">
                                        <?php if ($mostrarBotaoTransferirReais) { ?>
                                        <button type="button" class="btn btn-primary pull-right full-width" id="transferenciaContaBtnTransferirReais" onclick="modalTransferirReais();"><?php echo $idioma->getText("transferirReais") ?></button>
                                        </div>
                                            <?php } ?>

                                        <?php } ?>

                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                    <?php } ?>
                    
                    <?php } ?>

                    <?php if (\Models\Modules\Acesso\ModuloRn::validar(Utils\Rotas::M_TRANSFERENCIAS, Utils\Constantes::TRANSFERIR_PARA_EMPRESA)) { ?>
                    <div id="tab-4" class="tab-pane">
                        <div class="panel" style="background: #1c84c6">
                        <div class="panel-body" style="margin-top: 0px">

                            <div class="row">
                                <div class="col-sm-6 b-r">

                                    <div class="form-group">
                                        <label><?php echo $idioma->getText("descParaTransNc") ?></label> 
                                        <input type="text" class="form-control"  id="descricaoEmpresa"  maxlength="60"/>
                                    </div>

                                    <div class="form-group">
                                        <label><?php echo $idioma->getText("moeda") ?></label>
                                        <select class="form-control" id="transferenciaContaMoeda">
                                            <option value="r" ><?php echo $idioma->getText("opReais") ?></option>
                                            <option value="c" ><?php echo $moeda->nome ?></option>
                                        </select>
                                    </div>

                                    <div class="form-group" id="form-group-currency">
                                        <label><?php echo $idioma->getText("volumeEmNc") ?> <?php echo $moeda->simbolo ?></label>
                                        <div class="input-group">
                                            <input type="text" class="form-control" id="transferenciaContaCurrencyEmpresa">
                                            <span class="input-group-btn">
                                                <button type="button" class="btn btn-primary" onclick="utilizarSaldo('c');"><?php echo $idioma->getText("meuVolumeTotalNc") ?></button>
                                            </span>
                                        </div>
                                    </div>
                                    <div class="form-group" id="form-group-real">
                                        <label><?php echo $idioma->getText("volumeEm") ?> R$</label>
                                        <div class="input-group">
                                            <input type="text" class="form-control" id="transferenciaContaValorEmpresa">
                                            <span class="input-group-btn">
                                                <button type="button" class="btn btn-primary" onclick="utilizarSaldo('r');"><?php echo $idioma->getText("meuSaldoTotalNc") ?></button>
                                            </span>
                                        </div>
                                    </div>

                                </div>
                                        
                                        
                                <div class="col-sm-6">
                                    <div class="widget style1 success" style="background-color: #1c84c6 !important; color: #FFF">
                                        <div class="row text-center">

                                                <div id="transferenciaContaTotalEmpresaReal">
                                                </div>


                                                <span id="transferenciaContaTotalEmpresaMoedaCurrency" > <?php echo $moeda->nome ?> </span>
                                                <span id="transferenciaContaTotalEmpresaMoedaReal" > <?php echo $idioma->getText("reais") ?> </span>
                                                <h1 class="font-bold"> <label id="transferenciaContaTotalEmpresa">0.00000000</label></h1>

                                        </div>
                                    </div>

                                    <p><?php echo $idioma->getText("transfSemTaxa") ?></p>
                                    <p></p>
                                    <p style="color: #ed5565"><?php echo $idioma->getText("qualquerValor") ?> <label id="moedaSelectReal"><?php echo $idioma->getText("reais") ?></label><label id="moedaSelectMoeda"><?php echo $moeda->nome ?></label> <?php echo $idioma->getText("podeSerTransf") ?></p>

                                    <?php //if (Models\Modules\Acesso\ModuloRn::validar(Utils\Rotas::M_TRANSFERENCIAS, \Utils\Constantes::CADASTRAR)) { ?>

                                    <?php //if ($mostrarBotaoTransferir) { ?>
                                    <div class="col-xs-12 col-sm-6 pull-right">
                                    <button type="button" class="btn  btn-primary pull-right full-width" id="transferenciaContaBtnTransferirEmpresa" onclick="modalTransferirEmpresa();"><?php echo $idioma->getText("transfParaNc") ?></button>
                                    </div>
                                        <?php //} ?>

                                    <?php //} ?>
                                </div>
                            </div>
                        </div>
                    </div>
                        </div>
                            
                    <?php } ?>
                    
                    <br>
                    <div class="panel-body">
                        <div class="col-lg-12">
                            <form id="pesquisa">  
                                <div class="row">

                                    <div class="col col-md-2">
                                        <div class="form-group">
                                            <label class="control-label"><?php echo $idioma->getText("dtInicial") ?></label>
                                            <input type="text" id="dataInicial" class="form-control" value="<?php echo $dataInicial->formatar(\Utils\Data::FORMATO_PT_BR)?>"/>
                                        </div>
                                    </div>
                                    <div class="col col-md-2">
                                        <div class="form-group">
                                            <label class="control-label"><?php echo $idioma->getText("dtFinal") ?></label>
                                            <input type="text" id="dataFinal" class="form-control" value="<?php echo $dataFinal->formatar(\Utils\Data::FORMATO_PT_BR)?>" />
                                        </div>
                                    </div>
                                    <div class="col col-md-3">
                                        <div class="form-group">
                                            <label><?php echo $idioma->getText("registros") ?></label>
                                            <select class="form-control" id="nregistros">
                                                <option value="10">10</option>
                                                <option value="20">20</option>
                                                <option value="50">50</option>
                                                <option value="100">100</option>
                                                <option value="T"><?php echo $idioma->getText("todos") ?></option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col col-lg-3">
                                        <div class="form-group">
                                            <label><?php echo $idioma->getText("filtroGeral") ?></label>
                                            <input type="text" id="filtro" class="form-control"/>
                                        </div>
                                    </div>
                                    <div class="col col-lg-2 col-xs-12">
                                        <label>&nbsp;</label>
                                        <div class="form-group">

                                            <button type="button" class="btn btn-default pull-right full-width" onclick="filtrar()"><?php echo $idioma->getText("filtro") ?></button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>          
                         
                </div>
            </div>
            <br>
        </div>
    </div>
    
                   
    <div class="row" id="tabextrato">
        <div class="col-lg-12">        

            <div class="tabs-container">
                
                <ul class="nav nav-tabs">

                    <?php if (\Utils\Geral::isUsuario()) { ?>
                    <li class="nav-item active" style="text-align: center;">
                        <a data-toggle="tab" href="#tab-1" id='tab1' data-target="#tab-1, #tab-2-1">
                            <img src="<?php echo IMAGES?>currencies/<?php echo $moeda->icone ?>" style="max-width: 20px; height: 20px;" />
                            <?php echo $idioma->getText("abaTransfMoeda") ?> <?php echo $moeda->nome ?>
                        </a>
                    </li>
                    <li class="nav-item"  style="text-align: center;">
                        <a data-toggle="tab" href="#tab-2" id='tab2' data-target="#tab-2, #tab-2-2">
                            <img src="<?php echo IMAGES?>currencies/BRL.png" style="max-width: 20px; height: 20px;" />
                             <?php echo $idioma->getText("abaTransfReais") ?>
                        </a>
                    </li>
                    <?php } ?>
                </ul>
                
                <div class="tab-content">

                    <div id="tab-2-1" class="tab-pane active">

                        <div class="row">
                            
                                <div class="col-xs-12 col-lg-12">
                                    <div class="table-responsive">
                                <table class="table table-condensed table-stripped table-hover table-bordered" style="font-size: 10px">
                                    <thead>
                                        <tr>
                                            <?php if (Utils\Geral::isUsuario()) { ?>
                                            <th><?php echo $idioma->getText("cliente") ?></th>
                                            <?php } ?>
                                            <th><?php echo $idioma->getText("controle") ?></th>
                                            <th><?php echo $idioma->getText("data") ?></th>
                                            <th><?php echo $idioma->getText("volume") ?> (<?php echo $moeda->simbolo ?>)</th>
                                            <th><?php echo $idioma->getText("taxa") ?> (<?php echo $moeda->simbolo ?>)</th>
                                            <th><?php echo $idioma->getText("endereco") ?></th>
                                            <th><?php echo $idioma->getText("descricao") ?></th>
                                            <th><?php echo $idioma->getText("status") ?></th>
                                            <th><?php echo $idioma->getText("hash") ?></th>
                                        </tr>
                                    </thead>

                                    <tbody id="lista-currency" style="background-color: #fff">

                                    </tbody>

                                </table>
                                    </div>
                            </div>
                       
                        </div>

                    </div>

                    <div id="tab-2-2" class="tab-pane">
                        <div class="row">
                            
                                <div class="col-xs-12 col-lg-12">
                                    <div class="table-responsive">
                                <table class="table table-condensed table-stripped table-hover table-bordered" style="font-size: 10px">
                                    <thead>
                                        <tr>
                                            <?php if (Utils\Geral::isUsuario()) { ?>
                                            <th><?php echo $idioma->getText("cliente") ?></th>
                                            <?php } ?>
                                            <th><?php echo $idioma->getText("controle") ?></th>
                                            <th><?php echo $idioma->getText("data") ?></th>
                                            <th><?php echo $idioma->getText("descricao") ?></th>
                                            <th><?php echo $idioma->getText("valor") ?></th>
                                            <th><?php echo $idioma->getText("taxa") ?></th>
                                            <th><?php echo $idioma->getText("destinatario") ?></th>
                                        </tr>
                                    </thead>

                                    <tbody id="lista-reais" style="background-color: #fff;">

                                    </tbody>

                                </table>
                                    </div>
                           
                            </div>
                        </div>
                    </div>

                </div>

            </div>

            <div class="clearfix"></div>
        </div>
    </div>

    

<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>


<?php Utils\Layout::append("mensage_text", $_data) ?>

<script>
    $(document).ready(function () {
        
        filtrar();
        
        var ex = document.getElementsByName("transferenciaContaMoeda")[0];
        //var str= ex.options[ex.selectedIndex].value;
         //**or**
        //var str = ex.options[ex.selectedIndex].text;
        $("#ck-habilitar-descricao-reais").change(function () {
            $("#descricaoReais").prop("disabled", (!$(this).is(":checked")));
        });

        $("#ck-habilitar-descricao-currency").change(function () {
            $("#descricaoCurrency").prop("disabled", (!$(this).is(":checked")));
        });

        
        $("#tab1").click(function(){
          $(this).css("background-color", "<?php echo $moeda->mainColor ?>");
          $("#tab1").css("color", "<?php echo $moeda->corFonte ?>");
          $("#tab2").css("background-color", "");
          $("#tab4").css("background-color", "");
          $("#tab4").css("color", "#676a6c");
        });
        $("#tab2").click(function(){
          $(this).css("background-color", "#1ab394");
          $("#tab1").css("background-color", "");
          $("#tab1").css("color", "#5b5d5f");
          $("#tab4").css("background-color", "");
          $("#tab4").css("color", "#676a6c");
        });
        $("#tab4").click(function(){
          $(this).css("background-color", "#1c84c6");
          $(this).css("color", "#fff");
          $("#tab1").css("background-color", "");
          $("#tab1").css("color", "#5b5d5f");
          $("#tab2").css("background-color", "");
        });

          $("#tab1").css("background-color", "<?php echo $moeda->mainColor ?>");

        $("#transferenciaContaValorCurrency").keydown(function(event) {
            $(this).val(currency($(this).val(), 8, 8, event.keyCode));
            calcularValorTotal("c");
            event.preventDefault();
        });
        
        
        $("#transferenciaContaValorReais").keydown(function(event) {
            $(this).val(currency($(this).val(), 2, 8, event.keyCode));
            calcularValorTotal("r");
            event.preventDefault();
        });
        
        $("#transferenciaContaCurrencyEmpresa").keydown(function(event) {
            $(this).val(currency($(this).val(), 8, 8, event.keyCode));
            calcularValorTotalEmpresa();
            event.preventDefault();
        });
        $("#transferenciaContaValorEmpresa").keydown(function(event) {
            $(this).val(currency($(this).val(), 2, 8, event.keyCode));
            calcularValorTotalEmpresa();
            event.preventDefault();
        });
        
        $("#dataInicial,#dataFinal").datepicker({
            format: "dd/mm/yyyy",
            todayBtn: "linked",
            language: "pt-BR",
            orientation: "top left",
            autoclose: true,
            todayHighlight: true,
            toggleActive: true
        });
        
        $("#dataInicial, #dataFinal").datepicker({format: 'dd/mm/yyyy'}).mask("99/99/9999");
        
        function limpar(){
            $('#pesquisa').each (function(){
              this.reset();
              filtrar();
            });
        }
        
        $("#tokenBtc, #tokenReais, #pinBtc, #pinReais").numeric();
        
        $('#transferenciaContaCarteiraReais').on('keyup', function() {
            let myLength = $("#transferenciaContaCarteiraReais").val().length;
            
            if (myLength > 26) {
                findClienteWallet();
            } else  {
                $("#transferenciaContaNaoEncontradoContainerReais").hide();
                $("#transferenciaContaDestinatarioContainerReais").hide();
                $("#transferenciaContaNomeClienteDestinatarioReais").html("");
                $("#transferenciaContaBtnTransferirReais").prop("disabled", true);
            }
        });
        
        
        
        $("#transferenciaContaMoeda").change(function () {
            if ($(this).val() === "r") {
                $("#form-group-currency").hide();
                $("#form-group-real").show();
                
                $("#transferenciaContaTotalEmpresa").html("0,00");
                $("#transferenciaContaTotalEmpresaReal").show();
                $("#transferenciaContaTotalEmpresaMoedaReal").show();
                $("#transferenciaContaTotalEmpresaCurrency").hide();
                $("#transferenciaContaTotalEmpresaMoedaCurrency").hide();
                $("#moedaSelectReal").show();
                $("#moedaSelectMoeda").hide();
           
                
            } else {
                $("#form-group-currency").show();
                $("#form-group-real").hide();
                
                $("#transferenciaContaTotalEmpresa").html("0,00000000");
                $("#transferenciaContaTotalEmpresaCurrency").show();
                $("#transferenciaContaTotalEmpresaMoedaCurrency").show();
                $("#transferenciaContaTotalEmpresaReal").hide();
                $("#transferenciaContaTotalEmpresaMoedaReal").hide();
                $("#moedaSelectMoeda").show();
                $("#moedaSelectReal").hide();
            }
        }).trigger("change");
        
        $("#ck-habilitar-descricao-currency, #ck-habilitar-descricao-reais").trigger("change");
    });
    
    function calcularValorTotal(tipo) {
        if (tipo === "c") {
            var taxa = <?php echo number_format($taxa, 8, ".", "")?>;
            var valor = ($("#transferenciaContaValorCurrency").val().length > 0 ? parseFloat(toFloat($("#transferenciaContaValorCurrency").val())) : 0.00);
            var total = taxa + valor;
            
            $("#transferenciaContaTotalCurrency").html(total.toFixed(8) + " <?php echo $moeda->simbolo ?>");
            
        } else {
            var taxa = <?php echo number_format($configuracao->taxaTransferenciaInternaReais, 2, ".", "")?>;
            var valor = ($("#transferenciaContaValorReais").val().length > 0 ? parseFloat(toFloat($("#transferenciaContaValorReais").val())) : 0.00);
            var total = taxa + valor;
     
            $("#transferenciaContaTotalReais2").html("R$ " + mascaraValor(total.toFixed(2)));
            
        }
    }
    
    function calcularValorTotalEmpresa() {
        let tipo = $("#transferenciaContaMoeda").val();
        if (tipo === "c") {
            $("#transferenciaContaTotalEmpresa").text($("#transferenciaContaCurrencyEmpresa").val());
        } else {
            var valor = ($("#transferenciaContaValorEmpresa").val());
            $("#transferenciaContaTotalEmpresa").text($("#transferenciaContaValorEmpresa").val());
            $("#transferenciaContaTotalEmpresa").html("R$ " + mascaraValor(valor));
        }
    }
    
    function filtrar() {
        filtrarCurrency();
        filtrarReais();
    }
    
    function filtrarCurrency() {
        $("#lista-currency").html("<tr ><td class='text-center' colspan='9'><img src='<?php echo IMAGES ?>loading.gif' /></td></tr>");
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_BTC_TRANSFERENCIAS_FILTRAR  ?>',
            method: 'post',
            dataType: 'json',
            data: {
                dataInicial:$("#dataInicial").val(),
                dataFinal:$("#dataFinal").val(),
                filtro: $("#filtro").val(),
                nregistros: $("#nregistros").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#lista-currency").html(json.html);
                        
                        $(".transferencia-currency-descricao").each(function () {
                            let descricao = $(this).attr("data-descricao");
                            $(this).popover({
                                html: true,
                                trigger: "focus",
                                container: "body",
                                placement: "top",
                                title: "Transferência ",
                                content: descricao
                            });
                        });
                        
                    } else {
                        $("#lista-currency").html("<tr ><td class='text-center' colspan='9'>"+json.mensagem+"</td></tr>");
                    }
                } catch (e) {
                    $("#lista-currency").html("<tr ><td class='text-center' colspan='9'>"+e+"</td></tr>");
                }
            }
        });
    }
    
    function filtrarReais() {
        $("#lista-reais").html("<tr ><td class='text-center' colspan='7'><img src='<?php echo IMAGES ?>loading.gif' /></td></tr>");
        $.ajax({
            url: '<?php echo URLBASE_CLIENT  . Utils\Rotas::R_REAIS_TRANSFERENCIAS_FILTRAR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                dataInicial:$("#dataInicial").val(),
                dataFinal:$("#dataFinal").val(),
                filtro: $("#filtro").val(),
                nregistros: $("#nregistros").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#lista-reais").html(json.html);
                        
                        $(".transferencia-reais-descricao").each(function () {
                            let descricao = $(this).attr("data-descricao");
                            $(this).popover({
                                html: true,
                                trigger: "focus",
                                container: "body",
                                placement: "top",
                                title: "Transferência ",
                                content: descricao
                            });
                        });
                    } else {
                        $("#lista-reais").html("<tr ><td class='text-center' colspan='7'>"+json.mensagem+"</td></tr>");
                    }
                } catch (e) {
                    $("#lista-reais").html("<tr ><td class='text-center' colspan='7'>"+e+"</td></tr>");
                }
            }
        });
    }
    
    
    
    function transferirCurrency() {
        $("#transferenciaContaBtnTransferirCurrency, #modalTransacaoConfirmarCurrency, #modalTransacaoCancelarCurrency, #modalTransacaoReenviarCurrency").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_BTC_TRANSFERIR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                idClienteFrom: '<?php echo Utils\Criptografia::encriptyPostId($cliente->id) ?>',
                enderecoBitcoin: $("#enderecoBitcoinCurrency").val(),
                valor: $("#transferenciaContaValorCurrency").val(),
                descricao: $("#descricaoCurrency").val(),
                token: $("#tokenCurrency").val(),
                pin: $("#pinCurrency").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#modalTransacaoCancelarCurrency").prop("disabled", false).trigger("click");
                        showNotyAlert(json.mensagem, "s");
                        $("#transferenciaContaNomeClienteDestinatarioCurrency").html("");
                        $("#transferenciaContaDestinatarioContainerCurrency").hide();
                        $("#transferenciaContaNaoEncontradoContainerCurrency").hide();
                        $("#saldobtcCurrency").text(json.saldo);
                        $("#transferenciaContaValorCurrency").text("0,00000000");
                        $("#transferenciaContaTotalCurrency").text("0,00000000 <?php echo $moeda->simbolo ?>");
                        $("#transferenciaContaEmailCurrency").val("");
                        $("#idClienteDestiantarioCurrency").val("0");
                        filtrar();
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#transferenciaContaBtnTransferirCurrency, #modalTransacaoConfirmarCurrency, #modalTransacaoCancelarCurrency, #modalTransacaoReenviarCurrency").prop("disabled", false);
            }
        });
    }
    
    
    function transferirReais() {
        $("#transferenciaContaBtnTransferirReais, #modalTransacaoConfirmarReais, #modalTransacaoCancelarReais, #modalTransacaoReenviarReais").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_REAIS_TRANSFERIR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                idClienteFrom: '<?php echo \Utils\Criptografia::encriptyPostId($cliente->id) ?>',
                idClienteTo: $("#idClienteDestiantarioReais").val(),
                valor: $("#transferenciaContaValorReais").val(),
                descricao: $("#descricaoReais").val(),
                token: $("#tokenReais").val(),
                pin: $("#pinReais").val()
            },

            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#modalTransacaoCancelarReais").prop("disabled", false).trigger("click");
                        showNotyAlert(json.mensagem, "s");
                        $("#transferenciaContaNomeClienteDestinatarioReais").html("");
                        $("#transferenciaContaDestinatarioContainerReais").hide();
                        $("#transferenciaContaNaoEncontradoContaineReaisr").hide();
                        $("#saldobrlReais").text(json.saldo);
                        $("#transferenciaContaValorReais").val("0,00");
                        $("#transferenciaContaTotalReais").text("0,00");
                        $("#transferenciaContaCarteiraReais").text("");
                        $("#idClienteDestiantarioReais").val("0");
                        filtrar();
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#transferenciaContaBtnTransferirReais, #modalTransacaoConfirmarReais, #modalTransacaoCancelarReais, #modalTransacaoReenviarReais").prop("disabled", false);
            }
        });
    }
    
    
    function findCliente() {
        $("#transferenciaContaBtnFind").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_POSTGETCLIENTEBYEMAIL  ?>',
            dataType: 'json',
            method: 'post',
            data: {
                email: $("#transferenciaContaEmail").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        if (json.cliente.id > 0) {
                            $("#idClienteDestiantario").val(json.id);
                            $("#transferenciaContaDestinatarioContainer").show();
                            $("#transferenciaContaNaoEncontradoContainer").hide();
                            $("#transferenciaContaNomeClienteDestinatario").html(json.cliente.nome);
                        } else {
                            $("#idClienteDestiantario").val(0);
                            $("#transferenciaContaNaoEncontradoContainer").show();
                            $("#transferenciaContaDestinatarioContainer").hide();
                            $("#transferenciaContaNomeClienteDestinatario").html("");
                        }
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#transferenciaContaBtnFind").prop("disabled", false);
            }
        });
    }
    
    
    function findClienteWallet() {
        $("#transferenciaContaBtnFindReais").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_REAIS_CLIENTES_FINDBYWALLET ?>',
            dataType: 'json',
            method: 'post',
            data: {
                carteira: $("#transferenciaContaCarteiraReais").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        if (json.cliente.id > 0) {
                            $("#idClienteDestiantarioReais").val(json.id);
                            $("#transferenciaContaDestinatarioContainerReais").show();
                            $("#transferenciaContaNaoEncontradoContainerReais").hide();
                            $("#transferenciaContaNomeClienteDestinatarioReais").html(json.cliente.nome);
                            $("#transferenciaContaBtnTransferirReais").prop("disabled", false);
                        } else {
                            
                        }
                    } else {
                        //alert(json.mensagem);
                            $("#idClienteDestiantarioReais").val(0);
                            $("#transferenciaContaNaoEncontradoContainerReais").show();
                            $("#transferenciaContaDestinatarioContainerReais").hide();
                            $("#transferenciaContaNomeClienteDestinatarioReais").html("");
                            $("#transferenciaContaBtnTransferirReais").prop("disabled", true);
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                //$("#transferenciaContaBtnFind").prop("disabled", false);
            }
        });
    }
    
    function utilizarSaldo(tipo) {
        
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_INIT ?>',
            method: 'post',
            dataType: 'json',
            data: {
                
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        if (tipo === "c") {
                            var taxa = <?php echo number_format($taxa, 8, ".", "")?>;
                            var valor = parseFloat(json.saldobtc);
                            
                            if (valor > 0) {
                                var total = valor-taxa;
                            } else {
                                var total = 0;
                            }
                            $("#transferenciaContaValorCurrency").val(total.toFixed(8).replace(".",","));
                            $("#transferenciaContaCurrencyEmpresa").val(valor.toFixed(8).replace(",","."));
                        } else {
                            var taxa = <?php echo number_format($configuracao->taxaTransferenciaInternaReais, 2, ".", "")?>;
                            var valor = parseFloat(json.saldobrl.replace(".", "").replace(",", "."));

                            if (valor > 0) {
                                var total = valor-taxa;
                            } else {
                                var total = 0;
                            }
                            $("#transferenciaContaValorReais").val(total.toFixed(2).replace(".",","));
                            $("#transferenciaContaValorEmpresa").val(valor.toFixed(2).replace(".",","));
                        }
                        calcularValorTotal(tipo);
                        calcularValorTotalEmpresa();
                    }
                } catch (e) {
                }
                
            }
        });
    }
    
    function modalTransferirCurrency() {
        $("#transferenciaContaBtnTransferirCurrency").prop("disabled", true);
        $("#modalTransacaoCancelarCurrency").trigger("click");
        $("#tokenCurrency").val("");
        $("#pinCurrency").val("");
        var endereco = $("#enderecoBitcoinCurrency").val();
        var valor = parseFloat(($("#transferenciaContaValorCurrency").val().length > 0 ? $("#transferenciaContaValorCurrency").val().replace(",", ".") : 0));
        
        if (endereco.length <= 0 || valor <= 0) {
            
            var fields = [];
            if (endereco.length <= 0) {
                fields[0] = "Endereço";
            }
            if (valor <= 0) {
                fields[2] = "Valor";
            }
            
            
            $("#transferenciaContaBtnTransferirCurrency").prop("disabled", false);
            showNotyAlert("<?php echo $idioma->getText("vocePreciaInforarTodosParametros")?> (" + fields.join(", ") + ")", "e");
            
        } else {
            $.ajax({
                url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_BTC_AUTORIZACAO_TOKEN  ?>',
                method: 'post',
                dataType: 'json',
                data: {
                    enderecoBitcoin:  $("#enderecoBitcoinCurrency").val(),
                    valor: valor
                },
                success: function (json) {
                    try {
                        if (json.sucesso) {
                            $("#modalTransacaoMeioCurrency").html(json.meio);
                            $("#modalTransacaoCurrency").modal();
                        } else {
                            showNotyAlert(json.mensagem, "e");
                        }
                    } catch (e) {
                        showNotyAlert(e, "e");
                    }
                    $("#transferenciaContaBtnTransferirCurrency").prop("disabled", false);
                }
            });
        }
    }
    
    
    function modalTransferirReais() {
        $("#transferenciaContaBtnTransferirReais").prop("disabled", true);
        $("#modalTransacaoCancelarReais").trigger("click");
        $("#tokenReais").val("");
        $("#pinReais").val("");
        var idClienteTo = $("#idClienteDestiantarioReais").val();
        var valor = parseFloat(($("#transferenciaContaValorReais").val().length > 0 ? $("#transferenciaContaValorReais").val().replace(",", ".") : 0));
        
        if (!idClienteTo > 0 || valor <= 0) {
            
            var fields = [];
            if (!idClienteTo > 0) {
                fields[0] = "Cliente";
            }
            if (valor <= 0) {
                fields[2] = "Valor";
            }
            
            
            $("#transferenciaContaBtnTransferirReais").prop("disabled", false);
            showNotyAlert("<?php echo $idioma->getText("vocePreciaInforarTodosParametros")?> (" + fields.join(", ") + ")", "e");
        } else {
            $.ajax({
                url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_REAIS_AUTORIZACAO_TOKEN ?>',
                method: 'post',
                dataType: 'json',
                data: {
                    idClienteTo:  $("#idClienteDestiantarioReais").val(),
                    valor: valor
                },
                success: function (json) {
                    try {
                        if (json.sucesso) {
                            $("#modalTransacaoMeioReais").html(json.meio);
                            $("#modalTransacaoReais").modal();
                        } else {
                            showNotyAlert(json.mensagem, "e");
                        }
                    } catch (e) {
                        showNotyAlert(e, "e");
                    }
                    $("#transferenciaContaBtnTransferirReais").prop("disabled", false);
                    

                }
            });
        }
    }
    
    
    
    
    
    function modalTransferirEmpresa() {
        $("#transferenciaContaBtnTransferirEmpresa").prop("disabled", true);
        
        $("#modalTransacaoCancelarEmpresa").trigger("click");
        $("#modalTransacaoEmpresaTokenReais").val("");
        $("#modalTransacaoEmpresaPinReais").val("");
        
        var valor = 0;
        if ($("#transferenciaContaMoeda").val() === "r") {
            valor = parseFloat(($("#transferenciaContaValorEmpresa").val().length > 0 ? $("#transferenciaContaValorEmpresa").val().replace(",", ".") : 0));
        } else {
            valor = parseFloat(($("#transferenciaContaCurrencyEmpresa").val().length > 0 ? $("#transferenciaContaCurrencyEmpresa").val().replace(",", ".") : 0));
        }
        
        
        if (valor <= 0) {
            
            var fields = [];
            
            if (valor <= 0) {
                fields[1] = "Valor";
            }
            
            $("#transferenciaContaBtnTransferirEmpresa").prop("disabled", false);
            showNotyAlert("<?php echo $idioma->getText("vocePreciaInforarTodosParametros")?> (" + fields.join(", ") + ")", "e");
        } else {
            $.ajax({
                url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_EMPRESA_AUTORIZACAO_TOKEN ?>',
                method: 'post',
                dataType: 'json',
                data: {
                    tipoMoeda: $("#transferenciaContaMoeda").val(),
                    valor: valor
                },
                success: function (json) {
                    try {
                        if (json.sucesso) {
                            $("#modalTransacaoMeioEmpresa").html(json.meio);
                            $("#modalTransacaoEmpresa").modal();
                        } else {
                            showNotyAlert(json.mensagem, "e");
                        }
                    } catch (e) {
                        showNotyAlert(e, "e");
                    }
                    $("#transferenciaContaBtnTransferirEmpresa").prop("disabled", false);
                }
            });
        }
        
    }
    
    
    
    function transferirEmpresa() {
        var valor = 0;
        if ($("#transferenciaContaMoeda").val() === "r") {
            valor = parseFloat(($("#transferenciaContaValorEmpresa").val().length > 0 ? $("#transferenciaContaValorEmpresa").val().replace(",", ".") : 0));
        } else {
            valor = parseFloat(($("#transferenciaContaCurrencyEmpresa").val().length > 0 ? $("#transferenciaContaCurrencyEmpresa").val().replace(",", ".") : 0));
        }
        
        $("#transferenciaContaBtnTransferirEmpresa, #modalTransacaoReenviarEmpresa, #modalTransacaoCancelarEmpresa, #modalTransacaoConfirmarEmpresa").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_EMPRESA_TRANSFERIR ?>',
            method: 'post',
            dataType: 'json',
            data: {
                tipoMoeda: $("#transferenciaContaMoeda").val(),
                valor: valor,
                descricao: $("#descricaoEmpresa").val(),
                token: $("#modalTransacaoEmpresaTokenEmpresa").val(),
                pin: $("#modalTransacaoEmpresaPinEmpresa").val()
            },

            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#modalTransacaoCancelarEmpresa").prop("disabled", false).trigger("click");
                        
                        showNotyAlert(json.mensagem, "s");
                        
                        $("#saldobrlReais").text(json.saldobrl);
                        $("#saldobtcCurrency").text(json.saldobtc);
                        
                        $("#transferenciaContaValorEmpresa").val("0,00");
                        $("#transferenciaContaCurrencyEmpresa").val("0,00");
                        $("#transferenciaContaTotalEmpresa").text("0,00");
                        filtrar();
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#transferenciaContaBtnTransferirEmpresa, #modalTransacaoReenviarEmpresa, #modalTransacaoCancelarEmpresa, #modalTransacaoConfirmarEmpresa").prop("disabled", false);
            }
        });
    }
    
</script>


<div class="modal inmodal" id="modalTransacaoCurrency" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content animated bounceInRight">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                
                <h4 class="modal-title"><?php echo $idioma->getText("confirmaTransacao") ?></h4>
            </div>
            <div class="modal-body">
                <p>
                    <strong id="modalTransacaoMeioCurrency"></strong>
                </p>
                
                <div class="form-group">
                    <label><?php echo $idioma->getText("informaToken") ?></label> 
                    <input type="text"  class="form-control" id="tokenCurrency">
                </div>
                
                
                <div class="form-group">
                    <label><?php echo $idioma->getText("informaPin") ?> </label> 
                    <input type="password"  class="form-control" id="pinCurrency">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-info pull-left" onclick="modalTransferirCurrency();"  id="modalTransacaoReenviarCurrency"><?php echo $idioma->getText("reenviar") ?></button>
                <button type="button" class="btn btn-white" data-dismiss="modal" id="modalTransacaoCancelarCurrency"><?php echo $idioma->getText("cancelar") ?></button>
                <button type="button" class="btn btn-success" onclick="transferirCurrency();"  id="modalTransacaoConfirmarCurrency"><?php echo $idioma->getText("confirmaTransacaoBtn") ?></button>
            </div>
        </div>
    </div>
</div>



<div class="modal inmodal" id="modalTransacaoReais" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content animated bounceInRight">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                
                <h4 class="modal-title"><?php echo $idioma->getText("confirmaTransacao") ?></h4>
            </div>
            <div class="modal-body">
                <p>
                    <strong id="modalTransacaoMeioReais"></strong>
                </p>
                
                <div class="form-group">
                    <label><?php echo $idioma->getText("informaToken") ?> </label> 
                    <input type="text"  class="form-control" id="tokenReais">
                </div>
                
                
                <div class="form-group">
                    <label><?php echo $idioma->getText("informaPin") ?> </label> 
                    <input type="password"  class="form-control" id="pinReais">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-info pull-left" onclick="modalTransferirReais();"  id="modalTransacaoReenviarReais"><?php echo $idioma->getText("reenviar") ?></button>
                <button type="button" class="btn btn-white" data-dismiss="modal" id="modalTransacaoCancelarReais"><?php echo $idioma->getText("cancelar") ?></button>
                <button type="button" class="btn btn-success" onclick="transferirReais();"  id="modalTransacaoConfirmarReais"><?php echo $idioma->getText("confirmaTransacaoBtn") ?></button>
            </div>
        </div>
    </div>
</div>

<div class="modal inmodal" id="modalTransacaoEmpresa" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content animated bounceInRight">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                
                <h4 class="modal-title"><?php echo $idioma->getText("confirmaTransacao") ?></h4>
            </div>
            <div class="modal-body">
                <p>
                    <strong id="modalTransacaoMeioEmpresa"></strong>
                </p>
                
                <div class="form-group">
                    <label><?php echo $idioma->getText("informaToken") ?> </label> 
                    <input type="text"  class="form-control" id="modalTransacaoEmpresaTokenEmpresa">
                </div>
                
                
                <div class="form-group">
                    <label><?php echo $idioma->getText("informaPin") ?> </label> 
                    <input type="password"  class="form-control" id="modalTransacaoEmpresaPinEmpresa">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-info pull-left" onclick="modalTransferirEmpresa();"  id="modalTransacaoReenviarEmpresa"><?php echo $idioma->getText("reenviar") ?></button>
                <button type="button" class="btn btn-white" data-dismiss="modal" id="modalTransacaoCancelarEmpresa"><?php echo $idioma->getText("cancelar") ?></button>
                <button type="button" class="btn btn-success" onclick="transferirEmpresa();"  id="modalTransacaoConfirmarEmpresa"><?php echo $idioma->getText("confirmaTransacaoBtn") ?></button>
            </div>
        </div>
    </div>
</div>
