<?php

$configuracao = isset($_data["configuracao"]) ? $_data["configuracao"] : new Models\Modules\Cadastro\Configuracao();

$moduloDeposito = isset($_data["moduloDeposito"]) ? $_data["moduloDeposito"] : new Models\Modules\Acesso\Modulo();
$moduloSaque = isset($_data["moduloSaque"]) ? $_data["moduloSaque"] : new Models\Modules\Acesso\Modulo();
$moduloTransferencia = isset($_data["moduloTransferencia"]) ? $_data["moduloTransferencia"] : new Models\Modules\Acesso\Modulo();
$moduloNegociacoes = isset($_data["moduloNegociacoes"]) ? $_data["moduloNegociacoes"] : new Models\Modules\Acesso\Modulo();
$moduloServicos = isset($_data["moduloServicos"]) ? $_data["moduloServicos"] : new Models\Modules\Acesso\Modulo();
$moduloCartoes = isset($_data["moduloCartoes"]) ? $_data["moduloCartoes"] : new Models\Modules\Acesso\Modulo();
$moduloCofre = isset($_data["moduloCofre"]) ? $_data["moduloCofre"] : new Models\Modules\Acesso\Modulo();
?>


<?php Utils\Layout::append("inspina/metas", $_data) ?>

<?php Utils\Layout::append("inspina/scripts", $_data) ?>


<?php Utils\Layout::append("inspina/menu", $_data) ?>



    
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
            <div class="row wrapper border-bottom white-bg page-heading">
                <div class="col-lg-10">
                    <h2>Painel de Controle</h2>
                    <ol class="breadcrumb">
                        <li>
                            Configurações
                        </li>
                        <li class="active">
                            <strong>Painel de Controle</strong>
                        </li>
                    </ol>
                </div>
            </div>
</div>  
<br>
    <!-- Main content -->
    <section class="content">

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <?php Utils\Layout::append("mensagem", $_data)?>
                    <div class="panel-heading">
                        Configurações do Sistema
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <form id="form-configuracao" action="<?php echo URLBASE_CLIENT . Utils\Rotas::R_CONFIGURACOES_PAINEL_SALVAR ?>" method="post" enctype="multipart/form-data">
                            
                            <div class="row">
                                <div class="col col-lg-12">
                                    
                                    <div class="tabs-container">
                                        <ul class="nav nav-tabs">
                                            <li class="active"><a data-toggle="tab" href="#tab-transferencia" aria-expanded="true">Transferência</a></li>
                                            <li class=""><a data-toggle="tab" href="#tab-compra-venda" aria-expanded="false">Compra e Venda</a></li>
                                            <li class=""><a data-toggle="tab" href="#tab-dinheiro" aria-expanded="false">Dinheiro</a></li>
                                            <li class=""><a data-toggle="tab" href="#tab-cofre" aria-expanded="false">Investimento</a></li>
                                            <li class=""><a data-toggle="tab" href="#tab-cartao" aria-expanded="false">Cartão</a></li>
                                            <li class=""><a data-toggle="tab" href="#tab-boleto" aria-expanded="false">Boleto</a></li>
                                            <li class=""><a data-toggle="tab" href="#tab-remessa" aria-expanded="false">Remessa</a></li>
                                            <li class=""><a data-toggle="tab" href="#tab-email" aria-expanded="false">Email</a></li>
                                            <li class=""><a data-toggle="tab" href="#tab-deposito-btc" aria-expanded="false">Depósito Btc</a></li>
                                            <li class=""><a data-toggle="tab" href="#tab-permissoes" aria-expanded="false">Permissões</a></li>
                                            <li class=""><a data-toggle="tab" href="#tab-telegram" aria-expanded="false">Telegram</a></li>
                                        </ul>
                                        <div class="tab-content">
                                            
                                            
                                            
                                            <div id="tab-transferencia" class="tab-pane active">
                                                <div class="panel-body">
                                                    
                                                    
                                                    <h4 class="page-header">Transferência</h4>
                                                    <div class="row">
                                                        <div class="col col-lg-3">
                                                            <div class="form-group">
                                                                <label>Reais (informe o valor em R$)</label>
                                                                <input class="form-control valor-real" id="taxaTransferenciaInternaReais" name="taxaTransferenciaInternaReais" value="<?php echo number_format($configuracao->taxaTransferenciaInternaReais, 2, ",", "") ?>" />
                                                            </div>
                                                        </div>
                                                        <div class="col col-lg-3">
                                                            <div class="form-group">
                                                                <label>BTC (informe o valor em BTC)</label>
                                                                <input class="form-control valor-btc" id="valorCartaoExtaxaTransferenciaInternaBtc" name="taxaTransferenciaInternaBtc" value="<?php echo number_format($configuracao->taxaTransferenciaInternaBtc, 8, ",", "") ?>" />
                                                            </div>
                                                        </div>
                                                        <div class="col col-lg-3">
                                                            <div class="form-group">
                                                                <label>Valor máximo para saque sem autorização</label>
                                                                <input class="form-control valor-btc" id="valorMaximoSaqueBtc" name="valorMaximoSaqueBtc" value="<?php echo number_format($configuracao->valorMaximoSaqueBtc, 8, ",", "") ?>" />
                                                            </div>
                                                        </div>
                                                        <div class="col col-lg-3">
                                                            <div class="form-group">
                                                                <label>Taxa da Rede BTC</label>
                                                                <input class="form-control valor-btc" id="taxaRedeBtc" name="taxaRedeBtc" value="<?php echo number_format($configuracao->taxaRedeBtc, 8, ",", "") ?>" />
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            
                                            
                                            <div id="tab-cofre" class="tab-pane">
                                                <div class="panel-body">
                                                    <h4 class="page-header">Configurações do Cofre</h4>
                                                    <div class="row">
                                                        <div class="col col-lg-4">
                                                            <div class="form-group">
                                                                <label>Taxa de uso do Cofre (%)</label>
                                                                <input class="form-control valor-real text-center" id="comissaoUsoCofre" name="comissaoUsoCofre" value="<?php echo number_format($configuracao->comissaoUsoCofre, 2, ",", "") ?>" />
                                                            </div>
                                                        </div>
                                                        <div class="col col-lg-4">
                                                            <div class="form-group">
                                                                <label>Prazo para saque de valores do cofre (dias)</label>
                                                                <input class="form-control numeric text-center" id="prazoDiasSaqueCofre" name="prazoDiasSaqueCofre" value="<?php echo $configuracao->prazoDiasSaqueCofre ?>" />
                                                            </div>
                                                        </div>
                                                        <div class="col col-lg-4">
                                                            <div class="form-group">
                                                                <label>Prazo de duração do contrato (dias)</label>
                                                                <input class="form-control numeric text-center" id="prazoDiasContratoCofre" name="prazoDiasContratoCofre" value="<?php echo $configuracao->prazoDiasContratoCofre ?>" />
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            
                                            
                                            
                                            <div id="tab-compra-venda" class="tab-pane">
                                                <div class="panel-body">
                                                    <h4 class="page-header">Compra e Venda</h4>

                                                    <div class="row">
                                                        <div class="col col-lg-3">
                                                            <div class="form-group">
                                                                <label>Compra Ativa (%)</label>
                                                                <input class="form-control" id="percentualCompra" name="percentualCompra" value="<?php echo number_format($configuracao->percentualCompra, 2, ",", "") ?>" />
                                                            </div>
                                                        </div>
                                                        <div class="col col-lg-3">
                                                            <div class="form-group">
                                                                <label>Compra Passiva (%)</label>
                                                                <input class="form-control valor-real" id="percentualCompraPassiva" name="percentualCompraPassiva" value="<?php echo number_format($configuracao->percentualCompraPassiva, 2, ",", "") ?>" />
                                                            </div>
                                                        </div>
                                                        <div class="col col-lg-3">
                                                            <div class="form-group">
                                                                <label>Venda Ativa (%)</label>
                                                                <input class="form-control" id="percentualVenda" name="percentualVenda" value="<?php echo number_format($configuracao->percentualVenda, 2, ",", "") ?>" />
                                                            </div>
                                                        </div>
                                                        <div class="col col-lg-3">
                                                            <div class="form-group">
                                                                <label>Venda Passiva (%)</label>
                                                                <input class="form-control valor-real" id="percentualVendaPassiva" name="percentualVendaPassiva" value="<?php echo number_format($configuracao->percentualVendaPassiva, 2, ",", "") ?>" />
                                                            </div>
                                                        </div>
                                                    </div>
                                                    
                                                    <h4 class="page-header">Valor mínimo para negociação</h4>
                                                    <div class="row">
                                                        <div class="col col-lg-6">
                                                            <div class="form-group">
                                                                <label>Criptomoedas (BTC)</label>
                                                                <input class="form-control valor-btc" id="volumeMinimoNegociacaoBtc" name="volumeMinimoNegociacaoBtc" value="<?php echo number_format($configuracao->volumeMinimoNegociacaoBtc, 8, ",", "") ?>" />
                                                            </div>
                                                        </div>
                                                        <div class="col col-lg-6">
                                                            <div class="form-group">
                                                                <label>Real (R$)</label>
                                                                <input class="form-control " id="valorMinimoNegociacaoBrl" name="valorMinimoNegociacaoBrl" value="<?php echo number_format($configuracao->valorMinimoNegociacaoBrl, $configuracao->qtdCasasDecimais, ",", "") ?>" />
                                                            </div>
                                                        </div>
                                                    </div>
                                                    
                                                </div>
                                            </div>
                                            
                                            
                                            
                                            <div id="tab-dinheiro" class="tab-pane">
                                                <div class="panel-body">
                                                    <h4 class="page-header">Taxas para Depósito em Dinheiro</h4>
                                                    <div class="row">
                                                        
                                                        <div class="col col-md-2">
                                                            <div class="form-group">
                                                                <label>Depósito até 2 mil (%)</label>
                                                                <input class="form-control text-center" id="percentualDepositos" name="percentualDepositos" value="<?php echo number_format($configuracao->percentualDepositos, 2, ",", "") ?>" />
                                                            </div>
                                                        </div>
                                                        <div class="col col-md-2">
                                                            <div class="form-group">
                                                                <label>Depósito de 2 a 5 mil (%)</label>
                                                                <input class="form-control valor-real text-center" id="depositoDoisCinco" name="depositoDoisCinco" value="<?php echo number_format($configuracao->depositoDoisCinco, 2, ",", "") ?>" />
                                                            </div>
                                                        </div>
                                                        <div class="col col-md-2">
                                                            <div class="form-group">
                                                                <label>Depósito de 5 a 10 mil (%)</label>
                                                                <input class="form-control valor-real text-center" id="depositoCincoDez" name="depositoCincoDez" value="<?php echo number_format($configuracao->depositoCincoDez, 2, ",", "") ?>" />
                                                            </div>
                                                        </div>
                                                        <div class="col col-md-2">
                                                            <div class="form-group">
                                                                <label>Depósito de 10 a 50 mil (%)</label>
                                                                <input class="form-control valor-real text-center"  id="depositoDezCinquenta" name="depositoDezCinquenta" value="<?php echo number_format($configuracao->depositoDezCinquenta, 2, ",", "") ?>" />
                                                            </div>
                                                        </div>
                                                        
                                                        <div class="col col-md-2">
                                                            <div class="form-group">
                                                                <label>Depósito acima de 50 mil (%)</label>
                                                                <input class="form-control valor-real text-center"  id="depositoCinquentaAcima" name="depositoCinquentaAcima" value="<?php echo number_format($configuracao->depositoCinquentaAcima, 2, ",", "") ?>" />
                                                            </div>
                                                        </div>
                                                        
                                                        <div class="col col-md-2">
                                                            <div class="form-group">
                                                                <label>Taxa de estorno de depósitos (%)</label>
                                                                <input class="form-control valor-real text-center"  id="percentualEstornoDeposito" name="percentualEstornoDeposito" value="<?php echo number_format($configuracao->percentualEstornoDeposito, 2, ",", "") ?>" />
                                                            </div>
                                                        </div>
                                                    </div>
                                                    
                                                    
                                                    <h4 class="page-header">Taxas para Depósito em TED / DOC</h4>
                                                    
                                                    <div class="row">
                                                        <div class="col-lg-3">
                                                            <div class="form-group">
                                                                <label>Valor mínimo para saque (R$)</label>
                                                                <input class="form-control valor-real text-center"  id="valorMinSaqueReais" name="valorMinSaqueReais" value="<?php echo number_format($configuracao->valorMinSaqueReais, 2, ",", "") ?>" />
                                                            </div>
                                                        </div>

                                                        <div class="col-lg-3">
                                                            <div class="form-group">
                                                                <label>Comissão cobrada em saques (%)</label>
                                                                <input type="text" id="taxaSaque" name="taxaSaque" value="<?php echo number_format($configuracao->taxaSaque, 2, ",", ".") ?>" class="form-control valor-real text-center"/>
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-3">
                                                            <div class="form-group">
                                                                <label>Comissão TED e DOC (%)</label>
                                                                <input type="text" id="taxaDeposito" name="taxaDeposito" value="<?php echo number_format($configuracao->taxaDeposito, 2, ",", ".") ?>" class="form-control valor-real text-center"/>
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-3">
                                                            <div class="form-group">
                                                                <label>Tarifa de TED (R$)</label>
                                                                <input type="text" id="tarifaTed" name="tarifaTed" value="<?php echo number_format($configuracao->tarifaTed, 2, ",", ".") ?>" class="form-control valor-real text-center"/>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    
                                                    
                                                    <h4 class="page-header">Taxa Para depósito por Boleto bancário </h4>
                                                    <div class="row">
                                                        <div class="col-lg-3">
                                                            <div class="form-group">
                                                                <label>Tarifa para depósito em boletos (%)</label>
                                                                <input class="form-control valor-real text-center"  id="tarifaDepositoBoleto" name="tarifaDepositoBoleto" value="<?php echo number_format($configuracao->tarifaDepositoBoleto, 2, ",", "") ?>" />
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-3">
                                                            <div class="form-group">
                                                                <label>Taxa de depósito por boleto (%)</label>
                                                                <input class="form-control valor-real text-center"  id="taxaDepositoBoleto" name="taxaDepositoBoleto" value="<?php echo number_format($configuracao->taxaDepositoBoleto, 2, ",", "") ?>" />
                                                            </div>
                                                        </div>

                                                    </div>
                                                    
                                                    
                                                    
                                                    <h4 class="page-header">Convidados </h4>
                                                    <div class="row">
                                                        <div class="col-lg-3">
                                                            <div class="form-group">
                                                                <label>Comissão por convite (%)</label>
                                                                <input class="form-control valor-real text-center"  id="comissaoConvite" name="comissaoConvite" value="<?php echo number_format($configuracao->comissaoConvite, 2, ",", "") ?>" />
                                                            </div>
                                                        </div>

                                                    </div>
                                                    
                                                    
                                                    <h4 class="page-header">Prazos</h4>
                                                    <div class="row">
                                                        <div class="col-lg-3">
                                                            <div class="form-group">
                                                                <label>Prazo para validação Depósito (horas)</label>
                                                                <input class="form-control numeric text-center"  id="prazoHorasValidacaoDepositos" name="prazoHorasValidacaoDepositos" value="<?php echo $configuracao->prazoHorasValidacaoDepositos ?>" />
                                                            </div>
                                                        </div>

                                                        <div class="col-lg-3">
                                                            <div class="form-group">
                                                                <label>Prazo para validação Saque (horas)</label>
                                                                <input type="text" id="prazoHorasValidacaoSaques" name="prazoHorasValidacaoSaques" value="<?php echo $configuracao->prazoHorasValidacaoSaques ?>" class="form-control numeric text-center"/>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    
                                                    
                                                    <h4 class="page-header">Configurações</h4>
                                                    <div class="row">
                                                        <div class="col-lg-3">
                                                            <div class="form-group">
                                                                <label>Quantidade de casas decimais</label>
                                                                <input class="form-control numeric text-center"  id="qtdCasasDecimais" name="qtdCasasDecimais" value="<?php echo $configuracao->qtdCasasDecimais ?>" />
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            
                                            
                                            
                                            
                                            <div id="tab-cartao" class="tab-pane">
                                                <div class="panel-body">
                                                    
                                                    <h4 class="page-header">Cartão</h4>
                                                    <div class="row">
                                                        <div class="col-lg-3 ">
                                                            <div class="form-group">
                                                                <label>Aquisição de Cartão (R$) </label>
                                                                <input type="text" id="valorCartao" name="valorCartao" value="<?php echo number_format($configuracao->valorCartao, 2, ",", ".") ?>" class="form-control valor-real text-center"/>
                                                            </div>
                                                        </div>
                                                        
                                                        <div class="col-lg-3 ">
                                                            <div class="form-group">
                                                                <label>Mensalidade (R$)</label>
                                                                <input type="text" id="valorMensalidadeCartao" name="valorMensalidadeCartao" value="<?php echo number_format($configuracao->valorMensalidadeCartao, 2, ",", ".") ?>" class="form-control valor-real text-center"/>
                                                            </div>
                                                        </div>
                                                        
                                                        <div class="col-lg-3 ">
                                                            <div class="form-group">
                                                                <label>Taxa de Recarga (%)</label>
                                                                <input type="text" id="taxaRecargaCartao" name="taxaRecargaCartao" value="<?php echo number_format($configuracao->taxaRecargaCartao, 2, ",", ".") ?>" class="form-control valor-real text-center"/>
                                                            </div>
                                                        </div>
                                                        
                                                        
                                                        <div class="col-lg-3 ">
                                                            <div class="form-group">
                                                                <label>Prazo para recarga (horas)</label>
                                                                <input type="text" id="tempoRecargaCartao" name="tempoRecargaCartao" value="<?php echo $configuracao->tempoRecargaCartao ?>" class="form-control numeric text-center"/>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    
                                                </div>
                                            </div>
                                            
                                            
                                            
                                            <div id="tab-boleto" class="tab-pane">
                                                <div class="panel-body">
                                                    <h4 class="page-header">Boleto</h4>
                                                    <div class="row">
                                                        <div class="col-lg-4 ">
                                                            <div class="form-group">
                                                                <label>Taxa de comissão (%)</label>
                                                                <input type="text" id="taxaBoleto" name="taxaBoleto" value="<?php echo number_format($configuracao->taxaBoleto, 2, ",", ".") ?>" class="form-control valor-real text-center"/>
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-4 ">
                                                            <div class="form-group">
                                                                <label>Valor mínimo (R$)</label>
                                                                <input type="text" id="valorMinimoBoleto" name="valorMinimoBoleto" value="<?php echo number_format($configuracao->valorMinimoBoleto, 2, ",", ".") ?>" class="form-control valor-real text-center"/>
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-4 ">
                                                            <div class="form-group">
                                                                <label>Valor máximo (R$)</label>
                                                                <input type="text" id="valorMaximoBoleto" name="valorMaximoBoleto" value="<?php echo number_format($configuracao->valorMaximoBoleto, 2, ",", ".") ?>" class="form-control valor-real text-center"/>
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-4 ">
                                                            <div class="form-group">
                                                                <label>Prazo para pagamento (Horas)</label>
                                                                <input type="text" id="prazoPagamentoBoleto" name="prazoPagamentoBoleto" value="<?php echo $configuracao->prazoPagamentoBoleto ?>" class="form-control text-center numeric"/>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            
                                            
                                            
                                            <div id="tab-remessa" class="tab-pane">
                                                <div class="panel-body">
                                                    <h4 class="page-header">Remessa de Dinheiro</h4>
                                                    <div class="row">
                                                        <div class="col-lg-4 ">
                                                            <div class="form-group">
                                                                <label>Taxa de comissão (%)</label>
                                                                <input type="text" id="taxaRemessa" name="taxaRemessa" value="<?php echo number_format($configuracao->taxaRemessa, 2, ",", ".") ?>" class="form-control valor-real text-center"/>
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-4 ">
                                                            <div class="form-group">
                                                                <label>Valor mínimo (R$)</label>
                                                                <input type="text" id="valorMinimoRemessa" name="valorMinimoRemessa" value="<?php echo number_format($configuracao->valorMinimoRemessa, 2, ",", ".") ?>" class="form-control valor-real text-center"/>
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-4 ">
                                                            <div class="form-group">
                                                                <label>Valor máximo (R$)</label>
                                                                <input type="text" id="valorMaximoRemessa" name="valorMaximoRemessa" value="<?php echo number_format($configuracao->valorMaximoRemessa, 2, ",", ".") ?>" class="form-control valor-real text-center"/>
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-4 ">
                                                            <div class="form-group">
                                                                <label>Prazo para efetuação (Dias)</label>
                                                                <input type="text" id="prazoEfetuacaoRemessa" name="prazoEfetuacaoRemessa" value="<?php echo $configuracao->prazoEfetuacaoRemessa ?>" class="form-control text-center numeric"/>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            
                                            
                                            
                                            
                                            
                                            
                                            <div id="tab-email" class="tab-pane">
                                                <div class="panel-body">
                                                    <h4 class="page-header">Email</h4>
                                                    <div class="row">
                                                        <div class="col col-lg-6">
                                                            <div class="form-group">
                                                                <label>Nome da Conta de Email</label>
                                                                <input class="form-control" id="emailNome" name="emailNome" maxlength="200"  value="<?php echo $configuracao->emailNome ?>" />
                                                            </div>
                                                        </div>
                                                        <div class="col col-lg-6">
                                                            <div class="form-group">
                                                                <label>Host SMTP</label>
                                                                <input class="form-control" id="emailSmtp" name="emailSmtp" maxlength="200"  value="<?php echo $configuracao->emailSmtp ?>" />
                                                            </div>
                                                        </div>
                                                    </div>

                                                    <div class="row">
                                                        <div class="col col-lg-2">
                                                            <div class="form-group">
                                                                <label>Porta</label>
                                                                <input class="form-control" id="emailPorta" name="emailPorta" maxlength="4"  value="<?php echo $configuracao->emailPorta ?>" />
                                                            </div>
                                                        </div>
                                                        <div class="col col-lg-5">
                                                            <div class="form-group">
                                                                <label>Usuário</label>
                                                                <input type="email" class="form-control" id="emailUsuario" name="emailUsuario" maxlength="200"  value="<?php echo $configuracao->emailUsuario ?>" />
                                                            </div>
                                                        </div>
                                                        <div class="col col-lg-5">
                                                            <div class="form-group">
                                                                <label>Senha</label>
                                                                <input type="password" class="form-control" id="emailSenha" name="emailSenha" maxlength="200"  value="<?php echo $configuracao->emailSenha ?>" />
                                                            </div>
                                                        </div>
                                                    </div>

                                                    <div class="row">
                                                        <div class="col col-lg-12">
                                                            <div class="form-group">
                                                                <label>
                                                                    <input type="checkbox" name="emailSmtpAuth" value="1" id="emailSmtpAuth" checked="<?php echo ($configuracao->emailSmtpAuth > 0 ? "checked='true'" : "") ?>"> Requer SSL?
                                                                </label>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            
                                            <div id="tab-deposito-btc" class="tab-pane">
                                                <div class="panel-body">
                                                    
                                                    
                                                    <h4 class="page-header">Depósito Btc</h4>
                                                    
                                                    <div class="row">
                                                        <div class="col col-lg-6">
                                                            <div class="form-group">
                                                                <label>Quantidade mínima de confirmações de uma transação</label>
                                                                <input class="form-control numeric text-center" id="qtdMinConfirmacoesTransacao" name="qtdMinConfirmacoesTransacao" value="<?php echo $configuracao->qtdMinConfirmacoesTransacao ?>" />
                                                            </div>
                                                        </div>
                                                        <div class="col col-lg-6">
                                                            <div class="form-group">
                                                                <label>Quantidade máxima de confirmações de uma transação</label>
                                                                <input class="form-control numeric text-center" id="qtdMaxConfirmacoesTransacao" name="qtdMaxConfirmacoesTransacao" value="<?php echo $configuracao->qtdMaxConfirmacoesTransacao ?>" />
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            
                                            
                                            
                                            
                                            
                                            
                                            <div id="tab-permissoes" class="tab-pane">
                                                <div class="panel-body">
                                                    
                                                    <div class="row">
                                                        <div class="col col-sm-6">
                                                            <div class="checkbox m-r-xs">
                                                                <input type="checkbox" id="statusNovosCadastros" name="statusNovosCadastros" <?php echo ($configuracao->statusNovosCadastros > 0 ? "checked" : "") ?> value="1">
                                                                <label for="statusNovosCadastros">
                                                                    Habilitar cadastro de novos clientes.
                                                                </label>
                                                            </div>
                                                        </div>
                                                        <div class="col col-sm-6">
                                                            <div class="checkbox m-r-xs">
                                                                <input type="checkbox" id="statusLoginSistema" name="statusLoginSistema" <?php echo ($configuracao->statusLoginSistema > 0 ? "checked" : "") ?> value="1">
                                                                <label for="statusLoginSistema">
                                                                    Habilitar Login de clientes.
                                                                </label>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    
                                                    <div class="row">
                                                        <div class="col col-sm-6">
                                                            <div class="checkbox m-r-xs">
                                                                <input type="checkbox" id="statusUpgradePerfil" name="statusUpgradePerfil" <?php echo ($configuracao->statusUpgradePerfil > 0 ? "checked" : "") ?> value="1">
                                                                <label for="statusUpgradePerfil">
                                                                    Habilitar solicitações de upgrade de perfil.
                                                                </label>
                                                            </div>
                                                        </div>
                                                        
                                                        <div class="col col-sm-6">
                                                            <div class="checkbox m-r-xs">
                                                                <input type="checkbox" id="statusCarteiras" name="statusCarteiras" <?php echo ($configuracao->statusCarteiras > 0 ? "checked" : "") ?> value="1">
                                                                <label for="statusCarteiras">
                                                                    Habilitar criação, exibiçao e utilização de carteiras de criptomoedas.
                                                                </label>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    
                                                    
                                                    
                                                    <div class="row">
                                                        <div class="col col-sm-6">
                                                            <div class="checkbox m-r-xs">
                                                                <input type="checkbox" id="statusTransferenciaBrl" name="statusTransferenciaBrl" <?php echo ($configuracao->statusTransferenciaBrl > 0 ? "checked" : "") ?> value="1">
                                                                <label for="statusTransferenciaBrl">
                                                                    Habilitar transferência de Reais.
                                                                </label>
                                                            </div>
                                                        </div>
                                                        
                                                        <div class="col col-sm-6">
                                                            <div class="checkbox m-r-xs">
                                                                <input type="checkbox" id="statusTransferenciaCurrency" name="statusTransferenciaCurrency" <?php echo ($configuracao->statusTransferenciaCurrency > 0 ? "checked" : "") ?> value="1">
                                                                <label for="statusTransferenciaCurrency">
                                                                    Habilitar transferência de criptomoedas.
                                                                </label>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    
                                                    <div class="row">
                                                        <div class="col col-sm-6">
                                                            <div class="checkbox m-r-xs">
                                                                <input type="checkbox" id="statusDepositoBrl" name="statusDepositoBrl" <?php echo ($configuracao->statusDepositoBrl > 0 ? "checked" : "") ?> value="1">
                                                                <label for="statusDepositoBrl">
                                                                    Habilitar deposito de Reais.
                                                                </label>
                                                            </div>
                                                        </div>
                                                        
                                                        <div class="col col-sm-6">
                                                            <div class="checkbox m-r-xs">
                                                                <input type="checkbox" id="statusDepositoCurrency" name="statusDepositoCurrency" <?php echo ($configuracao->statusDepositoCurrency > 0 ? "checked" : "") ?> value="1">
                                                                <label for="statusDepositoCurrency">
                                                                    Habilitar deposito de criptomoedas.
                                                                </label>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    
                                                    
                                                    <br>
                                                    <div class="row">
                                                        <div class="col col-lg-12">
                                                            <div class="form-group">
                                                                <label>Mensagem para exibição no site</label>
                                                                <textarea class="form-control" id="alertaSite" name="alertaSite"  style="height: 100px;"><?php echo $configuracao->alertaSite ?></textarea>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    
                                                    <div class="row">
                                                        <div class="col col-lg-4">
                                                            <div class="form-group">
                                                                <label>Exibir o alerta acima até: </label>
                                                                <input class="form-control numeric text-center" id="dataFinalAlertaSite" name="dataFinalAlertaSite" value="<?php echo ($configuracao->dataFinalAlertaSite ? $configuracao->dataFinalAlertaSite->formatar(Utils\Data::FORMATO_PT_BR) : "") ?>" />
                                                            </div>
                                                        </div>
                                                        
                                                        <div class="col col-lg-4">
                                                            <div class="form-group">
                                                                <label>Cor da mensagem: </label>
                                                                <select class="form-control" id="tipoAlertaSite" name="tipoAlertaSite">
                                                                    <option value="null">Selecione o tipo de alerta</option>
                                                                    <option value="azul" <?php echo ($configuracao->tipoAlertaSite == "azul" ? "selected" : "") ?>  >Azul</option>
                                                                    <option value="vermelho" <?php echo ($configuracao->tipoAlertaSite == "vermelho" ? "selected" : "") ?>>Vermelho</option>
                                                                    <option value="amarelo" <?php echo ($configuracao->tipoAlertaSite == "amarelo" ? "selected" : "") ?>>Amarelo</option>
                                                                </select>
                                                            </div>
                                                        </div>
                                                        <div class="col col-lg-4">
                                                            <div class="form-group">
                                                                <div class="checkbox m-r-xs">
                                                                    <input type="checkbox" id="exibirMensagemSite" name="exibirMensagemSite" <?php echo ($configuracao->exibirMensagemSite > 0 ? "checked" : "") ?> value="1">
                                                                    <label for="exibirMensagemSite">
                                                                        Liberar mensagem para exibição no site
                                                                    </label>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        
                                                    </div>
                                                    
                                                    <div class="row">
                                                        <div class="col col-xs-12">
                                                            <h4 class="page-header">Habilitação de módulos</h4>
                                                        </div>
                                                    </div>
                                                    
                                                    <div class="row">
                                                        <div class="col col-lg-2">
                                                            <div class="form-group">
                                                                <label>Módulo Depósito: </label>
                                                                <div class="switch">
                                                                    <div class="onoffswitch">
                                                                        <input type="checkbox" class="onoffswitch-checkbox" name="modulo-deposito" id="modulo-deposito" value="1"  <?php echo ($moduloDeposito->visivelCliente > 0 ? "checked" : "") ?>>
                                                                        <label class="onoffswitch-label" for="modulo-deposito">
                                                                            <span class="onoffswitch-inner"></span>
                                                                            <span class="onoffswitch-switch"></span>
                                                                        </label>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        
                                                        <div class="col col-lg-2">
                                                            <div class="form-group">
                                                                <label>Módulo Saque: </label>
                                                                <div class="switch">
                                                                    <div class="onoffswitch">
                                                                        <input type="checkbox" class="onoffswitch-checkbox" name="modulo-saque" id="modulo-saque" value="1"  <?php echo ($moduloSaque->visivelCliente > 0 ? "checked" : "") ?>>
                                                                        <label class="onoffswitch-label" for="modulo-saque">
                                                                            <span class="onoffswitch-inner"></span>
                                                                            <span class="onoffswitch-switch"></span>
                                                                        </label>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        
                                                        <div class="col col-lg-2">
                                                            <div class="form-group">
                                                                <label>Módulo Transferência: </label>
                                                                <div class="switch">
                                                                    <div class="onoffswitch">
                                                                        <input type="checkbox" class="onoffswitch-checkbox" name="modulo-transferencia" id="modulo-transferencia" value="1"  <?php echo ($moduloTransferencia->visivelCliente > 0 ? "checked" : "") ?>>
                                                                        <label class="onoffswitch-label" for="modulo-transferencia">
                                                                            <span class="onoffswitch-inner"></span>
                                                                            <span class="onoffswitch-switch"></span>
                                                                        </label>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        
                                                        <div class="col col-lg-2">
                                                            <div class="form-group">
                                                                <label>Módulo Negociações: </label>
                                                                <div class="switch">
                                                                    <div class="onoffswitch">
                                                                        <input type="checkbox" class="onoffswitch-checkbox" name="modulo-negociacoes" id="modulo-negociacoes" value="1" <?php echo ($moduloNegociacoes->visivelCliente > 0 ? "checked" : "") ?>>
                                                                        <label class="onoffswitch-label" for="modulo-negociacoes">
                                                                            <span class="onoffswitch-inner"></span>
                                                                            <span class="onoffswitch-switch"></span>
                                                                        </label>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        
                                                        <div class="col col-lg-2">
                                                            <div class="form-group">
                                                                <label>Módulo Serviços: </label>
                                                                <div class="switch">
                                                                    <div class="onoffswitch">
                                                                        <input type="checkbox" class="onoffswitch-checkbox" name="modulo-servicos" id="modulo-servicos" value="1" <?php echo ($moduloServicos->visivelCliente > 0 ? "checked" : "") ?>>
                                                                        <label class="onoffswitch-label" for="modulo-servicos">
                                                                            <span class="onoffswitch-inner"></span>
                                                                            <span class="onoffswitch-switch"></span>
                                                                        </label>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        
                                                        <div class="col col-lg-2">
                                                            <div class="form-group">
                                                                <label>Módulo Cartões: </label>
                                                                <div class="switch">
                                                                    <div class="onoffswitch">
                                                                        <input type="checkbox" class="onoffswitch-checkbox" name="modulo-cartoes" id="modulo-cartoes" value="1" <?php echo ($moduloCartoes->visivelCliente > 0 ? "checked" : "") ?>>
                                                                        <label class="onoffswitch-label" for="modulo-cartoes">
                                                                            <span class="onoffswitch-inner"></span>
                                                                            <span class="onoffswitch-switch"></span>
                                                                        </label>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <br>
                                                    <div class="row">
                                                        <div class="col col-lg-2">
                                                            <div class="form-group">
                                                                <label>Módulo Cofre:</label>
                                                                <div class="switch">
                                                                    <div class="onoffswitch">
                                                                        <input type="checkbox" class="onoffswitch-checkbox" name="modulo-cofre" id="modulo-cofre" value="1" <?php echo ($moduloCofre->visivelCliente > 0 ? "checked" : "") ?>>
                                                                        <label class="onoffswitch-label" for="modulo-cofre">
                                                                            <span class="onoffswitch-inner"></span>
                                                                            <span class="onoffswitch-switch"></span>
                                                                        </label>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    
                                                </div>
                                            </div>
                                            
                                            <div id="tab-telegram" class="tab-pane">
                                                <div class="panel-body">
                                                    
                                                    <?php Utils\Layout::view("index_telegram_bots", $_data)?>
                                                    
                                                </div>
                                            </div>
                                        </div>


                                    </div>
                                    
                                </div>
                            </div>
                            
                            
                            
                            <div class="row">
                                <div class="col col-lg-12 text-center">
                                    <br><br><br>
                                    
                                    <?php if (\Models\Modules\Acesso\RotinaRn::validar(\Utils\Rotas::R_PAINELCONTROLE, \Utils\Constantes::EDITAR)) {  ?>
                                    <button class="btn btn-primary btn-lg" type="submit" id="btn-salvar">
                                        Salvar Alterações
                                    </button>
                                    <?php } ?>
                                </div>
                            </div>
                            
                        </form>
                    </div>
                    <!-- /.panel-body -->

                </div>
            </div>

        </div>

        <a  id="openOrder" target="_BLANK"></a>
    </section>
    
    <div class="clearfix"></div>
</div>

<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>

<script>
    $(document).ready(function () {

        $("#dataFinalAlertaSite").datepicker({format: "dd/mm/yyyy"}).mask("99/99/9999");

        $("#percentualSaque, #percentualCompra, #percentualVenda, #percentualDepositos, #valorCartao, #valorCartaoEx, #valorMensalidadeCartao, .valor-real, #taxaDepositoBoleto").keydown(function (event) {
            if (event.keyCode !== 9) {
                $(this).val(currency($(this).val(), 2, 8, event.keyCode));
                event.preventDefault();
            }
        });
        
        $("#valorMinimoNegociacaoBrl").keydown(function (event) {
            if (event.keyCode !== 9) {
                $(this).val(currency($(this).val(), <?php echo $configuracao->qtdCasasDecimais ?>, 8, event.keyCode));
                event.preventDefault();
            }
        });
        
        $(".valor-btc").keydown(function (event) {
            if (event.keyCode !== 9) {
                $(this).val(currency($(this).val(), 8, 8, event.keyCode));
                event.preventDefault();
            }
        });
        
        $("#emailPorta, .numeric").numeric();
        
        $("#form-configuracao").ajaxForm({
            dataType: "json",
            beforeSubmit: function () {
                $("#btn-salvar").prop("disabled", true);
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        location = "<?php echo URLBASE_CLIENT . Utils\Rotas::R_PAINELCONTROLE ?>";
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#btn-salvar").prop("disabled", false);
            }
        });
        
    });
    
    
    
    
</script>

