<?php

    $mensagens = (isset($_data["mensagensTelegram"]) ?  $_data["mensagensTelegram"] : Array());
    $grupos= (isset($_data["gruposTelegram"]) ?  $_data["gruposTelegram"] : Array());
    $bots = (isset($_data["botsTelegram"]) ?  $_data["botsTelegram"] : Array());

?>

<h4 class="page-header">Telegram</h4>

<div class="row">
    <div class="col col-lg-6 text-center">
        <button type="button" class="btn btn-success" onclick="listarBots();">
            Bots Cadastrados
        </button>
    </div>
    <div class="col col-lg-6 text-center">
        <button type="button" class="btn btn-success" onclick="listarGrupos();">
            Grupos Cadastrados
        </button>
    </div>
</div>


<br><br>
<div class="row">
    <div class="col-lg-12">
        <div class="tabs-container">
            <ul class="nav nav-tabs">
                <li class="active"><a data-toggle="tab" href="#tab-bots-telegram-1" aria-expanded="true"> Português</a></li>
                <li class=""><a data-toggle="tab" href="#tab-bots-telegram-2" aria-expanded="false">Inglês</a></li>
                <li class=""><a data-toggle="tab" href="#tab-bots-telegram-3" aria-expanded="false">Espanhol</a></li>
            </ul>
            <div class="tab-content">
                <div id="tab-bots-telegram-1" class="tab-pane active">
                    <?php 
                    $telegramMensagem = (isset($mensagens[1]) ? $mensagens[1] : new \Models\Modules\Cadastro\TelegramMensagemAutomatica());
                    ?>
                    <div class="panel-body">
                        
                        <div class="form-group">
                            <label>Mensagem: </label>
                            <textarea id="tab-bots-telegram-1-mensagem" style="height: 200px;" class="form-control"><?php echo $telegramMensagem->conteudo ?></textarea>
                        </div>
                        
                        <div class="row">
                            <div class="col col-lg-2">
                                <div class="form-group">
                                    <label>Bot: </label>
                                    <select id="tab-bots-telegram-1-bot"  class="form-control">
                                        <?php
                                        foreach ($bots as $botTelegram) {
                                            ?>
                                        <option value="<?php echo $botTelegram->id ?>" <?php echo ($telegramMensagem->idTelegramBot == $botTelegram->id ? "selected" : "") ?> ><?php echo $botTelegram->nome ?></option>
                                            <?php
                                        }
                                        ?>
                                    </select>
                                </div>
                            </div>
                            <div class="col col-lg-3">
                                <div class="form-group">
                                    <label>Grupo: </label>
                                    <select id="tab-bots-telegram-1-grupo" class="form-control">
                                        <?php
                                        foreach ($grupos as $grupoTelegram) {
                                            ?>
                                        <option value="<?php echo $grupoTelegram->id ?>" <?php echo ($telegramMensagem->idTelegramGrupo == $grupoTelegram->id ? "selected" : "") ?>  ><?php echo $grupoTelegram->nome ?></option>
                                            <?php
                                        }
                                        ?>
                                    </select>
                                </div>
                            </div>
                            <div class="col col-lg-2">
                                <div class="form-group">
                                    <label>Periodicidade</label>
                                    <select id="tab-bots-telegram-1-periodicidade"  class="form-control">
                                        <option value="1H" <?php echo ($telegramMensagem->periodicidade == "1H" ? "selected" : "") ?>>A cada 1 Hora</option>
                                        <option value="2H" <?php echo ($telegramMensagem->periodicidade == "2H" ? "selected" : "") ?>>A cada 2 Horas</option>
                                        <option value="4H" <?php echo ($telegramMensagem->periodicidade == "4H" ? "selected" : "") ?>>A cada 4 Horas</option>
                                        <option value="6H" <?php echo ($telegramMensagem->periodicidade == "6H" ? "selected" : "") ?>>A cada 6 Horas</option>
                                        <option value="12H" <?php echo ($telegramMensagem->periodicidade == "12H" ? "selected" : "") ?>>A cada 12 Horas</option>
                                        <option value="24H" <?php echo ($telegramMensagem->periodicidade == "24H" ? "selected" : "") ?>>A cada 24 Horas</option>
                                    </select>
                                </div>
                            </div>
                            
                            
                            <div class="col col-lg-3">
                                <div class="form-group">
                                    <label>Slug: </label>
                                    <input type="text" class="form-control slug-text" id="tab-bots-telegram-1-slug" value="<?php echo $telegramMensagem->slug ?>" />
                                </div>
                            </div>
                            
                            <div class="col col-lg-2 text-center">
                                <br>
                                <button type="button" class="btn  btn-<?php echo ($telegramMensagem->ativo > 0 ? "danger" : "primary") ?>" id="tab-bots-telegram-1-status"
                                        onclick="alterarStatusAtivoMensagemTelegram('<?php echo \Utils\Criptografia::encriptyPostId($telegramMensagem->id)?>')">
                                    <?php echo ($telegramMensagem->ativo > 0 ? "Desativar" : "Ativar") ?>
                                </button>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col col-lg-12 text-center ">
                                <button type="button" class="btn btn-success " onclick="salvarMensagemTelegram('<?php echo $telegramMensagem->id ?>');" >
                                    Atualizar Mensagem PT
                                </button>
                            </div>
                        </div>
                        
                    </div>
                </div>
                <div id="tab-bots-telegram-2" class="tab-pane">
                        
                    <?php 
                    $telegramMensagem2 = (isset($mensagens[2]) ? $mensagens[2] : new \Models\Modules\Cadastro\TelegramMensagemAutomatica());
                    ?>
                    <div class="panel-body">
                        
                        <div class="form-group">
                            <label>Mensagem: </label>
                            <textarea id="tab-bots-telegram-2-mensagem" style="height: 200px;" class="form-control"><?php echo $telegramMensagem2->conteudo ?></textarea>
                        </div>
                        
                        <div class="row">
                            <div class="col col-lg-2">
                                <div class="form-group">
                                    <label>Bot: </label>
                                    <select id="tab-bots-telegram-2-bot"  class="form-control">
                                        <?php
                                        foreach ($bots as $botTelegram) {
                                            ?>
                                        <option value="<?php echo $botTelegram->id ?>" <?php echo ($telegramMensagem2->idTelegramBot == $botTelegram->id ? "selected" : "") ?> ><?php echo $botTelegram->nome ?></option>
                                            <?php
                                        }
                                        ?>
                                    </select>
                                </div>
                            </div>
                            <div class="col col-lg-3">
                                <div class="form-group">
                                    <label>Grupo: </label>
                                    <select id="tab-bots-telegram-2-grupo" class="form-control">
                                        <?php
                                        foreach ($grupos as $grupoTelegram) {
                                            ?>
                                        <option value="<?php echo $grupoTelegram->id ?>" <?php echo ($telegramMensagem2->idTelegramGrupo == $grupoTelegram->id ? "selected" : "") ?>  ><?php echo $grupoTelegram->nome ?></option>
                                            <?php
                                        }
                                        ?>
                                    </select>
                                </div>
                            </div>
                            <div class="col col-lg-2">
                                <div class="form-group">
                                    <label>Periodicidade</label>
                                    <select id="tab-bots-telegram-2-periodicidade"  class="form-control">
                                        <option value="1H" <?php echo ($telegramMensagem2->periodicidade == "1H" ? "selected" : "") ?>>A cada 1 Hora</option>
                                        <option value="2H" <?php echo ($telegramMensagem2->periodicidade == "2H" ? "selected" : "") ?>>A cada 2 Horas</option>
                                        <option value="4H" <?php echo ($telegramMensagem2->periodicidade == "4H" ? "selected" : "") ?>>A cada 4 Horas</option>
                                        <option value="6H" <?php echo ($telegramMensagem2->periodicidade == "6H" ? "selected" : "") ?>>A cada 6 Horas</option>
                                        <option value="12H" <?php echo ($telegramMensagem2->periodicidade == "12H" ? "selected" : "") ?>>A cada 12 Horas</option>
                                        <option value="24H" <?php echo ($telegramMensagem2->periodicidade == "24H" ? "selected" : "") ?>>A cada 24 Horas</option>
                                    </select>
                                </div>
                            </div>
                            
                            <div class="col col-lg-3">
                                <div class="form-group">
                                    <label>Slug: </label>
                                    <input type="text" class="form-control slug-text" id="tab-bots-telegram-2-slug" value="<?php echo $telegramMensagem2->slug ?>" />
                                </div>
                            </div>
                            
                            <div class="col col-lg-2 text-center">
                                <br>
                                <button type="button" class="btn  btn-<?php echo ($telegramMensagem2->ativo > 0 ? "danger" : "primary") ?>" id="tab-bots-telegram-2-status"
                                        onclick="alterarStatusAtivoMensagemTelegram('<?php echo \Utils\Criptografia::encriptyPostId($telegramMensagem2->id)?>')">
                                    <?php echo ($telegramMensagem2->ativo > 0 ? "Desativar" : "Ativar") ?>
                                </button>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col col-lg-12 text-center ">
                                <button type="button" class="btn btn-success " onclick="salvarMensagemTelegram('<?php echo $telegramMensagem2->id?>');" >
                                    Atualizar Mensagem EN
                                </button>
                            </div>
                        </div>
                        
                    </div>
                </div>
                
                
                <div id="tab-bots-telegram-3" class="tab-pane">
                        
                    <?php 
                    $telegramMensagem3 = (isset($mensagens[3]) ? $mensagens[3] : new \Models\Modules\Cadastro\TelegramMensagemAutomatica());
                    ?>
                    <div class="panel-body">
                        
                        <div class="form-group">
                            <label>Mensagem: </label>
                            <textarea id="tab-bots-telegram-3-mensagem" style="height: 200px;" class="form-control"><?php echo $telegramMensagem3->conteudo ?></textarea>
                        </div>
                        
                        <div class="row">
                            <div class="col col-lg-2">
                                <div class="form-group">
                                    <label>Bot: </label>
                                    <select id="tab-bots-telegram-3-bot"  class="form-control">
                                        <?php
                                        foreach ($bots as $botTelegram) {
                                            ?>
                                        <option value="<?php echo $botTelegram->id ?>" <?php echo ($telegramMensagem3->idTelegramBot == $botTelegram->id ? "selected" : "") ?> ><?php echo $botTelegram->nome ?></option>
                                            <?php
                                        }
                                        ?>
                                    </select>
                                </div>
                            </div>
                            <div class="col col-lg-3"> 
                                <div class="form-group">
                                    <label>Grupo: </label>
                                    <select id="tab-bots-telegram-3-grupo" class="form-control">
                                        <?php
                                        foreach ($grupos as $grupoTelegram) {
                                            ?>
                                        <option value="<?php echo $grupoTelegram->id ?>" <?php echo ($telegramMensagem3->idTelegramGrupo == $grupoTelegram->id ? "selected" : "") ?>  ><?php echo $grupoTelegram->nome ?></option>
                                            <?php
                                        }
                                        ?>
                                    </select>
                                </div>
                            </div>
                            <div class="col col-lg-2">
                                <div class="form-group">
                                    <label>Periodicidade</label>
                                    <select id="tab-bots-telegram-3-periodicidade"  class="form-control">
                                        <option value="1H" <?php echo ($telegramMensagem3->periodicidade == "1H" ? "selected" : "") ?>>A cada 1 Hora</option>
                                        <option value="2H" <?php echo ($telegramMensagem3->periodicidade == "2H" ? "selected" : "") ?>>A cada 2 Horas</option>
                                        <option value="4H" <?php echo ($telegramMensagem3->periodicidade == "4H" ? "selected" : "") ?>>A cada 4 Horas</option>
                                        <option value="6H" <?php echo ($telegramMensagem3->periodicidade == "6H" ? "selected" : "") ?>>A cada 6 Horas</option>
                                        <option value="12H" <?php echo ($telegramMensagem3->periodicidade == "12H" ? "selected" : "") ?>>A cada 12 Horas</option>
                                        <option value="24H" <?php echo ($telegramMensagem3->periodicidade == "24H" ? "selected" : "") ?>>A cada 24 Horas</option>
                                    </select>
                                </div>
                            </div>
                            
                            
                            <div class="col col-lg-3">
                                <div class="form-group">
                                    <label>Slug: </label>
                                    <input type="text" class="form-control slug-text" id="tab-bots-telegram-3-slug" value="<?php echo $telegramMensagem3->slug ?>" />
                                </div>
                            </div>
                            
                            <div class="col col-lg-2 text-center">
                                <br>
                                <button type="button" class="btn  btn-<?php echo ($telegramMensagem3->ativo > 0 ? "danger" : "primary") ?>" id="tab-bots-telegram-3-status"
                                        onclick="alterarStatusAtivoMensagemTelegram('<?php echo \Utils\Criptografia::encriptyPostId($telegramMensagem3->id)?>')">
                                    <?php echo ($telegramMensagem3->ativo > 0 ? "Desativar" : "Ativar") ?>
                                </button>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col col-lg-12 text-center ">
                                <button type="button" class="btn btn-success " onclick="salvarMensagemTelegram('<?php echo $telegramMensagem3->id?>');" >
                                    Atualizar Mensagem ES
                                </button> 
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>


        </div>
    </div>
</div>


<div class="modal fade" id="modalListaBotsTelegram" tabindex="-1" role="dialog" aria-labelledby="modalListaBotsTelegram" aria-hidden="true" >
    <div class="modal-dialog modal-md" >
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="cadastroContaLabel">Listagem de Bots</h4>
            </div>
            <div class="modal-body">
                
                <div class="row">
                    <div class="col col-lg-12 text-center">
                        <button class="btn btn-primary" type="button" onclick="cadastroBotTelegram('<?php echo \Utils\Criptografia::encriptyPostId(0)?>')">
                            Novo Cadastro
                        </button>
                    </div>
                </div>
                <br>
                <table class="table table-bordered table-condensed table-striped">
                    <thead>
                        <tr>
                            <th>Nome</th>
                            <th>Editar</th>
                            <th>Ativar/Desativar</th>
                        </tr>
                    </thead>
                    <tbody id="modalListaBotsTelegramBody">
                        
                    </tbody>
                </table>
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="modalListaBotsTelegramFechar" data-dismiss="modal">Fechar</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>



<div class="modal fade" id="modalCadastroBotsTelegram" tabindex="-1" role="dialog" aria-labelledby="modalCadastroBotsTelegram" aria-hidden="true" >
    <div class="modal-dialog" >
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="cadastroContaLabel">Cadastro de Bot Telegram</h4>
            </div>
            <div class="modal-body">
                <input type="hidden" class="form-control" id="modalCadastroBotsTelegramId" />
                <div class="row">
                    <div class="col col-lg-6">
                        <div class="form-group">
                            <label class="control-label">Nome</label>
                            <input type="text" class="form-control" id="modalCadastroBotsTelegramNome" maxlength="200" />
                        </div>
                    </div>
                    <div class="col col-lg-6">
                        <div class="form-group">
                            <label class="control-label">Chave</label>
                            <input type="text" class="form-control" id="modalCadastroBotsTelegramChave" maxlength="200" />
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="modalCadastroBotsTelegramFechar" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-primary" onclick="salvarBotTelegram();" id="modalCadastroBotsTelegramSalvar" >Salvar</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>


<div class="modal fade" id="modalListaGruposTelegram" tabindex="-1" role="dialog" aria-labelledby="modalListaGruposTelegram" aria-hidden="true" >
    <div class="modal-dialog modal-md" >
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="cadastroContaLabel">Listagem de Grupos</h4>
            </div>
            <div class="modal-body">
                
                <div class="row">
                    <div class="col col-lg-12 text-center">
                        <button class="btn btn-primary" type="button" onclick="cadastroGrupoTelegram('<?php echo \Utils\Criptografia::encriptyPostId(0)?>')">
                            Novo Cadastro
                        </button>
                    </div>
                </div>
                <br>
                <table class="table table-bordered table-condensed table-striped">
                    <thead>
                        <tr>
                            <th>Nome</th>
                            <th>Código</th>
                            <th>Editar</th>
                            <th>Ativar/Desativar</th>
                        </tr>
                    </thead>
                    <tbody id="modalListaGruposTelegramBody">
                        
                    </tbody>
                </table>
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="modalListaGruposTelegramFechar" data-dismiss="modal">Fechar</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>



<div class="modal fade" id="modalCadastroGruposTelegram" tabindex="-1" role="dialog" aria-labelledby="modalCadastroGruposTelegram" aria-hidden="true" >
    <div class="modal-dialog" >
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="cadastroContaLabel">Cadastro de Grupo de Telegram</h4>
            </div>
            <div class="modal-body">
                <input type="hidden" class="form-control" id="modalCadastroGruposTelegramId" />
                <div class="row">
                    <div class="col col-lg-6">
                        <div class="form-group">
                            <label class="control-label">Nome</label>
                            <input type="text" class="form-control" id="modalCadastroGruposTelegramNome" maxlength="200" />
                        </div>
                    </div>
                    <div class="col col-lg-6">
                        <div class="form-group">
                            <label class="control-label">Código</label>
                            <input type="text" class="form-control" id="modalCadastroGruposTelegramCodigo" maxlength="200" />
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="modalCadastroGruposTelegramFechar" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-primary" onclick="salvarGruposTelegram();" id="modalCadastroGruposTelegramSalvar" >Salvar</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

<script>
    
    function alterarStatusAtivoMensagemTelegram(codigo) {
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . \Utils\Rotas::R_TELEGRAM_MENSAGEM_ALTERARSTATUS ?>',
            dataType: 'json',
            method: 'post',
            data: {
                codigo: codigo
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        showNotyAlert(json.mensagem, 's');
                        $("#tab-bots-telegram-"+json.codigo+"-status").removeClass("btn-danger").removeClass("btn-primary");
                        if (json.ativo) {
                            $("#tab-bots-telegram-"+json.codigo+"-status").addClass("btn-danger").html("Desativar");
                        } else {
                            $("#tab-bots-telegram-"+json.codigo+"-status").addClass("btn-primary").html("Ativar");
                        }
                        
                    } else {
                        showNotyAlert(json.mensagem, 'e');
                    }
                } catch (e) {
                    showNotyAlert(e, 'e');
                }
            }
        });
    }
    
    
         
    function salvarMensagemTelegram(codigo) {
        $("#modalCadastroGruposTelegramFechar, #modalCadastroGruposTelegramSalvar").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . \Utils\Rotas::R_TELEGRAM_MENSAGEM_SALVAR ?>',
            dataType: 'json',
            method: 'post',
            data: {
                codigo: codigo,
                periodicidade: $("#tab-bots-telegram-"+codigo+"-periodicidade").val(),
                grupo: $("#tab-bots-telegram-"+codigo+"-grupo").val(),
                bot: $("#tab-bots-telegram-"+codigo+"-bot").val(),
                conteudo: $("#tab-bots-telegram-"+codigo+"-mensagem").val(),
                slug: $("#tab-bots-telegram-"+codigo+"-slug").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        
                        showNotyAlert(json.mensagem, 's');
                    } else {
                        showNotyAlert(json.mensagem, 'e');
                    }
                } catch (e) {
                    showNotyAlert(e, 'e');
                }
            }
        });
    }
    
    
    function listarBots() {
        
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . \Utils\Rotas::R_TELEGRAM_BOTS_LISTAR ?>',
            dataType: 'json',
            method: 'post',
            data: {
                
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#modalListaBotsTelegramBody").html(json.html);
                        $("#modalListaBotsTelegram").modal();
                    } else {
                        showNotyAlert(json.mensagem, 'e');
                    }
                } catch (e) {
                    showNotyAlert(e, 'e');
                }
            }
        });
        
    }
    
    function cadastroBotTelegram(codigo) {
        
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . \Utils\Rotas::R_TELEGRAM_BOTS_CADASTRO ?>',
            dataType: 'json',
            method: 'post',
            data: {
                codigo: codigo
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#modalCadastroBotsTelegramFechar, #modalCadastroBotsTelegramSalvar").prop("disabled", false);
                        $("#modalCadastroBotsTelegramId").val(json.bot.id);
                        $("#modalCadastroBotsTelegramNome").val(json.bot.nome);
                        $("#modalCadastroBotsTelegramChave").val(json.bot.chave);
                        $("#modalCadastroBotsTelegram").modal();
                        
                    } else {
                        showNotyAlert(json.mensagem, 'e');
                    }
                } catch (e) {
                    showNotyAlert(e, 'e');
                }
            }
        });
        
    }
    
    
    function salvarBotTelegram() {
        $("#modalCadastroBotsTelegramFechar, #modalCadastroBotsTelegramSalvar").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . \Utils\Rotas::R_TELEGRAM_BOTS_SALVAR ?>',
            dataType: 'json',
            method: 'post',
            data: {
                codigo: $("#modalCadastroBotsTelegramId").val(),
                nome: $("#modalCadastroBotsTelegramNome").val(),
                chave: $("#modalCadastroBotsTelegramChave").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        listarBots();
                        $("#modalCadastroBotsTelegramFechar").prop("disabled", false).trigger("click");
                        showNotyAlert(json.mensagem, 's');
                    } else {
                        showNotyAlert(json.mensagem, 'e');
                    }
                } catch (e) {
                    showNotyAlert(e, 'e');
                }
            }
        });
        $("#modalCadastroBotsTelegramFechar, #modalCadastroBotsTelegramSalvar").prop("disabled", false);
    }
    
    function alterarStatusBotTelegram(codigo) {
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . \Utils\Rotas::R_TELEGRAM_BOTS_ALTERARSTATUS ?>',
            dataType: 'json',
            method: 'post',
            data: {
                codigo: codigo
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        listarBots();
                        
                        showNotyAlert(json.mensagem, 's');
                    } else {
                        showNotyAlert(json.mensagem, 'e');
                    }
                } catch (e) {
                    showNotyAlert(e, 'e');
                }
            }
        });
    }
    
    
    
    
    function listarGrupos() {
        
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . \Utils\Rotas::R_TELEGRAM_GRUPOS_LISTAR ?>',
            dataType: 'json',
            method: 'post',
            data: {
                
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#modalListaGruposTelegramBody").html(json.html);
                        $("#modalListaGruposTelegram").modal();
                    } else {
                        showNotyAlert(json.mensagem, 'e');
                    }
                } catch (e) {
                    showNotyAlert(e, 'e');
                }
            }
        });
        
    }
    
    function cadastroGrupoTelegram(codigo) {
        
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . \Utils\Rotas::R_TELEGRAM_GRUPOS_CADASTRO ?>',
            dataType: 'json',
            method: 'post',
            data: {
                codigo: codigo
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#modalCadastroGruposTelegramFechar, #modalCadastroGruposTelegramSalvar").prop("disabled", false);
                        $("#modalCadastroGruposTelegramId").val(json.grupo.id);
                        $("#modalCadastroGruposTelegramNome").val(json.grupo.nome);
                        $("#modalCadastroGruposTelegramCodigo").val(json.grupo.codigo);
                        $("#modalCadastroGruposTelegram").modal();
                        
                    } else {
                        showNotyAlert(json.mensagem, 'e');
                    }
                } catch (e) {
                    showNotyAlert(e, 'e');
                }
            }
        });
        
    }
    
    
    function salvarGruposTelegram() {
        $("#modalCadastroGruposTelegramFechar, #modalCadastroGruposTelegramSalvar").prop("disabled", true);
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . \Utils\Rotas::R_TELEGRAM_GRUPOS_SALVAR ?>',
            dataType: 'json',
            method: 'post',
            data: {
                id: $("#modalCadastroGruposTelegramId").val(),
                nome: $("#modalCadastroGruposTelegramNome").val(),
                codigo: $("#modalCadastroGruposTelegramCodigo").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        listarGrupos();
                        $("#modalCadastroGruposTelegramFechar").prop("disabled", false).trigger("click");
                        showNotyAlert(json.mensagem, 's');
                    } else {
                        showNotyAlert(json.mensagem, 'e');
                    }
                } catch (e) {
                    showNotyAlert(e, 'e');
                }
            }
        });
        $("#modalCadastroGruposTelegramFechar, #modalCadastroGruposTelegramSalvar").prop("disabled", false);
    }
    
    function alterarStatusGrupoTelegram(codigo) {
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . \Utils\Rotas::R_TELEGRAM_GRUPOS_ALTERARSTATUS ?>',
            dataType: 'json',
            method: 'post',
            data: {
                codigo: codigo
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        listarGrupos();
                        
                        showNotyAlert(json.mensagem, 's');
                    } else {
                        showNotyAlert(json.mensagem, 'e');
                    }
                } catch (e) {
                    showNotyAlert(e, 'e');
                }
            }
        });
    }
    
</script>