<?php

$idioma = new \Utils\PropertiesUtils("perfil", IDIOMA);
$cliente = Utils\Geral::getCliente();
$mostrarBotoes = ($paridade->ativo > 0 && $paridade->statusMercado > 0 && $cliente->statusMercado > 0 && $paridade->moedaBook->statusMercado > 0 && $paridade->moedaBook->ativo > 0);
$mostrarAlerta = false;
$mensagemAlerta = "";

$idioma2 = new \Utils\PropertiesUtils("menu", IDIOMA);

$_data["idiomaMenu"] = $idioma;

?>

<style>
  .border-edit {
    border: 1px solid #1c84c6 !important;
  }

  .carregando {
    background: url("<?php echo IMAGES ?>loading.gif") center no-repeat;
    width: 200px;
    height: 200px;
    position: absolute;
    top: 30%;
    left: 45%;
    color: blue;
  }

  .box {
    border-radius: 10px !important;
  }

  .box-conversion-custom {
    padding-right: 3px !important;
    padding-left: 3px !important;
  }

  .row {
    margin-right: 0 !important;
    margin-left: 0 !important;
  }


  * {
    font-family: "Segoe UI", Roboto, sans-serif;
  }

  .choose-position .select2-container {
    width: 100% !important;
  }

  /* .select2-selection__arrow {
    display: none !important;
  } */

  .choose-position .select2-container--default .select2-selection--single {
    width: 100% !important;
    display: flex;
    align-items: center;
    padding: 0 30px;
    height: 50px;
    line-height: 50px;
    font-weight: 500;
    font-size: 16px;
    background-color: #fafafa;
    border: 1px solid #eeeeee;
    border-radius: 25px;
    transition: 0.1s;
  }

  .select2-dropdown {
    border: 1px solid #eeeeee !important;
  }

  .choose-position .select2-search {
    display: none;
  }

  .choose-position .choose-input {
    width: 100% !important;
    display: flex;
    align-items: center;
    padding: 0 30px;
    height: 50px;
    line-height: 50px;
    font-weight: 500;
    font-size: 16px;
    background-color: #fafafa;
    border: 1px solid #eeeeee;
    border-top-left-radius: 25px;
    border-bottom-left-radius: 25px;
    border-top-right-radius: 4px;
    border-bottom-right-radius: 4px;
  }

  .choose-position .select2-results__option {
    display: flex;
    align-items: center;
  }

  .choose-position .select2-results__option .img-flag {
    width: 40px;
    height: 40px;
    border-radius: 50%;
    object-fit: cover;
    margin-right: 10px;
  }

  .choose-position .select2-container--default.select2-container--focus .select2-selection--single {
    border: 1px solid #c9c9c9 !important;
    outline: 0;
  }

  .choose-position span.select2-selection.select2-selection--single {
    outline: none;
  }

  .choose-position .select2-container--default .select2-selection--single .select2-selection__arrow {
    height: 35px;
    top: 50%;
    transform: translateY(-50%);
    right: 10px;
    width: 35px;
    background-color: #fff;
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    box-shadow: 0 5px 20px rgba(35, 49, 45, 0.14);
  }

  .btn-square {
    width: 75px;
    height: 75px;
    border-radius: 12px;
    border: 2px solid #2351ff;
    box-shadow: rgba(0, 0, 0, 0.2) 0px 2px 14px -6px;
  }

  .btn-square-sm {
    width: 50px;
    height: 50px;
    border-radius: 12px;
    border: 2px solid #2351ff;
    box-shadow: rgba(0, 0, 0, 0.2) 0px 2px 14px -6px;
  }

  .ico {
    transform: translate(13px, 62px);
  }

  .icon-badge {
    font-size: 20px;
  }

  .rounded-icon {
    height: 25px;
    width: 25px;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    border-radius: 50%;
    color: white;
    font-size: 1rem;
  }

  .fs-12 {
    font-size: 12px;
  }

  .fs-24 {
    font-size: 24px;
  }

  .settings .table {
    box-shadow: rgba(0, 0, 0, 0.2) 0px 2px 14px -6px;
    border-radius: 5px;
    border: none;
    margin-bottom: 15px;
  }

  .input_text {
    transform: translate(-10px, -37px);
  }

  .input_legend {
    background-color: white;
    transform: translate(10px, 16px);
    padding: 0 5px 0 5px;
    font-weight: bold;
    font-size: 12px;
  }

  #select_token,
  #form_imob,
  #info_imob,
  .md-visible,
  .balance-hidden {
    display: none;
  }
</style>
<?php Utils\Layout::append("inspina/metas", $_data) ?>
<?php Utils\Layout::append("inspina/scripts", $_data) ?>
<?php Utils\Layout::append("inspina/menu", $_data) ?>
<link href="<?php echo TEMA; ?>css.old/plugins/toastr/toastr.min.css" rel="stylesheet">
<!-- Main content -->

<div class="settings mtb15">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12 col-md-11 mx-auto">
        <div id="show_content">
          <h4>Garantia remunerada:</h4>
          <div class="row">
            <div class="col-lg-6">
              <div class="">
                <div class="row choose-position">
                  <div class="col box-conversion-custom text-center">
                    <div class="form-group" id="select_token">
                      <select id="cryptoFrom" class="crypto custom-select choose-position choose-position-input"
                        disabled>
                        <option value="GAR" title="/resources/images/currencies/GAR.png" data-decimal="8">GAR - Garantia
                        </option>
                      </select>
                    </div>
                    <div class="spinner-border text-primary" role="status" id="select_token_spinner">
                      <span class="sr-only">Loading...</span>
                    </div>
                  </div>
                </div>
              </div>
              <div class="">
                <div class="card">
                  <div class="card-body">
                    <div class="row">
                      <div class="col-md-6">
                        <h4>Saldo de <span class="nome_moeda"></span></h4>
                        <div class="info_saldo">
                          <span>Saldo disponível:
                            <span class="balance-hidden">****</span>
                            <span class="saldo_disponivel fw-bold text-primary balance-visible">
                              <div class="spinner-border spinner-border-sm text-primary" role="status">
                                <span class="sr-only">Loading...</span>
                              </div>
                            </span>
                          </span>
                          <a class="btn btn-sm btn-light ml-2" id="visibility-button3"><i class="icon ion-ios-eye"
                              id="eye3"></i></a>
                        </div>
                      </div>
                      <div class="col-sm-6" id="token_options">
                        <div class="row">
                          <div class="col mb-2">
                            <a class="btn btn-light btn-square-sm d-flex align-items-center mx-auto justify-content-center"
                              href="/deposit">
                              <i class="text-primary fs-30"><img src="assets/img/icon/ico-depositar.svg"
                                  alt="deposit"></i>
                            </a>
                            <p class="fw-bold text-center">Depositar</p>
                          </div>
                          <div class="col mb-2">
                            <a class="btn btn-light btn-square-sm d-flex align-items-center mx-auto justify-content-center"
                              href="/exchange">
                              <i class="text-primary fs-30"><img src="assets/img/icon/ico-comprar.svg"
                                  alt="exchange"></i>
                            </a>
                            <p class="fw-bold text-center">Comprar</p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-lg-6 mb-3">
              <div class="settings-main">
                <div class=" pl-2 pr-2 mr-2">
                  <p class="font-weight-lighter fs-12">ORIENTAÇÕES</p>
                  <div class="row">
                    <div class="col-1">
                      <span class="rounded-icon bg-primary">
                        <i class="icon ion-ios-information icon-badge"></i>
                      </span>
                    </div>
                    <div class="col-11">
                      As recompensas serão contabilizadas em até 2 dias úteis após o aceite da garantia.
                    </div>
                  </div>

                  <p class="font-weight-lighter fs-12 mt-3">INFORMAÇÕES ADICIONAIS</p>
                  <div class="row">
                    <div class="col-1">
                      <span class="rounded-icon bg-primary">
                        <i class="icon ion-ios-information icon-badge"></i>
                      </span>
                    </div>
                    <div class="col-11">
                      <a href="#" data-toggle="modal" data-target="#infoModal">Clique aqui</a> e saiba como funciona a
                      garantia de GAR.
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-lg-6">
              <h5 class="">Selecione uma imobiliária:</h5>
              <div class="" id="spinner_imob">
                <div class="d-flex justify-content-center">
                  <div class="spinner-border text-primary" role="status">
                    <span class="sr-only">Loading...</span>
                  </div>
                </div>
              </div>
              <div class="mt-3" id="form_imob">
                <div class="row choose-position">
                  <div class="col box-conversion-custom">
                    <div class="form-group">
                      <select id="select_imob" name="imob"
                        class="imob custom-select choose-position choose-position-input">
                      </select>
                    </div>
                  </div>
                </div>
              </div>
              <div class="" id="info_imob">
                <div class="card">
                  <div class="card-body">
                    <h4 id="imob_name"></h4>
                    <div class="info_imob">
                      <p class="">CNPJ:
                        <span class="cnpj fw-bold text-primary" id="imob_cnpj">
                        </span>
                      </p>
                      <span class="">Saldo liberado:
                        <span class="balance-hidden">****</span>
                        <span class="mb-2 fw-bold text-primary balance-visible" id="imob_available">
                        </span>
                      </span><br>
                      <span class="">Saldo bloqueado:
                        <span class="balance-hidden">****</span>
                        <span class="mb-1 fw-bold text-primary balance-visible" id="imob_blocked">
                        </span>
                      </span>
                      <div class="row mt-5">
                        <div class="col-6">
                          <button
                            class="btn btn-light btn-square d-flex align-items-center mx-auto justify-content-center"
                            data-toggle="modal" data-target="#garantiaModal">
                            <i class=""><img src="assets/img/icon/ico-staking.svg" alt="garantia"></i>
                          </button>
                          <p class="fw-bold text-center">Enviar Garantia</p>
                        </div>
                        <div class="col-6">
                          <button
                            class="btn btn-light btn-square d-flex align-items-center mx-auto justify-content-center"
                            data-toggle="modal" data-target="#retiradaModal">
                            <i class="ico"><img src="assets/img/icon/ico-resgatar.svg" alt="resgatar"></i>
                          </button>
                          <p class="fw-bold text-center">Pedir Retirada</p>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div class="col-lg-6">
              <div class="card">
                <div class="card-body">
                  <!-- <h5 class="card-title"><?php echo $idioma2->getText("idioma") ?></h5> -->
                  <h5 class="fw-bold">Informações</h5>
                  <div class="mt-3">
                    <span>Recompensa estimada este mês:</span>
                    <span class="d-block"><b id="apm_percent">
                        <div class="spinner-border spinner-border-sm text-primary" role="status">
                          <span class="sr-only">Loading...</span>
                        </div>
                      </b><span id="reward_period"></span></span>
                  </div>
                  <div class="mt-3 d-flex">
                    <div class="">
                      <span>Retirada:</span>
                      <span class="d-block">Somente ao final do contrato.</span>
                    </div>
                  </div>
                </div>
              </div>

              <div class="card">
                <div class="card-body">
                  <h5 class="fw-bold">Em garantia</h5>
                  <div class="">
                    <div class="mt-3">
                      <span>Saldo total em garantia:</span>
                      <span class="d-block"><span class="balance-hidden">****</span><span
                          class="staked_balance balance-visible">
                          <div class="spinner-border spinner-border-sm text-primary" role="status">
                            <span class="sr-only">Loading...</span>
                          </div>
                        </span> <span class="symbol_moeda"></span></span>
                    </div>
                    <div class="mt-3">
                      <span>Recompensa a receber:</span>
                      <span class="d-block"><span class="balance-hidden">****</span><span
                          class="reward_amount balance-visible">
                          <div class="spinner-border spinner-border-sm text-primary" role="status">
                            <span class="sr-only">Loading...</span>
                          </div>
                        </span> <span class="symbol_moeda"></span></span>
                    </div>
                    <div class="mt-3">Recompensa recebida:</span>
                      <span class="d-block"><span class="balance-hidden">****</span><span
                          class="accumulated_amount balance-visible">
                          <div class="spinner-border spinner-border-sm text-primary" role="status">
                            <span class="sr-only">Loading...</span>
                          </div>
                        </span><span class="symbol_moeda"></span></span>
                    </div>
                  </div>
                </div>
              </div>
            </div>

          </div>
          <h4 class="mt-5">Histórico</h4>
          <!-- <div class="row justify-content-start">
            <div class="col-lg-6 mt-3">
              <span class="d-block font-weight-lighter">ATIVIDADE</span>
              <div>
                <button class="btn btn-sm btn-primary mt-1" id="filterBtn0">Todas</button>
                <button class="btn btn-sm btn-white mt-1" id="filterBtn1">Garantia</button>
                <button class="btn btn-sm btn-white mt-1" id="filterBtn2">Recompensas</button>
                <button class="btn btn-sm btn-white mt-1" id="filterBtn3">Retirada</button>
              </div>
            </div>
            <div class="col-lg-6 mt-3">
              <span class="d-block font-weight-lighter">STATUS</span>
              <div>
                <button class="btn btn-sm btn-primary mt-1">Todos</button>
                <button class="btn btn-sm btn-white mt-1">Finalizadas</button>
                <button class="btn btn-sm btn-white mt-1">Processando</button>
                <button class="btn btn-sm btn-white mt-1">Erro</button>
              </div>
            </div>
          </div> -->
          <table class="mt-4 table settings text-center" id="table-garantia">
            <thead class="bg-light">
              <tr>
                <th scope="col">Moeda</th>
                <th scope="col">Descrição</th>
                <th scope="col">Recibo</th>
                <th scope="col">Data</th>
                <th scope="col">Quantidade</th>
                <th scope="col">Status</th>
              </tr>
            </thead>
            <tbody class="align-middle border border-white" id="transactions_table"></tbody>
          </table>
          <div id="pagination" class="d-flex justify-content-center"></div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- stakeModal -->
<div class="modal fade" id="garantiaModal" tabindex="-1" role="dialog" aria-labelledby="garantiaModalTitle"
  aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="garantiaModalTitle">Enviar Garantia</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group">
            <div class="info_saldo d-flex">
              <a class="btn btn-sm btn-light ml-2" id="visibility-button"><i class="icon ion-ios-eye" id="eye"></i></a>
              <span class="mr-1">Disponível para garantia:
                <a href="javascript:inserirSaldo(100);">
                  <span class="balance-hidden">****</span>
                  <span class="saldo_disponivel fw-bold text-primary balance-visible">
                    <div class="spinner-border spinner-border-sm text-primary" role="status">
                      <span class="sr-only">Loading...</span>
                    </div>
                  </span>
                </a>
              </span>
            </div>
            <div class="mt-2 mb-1">Imobiliária Selecionada: <span class="fw-bold selected_imob"></span></div>
            <label for="garantia_input" class="input_legend">Quantia para garantia:</label>
            <input type="text" class="form-control input_height" id="garantia_input" placeholder="1010.10564800">
            <div class="d-flex justify-content-between">
              <span class="fs-10 font-weight-lighter">Mínimo de <span class="min_stake"></span> <span
                  class="symbol_moeda"></span> para
                garantia.</span>
              <span class="input_text symbol_moeda mt-2"></span>
            </div>
            <div class="d-flex justify-content-between mt-3">
              <a href="javascript:inserirSaldo(25);" class="btn btn-sm btn-outline-primary fw-bold">25%</a>
              <a href="javascript:inserirSaldo(50);" class="btn btn-sm btn-outline-primary fw-bold">50%</a>
              <a href="javascript:inserirSaldo(75);" class="btn btn-sm btn-outline-primary fw-bold">75%</a>
              <a href="javascript:inserirSaldo(100);" class="btn btn-sm btn-outline-primary fw-bold">100%</a>
            </div>
          </div>
        </form>
      </div>
      <div class="modal-footer d-flex justify-content-between">
        <button type="button" class="btn btn-outline-danger" data-dismiss="modal">Cancelar</button>
        <a href="javascript:setGarantia();" type="button" class="btn btn-primary" id="garantia_button">Fazer
          Garantia</a>
      </div>
    </div>
  </div>
</div>

<!-- retiradaModal -->
<div class="modal fade" id="retiradaModal" tabindex="-1" role="dialog" aria-labelledby="retiradaModalTitle"
  aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="retiradaModalTitle">Pedir Retirada</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group">
            <div class="mt-3" id="form_operation">
              <div class="row choose-position">
                <div class="col box-conversion-custom">
                  <div class="form-group">
                    <div class="mb-1">Selecione um contrato para retirada:</div>
                    <select id="select_operation" class="imob custom-select choose-position choose-position-input">
                    </select>
                    <div class="mt-3 mb-1">Status: <span id="selected_status"></span></div>
                    <p class="mt-3 fs-10 font-weight-lighter">Após clicar em Fazer Retirada, aguarde a imobiliária
                      autorizar a retirada.</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </form>
      </div>
      <div class="modal-footer d-flex justify-content-between">
        <button type="button" class="btn btn-outline-danger" data-dismiss="modal">Cancelar</button>
        <a href="javascript:setRetirada();" type="button" class="btn btn-primary" id="retirada_button">Fazer
          Retirada</a>
      </div>
    </div>
  </div>
</div>

<!-- infoModal -->
<div class="modal fade" id="infoModal" tabindex="-1" role="dialog" aria-labelledby="infoModalTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="infoModalTitle">Informações do garantia de <span class="symbol_moeda"></span>
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p class="font-weight-lighter fs-12">ORIENTAÇÕES</p>
        <div class="row">
          <div class="col-1">
            <span class="rounded-icon bg-primary">
              <i class="icon ion-ios-information icon-badge"></i>
            </span>
          </div>
          <div class="col-11">
            <span>As recompensas serão contabilizadas em até 2 dias úteis após o aceite da garantia.</span>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>

<!-- waitingTxModal -->
<div class="modal fade" id="waitingTxModal" tabindex="-1" role="dialog" aria-labelledby="waitingTxModalTitle"
  aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="waitingTxModalTitle">Transação em progresso...</h5>
      </div>
      <div class="modal-body text-center">
        <p class="">Por favor, aguarde o fim da transação!</p>
        <div class="spinner-border text-primary mx-auto" role="status">
          <span class="sr-only">Loading...</span>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- completedModal -->
<div class="modal fade" id="completedModal" tabindex="-1" role="dialog" aria-labelledby="completedModalTitle"
  aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header bg-success">
        <h5 class="modal-title text-white" id="completedModalTitle">Transação Concluida!</h5>
      </div>
      <div class="modal-body text-center">
        <p class="fw-bold">A transação foi concluída!</p>
        <p class="fw-bold">A tela recarregará em instantes, aguarde!</p>
      </div>
    </div>
  </div>
</div>

<!-- End Main content -->

<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>
<link href="<?php echo TEMA; ?>css.old/plugins/toastr/toastr.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.10.0/dist/sweetalert2.all.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/sweetalert2@11.10.0/dist/sweetalert2.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
  integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
  </script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
  integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
  </script>
<script src="https://cdn.jsdelivr.net/npm/javascript-obfuscator/dist/index.browser.js"></script>
<script src="<?php echo JS; ?>maskMoney.min.js"></script>

<script>
  window.addEventListener('load', () => {
    const garantia_table = document.querySelector('#table-garantia');
    garantia_table.classList.toggle('table-responsive', window.matchMedia('(max-width:505px)').matches);
  });
</script>
<script>
  window.addEventListener('resize', () => {
    const garantia_table = document.querySelector('#table-garantia');
    garantia_table.classList.toggle('table-responsive', window.matchMedia('(max-width:505px)').matches);
  });
</script>
<script>
  var url_guarantee_balance = '<?php echo $_ENV['SITE_URL'] ?>' + '/api/priv/guarantee/balance';
  var url_guarantee_providers = '<?php echo $_ENV['SITE_URL'] ?>' + '/api/priv/guarantee/providers';
  var url_guarantee_provider_balance = '<?php echo $_ENV['SITE_URL'] ?>' + '/api/priv/guarantee/provider/balance';
  var url_guarantee_checkReward = '<?php echo $_ENV['SITE_URL'] ?>' + '/api/priv/guarantee/checkReward';
  var url_guarantee_checkAccumulatedReward = '<?php echo $_ENV['SITE_URL'] ?>' + '/api/priv/guarantee/checkAccumulatedReward';
  var url_guarantee_transfer = '<?php echo $_ENV['SITE_URL'] ?>' + '/api/priv/guarantee/transfer';
  var url_guarantee_operations = '<?php echo $_ENV['SITE_URL'] ?>' + '/api/priv/guarantee/operations';
  var url_guarantee_withdrawal = '<?php echo $_ENV['SITE_URL'] ?>' + '/api/priv/guarantee/withdrawal';

  var preco = 0;
  var time = 0;
  var saldo = 0;
  var saldo_stake = 0;
  var selected_imob = "";
  var selected_hash = "";
  let balanceVisibility = "";

  var tokens = {};
  var token = [];
  const handleVisibility = () => {
    const eye = document.getElementById("eye");
    const eye3 = document.getElementById("eye3");
    if (balanceVisibility == "true") {
      const hidden = document.querySelectorAll(".balance-hidden");
      for (var i = 0; i < hidden.length; i++) {
        hidden[i].style.display = "inline-flex";
      }
      const visible = document.querySelectorAll(".balance-visible");
      for (var i = 0; i < visible.length; i++) {
        visible[i].style.display = "none";
      }
      eye.classList.remove("ion-ios-eye");
      eye.classList.add("ion-ios-eye-off");
      eye3.classList.remove("ion-ios-eye");
      eye3.classList.add("ion-ios-eye-off");
      balanceVisibility = "false";
      localStorage.setItem("balance_visibility", "false")
    } else {
      const hidden = document.querySelectorAll(".balance-hidden");
      for (var i = 0; i < hidden.length; i++) {
        hidden[i].style.display = "none";
      }
      const visible = document.querySelectorAll(".balance-visible");
      for (var i = 0; i < visible.length; i++) {
        visible[i].style.display = "inline-flex";
      }
      eye.classList.remove("ion-ios-eye-off");
      eye.classList.add("ion-ios-eye");
      eye3.classList.remove("ion-ios-eye-off");
      eye3.classList.add("ion-ios-eye");
      balanceVisibility = "true";
      localStorage.setItem("balance_visibility", "true")
    }
  }

  if (balanceVisibility == "" && !localStorage.getItem("balance_visibility")) {
    balanceVisibility = "true";
    handleVisibility()
  } else {
    localStorage.getItem("balance_visibility") == "true" ? balanceVisibility = "false" : balanceVisibility = "true";
    handleVisibility()
  }

  document.getElementById("visibility-button").addEventListener("click", handleVisibility);
  document.getElementById("visibility-button3").addEventListener("click", handleVisibility);

  $(document).ready(function () {
    $("#cryptoFrom").select2();

    $("#cryptoFrom").on('select2:select', function (e) {
      $(".saldo_disponivel").html("");
      saldo = 0;
      var data = $("#cryptoFrom").val();
      const spinner = '<div class="spinner-border spinner-border-sm text-primary" role="status">' +
        '<span class="sr-only">Loading...</span>' +
        '</div>'
      $('.min_stake').html(spinner);
      $('.staked_balance').html(spinner);
      $('.reward_amount').html(spinner);
      $('.accumulated_amount').html(spinner);
      $('#apm_percent').html(spinner)
    });

    $("#select_imob").select2();
    $("#select_operation").select2();

    var option = '';

    $.ajax({
      url: url_guarantee_balance,
      method: "POST",
      dataType: 'json',
      data: {
        user_id: <?php echo json_encode($cliente->id) ?>
      },
      success: function (json) {
        if (json.message == "Sucesso!") {
          const nome = $("#cryptoFrom option:selected").text().replace(" ", "").split("-");
          $('.nome_moeda').html("Garantia");
          $('.symbol_moeda').html("GAR");
          $('#reward_period').html(" em <b>GAR</b>");
          saldo = parseFloat(json.data.coin_balance);
          saldo_stake = parseFloat(json.data.contract_balance);
          $(".saldo_disponivel").html(fixDecimals(saldo, 8));
          $('.staked_balance').html(fixDecimals(isNaN(saldo_stake) ? 0 : saldo_stake, 8));
          $(".crypto").select2({
            templateResult: function () {
              var $span = $("<span><img style='width: 25px;' src='/resources/images/currencies/GAR.png' />GAR - Garantia</span>");
              return $span;
            },
            templateSelection: function () {
              var $span = $("<span><img style='width: 25px;' src='/resources/images/currencies/GAR.png' />GAR - Garantia</span>");
              return $span;
            }
          });
          document.getElementById("select_token_spinner").style.display = "none";
          document.getElementById("select_token").style.display = "block";

          getCurrentApm();
          fetchTxs(1)
          // getCheckReward()
        } else {
          // $("#noCoinCard").show();
          showNotyAlert("Sem moedas na carteira, primeiro adquira moedas!", "e");
        }
      }
    });

    function getProviders() {
      $.ajax({
        url: url_guarantee_providers,
        method: "GET",
        dataType: 'json',
        success: function (json) {
          imob = json.data;
          imob.forEach(element => {
            option += '<option value="' + element.cnpj + '" title="' + element
              .name + '">' + element
                .name + ' - ' + element.cnpj + '</option>';
          });
          $('#select_imob').html(option);
          $(".imob").select2({
            templateResult: function (imb) {
              var $span = $("<span>" + imb.text + "</span>");
              return $span;
            },
            templateSelection: function (imb) {
              var $span = $("<span>" + imb.text + "</span>");
              // console.log(imb)
              $("#spinner_imob").hide();
              $("#form_imob").show();
              $("#info_imob").show();
              $('#imob_name').html(imb.title);
              $('#imob_cnpj').html(imb.id);
              selected_imob = imb;
              $('.selected_imob').html(imb.text);
              getProviderBalance(imb)
              return $span;
            }
          });
        }
      });
    }

    getProviders()

    function getProviderBalance(imb) {
      $.ajax({
        url: url_guarantee_provider_balance,
        method: "POST",
        dataType: 'json',
        data: {
          user_id: <?php echo json_encode($cliente->id) ?>,
          provider_doc: imb.id
        },
        success: function (json) {
          $('#imob_available').html(fixDecimals(json.data.available, 8));
          $('#imob_blocked').html(fixDecimals(json.data.blocked, 8));
        }
      });
    }

  });

  async function fetchTxs(page) {
    const update = {
      user_id: <?php echo json_encode($cliente->id) ?>,
    };

    const options = {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(update),
    };

    try {
      const response = await fetch('<?php echo $_ENV['SITE_URL'] ?>' + '/api/priv/guarantee/operations?page=' + page, options);
      const data = await response.json();
      const tx = data.data;

      var tBodyHtml = "";
      const tBody_tx = document.getElementById("transactions_table");
      const pagination = document.getElementById("pagination");
      tBody_tx.innerHTML = "";
      pagination.innerHTML = "";
      var operations = '';
      tx.forEach(e => {
        operations += '<option value="' + e.hash + '" title="' + e.status_name + ',' + e.status + '">' + e.provider.name + ' - ' + parseFloat(e.value).toFixed(4) + ' (' + (e.date).split("-")[0].trim() + ')' + '</option>';
      });
      $("#select_operation").html(operations)
      $("#select_operation").select2({
        templateResult: function (imb) {
          var $span = $("<span>" + imb.text + "</span>");
          return $span;
        },
        templateSelection: function (imb) {
          var $span = $("<span>" + imb.text + "</span>");
          selected_hash = imb.id;
          const status_id = parseInt(imb.title.split(",")[1])
          const status_name = imb.title.split(",")[0]
          const status = status_id ==1 ? "<span class='badge badge-warning p-2'>" + status_name + "</span>" :
            status_id == 2 ? "<span class='badge badge-success p-2'>" + status_name + "</span>" :
              status_id == 3 ? "<span class='badge badge-secondary p-2'>" + status_name + "</span>" :
                status_id == 4 ? "<span class='badge badge-dark p-2'>" + status_name + "</span>" :
                  status_id == 5 ? "<span class='badge badge-danger p-2'>" + status_name + "</span>" :
                    status_id == 6 ? "<span class='badge badge-warning p-2'>" + status_name + "</span>" :
                      status_id == 7 ? "<span class='badge badge-info p-2'>" + status_name + "</span>" :
                        status_id == 8 ? "<span class='badge badge-success p-2'>" + status_name + "</span>" :
                          "<span class='badge badge-primary p-2'>" + status_name + "</span>";
          $("#selected_status").html(status)
          const rtBtn = document.getElementById("retirada_button");
          status_id > 5 ? rtBtn.classList.add("disabled") : rtBtn.classList.remove("disabled")
          return $span;
        }
      });

      if (tx.length && tx.length > 0) {
        for (i = 0; i < tx.length; i++) {
          // const rawDate = tx[i].created_at.replace(".000000", "").replace("T", " ").replace("Z", "")
          //   .split(" ");
          // const dateGMT = new Date(rawDate[0] + "T" + rawDate[1] + "Z");
          // const date = dateGMT.toLocaleString("pt-BR", {
          //   timeZone: "America/Sao_Paulo"
          // }).trim().split(",");
          const date = (tx[i].date).trim().split("-")
          const amount = parseFloat(tx[i].value).toFixed(8);
          const qde = amount + ' GAR</span>';
          const status = tx[i].status == 1 ? "<span class='badge badge-warning p-2'>" + tx[i].status_name + "</span>" :
            tx[i].status == 2 ? "<span class='badge badge-success p-2'>" + tx[i].status_name + "</span>" :
              tx[i].status == 3 ? "<span class='badge badge-secondary p-2'>" + tx[i].status_name + "</span>" :
                tx[i].status == 4 ? "<span class='badge badge-dark p-2'>" + tx[i].status_name + "</span>" :
                  tx[i].status == 5 ? "<span class='badge badge-danger p-2'>" + tx[i].status_name + "</span>" :
                    tx[i].status == 6 ? "<span class='badge badge-warning p-2'>" + tx[i].status_name + "</span>" :
                      tx[i].status == 7 ? "<span class='badge badge-info p-2'>" + tx[i].status_name + "</span>" :
                        tx[i].status == 8 ? "<span class='badge badge-success p-2'>" + tx[i].status_name + "</span>" :
                          "<span class='badge badge-primary p-2'>" + tx[i].status_name + "</span>"
          const txid = tx[i].hash;
          const description = tx[i].provider.name;

          tBodyHtml += '<tr>' +
            '<td class="align-middle"><img src="/resources/images/currencies/GAR.png" height="30" width="30"></td>' +
            '<td class="align-middle"><span>' + description + '</span></td>' +
            '<td class="align-middle"><b class="text-primary">' + txid + '</b></td>' +
            '<td class="fs-12 align-middle p-2"><span>' + date[0] + '</span><span class="d-block">' +
            date[1] + '</span></td>' +
            '<td class="align-middle">' + qde + '</td>' +
            '<td class="align-middle">' + status + '</td>' +
            '</tr>'

          tBody_tx.innerHTML = tBodyHtml;

          var pages = "";
          for (const item of data.links) {
            const active = item.active == true ? "active" : "";
            const url = item.url == null ? "" : item.label == "&laquo; Anterior" ? data.current_page - 1 :
              item.label == "Próximo &raquo;" ? data.current_page + 1 : item.label;
            const disabled = item.url == null ? "disabled" : "";
            pages += '<li class="page-item ' + active + ' ' + disabled +
              '"><a class="page-link" href="javascript:fetchTxs(' + url + ');">' + item.label +
              '</a></li>'
          }
          const paginationHTML =
            '<nav class="mx-auto" aria-label="Page navigation example"><ul class="pagination">' + pages +
            '</ul></nav>';
          pagination.innerHTML = paginationHTML;
        }
      }
    } catch (error) {
      console.error('Data error: ' + error.message);
    }
  }

  function showSweetAlert(id, type, title, message) {
    $(id).modal("hide");
    $(document.body).removeClass("modal-open");
    $(".modal-backdrop").remove();
    var icon = "";
    type == "e" ? icon = "error" : type == "s" ? icon = "success" : icon = "warning";
    Swal.fire({
      title: title,
      text: message,
      icon: icon,
      timer: 3000,
      showConfirmButton: false,
      timerProgressBar: true
    }).then(() => {
      $(id).modal("show");
    })
  }

  function fixDecimals(num, decimal) {
    return (parseFloat(num).toFixed(decimal)).toString().replace('.', ',')
  }

  function setGarantia() {
    var valor = $('#garantia_input').val();
    valor = parseFloat(valor.replace(',', '.'))
    $('#garantia_input').val("");
    try {
      if (valor <= saldo * 1 && valor > 0) {
        $("#garantiaModal").modal("hide");
        $("#waitingTxModal").modal("show");
        $.ajax({
          url: url_guarantee_transfer,
          method: "POST",
          dataType: 'json',
          data: {
            user_id: <?php echo json_encode($cliente->id) ?>,
            amount: valor,
            provider_doc: selected_imob.id
          },
          success: function (json) {
            if (json.message == "Sucesso!") {
              showNotyAlert("Transação completa!", "s");
              $("#waitingTxModal").modal("hide");
              $("#completedModal").modal("show");
              setTimeout(() => {
                location.reload(true);
              }, 3000);
            } else {
              $("#waitingTxModal").modal("hide");
              showSweetAlert("#garantiaModal", "e", "Algo deu errado :(", "Saldo insuficiente!");
              showNotyAlert("Saldo insuficiente!", "e");
            }
          }
        });
      } else {
        showSweetAlert("#garantiaModal", "e", "Algo deu errado :(", "Valor incorreto ou saldo insuficiente!");
        showNotyAlert("Valor incorreto ou saldo insuficiente!", "e");
      }
    } catch (e) {
      showNotyAlert(e, "e");
    }
  }

  function setRetirada() {
    // var valor = $('#retirada_input').val();
    // valor = parseFloat(valor.replace(',', '.'));
    // $('#retirada_input').val("");
    try {
      $("#retiradaModal").modal("hide");
      $("#waitingTxModal").modal("show");
      // showNotyAlert("Certo!", "s");
      $.ajax({
        url: url_guarantee_withdrawal,
        method: "POST",
        dataType: 'json',
        data: {
          user_id: <?php echo json_encode($cliente->id) ?>,
          hash: selected_hash
        },
        success: function (json) {
          showNotyAlert("Transação completa!", "s");
          $("#waitingTxModal").modal("hide");
          $("#completedModal").modal("show");
          setTimeout(() => {
            location.reload(true);
          }, 3000);
        },
      });
    } catch (e) {
      showNotyAlert(e, "e");
    }
  }

  function inserirSaldo(percent) {
    var saldo_inserido = (saldo * percent / 100);
    $('#garantia_input').val(saldo_inserido.toString().replace('.', ','));
    // $('#valor').maskMoney('mask', saldo_inserido);
  };

  function inserirSaldoStake(percent) {
    var saldo_retirada = (saldo_stake * percent / 100);
    $('#retirada_input').val(saldo_retirada.toString().replace(".", ","));
  };

  function getCheckReward() {
    var recompensa = 0;
    $.ajax({
      url: url_guarantee_checkReward,
      method: "POST",
      dataType: 'json',
      data: {
        user_id: <?php echo json_encode($cliente->id) ?>
      },
      success: function (json) {
        recompensa = json.data.reward;
        $('.reward_amount').html(fixDecimals(isNaN(json.data.reward) ? 0 : json.data.reward, 8));
      }
    });

    $.ajax({
      url: url_guarantee_checkAccumulatedReward,
      method: "POST",
      dataType: 'json',
      data: {
        user_id: <?php echo json_encode($cliente->id) ?>
      },
      success: function (json) {
        // console.log("2 ", json)
        $('.accumulated_amount').html(fixDecimals((isNaN(json.data.reward) ? 0 : json.data.reward) - recompensa, 8));
      }
    });
  }

  getCheckReward()

  function getCurrentApm() {
    var stk = {
      simbolo: "GAR",
      apm: 10,
      bonus: 0,
      penalty: 0,
      min_stake: 10
    };
    const apmFinal = (stk.apm + stk.bonus) / 10 - (stk.apm + stk.bonus) / 10 * (stk.penalty / 1000);
    const min_stake = stk.min_stake;
    $('#apm_percent').html(apmFinal.toFixed(2).toString().replace(".", ",") + "%")
    $('.min_stake').html(fixDecimals(min_stake, 8));
  }

  // const fBtn0 = document.getElementById("filterBtn0");
  // const fBtn1 = document.getElementById("filterBtn1");
  // const fBtn2 = document.getElementById("filterBtn2");
  // const fBtn3 = document.getElementById("filterBtn3");
  // fBtn0.onclick = () => {
  //   fBtn0.className = "btn btn-sm btn-primary mt-1";
  //   fBtn1.className = "btn btn-sm btn-white mt-1"
  //   fBtn2.className = "btn btn-sm btn-white mt-1"
  //   fBtn3.className = "btn btn-sm btn-white mt-1"
  //   fetchTxs(1, 0);
  // }
  // fBtn1.onclick = () => {
  //   fBtn0.className = "btn btn-sm btn-white mt-1";
  //   fBtn1.className = "btn btn-sm btn-primary mt-1"
  //   fBtn2.className = "btn btn-sm btn-white mt-1"
  //   fBtn3.className = "btn btn-sm btn-white mt-1"
  //   fetchTxs(1, 1);
  // }
  // fBtn2.onclick = () => {
  //   fBtn0.className = "btn btn-sm btn-white mt-1";
  //   fBtn1.className = "btn btn-sm btn-white mt-1"
  //   fBtn2.className = "btn btn-sm btn-primary mt-1"
  //   fBtn3.className = "btn btn-sm btn-white mt-1"
  //   fetchTxs(1, 2);
  // }
  // fBtn3.onclick = () => {
  //   fBtn0.className = "btn btn-sm btn-white mt-1";
  //   fBtn1.className = "btn btn-sm btn-white mt-1"
  //   fBtn2.className = "btn btn-sm btn-white mt-1"
  //   fBtn3.className = "btn btn-sm btn-primary mt-1"
  //   fetchTxs(1, 3);
  // }

</script>

<script>
  // function getCheckAccumulatedReward() {
  //   $.ajax({
  //     url: "<?php echo URLBASE_CLIENT . \Utils\Rotas::R_STAKING_CHECK_ACCUMULATED_REWARD ?>",
  //     method: "POST",
  //     dataType: 'json',
  //     data: {
  //       contract_address: token[0].contract_address
  //     },
  //     success: function (json) {
  //       $('.accumulated_amount').html(fixDecimals(json.valor, token[0].decimal));
  //     }
  //   });
  // }
  // function getMinStake() {
  //   $.ajax({
  //     url: "<?php echo URLBASE_CLIENT . \Utils\Rotas::R_STAKING_MIN_STAKE ?>",
  //     method: "POST",
  //     dataType: 'json',
  //     data: {
  //       contract_address: token[0].contract_address
  //     },
  //     success: function (json) {
  //       $('.min_stake').html(fixDecimals(json.valor, token[0].decimal));
  //     }
  //   });
  // }

  // var apm = 0;
  // var bonus = 0;
  // var penalty = 0;

  // function getAPM() {
  //   $.ajax({
  //     url: "<?php echo URLBASE_CLIENT . \Utils\Rotas::R_STAKING_GET_APM ?>",
  //     method: "POST",
  //     dataType: 'json',
  //     data: {
  //       contract_address: token[0].contract_address
  //     },
  //     success: function (json) {
  //       apm = json.valor;
  //     }
  //   });
  // }

  // function getBonus() {
  //   $.ajax({
  //     url: "<?php echo URLBASE_CLIENT . \Utils\Rotas::R_STAKING_GET_BONUS ?>",
  //     method: "POST",
  //     dataType: 'json',
  //     data: {
  //       contract_address: token[0].contract_address
  //     },
  //     success: function (json) {
  //       bonus = json.valor;
  //     }
  //   });
  // }

  // function getPenalty() {
  //   $.ajax({
  //     url: "<?php echo URLBASE_CLIENT . \Utils\Rotas::R_STAKING_GET_PENALTY ?>",
  //     method: "POST",
  //     dataType: 'json',
  //     data: {
  //       contract_address: token[0].contract_address
  //     },
  //     success: function (json) {
  //       penalty = json.valor;
  //     }
  //   });
  // }
</script>




<?php Utils\Layout::append("mensage_text", $_data) ?>