<?php

$idioma = new \Utils\PropertiesUtils("perfil", IDIOMA);
$cliente = Utils\Geral::getCliente();
$mostrarBotoes = ($paridade->ativo > 0 && $paridade->statusMercado > 0 && $cliente->statusMercado > 0 && $paridade->moedaBook->statusMercado > 0 && $paridade->moedaBook->ativo > 0);
$mostrarAlerta = false;
$mensagemAlerta = "";

$idioma2 = new \Utils\PropertiesUtils("menu", IDIOMA);

$_data["idiomaMenu"] = $idioma;

?>

<style>
   .border-edit {
        border: 1px solid #1c84c6 !important;
    }

    .carregando {
        background: url("<?php echo IMAGES ?>loading.gif") center no-repeat;
        width: 200px;
        height: 200px;
        position: absolute;
        top: 30%;
        left: 45%;
        color: blue;
    }

    .box {
        border-radius: 10px !important;
    }

    .box-conversion-custom {
        padding-right: 3px !important;
        padding-left: 3px !important;
    }

    .row {
        margin-right: 0 !important;
        margin-left: 0 !important;
    }


    * {
        font-family: "Segoe UI", Roboto, sans-serif;
    }

    .choose-position .select2-container {
        width: 100% !important;
    }

    .choose-position .select2-container--default .select2-selection--single {
        width: 100% !important;
        display: flex;
        align-items: center;
        padding: 0 30px;
        height: 50px;
        line-height: 50px;
        font-weight: 500;
        font-size: 16px;
        background-color: #fafafa;
        border: 1px solid #eeeeee;
        border-radius: 25px;
        transition: 0.1s;
    }

    .select2-dropdown {
        border: 1px solid #eeeeee !important;
    }

    .choose-position .select2-search {
        display: none;
    }

    .choose-position .choose-input {
        width: 100% !important;
        display: flex;
        align-items: center;
        padding: 0 30px;
        height: 50px;
        line-height: 50px;
        font-weight: 500;
        font-size: 16px;
        background-color: #fafafa;
        border: 1px solid #eeeeee;
        border-top-left-radius: 25px;
        border-bottom-left-radius: 25px;
        border-top-right-radius: 4px;
        border-bottom-right-radius: 4px;
    }

    .choose-position .select2-results__option {
        display: flex;
        align-items: center;
    }

    .choose-position .select2-results__option .img-flag {
        width: 40px;
        height: 40px;
        border-radius: 50%;
        object-fit: cover;
        margin-right: 10px;
    }

    .choose-position .select2-container--default.select2-container--focus .select2-selection--single {
        border: 1px solid #c9c9c9 !important;
        outline: 0;
    }

    .choose-position span.select2-selection.select2-selection--single {
        outline: none;
    }

    .choose-position .select2-container--default .select2-selection--single .select2-selection__arrow {
        height: 35px;
        top: 50%;
        transform: translateY(-50%);
        right: 10px;
        width: 35px;
        background-color: #fff;
        border-radius: 50%;
        display: flex;
        align-items: center;
        justify-content: center;
        box-shadow: 0 5px 20px rgba(35, 49, 45, 0.14);
    }

  .btn-square {
    width: 75px;
    height: 75px;
    border-radius: 12px;
    border: 2px solid #2351ff;
    box-shadow: rgba(0, 0, 0, 0.2) 0px 2px 14px -6px;
  }

  .ico {
    transform: translate(13px, 62px);
  }

  .icon-badge {
    font-size: 20px;
  }

  .rounded-icon {
    height: 25px;
    width: 25px;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    border-radius: 50%;
    color: white;
    font-size: 1rem;
  }

  .fs-12 {
    font-size: 12px;
  }

  .fs-24 {
    font-size: 24px;
  }

  .settings .table {
    box-shadow: rgba(0, 0, 0, 0.2) 0px 2px 14px -6px;
    border-radius: 5px;
    border: none;
    margin-bottom: 15px;
  }
  
</style>
<?php Utils\Layout::append("inspina/metas", $_data) ?>
<?php Utils\Layout::append("inspina/scripts", $_data) ?>
<?php Utils\Layout::append("inspina/menu", $_data) ?>
<link href="<?php echo TEMA; ?>css.old/plugins/toastr/toastr.min.css" rel="stylesheet">
<!-- Main content -->

  <div class="settings mtb15">
    <div class="container-fluid">
      <div class="row">
        <div class="col-12 col-md-11 mx-auto">
          <h4>Selecione uma moeda:</h4>
          <div class="row">
            <div class="col-md-6 mt-4">
              <div class="">
                <div class="row choose-position">
                  <div class="col box-conversion-custom">
                    <div class="form-group">
                      <select id="cryptoFrom" class="crypto custom-select choose-position choose-position-input"></select>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-6">
              <div class="card">
                <div class="card-body">
                  <h4>Saldo de <span class="nome_moeda"></span></h4>
                  <div class="info_saldo">
                    Saldo disponível: <span id="saldo_disponivel" class="fw-bold text-primary"></span>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <h4 class="mt-3">Staking de <span class="nome_moeda"></span></h4>
          <div class="row">
            <div class="col-md-6">
              <div class="card">
                <div class="card-body">
                  <!-- <h5 class="card-title"><?php echo $idioma2->getText("idioma") ?></h5> -->
                  <h5 class="fw-bold">Informações</h5>
                  <div class="mt-3">
                    <span>Recompensa líquida estimada</span>
                    <span class="d-block"><b>3,30%</b> ao ano</span>
                  </div>
                  <div class="mt-3 d-flex">
                    <div class="">
                      <span>Resgate</span>
                      <span class="d-block">Em até 5 dias úteis</span>
                    </div>
                    <div class="ml-5">
                      <span>Staking mínimo</span>
                      <span class="d-block">0,00100000 ETH</span>
                    </div>
                  </div>
                </div>
              </div>
              <div class="card">
                <div class="card-body">
                  <h5 class="fw-bold">Em staking</h5>
                  <div class="row justify-content-between">
                    <div class="col-5">
                      <div class="mt-3">
                        <span>Saldo total em staking</span>
                        <span class="d-block">0,02835415 ETH</span>
                      </div>
                      <div class="mt-3">
                        <span>Lucro acumulado</span>
                        <span class="d-block">0,00005449 ETH</span>
                      </div>
                    </div>
                    <div class="col-7 mt-3">
                      <div class="row">
                        <div class="col-6 mb-2">
                          <button
                            class="btn btn-light btn-square d-flex align-items-center mx-auto justify-content-center">
                            <i class=""><img src="assets/img/icon/ico-staking.svg" alt="staking"></i>
                          </button>
                          <p class="fw-bold text-center">Fazer Staking</p>
                        </div>
                        <div class="col-6 mb-2">
                          <button
                            class="btn btn-light btn-square d-flex align-items-center mx-auto justify-content-center">
                            <i class="ico"><img src="assets/img/icon/ico-resgatar.svg" alt="resgatar"></i>
                          </button>
                          <p class="fw-bold text-center">Resgatar</p>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-6">
              <div class="settings-main">
                <div class=" pl-2 pr-2 mr-2">
                  <p class="font-weight-lighter fs-12">ORIENTAÇÕES</p>
                  <div class="row">
                    <div class="col-1">
                      <span class="rounded-icon bg-primary">
                        <i class="icon ion-ios-information icon-badge"></i>
                      </span>
                    </div>
                    <div class="col-11">
                      As recompensas serão contabilizadas em até 2 dias úteis após
                      o Staking.
                    </div>
                  </div>

                  <p class="font-weight-lighter fs-12 mt-3">INFORMAÇÕES ADICIONAIS</p>
                  <div class="row">
                    <div class="col-1">
                      <span class="rounded-icon bg-primary">
                        <i class="icon ion-ios-information icon-badge"></i>
                      </span>
                    </div>
                    <div class="col-11">
                      <a href="#">Clique aqui</a> e saiba como funciona o Staking
                      de <span class="nome_moeda"></span>.</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <h4 class="mt-5">Histórico</h4>
          <div class="row justify-content-end">
            <div class="col-lg-6 mt-3">
              <span class="d-block font-weight-lighter">ATIVIDADE</span>
              <div class="mt-1">
                <button class="btn btn-primary">Todas</button>
                <button class="btn btn-white">Staking</button>
                <button class="btn btn-white">Recompensas</button>
                <button class="btn btn-white">Resgate</button>
              </div>
            </div>
            <div class="col-lg-6 mt-3">
              <span class="d-block font-weight-lighter">STATUS</span>
              <div class="mt-1">
                <button class="btn btn-primary">Todos</button>
                <button class="btn btn-white">Finalizadas</button>
                <button class="btn btn-white">Processando</button>
                <button class="btn btn-white">Erro</button>
              </div>
            </div>
          </div>
          <table class="mt-4 table settings">
            <thead class="bg-light">
              <tr>
                <th scope="col">DATA</th>
                <th scope="col">ATIVIDADE</th>
                <th scope="col">QUANTIDADE</th>
                <th scope="col">PREVISÃO</th>
                <th scope="col">STATUS</th>
              </tr>
            </thead>
            <tbody class="align-middle border border-white">
              <tr>
                <th class="fs-12 align-middle p-2"><span>29/10/2023</span><span class="d-block">ÀS
                    13:32:51</span></th>
                <td class="align-middle">Recompensas</td>
                <td class="align-middle">0,00000226 ETH</td>
                <td class="align-middle">-</td>
                <td class="align-middle"><span class="badge bg-success p-2">Finalizado</span></td>
              </tr>
              <tr>
                <th class="fs-12 align-middle p-2"><span>28/10/2023</span><span class="d-block">ÀS
                    13:32:56</span></th>
                <td class="align-middle">Recompensas</td>
                <td class="align-middle">0,00000136 ETH</td>
                <td class="align-middle">-</td>
                <td class="align-middle"><span class="badge bg-success p-2">Finalizado</span></td>
              </tr>
              <tr>
                <th class="fs-12 align-middle p-2"><span>27/10/2023</span><span class="d-block">ÀS
                    13:32:31</span></th>
                <td class="align-middle">Recompensas</td>
                <td class="align-middle">0,00000165 ETH</td>
                <td class="align-middle">-</td>
                <td class="align-middle"><span class="badge bg-success p-2">Finalizado</span></td>
              </tr>
              <tr>
                <th class="fs-12 align-middle p-2"><span>26/10/2023</span><span class="d-block">ÀS
                    13:32:32</span></th>
                <td class="align-middle">Recompensas</td>
                <td class="align-middle">0,00000224 ETH</td>
                <td class="align-middle">-</td>
                <td class="align-middle"><span class="badge bg-success p-2">Finalizado</span></td>
              </tr>
              <tr>
                <th class="fs-12 align-middle p-2"><span>25/10/2023</span><span class="d-block">ÀS
                    18:32:1</span></th>
                <td class="align-middle">Recompensas</td>
                <td class="align-middle">0,00000184 ETH</td>
                <td class="align-middle">-</td>
                <td class="align-middle"><span class="badge bg-success p-2">Finalizado</span></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

<!-- End Main content -->


<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>
<link href="<?php echo TEMA; ?>css.old/plugins/toastr/toastr.min.css" rel="stylesheet">
<script src="<?php echo JS; ?>maskMoney.min.js"></script>
<script>
    var preco = 0;
    var time = 0;
    var saldo = 0;
    var regressor = null;
    var casaDecimal = 8;

    $(document).ready(function () {

        $("#cryptoFrom").select2();

        $("#cryptoFrom").on('select2:select', function (e) {
            $("#saldo_disponivel").html("");
            saldo = 0;
            casaDecimal = $("#cryptoFrom option:selected").attr("data-decimal");
            var data = $("#cryptoFrom").val();
            carregarSaldo(data);
        });


        var option = '';
        $.ajax({
            url: "<?php echo URLBASE_CLIENT . \Utils\Rotas::R_MERCADO_BALANCE ?>",
            method: "POST",
            dataType: 'json',
            success: function (json) {

                if (json.sucesso) {
                    json.moedas.forEach(element => {
                        option += '<option value="' + element.id_moeda + '" title="' + element.imagem + '" data-decimal="' + element.decimal + '">' + element.simbolo + ' - ' + element.nome + '</option>';
                    });
                    $('#cryptoFrom').html(option);
                    var nome = $( "#cryptoFrom option:selected" ).text().split("-");
                    $('.nome_moeda').html(nome[1]);
                    $(".crypto").select2({
                        templateResult: function (coin) {
                            var $span = $("<span><img style='width: 25px;' src=" + coin.title + " /> " + coin.text + "</span>");
                            return $span;
                        },
                        templateSelection: function (coin) {
                            var $span = $("<span><img style='width: 25px;' src=" + coin.title + " /> " + coin.text + "</span>");
                            return $span;
                        }
                    });

                    carregarSaldo($("#cryptoFrom").val());
                }
            }
        });
    });

    function carregarSaldo(moeda) {
        $('#nome_moeda').html("");
        var option = '';
        $.ajax({
            url: "<?php echo URLBASE_CLIENT . \Utils\Rotas::R_MERCADO_PARIDADES ?>",
            method: "POST",
            dataType: 'json',
            data: {
                moeda: moeda
            },
            success: function (json) {
                if (json.sucesso) {

                    json.moedas.forEach(element => {
                        option += '<option data-par="' + element.par + '" data-preco="' + element.preco + '" data-tipo="' + element.tipo + '" value="' + element.id_moeda + '" title="' + element.imagem + '">' + element.simbolo + ' - ' + element.nome + '</option>';
                    });
                    var nome = $( "#cryptoFrom option:selected" ).text().split("-");
                    $('.nome_moeda').html(nome[1]);
                    $(".crypto").select2({
                        templateResult: function (coin) {
                            var $span = $("<span><img style='width: 25px;' src=" + coin.title + " /> " + coin.text + "</span>");
                            return $span;
                        },
                        templateSelection: function (coin) {
                            var $span = $("<span><img style='width: 25px;' src=" + coin.title + " /> " + coin.text + "</span>");
                            return $span;
                        }
                    });
                }
                $("#saldo_disponivel").html(json.saldo_format);
                saldo = json.saldo;
            }
        });
    }

</script>
<?php Utils\Layout::append("mensage_text", $_data) ?>