<?php
$moeda = \Modules\principal\Controllers\Principal::getCurrency();

$saldo = isset($_data["saldo"]) ? $_data["saldo"] : "0,00000000";
$usuarios = isset($_data["usuarios"]) ? $_data["usuarios"] : Array();
$bancos = isset($_data["bancos"]) ? $_data["bancos"] : Array();
$p2p = isset($_data["p2p"]) ? $_data["p2p"] : new Models\Modules\Cadastro\P2pVenda();

//$p2p = new Models\Modules\Cadastro\P2pVenda();
?>


<?php Utils\Layout::append("inspina/metas", $_data) ?>

<?php Utils\Layout::append("inspina/scripts", $_data) ?>


<?php Utils\Layout::append("inspina/menu", $_data) ?>

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
            <div class="row wrapper border-bottom page-heading" style="background: linear-gradient(to right, #fff, <?php echo $moeda->mainColor ?>) !important;">
                <div class="col-lg-10">
                    <h2>P2P Compra / Venda</h2>
                    <ol class="breadcrumb" style="background-color: transparent !important;">
                        <li>
                            Serviços
                        </li>
                        <li class="active">
                            <strong>P2P Compra / Venda </strong>
                        </li>
                    </ol>
                </div>
            </div>

    <!-- Main content -->
    <section class="content">
        <br><br>
        
        <div class="row">
            <div class="col col-lg-12 text-center">
                
                <h3>Saldo em conta: <strong id="saldo-conta-p2p"><?php echo $saldo ?></strong></h3>
                
            </div>
        </div>
        
        <br><br><br>
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <?php Utils\Layout::append("mensagem", $_data)?>
                    
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        
                        <!--
                        <div class="row">
                            <div class="col col-xs-12 text-center">
                                <button type="button" class="btn btn-primary btn-lg" onclick="dialogRecargaCartao();">
                                    <i class="fa fa-dollar"></i> Faça Agora mesmo uma Recarga
                                </button>
                                <br><br>
                            </div>
                        </div>
                        -->
                        <form id="form-p2p" action="<?php echo URLBASE_CLIENT . Utils\Rotas::R_P2P_SALVAR ?>" method="post" enctype="multipart/form-data">
                            <input type="hidden" id="id" name="id" value="<?php echo $p2p->id ?>" />
                            <div class="row">
                                
                                <div class="col col-md-5">
                                    <div class="form-group">
                                        <label class="control-label">Nome do Cliente</label>
                                        <input type="text" id="nomeCliente" name="nomeCliente" class="form-control" value="<?php echo $p2p->nomeCliente ?>" />
                                    </div>
                                </div>
                                <div class="col col-md-4">
                                    <div class="form-group">
                                        <label class="control-label">Email do Cliente</label>
                                        <input type="email" id="emailCliente" name="emailCliente" class="form-control" value="<?php echo $p2p->emailCliente ?>" />
                                    </div>
                                </div>
                                <div class="col col-md-3">
                                    <div class="form-group">
                                        <label class="control-label">Telefone</label>
                                        <input type="text" id="telefone" name="telefone" class="form-control" value="<?php echo $p2p->telefone ?>" />
                                    </div>
                                </div>
                            </div>

                            
                            <div class="row">
                                <div class="col col-md-3">
                                    <div class="form-group">
                                        <label class="control-label">Tipo de Operação</label>
                                        <select class="form-control" id="tipoOperacao" name="tipoOperacao">
                                            <option value="<?php echo Utils\Constantes::ORDEM_COMPRA ?>" 
                                                <?php echo (Utils\Constantes::ORDEM_COMPRA == $p2p->tipoOperacao ? "selected = 'true'" : "")?> >Compra</option>
                                            <option value="<?php echo Utils\Constantes::ORDEM_VENDA ?>" 
                                                    <?php echo (Utils\Constantes::ORDEM_VENDA == $p2p->tipoOperacao ? "selected = 'true'" : "")?>>Venda</option>
                                        </select>
                                    </div>
                                </div>
                                
                                <div class="col col-md-3">
                                    <div class="form-group">
                                        <label class="control-label">Data da Operação</label>
                                        <input type="text" id="dataOperacao" name="dataOperacao" class="form-control" value="<?php echo ($p2p->dataOperacao != null ? $p2p->dataOperacao->formatar(\Utils\Data::FORMATO_PT_BR) : "") ?>" />
                                    </div>
                                </div>

                                <div class="col col-md-3">
                                    <div class="form-group">
                                        <label class="control-label">Tipo</label>
                                        <select class="form-control" id="tipoDeposito" name="tipoDeposito">
                                            <option value="<?php echo Utils\Constantes::TIPO_DEPOSITO_DOC ?>" 
                                                <?php echo (Utils\Constantes::TIPO_DEPOSITO_DOC == $p2p->tipoDeposito ? "selected = 'true'" : "")?> >DOC</option>
                                            <option value="<?php echo Utils\Constantes::TIPO_DEPOSITO_TED ?>" 
                                                    <?php echo (Utils\Constantes::TIPO_DEPOSITO_TED == $p2p->tipoDeposito ? "selected = 'true'" : "")?>>TED</option>
                                            <option value="<?php echo Utils\Constantes::TIPO_DEPOSITO_TEF ?>" 
                                                    <?php echo (Utils\Constantes::TIPO_DEPOSITO_TEF == $p2p->tipoDeposito ? "selected = 'true'" : "")?>>TEF</option>
                                            <option value="<?php echo Utils\Constantes::TIPO_DEPOSITO_DINHEIRO ?>" 
                                                    <?php echo (Utils\Constantes::TIPO_DEPOSITO_DINHEIRO == $p2p->tipoDeposito ? "selected = 'true'" : "")?>>Dinheiro</option>
                                        </select>
                                    </div>
                                </div>
                                
                                <div class="col col-md-3">
                                    <div class="form-group">
                                        <label class="control-label">Banco depositado</label>
                                        <select class="form-control" id="idBanco" name="idBanco">
                                            <option value="0" >Selecione o banco</option>
                                            <?php
                                            foreach ($bancos as $banco) {
                                            ?>
                                            <option value="<?php echo $banco->id ?>" 
                                                <?php echo ($banco->id == $p2p->idBanco ? "selected = 'true'" : "")?> ><?php echo $banco->nome ?></option>
                                            <?php
                                            }
                                            ?>
                                        </select>
                                    </div>
                                </div>
                            </div>


                            <div class="row">
                                <div class="col col-md-4">
                                    <div class="form-group">
                                        <label class="control-label">Valor Cotação</label>
                                        <input type="text" id="valorCotacao" name="valorCotacao" class="form-control" value="<?php echo number_format($p2p->valorCotacao, 2, ",", "") ?>" />
                                    </div>
                                </div>

                                <div class="col col-md-4">
                                    <div class="form-group">
                                        <label class="control-label">Volume BTC</label>
                                        <input type="text" id="volumeBtc" name="volumeBtc" class="form-control" value="<?php echo number_format($p2p->volumeBtc, 8, ",", "") ?>" />
                                    </div>
                                </div>
                                
                                <div class="col col-md-4">
                                    <div class="form-group">
                                        <label class="control-label">Valor</label>
                                        <input type="text" id="valor" name="valor" class="form-control" value="<?php echo number_format($p2p->valor, 2, ",", "") ?>" />
                                    </div>
                                </div>
                            </div>


                            <div class="row">
                                <div class="col col-md-5">
                                    <div class="form-group">
                                        <label class="control-label">Status</label>
                                        <select class="form-control" id="status" name="status">
                                            <option value="<?php echo Utils\Constantes::P2P_STATUS_PROCESSANDO ?>" 
                                                <?php echo (Utils\Constantes::P2P_STATUS_PROCESSANDO == $p2p->status ? "selected = 'true'" : "")?> >Processando</option>
                                            <option value="<?php echo Utils\Constantes::P2P_STATUS_NAO_CONFIRMADO ?>" 
                                                    <?php echo (Utils\Constantes::P2P_STATUS_NAO_CONFIRMADO == $p2p->status ? "selected = 'true'" : "")?>>Não Confirmado</option>
                                            <option value="<?php echo Utils\Constantes::P2P_STATUS_CONFIRMADO ?>" 
                                                    <?php echo (Utils\Constantes::P2P_STATUS_CONFIRMADO== $p2p->status ? "selected = 'true'" : "")?>>Confirmado</option>
                                            <option value="<?php echo Utils\Constantes::P2P_STATUS_CONCLUIDO ?>" 
                                                    <?php echo (Utils\Constantes::P2P_STATUS_CONCLUIDO == $p2p->status ? "selected = 'true'" : "")?>>Concluído</option>
                                        </select>
                                    </div>
                                </div>

                                <div class="col col-md-7">
                                    <div class="form-group">
                                        <label class="control-label">Operador</label>
                                        <select class="form-control" id="idUsuario" name="idUsuario">
                                            <?php foreach($usuarios as $usuario) { ?>
                                            <option value="<?php echo Utils\Criptografia::encriptyPostId($usuario->id) ?>" <?php echo ($usuario->id == $p2p->idUsuario ? "selected = 'true'" : "")?> ><?php echo $usuario->nome ?></option>
                                            <?php } ?>
                                        </select>
                                    </div>
                                </div>
                            </div>

                            <div class="row">


                                <div class="col col-md-6">
                                    <div class="form-group">
                                        <label class="control-label">Carteira</label>
                                        <input type="text" id="carteira" name="carteira" class="form-control" value="<?php echo $p2p->carteira ?>" />
                                    </div>
                                </div>

                                <div class="col col-md-6">
                                    <div class="form-group">
                                        <label class="control-label">Hash</label>
                                        <input type="text" id="hash" name="hash" class="form-control" value="<?php echo $p2p->hash ?>" />
                                    </div>
                                </div>


                            </div>

                        
                            <div class="row">
                                <div class="col col-md-6 text-center">
                                    <a href="<?php echo URLBASE_CLIENT . Utils\Rotas::R_P2P ?>servicos/p2p" class="btn btn-default" id="btnCancelar">
                                        Voltar
                                    </a>
                                </div>
                                <div class="col col-md-6 text-center">
                                    <button type="submit" class="btn btn-primary" id="btnSalvar">
                                        Salvar
                                    </button>
                                </div>
                            </div>
                            
                        </form>
                    </div>
                    <!-- /.panel-body -->

                </div>
            </div>

        </div>

        <a  id="openOrder" target="_BLANK"></a>
    </section>
    
    <div class="clearfix"></div>
</div>
<script>
    
        
    $(document).ready(function () {
        
        $("#valor").keydown(function (event) {
            $(this).val(currency($(this).val(), 2, 8, event.keyCode));
            event.preventDefault();
        });
        
        $("#valorCotacao").keydown(function (event) {
            $(this).val(currency($(this).val(), 2, 8, event.keyCode));
            calcularValor();
            event.preventDefault();
        });
        
        
        $("#volumeBtc").keydown(function (event) {
            $(this).val(currency($(this).val(), 8, 8, event.keyCode));
            calcularValor();
            event.preventDefault();
        });
        
        $("#tipoOperacao").change(function () {
            if ($(this).val() === "C") {
                $("#tipoDeposito, #idBanco").prop("disabled", true);
            } else {
                $("#tipoDeposito, #idBanco").prop("disabled", false);
            }
        });
        
        $("#dataOperacao").datepicker({format: "dd/mm/yyyy"}).mask("99/99/9999");
        
        $("#form-p2p").ajaxForm({
            dataType: "json",
            beforeSubmit: function () {
                $("#btnCancelar, #btnSalvar").prop("disabled", true);
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        
                        $("#saldo-conta-p2p").html(json.saldo);
                        clearScreen();
                        showNotyAlert(json.mensagem, "s");
                    } else {
                        showNotyAlert(json.mensagem, "e");
                    }
                } catch (e) {
                    showNotyAlert(e, "e");
                }
                $("#btnCancelar, #btnSalvar").prop("disabled", false);
            }
        });
        
        
        $("#tipoOperacao").trigger("change");
    });
    
    function calcularValor() {
        var cotacao = parseFloat($("#valorCotacao").val().length > 0 ? $("#valorCotacao").val().replace(",", ".") : 0);
        var volume = parseFloat($("#volumeBtc").val().length > 0 ? $("#volumeBtc").val().replace(",", ".") : 0);
        var valor = cotacao * volume;
        $("#valor").val(valor.toFixed(2).replace(".", ","));
    }
    
    function clearScreen() {
        $("#id").val("<?php echo Utils\Criptografia::encriptyPostId(0) ?>");
        $("#nomeCliente").val("");
        $("#emailCliente").val("");
        $("#telefone").val("");
        $("#dataOperacao").val("");
        $("#tipoDeposito").children("option").first().prop("selected", true);
        //$("#idBanco").val();
        $("#valor").val("0,00");
        $("#tipoOperacao").children("option").first().prop("selected", true);
        $("#valorCotacao").val("0,00");
        $("#volumeBtc").val("0,00000000");
        $("#status").children("option").first().prop("selected", true);
        //$("#idUsuario").val();
        $("#carteira").val();
        $("#hash").val();
        $("#tipoOperacao").trigger("change");
    }
    
</script>
<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>

