<?php
$moeda = Modules\principal\Controllers\Principal::getCurrency();

$moedas = (isset($_data["moedas"]) ? $_data["moedas"] : Array());
?>
<?php Utils\Layout::append("inspina/metas", $_data) ?>
<?php Utils\Layout::append("inspina/scripts", $_data) ?>
<?php Utils\Layout::append("inspina/menu", $_data) ?>
<div class="content-wrapper">
     <div class="row wrapper border-bottom page-heading" style="background: linear-gradient(to right, #fff, <?php echo $moeda->mainColor ?>) !important;">
        <div class="col-lg-10">
            <h2>Resumo de Contas</h2>
            <ol class="breadcrumb" style="background-color: transparent !important;">
                <li>
                    <a href="<?php echo Utils\Rotas::R_DASHBOARD ?>">Conta Corrente Empresa</a>
                </li>
                <li class="active">
                    <strong>Resumo de Clientes</strong>
                </li>
            </ol>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-lg-12">
            
            
            <div class="row">
                <div class="col col-lg-4">
                    <div class="form-group">
                        <label>Saldo Mínimo Reais</label>
                        <input type="text" class="form-control" id="filtroMinBrl" value="0,01" />
                    </div>
                </div>
                <div class="col col-lg-4">
                    <div class="form-group">
                        <label>Saldo Mínimo Currency</label>
                        <input type="text" class="form-control" id="filtroMinCurrency" value="0,00000001" />
                    </div>
                </div>
                <div class="col col-lg-4">
                    <div class="form-group">
                        <label>Filtro (nome do cliente)</label>
                        <input type="text" class="form-control" id="filtro" />
                    </div>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col col-lg-12 text-center">
                    <button onclick="filtrar();" type="button" class="btn btn-info">
                        Filtrar
                    </button>
                </div>
            </div>
            <br><br>
            <div class="row">
                <div class="col col-lg-12">

                    <div class="table-responsive" >
                    
                        <table class="table table-hover table-condensed table-responsive table-striped table-bordered">

                            <thead>
                                <tr>
                                    <th>Cliente</th>
                                    <th class="text-center" >R$</th>
                                    <?php 
                                    foreach ($moedas as $moeda) {
                                        ?>
                                    <th class="text-center" ><?php echo $moeda->simbolo ?></th>
                                        <?php
                                    }
                                    ?>
                                </tr>
                            </thead>

                            <tbody id="contas">

                            </tbody>


                            <tfoot>
                                <tr>
                                    <th><strong>Totais</strong></th>

                                    <th class="text-center" id="saldorealTotal">0,00</th>
                                    <?php 
                                    foreach ($moedas as $moeda) {
                                        ?>
                                    <th class="text-center" id="saldo<?php echo str_replace("$", "", $moeda->simbolo) ?>Total">0,00000000</th>
                                        <?php
                                    }
                                    ?>
                                </tr>
                            </tfoot>

                        </table>

                    </div>
                        
                </div>
            </div>
            
            <br><br><br>
            
            
            
            
            
        </div>
    </div>
   
    
    
    

<?php Utils\Layout::append("inspina/footer_esp", $_data) ?>


<?php Utils\Layout::append("mensage_text", $_data) ?>

<script>
    $(document).ready(function () {
        
        filtrar();
        
        $("#modalCobrancaValorCurrency, #filtroMinCurrency").keydown(function(event) {
            $(this).val(currency($(this).val(), 8, 8, event.keyCode));
            
            event.preventDefault();
        });
        
        $("#modalCobrancaValorBrl, #filtroMinBrl").keydown(function(event) {
            $(this).val(currency($(this).val(), 2, 8, event.keyCode));
            
            event.preventDefault();
        });
        
        
    });
    
    
    function filtrar() {
        $("#contas").html("<tr><td colspan='<?php echo "" . (sizeof($moedas) + 1)?>' class='text-center'><img src='<?php echo IMAGES ?>loading.gif' /></td></tr>");
        $.ajax({
            url: '<?php echo URLBASE_CLIENT . Utils\Rotas::R_CLIENTES_RESUMO_LISTARCONTAS ?>',
            method: 'post',
            dataType: 'json',
            data: {
                saldoMinBrl: $("#filtroMinBrl").val(),
                saldoMinCurrency:$("#filtroMinCurrency").val(),
                filtro: $("#filtro").val()
            },
            success: function (json) {
                try {
                    if (json.sucesso) {
                        $("#contas").html(json.html);
                        
                        var i = 0;
                        for (i = 0; i < json.saldos.length; i++) {
                            var m = json.saldos[i];
                            $("#saldo"+m.moeda+"Total").html(m.saldo);
                        }
                        
                    } else {
                        $("#contas").html("<tr><td colspan='<?php echo "" . (sizeof($moedas) + 1)?>' class='text-center'>"+json.mensagem+"</td></tr>");
                    }
                } catch (e) {
                    $("#contas").html("<tr><td colspan='<?php echo "" . (sizeof($moedas) + 1)?>' class='text-center'>"+e+"</td></tr>");
                }
            }
        });
    }
    
    
</script>